### ISSUE TITLE
Test Orchestrator for OpenSearch project

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/opensearch-build#107]
**Is your feature request related to a problem? Please describe.**
We need to build a test orchestrator for all repositories within OpenSearch to run tests and report them.

Tests we'd like to cover:
1. Unit
2. Precommit
3. DCO
4. Integration tests with out a test cluster infra
5. Integration tests with a test cluster infra
6. Performance tests
7. Upgrade tests.

We need 3 different pieces:

- [x] #109
- [x] #110
- [ ] #111

**Comment by peternied** [comment]
[Triage] @saratvemulapalli Is this issue still valid - seems like it can be closed out in favor of other issues around orchestration

**Comment by saratvemulapalli** [comment]
@peternied yes this could be closed and #111 is being tracked dedicatedly.
