### ISSUE TITLE
Create ServiceOpenSearchDashboards class to run Dashboards

### ISSUE THREAD

**Issue by tianleh** [opensearch-project/opensearch-build#1080]
### Is your feature request related to a problem? Please describe

part of #604

### Describe the solution you'd like

Similar to ServiceOpenSearch starting OpenSearch, ServiceOpenSearchDashboards shall be able to start OpenSearchDashboards

**Comment by tianleh** [comment]
Assume running integ test against local dir instead of public URL.

Currently OpenSearch tar is downloaded from the location specified by bundle manifest.
https://github.com/opensearch-project/opensearch-build/blob/main/src/test_workflow/integ_test/service_opensearch.py#L62

https://github.com/opensearch-project/opensearch-build/blob/main/src/test_workflow/dependency_installer.py#L51

Under `build` and `dist` dir, both OS and OSD are using the same file name for manifest. It is fine if we only want to run one of the services.

However, when we implement LocalTestClusterOpenSearchDashboards, there will be problems since we need both ServiceOpenSearchDashboards and ServiceOpenSearch. Thus their manifest files will need to exist together.

So, eventually we may need to change the manifest file names inside `build` and `dist` dir to allow co-existence.

This may not block this issue for now since I can assume the manifest is for OSD for now. But it will become needed when working on LocalTestClusterOpenSearchDashboards.

@dblock @seraphjiang @peterzhuamazon

**Comment by dblock** [comment]
> So, eventually we may need to change the manifest file names inside `build` and `dist` dir to allow co-existence.

Or those downloads can happen into two different (temporary) locations?

**Comment by tianleh** [comment]
> 

The issue is more about the bundle manifest to read the `location` of the tar instead of where to download them into.

Let's say I run build for both OS and OSD.
```
./build.sh manifests/1.2.0/opensearch-dashboards-1.2.0.yml
./build.sh manifests/1.2.0/opensearch-1.2.0.yml
```

Since the manifest.yml is the same name under folder `builds`, which build workflow runs later will wipe out the previous content.

Then assemble workflow `./assemble.sh builds/manifest.yml` will only assemble one of them.

Furthermore, assemble will generate manifest under folder dist which will have the same problem as build where the later assemble will override the previous one.

The rename task may be a prerequest for https://github.com/opensearch-project/opensearch-build/issues/1081 I plan to work on the rename as next step. 

@dblock @seraphjiang

**Comment by dblock** [comment]
I'd rather not mix outputs, so either we add `./build.sh --output-dir <path>` or default to `builds/opensearch` vs. `builds/opensearch-dashboards`.

**Comment by tianleh** [comment]
> 

Good suggestion! I will take this path "default to builds/opensearch vs. builds/opensearch-dashboards"

Created an issue to track the effort https://github.com/opensearch-project/opensearch-build/issues/1134
