### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by zealotous** [opensearch-project/opensearch-build#1083]
### Describe the bug

docker-compose.yml link is broken on https://hub.docker.com/r/opensearchproject/opensearch-dashboards
It points to 
https://github.com/opensearch-project/opensearch-build/blob/main/release/docker/dockercomposefiles/docker-compose.yml
but have to point to 
https://github.com/opensearch-project/opensearch-build/blob/main/docker/release/dockercomposefiles/docker-compose.yml

### To reproduce

Open https://hub.docker.com/r/opensearchproject/opensearch-dashboards
Follow docker-compose link

### Expected behavior

Correct link on docker hub

**Comment by peterzhuamazon** [comment]
Thanks @zealotous I have fixed the links for now.

Thanks.
