### ISSUE TITLE
Workflow Manager - Life cycle

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/opensearch-build#109]
- [ ] Investigate and Design - Figure out how to create orchestration workflow in Jenkins, how can multiple independent jobs be stitched under one id (and individual job ids), how can orchestration framework provide inputs for each jobs and trigger them, etc.
- [ ] Coordinate with build automation team to define Manifest .
- [ ] Build the orchestration layer that stitches together multiple independent jenkins jobs like integration, performance, upgrade testing. Publish logs to investigate failure scenarios

**Comment by setiah** [comment]
Updated w/ below sub-tasks

- [ ] Investigate and Design - Figure out how to create orchestration workflow in Jenkins, how can multiple independent jobs be stitched under one id (and individual job ids), how can orchestration framework provide inputs for each jobs and trigger them, etc.
- [ ] Coordinate with build automation team to define Manifest .
- [ ] Build the orchestration layer that stitches together multiple independent jenkins jobs like integration, performance, upgrade testing. Publish logs to investigate failure scenarios

**Comment by dblock** [comment]
What do we do with this issue @saratvemulapalli?

**Comment by saratvemulapalli** [comment]
Good question, @setiah I see most of these pieces are done except reporting the results and we have other issues to take care of that. 
Do you have anything else to cover here or could we close this down?

**Comment by peternied** [comment]
@saratvemulapalli Are you still working on this issue, or has this been rolled up into another change?

**Comment by saratvemulapalli** [comment]
This is rolled up to #262 and #263.
Will close this, thanks guys!
