### ISSUE TITLE
[RELEASE] Data Prepper 1.2.0 to Docker

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/opensearch-build#1106]
### Is your feature request related to a problem? Please describe

The Data Prepper team plans to release Data Prepper to Docker.

Planned release date: Dec 2, 2021.

### Describe the solution you'd like

We discussed this with @peterzhuamazon. Based on this discussion we plan to create a single script which will build Data Prepper, build the Docker image, and push to Docker Hub. The `docker-build` Jenkins job will be able to run this script with the necessary permissions to perform this push.

### Additional context

The Data Prepper work to create this change is:
https://github.com/opensearch-project/data-prepper/issues/623

**Comment by dlvenable** [comment]
Data Prepper will require Java 14 to build. Is this the JDK which the `docker-build` script uses?

**Comment by peterzhuamazon** [comment]
@dlvenable you guys can check whether this one runs
https://hub.docker.com/r/opensearchstaging/data-prepper/tags?page=1&name=1.2.0

One your code is ready we can push again.

https://github.com/opensearch-project/data-prepper/issues/623#issuecomment-983198370

**Comment by dlvenable** [comment]
@peterzhuamazon , We have confirmed that this works for log ingestion, but haven't gotten a trace analytics test case running yet. I don't see any reason why it won't work, but we can let you know if it does have an issue.

Regardless, we haven't yet tagged Data Prepper, so we will need to push another image.

**Comment by dlvenable** [comment]
@peterzhuamazon , We have confirmed that the OTel Trace source also works in that image. Our smoke testing is now complete.

We should be tagging the branch either today or Monday for a release on Tuesday, Dec 7.

**Comment by dlvenable** [comment]
This is now available.

https://hub.docker.com/r/opensearchproject/data-prepper/tags?page=1&ordering=last_updated&name=1.2.0
