### ISSUE TITLE
Create an account at packagist to publish

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/opensearch-build#1108]
Currently, the packagist package cannot update automatically, as it needs admin privileges to add a webhook into the repository. (https://packagist.org/about#how-to-update-packages).

Please create an opensearch-project accout.

**Comment by zelinh** [comment]
[Triage] @VijayanB This is not on our priority list now. @bbarani Can you add more details here?

**Comment by VijayanB** [comment]
@bbarani can you help us to create an account?

**Comment by bbarani** [comment]
@VijayanB We will look in to this request soon. I will keep you updated on the progress.

**Comment by gaiksaya** [comment]
Hi @VijayanB , can you please add more details to this issue?
Which repository does it concern?
What is the requirement of this change eg: release, regular updates, etc ?
Its unclear why we need this account and for what purpose.

Thanks!

**Comment by VijayanB** [comment]
It is for client: https://github.com/opensearch-project/opensearch-php

V1.0 is released by external contributor, who is the only admin ( account in pacifist) so far. We would like to have a user from opensearch-infra who can be admin as well.

**Comment by gaiksaya** [comment]
I see. Thanks. 
On quick search looks like this is what we have right now: https://packagist.org/packages/opensearch-project/opensearch-php
Will work on creating a user.
Thanks!

**Comment by bbarani** [comment]
Closing this issue as there is already a package published by the community : https://packagist.org/packages/opensearch-project/opensearch-php

**Comment by wbeckler** [comment]
Hi @gaiksaya I think you can still create a packagist account and then we can automate publishing php using that, as @shyim would add that account to our package.

**Comment by gaiksaya** [comment]
> Hi @gaiksaya I think you can still create a packagist account and then we can automate publishing php using that, as @shyim would add that account as a maintainer to our package.

Hi @wbeckler, just to confirm, once the packagist account is created, we can be added as maintainer to existing package and can release under the same namespace `opensearch-project` ?

**Comment by shyim** [comment]
@gaiksaya Yes

**Comment by gaiksaya** [comment]
Got it. Thanks! @bbarani Are you okay with this request? Any objection?

**Comment by gaiksaya** [comment]
Talked to @bbarani I'll move ahead with creating the account. Regarding creating the automation process please follow #3146

**Comment by gaiksaya** [comment]
We have created the new packagist account: https://packagist.org/users/opensearch/
Closing this issue!

**Comment by shyim** [comment]
I made him maintainer :+1:
