### ISSUE TITLE
[Bug]: assemble execution dowloads .tar.gz in the root directory instead of temp location

### ISSUE THREAD

**Issue by tianleh** [opensearch-project/opensearch-build#1109]
### Describe the bug

After running build and then assemble, `opensearch-1.2.0-linux-x64.tar.gz` will show up in `git status` This needs to be downloaded in a temp location.

Based on my research, the issue is here https://github.com/opensearch-project/opensearch-build/blob/main/src/assemble_workflow/dist.py#L76
### To reproduce

Run `./build.sh manifests/1.2.0/opensearch-1.2.0.yml`

Then run `./assemble.sh builds/manifest.yml`

**Comment by tianleh** [comment]
Initially we thought that it was caused by integ test script. But after checking out a clean workpsace, the tar file will show up in project root directory after build and assemble.

**Comment by tianleh** [comment]
Unassign it from myself since it is not related to CI test automation. 

Feel free to pick up this issue if anyone is interested to fix it. 

(I could potentially revisit this once CI test automation project is done)

**Comment by abhinavGupta16** [comment]
[triaged] I will look into this and try to reproduce this issue

**Comment by peterzhuamazon** [comment]
This is expected behavior and is not downloaded.
The `bundle.py` will invoke `dist.py` and one part of it is to build the bundle into root folder, then `shutil.copy` to dist folder.

This is expected while can be improve, not a blocker.
