### ISSUE TITLE
Add integ test execution as part of PR Github checks

### ISSUE THREAD

**Issue by tianleh** [opensearch-project/opensearch-build#1110]
### Is your feature request related to a problem? Please describe

Currently unit tests are executed as part of PR checks. https://github.com/opensearch-project/opensearch-build/tree/main/.github/workflows

We want to add integ test execution so that developers do not need to manually run it.

### Describe the solution you'd like

Integ test runs in PR check.

**Comment by dblock** [comment]
FYI we didn't include any actual OpenSearch tests in GHA in this project because of hardware requirements; those run in Jenkins jobs

**Comment by gaiksaya** [comment]
Closing this issue as we do not plan to run integration tests as part of GitHub CI checks.
