### ISSUE TITLE
Create a `results.yml` file after test run

### ISSUE THREAD

**Issue by owaiskazi19** [opensearch-project/opensearch-build#1113]
### Is your feature request related to a problem? Please describe

Coming from https://github.com/opensearch-project/opensearch-build/pull/1105#discussion_r754519093. After running `test.sh` for Integration , BWC or Performance Test `results.yml` should be created which will consist of platform, architecture, version and the location.

### Describe the solution you'd like

Generate a `results.yml` file which should have the content of `build.yml` and later can be loaded in `uploadTestResults` global variable to publish test results.

**Comment by dblock** [comment]
It could probably also include some summary of results or pointers to other files.

**Comment by owaiskazi19** [comment]
Summary of the test can be integrated using `TestResults`.

**Comment by gaiksaya** [comment]
We have a summary file called <component-name>.yml but it lives in 
```
https://ci.opensearch.org/ci/dbc/bundle-build/1.2.0/1127/linux/x64/test-results/10/<test-type>/<component-name>/<config>/test-results/<component-name>.yml
```
Maybe we can add those links as a part of https://github.com/opensearch-project/opensearch-build/blob/main/src/test_workflow/test_recorder/test_recorder.py#L39-L49

**Comment by peternied** [comment]
Closing this in favor of https://github.com/opensearch-project/opensearch-build/issues/1274
