### ISSUE TITLE
Develop a mechanism for each repo to create and use an account with permissions to ASM

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#112]
**Is your feature request related to a problem? Please describe.**

As part of https://github.com/opensearch-project/opensearch-build/issues/20, components need to be able to execute a GH workflow that assumes a role to fetch credentials from a central account via Amazon Secrets Manager and set these as an env variables. 

**Describe the solution you'd like**

- [ ] Document how accounts are setup
- [ ] Document how permissions are setup so that a role can be assumed during a GH workflow
- [ ] Document how to set credentials in ASM and what those credentials need to be, e.g. for access to Maven Central
- [ ] Document how to fetch credentials from ASM
- [ ] Provide a reference implementation of the above

**Comment by mch2** [comment]
Closing this as it is not needed with proposal #132
