### ISSUE TITLE
Record logs when Dashboards plugin integration test fails

### ISSUE THREAD

**Issue by joshuali925** [opensearch-project/opensearch-build#1124]
### Is your feature request related to a problem? Please describe

Currently we can see the video if a cypress test fails, but it is still difficult to debug if the UI doesn't show the root cause and we cannot reproduce the failure on our side. [An example](https://github.com/opensearch-project/opensearch-build/issues/1118#issuecomment-975995642), one cypress test failed with UI showing an object is not found while the same object is found before and after page load, and the test succeeded after rerun. It would be helpful to have some backend logs to debug.

### Describe the solution you'd like

Record OpenSearch and Dashboards logs as well, so we can determine and fix any flaky test or environment setup issue.

**Comment by gaiksaya** [comment]
We are now recording all logs for Dashboards plugins as a part of #1274
