### ISSUE TITLE
Publish JARs to Sonatype Staging

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#113]
**Is your feature request related to a problem? Please describe.**

As part of #20, provide a reference implementation to publish artifacts to Sonatype Staging from a GH workflow.

**Comment by mch2** [comment]
This is covered with [this](https://github.com/opensearch-project/opensearch-infra/blob/main/jenkins/jobs/OpenSearch_CI/release_ci/opensearch_maven_release/Jenkinsfile) workflow - closing.
