### ISSUE TITLE
Remove the word 'bundle' from artifact downloads link

### ISSUE THREAD

**Issue by bbarani** [opensearch-project/opensearch-build#1132]
### Is your feature request related to a problem? Please describe

The link to download OpenSearch artifacts contains the word 'bundle' in it instead of distribution

https://artifacts.opensearch.org/releases/bundle/opensearch/1.2.0/... 

### Describe the solution you'd like

Replace the word 'bundle' with 'distribution' and update the dependencies accordingly

https://artifacts.opensearch.org/releases/bundle/opensearch/1.2.0/...  to https://artifacts.opensearch.org/releases/distributions/opensearch/1.2.0/...

**Comment by abhinavGupta16** [comment]
[triaged] This issue needs to be groomed to checkout the scope of this task.

**Comment by bbarani** [comment]
Closing this issue as its more of a suggestion and not a must have feature. We can re-open it if any changes is needed on the artifact url.
