### ISSUE TITLE
Distinguish OpenSearch vs OpenSearchDashboards manifest file during build and assemble workflow

### ISSUE THREAD

**Issue by tianleh** [opensearch-project/opensearch-build#1134]
### Is your feature request related to a problem? Please describe

Currently both manifest files share the same name inside `builds` and `dist` folders. Thus they cannot co-exist. We want to have both together. This is motivated by #604

### Describe the solution you'd like

OpenSearch and OpenSearchDashboards manifest files could be distinguished and thus co-exist.

**Comment by dblock** [comment]
I'd rather not mix outputs, so either we add `./build.sh --output-dir <path>` or default to `builds/opensearch` vs. `builds/opensearch-dashboards`?

**Comment by tianleh** [comment]
I will follow "default to builds/opensearch vs. builds/opensearch-dashboards"
