### ISSUE TITLE
Release opensearch-java client 1.0.0 to maven

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/opensearch-build#1136]
Repo: https://github.com/opensearch-project/opensearch-java
Branch: 1.0.0 ( is still in progress )

Expected code freeze: Dec 15th 2021
Expected release date: Dec 20, 2021

**Comment by gaiksaya** [comment]
Hi @VijayanB What is the new expected release date for this? Can you update the issue with the same?
Thanks!

**Comment by bbarani** [comment]
Closing this issue as we have already released opensearch-java client to Maven. https://search.maven.org/artifact/org.opensearch.client/opensearch-java

**Comment by zelinh** [comment]
Closing this issue as OpenSearch-java 1.0.0 has been published to Maven Central. 
https://search.maven.org/artifact/org.opensearch.client/opensearch-java
