### ISSUE TITLE
Nightly bundle builds do not include full bundle until T-14 days to release.

### ISSUE THREAD

**Issue by mch2** [opensearch-project/opensearch-build#1140]
This is a suggestion to improve the release template and release cycle.

While performance testing for the 1.2 release we found a [performance degradation](https://github.com/opensearch-project/OpenSearch/issues/1560) in the bundle.  To try and diagnose the issue we pulled older nightly builds at various times and re-ran perf tests to identify when a degradation may have been introduced.  Ideally we would have these performance tests running nightly.  However, even when that is completed we will unfortunately be running against different configurations of the bundle because components are added to the manifest only [T-14 days](https://github.com/opensearch-project/opensearch-build/blob/main/.github/ISSUE_TEMPLATE/release_template.md#cicd---ends-release-minus-14-days) before release.

For example - right now for [2.0](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/2.0.0/opensearch-2.0.0.yml) and [1.3](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/1.3.0/opensearch-1.3.0.yml) releases, we have no components being built nightly other than OpenSearch. 

After every release we would have a functioning manifest for the next major and minor release that includes the known components at that time.  This will help us identify when an issue was introduced and will further aid us when we are running nightly benchmarks against the full bundle.

I have opened #1139 as a suggestion. An alternative here is we cut the release issue for the next release immediately on release day and ensure the manifest is updated right away.

**Comment by dblock** [comment]
We already have an issue for 1.3.0, but what we don't have is issues in every component. For that to happen we should have a release manager for 1.3.0 now (earlier) that can go do all that prep work.

**Comment by dblock** [comment]
I've updated the template to prepare for next development iteration in https://github.com/opensearch-project/opensearch-build/pull/1377 and it will kick off the process that together with https://github.com/opensearch-project/opensearch-build/issues/1375 will get us to produce the complete bundle a lot earlier. I'll close this because the latter captures the work to fix this specific problem (a dup).
