### ISSUE TITLE
[Bug]: Cannot build AL2 CI docker image

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/opensearch-build#1148]
### Describe the bug

Tried building AL2 CI docker image using the docker file: https://github.com/opensearch-project/opensearch-build/blob/main/docker/ci/dockerfiles/ci-runner.al2.dockerfile and is failed with below error:

```
ci-runner.al2.dockerfile:38
--------------------
  36 |     
  37 |     # Add k-NN Library dependencies
  38 | >>> RUN yum install epel-release -y && yum repolist && yum install openblas-static lapack -y
  39 |     RUN pip3 install cmake==3.21.3
  40 |     
--------------------
error: failed to solve: process "/bin/sh -c yum install epel-release -y && yum repolist && yum install openblas-static lapack -y" did not complete successfully: exit code: 1
```
We had [this PR](https://github.com/opensearch-project/opensearch-build/pull/821) up but looks like @jmazanec15 needs to do more research to fix this.

### To reproduce

Try to build the docker image using the above mentioned docker file

### Expected behavior

It should build successfully

**Comment by abhinavGupta16** [comment]
@jmazanec15 - Can you look into this?

**Comment by jmazanec15** [comment]
Taking a look at this. The problem I was facing is that I cannot install openblas-devel from epel on AL2 on ARM because the package requires libgfortran.so.3 and AL2 on arm comes with libgfortran.so.4. I will try to brainstorm solutions to this this week.

However, as the Dockerfile stands I was able to build image on x64.

**Comment by prudhvigodithi** [comment]
Hey I dont see we are using this al2 CI image anymore, please correct me if i'm wrong ? If so can we close this issue?
Dockerfiles: https://github.com/opensearch-project/opensearch-build/tree/main/docker/ci/dockerfiles/current
@bbarani @peterzhuamazon @gaiksaya

**Comment by peterzhuamazon** [comment]
This is not even an issue anymore it was a overlook at the time when we try to build knn on al2 and revert back to centos7.
Close now.
