### ISSUE TITLE
[Bug]: Docker build fails without security plugin

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#1154]
### Describe the bug

For 1.3.0 we don't have plugins (yet).

```
#25 [linux/arm64 linux_stage_0 5/8] RUN tar -xzpf /tmp/opensearch/opensearch-`uname -p`.tgz -C /usr/share/opensearch --strip-components=1 && rm -rf /tmp/opensearch &&     chmod 750 /usr/share/opensearch/plugins/opensearch-security/tools/* &&     mkdir -p /usr/share/opensearch/data && chown -R 1000:1000 /usr/share/opensearch/data
#25 CANCELED
------
 > [linux/amd64 linux_stage_0 5/8] RUN tar -xzpf /tmp/opensearch/opensearch-`uname -p`.tgz -C /usr/share/opensearch --strip-components=1 && rm -rf /tmp/opensearch &&     chmod 750 /usr/share/opensearch/plugins/opensearch-security/tools/* &&     mkdir -p /usr/share/opensearch/data && chown -R 1000:1000 /usr/share/opensearch/data:
#12 3.453 chmod: cannot access '/usr/share/opensearch/plugins/opensearch-security/tools/*': No such file or directory
------
opensearch.al2.dockerfile:34
--------------------
  33 |     COPY opensearch-*.tgz /tmp/opensearch/
  34 | >>> RUN tar -xzpf /tmp/opensearch/opensearch-`uname -p`.tgz -C $OPENSEARCH_HOME --strip-components=1 && rm -rf /tmp/opensearch && \
  35 | >>>     chmod 750 $OPENSEARCH_HOME/plugins/opensearch-security/tools/* && \
  36 | >>>     mkdir -p $OPENSEARCH_HOME/data && chown -R $UID:$GID $OPENSEARCH_HOME/data
  37 |     COPY opensearch-docker-entrypoint.sh opensearch-onetime-setup.sh $OPENSEARCH_HOME/
--------------------
error: failed to solve: process "/bin/sh -c tar -xzpf /tmp/opensearch/opensearch-`uname -p`.tgz -C $OPENSEARCH_HOME --strip-components=1 && rm -rf /tmp/opensearch &&     chmod 750 $OPENSEARCH_HOME/plugins/opensearch-security/tools/* &&     mkdir -p $OPENSEARCH_HOME/data && chown -R $UID:$GID $OPENSEARCH_HOME/data" did not complete successfully: exit code: 1
```

### To reproduce

Any CI build fails this way today.

### Expected behavior

Docker build should be skipped or produce some output just with OpenSearch core.

**Comment by gaiksaya** [comment]
I think we need to add conditional check to see if plugin is present before adding any config or performing any operations related to any plugin. Same thing applies to plugin related configurations in `opensearch-tar-install.sh` and any other kind of packaging scripts. [Example](https://github.com/opensearch-project/opensearch-build/blob/main/scripts/legacy/tar/linux/opensearch-tar-install.sh#L8-L21) 
cc: @zylzulu and @peterzhuamazon (working on rpm distribution)

**Comment by peterzhuamazon** [comment]
This is not fixed will open again.
1. @tianleh changes the folder structure of builds / dists and add opensearch / opensearch-dashboards subfolders in https://github.com/opensearch-project/opensearch-build/pull/1145. Therefore, the link to them needs to be updated as evidenced in Jenkins log that downloads never complete correctly due to wrong folder structure (243 size).
```

total 32
-rw-r--r-- 1 root root  285 Nov 29 17:08 log4j2.properties
-rw-r--r-- 1 root root  243 Nov 29 17:08 opensearch-aarch64.tgz
-rwxr-xr-x 1 root root 4422 Nov 29 17:08 opensearch-docker-entrypoint.sh
-rwxr-xr-x 1 root root 2171 Nov 29 17:08 opensearch-onetime-setup.sh
-rw-r--r-- 1 root root  243 Nov 29 17:08 opensearch-x86_64.tgz
-rw-r--r-- 1 root root  460 Nov 29 17:08 opensearch.yml
-rw-r--r-- 1 root root 1652 Nov 29 17:08 performance-analyzer.properties

......


 > [linux/amd64 linux_stage_0 5/9] RUN tar -xzpf /tmp/opensearch/opensearch-`uname -p`.tgz -C /usr/share/opensearch --strip-components=1 && rm -rf /tmp/opensearch &&     mkdir -p /usr/share/opensearch/data && chown -R 1000:1000 /usr/share/opensearch/data:
#12 0.097 
#12 0.097 gzip: stdin: not in gzip format
#12 0.097 tar: Child returned status 1
#12 0.097 tar: Error is not recoverable: exiting now
```

2. The `COPY` command is being changed to `cp` for mitigating PA not exist failure, but incorrectly assume the file is on the build container already, need to `COPY` the entire folder then `cp` with if statement for security and PA. https://github.com/opensearch-project/opensearch-build/pull/1162/files#r758593655

3. In @dblock #1133 it assumes the `opensearchstaging` user in docker hub is having a counterpart `opensearch-dashboardsstaging`, need to hard code this value to `opensearchstaging` for now. https://github.com/dblock/opensearch-build/blob/727c4edc67c48a11f87738d7a441dfefdfe110d6/vars/buildDockerImage.groovy#L28


Thanks.

**Comment by dblock** [comment]
> 3. In @dblock [Extract remaining common scripts. #1133](https://github.com/opensearch-project/opensearch-build/pull/1133) it assumes the `opensearchstaging` user in docker hub is having a counterpart `opensearch-dashboardsstaging`, need to hard code this value to `opensearchstaging` for now. https://github.com/dblock/opensearch-build/blob/727c4edc67c48a11f87738d7a441dfefdfe110d6/vars/buildDockerImage.groovy#L28

That's my bad. Maybe rename that use to something like `opensearch-build`?

**Comment by peterzhuamazon** [comment]
> > 3. In @dblock [Extract remaining common scripts. #1133](https://github.com/opensearch-project/opensearch-build/pull/1133) it assumes the `opensearchstaging` user in docker hub is having a counterpart `opensearch-dashboardsstaging`, need to hard code this value to `opensearchstaging` for now. https://github.com/dblock/opensearch-build/blob/727c4edc67c48a11f87738d7a441dfefdfe110d6/vars/buildDockerImage.groovy#L28
> 
> That's my bad. Maybe rename that use to something like `opensearch-build`?

Can you clarify what does `rename that use to something like opensearch-build` mean? A bit confused.
Thanks.

**Comment by dblock** [comment]
> > > 3. In @dblock [Extract remaining common scripts. #1133](https://github.com/opensearch-project/opensearch-build/pull/1133) it assumes the `opensearchstaging` user in docker hub is having a counterpart `opensearch-dashboardsstaging`, need to hard code this value to `opensearchstaging` for now. https://github.com/dblock/opensearch-build/blob/727c4edc67c48a11f87738d7a441dfefdfe110d6/vars/buildDockerImage.groovy#L28
> > 
> > 
> > That's my bad. Maybe rename that use to something like `opensearch-build`?
> 
> Can you clarify what does `rename that use to something like opensearch-build` mean? A bit confused. Thanks.

The user name "opensearchstaging" was confusing as I thought it related to the product opensearch vs. opensearch dashboards. A less ambiguous name could have been "opensearch-project-builder" for example.

**Comment by peterzhuamazon** [comment]
> > > > 3. In @dblock [Extract remaining common scripts. #1133](https://github.com/opensearch-project/opensearch-build/pull/1133) it assumes the `opensearchstaging` user in docker hub is having a counterpart `opensearch-dashboardsstaging`, need to hard code this value to `opensearchstaging` for now. https://github.com/dblock/opensearch-build/blob/727c4edc67c48a11f87738d7a441dfefdfe110d6/vars/buildDockerImage.groovy#L28
> > > 
> > > 
> > > That's my bad. Maybe rename that use to something like `opensearch-build`?
> > 
> > 
> > Can you clarify what does `rename that use to something like opensearch-build` mean? A bit confused. Thanks.
> 
> The user name "opensearchstaging" was confusing as I thought it related to the product opensearch vs. opensearch dashboards. A less ambiguous name could have been "opensearch-project-builder". Anyway this is minor.

Yeah this is just following up with `opensearchproject` production account format, similar to ODFE setup as well.

**Comment by peterzhuamazon** [comment]
Remember there is still a issue within docker entrypoint file https://github.com/tianleh/opensearch-build/blob/main/docker/release/config/opensearch/opensearch-docker-entrypoint.sh#L100-L131

It is expecting PA to exist so that if any of OpenSearch or PA failed to start or process TERM/EXIT the whole docker container will terminate.

@dblock please advice if we should make it run with and without PA, but that is a much bigger change.
The PR #1179 can ensure the docker build runs correctly, not docker run correctly.

Thanks.

**Comment by dblock** [comment]
Producing a docker image is problem 1), then producing a docker image which can start is 2). Open a bug for 2).
