### ISSUE TITLE
Create GHA Workflow Templates for Repositories

### ISSUE THREAD

**Issue by adnapibar** [opensearch-project/opensearch-build#116]
Each repository will maintain its own GHA CI scripts within its repository. This is similar to existing ODFE build with some changes.

**Common entry-points & templates**
We migrate build specific detail from these scripts into common CI agnostic entry-points similar to the integtest.sh proposal (Add plugin integration testing to the OpenSearch build workflow #58) already in place. In addition, infra provides a set of common GHA templates for each repository to use in their repositories that invokes these common entry-points.

These additional scripts be:

- **build.sh** wraps all steps required to build the artifact. If the repo is cloned locally this script should execute and produce an artifact without issue.
- **publish-snapshot.sh** wraps all steps required to publish a snapshot version to https://aws.oss.sonatype.org/content/repositories/snapshots/
- **publish-staging.sh** wraps steps required to publish a staging version to https://aws.oss.sonatype.org/content/repositories/staging.

Triggers would look something like:

- **On PR:** The repository runs a precommit workflow, which will build the code and run any relevant tests (via build.sh ). Since this is orchestrated by GitHub Actions (GHA), results and logs will be easily visible to the community.
- **On Merge:** The repository runs a CI workflow that invokes build.sh and then publish-snapshot.sh.
- **Workflow Dispatch:** Triggers a release workflow that invokes build.sh, integTest.sh, and publish-staging.sh.

**Comment by dblock** [comment]
Let's put scripts into some subfolders, e.g. `build/`.

**Comment by adnapibar** [comment]
> Let's put scripts into some subfolders, e.g. `build/`.
> 
> If most systems use the OpenSearch gradle system, then we shouldn't need more brittle scripts. Consider making things like `publish-snapshot.sh` optional and default to assuming that this is an OpenSearch plugin for example and run `./gradlew ...`.

The scripts are under `scripts` in the [.github](https://github.com/opensearch-project/.github) repo.  Do you have any other location in mind?

I don't see there is any way of enforcing these automatically, so individual repos may choose to ignore certain things. We can provide more clarify through the README though, what do you think?

**Comment by dblock** [comment]
> > Let's put scripts into some subfolders, e.g. `build/`.
> > If most systems use the OpenSearch gradle system, then we shouldn't need more brittle scripts. Consider making things like `publish-snapshot.sh` optional and default to assuming that this is an OpenSearch plugin for example and run `./gradlew ...`.
> 
> The scripts are under `scripts` in the [.github](https://github.com/opensearch-project/.github) repo. Do you have any other location in mind?

That works.

> I don't see there is any way of enforcing these automatically, so individual repos may choose to ignore certain things. We can provide more clarify through the README though, what do you think?

What I am trying to say is that we should provide default implementation for those scripts when they are not present. For 95% of the cases in order to onboard CI I should just be able to copy workflows and not add any shell scripts.
