### ISSUE TITLE
Automate pushing staging artifacts to production during release

### ISSUE THREAD

**Issue by bbarani** [opensearch-project/opensearch-build#1176]
### Is your feature request related to a problem? Please describe

We need to create an automated mechanism to migrate the artifacts generated in staging environment to production environment

### Describe the solution you'd like

All the staging artifacts generated should be migrated to production automatically. This includes daily build artifacts, distribution artifacts, native plugin/ plugin zips, docker artifacts.

- [ ] https://github.com/opensearch-project/opensearch-build/issues/1823
- [ ] https://github.com/opensearch-project/opensearch-build/issues/184
- [x] #716 
- [x] Publish Docker artifacts to production
- [ ] Publish distribution artifacts to production

**Comment by bbarani** [comment]
@prudhvigodithi @gaiksaya @peterzhuamazon Can we close this issue?

**Comment by gaiksaya** [comment]
I would say yes however, `This includes daily build artifacts` are not pushed today but are accessible via ci.opensearch.org
I don't think we need to push those to production. The issue title says during release which we have in place today. 
Thanks!
