### ISSUE TITLE
[Bug]: [bundle build]: Opensearch bundle build failed

### ISSUE THREAD

**Issue by abhinavGupta16** [opensearch-project/opensearch-build#1186]
### Describe the bug

Opensearch bundle build failed on jenkins. docker-build is failing

### To reproduce

Rebuild the `opensearch-bundle-build` job

**Comment by abhinavGupta16** [comment]
@peterzhuamazon is looking into this

**Comment by dblock** [comment]
This was fixed in https://github.com/opensearch-project/opensearch-build/pull/1179
