### ISSUE TITLE
Publish docker images to ghcr.io

### ISSUE THREAD

**Issue by viceice** [opensearch-project/opensearch-build#1198]
**Is your feature request related to a problem? Please describe.**
Docker hub has pull limits, ghcr.io not.

**Describe the solution you'd like**
Additionally publish the docker images to ghcr.io.

**Describe alternatives you've considered**
manually re-publish to ghcr

**Additional context**

no

**Comment by bbarani** [comment]
Hello @viceice we have published he Docker images to [ECR gallery](https://gallery.ecr.aws/opensearchproject?page=1) as well. Would that help you with overcoming pull limits?

**Comment by viceice** [comment]
probably yes, will test them the next days

**Comment by bbarani** [comment]
Closing this issue since we have published he Docker images to [ECR gallery](https://gallery.ecr.aws/opensearchproject?page=1) but feel free to re-open if you have any other questions.
