### ISSUE TITLE
[Design Discussion] s3 and roles structure for s3

### ISSUE THREAD

**Issue by abhinavGupta16** [opensearch-project/opensearch-build#1223]
Continuing the discussion from #1219, there is a requirement to upload Artifacts for various clients and opensearch on s3. This requires us to edit or create new roles and buckets on s3 to store the artifacts on s3.

We need to discuss and come up with the best possible design which is both scalable and easy to manage, so we can follow this procedure for future clients as they increase in number and also make changes for existing clients accordingly.

**Comment by peternied** [comment]
Here is a diagram for the existing process used to build OpenSearch, I think with some minor modifications to our process we can get any 'client' components to follow a nearly identical process.  With this in mind I don't think we need to alter our existing temp artifact storage story at all.

![image](https://user-images.githubusercontent.com/2754967/144479096-6689fa0f-0e08-439b-bc8f-e2a0f9e2042b.png)

---

![image](https://user-images.githubusercontent.com/2754967/144479929-cd52a288-7747-4291-8795-3673079e271c.png)

**Comment by bbarani** [comment]
@abhinavGupta16 Are we good to close this issue?

**Comment by gaiksaya** [comment]
Closing this issue as clients will have their own infrastructure.
