### ISSUE TITLE
Require test manifest path for running tests

### ISSUE THREAD

**Issue by tianleh** [opensearch-project/opensearch-build#1228]
### Is your feature request related to a problem? Please describe

#604

### Describe the solution you'd like

require test manifest path for running tests

**Comment by tianleh** [comment]
Also move the test manifest files from `src` to `manifests`

**Comment by dblock** [comment]
@tianleh No need to make new issues for things you're already working on :) less work for you

**Comment by tianleh** [comment]
> 

Thanks for the suggestion. I originally created this issue because the effort seemed non-trivial. Also I am keeping practicing my ability to realize such phased changes in advance. With such tracking (or "backfilling") exercise, I can always look back later as self retrospective of task breakdown when I need to create tasks for a group of engineers.

If it is the label "untriaged" which may attract the team' attention to groom the issue, I can quickly remove such label post creation.

**Comment by tianleh** [comment]
I have been maintaining the overall picture of the task breakdown in this issue https://github.com/opensearch-project/opensearch-build/issues/604 (scroll down a bit from the top)
