### ISSUE TITLE
Automate the RPM distribution builds validation

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#1244]
RPM distribution is really close (https://github.com/opensearch-project/opensearch-build/issues/1117), we need an automated way to validate that the constructed RPM image works.  This will make sure that we can catch any issues that prevent the components from being viable.

Note; this might require an additional realm of testing that we do not have today we should consider how we can best integrate this with our processes and make sure it is documented.

Acceptance criteria:
- Given an RPM with OpenSearch verify that the service operations

**Comment by zelinh** [comment]
[Triage] Line this issue to the META issue #27 .

**Comment by gaiksaya** [comment]
We have milestone 6 covered as a validation for RPM. Please see: https://github.com/opensearch-project/opensearch-build/issues/27
Closing this one as a duplicate
