### ISSUE TITLE
Need go 1.16 and goreleaser in dockerfiles

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/opensearch-build#1248]
In order to build and generate openserach-cli artifacts, docker should have following software
1. go 1.16 ( lower version will not work )
2. goreleaser from https://goreleaser.com/install/

This prerequisite to #833

**Comment by zelinh** [comment]
[Triage] Which dockerfile are you referring to?

**Comment by VijayanB** [comment]
The docker file which is used by Jenkins for automation

**Comment by bbarani** [comment]
@VijayanB Is this still a valid issue?

**Comment by gaiksaya** [comment]
Hi @VijayanB ,

As per new release model https://github.com/opensearch-project/opensearch-build/issues/1234 we won't be building anything but only releasing the artifacts. 
Closing this issue as prerequisite issue is also closed.
