### ISSUE TITLE
[RELEASE] Data Prepper 1.1.0 tar.gz artifacts

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/opensearch-build#1253]
### Is your feature request related to a problem? Please describe

The Data Prepper team would like to release Data Prepper 1.1.0 as tar.gz files. There are four tar.gz files for distribution:

* Linux
* Linux with JDK
* macOS
* macOS with JDK

Planned release date: Whenever possible. These artifacts are ready.

### Describe the solution you'd like

The Data Prepper contributors have built these artifacts and uploaded them to an S3 bucket. From there, we'd like the build team to copy and sign these artifacts with their existing signing infrastructure. Then the build team can make them available as public links.

Once the links are ready, the Data Prepper team can update the OpenSearch.org download documentation page to include them.

### Additional context

The Data Prepper work necessary for this change is:
opensearch-project/data-prepper#696

**Comment by zelinh** [comment]
[Triage] Data prepper team will need to attend infra's office hour and work with infra's oncall of the week to release tarball. They have changed the release date so this is not urgent.

**Comment by dlvenable** [comment]
@zelinh , Yes, this release is not urgent. It may also serve as a good test bed for releasing Data Prepper 1.2.0 as a tar.gz.

**Comment by dlvenable** [comment]
Data Prepper 1.1.1 uses log4j 2.15.0. Data Prepper is using log4j 2.16.0 which fixes an important CVE. Because of this, we are going to pass on creating a 1.1.x tar.gz artifact, and only release 1.2.0. Thus, I'm closing this issue.
