### ISSUE TITLE
Add guides for scenario 'component is not shipping'

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#1255]
In our component issues it can be confusing what you should be doing if a given component is opting not to be included in a release.  Document exactly what they should do to be removed.

Acceptance Criteria:
- Updated 'How to use this issue' section with instructions in the [release_template.md](https://github.com/opensearch-project/opensearch-build/blame/main/meta/templates/releases/release_template.md#L3).

**Comment by bbarani** [comment]
@abhinavGupta16 Can we document this as part of release template changes as well?

**Comment by bbarani** [comment]
Closing this issue as the release template has been update with the appropriate instruction.
