### ISSUE TITLE
Add documentation for how a new component should be added

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#1256]
We have some documentation on how to onboard, lets make sure that documentation properly handles how to onboard during the preparation phase when a release ticket has already been created.

Acceptance Criteria:
- Review and update the documentation

**Comment by gaiksaya** [comment]
We have the documentation for component onboarding https://github.com/opensearch-project/opensearch-build/blob/main/ONBOARDING.md#onboard-to-build-workflow
