### ISSUE TITLE
Document the end-to-end OpenSearch release process

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#1258]
There are elements of the release process that are still vague, such as 'publish results'.  These actions should have clearly defined steps so they are repeatable and transparent to the community.

Acceptance criteria:
- Review https://github.com/opensearch-project/opensearch-build/issues/567, document gaps that need coverage, add them to this list.
- Work through the list, create follow up tasks for items that need additional consideration or community involvement.

Gaps:
- [ ] How to verify components have completed Preparation/Development/Release Testing/Release/Post Release
- [ ] How to pick a release candidate build
- [ ] How to generate release notes
- [ ] How to perform artifact signing
- [ ] How to release to maven
- [ ] How to release native plugins
- [ ] How to execute integration tests for final sign off
- [ ] How to publish integration test results
- [ ] How to publish performance test results
- [ ] How to publish docker images
- [ ] How to publish blog posts
- [x] How to get help on a critical issue
- [x] How to conduct a retrospective
- [x] How to correct mistakes
- [x] ~How to verify version label creation~ _This isn't needed if the release owner drives the process_

**Comment by bbarani** [comment]
@abhinavGupta16 can you please also include the above list to https://github.com/opensearch-project/opensearch-build/issues/1257?

**Comment by bbarani** [comment]
This is being tracked as part of this [PR](https://github.com/opensearch-project/opensearch-build/blob/1499c472fec3d36bc0d3b30ffca8b08bb5a65c4d/RELEASE_PROCESS_OPENSEARCH.md#post-release)
