### ISSUE TITLE
[Enhancement]Multi-Region Failover for S3 and enable Versions for duplicates

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#1267]
### Is your feature request related to a problem? Please describe

Due to IAD failure today we are not able to build 1.1.1 bundle for testing, which is scheduled to be completed today.
https://github.com/opensearch-project/opensearch-build/issues/870

![Screen Shot 2021-12-07 at 2 22 42 PM](https://user-images.githubusercontent.com/65193828/145092862-11fdf39d-37fc-480c-a9fb-ef968c1fab2c.png)

```
urllib.error.HTTPError: HTTP Error 500: Internal Server Error
```

```

$ wget https://ci.opensearch.org/ci/dbc/bundle-build/1.1.0/20210930/linux/x64/builds/opensearch/plugins/opensearch-notebooks-1.1.0.0.zip
--2021-12-07 14:06:31--  https://ci.opensearch.org/ci/dbc/bundle-build/1.1.0/20210930/linux/x64/builds/opensearch/plugins/opensearch-notebooks-1.1.0.0.zip
Resolving ci.opensearch.org (ci.opensearch.org)... 18.67.76.79, 18.67.76.20, 18.67.76.9, ...
Connecting to ci.opensearch.org (ci.opensearch.org)|18.67.76.79|:443... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2021-12-07 14:06:33 ERROR 500: Internal Server Error.
```

 We also did not enable versions on S3 bucket of dev Jenkins, thus it is possible to delete artifact without recovery possibilities.

### Describe the solution you'd like

1. Make sure we have multi-region failover/replication for our S3 buckets on dev Jenkins.
2. Make sure versions are enabled for these buckets.
3. Make sure these S3 bucket has delete protection enabled.

......more

**Comment by peterzhuamazon** [comment]
cc: @bbarani

**Comment by bbarani** [comment]
@peterzhuamazon Is this still a valid issue with our Public Jenkins infrastructure?

**Comment by peterzhuamazon** [comment]
* 20231024: 2PR with Jeff to setup release artifacts s3 bucket replication rules.

**Comment by peterzhuamazon** [comment]
After talking to @gaiksaya it seems the staging buckets are hosting majority of the build artifacts, which later get turned into either RC or release artifacts, and eventually goes to production bucket.

Therefore, we are reducing the priority of next set of task on the staging bucket backup, as it requires cdk changes in the code. The prod bucket is backed up and have versioning with replication rules already.

Thanks.

**Comment by gaiksaya** [comment]
Looking at the above comment, staging repo does not need replication as of today. If required, please create new issue.
Closing this issue for now as Prod bucket is backed up with replication rules in place.
Thanks!
