### ISSUE TITLE
check-for-build job always sent failure notification if child job fails

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#1285]
This notification should only happen if there is an internal error, maybe there is a different error we can check for?  https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/check-for-build.jenkinsfile#L75

Acceptance Criteria:
We should only see failure notifications if there is an error generated inside of this job, not any child jobs.

**Comment by zelinh** [comment]
Closing this since the issue should have been resolved.
