### ISSUE TITLE
[Bug]Patch bundle tar has min version number

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#1286]
### Describe the bug

The 1.1.1 bundle tarball, once you extract it, will show 1.1.0 version in the folder name.
This is because the 1.1.1 bundle is using 1.1.0 min, thus does not change the folder name accordingly.

```

drwxr-xr-x  9 zhujiaxi amazon      4096 Dec  9 23:09 opensearch-dashboards-1.1.0-linux-x64
-rw-r--r--  1 zhujiaxi amazon 201750620 Dec  9 23:11 opensearch-dashboards-1.1.1-linux-x64.tar.gz
```

### To reproduce

Download any of the OpenSearch or Dashboards bundle for 1.1.1 then extract it.

https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/1.1.1/8/linux/x64/dist/opensearch/opensearch-1.1.1-linux-x64.tar.gz
https://ci.opensearch.org/ci/dbc/distribution-build-opensearch-dashboards/1.1.1/7/linux/x64/dist/opensearch-dashboards/opensearch-dashboards-1.1.1-linux-x64.tar.gz

### Expected behavior

The internal folder within the tarball should have the same version as the one in tarball name.

**Comment by tianleh** [comment]
The version/folder name mismatch is failing the integration test since there is logic to look for the executable inside the extracted folder.
