### ISSUE TITLE
Clean up distribution.py to be class based

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#1289]
Following up feedback on https://github.com/opensearch-project/opensearch-build/pull/1288

Acceptance criteria:
- To be consistent I would make this a class called Distribution that takes a base url and product name in the constructor, then add a find method.
- Check that the exception is a 403 or 404, fail on everything else.
- Add unit tests

**Comment by rishabh6788** [comment]
This has already been implemented. Closing.
