### ISSUE TITLE
Automate performance testing for OpenSearch

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/opensearch-build#129]
Create automated jobs to run performance testing

**Comment by camerski** [comment]
Implement a `PerformanceTestSuite` class and wire it in to `test.py`. This could be similar to `IntegTestSuite` if we need per-component performance tests, or it could be a bundle-level thing. In any case, the interface should be similar: Accept a test cluster endpoint, return when the tests are finished, report results in some sensible fashion.

See https://github.com/opensearch-project/opensearch-build/blob/main/bundle-workflow/python/test.py and https://github.com/opensearch-project/opensearch-build/blob/main/bundle-workflow/python/test_workflow/integ_test_suite.py

**Comment by peternied** [comment]
See https://github.com/opensearch-project/opensearch-build/issues/583 for the remaining work, http://jenki-jenki-fpgmrv2ryxko-1366042710.us-east-1.elb.amazonaws.com/job/perf-test/ is failing, but exists

**Comment by owaiskazi19** [comment]
> > This work has been completed, there are bugs and follow up tasks associated with the actual work
> 
> We have not integrated the performance testing with jenkins yet! @owaiskazi19 correct me if I am wrong.

That's correct. We have not integrated perf test with jenkins

**Comment by kotwanikunal** [comment]
Taking a look into this issue.
