### ISSUE TITLE
[RELEASE] Release version 1.2.1

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#1290]
## Release OpenSearch and OpenSearch Dashboards 1.2.1

This is an out of band release, it will follow the release process but normal steps will be abbreviated 

### Preparation

- [x] Assign this issue to a release owner.
- [x] Document any new quality requirements or changes.
- [x] [Create a version label](https://github.com/opensearch-project/opensearch-plugins/blob/main/META.md#create-or-update-labels-in-all-plugin-repos) in each component repo for this, and the next minor release.
- [x] Confirm that OpenSearch-Dashboards does not need an updated manifest

### Development

- [x] OpenSearch core has update for 1.2.1
- [x] Security has update for 1.2.1
- [x] common-utils https://github.com/opensearch-project/common-utils/pull/103
- [x] job-scheduler https://github.com/opensearch-project/job-scheduler/pull/108
- [x] alerting https://github.com/opensearch-project/alerting/pull/255
- [x] asynchronous-search https://github.com/opensearch-project/asynchronous-search/pull/77
- [x] index-management https://github.com/opensearch-project/index-management/pull/222
- [x] k-NNhttps://github.com/opensearch-project/k-NN/pull/241
- [x] security https://github.com/opensearch-project/security/pull/1518
- [x] performance-analyzer https://github.com/opensearch-project/performance-analyzer/pull/87
- [x] anomaly-detection https://github.com/opensearch-project/anomaly-detection/pull/327
- [x] cross-cluster-replication https://github.com/opensearch-project/cross-cluster-replication/pull/266
- [x] sql https://github.com/opensearch-project/sql/pull/325
- [x] dashboards-reports https://github.com/opensearch-project/dashboards-reports/pull/253
- [x] opensearch-observability https://github.com/opensearch-project/trace-analytics/pull/317
- [x] Make pull requests to add each component to [manifests/1.2.1/opensearch-1.2.1.yml](/opensearch-project/opensearch-build/tree/main/manifests/1.2.1/opensearch-1.2.1.yml) https://github.com/opensearch-project/opensearch-build/pull/1299
- [x] All components have been updated (+1 hour)
- [x] Declare a release candidate build
- [x] Create an issue publish all test results.  (+1.5 hour)
  - [X] Performance tests, tracked on this issue
  - [x] Integration tests, tracked on this issue
- [x] Verify all issued labeled `v1.2.1` in all projects have been resolved.
- [x] Complete [documentation](https://github.com/opensearch-project/documentation-website) for this release.
- [x] Maven release (+1 hour)
    * https://github.com/opensearch-project/opensearch-infra/pull/139
    * https://github.com/opensearch-project/opensearch-infra/pull/140
    * https://github.com/opensearch-project/opensearch-infra/pull/141
- [x] Native plugins release
- [x] Publish Docker images (+.5 hour) 
- [x] Author [blog post](https://github.com/opensearch-project/project-website) for this release.
- [x] Gather, review and publish release notes. [git-release-notes](https://github.com/ariatemplates/git-release-notes) may be used to generate release notes from your commit history.
- [x] Publish this release on [opensearch.org](https://opensearch.org/downloads.html).
- [x] Publish forum posts - release is launched!
- [x] Publish [blog post](https://github.com/opensearch-project/project-website) - release is launched!

### Post Release

- [x] Create [release tags](https://github.com/opensearch-project/.github/blob/main/RELEASING.md#tagging) for each component.
- [x] Replace refs in [manifests/1.2.1](/opensearch-project/opensearch-build/tree/main/manifests/1.2.1) with tags.
- [x] Update [this template](https://github.com/opensearch-project/opensearch-build/blob/main/.github/ISSUE_TEMPLATE/release_template.md) with any new or missed steps.
- [ ] Conduct a retrospective, and publish its results. https://github.com/opensearch-project/opensearch-build/issues/1314

**Comment by peternied** [comment]
We need to rev all version number, will be adding a new checklist for all the version to be rebuild

**Comment by peternied** [comment]
### Release candidate testing instructions
- Use Docker-Compose to setup a cluster
  + Download this [gist](https://gist.github.com/peternied/f693b9230ba68f9d7b9a26a8e6c097b8) as docker-compose.yml on your machine
  + Get latest image versions `docker-compose pull`
  + Start the cluster `docker-compose up`

- [OpenSearch docker](https://hub.docker.com/r/opensearchstaging/opensearch/tags?page=1&name=1.2.1) 
  + Start without security
     - Docker command `docker pull opensearchstaging/opensearch:1.2.1 && docker run -it -p 9200:9200 -e "discovery.type=single-node" -e "DISABLE_SECURITY_PLUGIN=true" opensearchstaging/opensearch:1.2.1`
    - Connect command `curl https://localhost:9200`
  + Start with security
    - Docker command `docker pull opensearchstaging/opensearch:1.2.1 && docker run -it -p 9200:9200 -e "discovery.type=single-node" opensearchstaging/opensearch:1.2.1`
    - Connect command `curl --insecure https://admin:admin@localhost:9200`

- Use TARs to deploy OpenSearch Manually (Updated 2021/11/22 11:00 PST)
  + OpenSearch - Build 1127
    * x64 [[manifest](https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/1.2.1/53/linux/x64/dist/opensearch/manifest.yml)] [[tar](https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/1.2.1/53/linux/x64/dist/opensearch/opensearch-1.2.1-linux-x64.tar.gz)]
    * arm64 [[manifest](https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/1.2.1/53/linux/arm64/dist/opensearch/manifest.yml)] [[tar](https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/1.2.1/53/linux/arm64/dist/opensearch/opensearch-1.2.1-linux-arm64.tar.gz)]

From [Docker Release](https://github.com/opensearch-project/opensearch-build/tree/main/docker/release)

**Comment by peternied** [comment]
Performance testing has been triggered, tracking numbers for the results.
- 5453d4e4-9f6c-439a-be0c-09878412905c
- 296bec5f-1b35-46c7-b9cd-2dc370546583
- 17ee8f29-e0b9-4a4e-b309-653adead9671
- 62ed636e-3a3b-48a8-9f5f-a1da78348c50

**Comment by peternied** [comment]
### Integration testing kicked off - results will come tomorrow
```
./test.sh integ-test manifests/1.3.0/opensearch-1.3.0-test.yml --paths opensearch=https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/1.2.1/53/linux/x64

./test.sh integ-test manifests/1.3.0/opensearch-1.3.0-test.yml -paths opensearch=https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/1.2.1/53/linux/arm64
```

**Comment by peternied** [comment]
Needed to work around an upload issue for https://github.com/opensearch-project/opensearch-build/issues/1261 RC artifacts have been uploaded

**Comment by peterzhuamazon** [comment]
![Screen Shot 2021-12-11 at 2 03 57 PM](https://user-images.githubusercontent.com/65193828/145688527-3c0d981a-de56-4b64-9bc4-23a7162748cf.png)


Maven up: https://aws.oss.sonatype.org/content/repositories/releases/org/opensearch/opensearch/1.2.1/

Waiting for sync from the central: https://repo1.maven.org/maven2/org/opensearch/opensearch/1.2.1/

**Comment by peterzhuamazon** [comment]
All tar are pushed to production bucket.

**Comment by peterzhuamazon** [comment]
Native plugins live:
```
% ./bin/opensearch-plugin install repository-s3
-> Installing repository-s3
-> Downloading repository-s3 from opensearch
[=================================================] 100%
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.lang.RuntimePermission accessDeclaredMembers
* java.lang.RuntimePermission getClassLoader
* java.lang.reflect.ReflectPermission suppressAccessChecks
* java.net.SocketPermission * connect,resolve
* java.util.PropertyPermission opensearch.allow_insecure_settings read,write
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.

Continue with installation? [y/N]y
-> Installed repository-s3 with folder name repository-s3
```

**Comment by peterzhuamazon** [comment]
Docker up:
https://hub.docker.com/r/opensearchproject/opensearch/tags
```
$ curl https://localhost:9200/ -u admin:admin --insecure
{
  "name" : "opensearch-node1",
  "cluster_name" : "opensearch-cluster",
  "cluster_uuid" : "teJylxlBQVKqXt_doKdSxQ",
  "version" : {
    "distribution" : "opensearch",
    "number" : "1.2.1",
    "build_type" : "tar",
    "build_hash" : "e3a44fa71b290fb265a94ef4297f044b9a63a762",
    "build_date" : "2021-12-11T04:24:30.324011Z",
    "build_snapshot" : false,
    "lucene_version" : "8.10.1",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "The OpenSearch Project: https://opensearch.org/"
}
$ curl https://localhost:9200/_cat/plugins -u admin:admin --insecure
opensearch-node2 opensearch-alerting                  1.2.1.0
opensearch-node2 opensearch-anomaly-detection         1.2.1.0
opensearch-node2 opensearch-asynchronous-search       1.2.1.0
opensearch-node2 opensearch-cross-cluster-replication 1.2.1.0
opensearch-node2 opensearch-index-management          1.2.1.0
opensearch-node2 opensearch-job-scheduler             1.2.1.0
opensearch-node2 opensearch-knn                       1.2.1.0
opensearch-node2 opensearch-observability             1.2.1.0
opensearch-node2 opensearch-performance-analyzer      1.2.1.0
opensearch-node2 opensearch-reports-scheduler         1.2.1.0
opensearch-node2 opensearch-security                  1.2.1.0
opensearch-node2 opensearch-sql                       1.2.1.0
opensearch-node1 opensearch-alerting                  1.2.1.0
opensearch-node1 opensearch-anomaly-detection         1.2.1.0
opensearch-node1 opensearch-asynchronous-search       1.2.1.0
opensearch-node1 opensearch-cross-cluster-replication 1.2.1.0
opensearch-node1 opensearch-index-management          1.2.1.0
opensearch-node1 opensearch-job-scheduler             1.2.1.0
opensearch-node1 opensearch-knn                       1.2.1.0
opensearch-node1 opensearch-observability             1.2.1.0
opensearch-node1 opensearch-performance-analyzer      1.2.1.0
opensearch-node1 opensearch-reports-scheduler         1.2.1.0
opensearch-node1 opensearch-security                  1.2.1.0
opensearch-node1 opensearch-sql                       1.2.1.0
```

**Comment by peternied** [comment]
The 1.2.1 release is live everywhere!
