### ISSUE TITLE
Consolidate code that locates a distribution in DependencyInstaller

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#1309]
### Is your feature request related to a problem? Please describe

Coming from https://github.com/opensearch-project/opensearch-build/pull/1308#discussion_r767182142, consolidate how we find a distribution URL from multiple places.

### Describe the solution you'd like

Consolidate how we find a distribution URL from multiple places.

**Comment by zelinh** [comment]
[Triage] Which comments are you referring to?

**Comment by bbarani** [comment]
@dblock Can you provide more context on this issue? Is the expectation to host consolidated list of distribution URL's that can be used by everyone (including distribution downloader)?

**Comment by dblock** [comment]
This ask was to refactor some internal code so that we don't do the same logic in two places. It's going to sit here for a long time occupying space, so let's just close it.
