### ISSUE TITLE
[Retrospective] Release 1.2.1

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#1314]
### How to use this issue?
Please add comments to this issue, they can be small or large in scope.  Honest feedback is important to improve our processes, suggestions are also welcomed but not required.

### What will happen to this issue post release?
There will be a discussion(s) about how the release went and how the next release can be improved.  Then this ticket will be updated with the notes of that discussion along side action items.

**Comment by peternied** [comment]
💯 Super fast turnaround from all the teams, heroic!

**Comment by peternied** [comment]
Started with the patch release process so that components did not need to be updated.  This process had quirks, initially tried to work through it but got blocked on https://github.com/opensearch-project/OpenSearch/issues/1707 Had to pivot mid-process to have all component teams rev their version numbers

**Comment by peternied** [comment]
When all component terms were reving their version numbers they needed a snapshot build with dependencies included to pass CI systems.  This causes several false starts first with common-utils, then job scheduler, then alerting, +3 hours in delays on the build.

**Comment by peternied** [comment]
Our Jenkins build environment became unstable in the middle of the release.  This might be related to a bad java install on the hosts, but it is unclear how that happened any why recovery only occurred after restarting the entire system.  We didn't have good  telemetry on these failures other than seeing failed builds.

Also did not have a good work around other than to get the environment functional again.  Highlighting how important deploying new Jenkins stamps could be in the future when we have more jobs running on a cluster or illustrating that we need to isolate functionality between them

**Comment by dblock** [comment]
We did not know/remember that 1.2.0 plugins won't be able to start on 1.2.1 core, so the initial patch version didn't work at all.

**Comment by elfisher** [comment]
We need to think through how to make the distribution update process simple for users so that when important upgrades come out it is super simple to adopt the new version.

**Comment by dvonlehman** [comment]
We install opensearch on our local development machines using homebrew. In order for the homebrew formulae to be updated for version 1.2.1 it seems like a new release needs to be published to github. 

```rb
url "https://github.com/opensearch-project/OpenSearch/archive/1.2.0.tar.gz"
sha256 "d140f90849e73e14a64767e0cbe029d8e54d00d3cc70a13681766e2739e77121"
```
https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/opensearch.rb#L4 

When might we expect the `1.2.1.tar.gz` to be available?

Thanks for addressing the log4j vulnerability so quickly!

**Comment by peternied** [comment]
> When might we expect the `1.2.1.tar.gz` to be available?

@dvonlehman There is published version of 1.2.1 available off of the [release page](https://github.com/opensearch-project/OpenSearch/releases/tag/1.2.1), here is a link to the [tar.gz](https://github.com/opensearch-project/OpenSearch/archive/refs/tags/1.2.1.tar.gz) of the source.  Is there a kind of integration that would make detecting / updating for new versions easier?

**Comment by dvonlehman** [comment]
@peternied I'm specifically interested in installing version 1.2.1 (the one that includes the log4j update) on a mac using homebrew. I was able to submit a version bump PR to the homebrew repo with the new OpenSearch release: https://github.com/Homebrew/homebrew-core/pull/91468

**Comment by dblock** [comment]
Oh wow, that builds and runs the software from source, none of this is really released software per-se. But it does work ... If you just want to patch that use the distribution from the 1.2.2 tag, https://github.com/opensearch-project/OpenSearch/releases/tag/1.2.2

**Comment by peternied** [comment]
See https://github.com/opensearch-project/opensearch-build/issues/880#issuecomment-1006130147 for the summary across all 1.2.0-1.2.3 retros.
