### ISSUE TITLE
[Dashboards] Upgrade to Node 14

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/opensearch-build#1320]
This is blocked by: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/920

### Is your feature request related to a problem? Please describe

Add Node 14 for OpenSearch Dashboards when is merged. We are working [here](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/920) to upgrade OpenSearch Dashboards to Node 14.

### Describe the solution you'd like

We will need to update the build process to support the node upgrade. I believe the CI runner docker images will need to be updated: https://github.com/opensearch-project/opensearch-build/tree/4107aaa25714371b63708e08e6b5485231adc312/docker/ci/dockerfiles.

Along with publishing it to Dockerhub to be picked up and used by the pipeline.

**Comment by boktorbb-amzn** [comment]
Upgraded Node version to 14.18.2 in #1350

**Comment by boktorbb-amzn** [comment]
The opensearch-build repo will need to create a new docker image with the proper Node version (14.18.2) before we can merge the Dashboards Node 14 PR

**Comment by kavilla** [comment]
Will need to update the jenkinsfile to consume the correct docker image.
