### ISSUE TITLE
[Docker] whitelist sysctl call 

### ISSUE THREAD

**Issue by tianleh** [opensearch-project/opensearch-build#1321]
### Is your feature request related to a problem? Please describe

Due to large size of the project, as a developer, we may need to increase this param

`fs.inotify.max_user_watches=524288`  per VS Code guideline https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc

However, when running the `sysctl` call with docker run, it gives error like this

`flag: sysctl 'fs.inotify.max_user_watches=524288' is not whitelisted`

### Describe the solution you'd like

Whitelist `sysctl`

**Comment by tianleh** [comment]
An online reference https://github.com/moby/moby/issues/4611#issuecomment-305336451

**Comment by zelinh** [comment]
[Triage] You can whitelist this param in your local environment as developer, but right now we are not whitelist any new parameter for production.
