### ISSUE TITLE
Script to build each component from manifest and assemble bundle.

### ISSUE THREAD

**Issue by mch2** [opensearch-project/opensearch-build#133]
This script should read a manifest and output all artifacts ready for upload.
Example.
/build/opensearch-dashboards-min-1.0.0-SNAPSHOT-linux-arm64-198.tar.gz <- min bundle
/build/opensearch-dashboards-1.0.0-SNAPSHOT-linux-arm64-198.tar.gz. <-- full bundle
/build/opensearch-sql-1.0.0.0-rc1.zip
/build/org/opensearch... <- maven artifacts

Input: to the script should be a manifest file location - format defined here #111 
Output: all required artifacts are written to ./build

- [x] Clone each component repository defined in the manifest
- [x] Build each component. This includes plugin zips and maven artifacts and place under a new folder with build id.  Note: We need to know if the version of a particular component is already published to maven central.  If this is the case we do not need to rebuild and include that artifact.
- [ ] Assemble the bundle itself and add to the /build directory. This is dependent on being able to write manifests - #134 

To make assembling maven artifacts easier, each repo can be published to maven local and copied from that location into /build.  All artifacts will be under org/opensearch.

**Comment by dblock** [comment]
#145 and #150 for (1) and (2)
