### ISSUE TITLE
Take a release candidate build and publish its artifacts onto artifacts.opensearch.org

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#1332]
We need a system to accept a url and then pick up the RC build and promote those artifacts to production, they might need to be signed for this to complete.

Needs to work on tarball + native plugins

**Comment by peterzhuamazon** [comment]
We have the core functionality completed in #1354 and will improve it in https://github.com/opensearch-project/opensearch-build/issues/1355
