### ISSUE TITLE
Skip old(er) manifests in CI

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#1335]
### Is your feature request related to a problem? Please describe

We have 30+ manifests running CI checks in https://github.com/opensearch-project/opensearch-build/pull/1331. That takes more and more time and is not scalable long term even with infinite parallelization.

### Describe the solution you'd like

Skip some manifest checks. One idea could be to skip the last patch release, e.g. skip 1.1.0, 1.1.1, 1.1.2 when we have 1.1.3 for example. Another could be to commit release `.lock` files and check for changes.

**Comment by zelinh** [comment]
[Triage] Adding this issue to our product backlog. We have enough information on this.
