### ISSUE TITLE
[Bug]: Build is not publishing -min artifact to https://artifacts.opensearch.org/snapshots automatically

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#1344]
### Describe the bug

https://github.com/opensearch-project/asynchronous-search/runs/4535094305?check_suite_focus=true is failing because it can't find https://artifacts.opensearch.org/snapshots/core/opensearch/1.2.2-SNAPSHOT/opensearch-min-1.2.2-SNAPSHOT-linux-x64-latest.tar.gz.

### To reproduce

https://github.com/opensearch-project/asynchronous-search/runs/4535094305?check_suite_focus=true

**Comment by peternied** [comment]
Artifacts are in place, and I've restarted the CI workflow for asynchronous-search
