### ISSUE TITLE
[META] Automate artifact signing with OpensearchSignerClient for linux

### ISSUE THREAD

**Issue by abhinavGupta16** [opensearch-project/opensearch-build#1351]
### Is your feature request related to a problem? Please describe

Signing currently is a long painstaking process. It needs to be automated to save time when releasing artifacts. We need a tool to be able to sign all artifacts - 
- opensearch
- opensearch-dashboards

### Describe the solution you'd like

Use the existing `Signer.py` class to sign the artifacts and generate ".sig" file along with ".asc" files.

### Tasks
- [x] #1382
- [x] #1383
- [x] #1385

### Acceptance Criteria
- [ ] User is able to provide the artifact directory and tool is able to sign all the artifacts in the directory
- [ ] User is able to pass the artifact path and the tool is able to sign the artifact

### Next Steps
Next steps would include to extend this process over for mac and windows

**Comment by peternied** [comment]
This workflow supports this scenario https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/sign-artifacts/sign-standalone-artifacts.jenkinsfile
