### ISSUE TITLE
[Enhancement] Add tests and improvement to the promotion jenkins workflow

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#1355]
We are adding tar and native plugin zips auto promotion here: https://github.com/opensearch-project/opensearch-build/pull/1354

There are several improvement needed after the PR is merged:
1. Write a full test for the jenkinsfile, including gradle/groovy test case file, sample jenkinsfile, txt results.
2. Put s3upload params to its own variable.
3. Rename all the `AWS_ACCOUNT_PUBLIC` to `AWS_CENTRAL_ARTIFACT_ACCOUNT` as it is mistakenly added 1st in Jenkins with a wrong name, and rename all the entries related to it.
4. As of now it is designed to trigger multiple times by engineer on different arch/platform, we can definitely add a multi-arch trigger so we dont need to manually trigger it multiple times.
5. Reduce the number of params needed for the jenkinfile.
6. Use build parameter more as that feeds in more information for the task.

**Comment by gaiksaya** [comment]
Closing this as the feature has been implemented via https://github.com/opensearch-project/opensearch-build/pull/4280
