### ISSUE TITLE
[Bug]: Maven sign and upload should be done inside a docker container

### ISSUE THREAD

**Issue by abhinavGupta16** [opensearch-project/opensearch-build#1357]
### Describe the bug

We should be using a docker container to run jenkinsjob. 

https://github.com/opensearch-project/opensearch-infra/blob/main/jenkins/jobs/OpenSearch_CI/release_ci/opensearch_maven_release/Jenkinsfile#L3-L5

Also, should this file be a part of `opensearch-build`?

### To reproduce

Docker container is not used - 

https://github.com/opensearch-project/opensearch-infra/blob/main/jenkins/jobs/OpenSearch_CI/release_ci/opensearch_maven_release/Jenkinsfile#L3-L5

**Comment by zelinh** [comment]
[Triage] Move this to product backlog.

**Comment by zelinh** [comment]
We decide to move the maven workflow to our build repo since this could use the libraries in build repo and promote our public visibility. 
Also this job will require proper testing and some re-design on the signing part.
