### ISSUE TITLE
Need a post-deployment artifacts validation

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#1358]
After a release has been pushed we should make sure that everything we expect is available.

Acceptance Criteria
- Compile a list of urls that are added on artifacts.opensearch.org for the distribution build, opensearch-min, native plugins.
- Come up with a url translation on a version update, could be something like https://artifacts.opensearch.org/releases/bundle/opensearch/1.2.1/opensearch-1.2.1-linux-x64.tar.gz ->
https://artifacts.opensearch.org/releases/bundle/opensearch/{VERSION-x.y.z}/opensearch-{VERSION-x.y.z}-linux-x64.tar.gz
- Write a tool/job that accepts a parameter for the version number and then makes sure all the public artifacts resolve providing a pass/fail result, if there is a failure it is clear what needs investigation

**Comment by bbarani** [comment]
Closing this issue as redundant issue of https://github.com/opensearch-project/opensearch-build/issues/2524
