### ISSUE TITLE
Need a post-deployment functional validation 

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#1359]
Continuation of #1358

Acceptance criteria
- For docker images, start up the image run a curl command and verify the version number matches the expected value
  * How to verify that the docker container can start the service correctly
  * Connect with core team on what would be the tests to support after service starts
  * Do we want to support other container env, etc.
  * As opensearch what is the range of coverage we want to support
- For native plugins, install them with plugin tool and make sure it succeeds
- Write a tool/job that accepts a parameter for the version number and provides a pass/fail result, if there is a failure it is clear what needs investigation
- Automate for on snapshot/release candidate builds
- Automate for production releases

**Comment by peternied** [comment]
@opensearch-project/opensearch-core seems like there could be overlap with your validation processes, as well as ideas for more important/useful tests that could be run.

**Comment by bbarani** [comment]
Closing this in favor of https://github.com/opensearch-project/opensearch-build/issues/2524
