### ISSUE TITLE
Check versions of artifacts bundled in a distribution

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/opensearch-build#137]
**Is your feature request related to a problem? Please describe.**
Bundle being built for a release do not verify the versions of the artifacts or that "everything works together".
Artifacts name them version x but can still be of version y and built out of version z of OpenSearch/Dashboards 
**Describe the solution you'd like**
We'd like to improve the release quality. We should an automated way to verify the artifacts provided with the version they claim to be and the version we'd like to build for release.

Whats the motivation behind this?
Anomaly Detection plugin was still using OpenSearch and its dependencies with 1.0.0-rc1 and claiming the plugin version to be 1.0.0.0. But really underneath they were running different versions and cannot be bundled for a release as the plugin should have been built with 1.0.0 of OpenSearch and 1.0.0.0 of other dependent plugins/libraries.  
Ref: 
AD 1.0 release branch: https://github.com/opensearch-project/anomaly-detection/blob/1.0.0.0/build.gradle#L33-L35
Issue to fix after the release is done: https://github.com/opensearch-project/anomaly-detection/issues/153

We cannot manually scale and should have an automated workflow to check these artifacts for every release to start with.
With the CI infrastructure we are building, we should be able to add another CI job to verify the artifacts just before bundling them for the release.

**Comment by ylwu-amzn** [comment]
https://github.com/opensearch-project/anomaly-detection/issues/153
Seems we forgot to backport https://github.com/opensearch-project/anomaly-detection/pull/114 to 1.0 branch. Any suggestion about how to avoid such error in future? @saratvemulapalli @dblock

**Comment by saratvemulapalli** [comment]
Any manual process involved it can lead to errors. 
We should build tooling around this which is what I have explained above to have a job while building a bundle to verify it. 
Do you have any other suggestions?

**Comment by dblock** [comment]
These dependencies should be strong, aka if anomaly-detection was built against OpenSearch x.y, it should not run unless the OpenSearch JAR it's loading matches x.y.

**Comment by ylwu-amzn** [comment]
> Any manual process involved it can lead to errors.
> We should build tooling around this which is what I have explained above to have a job while building a bundle to verify it.
> Do you have any other suggestions?

We already have steps to build AD bundle in AD CI: https://github.com/opensearch-project/anomaly-detection/blob/1.0/.github/workflows/CI.yml#L78. But the CI didn't fail as we use rc1 at all places in 1.0 branch.
Maybe infra team can add same build steps in their CI workflow to make sure all plugins have correct version.

**Comment by dblock** [comment]
I had written https://github.com/opensearch-project/opensearch-build/issues/354, which I think is partially a dup. I'm making this issue about bundle integration tests that don't belong in the build workflow, while https://github.com/opensearch-project/opensearch-build/issues/354 can remain specifically about checking for versions during bundle build. 

See https://github.com/opensearch-project/opensearch-build/pull/372 for a start.
