### ISSUE TITLE
Name builds in Jenkins

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#1391]
### Is your feature request related to a problem? Please describe

It's hard to tell what Jenkins is building. In this screenshot it's building 1.2.1, 1.2.3, 1.3.0 and 2.0.0 of OpenSearch

![Screen Shot 2021-12-20 at 8 36 07 PM](https://user-images.githubusercontent.com/542335/146855925-601f5676-14e7-464c-b353-2e47de94a60c.png)
.

### Describe the solution you'd like

Label the builds at runtime with the build number, product and version/manifest being built.

### Additional context

https://stackoverflow.com/questions/43639099/set-the-build-name-and-description-from-a-jenkins-declarative-pipeline

**Comment by peterzhuamazon** [comment]
![Screen Shot 2021-12-20 at 8 40 33 PM](https://user-images.githubusercontent.com/65193828/146856292-1a16ae13-761d-4752-85da-a79cf5ee5df2.png)

We already have this in the freestyle snapshot creation workflow.
It is using an external plugin to achive.

**Comment by peterzhuamazon** [comment]
We can also add upstream workflow descriptions to be used for docker image building related workflows.

**Comment by peterzhuamazon** [comment]
Will try to put it into a lib and test again per @dblock suggestion.

Thanks.

**Comment by peterzhuamazon** [comment]
Seems like this issue is fixed now as we can directly get the upstream information from upstream logs.
