### ISSUE TITLE
[Enhancement] Replace $JOB_NAME with $JOB_BASE_NAME in all jenkinsfiles and libs

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#1394]
We currently use $JOB_NAME which runs well if we only have everything in the root directory.

However, once we starts to create folders in Jenkins and separate jobs with these folders, $JOB_NAME will leads to the full path of the job, not just name.

This can leads to issues and break our current setup on S3 and more.

```
JOB_NAME
    Name of the project of this build, such as "foo" or "foo/bar".
JOB_BASE_NAME
    Short Name of the project of this build stripping off folder paths, such as "foo" for "bar/foo".
```

I suggest we make this change and open to other ideas.

Thanks.

**Comment by dblock** [comment]
Makes sense to me, I didn’t know that the name inherited the path.

**Comment by ScreamingPigeon** [comment]
I can work on this issue. As I understand this would involve making changes to all the files ending with  `.groovy` in the './tests/jenkins/` directory. I am curious though about the exact issues caused by using the full path instead of the name

**Comment by peterzhuamazon** [comment]
As of now we have not make folders in our setups, but rather views.
This is a very low priority task for now.
And we will close it for the time being. Thanks.
