### ISSUE TITLE
[Bug]: Error building OpenSearch: Expected to have Implementation-Version=any of [None, '1.2.2.0', '1.2.2'], but was '1.2.3'

### ISSUE THREAD

**Issue by enp** [opensearch-project/opensearch-build#1397]
### Describe the bug

Can't build opensearch 1.2.2 from source

### To reproduce

```
$ git clone https://github.com/opensearch-project/opensearch-build.git
$ git checkout opensearch-1.2.2
$ docker build -f docker/ci/dockerfiles/ci-runner.centos7.dockerfile -t opensearch-1.2.2-build .
$ docker run -it --rm -v $(pwd):/project -w /project opensearch-1.2.2-build bash
$ ./build.sh manifests/1.2.2/opensearch-1.2.2.yml 
...
2021-12-22 12:48:02 ERROR    Error building OpenSearch, retry with: ./build.sh manifests/1.2.2/opensearch-1.2.2.yml --component OpenSearch
Traceback (most recent call last):
  File "/tmp/opensearch/src/build_workflow/opensearch/build_artifact_check_maven.py", line 41, in check
    properties.check_value_in("Implementation-Version", versions)
  File "/tmp/opensearch/src/system/properties_file.py", line 57, in check_value_in
    raise PropertiesFile.UnexpectedKeyValuesError(key, expected, value)
system.properties_file.UnexpectedKeyValuesError: Expected to have Implementation-Version=any of [None, '1.2.2.0', '1.2.2'], but was '1.2.3'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./src/run_build.py", line 78, in <module>
    sys.exit(main())
  File "./src/run_build.py", line 67, in main
    builder.export_artifacts(build_recorder)
  File "/tmp/opensearch/src/build_workflow/builder_from_source.py", line 60, in export_artifacts
    build_recorder.record_artifact(self.component.name, artifact_type, relative_path, absolute_path)
  File "/tmp/opensearch/src/build_workflow/build_recorder.py", line 40, in record_artifact
    BuildArtifactChecks.check(self.target, artifact_type, artifact_file)
  File "/tmp/opensearch/src/build_workflow/build_artifact_checks.py", line 42, in check
    instance.check(path)
  File "/tmp/opensearch/src/build_workflow/opensearch/build_artifact_check_maven.py", line 43, in check
    raise BuildArtifactCheck.BuildArtifactInvalidError(path, str(e))
build_workflow.build_artifact_check.BuildArtifactInvalidError: Artifact custom-settings-1.2.3-javadoc.jar is invalid. Expected to have Implementation-Version=any of [None, '1.2.2.0', '1.2.2'], but was '1.2.3'.
```

### Expected behavior

Expecting to build opensearch as described in https://github.com/opensearch-project/opensearch-build/blob/main/README.md#building-from-source

### Host / Environment

Docker

**Comment by dblock** [comment]
I think the 1.2.2 tag was premature and should have included https://github.com/opensearch-project/opensearch-build/commit/7785777cfdcfb5ebbe05307919cbbccf5884d0bc which locked the manifest version(s) at the 1.2.2 _tag_. I'd rather not re-tag - does this work off `main` right now?

**Comment by enp** [comment]
Thank you, will try. So, you proposing to build from `main` for next versions too?

**Comment by dblock** [comment]
> Thank you, will try. So, you proposing to build from `main` for next versions too?

1. The 1.2.2 tag should have been stable, what you reported is, indeed, a bug.
2. You can (should be able to) currently build all versions of OpenSearch and OpenSearch Dashboards from `main`. Our CI does that.

Does this help?

**Comment by enp** [comment]
No, I have another error on https://github.com/opensearch-project/opensearch-build/blob/main/docker/release/dockerfiles/opensearch.al2.dockerfile#L37 while building on ```main```:

```
Step 10/33 : COPY * $TEMP_DIR
When using COPY with more than one source file, the destination must be a directory and end with a /
```

**Comment by dblock** [comment]
> No, I have another error on https://github.com/opensearch-project/opensearch-build/blob/main/docker/release/dockerfiles/opensearch.al2.dockerfile#L37 while building on `main`:
> 
> ```
> Step 10/33 : COPY * $TEMP_DIR
> When using COPY with more than one source file, the destination must be a directory and end with a /
> ```

I see `TEMP_DIR=/tmp/opensearch`, maybe that needs to be created if it doesn't exist?

**Comment by enp** [comment]
No, this directory is already created and contains opensearch-build tree

Anyway adding / to $TEMP_DIR solves problem, can you fix this?

**Comment by dblock** [comment]
> No, this directory is already created and contains opensearch-build tree
> 
> Anyway adding / to $TEMP_DIR solves problem, can you fix this?

Interesting!  How did this ever work before? This was added in https://github.com/opensearch-project/opensearch-build/issues/1154, cc: @peterzhuamazon 

@enp You can also PR the change! Thanks.

**Comment by peterzhuamazon** [comment]
> > No, this directory is already created and contains opensearch-build tree
> > Anyway adding / to $TEMP_DIR solves problem, can you fix this?
> 
> Interesting! How did this ever work before? This was added in #1154, cc: @peterzhuamazon
> 
> @enp You can also PR the change! Thanks.

As per online research, Docker version 18.09.0, build 4d60db4 and before does not support using wildcard with destination folder w/o `/`, which has since been patched so docker will auto detect whether destination is a file or dir.

We are using docker enginer `Docker version 19.03.13-ce, build 4484c46` or above for our builds, thus does not have this issue with docker builds.

However, this can be easily addressed for older version user with appending slash to the end of the folder name.

Thanks.
