### ISSUE TITLE
[Retrospective] Release 1.2.3

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#1401]
### How to use this issue?
Please add comments to this issue, they can be small or large in scope.  Honest feedback is important to improve our processes, suggestions are also welcomed but not required.

### What will happen to this issue post release?
There will be a discussion(s) about how the release went and how the next release can be improved.  Then this ticket will be updated with the notes of that discussion along side action items.

**Comment by dblock** [comment]
Release notes are still manual, but maybe the solution is not to automate release notes but do something like https://github.com/dblock/danger-changelog that requires those making PRs to write a humanly readable changelog?

https://github.com/opensearch-project/opensearch-build/issues/698
https://github.com/opensearch-project/opensearch-build/issues/438

**Comment by bbarani** [comment]
Improve / automate the signing and publish workflow. 
#1351 
#1383

**Comment by dblock** [comment]
Installation of plugins was untested and broke for customers, https://github.com/opensearch-project/opensearch-build/issues/1406

**Comment by peternied** [comment]
See https://github.com/opensearch-project/opensearch-build/issues/880#issuecomment-1006130147 for the summary across all 1.2.0-1.2.3 retros.
