### ISSUE TITLE
Get docker image from constants file for Jenkins job

### ISSUE THREAD

**Issue by abhinavGupta16** [opensearch-project/opensearch-build#1409]
### Is your feature request related to a problem? Please describe

Currently, all the images mentioned in the jenkins job are added as strings. This poses 2 problems - 
- This makes it very difficult to make changes and update them if required. It is very easy to miss an image making the jobs vulnerable to failure. 
- It is difficult to see and analyze which docker images are currently in use by the jenkins jobs and find an iamge.

### Describe the solution you'd like

- Create a constants file that will have the all the strings associated with the jenkins job
- All the images for jenkins job are being picked from the constants file

### Acceptance Criteria
- [ ] All jenkins job pull their images from the constants file

**Comment by dblock** [comment]
Isn't this a dup of https://github.com/opensearch-project/opensearch-build/issues/1325?

**Comment by zelinh** [comment]
[Triage] Closing this one since this is a duplicate issue.
