### ISSUE TITLE
Adding Docker Build related automation / linting as PR checks

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#1414]
If any code in dockerfiles get updated, we should run a validation docker workflow in github actions to ensure the build is success.

#1397 shows some issues in older docker enginer version, we probably need to test the BC as well.

Thanks.

**Comment by bbarani** [comment]
@rishabh6788 @prudhvigodithi @peterzhuamazon @gaiksaya Do we have any automated validation workflows running now?

**Comment by gaiksaya** [comment]
No we do not. @peterzhuamazon Can you be more clear on this? Do we want to test the docker image building part or see if docker image is causing issues for some plugins?
For 1. where docker image config needs to be tested we can build and test (start a cluster and run basic apis) as integration tests for docker on your part
For 2. If we need to check docker image issues with some plugins, we need to add docker as one of the distribution in the integration testing framework.

**Comment by peterzhuamazon** [comment]
This is very old and the current idea of mine is just to have a simple docker build so at least we know there is no syntax issues in the dockerfile before merge.

Thanks.

**Comment by peterzhuamazon** [comment]
Adding docker linting:
* https://github.com/opensearch-project/opensearch-build/pull/3337
