### ISSUE TITLE
Support extracting WhiteSource data through API after the scanning.

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#1415]
This is related to @ryanbogan where we need to extract the data through whitesource API after the scan and use it to build the dependency tree later.

This issue is used to record all the related activities.

Thanks.

**Comment by abhinavGupta16** [comment]
[Triage] @peterzhuamazon @ryanbogan - can you add more details to the task? Also, can you add Acceptance Criteria to this as well?

Thank you!

**Comment by bbarani** [comment]
@ryanbogan Can you please confirm if you are actively working on this requirement?

**Comment by CEHENKLE** [comment]
Hey @bbarani he's not working on it -- that's on me.  I think it needs a new owner

**Comment by zelinh** [comment]
Closing this issue for now. We can open a new one if needed.
