### ISSUE TITLE
Add windows support for signing artifacts

### ISSUE THREAD

**Issue by abhinavGupta16** [opensearch-project/opensearch-build#1430]
### Is your feature request related to a problem? Please describe

Currently, the `signer.py` only supports signing for linux clients for PGP. We need to extend this for windows as well.

We also need to extend the `signArtifacts` job for standalone components to be able to sign windows artifacts.

### Describe the solution you'd like

Pass windows as a parameter and signer can sign and verify windows artifacts.

### Acceptance Criteria
- [x] I am able to sign and verify windows artifacts using `sign.sh`.
- [x] Added test cases to test the workflow
- [x] Updated the `signArtifacts` job for standalone components for windows
- [x] Updated the test cases for `signArtifacts` job for standalone components for windows

**Comment by zelinh** [comment]
New PR #2156 was raised. Now with that PR, we should be able to sign windows artifacts with the sign scripts we have and also sign by using jenkins `signArtifacts` library.
