### ISSUE TITLE
Adding limitation on Jenkins workflows so it will overflow the main node disk

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#1433]
Back in freestyle time we add limitation of 300 build history per workflow, means if there are more than 300 build history, the oldest build history will be removed.

Once we switch to pipeline files we have not set this up, means there are no life cycle on these history.

Check_for_build has nearly 27000+ build history now all saved on Jenkins main node.

This would not only overflow the Jenkins disk quick, but also slow the loading when browsing Jenkins.

Suggesting adding the limitation back and we can log rotate and save to s3.

```
pipeline {
  options {
    buildDiscarder(logRotator(numToKeepStr: '30', artifactNumToKeepStr: '30'))
  }
  ...
}

////////////////////////////////////////////////////////////////////////////

    daysToKeepStr: history is only kept up to this days.
    numToKeepStr: only this number of build logs are kept.
    artifactDaysToKeepStr: artifacts are only kept up to this days.
    artifactNumToKeepStr: only this number of builds have their artifacts kept.

```

Thanks.

**Comment by bbarani** [comment]
@peterzhuamazon Is this still a valid issue even after reducing the retention period?

**Comment by bbarani** [comment]
@peterzhuamazon Is this still a valid issue?

**Comment by peterzhuamazon** [comment]
We can always give bigger disk to Jenkins, as since we have a need now to retain all the logs, so close this.
