### ISSUE TITLE
Build Data Prepper continuously

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/opensearch-build#1439]
### Is your feature request related to a problem? Please describe

The new Data Prepper tarball build in #1434 is only building and deploying once it is time to release. Data Prepper is a standalone application and can build nightly.

### Describe the solution you'd like

Create a build of Data Prepper which builds all artifacts. This build can run against multiple branches. It can also produce nightly builds when changes are made to the project.

Additionally, Data Prepper would need a second promotion build to sign artifacts.

Data Prepper has the following artifacts which need to be built:
* Docker image
* Tarballs (linux only presently)
* Maven artifacts

**Comment by gaiksaya** [comment]
[Triage] We will follow up after https://github.com/opensearch-project/opensearch-build/issues/1234

**Comment by dlvenable** [comment]
Data Prepper will now have its own staging GitHub Action. This will run regularly.

Since the Jenkins job in this project signs and uploads to production, it should not run aside from a manual request to promote a staging build. Thus, I'm closing this issue.
