### ISSUE TITLE
Update test orchestrator pipeline

### ISSUE THREAD

**Issue by ohltyler** [opensearch-project/opensearch-build#1447]
The test orchestration pipeline (see [here](https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/test/orchestrator/Jenkinsfile)) is out of date, and the parameters being passed to the different test jobs are now invalid and don't work.

Work should be done to update these jobs in a consistent manner, where the same set of parameters can be passed to all of them. The integ test job has been updated as part of #1429

**Comment by gaiksaya** [comment]
[Triage] We should delete the orchestration workflow and update the documentation

**Comment by ohltyler** [comment]
I'll work on cleaning up this old code and updating the READMEs in a follow-up PR to #1429.
