### ISSUE TITLE
[Bug]: Entrypoint for Docker image erases config file

### ISSUE THREAD

**Issue by davidlago** [opensearch-project/opensearch-build#1454]
### Describe the bug

After #1130 was merged, [this line](https://github.com/opensearch-project/opensearch-build/pull/1130/files#diff-107c2499e08c900c5ab75b5fd413c22bd9cf1ffe3819aeddabe51836ee4c58f5R72) completely wipes out the configuration file of the docker container on startup.

### To reproduce

```
docker run -it -p 9200:9200 -e "discovery.type=single-node" opensearchstaging/opensearch:1.2.4
```

as `1.2.4` is the first image built with this entrypoint.

### Expected behavior

Container should start up successfully.

### Host / Environment

MacOS, docker.

**Comment by peterzhuamazon** [comment]
Taking a look.

**Comment by peterzhuamazon** [comment]
The issue is due to that:

Reading from and writing to opensearch.yml in the same command line is error-prone. sed is trying to read from the file at the same time that tee wants to truncate it and write to it.
