### ISSUE TITLE
Auto-format the auto-generated manifest YML

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#1457]
### Is your feature request related to a problem? Please describe

When a new manifest is generated by the manifests workflow it's strangely formatted. When we try to make changes to it by hand we end up auto-formatting it very differently, e.g. https://github.com/opensearch-project/opensearch-build/pull/1449

### Describe the solution you'd like

Write new manifests that are formatted as if they were authored by the default auto-formatter in VSCode (or other editor).

**Comment by peternied** [comment]
An alternative approach, we could apply a check / auto-formatter on all manifest.yml files.
