### ISSUE TITLE
Update build system to build performance-analyzer

### ISSUE THREAD

**Issue by mch2** [opensearch-project/opensearch-build#148]
Currently Performance-analyzer is commented out in the [InputManifest](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/opensearch-bundle.1.0.yml) for 1.0.  

This component should be included with all the others but its build is currently failing if uncommented.

- This component requires performance-analyzer-rca to also be assembled and included within performance-analyzer-rca.zip. [Example](https://github.com/opensearch-project/opensearch-build/blob/main/release/tar/linux/opensearch-tar-build.sh#L147) of it being required during bundle assembly. 
- This component's snapshot build by passing -Dbuild.snapshot=true needs to work and output -SNAPSHOT artifacts.

**Comment by xuezhou25** [comment]
About this build fail, it is because [spotless](https://github.com/opensearch-project/performance-analyzer-rca/blob/c1c32ab1f03e96fbbb03b520ba0de7d61d2d1618/build.gradle#L100) in RCA(when build PA, it will by default build RCA internal) required two branch to compare(for example main and 1.0). 
```
* What went wrong:
A problem occurred configuring root project 'tmp3gn5llmf'.
> No such reference 'origin/main'
```
After fix RCA by skip the spotless step, it can build successful.

**Comment by mch2** [comment]
RCA is also failing its spotbugs check on main. -> https://github.com/opensearch-project/performance-analyzer-rca/pull/47

We can get by that when building RCA directly, but when we build the main plugin repo it is *always* cloning and building the main branch of RCA internally as part of its build scripts. https://github.com/opensearch-project/performance-analyzer/issues/45
This means we cannot bypass this step and the build fails.

This means that any build of perf analyzer fails, even for 1.1, until the above PR is merged.

**Comment by mch2** [comment]
with the following snippet we can get by the spotbugs check in build.sh for each repo.

```
# remove this script when https://github.com/opensearch-project/performance-analyzer/issues/44 is fixed
git fetch origin main
git checkout main
# move back to initial ref
git checkout -
```

without the [spotbugs](opensearch-project/performance-analyzer-rca#47) fix we have no way of producing a successful build.
