### ISSUE TITLE
Make entrypoint scripts actual entrypoints in docker images

### ISSUE THREAD

**Issue by gilbsgilbs** [opensearch-project/opensearch-build#1486]
### Is your feature request related to a problem? Please describe

Currently, entrypoints scripts are defined as an docker commands and not as entrypoints:

- https://github.com/opensearch-project/opensearch-build/blob/fb20bc0e81bd6e055e40a9f86fcea22c7165c81a/docker/release/dockerfiles/opensearch.al2.dockerfile#L109
- https://github.com/opensearch-project/opensearch-build/blob/fb20bc0e81bd6e055e40a9f86fcea22c7165c81a/docker/release/dockerfiles/opensearch-dashboards.al2.dockerfile#L87

Extra arguments passed to this entrypoint script are ignored (unless #1484 is merged at some point).

This is quite uncommon and prevents the commands to be easily reused or extended for other purposes.

### Describe the solution you'd like

I'd suggest doing something similar to the [postgres docker image](https://github.com/docker-library/postgres/blob/a83005b407ee6d810413500d8a041c957fb10cf0/14/bullseye/docker-entrypoint.sh#L298) (which I guess is pretty standard in Docker images).

- Define entrypoint scripts as `ENTRYPOINT` in the Dockerfile
- Define `openseach` or `opensearch-dashboards` as default `CMD` (this requires adding `$OPENSEARCH_HOME/bin`/`$OPENSEARCH_DASHBOARDS_HOME/bin` to the `PATH`)
- If the command passed to the entrypoint looks like a flag (i.e. starts with a dash), consider that `opensearch`/`opensearch-dashboards` command is implicit
- If the first argument passed to the entrypoint is `opensearch`/`opensearch-dashboards`, run the setup recipe and exec the command, forwarding extra arguments
- Otherwise, just exec the command

This would allow for the following `docker run` commands:
- `docker run opensearchproject/opensearch opensearch -Ediscovery.type=single-node`
- `docker run opensearchproject/opensearch -Ediscovery.type=single-node`
- `docker run opensearchproject/opensearch bash`

This is also slightly more extensible in case you want to use opensearchproject/opensearch as a base image for other images.

I think this suggestion is 100% backwards compatible, even for people who have overriden the `CMD` in a custom image (because the entrypoint would then invoke their custom `CMD` normally).

### Additional context

See also #1484.

I'm happy to contribute if this suggestion seems OK to you.

**Comment by dblock** [comment]
💯  @gilbsgilbs please do contribute!
