### ISSUE TITLE
Consolidate release artifact URL

### ISSUE THREAD

**Issue by tianleh** [opensearch-project/opensearch-build#1491]
### Is your feature request related to a problem? Please describe

The release artifact can be accessed in the following style from https://github.com/opensearch-project/opensearch-build/issues/1482

https://artifacts.opensearch.org/releases/1.2.0/dist/opensearch-dashboards/opensearch-dashboards-1.2.0-linux-x64.tar.gz

We can deprecate the existing one 
https://artifacts.opensearch.org/releases/bundle/opensearch-dashboards/1.2.0/opensearch-dashboards-1.2.0-linux-x64.tar.gz

### Describe the solution you'd like

remove the existing one with "bundle" keyword and use new link in https://opensearch.org/

**Comment by gaiksaya** [comment]
[Triage] This is a breaking change. Needs to be investigated.

**Comment by tianleh** [comment]
We are considering taking the approach to support `latest` in url instead of touching the release url. (https://github.com/opensearch-project/opensearch-build/issues/1492) Thus this issue is no longer applicable.

**Comment by gaiksaya** [comment]
Hi @tianleh , looks like changes related to this issue were merged in #1490 . Are you going to revert that change?

**Comment by tianleh** [comment]
> Hi @tianleh , looks like changes related to this issue were merged in #1490 . Are you going to revert that change?

See this https://github.com/opensearch-project/opensearch-build/pull/1490#issuecomment-1015795848

**Comment by gaiksaya** [comment]
Got it! Thank you
