### ISSUE TITLE
[Feature] Add support for urls to substitute `latest` for the most recent build number

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#1492]
From https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1038

Potential Solutions:
- **Add functionality to the url re-writer**
  The cdk deployment that uses a lambda function to rewrite the url on incoming requests to the s3 buckets, this could be updated to handle the `/latest/` string in place of a build number by scanning the s3 bucket.  https://github.com/opensearch-project/opensearch-build/blob/f79e7fd2d8d39290e064fa915800d510dfee40f8/deployment/lib/artifacts-public-access.ts#L23-L29

   *Trade-offs*: Con, the bucket might not contain that artifact and result in a 404.  Pro, could be applied on older builds.

- **When uploading artifacts, also add a `latest` bucket**
  The upload code is on a shard and the artifacts could be uploaded into multiple locations.  https://github.com/opensearch-project/opensearch-build/blob/f79e7fd2d8d39290e064fa915800d510dfee40f8/vars/uploadArtifacts.groovy#L26-L29

   *Trade-offs*: Con, Only works on products that build with that shared library function.  Doesn't work with 1.x kind of functionality

Acceptance Criteria:
- Given a url such as `https://ci.opensearch.org/ci/dbc/bundle-build-dashboards/1.2.0/LATEST/linux/x64/builds/plugins/queryWorkbenchDashboards-1.2.0.zip` gets the same artifact as calling `https://ci.opensearch.org/ci/dbc/bundle-build-dashboards/1.2.0/512/linux/x64/builds/plugins/queryWorkbenchDashboards-1.2.0.zip` (Assuming 512 is the most recent version)
- Given a url such as  `https://ci.opensearch.org/ci/dbc/bundle-build-dashboards/1.2.0/LATEST/linux/x64/builds/plugins/queryWorkbenchDashboards-1.2.0.zip` after the artifact has been updated the url returns the artifact in a way that bypasses caching.

**Comment by dblock** [comment]
I think the best case scenario for "latest" would be a 302 redirect, is that an option 3? That is also something that would allow us to move downloadable files around as we tend to do this quite a bit while we learn the "ideal" url structure.

**Comment by peternied** [comment]
> I think the best case scenario for "latest" would be a 302 redirect

Good callout, I've added it to the acceptance criteria that we need a way to get through a cache.

**Comment by dblock** [comment]
Couple more:

1. Coming from https://github.com/opensearch-project/opensearch-build/pull/1493 I'd like "latest" to automatically give me a released version of 1.2.3 if 1.2.3 has been released or the latest available build of 1.2.3 if it has not. 
2. Consider supporting latest semver, latest 1.x could be the latest released 1.2.3, etc.

**Comment by tianleh** [comment]
@peternied We have a dependency on this for running Dashboards integ test against a static OpenSearch url https://github.com/opensearch-project/opensearch-build/issues/1322 Do you know when this issue can be done?

**Comment by peternied** [comment]
@tianleh we would welcome your contribution, The first option, `Add functionality to the url re-writer` seem like the sensible option to support a wide variety of scenarios and backward compatibility

**Comment by tianleh** [comment]
take a look

**Comment by tianleh** [comment]
@seraphjiang for visibility

**Comment by seraphjiang** [comment]
> @tianleh we would welcome your contribution, The first option, `Add functionality to the url re-writer` seem like the sensible option to support a wide variety of scenarios and backward compatibility

Hi @peternied, could infra team prioritize this item?

**Comment by tianleh** [comment]
Experimenting with Option 1 a bit. It requires a list operation of the S3 bucket to find the most modified object. This can be done by a command like this
`aws s3api list-objects-v2 --bucket "test-access-1-20" --query 'sort_by(Contents, &LastModified)[-1].Key' --output=text`

However, this query will have performance impact to sort the objects under the bucket and require potential pagination (>1000 items). Thus we may need to build some storage layer which stores the mapping from `latest` for every version to a build number somewhere (e.g DynamoDB). 

Given this, for simplicity, I would suggest the option 2 ("When uploading artifacts, also add a latest bucket") for development in this iteration.

**Comment by tianleh** [comment]
@dblock

**Comment by peternied** [comment]
> done by a command like this
> `aws s3api list-objects-v2 --bucket "test-access-1-20" --query 'sort_by(Contents, &LastModified)[-1].Key' --output=text`

@tianleh If this output is sorted in newest to oldest, shouldn't the first result be the most recent build?  That seems pretty scalable without any addition additional service calls or tracking systems.

The number of builds for a given release is a function of the number of changes in it, so I doubt this will be sufficiently larger than 1,000 change if we are releasing every quarter or faster.

**Comment by tianleh** [comment]
Thanks Peter for mentioning the `ls` and adding `/` to the folder name to get the one-step deep sub folders.
`aws s3 ls s3://artifact-bucket-stack-buildbucket-9omh0hnpg12q/distribution-build-opensearch/1.2.3/`

I will check more on how the logic can be integrated into the Lambda function https://github.com/opensearch-project/opensearch-build/blob/main/deployment/lib/artifacts-public-access.ts#L23

**Comment by tianleh** [comment]
After researching more, there are two ways to perform such in JavaScript.

1.  use the `aws-sdk` and `s3.listObjects`. See this https://docs.aws.amazon.com/code-samples/latest/catalog/javascript-s3-s3_listobjects.js.html
2. use the `aws-cli-js`. See this https://www.npmjs.com/package/aws-cli-js

Will experiment more to see which one is simpler.

**Comment by tianleh** [comment]
Also current Lambda code exists as an inline String https://github.com/opensearch-project/opensearch-build/blob/main/deployment/lib/artifacts-public-access.ts#L24 Will also check if there is an elegant way to make it exist as regular code for better readability since now the logic is more complicated.

**Comment by peternied** [comment]
@tianleh Is there a draft PR that I could follow?  While I would love an elegant solution, I think it make sense to discuss tradeoffs in a PR

**Comment by tianleh** [comment]
> @tianleh Is there a draft PR that I could follow? While I would love an elegant solution, I think it make sense to discuss tradeoffs in a PR

Sure. https://github.com/opensearch-project/opensearch-build/pull/1569
