### ISSUE TITLE
create and commit "artifacts/vars-build" instead of dynamically creating/deleting during TestPromoteArtifacts

### ISSUE THREAD

**Issue by tianleh** [opensearch-project/opensearch-build#1494]
### Is your feature request related to a problem? Please describe

This is motivated by @dblock 's PR comment on https://github.com/opensearch-project/opensearch-build/pull/1490#discussion_r786190883

### Describe the solution you'd like

The test files below shall be checked in instead of being dynamically setup.
https://github.com/opensearch-project/opensearch-build/blob/main/tests/jenkins/TestPromoteArtifacts.groovy#L76-L84

### Acceptance Criteria:

The test files under `artifacts/vars-build` are committed as part of the code instead of being copied in `setUp` function and then deleted in `after` function.

https://github.com/opensearch-project/opensearch-build/blob/main/tests/jenkins/TestPromoteArtifacts.groovy#L76-L84

**Comment by gaiksaya** [comment]
[Triage] Hi @tianleh, can you add the acceptance criteria and update the issue?
Thanks!

**Comment by tianleh** [comment]
> [Triage] Hi @tianleh, can you add the acceptance criteria and update the issue?
> Thanks!

@gaiksaya Thanks for the info! I just added `Acceptance Criteria` part. Let me know if it is easier to understand now.

**Comment by bbarani** [comment]
@tianleh Any update on the current status?

**Comment by gaiksaya** [comment]
We have separated out the build-libraries into its own repository https://github.com/opensearch-project/opensearch-build-libraries. The tests now use its own version and grabs the right version tag of build-libraries for testing.

Closing this issue!
Thanks!
