### ISSUE TITLE
Supporting running integ tests on multiple JDKs

### ISSUE THREAD

**Issue by ohltyler** [opensearch-project/opensearch-build#1495]
Current integ test jenkinsfile is only running on JDK14. This should be changed to support multiple JDKs and should match what OpenSearch supports / runs on.

**Comment by gaiksaya** [comment]
Hi @ohltyler ,

Currently, the tests are run using jdk specified in the input manifest. It does match what OpenSearch and other components are build on. I believe the request if you run integration tests on all supported JDKs?

**Comment by ohltyler** [comment]
Hi @gaiksaya , yes, this looks to be very out of date. I'll close.
