### ISSUE TITLE
[Bug]: checksum check failing for OpenSearch

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/opensearch-build#1497]
### Describe the bug

OpenSearch Dashboards out-of-the-box experience downloads a snapshot of OpenSearch to start up and run some integration tests and functional tests. However, there is [logic](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/packages/osd-opensearch/src/artifact.js#L427) before starting OpenSearch artifact automatically downloaded to verify the checksum. As of last week (roughly 1/14), we started to notice this logic has been failing with the result being:

```
    artifact downloaded from https://artifacts.opensearch.org/snapshots/core/opensearch/2.0.0-SNAPSHOT/opensearch-min-2.0.0-SNAPSHOT-linux-x64-latest.tar.gz does not match expected checksum
      expected: 02479d4417c501750b0afc39f74bfb5969f086ea6f6a31943298bbbf1dc06be48de3e32051087e58cca8712e3de5066aa48ec1f803d88508ffad96b5246d2f03
      received: 6944c39d9d32d82c2c0604426ba8a98737e725108e9ca7559e90efbf44928e48634983f8696d34a49c53d2973c9e07a91a3ec7f5affe0410c46779b983941873
```
[[SOURCE](https://github.com/opensearch-project/OpenSearch-Dashboards/runs/4836313804?check_suite_focus=true)]

### To reproduce

This is specifically relying out of the out of box experience. If you have an OpenSearch artifact downloaded and pointing to it with `TEST_OPENSEARCH_FROM` it will avoid this logic. 

To reproduce:
* Ensure no running version of OpenSearch
* `unset TEST_OPENSEARCH_FROM`
* `git checkout main`
* `yarn osd bootstrap`
* `yarn test:jest_integration`

Notice failure in integration tests.

### Expected behavior

Integration tests work out of the box and thus the CI will succeed. Developers should be able to run `yarn test:jest_integration` without setting `TEST_OPENSEARCH_FROM`

### Screenshots

n/a

### Host / Environment

Local ubuntu & github ci

### Additional context

Example: https://github.com/opensearch-project/OpenSearch-Dashboards/runs/4836313804?check_suite_focus=true

### Relevant log output

```shell
artifact downloaded from https://artifacts.opensearch.org/snapshots/core/opensearch/2.0.0-SNAPSHOT/opensearch-min-2.0.0-SNAPSHOT-linux-x64-latest.tar.gz does not match expected checksum
      expected: 02479d4417c501750b0afc39f74bfb5969f086ea6f6a31943298bbbf1dc06be48de3e32051087e58cca8712e3de5066aa48ec1f803d88508ffad96b5246d2f03
      received: 6944c39d9d32d82c2c0604426ba8a98737e725108e9ca7559e90efbf44928e48634983f8696d34a49c53d2973c9e07a91a3ec7f5affe0410c46779b983941873
```

**Comment by dblock** [comment]
There were some changes in signing, e.g. https://github.com/opensearch-project/opensearch-build/pull/1437, @abhinavGupta16 care to take a look?

**Comment by kavilla** [comment]
> @kavilla Is this problem with `-latest` only? Maybe we updated `-latest` but didn't update the checksum? See #1492 for a permanent fix discussion.

Just changed the verification to one without `-latest`: `https://artifacts.opensearch.org/snapshots/core/opensearch/2.0.0-SNAPSHOT/opensearch-min-2.0.0-SNAPSHOT-linux-x64-844.tar.gz`. 

All the test passed!

**Comment by peternied** [comment]
https://github.com/opensearch-project/opensearch-build/blob/824674d8f0f366c044a728643ec81b595d04bb1e/vars/uploadMinSnapshotsToS3.groovy#L10-L14

It doesn't look like the checksum is being updated, that should be a quick fix

**Comment by peterzhuamazon** [comment]
Confirmed that the workflow only upload the latest artifact but not update the latest checksum:
```

% cat opensearch-min-2.0.0-SNAPSHOT-linux-x64-latest.tar.gz.sha512
02479d4417c501750b0afc39f74bfb5969f086ea6f6a31943298bbbf1dc06be48de3e32051087e58cca8712e3de5066aa48ec1f803d88508ffad96b5246d2f03  opensearch-min-2.0.0-SNAPSHOT-linux-x64-latest.tar.gz

% sha512sum opensearch-min-2.0.0-SNAPSHOT-linux-x64-latest.tar.gz
00d00d8d06afb2212930ee5b5e8f704a305ae90ce75d131cb6b89e94a5d23ff443f66343c2cbd2718c1b85fee1b133fe23b30cbc95d8c71509482d95df6a5493  opensearch-min-2.0.0-SNAPSHOT-linux-x64-latest.tar.gz
```

**Comment by peterzhuamazon** [comment]
Not only the sha512 is not updated, but also the cloudfront cache is not purged after updating the S3.

**Comment by tmarkley** [comment]
@peterzhuamazon thanks for picking this up! Just an fyi, it's currently blocking us from merging PRs because our test workflow is failing.

**Comment by peterzhuamazon** [comment]
Code is nearly ready in my personal branch.
https://github.com/opensearch-project/opensearch-build/compare/main...peterzhuamazon:opensearch-latestchecksum-1497?expand=1

However, just recently discovered that dashboards min artifacts is not being updated at all.
This is likely due to dashboards doesnt have SNAPSHOTS build yet.
https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/opensearch-dashboards/distribution-build.jenkinsfile

A second PR is required to resolve dashboards issues.
My PR can only resolve the opensearch issues and add some setups preparing for dashboards.

Thanks.

**Comment by kavilla** [comment]
> My PR can only resolve the opensearch issues and add some setups preparing for dashboards.

Yeah, can create an issue to look and I can take it up.

**Comment by peterzhuamazon** [comment]
> > My PR can only resolve the opensearch issues and add some setups preparing for dashboards.
> 
> Yeah, can create an issue to look and I can take it up.

https://github.com/opensearch-project/opensearch-build/issues/1577

Thanks.
