### ISSUE TITLE
Run CCR Perf tests as part of Jenkins CI

### ISSUE THREAD

**Issue by ankitkala** [opensearch-project/opensearch-build#1500]
### Is your feature request related to a problem? Please describe

https://github.com/opensearch-project/opensearch-build/issues/1428

### Describe the solution you'd like

After all tasks mentioned in https://github.com/opensearch-project/opensearch-build/issues/1428 are complete, we need to work towards enabling these tests as part of Jenkins CI.

**Comment by bbarani** [comment]
@ankitkala Can you update the progress of this issue?

**Comment by bbarani** [comment]
@ankitkala Can you update the progress of this issue? Is this still actively worked upon?

**Comment by bbarani** [comment]
@ankitkala Can you update the progress of this issue? Can we close this issue?
