### ISSUE TITLE
Document signing (do we sign with SHA256?)

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#1502]
### Is your feature request related to a problem? Please describe

The [documentation on signing](https://github.com/opensearch-project/opensearch-build#signing-artifacts) is very sparse. We have a non-open-source signer black box, but even simple questions like "do we sign with SHA256" cannot be easily answered.

### Describe the solution you'd like

Document what is being signed, when, and how, with what keys, algorithms, etc.

### Additional context

Coming from https://github.com/opensearch-project/opensearch-build/issues/1452#issuecomment-1015767175 and https://github.com/opensearch-project/opensearch-build/issues/27#issuecomment-858058677

**Comment by gaiksaya** [comment]
[Triage] We will add documentation as much as possible.

**Comment by peterzhuamazon** [comment]
All the code are in the scripts folder.
Digest creation and signing the rpms and yum repos.
To cut it short we go a step further with SHA512.

**Comment by justchris1** [comment]
Are you adding a signature for SHA512, or replacing the SHA256 signature with SHA512?

**Comment by peterzhuamazon** [comment]
> Are you adding a signature for SHA512, or replacing the SHA256 signature with SHA512?

We just define our signing process to use SHA512.
If you do not define algorithm it defaults to SHA1.
Many rpms use SHA256, we use SHA512.

```
Header V4 RSA/SHA512 Signature, key ID 9310d3fc
Header SHA256 digest
Header SHA1 digest
Payload SHA256 digest
V4 RSA/SHA512 Signature, key ID 9310d3fc
MD5 digest
```
