### ISSUE TITLE
[Python Typechecking] CI workflow `pipenv run mypy src\ci_workflow tests\tests_ci_workflow`

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#1508]
See full instructions at https://github.com/opensearch-project/opensearch-build/issues/1237

Acceptance criteria:
 - Run `pipenv run mypy src/ci_workflow tests/tests_ci_workflow` passes without error

**Comment by abhinavGupta16** [comment]
Keeping the issue open for remaining fixes - https://github.com/opensearch-project/opensearch-build/pull/1582#pullrequestreview-870834996

**Comment by zelinh** [comment]
Closing this issue after additional fixes.
