### ISSUE TITLE
[PATCH RELEASE ] - 1.0.1  patch release

### ISSUE THREAD

**Issue by elfisher** [opensearch-project/opensearch-build#151]
There is [an issue](https://github.com/opensearch-project/index-management/issues/108) in Index Management that breaks backwards compatibility in the response body of individual explain requests. To address this issue there will be a 1.0.1 patch release. This will be tracked in the [project roadmap](https://github.com/orgs/opensearch-project/projects/1) along side the other releases. 

If there are any additional bugs that will be patched as part of 1.0.1, please comment on this issue so that it can be incorporated.

**Comment by tmarkley** [comment]
For Dashboards: 
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/704
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/699
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/698

We also have a set of documentation improvements/fixes that should at least go into our 1.0 branch: https://github.com/opensearch-project/OpenSearch-Dashboards/pulls?q=is%3Apr+is%3Aclosed+label%3Adocs+label%3Av1.1.0

**Comment by elfisher** [comment]
> For Dashboards:
> [opensearch-project/OpenSearch-Dashboards#704](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/704)
> [opensearch-project/OpenSearch-Dashboards#699](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/699)
> [opensearch-project/OpenSearch-Dashboards#698](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/698)
> 
> We also have a set of documentation improvements/fixes that should at least go into our 1.0 branch: https://github.com/opensearch-project/OpenSearch-Dashboards/pulls?q=is%3Apr+is%3Aclosed+label%3Adocs+label%3Av1.1.0

@tmarkley do you want me to go ahead and add these to the 1.0.1 patch release in the roadmap?

**Comment by nebulon42** [comment]
Maybe too late to the party but just wanting to bring an issue with demo certificates in the container images to your attention which IMO will prevent production use of said container images. See #254.

**Comment by bbarani** [comment]
Closing this issue as we have released 1.0.1 version - https://discuss.opendistrocommunity.dev/t/opensearch-1-0-1-is-now-available/6905
