### ISSUE TITLE
Integrate docker promotion and promoteArtifacts to run together

### ISSUE THREAD

**Issue by abhinavGupta16** [opensearch-project/opensearch-build#1516]
### Is your feature request related to a problem? Please describe

Currently, during a release, we manually trigger a job to promote artifacts from staging to production. We then have to manually trigger a job to move the image from staging to production. We need to add copying docker image from staging to prod as a part of the promotion steps. 

### Describe the solution you'd like

`copyDockerImage.groovy` could be used to copy images from staging to production.
This can be done in one of 2 ways - 
1. Create a new job which can trigger `promoteArtifacts` and `copyDockerImage` in parallel
2. Integrate `copyDockerImage` with the current `promoteArtifacts`

### Acceptance Criteria
- [ ] Manual step to move docker image from staging to prod is automated.

**Comment by bbarani** [comment]
@peterzhuamazon @gaiksaya @prudhvigodithi Is this still a valid issue?

**Comment by prudhvigodithi** [comment]
This issue should be resolved with this PR 
https://github.com/opensearch-project/opensearch-build/pull/2128

**Comment by peterzhuamazon** [comment]
Closed for now as #2128 is merged.
