### ISSUE TITLE
Integrate `docker-build-with-ecr` job with `buildDockerImage.groovy`

### ISSUE THREAD

**Issue by abhinavGupta16** [opensearch-project/opensearch-build#1518]
### Is your feature request related to a problem? Please describe

After the `docker-build-with-ecr` is tested throughly, we need to replace `docker-build` with `docker-build-with-ecr` 
 in the [buildDockerImage.groovy](https://github.com/opensearch-project/opensearch-build/blob/main/vars/buildDockerImage.groovy#L20)

### Describe the solution you'd like

Change `buildDockerImage.groovy` to use `docker-build-with-ecr` to build image instead of `docker-build`

### Acceptance Criteria
- [ ] `buildDockerImage.groovy` uses `docker-build-with-ecr` instead of `docker-build`
- [ ] remove `docker-build` job
- [ ] docker images are automatically built and published on `docker-hub` and `ecr` as a part of opensearch-ci builds

**Comment by prudhvigodithi** [comment]
We can directly rename the job `docker-build-with-ecr` to `docker-build` once the code is battle tested, this was not need to touch the shared library [buildDockerImage.groovy](https://github.com/opensearch-project/opensearch-build/blob/main/vars/buildDockerImage.groovy#L18)

**Comment by prudhvigodithi** [comment]
PR: https://github.com/opensearch-project/opensearch-build/pull/2128 
add's `docker-copy.jenkinsfile` that should support image copy across DockerHub and ECR registries, leaving existing docber-build job untouched (just renamed the file to `docker-build.jenkinsfile`, the logic remains the same.)
