### ISSUE TITLE
Correct copyright notices to reflect Copyright OpenSearch Contributors

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#152]
Coming from https://github.com/opensearch-project/.github/issues/21.

The correct copyright for open-source projects in opensearch-project is "Copyright OpenSearch Contributors". Please correct any places that say otherwise, especially where it says copyright Amazon. Make sure NOTICE.txt and README match. See https://github.com/opensearch-project/.github/pull/24 for an example.

**Comment by AMoo-Miki** [comment]
The correct header for files like [this one](https://github.com/opensearch-project/opensearch-build/blob/main/config/opensearch_dashboards.yml) is:

```
# Copyright OpenSearch Contributors
# SPDX-License-Identifier: Apache-2.0
```

For files that contain attribution to an external project, place this long version above those of the external project(s).

```
# Copyright OpenSearch Contributors
# SPDX-License-Identifier: Apache-2.0
#
# The OpenSearch Contributors require contributions made to
# this file be licensed under the Apache-2.0 license or a
# compatible open source license.
#
# Modifications Copyright OpenSearch Contributors. See
# GitHub history for details.
```

Here is a rough list of files that need to change:
https://github.com/opensearch-project/opensearch-build/search?q=copyright+amazon.com+reserved
