### ISSUE TITLE
[Bug]: 1.3.0 OpenSearch distribution build fails to come up

### ISSUE THREAD

**Issue by qreshi** [opensearch-project/opensearch-build#1523]
### Describe the bug

It looks as though the 1.3.0 staging Docker image might be failing to come up due to the `InitialBootClassLoaderMetaspaceSize` VM option used by the PA plugin.

The container logs outputted just showed the following:
```
Enabling OpenSearch Security Plugin
Killing opensearch process 130
OpenSearch exited with code 143
Performance analyzer exited with code 1
```

Logging onto the container itself and running the entry point script manually produced the following PA logs (no other logs under the `/logs` directory):
```
sh-4.2$ cat performance-analyzer.log
Unrecognized VM option 'InitialBootClassLoaderMetaspaceSize=30720'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

When searching older issues I came across opensearch-project/opensearch-build#504 which had `"OpenJDK 64-Bit Server VM warning: Option InitialBootClassLoaderMetaspaceSize was deprecated in version 15.0 and will likely be removed in a future release."` in one of the log entries as well which supports the claim of its removal.

### To reproduce

1. Pull 1.3.0 staging docker image: `docker pull opensearchstaging/opensearch:1.3.0`
2. Run it: `docker run -p 9200:9200 -d -p 9600:9600 -e "discovery.type=single-node" opensearchstaging/opensearch:1.3.0`

### Expected behavior

Container coming up successfully.

**Comment by reta** [comment]
@saratvemulapalli correct,  and removed in JDK-16 (in scope of https://bugs.openjdk.java.net/browse/JDK-8221173)

**Comment by peterzhuamazon** [comment]
This is resolved now thanks @reta.

**Comment by qreshi** [comment]
Just a follow-up here, I don't think it's an opensearch-build issue now but the PA plugin also needs to remove its references to the VM option.

I saw the following two references to it:
* [build.gradle](https://github.com/opensearch-project/performance-analyzer-rca/blob/05cfc8dabe1cc4a833467c4e61e10dbe4647f6ba/build.gradle#L56)
* [CLI script](https://github.com/opensearch-project/performance-analyzer/blob/cb34f28656a03a4291ecaafce1f580b6fdb96742/packaging/performance-analyzer-agent-cli#L5)

I believe the error is still coming up in the Docker image because of this

**Comment by peternied** [comment]
@qreshi Can you create an issue in the PA repo to track?

**Comment by qreshi** [comment]
@peternied Would it be possible to re-open this and move it to the PA repo since its the same issue?

**Comment by peternied** [comment]
I'd recommend creating fresh issues for each area that needs following up, linking back to this issue seems appropriate.

**Comment by reta** [comment]
@qreshi we could add new issue (s) to PA repos (pull requests are out already)
