### ISSUE TITLE
Publish logstash-oss-with-opensearch-output-plugin:7.16.3

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/opensearch-build#1532]
Core: Logstash OSS 7.16.3 ( this has CVE update )
Plugin: https://github.com/opensearch-project/logstash-output-opensearch/ ( v1.2)

Distribution:
Docker image
tar ( macos x64, linux x64, linux arm64)

**Comment by gaiksaya** [comment]
Hi @VijayanB Is there an estimated date of release?

**Comment by VijayanB** [comment]
This is now available at https://opensearch.org/downloads.html
