### ISSUE TITLE
[Bug]: WhiteSource integration PR check is not sync with latest vulnerability library

### ISSUE THREAD

**Issue by zelinh** [opensearch-project/opensearch-build#1533]
### Describe the bug

WhiteSource integration CVEs libraries is not updated with latest CVEs scanned for PR check. The baseline library called `base branch commit` WhiteSource compared for difference in PR check is often quite old and not showing the exact most recent CVEs fix/introduce. 

### To reproduce

When creating a PR for modifying dependencies. 

### Expected behavior

The PR CVEs diff check should compared to the latest scanned commit instead of the `base branch commit`.

**Comment by zelinh** [comment]
Creating this issue as reference. According to WhiteSource support, this issue would be improved in the upcoming version 22.1.2 (planned release of Feb 7th). By then, the comparison will be made to the latest commit that triggered a scan in main, and we should see completely up to date vulnerability information in the PR scans.

**Comment by gaiksaya** [comment]
[Triage] Whitesource is working is on this issue.

**Comment by bbarani** [comment]
@zelinh can you check and close this issue if it has been resolved by Whitesource?

**Comment by zelinh** [comment]
This was supposed to be resolved in the version I mentioned above. However, I noticed this issue still existed in the recent scan and confirmed with WhiteSource support last week. They are looking at this issue again.

**Comment by bbarani** [comment]
I am closing this issue as we dont have any action items from our side to fix this issue. Please update this issue once you hear back from Whitesource.

**Comment by zelinh** [comment]
I found that recently WhiteSource released a new version saying this issue on diff check has been fixed. 
https://whitesource.atlassian.net/wiki/spaces/WD/pages/817037652/Developer+Integrations+Release+Notes#Resolved-Issues. 
We currently don't have a PR triggering the scan; will check back once the integration PR check triggered.
