### ISSUE TITLE
[Bug]: 1.2.4 snapshot artifacts missing

### ISSUE THREAD

**Issue by qreshi** [opensearch-project/opensearch-build#1535]
### Describe the bug

1.2.4 snapshot artifacts can no longer be found [in the staging repo](https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/).

This is causing anything building using `1.2.4-SNAPSHOT` to fail. Since `1.2.4` has already released should all consumers be updating their references of `1.2.4-SNAPSHOT` to `1.2.4`?

### To reproduce

Attempt to build anything currently using `1.2.4-SNAPSHOT`.

### Expected behavior

Either continue to have `-SNAPSHOT` dependencies present for even previous versions or require all consumers to update to use the released artifact in builds after release of the version in question.

**Comment by qreshi** [comment]
I also forgot to mention that if we are expected to not build with snapshot on already released versions, we can include `-Dbuild.snapshot=false` when building assuming the build scripts account for it (which they should).

**Comment by peterzhuamazon** [comment]
Checking jenkinsfile, it should still upload to the snapshot repo in every run:
https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/opensearch/distribution-build.jenkinsfile#L30-L63

**Comment by peterzhuamazon** [comment]
However, it is not showing for a couple of releases.
![Screen Shot 2022-01-24 at 5 56 23 PM](https://user-images.githubusercontent.com/65193828/150878796-964635b9-26ff-4869-80d6-7f75e44927ca.png)



In fact, I also dont see js spi anymore
![Screen Shot 2022-01-24 at 5 57 22 PM](https://user-images.githubusercontent.com/65193828/150878846-4ea8b38e-c156-4d09-946a-582cc4f77462.png)
.

**Comment by peterzhuamazon** [comment]
Seems like uploading complete in 644 for 1.2.4 releases:
```
Uploaded to nexus: https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/opensearch/maven-metadata.xml (504 B at 30 kB/s)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.192 s
[INFO] Finished at: 2022-01-14T04:00:46Z
[INFO] ------------------------------------------------------------------------
Skipping upload for ./org/opensearch/opensearch/1.2.4-SNAPSHOT/opensearch-1.2.4-20220114.034255-1.jar.md5
Skipping upload for ./org/opensearch/opensearch/1.2.4-SNAPSHOT/opensearch-1.2.4-20220114.034255-1.jar.sha1
Skipping upload for ./org/opensearch/opensearch/1.2.4-SNAPSHOT/opensearch-1.2.4-20220114.034255-1.jar.sha256
Skipping upload for ./org/opensearch/opensearch/1.2.4-SNAPSHOT/opensearch-1.2.4-20220114.034255-1.jar.sha512
Skipping upload for ./org/opensearch/opensearch/1.2.4-SNAPSHOT/opensearch-1.2.4-20220114.034255-1.module
Skipping upload for ./org/opensearch/opensearch/1.2.4-SNAPSHOT/opensearch-1.2.4-20220114.034255-1.module.md5
Skipping upload for ./org/opensearch/opensearch/1.2.4-SNAPSHOT/opensearch-1.2.4-20220114.034255-1.module.sha1
Skipping upload for ./org/opensearch/opensearch/1.2.4-SNAPSHOT/opensearch-1.2.4-20220114.034255-1.module.sha256
Skipping upload for ./org/opensearch/opensearch/1.2.4-SNAPSHOT/opensearch-1.2.4-20220114.034255-1.module.sha512
Skipping upload for ./org/opensearch/opensearch/1.2.4-SNAPSHOT/opensearch-1.2.4-20220114.034255-1.pom.md5
Skipping upload for ./org/opensearch/opensearch/1.2.4-SNAPSHOT/opensearch-1.2.4-20220114.034255-1.pom.sha1
Skipping upload for ./org/opensearch/opensearch/1.2.4-SNAPSHOT/opensearch-1.2.4-20220114.034255-1.pom.sha256
Skipping upload for ./org/opensearch/opensearch/1.2.4-SNAPSHOT/opensearch-1.2.4-20220114.034255-1.pom.sha512
Finished uploading ./org/opensearch/opensearch/1.2.4-SNAPSHOT
Skipping upload for ./org/opensearch/os/1.2.4-SNAPSHOT/maven-metadata.xml
Skipping upload for ./org/opensearch/os/1.2.4-SNAPSHOT/maven-metadata.xml.md5
Skipping upload for ./org/opensearch/os/1.2.4-SNAPSHOT/maven-metadata.xml.sha1
Skipping upload for ./org/opensearch/os/1.2.4-SNAPSHOT/maven-metadata.xml.sha256
Skipping upload for ./org/opensearch/os/1.2.4-SNAPSHOT/maven-metadata.xml.sha512
Uploading: ./org/opensearch/os/1.2.4-SNAPSHOT/os-1.2.4-20220114.034255-1.jar with ./org/opensearch/os/1.2.4-SNAPSHOT/os-1.2.4-20220114.034255-1.pom to https://aws.oss.sonatype.org/content/repositories/snapshots/
```

**Comment by peterzhuamazon** [comment]
Skipped due to:
https://github.com/opensearch-project/opensearch-build/blob/main/publish/publish-snapshot.sh#L121-L130

Seems like it only skipped all the checksum file so other files should upload to snapshot repo.

**Comment by peterzhuamazon** [comment]
This is probably due to data retention policy:
https://help.sonatype.com/iqserver/managing/data-retention-and-purging

The confusing part is, why is 1.2.1-1.2.4 not on the list, as they are less than 3 months.
If we are using the default policy.

We probably need to open a ticket with sonatype.

I do want to get your guys opinion on this @dblock @peternied before I send out the ticket.

Thanks.

**Comment by peternied** [comment]
Are there any processes that could be deleting those artifacts, what does an audit the access to those credentials show?

Unless we find a smoking gun in a couple minutes let's file the ticket, artifacts are disappearing and I don't know what the turn around will be.

**Comment by peterzhuamazon** [comment]
I have created issue with sonatype as I cannot find anything else related to this issue for now.
https://issues.sonatype.org/browse/OSSRH-77609

Thanks.

**Comment by peterzhuamazon** [comment]
Joel from Sonatype has replied with these:
```
Here's the current configuration of the Remove Snapshots scheduled task (which runs weekly, specifically every Sunday afternoon):

What this config tells me is that a minimum of 4 snapshots will be retained. Any snapshots 2 days or older will be removed. Also, any snapshot versions that have had an analogous release version published will be deleted 2 days after the release was published.

I'm happy to adjust these settings to meet your requirements.

```

![image](https://user-images.githubusercontent.com/65193828/151039026-d5665878-3e45-48dd-baa7-3d2831facf7a.png)


@dblock @peternied this seems to me that our artifacts are deleted too often and frequent.
Shall we completely disable this scheduled cleanup, or shall we change the settings to some larger value?

I am questioning whether we need all the snapshots after a certain amount of time.

Thanks.

**Comment by peternied** [comment]
I'm not sure how this policy is applied, as it is strange that we have 1.0.1-SNAPSHOTS.
I think the minimally appropriate policy looks like this:
- For all build versions (1.0.0, 1.2.3, 1.2.4, 1.3.0,...)
  - Keep the at least the last set of snapshot binaries for that version indefinitely

Consider the current policy, it looks like 4 snapshots are preserved, so that could be our minimum number of binaries.  The current weekly execution seems reasonable, but I would prefer it if it was daily so anyone depending on a hardcoded reference would be broken as soon as possible.

**Comment by peterzhuamazon** [comment]
My response:

```
Hi Joel, After talking to my team, the decision is to `DISABLE` the retention scheduled task.

We want to keep every copy of our snapshot, and seems like if we push to a folder that already exist, the old content will be overwritten anyway.

As for the disk usage, would you let us know what is the limit on that?

Thanks.


```

**Comment by peterzhuamazon** [comment]
We disable retention, reply from Joel.
```
Don't worry about the disk usage. We use a single set of volumes for release and snapshot storage, and we expect to have to continue to add disk for new release versions that get published. Not cleaning up snapshots just means that we may have to add disk more frequently.

The scheduled task for snapshot cleanup is currently disabled.

```

**Comment by peternied** [comment]
@peterzhuamazon Have we published replacement artifacts?

**Comment by peterzhuamazon** [comment]
> @peterzhuamazon Have we published replacement artifacts?


https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/opensearch/1.2.4-SNAPSHOT/
1.2.4 is already published and the new purge was not happening until Sunday.
Therefore, we have 1.2.4 as of now.
