### ISSUE TITLE
How can OpenSearch-Build make sure it does not create a breaking change for external workflows?

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#1536]
As the workflow scripts are not located in the same repository, there need to be protections to be sure that these workflows are not broken when changes are made.

Having a list of all registered component repositories, a way to find all of the workflows, and then execute them to verify they have not regressed would be a way to do this.

Acceptance Criteria:
 - [ ] Determine the relationship between OpenSearch-Build and test repositories
   - OpenSearch-Build has a library of tools, make sure client workflows have access as well as are checked to verify that have not been broken by an interface change.  This seems to be a set of regression tests with all libraries included
 - [ ] How will checks be run during pull requests to make sure that workflows in other repositories are not broken?
 - [ ] What happens if someone breaks the workflow on their side, is there an inverse check to make sure aren't out of alignment with the central repository?

**Comment by gaiksaya** [comment]
One approach to avoid breaking change is my keeping regressions files in build repository and jenkins Files in component repository. In this way when a change is introduced, the regression files will test the change for remote JenkinsFiles as well. 
Failure would suggest a change needs to be made on remote file as well

**Comment by gaiksaya** [comment]
https://github.com/opensearch-project/opensearch-build/issues/1534#issuecomment-1220700133

**Comment by gaiksaya** [comment]
Versioning is the way to go forward. If anyone has something better please let us know. Created an issue to track this during implementation https://github.com/opensearch-project/opensearch-build/issues/2489
