### ISSUE TITLE
What modifications are needed for the input / build / dist manifests?

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#1537]
Assuming that input / build / dist manifests files are created for all opensearch projects, are many changes needed?

An input manifest determines the code that is pulled along with some checks/target information.  The build manifest holds the data about a built project, and the dist manifest is all of the files that are included in the distribution (for most OpenSearch projects this is only one project so its less interesting.)

- What improvements do we need with the current process?

Acceptance Criteria:
- [ ] Are full fledged implementations of the input manifest needed, related to https://github.com/opensearch-project/opensearch-build/issues/1506.
- [ ] Can build manifests be generated from a tool rather than requiring each build system to create them?
- [ ] Are distribution manifests useful?
- [ ] Document when are the manifests used in the release process, and update the workflow diagrams.

**Comment by gaiksaya** [comment]
Closing this issue since we will be going ahead with GitHub release as a mode of trigger for the release.
Thanks!
