### ISSUE TITLE
Where should manifest files be placed, and what branch?

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#1538]
Input manifests / 'what is going to be released' and the release workflow information needs to be managed somewhere, as it will be in the repository of the project what is the organization model.

Acceptance Criteria:
 - [ ] Determine the folder structure that the release process will have in the OpenSearch project repository
 - [ ] Determine what branches should be updated with the data
   - Does it matter if the branch that is released is independent of the release configuration?
 - [ ] Update the release workflow with the logistics of a release  with an updated diagram

**Comment by gaiksaya** [comment]
Closing this issue since we will be going ahead with GitHub release as a mode of trigger for the release.
Thanks!
