### ISSUE TITLE
Adopt a default integtest.sh

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#154]
**Is your feature request related to a problem? Please describe.**

Looking at how https://github.com/opensearch-project/opensearch-build/pull/138 is implemented and the proliferation of https://github.com/opensearch-project/anomaly-detection/blob/main/integtest.sh that are identical repo-to-repo, adopt a similar system with a default implementation as in https://github.com/opensearch-project/opensearch-build/tree/main/tools/bundle-build. I expect to cut down the scripts by 75% as most implementations are gradle-based.

**Describe the solution you'd like**
1. Create a default version of integtest.sh in `scripts` in this repo, and use it unless an override version is present.
2. Optionally support override versions in `scripts` in this repo. 
3. Delete every copy-pasted integtest.sh in each repo that looks like the default.
4. Move integtest.sh from root to `scripts/` in each repo, we're making a mess.

**Comment by dblock** [comment]
@saratvemulapalli

**Comment by saratvemulapalli** [comment]
@dblock I think this is already taken care of. 
Feel free to reopen this if there is any thing else needed.
Ref: https://github.com/opensearch-project/opensearch-build/blob/main/bundle-workflow/scripts/default/integtest.sh
