### ISSUE TITLE
OSX Releases

### ISSUE THREAD

**Issue by taf2** [opensearch-project/opensearch-build#1542]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Elasticsearch released zip files for macosx.  This was very nice as it was pretty self contained and just worked... I see only docker and linux options here... 

**Describe alternatives you've considered**
Staying elasticsearch seems easier then switching how we do things... 

**Additional context**
This would just be nice and make it easier to adopt...

**Comment by CEHENKLE** [comment]
Hey @taf2 !   Thanks for the feedback.  We're tracking a mac distribution in #38  I'm going to resolve this issue, but please track the work there. 

Thanks again,
/C

**Comment by taf2** [comment]
Thanks!
