### ISSUE TITLE
Does the output manifest in bundle-build need to match 100% the existing 1.0 manifest

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#155]
**Is your feature request related to a problem? Please describe.**

Looks like https://artifacts.opensearch.org/builds/opensearch/1.0.0/manifest.yml is slightly different from what bundle-build is generating after #150. Do we need to make bundle-build the same?
 
**Describe the solution you'd like**

Some trivial key renaming would be needed, like `sha` -> `commit` and such.

**Comment by mch2** [comment]
The format of https://artifacts.opensearch.org/builds/opensearch/1.0.0/manifest.yml is going to change with whats proposed in #111.  We also should treat these as separate entities.  This is how I'm thinking about this:

InputManifest -> Static file that lives in the repo that tells us how to build
BuildManifest -> Output of a build that lists all components/libs built, this is the input to a bundle assembly.
BundleManifest -> Output of a bundle build, only includes core + list of plugins installed and their locations (s3/local path).

While there is overlap here in terms of fields/properties, the files themselves have different use cases.  I'll see if I can reuse some code here during their generation if that simplifies things.

**Comment by mch2** [comment]
Closing this issue. We have both manifests being built as separate entities.
