### ISSUE TITLE
[RPM M4] Publish individual package

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#1550]
Tasks | Estimate | Status | Notes | Dependencies
-- | -- | -- | -- | --
Update the link of the RPM package on S3/CloudFront to our website download pages | 1 | Complete |   | Need PR to website related repos for this
Provide ability to manually download the RPM package with the link | 1 | Complete |   |  
Add ability to install the package manually with YUM/RPM command on their server, or they can deploy the package to their own internal repo and consume with YUM | 1 | Complete | Once user has the package they can do whatever they prefer to utilize the package |  
Add instructions and download page to opensearch.org website | 1 | In Review | | |

**Comment by peterzhuamazon** [comment]
@stockholmux Please attach the website PR for publishing individual rpm packages to here.
Thanks.

**Comment by peterzhuamazon** [comment]
The ground function of promoting rpm to production S3 is already there.

**Comment by stockholmux** [comment]
Tracking on https://github.com/opensearch-project/project-website/issues/772
