### ISSUE TITLE
[Proposal] Support AL2023/NodeJS18 for OpenSearch/Dashboards Releases

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#1563]
With the announcement of Amazon Linux 2023 Preview available for testing, we want to setup some notes here for the support of AL2023 once it is fully released to public.
https://aws.amazon.com/about-aws/whats-new/2021/11/preview-amazon-linux-2022/
https://aws.amazon.com/about-aws/whats-new/2023/03/amazon-linux-2023/

* Evaluate the compatibility of AL2023 when running OpenSearch/Dashboards
  * OpenSearch/Dashboards latest binary can run on AL2023 with the same expected behaviors on AL2
  * Working alongside plugin teams to ensure all the plugins are running as expected
  * Performance testing to ensure there is no performance regression
  * Evaluate the package/dependencies availability on AL2023 default repository
  * Evaluate the size of the image vs contents integrity
* Evaluate AL2023 availability
  * AL2023 available on docker for both x64 and arm64
  * AL2023 available on EC2 for both x64 and arm64 for testing
* Evaluate Build Process
  * What level of changes do we need to support AL2023 with current build process and scripts
  * Can we support both AL2 and AL2023 in the same system
  * Build tool related libs/packages/dependencies availability on AL2023
* Evaluate deprecation plan for older OS
  * When would we deprecate AL2 while supporting AL2023
  * Will this introduce breaking changes to customer
  * Would we support older version of OpenSearch/Dashboards with new OS?

We welcome more discussion on this.

Thanks.

**Comment by peterzhuamazon** [comment]
Hi @nknize @dblock what do you think about this change?

From our teams perspective it makes sense to upgrade the main docker image from AL2 to AL2023 starting 3.0.0. It also make sense that we use this opportunities to upgrade other OS such as Ubuntu and Rockylinux to their latest versions.

Thanks.

**Comment by dblock** [comment]
I really don't know enough about this @peterzhuamazon. What are pros/cons?

**Comment by peterzhuamazon** [comment]
Now with this issue on the horizon, we need to also think about how to proceed with the changes:
* opensearch-project/opensearch-dashboards#3601 


This means:
* We have to deprecate ci image that uses centos7 or al2.
* Our ci and release docker images have to move from al2 to al2023
* #3351 
  * Python upgrade from 3.7 to 3.9 must follow as al2023 is default to newer version of python
  * AL2 has python 3.7 by default but AL2023 is already bundled with 3.9. It would take longer time just try to compile Python 3.7 on AL2023.
* KNN will 100% break for certain old OS users if we still use the same docker image for 1.x / 2.x / 3.x, as centos7 is the pinnacle of KNN, as it has the oldest glibc version which does not support Node18. 
  * https://github.com/opendistro-for-elasticsearch/k-NN/issues/169
  * Unless we add a new jenkinsfile just for 1.x, we cannot tweak the existing dist-build-dashboards jenkinsfile too much as it is near the size limit of Jenkinsfile max size.
  * Adding a new jenkinsfile just for 1.x will break a lot of the internal hardcoded folder structure on S3
  * One way to avoid this is that OS has to use centos7 to build and OSD has to use al2023 to build, which is very unformalized and hard to maintain.
* This has to happen after Jenkins Upgrade complete
  * https://github.com/opensearch-project/opensearch-ci/pull/277
* This is a major breaking change and seems like they are trying to backport to 2.x as well due to node14 is deprecated and we cannot ship a deprecated product.

**Comment by bbarani** [comment]
Tagging @vamshin @seanneumann for visibility.

**Comment by seanneumann** [comment]
For the Node 18 upgrade, we're targeting 2.8. This is important as Node 14 no longer will receive security updates (as of April 2023). Is there an ask to delay to solve the above?

**Comment by peterzhuamazon** [comment]
KNN support on the native code compilation:
```
node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by node)
node: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by node)
node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by node)
node: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by node)
node: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by node)
node: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by node)
```


```
# CentOS8/RockyLinux8
ldd (GNU libc) 2.28

# CentOS7
ldd (GNU libc) 2.17

# AL2
ldd (GNU libc) 2.26

# AL2023
ldd (GNU libc) 2.34
```
Seems like if we want to switch from CentOS7 to CentOS8, we will need to remove support of CentOS7 and AL2 from our support matrix on our website as well, since CentOS8/RockyLinux8 is the baseline of node18 with glibc 2.28.
https://github.com/nodejs/node/issues/43246


https://opensearch.org/docs/latest/opensearch/install/compatibility/
cc: @krisfreedain

**Comment by krisfreedain** [comment]
> we will need to remove support of CentOS7 and AL2 from our support matrix on our website as well, since CentOS8/RockyLinux8 is the baseline of node18 with glibc 2.28

I would agree @peterzhuamazon - if we test on CentOS8/RockyLinux8 the compatibility matrix needs to be updated to accurately reflect that for the community

**Comment by ananzh** [comment]
Hi @peterzhuamazon we will bump the node.js to version `18.16.0`

**Comment by jmazanec15** [comment]
@peterzhuamazon want to clarify, you are saying that node 18 requires 2.28, correct? Then doesn't this break compatibility with AL2 and centos 7? So, regardless of k-NN libs, upgrading to Node 18 would require us to remove centos 7 and AL2 from the compatibility matrix.

If this is not the case, we could also elect to compile k-NN libs in separate docker image to maintain compatibility.

**Comment by joshuali925** [comment]
@peterzhuamazon not sure if you saw this https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3601#issuecomment-1555160621

unlike chromium, it is possible to do a custom build of nodejs on centos 7 to lower glibc dependencies (I also saw musl builds somewhere, which can be another possibility to workaround this issue). I've not looked into performance or other issues might be caused by downgrading glibc, but if OS upgrade is difficult maybe this would be easier?

**Comment by anirudha** [comment]
Did anyone confirm node 18 with AL2? @seanneumann 

We noticed some glibc related compatibility issues. Not sure if it's an isolated incident.

**Comment by peterzhuamazon** [comment]
> @peterzhuamazon not sure if you saw this [opensearch-project/OpenSearch-Dashboards#3601 (comment)](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3601#issuecomment-1555160621)
> 
> unlike chromium, it is possible to do a custom build of nodejs on centos 7 to lower glibc dependencies (I also saw musl builds somewhere, which can be another possibility to workaround this issue). I've not looked into performance or other issues might be caused by downgrading glibc, but if OS upgrade is difficult maybe this would be easier?

That is likely not an option because CentOS7 is going to be out of support in 1 year, and we are also on track to move to al2023 anyway. Manually rebuild nodejs18 would add another dep on our side, which is not going to scale on the long run.

Thanks.

**Comment by AMoo-Miki** [comment]
> Did anyone confirm node 18 with AL2? @seanneumann
> 
> We noticed some glibc related compatibility issues. Not sure if it's an isolated incident.

Node 18 will not run on AL2; I tried it.

OSD 2.8 will be compatible with Node 14, 16, and 18. OSD 2.8 will also bundle Node 18 and a Node 14 for fallback; with this OSD 2.8 can run on AL2 by using the bundled Node 14.

**Comment by peterzhuamazon** [comment]
> @peterzhuamazon want to clarify, you are saying that node 18 requires 2.28, correct? Then doesn't this break compatibility with AL2 and centos 7? So, regardless of k-NN libs, upgrading to Node 18 would require us to remove centos 7 and AL2 from the compatibility matrix.
> 
> If this is not the case, we could also elect to compile k-NN libs in separate docker image to maintain compatibility.

1. It does, al2/centos7 have older libs than 2.28.
2. Agreed that we need to move out of centos7 and al2 at some point.

**Comment by peterzhuamazon** [comment]
> > Did anyone confirm node 18 with AL2? @seanneumann
> > We noticed some glibc related compatibility issues. Not sure if it's an isolated incident.
> 
> Node 18 will not run on AL2; I tried it.
> 
> OSD 2.8 will be compatible with Node 14, 16, and 18. OSD 2.8 will also bundle Node 18 and a Node 14 for fallback; with this OSD 2.8 can run on AL2 by using the bundled Node 14.

If node14 out of support can we even bundle a 14 alongside 18 together?

**Comment by AMoo-Miki** [comment]
@peterzhuamazon I hate it but being a minor release, we have to.

**Comment by peterzhuamazon** [comment]
Here are some of the update to the situation:

# AL2023 / NodeJS18 Upgrade Status on 2.8.0 Release

## Background

With the release of OpenSearch Project 2.8.0 approaching on 2023/06/06, and the [end-of-life for NodeJS 14](https://github.com/nodejs/release#release-schedule) just three weeks ago on 2023/04/30, we want to review the current situation regarding the necessary upgrade to the latest LTS NodeJS 18. 

This upgrade will require significant changes, and our goal is to lay out the steps for each stakeholder involved in the release, review essential items, and find a path forward.

We have a related issue opened to capture all required actions, and synced some part of the comments to this quip:
https://github.com/opensearch-project/opensearch-build/issues/1563

## Status

* **OSD Team:** @AMoo-Miki @ananzh 
    * NodeJS 18 Annoucement:
        * [Bump Node.js from 14 to 18 Proposal OpenSearch-Dashboards#3601](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3601)
        * [Upcoming Transition to Node.js v18: Plugin Compatibility Test Required Overall Issue OpenSearch-Dashboards#4058](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4058)
    * NodeJS 18 PR raised: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4071
    * Plan to push the change to main/3.x, then backport to 2.x, would impact upcoming 2.8.0.
    * Plan to support NodeJS 14/16/18 on above branches
    * Plan to use 18.16.0 for the upcoming release
    * Need to start a campaign on all OSD plugin owners to upgrade to 18?
    * NodeJS 18 requires host to have glibc 2.27 version (presumably 2.28 per official NodeJS):
        * [NodeJS 18 revert to building on CentOS 7, RHEL 7, Ubuntu Bionic 18.04, other other LTS distros nodejs/node#43246](https://github.com/nodejs/node/issues/43246)
        * Only unofficial builds have NodeJS 18 supports older glibc versions



* **EE Team:** @peterzhuamazon 
    * _CI Images:_
        * Currently both OS and OSD are using CentOS7 docker images to build and assemble into final artifacts
            * CentOS7 has glibc 2.17 which does not support NodeJS 18
            * We need to move from CentOS7 to RockyLinux8 (Not CentOS8 as CentOS have changed their release from downstream to upstream on dev focused releases)
                * https://blog.centos.org/2020/12/future-is-centos-stream/
            * If possible, we can go ahead and move to AL2023 in case glibc requirement changes again
            * This also means we need to upgrade [opensearch-build](https://github.com/opensearch-project/opensearch-build)repository from Python 3.7 to Python 3.9, as AL2023 defaults to use Python 3.9, while RL8 defaults to 3.6, just like CentOS7.
            * [Migrate build repo code from using Python 3.7 to 3.9 version #3351](https://github.com/opensearch-project/opensearch-build/issues/3351)
                * Python 3.7 support will reach its eol in 1 month (2023/06/27): https://endoflife.date/python
            * New docker files need to be written and tested, and new images need to be built
        * EE uses AL2 AMI as docker host. Although docker containerization means host should not affect containers behavior, we still need to verify this.
            * If needed, new AMI configurations needs to be setup, new AMI needs to be built, and Jenkins needs to be redeployed with all changes
        * Windows NodeJS 18 support on AMI
    * _Release Images:_
        * Currently both OS and OSD are using AL2 base images to encapsulate release artifacts for docker
            * AL2 has glibc 2.26 which does not support NodeJS 18
            * We need to move from AL2 to AL2023 which has glibc 2.34
            * Need to test the docker images properly so it resembles the exact same behavior before upgrade
    * _Release pipeline:_
        * Infra needs to have specific setup just to support 1.x branch OS / OSD building process
        * Initially all 3 lines of artifacts are built on the same docker ci images, now we might need to maintain more than one image for different lines



* **k-NN Team:** @jmazanec15 
    * Since [OpenDistro for ElasticSearch](https://opendistro.github.io/) (ODFE), we specifically build k-NN on CentOS7 due to it has the oldest glibc version 2.17.
        * [Use containers for library artifact build opendistro-for-elasticsearch/k-NN#169](https://github.com/opendistro-for-elasticsearch/k-NN/issues/169)
    * This ensures that the k-NN lib will not crash on any glibc version above 2.17.
    * If we build k-NN nmslib on RockyLinux8, which has glibc 2.28, then k-NN nmslib will crash on CentOS7/AL2 with older versions of the glibc.
    * This also means we need to remove support of CentOS7/AL2 from the compatibility matrix and add RockyLinux 8 / AL2023.
        * https://opensearch.org/docs/latest/opensearch/install/compatibility/





## Approaches

Both OS and OSD keep CentOS7/AL2 for 2.8.0 release, have 16 in build ci and 14/18 bundled in artifacts, move everything to RockyLinux8/AL2023 and NodeJS18 in later releases.

* _Pros:_
    * No changes on OS/OSD base image until needed
    * No k-NN issues to support glibc 2.17, later 2.28
    * More time required to upgrade both OS and OSD, on CI and Release
    * More time on the infra pipelines changes on Jenkins
    * Less changes for customer to consume for a minor/patch version change
    * The 2.8.0 release would have less changes close to freeze date
* _Cons:_
    * The compatibility matrix would need to update to RockyLinux8 and above
    * Still needs to maintain a 1.x specific release outside of 2.x/3.x means more work and temp scripts




## More questions:

* Possibilities of adding 16 for 2.8.0, then 18 for 2.9.0 forward (ans: not bundle 16 as 16 / 18 are much more similar than 14 / 18).
* Need to check whether we bundle both 14 and 18 in the 2.8.0, with automatically switch/fallback options if host does not support 18?
* Does 2.x still use 16 to build and main use 18 to build?
* Later on, users must use nodejs18 and cannot use 14 anymore, more modernized changes?
* Keep our build system building 16 so build system secure in 2.8.0 until move to 18?
* Possible RockyLinux8 and above as new compatibility matrix?


Thanks.

**Comment by ananzh** [comment]
The tested Node.js 16 version is `16.20.0`.

**Comment by peterzhuamazon** [comment]
Need to move the integTest runner to rockylinux8 as well: 
* https://github.com/opensearch-project/opensearch-build/issues/3554

**Comment by peterzhuamazon** [comment]
All docker images updated and synced:
* https://build.ci.opensearch.org/job/docker-copy/502/console

Next is AMI.

**Comment by peterzhuamazon** [comment]
These three will need to get baseOS change to rockylinux8 before adding node18.
These are the only ones do not have node18 on docker images, AMI not affected.

docker/ci/dockerfiles/current/build.centos7.opensearch-dashboards.x64.arm64.dockerfile
docker/ci/dockerfiles/current/release.centos.clients.x64.arm64.dockerfile
docker/ci/dockerfiles/current/test.centos7.performance-test.x64.arm64.dockerfile

**Comment by peterzhuamazon** [comment]
New Bug:
* https://github.com/opensearch-project/opensearch-ci/issues/297

**Comment by peterzhuamazon** [comment]
Rockylinux:8
```

gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-18)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Will switch to devtooset8 on centos7 to match with rockylinux:8 which we will eventually switch to.

**Comment by peterzhuamazon** [comment]
Using scl and devtoolset might be a problem because it requires running `source scl_source enable devtoolset8` either through rc or through profile.

With us locking docker images to non-interactive shell this is not the best option.
Exploring manually compile gcc 8 from source.

**Comment by peterzhuamazon** [comment]
Hi All,

We are going to stay with node16 for 2.9, and plan to move to node18 for 2.10.
This would ensure us to have enough time for the upgrade.
As well as compensate the changes for multiple teams.

We can also start the Python3.9 upgrade process as Python3.7 is about to be eol by 2023/06/23.

Once we go to node18 in 2.10, the support matrix of our product will need to remove these OSes:

* RHEL7&CentOS7 / AmazonLinux2 (glibc2.17 / glibc2.26)
* Ubuntu 16.04 / Ubuntu 18.04 (glibc2.23 / glibc2.27)
(Note: we still bundle node14 as fallback so technically above can still run, but 14 is eol and we do not officially support them anymore)

This also requires that the 2.x branch stays on 16.20.0 in .nvmrc, and have no node18 specific code committed until 2.9.0 is released to the public.

Infra will take care of the node18 upgrade once after 2.9.0.

Thanks.

cc: @CEHENKLE @dblock @seanneumann @AMoo-Miki @ananzh @seraphjiang @vamshin @jmazanec15 @bbarani @hdhalter

**Comment by peterzhuamazon** [comment]
The cmake upgrade to 3.23.3 version was initially setup as a follow up in the al2023 upgrade/nodejs upgrade, tho now it seems like a 2.9.0 dependencies thus it needs to be updated soon.

Thanks.

**Comment by peterzhuamazon** [comment]
## 20230801 Update: (AL2023/NodeJS18 on 2.10.0 Release)

### Required Steps

* Update all AMIs to have NodeJS14/16/18 support.
* Update all CI docker images to have NodeJS14/16/18 support.
* Update all Release docker images to use NodeJS18 as the base node version for OSD.
* Deprecate all CentOS7 images in build systems and replace with the RockyLinux8 images (Except client release image as it does not require nodejs18 by default for now).
* Work with OSD team members to ensure all OSD core and plugins are locking to NodeJS 18.16.0 at least on 2.x/2.10 branches. 1.x can pending.
* Since KNN already update the dependencies such as gcc to v7 and cmake to 3.23.3, it is easier for us to bring them onto either Rockylinux8 or AL2023. Starting from now k-NN will not be able to run on OS with glibc version lower than 2.28 (previously 2.17)
* Work with doc team to update the doc compatibility charts to remove CentOS7 support and add AL2023.
* Test all the pipelines on the new servers.


### Optional Steps
* Need to discuss after the 2.10.0 release whether or not 1.x line need to upgrade as well.
* Have separate pipeline to test NodeJS14 bc abilities.

**Comment by wbeckler** [comment]
What is the status of the separate pipeline to test node 14 backward compatibility? There are going to be users using old linux versions who can't go past node 14 yet, and it would be useful to know what fixes we can do so as to not unnecessarily break things for those users.

**Comment by bbarani** [comment]
@wbeckler We do not have plans to create a separate pipeline in public Jenkins infra for EOL versions of Node. If needed, this needs to be tackled at repo level.

**Comment by peterzhuamazon** [comment]
Have quick talk with OSD @AMoo-Miki about core, and we are planning to switch 2.x to 18.16.0 next week to start testing on the 2.10.0 build with newer nodejs.

Thanks.

**Comment by peterzhuamazon** [comment]
The majority of the tasks in this issue is resolved and implemented.
We will issue new tickets whenever new tasks coming up.

Thanks.
