### ISSUE TITLE
[BUG]Error when running Docker image

### ISSUE THREAD

**Issue by qmonitoring** [opensearch-project/opensearch-build#1567]
**Describe the bug**

When I try to run a docker image (following the [documentation](https://opensearch.org/docs/latest/opensearch/install/docker/#configure-opensearch)) I get this error:

`tee: /usr/share/opensearch/config/opensearch.yml: Permission denied`

The container won't start.

**To Reproduce**

` docker run -p 9200:9200 -p 9600:9600 -e "discovery.type=single-node" -v /usr/share/opensearch/config/custom-opensearch.yml:/usr/share/opensearch/config/opensearch.yml opensearchproject/opensearch:1.2.4`

**Expected behavior**

Opensearch up and running

**Host/Environment (please complete the following information):**

centos-release-8.2-2.2004.0.1.el8.x86_64

**Additional context**

I tried many options: change the configuration file, use a old version of the image, but the result was equally unsuccessful. For _opensearchproject/opensearch:1.2.3_ the error is:

`tee: /usr/share/opensearch/config/opensearch.yml: Permission denied`
`sed: cannot rename /usr/share/opensearch/config/sedZbSzcg: Device or resource busy`

**Comment by peterzhuamazon** [comment]
Hi @qmonitoring please refer to #1529 for more context and discussion as well as temp fixes that I am preparing to resolve the race condition.

As of now if your yml file is root owned it cannot be updated as that requires a complete change in how we handle the startup variable. Or you can make your yml file owned by opensearch and it should run.

Sorry for inconvinience,
Thanks.

**Comment by peterzhuamazon** [comment]
Close this issue please continue the discussion in #1529 as we have a fix now for you to test:
https://github.com/opensearch-project/opensearch-build/issues/1529#issuecomment-1027319799

Thanks.
