### ISSUE TITLE
Refactor tester, maybe reuse BuildOutput manifest and other shared code

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#157]
**Is your feature request related to a problem? Please describe.**

- We have at least 2 tools using build output workflows, https://github.com/opensearch-project/opensearch-build/tree/main/workflows/testing and https://github.com/opensearch-project/opensearch-build/tree/main/tools/bundle-build. The python implementation for these manifests should probably be shared. See https://github.com/opensearch-project/opensearch-build/issues/155#issuecomment-894443601 for more ideas.
- The tester tool needs refactoring discussed in #138.

**Comment by camerski** [comment]
Resolved by https://github.com/opensearch-project/opensearch-build/pull/170
