### ISSUE TITLE
Customizing image - help needed

### ISSUE THREAD

**Issue by PallaviIgave** [opensearch-project/opensearch-build#1570]
I am trying to customize an opensearch image and add indexes data in data directory. We need to do it since we want to use this customized image at multiple places. 

The steps in Multi-stage Dockerfile are:
**Stage 1:**
1) Change `discovery.type` setting in opensearch.yml 
2) Run entrypoint `RUN /usr/share/opensearch/opensearch-docker-entrypoint.sh`
3) Load indexes into opensearch domain by talking to localhost:9200

**Stage 2:**
1) Copy data folder from stage1 to final stage

Issue:
The docker build stucks on step 2 in Stage 1. I am not able to hit localhost after that at 3 in stage 1.

Do you have any better idea to do this kind of stuff?

**Comment by bbarani** [comment]
@PallaviIgave We do not customize opensearch image for specific use case but I would recommend asking this question in [forums](https://discuss.opendistrocommunity.dev/c/build/12) to see if you get any help there. I am closing this issue for now but feel free to re-open in case of any additional questions.
