### ISSUE TITLE
Automated container scanning for OpenSearch and OpenSearch Dashboard images

### ISSUE THREAD

**Issue by bbarani** [opensearch-project/opensearch-build#1576]
### Is your feature request related to a problem? Please describe

We are currently running the container scans for Docker images manually during release. We do not have any automated container scanning solution to report any vulnerabilities proactively

### Describe the solution you'd like

Implement automated container scanning solution using the tools listed below,

- [Trivy](https://github.com/aquasecurity/trivy)
- [Clair](https://github.com/quay/clair)
- [Whitesource](https://whitesource.atlassian.net/wiki/spaces/WD/pages/710673221/Docker+Image+Integration)

### Acceptance Criteria

Container images are scanned during the build process and reports the CVEs

**Comment by gaiksaya** [comment]
[Triage] We need to look into both the tools and accordingly integrate with our docker build system as well.

**Comment by bbarani** [comment]
Closing this issue as we have integrated[ Trivy scans](https://github.com/opensearch-project/opensearch-build/pull/2440) with distribution build process.
