### ISSUE TITLE
How should teams manage pre-release artifacts?

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#1578]
There needs to be recommendations for how and where to store/manage pre-released artifacts, for example binaries that are unsigned that are then promoted via the release process.

Acceptance Criteria:
- [x] What is the recommended way to store pre-release binaries artifacts?
- [x] What is the recommended way to store pre-release container images?

**Comment by gaiksaya** [comment]
For pre-release binaries GitHub release artifacts (or assets as they are called) can be used. In case of large size, a storage infrastructure needs to be used. 

For pre-release container images dockerhub allows creating free accounts and host docker images. The component teams can have their own staging account for the same. In case of any other container images, like ECR infrastructure needs to be set up by component team. This gives them control over what they stage, test it if required and then kick in the release workflow that will pick these up.

@VachaShah @dblock @bbarani What do you think?

**Comment by dblock** [comment]
Dockerhub staging is similar to maven staging. I don't have a strong opinion on whether we need to centralize this "storage infrastructure" or can use these different existing ones.

**Comment by gaiksaya** [comment]
Problem with using existing ones is again centralized credentials management. So can't use opensearchstaging account but new one can be created by component/client team to manage the container images.

Here are the recommendations:

* What is the recommended way to store pre-release binaries artifacts?
Recommended way is to use github release assets to store the binaries. If the size of the binaries exceeds the limit, we recommend to have a storage like S3 bucket accessible via cloudfront to download the artifacts

* What is the recommended way to store pre-release container images?
For pre-release containers it is recommended to store the container images on any public container repositories like ECR, dockerhub, etc.
