### ISSUE TITLE
Create OpenSearch Dashboards 1.1 Distribution

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#158]
**Is your feature request related to a problem? Please describe.**

Produce an OpenSearch Dashboards bundle.

**Describe the solution you'd like**

Extend https://github.com/opensearch-project/opensearch-build/tree/main/scripts/bundle-build to support OpenSearch Dashboards. Will need a default script for each component and overrides. Might need to move some things around in scripts into an OpenSearch subfolder to accommodate.

**Comment by bbarani** [comment]
The current progress of Opensearch Dashboards automation can be tracked here - https://github.com/opensearch-project/opensearch-build/issues/158

**Comment by dblock** [comment]
The leftover work is to add components to dashboards manifest and hook up the build job to Jenkins.

**Comment by peternied** [comment]
> The leftover work is to add components to dashboards manifest and hook up the build job to Jenkins.

@kavilla Should we spin those tasks into additional issues and update https://github.com/opensearch-project/opensearch-build/issues/573 or wait for them on this issue?

**Comment by dblock** [comment]
We released 1.2 OpenSearch Dashboards using automated build, closing.
