### ISSUE TITLE
[BUG] Use opensearch-build tags to build older releases

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#1583]
We have released 1.2.4 last week and today the 1.2.4 build is breaking due to this:

@amitgalitz removed the build.sh script for job-scheduler in opensearch-build repo, so the build.sh in js repo can be favored.
https://github.com/opensearch-project/opensearch-build/commit/4c3ae78a5e8a390eb68521e295abc3b4e438edee

This caused js to fail in 1.2.4 build:
```
Invalid option: -?
+ exit 1
2022-02-02 00:58:45 ERROR    Error building job-scheduler, retry with: ./build.sh manifests/1.2.4/opensearch-1.2.4.yml --component job-scheduler
Traceback (most recent call last):
  File "./src/run_build.py", line 78, in <module>
    sys.exit(main())
  File "./src/run_build.py", line 66, in main
    builder.build(build_recorder)
  File "/var/jenkins/workspace/distribution-build-opensearch@3/src/build_workflow/builder_from_source.py", line 50, in build
    self.git_repo.execute(build_command)
  File "/var/jenkins/workspace/distribution-build-opensearch@3/src/git/git_repository.py", line 83, in execute
    subprocess.check_call(command, cwd=cwd, shell=True)
  File "/usr/local/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'bash /tmp/tmpqh6fm_q6/job-scheduler/scripts/build.sh -v 1.2.4 -p linux -a arm64 -s false -o builds' returned non-zero exit status 1.
```

I have found that opensearch-build main branch js build.sh, is different from the 1.2.4 tag js build.sh in js repo.

* test1: build repo default: https://raw.githubusercontent.com/opensearch-project/opensearch-build/50e0afedcfa868764c3[…]5b71db5670c369/scripts/components/job-scheduler/build.sh
* test2: 1.2.4.0 tag js script: https://raw.githubusercontent.com/opensearch-project/job-scheduler/1.2.4.0/scripts/build.sh

```
$ diff -bi test1 test2
17d16
<     echo -e "-p PLATFORM\t[Optional] Platform, ignored."
23c22
< while getopts ":h:v:s:o:p:a:" arg; do
---
> while getopts ":h:v:s:o:a:" arg; do
38,40d36
<         p)
<             PLATFORM=$OPTARG
<             ;;
67,68c63,64
< mkdir -p $OUTPUT/maven/org/opensearch
< cp -r ./build/local-staging-repo/org/opensearch/. $OUTPUT/maven/org/opensearch
---
> mkdir -p $OUTPUT/maven/org/opensearch/opensearch-job-scheduler-spi
> cp -r ./build/local-staging-repo/org/opensearch/opensearch-job-scheduler-spi $OUTPUT/maven/org/opensearch/opensearch-job-scheduler-spi
73a70
>
```

As of now, all of our builds, regardless of versions, are using the `main` branch of opensearch-build repo. Since we already cut tags for past releases, seems more keen to me that we should use tags / branches of 1.2.4 to build 1.2.4. instead of `main` branch.

Thanks.

**Comment by dblock** [comment]
The 1.2.4 build should not be building anymore, I see that the manifest is pointing to tags, so why was that kicked off?

We do need to backport @amitgalitz change to 1.2 branch of job-scheduler though.

**Comment by amitgalitz** [comment]
> The 1.2.4 build should not be building anymore, I see that the manifest is pointing to tags, so why was that kicked off?
> 
> We do need to backport @amitgalitz change to 1.2 branch of job-scheduler though.

I already backported it to 1.2 https://github.com/opensearch-project/job-scheduler/pull/120. I think the reason its failing is because 1.2 branch missed a different backport to it's build script which is only getting exposed now once the script was removed from opensearch-build. This PR might be the fix for this: https://github.com/opensearch-project/job-scheduler/pull/124

**Comment by gaiksaya** [comment]
[Triage] Closing this since the above PR is merged. Also we need not build already versions.
