### ISSUE TITLE
[Build] Create a Docker image for Ruby

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#1593]
Ruby needs to be built with the signing key present in the code base with the locked down credentials model we have in the OpenSearch Project the only place this can happen is in a Jenkins job coupled with the this OpenSearch-Build repository.

In order to build ruby projects we need the correct interpreter to be selectable.  There have been multiple attempts, https://github.com/opensearch-project/opensearch-build/pull/1216, https://github.com/opensearch-project/opensearch-build/pull/1202, and https://github.com/opensearch-project/opensearch-build/pull/1142 and none of them have offer the full functionality that is needed.

We have a nearly functional build pull request that was stifled by the missing docker image. https://github.com/opensearch-project/opensearch-build/pull/1330.

### Acceptance Criteria:
- There is a new docker file in [docker/ci/dockerfiles](https://github.com/opensearch-project/opensearch-build/tree/main/docker/ci/dockerfiles)
- The image is lightweight containing 
   - AWS CLI
   - rvm with the following interpreters installed
      - ruby-2.7
      - ruby-3.0
      - jruby-9.2.X
- The docker image can download and install a new interpreter with user permissions with `rvm install {interpreter}` and set it as default `rvm use {interpreter}`

### Follow up:
- Reopen https://github.com/opensearch-project/opensearch-build/pull/1330 and make changes to accommodate the new docker image

**Comment by bbarani** [comment]
@opensearch-project/engineering-effectiveness  Can we close this issue?

**Comment by peterzhuamazon** [comment]
We have ruby already included in this image, and can install necessary gem if needed by adding to the dockerfile.
https://github.com/opensearch-project/opensearch-build/blob/main/docker/ci/dockerfiles/current/build.centos7.opensearch.x64.arm64.dockerfile

Thanks.
