### ISSUE TITLE
Update the Data Prepper Promotion/Release Job

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/opensearch-build#1594]
### Is your feature request related to a problem? Please describe

Data Prepper is looking to use an updated release process as described in https://github.com/opensearch-project/data-prepper/issues/977.

### Describe the solution you'd like

Update the Data Prepper promotion job to perform all the necessary promotions based on the artifacts produced into the Data Prepper artifacts repositories.

**Comment by gaiksaya** [comment]
[Triage] This will be fixed as a part of universal build workflow. Please see #1234
