### ISSUE TITLE
Allow S3 uploading of index.yml file besides builds/dist

### ISSUE THREAD

**Issue by tianleh** [opensearch-project/opensearch-build#1601]
### Is your feature request related to a problem? Please describe

While working on supporting `latest` in url, we are following the suggestion to https://github.com/opensearch-project/opensearch-build/pull/1569#discussion_r797969777 to upload an `index.yml` file which contains the latest build number.

However,  as documented in https://github.com/opensearch-project/opensearch-build/pull/1569#issuecomment-1030725376, we identify that there is AmazonS3Exception when uploading `index.yml` file. Looks like the IAM role `opensearch-bundle` is not allowed to perform such uploading. The complete log is in this Jenkins run http://jenki-jenki-fpgmrv2ryxko-1366042710.us-east-1.elb.amazonaws.com/job/Playground/job/tianleh-distribution-url-latest/7/console

### Describe the solution you'd like

Allow `opensearch-bundle` to upload `index.yml` file under `$BUCKET/distribution-build-opensearch/1.2.4`

**Comment by tianleh** [comment]
@peternied  Could infra team help prioritize this while I am working on https://github.com/opensearch-project/opensearch-build/pull/1569? 

CC @dblock  @seraphjiang @bbarani @xinlamzn  for visibility

**Comment by dblock** [comment]
@tianleh I believe this should be added to https://github.com/opensearch-project/opensearch-build/blob/main/deployment/lib/identities.ts#L40 as needed

**Comment by tianleh** [comment]
Decided to use `index.json` instead of `index.yml` https://github.com/opensearch-project/opensearch-build/pull/1569#issuecomment-1036091352
