### ISSUE TITLE
[Code cleanup] Component iteration in test runners

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/opensearch-build#1604]
### Is your feature request related to a problem? Please describe

Clean up the logic for test runners that go through the components. [[EXAMPLE](https://github.com/opensearch-project/opensearch-build/blob/main/src/test_workflow/integ_test/integ_test_runner.py#L29)]

Source: https://github.com/opensearch-project/opensearch-build/pull/1603#discussion_r801627094

> Not for this PR, but we do a similar workflow in many places and I don't love the double-select here, first pass --component name to pick a component, but then we also only want components that have a test configuration.

### Describe the solution you'd like

Source: https://github.com/opensearch-project/opensearch-build/pull/1603#discussion_r801627094

> One option would be to fail if self.args.component not in self.test_manifest.components with an explicit error, and refactor components.select to take an array of components, i.e. self.components.select(focus=self.test_manifest.components).

> Another, possibly better, could be to do self.components.select(focus=self.args.component, configs=self.test_manifest.components, key: "bwc_test") that would return a set of tuples of component + configuration. The code then becomes quite clean:

```
for component, config in self.components.select(focus=self.args.component, configs: self.test_manifest.components, key: "bwc_test"):
   test_suite = ...
   ...
```

### Describe alternatives you've considered

N/A

**Comment by kavilla** [comment]
More clean up: https://github.com/opensearch-project/opensearch-build/issues/1512. Type new classes.

**Comment by gaiksaya** [comment]
Closing this issue as stale. Don't see any action item in the PR description. Please re-open if needed.
