### ISSUE TITLE
[Bug]: Cannot login with default username/password in OpenSearch Dashboards setup via Docker

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/opensearch-build#1623]
### Describe the bug

I was trying to setup an opensearch cluster with Dashboards via docker. 
I did use the docker-compose.yml from [opensearch.org/downloads](https://opensearch.org/samples/docker-compose.yml).

After setting up, i was able to access opensearch via default username and password.
```
vemsarat@machine docker % curl --insecure 'https://localhost:9200/_cluster/health?pretty' -u admin:admin
{
  "cluster_name" : "opensearch-cluster",
  "status" : "green",
  "timed_out" : false,
  "number_of_nodes" : 2,
  "number_of_data_nodes" : 2,
  "active_primary_shards" : 3,
  "active_shards" : 6,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 0,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0,
  "task_max_waiting_in_queue_millis" : 0,
  "active_shards_percent_as_number" : 100.0
}
```
But I could not access Dashboards.
<img width="1792" alt="Screen Shot 2022-02-15 at 9 54 52 AM" src="https://user-images.githubusercontent.com/16944164/154120579-8567c61c-ccad-4e87-a486-fa9d72dbfbd5.png">
Logs:
```
opensearch-dashboards    | {"type":"log","@timestamp":"2022-02-15T17:48:51Z","tags":["error","plugins","securityDashboards"],"pid":1,"message":"Failed authentication: Error: [invalid_index_name_exception] Invalid index name [_plugins], must not start with '_'., with { index=\"_plugins\" & index_uuid=\"_na_\" }"}
```

### To reproduce

1. Download docker-compose file via [opensearch.org/downloads](https://opensearch.org/samples/docker-compose.yml).
2. `docker-compose up`
3. Open `localhost:5601` in browser

### Expected behavior

Login using default username and password for OpenSearch Dashboards.

### Screenshots

Attached.

### Host / Environment

Mac OS X Monterey 

### Additional context

Could be related to security dashboards plugin, but I wanted start with OpenSearch build.

**Comment by bbarani** [comment]
@saratvemulapalli I couldn't reproduce this issue in latest version. 

**Steps followed:**

1. Downloaded[ Docker compose file](https://opensearch.org/samples/docker-compose.yml)
2. Executed docker-compose up 

```
38f9d36a2da3:~ bbarani$ docker-compose up
Creating network "bbarani_opensearch-net" with the default driver
Creating volume "bbarani_opensearch-data1" with default driver
Creating volume "bbarani_opensearch-data2" with default driver
Pulling opensearch-dashboards (opensearchproject/opensearch-dashboards:latest)...
latest: Pulling from opensearchproject/opensearch-dashboards
f964900200fc: Already exists
0838be2a8413: Pull complete
62bacc114ff6: Pull complete
c0017720ade8: Pull complete
e63329c6aff2: Pull complete
Digest: sha256:6e786127e04227d4cf5696e86be6f49fb106a4f60e7baf35e8c4dfed1e3c24cc
Status: Downloaded newer image for opensearchproject/opensearch-dashboards:latest
Creating opensearch-node1      ... done
Creating opensearch-node2      ... done
Creating opensearch-dashboards ... done
```

Login screen:
<img width="980" alt="Screen Shot 2022-02-15 at 11 29 48 AM" src="https://user-images.githubusercontent.com/70038446/154137160-960014ea-fd71-4dd2-9d48-0897c5ffa34b.png">

Post log in:
<img width="1341" alt="Screen Shot 2022-02-15 at 11 29 20 AM" src="https://user-images.githubusercontent.com/70038446/154137213-e6727b1c-a152-48dc-8041-f44a035a5f30.png">

**Comment by saratvemulapalli** [comment]
Thanks @bbarani , thats interesting. 
I tried different browsers. But somehow my machine is seeing this problem.

**Comment by bbarani** [comment]
@saratvemulapalli Can you kill all the running process and execute just docker-compose up?

**Comment by saratvemulapalli** [comment]
That's a good point. I did try somehow it doesn't work for me. 

I'll close this issue, let's see if anybody else reports the same problem.
