### ISSUE TITLE
[Distribution-build-opensearch-dashboard Breaks] Error building queryWorkbenchDashboards components

### ISSUE THREAD

**Issue by zelinh** [opensearch-project/opensearch-build#1626]
### Describe the bug

Currently our distribution-build-opensearch-dashboards is broken. 
Here is the context of error. 
```
+ cp -r ../workbench/ ../../OpenSearch-Dashboards/plugins
cp: cannot create directory ‘../../OpenSearch-Dashboards/plugins’: No such file or directory
2022-02-15 21:34:32 ERROR    Error building queryWorkbenchDashboards, retry with: ./build.sh manifests/1.3.0/opensearch-dashboards-1.3.0.yml --component queryWorkbenchDashboards
```

### To reproduce

Run `./build.sh manifests/1.3.0/opensearch-dashboards-1.3.0.yml --component queryWorkbenchDashboards` in the root of this build repo inside the CI container.

**Comment by joshuali925** [comment]
@eugenesk24 is tracking 1.3 release, linking PR to fix the issue https://github.com/opensearch-project/sql/pull/419

**Comment by bbarani** [comment]
@zelinh Can we close this issue?

**Comment by zelinh** [comment]
Closing this since this issue has been resolved.
