### ISSUE TITLE
check-for-build job always fails if child job fails

### ISSUE THREAD

**Issue by zelinh** [opensearch-project/opensearch-build#1627]
This issue has been solved in previous #1285. However, in recent change, catch block was removed from this job. Therefore this job will always fail and send out notification if its child job (e.g. distribution-build-opensearch-dashboards) fails. 
This notification should only happen if there is an internal error (e.g. `TARGET_JOB_NAME` is invalid) in this job. 
https://github.com/opensearch-project/opensearch-build/blob/bddbc06dd5ee6b67d3be3230cab922a083d4f15a/jenkins/check-for-build.jenkinsfile#L75-L78

### Acceptance Criteria:
We should only see failure notifications if there is an error generated inside of this job, not any child jobs.

**Comment by zelinh** [comment]
Reopen this issue since we revert the commit.

**Comment by bbarani** [comment]
@zelinh Can we close this issue?

**Comment by zelinh** [comment]
> @zelinh Can we close this issue?

Not really, I reopened this issue since we reverted the initial change. I'm not actively working on this right now.

**Comment by bbarani** [comment]
@zelinh @peterzhuamazon Whats the current status of this issue?

**Comment by bbarani** [comment]
@zelinh @peterzhuamazon Whats the current status of this issue?

**Comment by zelinh** [comment]
I can confirm that this issue is still valid but shouldn't be urgent. @peterzhuamazon Do you think we need to fix this?

**Comment by bbarani** [comment]
@zelinh Please update this issue with the current status.

**Comment by bbarani** [comment]
@zelinh Please update this issue with the current status.

**Comment by zelinh** [comment]
I would close this issue for now. We could re-visit this to see if this is valid once we optimize our build workflow.
