### ISSUE TITLE
Support additional qualifiers in OpenSearch and OpenSearch Dashboards

### ISSUE THREAD

**Issue by bbarani** [opensearch-project/opensearch-build#1632]
### Is your feature request related to a problem? Please describe

Currently the distribution build process doesn't support passing any additional qualifier other than the 3 digit versions hence we have to manually make changes to generate builds with additional qualifiers 

### Describe the solution you'd like

Add the ability to pass additional qualifier to automated distribution build  process. Distribution build process should pick it from the manifest file used for creating the builds. Possible qualifiers includes but not limited to,

- Beta
- Alpha
- RC
- Preview
- Preview-1
- Preview.1

### Alpha1

The user should be able to build OpenSearch and Dashboards using the above qualifiers via build process

- [x] https://github.com/opensearch-project/opensearch-build/pull/1844
       https://github.com/opensearch-project/opensearch-build/pull/1867
- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1340
- [ ] https://github.com/opensearch-project/alerting-dashboards-plugin/issues/194
- [x] https://github.com/opensearch-project/alerting/issues/348
       https://github.com/opensearch-project/alerting/pull/366
       https://github.com/opensearch-project/alerting/pull/373
       https://github.com/opensearch-project/alerting/pull/376
       https://github.com/opensearch-project/alerting/pull/377
- [ ] https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/issues/209
- [x] https://github.com/opensearch-project/anomaly-detection/issues/432
       https://github.com/opensearch-project/anomaly-detection/pull/468
       https://github.com/opensearch-project/anomaly-detection/pull/472
       https://github.com/opensearch-project/opensearch-build/pull/1838
       https://github.com/opensearch-project/anomaly-detection/pull/483
       https://github.com/opensearch-project/anomaly-detection/pull/486
- [x] https://github.com/opensearch-project/asynchronous-search/issues/103
        https://github.com/opensearch-project/asynchronous-search/pull/115
        https://github.com/opensearch-project/asynchronous-search/pull/118
        https://github.com/opensearch-project/asynchronous-search/pull/119
        https://github.com/opensearch-project/asynchronous-search/pull/120
        https://github.com/opensearch-project/asynchronous-search/pull/123
- [x] https://github.com/opensearch-project/common-utils/issues/131
       https://github.com/opensearch-project/common-utils/pull/128
       https://github.com/opensearch-project/common-utils/pull/146
       https://github.com/opensearch-project/opensearch-build/pull/1796
       https://github.com/opensearch-project/common-utils/pull/151
       https://github.com/opensearch-project/common-utils/pull/152
- [ ] https://github.com/opensearch-project/dashboards-reports/issues/306
       https://github.com/opensearch-project/dashboards-reports/pull/327
- [ ] https://github.com/opensearch-project/dashboards-visualizations/issues/53
- [x] https://github.com/opensearch-project/index-management-dashboards-plugin/issues/166
- [x] https://github.com/opensearch-project/index-management/issues/303
        https://github.com/opensearch-project/index-management/pull/318
        https://github.com/opensearch-project/index-management/pull/323
- [x] https://github.com/opensearch-project/job-scheduler/issues/142
        https://github.com/opensearch-project/job-scheduler/pull/139
        https://github.com/opensearch-project/job-scheduler/pull/152
        https://github.com/opensearch-project/job-scheduler/pull/162
        https://github.com/opensearch-project/job-scheduler/pull/163
- [x] https://github.com/opensearch-project/k-NN/issues/315
       https://github.com/opensearch-project/k-NN/pull/329
       https://github.com/opensearch-project/k-NN/pull/334
       https://github.com/opensearch-project/k-NN/pull/349
- [ ] https://github.com/opensearch-project/notifications/issues/379
       https://github.com/opensearch-project/notifications/pull/391
       https://github.com/opensearch-project/notifications/pull/404
       #1957
- [x] https://github.com/opensearch-project/performance-analyzer/issues/158
       https://github.com/opensearch-project/performance-analyzer/pull/175
       https://github.com/opensearch-project/performance-analyzer/pull/179
       https://github.com/opensearch-project/opensearch-build/pull/1940
- [x] https://github.com/opensearch-project/performance-analyzer-rca/issues/144
       https://github.com/opensearch-project/performance-analyzer-rca/pull/152
       https://github.com/opensearch-project/performance-analyzer-rca/pull/156
- [ ] https://github.com/opensearch-project/security-dashboards-plugin/issues/921
- [x] https://github.com/opensearch-project/security/issues/1676
       https://github.com/opensearch-project/security/pull/1702
       https://github.com/opensearch-project/security/pull/1738
       https://github.com/opensearch-project/security/pull/1698
       https://github.com/opensearch-project/security/pull/1741
- [x] https://github.com/opensearch-project/sql/issues/485
- [x] https://github.com/opensearch-project/observability/issues/577
       https://github.com/opensearch-project/observability/pull/619
- [x] https://github.com/opensearch-project/cross-cluster-replication/issues/334
       https://github.com/opensearch-project/cross-cluster-replication/pull/353
       https://github.com/opensearch-project/cross-cluster-replication/pull/358
- [x] https://github.com/opensearch-project/ml-commons/issues/258
       https://github.com/opensearch-project/ml-commons/pull/257
       https://github.com/opensearch-project/ml-commons/pull/262
       https://github.com/opensearch-project/ml-commons/pull/269
       https://github.com/opensearch-project/ml-commons/pull/271

### RC1
- [ ] https://github.com/opensearch-project/opensearch-build/pull/1863

**Comment by peterzhuamazon** [comment]
This needs a change in the current workflows as we do not support qualifiers yet, only raw version numbers in digits.

cc: @dblock

**Comment by dblock** [comment]
I think we should support the version in the manifest, i.e. I would like to be able to write the following in https://github.com/opensearch-project/opensearch-build/blob/main/manifests/2.0.0/opensearch-2.0.0.yml#L9

```
version: 2.0-preview # or really anything that's standard Java package version format
```

The version is already passed around as -Dopensearch.version, and version checks need to understand this.

**Comment by zelinh** [comment]
[Triage] We have enough information and we need to groom this issue to understand the scope.

**Comment by joshuali925** [comment]
any instructions on how this should be supported by dashboards plugins?

**Comment by peterzhuamazon** [comment]
Reopen this as @kavilla mistakenly close the meta issue.

**Comment by kavilla** [comment]
This is weird, I did not link this issue on the PR besides with the commit but since I mentioned it in the git description github closed it which is new behavior.

**Comment by cliu123** [comment]
Looks like OpenSearch core doesn't accept plugin version with version_qualifier. Plugin installation failed: https://github.com/opensearch-project/security/runs/5797837160?check_suite_focus=true
```
2022-04-02T05:49:53.3391925Z -> Installing file:///docker-host/security-plugin.zip
2022-04-02T05:49:53.3426933Z ##[error]Exception in thread "main" java.lang.IllegalArgumentException: the version needs to contain major, minor, and revision, and optionally the build: 2.0.0.0-alpha1
2022-04-02T05:49:53.3428210Z 	at org.opensearch.Version.fromString(Version.java:186)
2022-04-02T05:49:53.3428625Z 	at org.opensearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:222)
2022-04-02T05:49:53.3429203Z 	at org.opensearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:811)
2022-04-02T05:49:53.3429760Z 	at org.opensearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:870)
2022-04-02T05:49:53.3430273Z 	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:275)
2022-04-02T05:49:53.3430780Z 	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:249)
2022-04-02T05:49:53.3431282Z 	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:100)
2022-04-02T05:49:53.3431744Z 	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
2022-04-02T05:49:53.3432163Z 	at org.opensearch.cli.MultiCommand.execute(MultiCommand.java:104)
2022-04-02T05:49:53.3432587Z 	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
2022-04-02T05:49:53.3432972Z 	at org.opensearch.cli.Command.main(Command.java:101)
2022-04-02T05:49:53.3433771Z 	at org.opensearch.plugins.PluginCli.main(PluginCli.java:60)
```

**Comment by dblock** [comment]
I believe we're done with propagating rc1 qualifiers, closing.
