### ISSUE TITLE
[Bug]: OpenSearch build builds OpenSearch Dashboards

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#1634]
### Describe the bug

In https://github.com/opensearch-project/opensearch-build/pull/590/ we have introduced a `-d` option that says "build OpenSearch Dashboards". This is odd, why would OpenSearch build know anything about OpenSearch Dashboards?

### To reproduce

See https://github.com/opensearch-project/opensearch-build/pull/1631/files#r808574435

### Expected behavior

Change the default script, remove `-d` from OpenSearch build scripts.

**Comment by dblock** [comment]
@kavilla Could you please give some context here? Thanks!

**Comment by kavilla** [comment]
> @kavilla Could you please give some context here? Thanks!

Yeah it should be removed. It was added in the default script when the default script was just the one [[REF](https://github.com/opensearch-project/opensearch-build/pull/590/files)].
