### ISSUE TITLE
[BUG] Only send `-d` to core components, instead of everything.

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#1651]
As of now, build workflow will not send `-d` if user does not specify `--distribution`.
However, if user specify things such as `--distribution rpm` and try to build core+all plugins,
`-d` will be sent to plugins as well.

The plugin build script does not know how to interpret `-d` thus fail.
```
+ echo 'Invalid option: -?'
Invalid option: -?
+ exit 1
2022-02-17 23:58:36 ERROR    Error building common-utils, retry with: ./build.sh manifests/1.3.0/opensearch-1.3.0.yml --component common-utils
Traceback (most recent call last):
  File "./src/run_build.py", line 79, in <module>
    sys.exit(main())
  File "./src/run_build.py", line 67, in main
    builder.build(build_recorder)
  File "/local/home/zhujiaxi/opensearch-build-peterzhuamazon/src/build_workflow/builder_from_source.py", line 49, in build
    self.git_repo.execute(build_command)
  File "/local/home/zhujiaxi/opensearch-build-peterzhuamazon/src/git/git_repository.py", line 83, in execute
    subprocess.check_call(command, cwd=cwd, shell=True)
  File "/usr/lib64/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'bash /local/home/zhujiaxi/opensearch-build-peterzhuamazon/scripts/components/common-utils/build.sh -v 1.3.0 -p linux -a x64 -d rpm -s false -o builds' returned non-zero exit status 1.
```

Need to add a condition where if component != OpenSearch/OpenSearch-Dashboards, then `-d` will not be sent even if not None.

**Comment by dblock** [comment]
> Need to add a condition where if component != OpenSearch/OpenSearch-Dashboards, then `-d` will not be sent even if not None.

That's too bad. Maybe it's easier to just add required `-d` into all the scripts?

**Comment by peterzhuamazon** [comment]
> > Need to add a condition where if component != OpenSearch/OpenSearch-Dashboards, then `-d` will not be sent even if not None.
> 
> That's too bad. Maybe it's easier to just add required `-d` into all the scripts?

The previous discussion on this is to not adding `-d` to all scripts.
I am happy to do so just wonder is there any process changed for this?

I already open PR #1652 to add this functionality, please comment.

Thanks.

**Comment by dblock** [comment]
> > > Need to add a condition where if component != OpenSearch/OpenSearch-Dashboards, then `-d` will not be sent even if not None.
> > 
> > 
> > That's too bad. Maybe it's easier to just add required `-d` into all the scripts?
> 
> The previous discussion on this is to not adding `-d` to all scripts. I am happy to do so just wonder is there any process changed for this?

Yes, I didn't realize that it was going to be a problem and would require this hack :(

**Comment by dblock** [comment]
That's fine with me. Open a separate issue for that.

**Comment by peterzhuamazon** [comment]
@dblock create a new issue to track this: https://github.com/opensearch-project/opensearch-build/issues/1655
