### ISSUE TITLE
Create onboarding documentation for test automation for plugins

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/opensearch-build#167]
Add technical documentation for repositories to help onboard to test automation.

- [x] #224
  - [ ] Test Orchestration Layer
  - [ ] Performance Tests
  - [ ] Integration Tests
- [x] #223

**Comment by bbarani** [comment]
@setiah Can you update the status of this issue? Are you working on creating the needed documentation?

**Comment by zelinh** [comment]
@setiah Are you actively working on this?

**Comment by gaiksaya** [comment]
[triage] Looks like tasks from the issue description are complete. closing the issue. Feel free to reopen with more information.
Thanks!
