### ISSUE TITLE
Optional plugin support for k-NN from OpenSearch 2.0

### ISSUE THREAD

**Issue by vamshin** [opensearch-project/opensearch-build#1670]
### Is your feature request related to a problem? Please describe

From OpenSearch-2.0, we have decided to have non jvm based plugins to be optional which means they would not be bundled with the default opensearch2.0 distribution. These optional plugin artifacts should be downloadable and installed using ```opensearch-plugin-install``` script.

Motivation:
-> Unblocking OpenSearch in order to accelerate our ability to offer more distribution targets (os, architecture, package manager, etc.)

### Describe the solution you'd like

k-NN plugin artifacts should be hosted for community to download and install as per demand

### Acceptance Criteria
- The plugin URI will be shared a a part of documentation to the users
- Users can install plugin using URI
- Optional plugins should be tested with the distribution before every release. (Add them to current integration test process)

**Comment by gaiksaya** [comment]
[Triage] The ways to install is to pass an uri or a file for installing. 
Testing needs to be done against the final distribution build for 2.0.0 and other versions going forward.
k-NN plugin will be removed from manifest and will act as a stand-alone component.

**Comment by bbarani** [comment]
We will not be making any change in 2.x version and we will revisit this for 3.0.
