### ISSUE TITLE
[Enhancement] Make build notification in chat show failed build command

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#1672]
It would be easier for us to debug the failure of build pipelines without the need to log dive.

If the build bot is able to print the failed build command in notification chat, it would be easier to reproduce the issue and save time.

Ex:
```
BUILD FAILED in 26s
1 actionable task: 1 executed
2022-02-25 17:17:28 ERROR    Error building security, retry with: ./build.sh manifests/1.3.0/opensearch-1.3.0.yml --component security --snapshot
```

Thanks.

**Comment by prudhvigodithi** [comment]
We can achieve this in the following ways:

1)Consume the logs of the current job and parse for the error, this is little bit complex as each build fail for different error. 
Can come up with a shared library as
```
def BuildFailureCause() {
    
                     
                          def cause = "Caused:"
                          def error = "ERROR: "

                                build.getLog().eachLine { line ->
                                        if (line =~ /$cause/ || line =~ /$error/ ) {
                                            println "error: $line"  }
                                                          }

                         }

```
2) The another way is to consume the current running build logs and dump them as readable message 
Example as `def log = currentBuild.rawBuild.getLog(100).join('\n')`

3) We can use try catch block for each stage and get catch the error to convert to toString() format to read the error, but with this we need to add try/catch block to every stage out there in jenkinsfile
```
        stage('build') {
            steps {
                node('Agent') {
                    script {
                        FAILED_STAGE=env.STAGE_NAME
                        try {
                            echo "test"
                        }
                        catch (Exception e) {
                            ERROR=e.toString()
                            echo 'Exception occurred: ' + e.toString()
                            sh "exit 1"
                        }
                        
                    
                    }
                }
            }

```
4) We can combine try/catch block with post script to catch the failed stage and dump the error.

**Comment by peterzhuamazon** [comment]
Thanks @prudhvigodithi 

If you can show some examples of each it would be helpful for us to make a decision on which is suits our needs well.

Thanks.

**Comment by prudhvigodithi** [comment]
Fixed, added detailed error message to publish to slack channel
`MESSAGE=[2022-03-29 20:11:36 ERROR    Error building job-scheduler, retry with: ./build.sh manifests/1.4.0/opensearch-1.4.0.yml --component job-scheduler, 2022-03-29 20:12:32 ERROR    Error building job-scheduler, retry with: ./build.sh manifests/1.4.0/opensearch-1.4.0.yml --component job-scheduler, 2022-03-29 20:12:37 ERROR    Error building job-scheduler, retry with: ./build.sh manifests/1.4.0/opensearch-1.4.0.yml --component job-scheduler --snapshot, 2022-03-29 20:21:57 ERROR    Error building job-scheduler, retry with: ./build.sh manifests/1.4.0/opensearch-1.4.0.yml --component job-scheduler --snapshot]`
https://github.com/opensearch-project/opensearch-build/pull/1819
