### ISSUE TITLE
Add documentation about using yarn

### ISSUE THREAD

**Issue by tianleh** [opensearch-project/opensearch-build#1680]
### Is your feature request related to a problem? Please describe

js-tests are using yarn. https://github.com/opensearch-project/opensearch-build/runs/5380150125?check_suite_focus=true We may need to add some documentation

This shall be documented in the readme about using yarn to run jest tests
https://github.com/opensearch-project/opensearch-build/blob/01ce6e91d7aa0f5f7a73121407e4252d8c7290b1/DEVELOPER_GUIDE.md#yarn

### Describe the solution you'd like

This shall be documented in the readme about using yarn to run jest tests
https://github.com/opensearch-project/opensearch-build/blob/01ce6e91d7aa0f5f7a73121407e4252d8c7290b1/DEVELOPER_GUIDE.md#yarn

**Comment by bbarani** [comment]
@tianleh  Can you please prioritize this documentation effort?

**Comment by tianleh** [comment]
> @tianleh Can you please prioritize this documentation effort?

Thanks for the reminder. ETA 6/24/2022

**Comment by bbarani** [comment]
@tianleh Can you please prioritize this documentation effort?

**Comment by bbarani** [comment]
@tianleh Can you please prioritize this documentation effort?

**Comment by bbarani** [comment]
@tianleh @seraphjiang Cab you please update the current status?

**Comment by bbarani** [comment]
@tianleh @seraphjiang Cab you please update the current status?

**Comment by gaiksaya** [comment]
Closing this issue. I believe https://github.com/opensearch-project/opensearch-dashboards-functional-test/blob/main/DEVELOPER_GUIDE.md is more appropriate place to add this information.
Thanks!
