### ISSUE TITLE
Integ Test Jenkinsfiles Input Manifest Param

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/opensearch-build#1687]
### Is your feature request related to a problem? Please describe

Origin: https://github.com/opensearch-project/opensearch-build/pull/1653#discussion_r817145061

Right now we pass information to the integ test jobs like the information on the runner. We need to do this because certain images have different dependencies. For example, all `1.x` builds of OpenSearch Dashboards requires Node 10.24.1 but all builds for `2.x` require 14.18.2. The same image cannot be used build, install, and execute integration tests.

### Describe the solution you'd like

Instead of passing a string about the AGENT, integ test jobs should just accept the input manifest that triggered the build job and read the information from the input manifest.

**Comment by gaiksaya** [comment]
Closing this issue as we now have the described solution implemented
> Instead of passing a string about the AGENT, integ test jobs should just accept the input manifest that triggered the build job and read the information from the input manifest.
