### ISSUE TITLE
[Bug]: OpenSearch integ tests should run in docker

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/opensearch-build#1688]
### Describe the bug

Current implementation: https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/opensearch/integ-test.jenkinsfile#L37

### To reproduce

n/a

### Expected behavior

Should use
```
docker {
....
}
```

**Comment by bbarani** [comment]
@kavilla Can you please update this issue with the current status?

**Comment by kavilla** [comment]
Hey @bbarani, looking at the OpenSearch integ test run it looks like each component is ran in it's own docker container. But for verification a maintainer to confirm would be good and then this issue can be closed I believe.

Thanks!

**Comment by prudhvigodithi** [comment]
Hey @kavilla the OpenSearch integ tests for CI, yes they do run in docker agents, but when executed locally its not, we can close this issue, wdyth @kavilla ?

**Comment by bbarani** [comment]
@kavilla @prudhvigodithi @gaiksaya Can we close this issue?

**Comment by jordarlu** [comment]
Hi, team, I am gonna close this issue for now as it has been a while without further dialog. Please feel free to reopen it if needed... thanks!!
