### ISSUE TITLE
add documentation about latest url

### ISSUE THREAD

**Issue by tianleh** [opensearch-project/opensearch-build#1689]
### Is your feature request related to a problem? Please describe

Add documentation about #1569 and artifact urls

### Describe the solution you'd like

- [ ] Add the documentation to use the all latest released artifacts urls.

- [ ] Add documentation about #1569 

Edit [DEVELOPER_GUIDE.md](https://github.com/opensearch-project/opensearch-build/blob/main/DEVELOPER_GUIDE.md) for documentation

**Comment by bbarani** [comment]
@tianleh Can you prioritize this issue? I assume you already have enough information to add to the documentation?

**Comment by tianleh** [comment]
> @tianleh @seraphjiang Would you be able to help prioritize this issue?

I will work on it this week. ETA: 5/27/2022.
