### ISSUE TITLE
[Bug]: distribution url to index.json is being cached by CloudFront leading to old value of latest url

### ISSUE THREAD

**Issue by tianleh** [opensearch-project/opensearch-build#1690]
### Describe the bug

The latest url has a logic to read from index.json https://github.com/opensearch-project/opensearch-build/blob/main/deployment/lambdas/cf-url-rewriter/cf-url-rewriter.ts#L14 However, this url is being cached by CloudFront. 

When the following URl
https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/1.3.0/latest/linux/arm64/builds/opensearch/manifest.yml it shows the latest number is 1024

<img width="470" alt="Screen Shot 2022-03-02 at 7 43 15 AM" src="https://user-images.githubusercontent.com/60111637/156395832-3597581e-8dfe-4d69-aedf-a434d43d4ce4.png">

However, by visiting the S3 bucket, the content is the file is actually 1028

<img width="930" alt="Screen Shot 2022-03-02 at 7 43 56 AM" src="https://user-images.githubusercontent.com/60111637/156395967-c77946d8-f53b-44e7-b3ca-2a2864f941e7.png">

Based on my research, by the default, the CF cache is 24hours which means that currently the latest url is using whatever built 24 hours ago. https://aws.amazon.com/premiumsupport/knowledge-center/cloudfront-serving-outdated-content-s3/

### To reproduce

See the description part.

### Expected behavior

The latest shall get the actual latest or at least a much short cache ttl (maybe 5mins?)

**Comment by tianleh** [comment]
Based on my research below, I may need to invalidate the url by '/*' 

https://aws.amazon.com/premiumsupport/knowledge-center/cloudfront-serving-outdated-content-s3/
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Invalidation.html#invalidation-specifying-objects
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Invalidation.html#invalidation-specifying-objects-paths

cc @dblock @seraphjiang for visibility.

**Comment by tianleh** [comment]
Just updating Invalidation doesn't work during my local test. Notice there is another layer of cache at origin configuration. 
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/origin-shield.html

Dig more.

**Comment by tianleh** [comment]
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/distribution-web-values-specify.html#DownloadDistValuesObjectCaching

**Comment by tianleh** [comment]
Thanks @sichend for sharing knowledge that invalidation is one-time thing and is not lasting.

**Comment by gaiksaya** [comment]
These are the current settings in the cloudfront:
https://github.com/opensearch-project/opensearch-build/blob/main/deployment/lib/artifacts-public-access.ts#L34-L54
Can you check what needs to be changed?

**Comment by tianleh** [comment]
> These are the current settings in the cloudfront:
> https://github.com/opensearch-project/opensearch-build/blob/main/deployment/lib/artifacts-public-access.ts#L34-L54
> Can you check what needs to be changed?

yep. I am checking the syntax to add a custom cache policy to the CloudFront and will run experiments in my personal AWS account.

**Comment by tianleh** [comment]
Add `              defaultTtl: Duration.seconds(0)` to the following block. Running cdk deployment locally to see if it can take effect.

```
behaviors: [
            {
              isDefaultBehavior: true,
              compress: true,
              allowedMethods: CloudFrontAllowedMethods.GET_HEAD,
              lambdaFunctionAssociations: [{
                eventType: LambdaEdgeEventType.VIEWER_REQUEST,
                lambdaFunction: urlRewriter.currentVersion,
              }],
              defaultTtl: Duration.seconds(0)
            },
          ],

```

**Comment by tianleh** [comment]
Verified the proposed change. Making a PR...
