### ISSUE TITLE
Make OSD integ test result human readable

### ISSUE THREAD

**Issue by tianleh** [opensearch-project/opensearch-build#1707]
### Is your feature request related to a problem? Please describe

The output contains garbled text. 

https://ci.opensearch.org/ci/dbc/integ-test-opensearch-dashboards/1.3.0/1484/linux/x64/test-results/b94f426463b24046a2ed33c5be290508/integ-test/functionalTestDashboards/without-security/test-results/stdout.txt

We suspect that this is related to Cypress output some characters like 'check mark's.

### Describe the solution you'd like

No more garbled text

**Comment by tianleh** [comment]
cc @kavilla

**Comment by kavilla** [comment]
@tianleh, I believe we resolved this on the cypress side? Can we close this now?

**Comment by tianleh** [comment]
We did see some improvement. However, when the report url is opened https://ci.opensearch.org/ci/dbc/integ-test-opensearch-dashboards/1.3.0/1498/linux/x64/test-results/ea967d6ef3a34b0a85f5636ea38ebc9f/integ-test/functionalTestDashboards/with-security/test-results/stdout.txt it is not easy to read. As a workaround, users need to download it locally or use curl to open it.

I'd keep this issue open until we are able to let the direct link readable.

@kavilla

**Comment by bbarani** [comment]
@tianleh @kavilla Did you make any progress on this issue?

**Comment by kavilla** [comment]
Hello @bbarani, I think it's still open based on @tianleh comment. I did create https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/217 that we could probably utilize.

**Comment by joshuarrrr** [comment]
@tianleh - is https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/217 sufficient to close this?

**Comment by tianleh** [comment]
> @tianleh - is [opensearch-project/opensearch-dashboards-functional-test#217](https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/217) sufficient to close this?

Looks sufficient to close this. Thanks for the follow up.
