### ISSUE TITLE
Improve component release issues

### ISSUE THREAD

**Issue by ohltyler** [opensearch-project/opensearch-build#1718]
Coming from 1.3 release, I see a few places the component release issues can be improved to make it more clear on the expectations of component owners:

- [ ] Each of the steps (Preparation, CI/CD, Pre-release, Release, and Post-release) are missing ECDs for each ([example](https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/issues/182)). There is no clear mapping between each of these sections, and the release dates mentioned in the base release issue ([example](https://github.com/opensearch-project/opensearch-build/issues/889)). From a component owner's perspective, this makes it difficult to know exactly when each of these steps should be finished. For example, in the 1.3 release, only a few components updated the manifest to point to a 1.3 branch before the intended cutoff time. 
- [ ] The campaigns listed in the base release issue aren't mentioned here. Suggest to add a checklist item to finish all campaigns as part of the preparation or pre-release sections.
- [ ] The release notes should be moved to pre-release step (it is only a release step for infra team when compiling all of the components' release notes)

**Comment by jordarlu** [comment]
Hi, @ohltyler , just want to circle back on this issue with you as the team has made many updates since this issue was opened, for example https://github.com/opensearch-project/opensearch-build/issues/4115, do you think we are good to close this issue for now? thanks !

**Comment by ohltyler** [comment]
@jordarlu Hi, thanks for bringing this up! Agreed that this is now out of date with all of the changes. I'll close this :)
