### ISSUE TITLE
Support Data Prepper Maven releases

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/opensearch-build#1751]
### Is your feature request related to a problem? Please describe

Data Prepper needs to release Maven artifacts.

### Describe the solution you'd like

Update the `release-data-prepper-all-artifacts` job to release Maven artifacts. These release steps will do the following:

1. Copy artifacts from the Data Prepper staging site.
2. Sign the artifacts.
3. Upload to Sonatype

We expect that promoting from Sonatype to Maven Central is a manual step.

**Comment by zelinh** [comment]
[Triage] Closing this issue since it's being released. @dlvenable Feel free to re-open this if there is any other issues.
