### ISSUE TITLE
[Enhancement] Add extra docker tags specifically for different builds

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#1762]
We have seen an issue today were IM committed a change during code freeze time:
https://github.com/opensearch-project/index-management/pull/311

This triggers a new build in jenkins, although we have separate links for tarball, docker only has one tag `1.3.0` and get overwritten.

I propose we have separate tags for docker based on builds.

Ex:

`latest`: always pointing latest
`1.3.0`: pointing to the latest version in 1.3.0
`1.3.0.1234`: pointing to the version with build number 1234 in 1.3.0

This way we can for sure lock all the artifacts to a specific version and will not overwrite without backups.

Thanks.

**Comment by dblock** [comment]
Would be great to get this done in the 2.0 timeframe.

**Comment by zelinh** [comment]
[Triage] For the tag with build number in it, we could activate it when there will be a release candidate coming to avoid too many images.

**Comment by peterzhuamazon** [comment]
Update 20220607:
* https://github.com/opensearch-project/opensearch-build/pull/2163

**Comment by peterzhuamazon** [comment]
Update 20220609:
* #2176

**Comment by peterzhuamazon** [comment]
This is complete and can be closed for now.
Thanks.
