### ISSUE TITLE
Publish OpenSearch JS Client v1.1.0 to NPM

### ISSUE THREAD

**Issue by zuochengding** [opensearch-project/opensearch-build#1763]
### Is your feature request related to a problem? Please describe

We are going to add some improvements into opensearch-js client so that we can have memory circuit breaker for nodeJS client.

- https://github.com/opensearch-project/opensearch-js/issues/202

### Describe the solution you'd like

- Add memory check for response, if the total memory consumed exceed the limit, then we destroy the response instead to avoid potential out of memory crash.
- PR: https://github.com/opensearch-project/opensearch-js/pull/207
### Estimate release date
March 30, 2022

**Comment by bbarani** [comment]
Closing this issue as we released OpenSearch JS Client v1.1.0 to NPM
