### ISSUE TITLE
Publish opensearch-py to PyPI

### ISSUE THREAD

**Issue by Shivamdhar** [opensearch-project/opensearch-build#1764]
### Is your feature request related to a problem? Please describe

Publish opensearch-py v `1.1` to PyPI

Repo: https://github.com/opensearch-project/opensearch-py

branch: 1.1 (to be created once PR: https://github.com/opensearch-project/opensearch-py/pull/138 is merged)

PyPI link: https://pypi.org/project/opensearch-py/

Release date: 03/22/22 (any changes will be communicated)

### Describe the solution you'd like

Upload opensearch-py v `1.1` to PyPI and test if `pip install opensearch-py` works.

**Comment by peterzhuamazon** [comment]
Starting releasing right now with @Shivamdhar 2PR.

**Comment by peterzhuamazon** [comment]
We just shipped OpenSearch our python client for OpenSearch on 1.1.0.
https://pypi.org/project/opensearch-py/1.1.0/
