### ISSUE TITLE
[TESTS]  Do not log status code in test result if `PASS`

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/opensearch-build#1767]
### Is your feature request related to a problem? Please describe

I'm might the only but with [this to string format](https://github.com/opensearch-project/opensearch-build/blob/main/src/test_workflow/test_result/test_result.py#L15) logs output like the following:
```
2022-03-15 22:03:36 INFO     | alerting             | with-security        | PASS  |    0 |
```

If all the tests passes. With purely looking at log messages I would assume that this means 0 tests passed. But internally I know that that 0 is actually the status code of `0` which means success. However, I also know that for OpenSearch Dashboards cypress tests, the exit code is equal to the amount of tests failed if the test runner was able to run the tests.

### Describe the solution you'd like

Don't output the status code on `PASS`

For example:
```
2022-03-15 22:03:36 INFO     | alerting             | with-security        | PASS  |
```

**Comment by zelinh** [comment]
[Triage] We know what to do then moving this to our product backlog.
