### ISSUE TITLE
[Retrospective] Release 1.3.0

### ISSUE THREAD

**Issue by zelinh** [opensearch-project/opensearch-build#1775]
### How to use this issue?
Please add comments to this issue, they can be small or large in scope.  Honest feedback is important to improve our processes, suggestions are also welcomed but not required.

### What will happen to this issue post release?
There will be a discussion(s) about how the release went and how the next release can be improved.  Then this ticket will be updated with the notes of that discussion along side action items.

**Comment by evs-xsarus** [comment]
I was waiting on the release of 1.2.5 as I believed it had the fix for running the docker using docker-compose based on https://opensearch.org/docs/latest/opensearch/install/docker/#sample-docker-compose-file-for-development .

After testing the 1.3.0 release, the problem still exists:

> ERROR: for opensearch-node1 Cannot start service opensearch-node1: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "./opensearch-docker-entrypoint.sh": stat ./opensearch-docker-entrypoint.sh: no such file or directory: unknown

 as described in:

* https://github.com/opensearch-project/opensearch-build/pull/1130
* https://github.com/opensearch-project/OpenSearch/issues/768

Leaving this out, makes it hard to start development using OpenSearch. It's a missed chance to apply this change to this latest release.

**Comment by dblock** [comment]
We committed high risk changes late, for example https://github.com/opensearch-project/asynchronous-search/pull/104 came in almost at the very end and turned out to be fairly non-trivial.

**Comment by bbarani** [comment]
We should disable the auto-build process for specific release once the release candidate is finalized to avoid last minute changes getting in to the release candidates (Ex: https://github.com/opensearch-project/index-management/pull/311)

**Comment by peterzhuamazon** [comment]
> I was waiting on the release of 1.2.5 as I believed it had the fix for running the docker using docker-compose based on https://opensearch.org/docs/latest/opensearch/install/docker/#sample-docker-compose-file-for-development .
> 
> After testing the 1.3.0 release, the problem still exists:
> 
> > ERROR: for opensearch-node1 Cannot start service opensearch-node1: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "./opensearch-docker-entrypoint.sh": stat ./opensearch-docker-entrypoint.sh: no such file or directory: unknown
> 
> as described in:
> 
>     * [Fix issue with docker volume-mounted config file #1130](https://github.com/opensearch-project/opensearch-build/pull/1130)
> 
>     * [Starting OpenSearch Docker containers fails when using a custom config OpenSearch#768](https://github.com/opensearch-project/OpenSearch/issues/768)
> 
> 
> Leaving this out, makes it hard to start development using OpenSearch. It's a missed chance to apply this change to this latest release.



> I was waiting on the release of 1.2.5 as I believed it had the fix for running the docker using docker-compose based on https://opensearch.org/docs/latest/opensearch/install/docker/#sample-docker-compose-file-for-development .
> 
> After testing the 1.3.0 release, the problem still exists:
> 
> > ERROR: for opensearch-node1 Cannot start service opensearch-node1: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "./opensearch-docker-entrypoint.sh": stat ./opensearch-docker-entrypoint.sh: no such file or directory: unknown
> 
> as described in:
> 
>     * [Fix issue with docker volume-mounted config file #1130](https://github.com/opensearch-project/opensearch-build/pull/1130)
> 
>     * [Starting OpenSearch Docker containers fails when using a custom config OpenSearch#768](https://github.com/opensearch-project/OpenSearch/issues/768)
> 
> 
> Leaving this out, makes it hard to start development using OpenSearch. It's a missed chance to apply this change to this latest release.

Hi @evs-xsarus 

Only come to know this DEV compose file today.
I have opened an issue with documentation, as I also see errors but not the same:
https://github.com/opensearch-project/documentation-website/issues/464

The one we link on the website with 2 data 1 dashboards runs well:
https://opensearch.org/samples/docker-compose.yml

Thanks.

**Comment by ohltyler** [comment]
The component release issues weren't clear on the expectations and led to a lot of last-minute changes. I've included some proposed changes in #1718

**Comment by zelinh** [comment]
# Reflection on OpenSearch Release 1.3.0.

Thanks all contributors for your great effort on authoring code changes, reviewing pull requests, dedications on issues so that we could drive a successful 1.3.0 OpenSearch release.
Special kudos for all our automation processes that helped us drive the fastest release launch call ever.

## Area for improvements
* We created public GitHub release issues on all release plugins repositories. It took quite some time for few repos to assign the release owners and start work on the release tasks. 
* GitHub issue label for 1.3.0 missed to label release issues on some of the plugin repos. We asked teams to triage and label all related release issues with this label. Without that, it's difficult for us to keep track of those issues especially to the current version release.
* Preparation for the release notes was not included in the proper component issue stage which caused delay for collecting them. Everyone feel free to draft PR for our plugin release template [here](https://github.com/opensearch-project/opensearch-build/blob/main/meta/templates/releases/release_template.md) so that we could provide better release experience in the future.
* Last minutes code commit changes after cutoff time pushed the docker build overwriting the release candidates. We had to disable our CI on 1.3.0 to stop accepting any further changes. 
* Campaign issues were only included in the overall release issue in build repo; it's hard for plugin teams to quickly refer to and work on the certain issue on their repositories. 

## Action Items
* https://github.com/opensearch-project/opensearch-build/issues/1787
* https://github.com/opensearch-project/opensearch-build/issues/1767
* https://github.com/opensearch-project/opensearch-build/issues/1762
* https://github.com/opensearch-project/opensearch-build/issues/1718
* https://github.com/opensearch-project/OpenSearch/issues/1891
* https://github.com/opensearch-project/anomaly-detection/issues/265
* https://github.com/opensearch-project/job-scheduler/issues/53
* https://github.com/opensearch-project/cross-cluster-replication/issues/244
* https://github.com/opensearch-project/observability/issues/520

With this we are closing out the retro items for 1.3.0.
