### ISSUE TITLE
[CICD] Migrate lucene snapshot creation PR to pipelines

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#1778]
We currently build lucene snapshots using the old Jenkins.
We need to migrate the freestyle workflow to pipelines to new Jenkins.

Every time when we run a new lucene, someone from Infra Team can trigger the build, and it will push to artifacts.opensearch.org/snapshots/lucene.

Thanks.

**Comment by peterzhuamazon** [comment]
I think @nknize @mch2 can give a better understanding of this.
Thanks.

**Comment by nknize** [comment]
1. Lucene artifacts aren't built with consistent stamped filenames. We'd have to add an entry for each Lucene dependency to `version.properties` making it a nightmare to maintain.

2. Not all upstream artifacts are built at the same time; only the ones that are modified.

3. Artifacts are built by PR, so if a bug is introduced upstream we'd have to rollback or wait for a fix.

4. Using our own snapshot builds gives us certainty over the dependencies.

**Comment by dblock** [comment]
Does it have to be Jenkins? Or a GHA workflow in a new repo?
