### ISSUE TITLE
Planned Breaking Changes for 2.0

### ISSUE THREAD

**Issue by brijos** [opensearch-project/opensearch-build#1780]
### Is your feature request related to a problem? Please describe

This issue is being used to track and increase transparency around the breaking changes planned for the 2.0 release.  The goal is to help the community get a preview of the breaking changes ahead of time so that migration details can be accounted for.  Feedback on the process is welcomed.

### Describe the solution you'd like

Each repo who plans to release breaking changes in 2.0 needs to link to this issue.  This issue will be posted on the public roadmap for the community to see and provide feedback on.  Contributors will do their best to highlight breaking changes early on in the process.  Community members are encouraged to add feedback to the proposed breaking changes to improve the product offering.

### Describe alternatives you've considered

We will be testing this process out and will learn as we go.

**Comment by saratvemulapalli** [comment]
Here is a meta issue for breaking changes in OpenSearch (core).
https://github.com/opensearch-project/OpenSearch/issues/2480

**Comment by cliu123** [comment]
Security plugin breaking changes([PR](https://github.com/opensearch-project/security/pull/1691)):
Security plugin will drop the rolling upgrade support ODFE -> OpenSearch 1.2.0, but will still support the upgrade patch ODFE 1.13 -> OpenSearch 1.x -> OpenSearch 2.0.0

**Comment by seanneumann** [comment]
Dashboards issue tracking breaking changes for plugins... [[2.0] Dashboards Plugin Errors #1206](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1206)

**Comment by martin-gaievski** [comment]
no breaking changes for k-NN plugin

**Comment by jackiehanyang** [comment]
ml-commons and PPL integration has a breaking change, please see more details in [Support more orderless parameters for KEMANS and AD commands](https://github.com/opensearch-project/sql/issues/462)

**Comment by vamsi-amazon** [comment]
sql, observability and reporting plugins have no breaking changes planned for this release.

**Comment by ankitkala** [comment]
No breaking change for cross-cluster-replication
