### ISSUE TITLE
OpenSearch release template improvements

### ISSUE THREAD

**Issue by dreamer-89** [opensearch-project/opensearch-build#1787]
### Is your feature request related to a problem? Please describe

Improvement in release template for OpenSearch repository

### Describe the solution you'd like

Suggestions based on my experience as OpenSearch release manager.

### Generic
- There should be some rough timelines on when specific task needs to be started (and completed if other process is dependent on it). 
### Preparation
-  Triaging and labeling issues for release should be done on recurring basis. Doing this as one time activity before release is error prone.
### CI/CD
- Add step for incrementing the main next release version. Added here: https://github.com/opensearch-project/OpenSearch/pull/2430
- Add step for incrementing the next patch version. Added here: https://github.com/opensearch-project/OpenSearch/pull/2509
- `Re(add) this repo to the (if not exist) [manifest](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/1.3.0/).` This step is not applicable for OpenSearch engine as it being core repository.
### Release
   -  As mentioned [here](https://github.com/opensearch-project/OpenSearch/issues/2257#issuecomment-1067290867), we can make use of tools like git-release-notes to get release notes in markdown. 
   -   Remove the dependabot commits (feedback from @dblock @stockholmux ) from generated release notes.
### Post Release
- `Create a release tag` can be removed as there is already automation in place to create those automatically. 

Related: https://github.com/opensearch-project/OpenSearch/issues/2257

**Comment by zelinh** [comment]
Thanks for the reviews here. Some of your suggestion have been updated in our component release notes template here. https://github.com/opensearch-project/opensearch-build/blob/main/meta/templates/releases/release_template.md
You can create a PR there to help us optimize it for future release.

**Comment by bbarani** [comment]
@zelinh @dreamer-89 Do you have any updates on this issue?

**Comment by bbarani** [comment]
@zelinh @dreamer-89 Do you have any updates on this issue?

**Comment by zelinh** [comment]
We have updated our template here. https://github.com/opensearch-project/opensearch-build/pull/3635
Do we have any other concerns regarding of this @dreamer-89 or I could close this issue. Thanks.

**Comment by dreamer-89** [comment]
> We have updated our template here. #3635 Do we have any other concerns regarding of this @dreamer-89 or I could close this issue. Thanks.

Thanks @zelinh for the update. As template is updated, closing this issue.
