### ISSUE TITLE
[Bug]: OpenSearch-2.0.0 snapshot build is failing due to common-utils

### ISSUE THREAD

**Issue by vamshin** [opensearch-project/opensearch-build#1790]
### Describe the bug

OpenSearch-2.0.0 snapshot build is failing since March 9th 
https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/opensearch/2.0.0-SNAPSHOT/

### To reproduce

https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/opensearch/2.0.0-SNAPSHOT/

### Expected behavior

New snapshot available with latest Main branch changes of OpenSearch core

**Comment by dblock** [comment]
@praveensameneni

**Comment by praveensameneni** [comment]
@getsaurabh02 is looking into the issue

**Comment by bbarani** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'common-utils'.
> Could not resolve all files for configuration ':classpath'.
   > Could not find org.opensearch.gradle:build-tools:2.0.0.
     Searched in the following locations:
       - file:/usr/share/opensearch/.m2/repository/org/opensearch/gradle/build-tools/2.0.0/build-tools-2.0.0.pom
       - https://repo.maven.apache.org/maven2/org/opensearch/gradle/build-tools/2.0.0/build-tools-2.0.0.pom
       - https://plugins.gradle.org/m2/org/opensearch/gradle/build-tools/2.0.0/build-tools-2.0.0.pom
       - https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/gradle/build-tools/2.0.0/build-tools-2.0.0.pom
     Required by:
         project :

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

**Comment by getsaurabh02** [comment]
Hi @vamshin @bbarani 
Looked into the [code change](https://github.com/opensearch-project/common-utils/pull/122/files) for ``2.0`` version change for ``common-utils`` and they seem to be complete. However from the failure above, it looks like the ``opensearch_version`` being expected [here](https://github.com/opensearch-project/common-utils/pull/122/files#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7R21) is ``2.0.0-SNAPSHOT`` and not just ``2.0.0``, which seems to be the cause of the issue in this case. This has been a standard so far. Can we confirm this once by updating the build argument, and discuss if there are any change in the expectation here.

cc: @lezzago

**Comment by bbarani** [comment]
@getsaurabh02 I think it needs to point to opensearch 2.0.0-alpha10SNAPSHOT as this is not a GA release. @dblock @peterzhuamazon Can you confirm?

**Comment by peterzhuamazon** [comment]
The issue is related to recently changing to `2.0.0-alpha1` in the revision.
```
+ ./gradlew build -x test -Dopensearch.version=2.0.0-SNAPSHOT -Dbuild.snapshot=true -Dbuild.version_qualifier=
+ ./gradlew build -x test -Dopensearch.version=2.0.0 -Dbuild.snapshot=false -Dbuild.version_qualifier=
```

New plugins needs to allow their qualifier to have `2.0.0` the opensearch.version, they also need to change their qualifier to `alpha1`.

```
-Dopensearch.version=2.0.0 -Dbuild.version_qualifier=alpha1
```

Also need to make sure their 
```
        opensearch_version = System.getProperty("opensearch.version", "2.0.0-alpha1-SNAPSHOT")
```

Thanks.

**Comment by peterzhuamazon** [comment]
I have figured out the common-utils issue will send PR.
