### ISSUE TITLE
[Enhancement] Add new subfolder to support more distributions

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#1800]
As of now, we only have one folder for all distributions:
```
# local
builds/opensearch/dist/
dist/opensearch/

# S3
distribution-build-opensearch/1.3.0/1362/linux/x64/dist/opensearch/
```

This would cause issues on Jenkins as we tend to build multiple distributions together.
This means one manifest.yml would override the other one.
```
manifest.yml 
opensearch-1.3.0-linux-x64.tar.gz
opensearch-1.3.0-linux-x64.rpm
```

We would like to add a new subfolder such that:
```
# local
builds/opensearch/tar/dist/
builds/opensearch/rpm/dist/

dist/opensearch/tar/
dist/opensearch/rpm/

# S3
distribution-build-opensearch/1.3.0/1362/linux/x64/dist/opensearch/tar/
distribution-build-opensearch/1.3.0/1362/linux/x64/dist/opensearch/rpm/

```

Thanks.

**Comment by peterzhuamazon** [comment]
Similar to https://github.com/opensearch-project/opensearch-build/pull/1145

**Comment by tianleh** [comment]
Taking a look. Similar to my previous work to introduce `opensearch` and `opensearch-dashboards` subfolders https://github.com/opensearch-project/opensearch-build/pull/1145

cc @seraphjiang

**Comment by tianleh** [comment]
RPM build for OSD 2.0.0 failed https://github.com/opensearch-project/opensearch-build/pull/1807#issuecomment-1076059844

RPM build for OSD 1.3.0 also failed https://github.com/opensearch-project/opensearch-build/pull/1807#issuecomment-1076074548

**Comment by peterzhuamazon** [comment]
> RPM build for OSD 2.0.0 failed [#1807 (comment)](https://github.com/opensearch-project/opensearch-build/pull/1807#issuecomment-1076059844)
> 
> RPM build for OSD 1.3.0 also failed [#1807 (comment)](https://github.com/opensearch-project/opensearch-build/pull/1807#issuecomment-1076074548)

Support in #1815
