### ISSUE TITLE
[Bug]: Auto-release workflow creates a v{{release}} label

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#1808]
### Describe the bug

The variable name isn't expanding for the label of the newly created release issues. 

### To reproduce

The workflow that runs is https://github.com/opensearch-project/opensearch-build/blob/main/.github/workflows/releases.yml
Example: https://github.com/opensearch-project/opensearch-build/issues/1805

### Expected behavior

Version label to be expanded into an actual version number.

### Screenshots

<img width="351" alt="Screen Shot 2022-03-23 at 11 24 51 AM" src="https://user-images.githubusercontent.com/542335/159734940-751cc140-7ad2-491e-829f-87bce67138c6.png">

### Additional context

Check that create-an-issue supports expanding labels. I believe it does, so not sure what's going on here. Maybe just a typo somewhere in the template.

**Comment by peterzhuamazon** [comment]
This seems like an issue with how github interpret {{}} with the leading letter `v`.
We will close this for now, please feel free to reopen it.

Thanks.

**Comment by dblock** [comment]
This is still a problem, the auto workflow still opens tickets with the wrong label and the newer version of the GitHub action I believe fixes it.

**Comment by peterzhuamazon** [comment]
Find the issue:

https://github.com/JasonEtco/create-an-issue/issues/74#issuecomment-739554602

**Comment by peterzhuamazon** [comment]
Seems like @dblock already implement this then I can either fix in his fork, or just create a new env var with the `v` + `VERSION`.

https://github.com/JasonEtco/create-an-issue/pull/95

**Comment by dblock** [comment]
Yes please use https://github.com/marketplace/actions/create-a-github-issue!

**Comment by peterzhuamazon** [comment]
I was reading about nunjucks and seems like it is just not checking out the latest changes you implemented here:

https://github.com/dblock/create-a-github-issue/commit/95768e83ba103bc646df2aa691258fe8207cf2c6

Thanks.
