### ISSUE TITLE
Require 1 approval on this repo for merging PRs

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#181]
**Is your feature request related to a problem? Please describe.**
Unlike other repositories in opensearch-project, this one requires 2 people to approve PRs. This creates an illusion of security,  as the untrusted part of this system is the component build code, not the build system itself. Having 2-PR reviews on the execution environment doesn't buy us much safety if the untrusted code we're executing can change with only one review.

**Describe the solution you'd like**
Lower the number of people required to make changes to 1.

**Comment by peternied** [comment]
[Triage] We are going to keep this setting as is for the time being, as we get more automation and coverage we can look at revisiting this.
