### ISSUE TITLE
[Bug]: job-scheduler build fails for tag 1.2.0.0

### ISSUE THREAD

**Issue by rishabh6788** [opensearch-project/opensearch-build#1810]
### Describe the bug

While following build instructions for Opensearch the plugin build for job-scheduler is failing with below error for OpenSearch-1.2.0:
2022-03-16 17:02:01 INFO Executing "bash /tmp/tmp2lphhlcp/job-scheduler/scripts/build.sh -v 1.2.0 -p linux -a x64 -s false -o builds" in /tmp/tmp2lphhlcp/job-scheduler

getopts :h✌️s⭕a: arg
case $arg in
VERSION=1.2.0
getopts :h✌️s⭕a: arg
case $arg in
echo 'Invalid option: -?'
Invalid option: -?
exit 1
2022-03-16 17:02:01 ERROR Error building job-scheduler, retry with: ./build.sh manifests/1.2.0/opensearch-1.2.0.yml --component job-scheduler
The issue is that build.sh script in job-scheduler for 1.2.0.0 tag do not support platform parameter https://github.com/opensearch-project/job-scheduler/blob/1.2.0.0/scripts/build.sh.
This change is present in newly released Opensearch-1.3.0 and the build succeeds without any issue.

### To reproduce

Run ./build.sh manifests/1.2.0/opensearch-1.2.0.yml 

### Expected behavior

The build for Opensearch-1.2.0 and plugins should succeed while following the build instructions in the Readme.

**Comment by dblock** [comment]
With 1.3.0 shipped we can remove 1.2.0 scheduled job and stop building that. That's the easiest fix. Otherwise we should be using an older tag of opensearch-build.

**Comment by peterzhuamazon** [comment]
This is not a problem @rishabh6788 as you can use the tags of 1.2.x to build.
Main is not guaranteed to run older builds that is the reason we create tags.
Close this issue as for now.

Thanks.
