### ISSUE TITLE
[Bug] Support specifying distribution for test scripts

### ISSUE THREAD

**Issue by tianleh** [opensearch-project/opensearch-build#1812]
Once https://github.com/opensearch-project/opensearch-build/issues/1800 is implemented, the manifest.yml path or url will have a subfolder for distribution. We may need to introduce a distribution parameter to figure out which distribution's yml to use.

E.g The current test command is 

`./test.sh integ-test manifests/1.3.0/opensearch-dashboards-1.3.0-test.yml -p opensearch=https://ci.opensearch.org/ci/dbc/Playground/tianleh-test/tianle-opensearch-build-3-22/1.3.0/5/linux/x64 opensearch-dashboards=https://ci.opensearch.org/ci/dbc/Playground/tianleh-test/tianleh-osd-build-3-22/1.3.0/7/linux/x64
`

The current logic is to find manifest under `dist/opensearch/manifest.yml` but there could be different distributions `dist/opensearch/tar/manifest.yml` The `tar` will need to be provided from the test command.

**Comment by dblock** [comment]
Shouldn't the path just include tar? `-p opensearch=https://ci.opensearch.org/ci/dbc/Playground/tianleh-test/tianle-opensearch-build-3-22/1.3.0/5/linux/x64/**tar**`

**Comment by tianleh** [comment]
> Shouldn't the path just include tar? `-p opensearch=https://ci.opensearch.org/ci/dbc/Playground/tianleh-test/tianle-opensearch-build-3-22/1.3.0/5/linux/x64/**tar**`

Per https://github.com/opensearch-project/opensearch-build/issues/1800 , the structure is `builds/opensearch/tar/dist/` If we want to achieve https://github.com/opensearch-project/opensearch-build/issues/1812#issuecomment-1076763124 we may need to update the structure to be `tar/builds/opensearch/dist`

Looks like `tar/builds/opensearch/dist` is simpler. cc @peterzhuamazon @dblock

**Comment by tianleh** [comment]
Verify that the upload permission doesn't need changes since it is wildcard match. https://github.com/opensearch-project/opensearch-build/blob/main/deployment/lib/identities.ts

**Comment by dblock** [comment]
What do you propose @tianleh for full build paths? What does the following become?

https://ci.opensearch.org/ci/dbc/Playground/tianleh-test/tianle-opensearch-build-3-22/1.3.0/5/linux/x64/
https://ci.opensearch.org/ci/dbc/Playground/tianleh-test/tianle-opensearch-build-3-22/1.3.0/5/linux/arm64

**Comment by tianleh** [comment]
I am proposing the following (inspired by your suggestion):

the local structure will look like 
`tar/builds/opensearch/dist`
`tar/dist/opensearch/`

The full urls will become
https://ci.opensearch.org/ci/dbc/Playground/tianleh-test/tianle-opensearch-build-3-22/1.3.0/5/linux/x64/tar/builds/opensearch/manifest.yml

https://ci.opensearch.org/ci/dbc/Playground/tianleh-test/tianle-opensearch-build-3-22/1.3.0/5/linux/arm64/tar/dist/opensearch/manifest.yml

Then there is no need to change the code logic for integ/bwc test. We just need to pass the new url into test command.

We may need to update the artifact uploading logic to upload the `tar` instead of `builds`/`dist`
https://github.com/opensearch-project/opensearch-build/blob/main/vars/uploadArtifacts.groovy#L12

@dblock

**Comment by tianleh** [comment]
> Verify that the upload permission doesn't need changes since it is wildcard match. https://github.com/opensearch-project/opensearch-build/blob/main/deployment/lib/identities.ts

For this file, if we do not want to make any changes, then the artifact upload logic will upload `tar/builds` and `tar/dist` so that the wildcard match can take effect.

**Comment by tianleh** [comment]
One small issue is that the local structure will look a bit messy since it will have `rpm`, `tar` under the root directory while the original solution will have `builds` under the root directory.

**Comment by dblock** [comment]
> One small issue is that the local structure will look a bit messy since it will have `rpm`, `tar` under the root directory while the original solution will have `builds` and `dist` under the root directory.

Right, so that feels strange, but are the artifacts in builds radically different in the two types of builds? 

I feel like we need to merge builds and dist into a single pipeline, but that's a different problem.

**Comment by tianleh** [comment]
I will continue with the proposal in https://github.com/opensearch-project/opensearch-build/issues/1812#issuecomment-1076826408 We can later continue optimizing the local structure since it is not customer facing.

@dblock

**Comment by peterzhuamazon** [comment]
We need to add the platform folder in test recorder just like the one in distribution.

**Comment by peterzhuamazon** [comment]
This can be closed now as the --paths param already point to specific build manifest, which has distribution related param and information.

Thanks.
