### ISSUE TITLE
Update IntegTest job to accept parameters based on manifest and kick off multiple integ tests in parallel.

### ISSUE THREAD

**Issue by setiah** [opensearch-project/opensearch-build#183]

**Comment by camerski** [comment]
I don't think we should be updating the existing Jenkins integ test job. It does not do what we need, is heavily hard-coded, and it's going to be less work to implement #177 with a new, trivial Jenkins job to wrap it.

**Comment by setiah** [comment]
Closing as this is covered under atomic task #263
