### ISSUE TITLE
Markdown URLs in notification message

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/opensearch-build#1831]
### Is your feature request related to a problem? Please describe

The notifications are starting to become large with a lot of results and links.

### Describe the solution you'd like

I believe slack supports it by <link|text> but I'm not sure if our system supports it. Perhaps we can list results as `Integ Tests (x64) [RESULTS]` with `[RESULTS]` being a link to the absolute url. Links to builds and dist folders for the artifacts can just be `[BUILD-MANIFEST]` `[DIST-MANIFEST]`. People can still right click on the URL and get the full URL but least it cleans up the notification if there are a bunch of builds.

**Comment by zelinh** [comment]
[Triage] @prudhvigodithi will work with you on the notification for dashboards and once we have the same convention for OpenSearch and OSD, we can start to mark them.

**Comment by bbarani** [comment]
@kavilla As a first step we have surfaced the failures on the notification message. We can enhance the message with markdown but our ultimate goal is to create automated GitHub issues for the build failures corresponding to a specific repo.

**Comment by kavilla** [comment]
Oh that would be cool!

**Comment by bbarani** [comment]
We are moving away from internal communication to creating issues directly on GitHub hence closing this issue. Feel free to re-open if needed.
