### ISSUE TITLE
Support RPM in integ test

### ISSUE THREAD

**Issue by tianleh** [opensearch-project/opensearch-build#1857]
### Is your feature request related to a problem? Please describe

Currently the execution flow of `test.sh` has hardcoded logic for tarball. https://github.com/opensearch-project/opensearch-build/blob/main/src/test_workflow/integ_test/service_opensearch.py#L54

Also the latest url for OpenSearch shall be updated to support distribution parameter
https://github.com/opensearch-project/opensearch-build/blob/main/vars/runIntegTestScript.groovy#L25

### Describe the solution you'd like

see above

**Comment by bbarani** [comment]
Duplicate of https://github.com/opensearch-project/opensearch-build/issues/1951
