### ISSUE TITLE
[Enhancement] Create a groovy src library for distribution manifest

### ISSUE THREAD

**Issue by zelinh** [opensearch-project/opensearch-build#1877]
### Is your feature request related to a problem? Please describe

Currently we only have `BuildManifest` and `InputManifest` Jenkins method to process and fetch information from either build manifest or the manifest for ci pipeline. Although we can use `BuildManifest` to process the data for the distribution bundle manifest but it still lacks of some info like `location`. We should have a Jenkins library specifically for distribution manifest for those who want to use. 
Example distributon manifest from 1.3.1 release: https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/1.3.1/1584/linux/x64/dist/opensearch/manifest.yml

### Acceptance criteria

- [ ] We have a Jenkins library `DistributionManifest.groovy` used to process info from distribution manifest.

### Describe alternatives you've considered

Keep using the library based on `BuildManifest.groovy` but makes it more general for both types of manifest.

**Comment by abhinavGupta16** [comment]
[triage] It's a good idea to separate the manifests if it has a use case. We'll need to update the tag creation job once this is complete to use the `DistributionManifest.groovy`

**Comment by zelinh** [comment]
Closing this issue as we now have this library available.
