### ISSUE TITLE
[Enhancement] Possible gradle plugin to take care of version/qualifier/snapshot

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#1892]
In this PR, Drew suggested that we create a gradle plugin to take care of version/qualifier/snapshot going on, so that other component can simply pull the plugin for any changes.
https://github.com/opensearch-project/index-management/pull/323

Seeing how many PRs I have already sent to components just for this qualifier verison change, I would say we can invest some resources to get this happen and free up all the repetitive changes.

https://github.com/opensearch-project/opensearch-build/issues/1632

Thanks.

**Comment by abhinavGupta16** [comment]
[triaged] It's a valid issue. We will look into options to accommodate this

**Comment by peterzhuamazon** [comment]
We do not need this anymore as we only do this one time every major version.

Close this for now and please feel free to re-open if needed.

Thanks.
