### ISSUE TITLE
Create issues on build failures

### ISSUE THREAD

**Issue by abhinavGupta16** [opensearch-project/opensearch-build#1899]
### Is your feature request related to a problem? Please describe

We want to create a github issue in the respective plugins, opensearch or OpenSearch-dashboards repositories when the build failures.

### Describe the solution you'd like

- [x] Filter out issues from noise about build failure
- [x] Create issues in respective repositories for build failures on jenkins.
- [x] Tag owners in build failures on github once the issue is created.
- [x] Duplicate issues are not created for build failures

### Acceptance Criteria
- [x] Github issue is created automatically in the respective repository when the build fails.
- [x] Duplicate issues are not created
- [x] Issues are filtered based on failures to avoid noise

**Comment by rishabh6788** [comment]
The required PR has been merged and issue creation has been enabled. 
Example: https://github.com/opensearch-project/performance-analyzer/issues/282. 

Closing this issue.
