### ISSUE TITLE
Remove hardcoded git repo checkout for the repo `opensearch-build`

### ISSUE THREAD

**Issue by tianleh** [opensearch-project/opensearch-build#1901]
We have noticed a few places where the build repo link is hardcoded for checkout. E.g
https://github.com/opensearch-project/opensearch-build/blob/ff40ffba5e96836eaf8a3d70f0b4444bf6d2ef2b/vars/buildDockerImage.groovy

https://github.com/opensearch-project/opensearch-build/blob/9a82a23231cfa6f07bc4fa677b43795fbe8f49ff/vars/detectDockerAgent.groovy

Developers need to modify these values to their folked repo name and branch which is lowering the development efficient. These values shall read from the local workspace or as params.

**Comment by tianleh** [comment]
cc @peterzhuamazon

**Comment by abhinavGupta16** [comment]
[triage] We can take in the repository url and the branch as parameters and default to main if not provided for places where we checkout `opensearch-build` within libraries.

**Comment by peterzhuamazon** [comment]
Apparently jenkins would pull git repo when pulling the jenkinsfile, so we can delete these git url calls once we confirm not needing them anymore.

Thanks.

**Comment by peterzhuamazon** [comment]
This is nearly done except @zelinh whitesource scan, but that one is ok as it does not need to specify other versions.
@zelinh can decide whether want to change it or not.

Thanks.
