### ISSUE TITLE
[Bug]: Maven snapshots for a particular version fall behind "Qualified" versions.

### ISSUE THREAD

**Issue by mch2** [opensearch-project/opensearch-build#1910]
### Describe the bug

Qualifiers are being added to the version of maven publications.  At that point the nightlies without the qualifier fall behind and are not updated.  This also adds an extra step for all repos that depend on opensearch packages to update to the latest qualified version string in their ci.  With the introduction of the alpha1 build we now have the following builds in [sonatype](https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/opensearch-core/).

```
2.0.0-SNAPSHOT/	Wed Mar 09 01:41:04 UTC 2022	 	
2.0.0-alpha1-SNAPSHOT/	Tue Apr 05 21:48:15 UTC 2022
```

The builds with the alpha1 qualifier are now 27 days newer than the 2.0.0-SNAPSHOT while the "alpha1" versions are updated nightly.

### To reproduce

https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/opensearch-core

### Expected behavior

I'd expect 2.0.0-SNAPSHOT to hold the latest snapshot and be equal to or ahead of a qualified version.  Users should be able to pull in the latest SNAPSHOT of a major.minor.patch version of the repo, even if a version with a qualifier is cut at a certain point.  Also as a side question, I'm not sure what benefit we get from qualifiers in maven dependencies? The snapshot with the qualifier in it is still a moving target.

**Comment by zelinh** [comment]
[Triage] @mch2 From what we discussed, the qualifier would be picked up from the manifest. We are not sure it's possible to have both snapshots existing. @dblock Could you provide more information here?

**Comment by mch2** [comment]
Hi @zelinh.  Yes, the qualifier is picked up from the manifest and passed down to each component - [example](https://github.com/opensearch-project/opensearch-build/blob/main/scripts/components/OpenSearch/build.sh#L141).  I would imagine we need the qualifier on the assembled artifact, so passing to `./gradlew assemble`, but I'm not sure we need these for maven artifacts in `z./gradlew publishNebulaPublicationToTestRepository -Dbuild.snapshot=$SNAPSHOT -Dbuild.version_qualifier=$QUALIFIER`.  I think we should be able to leave the qualifiers out of those publish commands.

Is there a use case for having the maven artifacts include qualifiers?
