### ISSUE TITLE
Upload the distribution snapshot plugin zips to nexus maven snapshot repo.

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/opensearch-build#1917]
### Is your feature request related to a problem? Please describe

https://github.com/opensearch-project/opensearch-build/issues/1234

### Describe the solution you'd like

`mvn install:install-file -DgroupId=org.opensearch.plugin -DartifactId=pgplugin -Dversion=0.0.1 -Dpackaging=zip -Dfile=package.zip -DlocalRepositoryPath=../loacalrepo/`

With the above cli command now we have folder created as maven coordinates 
`loacalrepo/org/opensearch/plugin/pgplugin/0.0.1`

This will have pom file and zip file stored in `loacalrepo/org/opensearch/plugin/pgplugin/0.0.1`

**settings.xml**
```
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                      https://maven.apache.org/xsd/settings-1.0.0.xsd">
  <servers>
    <server>
      <id>nexus</id>
      <username>${SONATYPE_USERNAME}</username>
      <password>${SONATYPE_PASSWORD}</password>
    </server>
  </servers>
</settings>
```

`mvn --settings="${mvn_settings}" deploy:deploy-file -DgeneratePom=false -DrepositoryId=nexus -DpomFile=loacalrepo/org/opensearch/plugin/pgplugin/0.0.1/pgplugin-0.0.1.pom -Dfile=loacalrepo/org/opensearch/plugin/pgplugin/0.0.1/pgplugin-0.0.1.zip -Durl=$repo_url`

**Comment by dblock** [comment]
Looks like a dup of https://github.com/opensearch-project/opensearch-build/issues/716

**Comment by prudhvigodithi** [comment]
Hey @dblock, since there are two aspects for this maven publish, one for snapshots repo and other for actual release repo, the two repo workflows are not constant, as release repo has more wider process, like pre staging, promoting, signing, additional maven tags and then releasing, so I have created a meta issue https://github.com/opensearch-project/opensearch-build/issues/1916 that expands with more details based on the issue https://github.com/opensearch-project/opensearch-build/issues/716. 
Right now the snapshot zips for maven snapshot repo, does not have an enforced workflow to publish a zip, unlike the actual release repo, so I have separated into two tasks for snapshot plugin zips and release plugin zips and together tracked in https://github.com/opensearch-project/opensearch-build/issues/1916.

**Comment by prudhvigodithi** [comment]
Using the plugin [opensearch.pluginzip](https://github.com/opensearch-project/opensearch-plugins/blob/main/BUILDING.md#opensearchpluginzip) and with existing [CI worflows](https://github.com/opensearch-project/opensearch-build/tree/main/jenkins), the zips will signed and published
Example
https://repo1.maven.org/maven2/org/opensearch/plugin/opensearch-ml-plugin/2.0.1.0/
https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/plugin/opensearch-ml-plugin/2.1.0.0-SNAPSHOT/
Closing this issue as resolved :)
@dblock @bbarani
