### ISSUE TITLE
Sign and Upload the release plugin zips to nexus maven release repo.

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/opensearch-build#1918]
### Is your feature request related to a problem? Please describe

https://github.com/opensearch-project/opensearch-build/issues/1234

### Describe the solution you'd like

**settings.xml**

```
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                      https://maven.apache.org/xsd/settings-1.0.0.xsd">
                    
  <servers>
    <server>
      <id>nexus</id>
      <username>${SONATYPE_USERNAME}</username>
      <password>${SONATYPE_PASSWORD}</password>
    </server>
  </servers>
</settings>
```

Create a staging repo` nexus-staging:rc-open`   this will create a new new staging repository on the remote Nexus 
Upload zips from the local filesystem to a staging repository using plugin in built `deploy-staged-repository`
Close the created staging repo `nexus-staging:rc-close `

- Sign the generate zips.
- Stage them as per staging repo workflow requirements.
- Add necessary tags in POM xml (modify before uploading) Example as
```
<licenses>
<license>
<name>The Apache License, Version 2.0</name>
<url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
</license>
</licenses>
<developers>
<developer>
<id>amazonwebservices</id>
<organization>Amazon Web Services</organization>
<organizationUrl>https://aws.amazon.com</organizationUrl>
</developer>
</developers>
<scm>
<connection>scm:git@github.com:opensearch-project/common-utils.git</connection>
<developerConnection>scm:git@github.com:opensearch-project/common-utils.git</developerConnection>
<url>git@github.com:opensearch-project/common-utils.git</url>
</scm>
<dependencies/>
```
- Once verified publish to release repo.

**Comment by dblock** [comment]
Looks like a subset of https://github.com/opensearch-project/opensearch-build/issues/716

**Comment by prudhvigodithi** [comment]
Hey @dblock, there are two aspects for this maven publish, one for snapshots repo and other for actual release repo, the two repo workflows are not constant, as release repo has more wider process, like pre staging, promoting and signing, so I have created a meta issue https://github.com/opensearch-project/opensearch-build/issues/1916 that expands with more details based on the issue https://github.com/opensearch-project/opensearch-build/issues/716.

**Comment by prudhvigodithi** [comment]
Using the plugin [opensearch.pluginzip](https://github.com/opensearch-project/opensearch-plugins/blob/main/BUILDING.md#opensearchpluginzip) and with existing [CI worflows](https://github.com/opensearch-project/opensearch-build/tree/main/jenkins), the zips will signed and published
Example
https://repo1.maven.org/maven2/org/opensearch/plugin/opensearch-ml-plugin/2.0.1.0/
Closing this issue as resolved :) 
@dblock @bbarani
