### ISSUE TITLE
Github workflow integration with public S3 buckets using OIDC.

### ISSUE THREAD

**Issue by mch2** [opensearch-project/opensearch-build#1920]
We have multiple issues popping up requiring new snapshot builds of lucene to artifacts.opensearch. Related issues: https://github.com/opensearch-project/OpenSearch/issues/2785 and https://github.com/opensearch-project/OpenSearch/issues/2786.

Currently the only way for us to do this is with a jenkins job that only a few have access to see & execute.  This slows us down and adds an extra job that needs to be maintained in the jenkins stack when it can be a simple gh workflow.

I would like to propose we improve this process by setting up a gh workflow in the OpenSearch repo that builds and publishes lucene snapshots to artifacts.opensearch.org using OIDC.

I've put together a test workflow [here](https://github.com/mch2/TestActions/blob/main/.github/workflows/lucene-snapshots.yml) to demonstrate.  This workflow can be used as is subbing in bucket & roles.

To do this I will need help setting up the OIDC provider, role, and policy to the specific s3 bucket.  This is the recommended way to assume role & fetch credentials from GH workflows - https://github.com/aws-actions/configure-aws-credentials#assuming-a-role as it does not use long running aws creds.  If this is acceptable I am happy to PR the necessary cdk or cfn scripts to set it up, which is almost identical to [this](https://github.com/aws-actions/configure-aws-credentials#sample-iam-role-cloudformation-template) example.

**Comment by peternied** [comment]
There are build jobs that produce maven snapshot artifacts, how about setup our own of lucence which uploads to our maven instance and then pass around that path?

Seems like it might be easier to continuously build the lucence setting aside any concerns with access control / permissions

**Comment by mch2** [comment]
> There are build jobs that produce maven snapshot artifacts, how about setup our own of lucence which uploads to our maven instance and then pass around that path?
> 
> Seems like it might be easier to continuously build lucence setting aside any concerns with access control / permissions

Hey Peter thanks for the input. Few concerns:

1. The build output is not visible.  We need the commit sha from build output to include in the version string linked above in order to pull a snapshot.  We want to lock to a build vs a branch - [related](https://github.com/opensearch-project/opensearch-build/issues/1778#issuecomment-1072661738). 
2. This is fine as long as we are pushing to artifacts.opensearch (or another public bucket) and not sonatype maven repo. We still require these dependencies to be consumed in opensearch under the same group and artifact IDs so we can easily swap between our snapshots. & release versions by specifying the version [here](https://github.com/opensearch-project/OpenSearch/blob/main/buildSrc/version.properties#L2).  I don't think we are able to push there for a group id outside of org.opensearch.
3. Redundant builds, this is only needed ad-hoc.
4. To add a build of a separate lucene branch adds an extra PR step.

**Comment by peternied** [comment]
> 1. The build output is not visible.
If the jenkins output was public would this be an issue?

> 2. I don't think we are able to push there for a group id outside of org.opensearch.
Not sure that we need maven, but if build consumption is easier it might be worthwhile.  It would be good to know if its possible.

> 3. Redundant builds, this is only needed ad-hoc.
Check for build has a mechanism not to rebuild on the same git SHA, it could be leverage.  We could create a Lucence fork just for this purpose if it makes sense and more closely tie it to our systems.  Note, this could have huge overlap with asking/offering Lucence a cleaner method

**Comment by mch2** [comment]
I've been thinking about this. Given that these are not "prod" artifacts or part of the OpenSearch distribution I don't think they belong in artifacts.opensearch, I'd like to go ahead and make a separate account & bucket.

**Comment by zelinh** [comment]
[Triage] @mch2 Please let us know if you need help from us on this.

**Comment by dlvenable** [comment]
@mch2 , Having done something somewhat similar for Data Prepper, I think your proposed approach is reasonable. In addition to using the Data Prepper release process to stage artifacts for production, we also may use it for pre-release builds (e.g. weekly or nightly builds). That latter use-case seems somewhat similar to what you wish to do.

Also, if it helps, we have a CloudFormation stack you could use which sets up the Data Prepper staging environment. It is probably almost exactly what you want aside from the ECS repository.

https://github.com/opensearch-project/data-prepper/tree/main/release/staging-resources-cdk/lib

There are a few constants related to Data Prepper (e.g. the repository which may access the OIDC credentials), but these should be easy to resolve.

**Comment by mch2** [comment]
Thanks @dlvenable ! This is exactly what we need.  In fact I was able to reuse the same cdk project without the ecr resources.  Leaving this issue open until I PR and wire up the workflow.
