### ISSUE TITLE
[Bug]: add `nvm` to docker image PATH env var

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/opensearch-build#1922]
### Describe the bug

Origin: https://github.com/opensearch-project/opensearch-build/pull/1905

This PR fixes the build for `2.0.0` OSD but I had to source the `nvm` from `$NVM_DIR` which could technically be undefined. Which the same could be said about adding it the PATH variable but assuming PATH is more safe than assuming NVM_DIR.

### To reproduce

Don't export $NVM_DIR and these scripts will fail

### Expected behavior

I don't need to source nvm everytime just incase I want to use it because it will have already been added to PATH

**Comment by zelinh** [comment]
[Triage] @kavilla Is this resolved?

**Comment by kavilla** [comment]
I still believe this should be done. For my solution I sourced nvm from$ NVM_DIR which has potential to not be defined. We should ensure to add the script PATH [here](https://github.com/opensearch-project/opensearch-build/blob/main/docker/ci/dockerfiles/build.centos7.opensearch-dashboards.x64.arm64.dockerfile#L151), so that we do not have to rely on $NVM_DIR be created.

**Comment by bbarani** [comment]
@kavilla Whats the current status of this issue?

**Comment by kavilla** [comment]
I could add it but I don't have the resources to publish this to docker hub.

**Comment by bbarani** [comment]
@peterzhuamazon @gaiksaya Can you help @kavilla here?

**Comment by gaiksaya** [comment]
Sure, @kavilla Can you point to the right script PATH? Looks like the one you posted is giving 404

**Comment by peterzhuamazon** [comment]
This has been fixed by using `nvm install` and syncing the version from dashboards core/plugin repo .nvmrc file.
