### ISSUE TITLE
[Build] check if NVM_DIR exists

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/opensearch-build#1925]
### Is your feature request related to a problem? Please describe

Origin: https://github.com/opensearch-project/opensearch-build/pull/1905

NVM_DIR might not be defined while building OSD.

### Describe the solution you'd like

check if NVM_DIR exists before trying to use it. If not out put an explicit error message

@peterzhuamazon note: This is explicitly related to the OSD and OSD plugins build.sh that requires use of nvm to switch nodejs versions.

### Describe alternatives you've considered

https://github.com/opensearch-project/opensearch-build/issues/1922

**Comment by bbarani** [comment]
@kavilla Are you actively looking in to this issue?

**Comment by kavilla** [comment]
I am not. Apologies. But I added a good first issue label to this. This will be an improvement and relatively small but is not a blocker for anything.

**Comment by Sugarlust** [comment]
Hey @kavilla I would like to try to fix this issue. Do you have any idea on where I should start looking ?

**Comment by bbarani** [comment]
According to @peterzhuamazon, this is not an issue anymore so closing it. Feel free to re-open if needed.
