### ISSUE TITLE
Option to tag the image as latest when promoting docker image

### ISSUE THREAD

**Issue by abhinavGupta16** [opensearch-project/opensearch-build#1935]
### Is your feature request related to a problem? Please describe

[docker-ecr-promote](https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/docker-ecr/docker-ecr-promote.jenkinsfile) job currently is able to promote multi-arch docker images from staging to production. However, the promoted image is not marked as latest, which would be a common requirement when releasing to production. 

### Describe the solution you'd like

There are two possible solutions - 
- Always mark the promoted image as latest, to ecr and docker-hub
- Give an option parameter to mark the image as latest during promotion

### Acceptance Criteria
- We are able to mark image as latest for ecr and dockerhub when promoting image to production environments

**Comment by zelinh** [comment]
[Triage] This is a valid issue. We can add this in our docker promotion job.

**Comment by bbarani** [comment]
Closing this issue as we have merged the PR to implement this feature.
