### ISSUE TITLE
Build System - Create InputManifest for OpenSearch 2.0 build

### ISSUE THREAD

**Issue by mch2** [opensearch-project/opensearch-build#194]
Create an InputManifest for the 2.0 bundle build that records all components that should be included.

The manifest should look like the one created for [1.0](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/opensearch-1.0.0.yml) and live next to it in this repo.

**Comment by dblock** [comment]
We need 1.1 too and start building that.

**Comment by peternied** [comment]
[Triage] This manifest has been created https://github.com/opensearch-project/opensearch-build/tree/main/manifests/2.0.0
