### ISSUE TITLE
[Retrospective] Release 1.3.1

### ISSUE THREAD

**Issue by abhinavGupta16** [opensearch-project/opensearch-build#1943]
#1885 

How to use this issue?
Please add comments to this issue, they can be small or large in scope. Honest feedback is important to improve our processes, suggestions are also welcomed but not required.

What will happen to this issue post release?
There will be a discussion(s) about how the release went and how the next release can be improved. Then this ticket will be updated with the notes of that discussion along side action items.

**Comment by kavilla** [comment]
Overall felt pretty successful and thanks for the help!

For 1.3.1, I was able to address the flakiness in tests presented by most plugins besides alerting and observability. Will need to follow-up with these tests. The issue with these tests is that they introduce arbitrary wait times for when they expect results to be ready which has no guarantee and against cypress best practices. The follow-up would be to intercept the requests that these plugins make and wait for the response before continuing the test as per best practices. These should address the flakiness and also speed up the test run.

One thing to comment is that we were told to create release notes for 1.3.1 OpenSearch Dashboards, but 1.3.1 OpenSearch did not https://github.com/opensearch-project/OpenSearch/tree/main/release-notes. Was this an oversight? Or purposeful. I think both should be matching either no release-notes or include release-notes.

**Comment by bbarani** [comment]
Closing this retro issue for 1.3.1 release. Feel free to add any additional comments to this issue as needed.
