### ISSUE TITLE
Automate integ test using RPM bundle.

### ISSUE THREAD

**Issue by zelinh** [opensearch-project/opensearch-build#1951]
Currently our integ tests are working only for using tarball distribution. We now have workflow to generate RPM bundle. We need incorporate the automated integ tests for RPM bundle.

**Comment by peterzhuamazon** [comment]
Re-open as we add the functionality but not added to distribution pipeline yet.

**Comment by peterzhuamazon** [comment]
Close this from our side as dashboards is handled by @tianleh team.
