### ISSUE TITLE
Create InputManifest for OpenSearch 1.1 build

### ISSUE THREAD

**Issue by mch2** [opensearch-project/opensearch-build#196]
Create an InputManifest for the 1.1 bundle build that records all components that should be included.

The manifest should look like the one created for [1.0](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/opensearch-1.0.0.yml) and live next to it in this repo.

**Comment by dblock** [comment]
Do we want to rewrite this and other issues for building other bundled versions as a checklist? For example:

- [ ] create an input manifest for the version, e.g. [link]
- [ ] configure add a job to Jenkins, e.g. [link]
- [ ] setup ...
