### ISSUE TITLE
Publish logstash-input-opensearch plugin to rubygems.org for 1.0.0 version

### ISSUE THREAD

**Issue by naveentatikonda** [opensearch-project/opensearch-build#1964]
git repo - https://github.com/opensearch-project/logstash-input-opensearch
Est Date - 25th April, 2022

**Comment by bbarani** [comment]
Closing this issue as we have already released logstash input plugin 1.0 on [RubyGems](https://rubygems.org/gems/logstash-input-opensearch/versions/1.0.0).
