### ISSUE TITLE
[Enhancement] Make input manifest combine version+qualifier like build/bundle manifest or vise versa

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#1965]
As of now, 2.0.0 input_manifest separate the version and qualifier field.

```
version: 2.0.0
qualifier: alpha1
```

After build and assemble, the build_manifest and bundle_manifest combined this two fields into one.
```
version: 2.0.0-alpha1
```

This is not only confusing but also causing a lot of hard coding.

For example, rpm does not support `-` as stated in this [issue comment](https://github.com/opensearch-project/opensearch-build/issues/1549#issuecomment-1098429590). In order to separate version and qualifier with `.` instead of `-`, we want to directly call `build.version` and `build.qualifier`, but now we have to do `version.replace('-', '.')` which is not clean and is assuming the incoming `version=2.0.0-alpha1`.

I would like a consistent solution here, either separate the field for all or combine the field for all.

Thanks.

**Comment by dblock** [comment]
This would require changing how OpenSearch and plug-in gradle builds receive the build qualifier (remove support for it, include the qualifier as part of the version). It’s a good idea, but a lot of work.
