### ISSUE TITLE
[META] CICD readiness for 1.1 release

### ISSUE THREAD

**Issue by setiah** [opensearch-project/opensearch-build#201]
The tracks all tasks, including integrations, for making the CICD pipeline ready for OpenSearch 1.1 release.

**Comment by minalsha** [comment]
Let's document what all is completed for 1.1 release and what all is pending with level of effort(in terms of days), ECDs, dependencies.

**Comment by dblock** [comment]
Maybe this should be a project instead?

**Comment by dblock** [comment]
Project is https://github.com/opensearch-project/opensearch-build/projects/3
