### ISSUE TITLE
Add unit test for jenkinsfile

### ISSUE THREAD

**Issue by tianleh** [opensearch-project/opensearch-build#2023]
### Is your feature request related to a problem? Please describe

Need a mechanism to add unit tests for jenkinsfile besides the Groovy files https://github.com/opensearch-project/opensearch-build/tree/main/tests/jenkins

### Describe the solution you'd like

write and update unit test same as the Groovy file changes

**Comment by prudhvigodithi** [comment]
[Triage] We have all the required details, we will design and implement the testing framework to add tests to Jenkinsfiles.

**Comment by prudhvigodithi** [comment]
It's better to add tests at per Jenkins library instead of Jenkinsfiles, ideally for the exact library functionality.
Closing this issue, please feel free to reopen @tianleh
