### ISSUE TITLE
[Bug] How to label and track issues for the 2.0.0 GA release 

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#2026]
In the current 2.0.0 RC release https://github.com/opensearch-project/opensearch-build/issues/1624 we created the labels as `2.0.0` in all repositories.  As we are past code fresh, we are seeing non-critical issues that are not getting into the current release.  How can we tag/track these issues/PRs for the 2.0.0 GA release?

**Comment by peternied** [comment]
In security we added another tag `v2.0.0-GeneralAvailability` to track this issues as an ad-hoc process

**Comment by dblock** [comment]
Post RC1 it's just v2.0.0, no?

**Comment by peternied** [comment]
Until RC1 has shipped, we don't have a clear label for these issues.  Makes it harder to drive queries to zero
