### ISSUE TITLE
[BUG][2.0.0]PA not running in RPM distribution

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#2043]
The error log:

```
ERROR StatusLogger Reconfiguration failed: No configuration found for '659e0bfd' at 'null' in 'null'
01:21:06.820 [main] ERROR org.opensearch.performanceanalyzer.config.PluginSettings - Loading config file /usr/share/opensearch/config/opensearch-performance-analyzer/performance-analyzer.properties failed with error: org.opensearch.performanceanalyzer.config.ConfigFileException: java.io.FileNotFoundException: /usr/share/opensearch/config/opensearch-performance-analyzer/performance-analyzer.properties (No such file or directory). Disabling plugin.
01:21:06.823 [main] ERROR org.opensearch.performanceanalyzer.PerformanceAnalyzerApp - Performance analyzer app stopped due to invalid config status.
```

This error is caused by the change of config directory in RPM.
Not in `$OPENSEARCH_HOME/config` anymore, but in `/etc/opensearch`.

How to resolve:
1. We can have `bin/opensearch-performance-analyzer/performance-analyzer-agent-cli` to point to `$OPENSEARCH_PATH_CONF` instead of `$OPENSEARCH_HOME/config`.
2. We can also create a `config` symlink in the rpm pointed to `/etc/opensearch`, the problem with this approach is security demo cert installation script is checking whether `$OPENSEARCH_HOME/config` exists. If so, install as tar; if not, install as rpm.

I prefer to have 1 as that is the minimum changes as well as changes in `scripts/legacy/tar/linux/opensearch-tar-install.sh` to add `OPENSEARCH_PATH_CONF` values and exports.

Thanks.

**Comment by peterzhuamazon** [comment]
@sruti1312 @CEHENKLE @bbarani

**Comment by bbarani** [comment]
@peterzhuamazon Can we also add automated tests for PA to capture these issues for RPM as well?

**Comment by dblock** [comment]
Is the fix in this repo or PA? Can we please move it to the right repo and assign to an engineer in PA?

**Comment by peterzhuamazon** [comment]
https://github.com/opensearch-project/performance-analyzer-rca/pull/172
https://github.com/opensearch-project/performance-analyzer/pull/200
