### ISSUE TITLE
Generate statistics on various contributor activities across product releases

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#2070]
### Is your feature request related to a problem? Please describe

I would like to know how well we're doing with engaging the open-source community for OpenSearch, release after release. 

### Describe the solution you'd like

A way to generate/visualize answers to the following questions:

1. How many non-Amazonians/Amazonians contributed to OpenSearch 2.0?
2. How many non-Amazonians/Amazonians contributed to OpenSearch clients this year?
2. How many new features were introduced by non-Amazonians in OpenSearch 2.0?
3. How many bug fixes were made in OpenSearch 2.0.
4. What is the % of contributions that are maintenance, i.e. aren't features or bug fixes?

### Additional context

I have been [looking](https://github.com/dblock/opensearch-project-tools/blob/master/bin/list-non-aws-contrbutions.rb) at various numbers of contributors to opensearch-project/OpenSearch week-over-week, but I have many more questions release-after-release.

**Comment by prudhvigodithi** [comment]
[Triage] @CEHENKLE will be looking into this issue.

**Comment by bbarani** [comment]
@prudhvigodithi Lets track this as part of the metrics initiative.

**Comment by prudhvigodithi** [comment]
> @prudhvigodithi Lets track this as part of the metrics initiative.

Sure @bbarani this issue best suits the metrics initiative.

**Comment by bbarani** [comment]
Closing this issue as we have https://github.com/opensearch-project/project-tools repo to understand the metrics.
