### ISSUE TITLE
[Enhancement] Allow component only build in distribution pipeline

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#2091]
As of now, our distribution build workflow for OS and OSD will build everything put in the manifest file.
This cause some issue and dependency problems when you only want to build one component, such as core, so plugin owners can consume the latest Maven and pass their checks on PR.

Example:
* 2.0.0 GA requires all plugins to remove `rc1` to build successfully.
* Plugins cannot remove `rc1` because their PR checks fail due to no `2.0.0 GA` maven/docker.
* But we cannot build 2.0.0 GA due to plugin still have `rc1` qualifier.
* The only solution to this is to only build 2.0.0 GA core, which current pipeline does not support, but python code already support with `--component` parameter.

Thanks.

**Comment by dblock** [comment]
I think you're proposing to create a new pipeline for OpenSearch-min that can be run on demand.

**Comment by peterzhuamazon** [comment]
We dont need to create a new pipeline, just add one param in the existing pipeline is enough.

**Comment by peterzhuamazon** [comment]
This confirms to push 2.0.0-SNAPSHOT with @prudhvigodithi.
```
2.0.0-SNAPSHOT/ 	Tue May 10 19:31:29 UTC 2022 	
```
