### ISSUE TITLE
provide a smaller Docker image

### ISSUE THREAD

**Issue by aviau** [opensearch-project/opensearch-build#2097]
It would be great if OpenSearch provided a smaller docker image than the one currently in the Docker Hub. (https://hub.docker.com/r/opensearchproject/opensearch/tags)

Other databases such as postgres provide alpine-based images that are much smaller.

It may not be possible due to OpenSearch's dependencies, in that case feel free to close this bug.

Cheers,

**Comment by dblock** [comment]
Moving this to opensearch-build.

**Comment by dblock** [comment]
@aviau Do you have any examples where the size of the image is a problem?

**Comment by aviau** [comment]
It isn't a major problem, just a QoL improvement. In an effort to speedup the initial setup of our dev environment we switched to small images for all of our dependencies, and it was a welcome change amongst our devs.

**Comment by aviau** [comment]
Nice! Good job!
