### ISSUE TITLE
Build System CI - Update to tag "latest" builds

### ISSUE THREAD

**Issue by mch2** [opensearch-project/opensearch-build#210]
Right now we are dumping artifacts into S3 with a build-id in the path.  After a nightly build completes we should be tagging that build id as "latest" for /builds and /bundles.

**Comment by bbarani** [comment]
@mch2 How would you differentiate latest builds vs last known good builds?

**Comment by peternied** [comment]
Closing in favor of https://github.com/opensearch-project/opensearch-build/issues/1492 which is in active development
