### ISSUE TITLE
Add prometheus exporter plugin to OpenSearch

### ISSUE THREAD

**Issue by sastorsl** [opensearch-project/opensearch-build#2109]
### Is your feature request related to a problem? Please describe

Getting metrics through prometheus gives a great benefint.
Pr now one either has to providison ones own docker image or install in the plugin in one way or another.

### Describe the solution you'd like

Add the prometheus exporter plugin to the main docker image, or as an option in a separate official docker image for OpenSearch.

### Describe alternatives you've considered

A separate install would require extra steps.
Building your own docker image would require a separate process for a use case which would benefit many. It can be done, but it's better if it came through the official image.

### Additional context

N/A

**Comment by bbarani** [comment]
It looks like this has been already added to community project page - https://opensearch.org/community_projects 

@dblock @CEHENKLE What are you thoughts of adding it to our Docker image? I prefer it to be part of community project rather than baking it to Docker image to avoid tight coupling during releases but need your inputs as well.

**Comment by dblock** [comment]
It would be the first plugin that we include that is not in opensearch-project (https://github.com/aiven/prometheus-exporter-plugin-for-opensearch). Adding anything to the official distribution and docker image would mean testing it exporter as part of the distribution, reviewing all its code changes every time for any security issues and such, and asking plugin maintainers to work in lock-step with the distribution team. I am not sure we can be asking of the Aiven team to take on this overhead, and I doubt they would be interested as it would tie their release and make it harder to move faster. So I would not recommend doing this.

**Comment by bbarani** [comment]
@dblock thats exactly my concern as well. Its easier to develop and maintain a standalone plugin not pre-installed in the distribution as they have additional flexibility of building, testing and releasing it using an already released stable distribution. It would require a lot of co-ordination and heavy lifting to pre-install it as part of the distribution generation process.

**Comment by bbarani** [comment]
Closing this issue as we are not going to support adding this external plugin to distribution build at this point in time. Please feel free to re-open if anyone thinks otherwise.
