### ISSUE TITLE
Trigger notifications after test run

### ISSUE THREAD

**Issue by setiah** [opensearch-project/opensearch-build#211]
The [test-orchestrator-pipeline](https://github.com/opensearch-project/opensearch-build/blob/main/bundle-workflow/jenkins_workflow/test/orchestrator/Jenkinsfile#L45-L50) has a notify job that is currently no-op. This issue is for adding logic to the job to trigger notifications after a successful/failed test-execute step.

**Comment by peternied** [comment]
This was completed in https://github.com/opensearch-project/opensearch-build/pull/1105
