### ISSUE TITLE
Rebuild snapshot builds without -SNAPSHOT and promote outputs to staging

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#213]
Convert a build_manifest at a url back into an input_manifest where all refs are set to the commit_id from each component.

The flow I am thinking of from CI would be:

1. Invoke build & bundling systems with snapshot qualifier <- snapshot maven artifacts are promoted to a snapshot repo. This is captured in #179. 
2. After tests pass, convert the built build_manifest from step 1 into an input_manifest. This is this item.
3. Re-run the build & bundling steps with the new input_manifest, with the snapshot flag off.
4. Promotes artifacts to a staging repo.

**Comment by dblock** [comment]
I split this off https://github.com/opensearch-project/opensearch-build/issues/179 which focuses on just getting a snapshot build succeeding, which turned out into its own can of worms.

**Comment by dblock** [comment]
@mch2 Do we want to attempt this for 1.0.1 or 1.1?

**Comment by mch2** [comment]
This issue is no longer required.  We will build snapshots and release builds nightly as separate pipelines.
