### ISSUE TITLE
[Renew Key] Upcoming expiration of our current sub public key (expire on 20230512) 

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#2136]
This is a reminder that the new sub public key that we extended in #2040 will expire on 20230512.

We need to take action to extend the key again before that.

Guide: https://github.com/opensearch-project/opensearch-build/issues/2040#issuecomment-1125449385

* Upload the key to the production S3 bucket while work with project-website on it.
* Upload to keyserver: https://github.com/opensearch-project/opensearch-build/issues/2040#issuecomment-1132261924
* Update on https://opensearch.org/verify-signatures.html
* Make sure the key will expire in exactly one year on 20240512.

Thanks.

**Comment by peterzhuamazon** [comment]
Hi,
@bbarani this is for 20230512 expiration which is the extension of our extended key.
Thanks.

**Comment by bbarani** [comment]
@rishabh6788 are we tracking it via current monitoring and alarms?

**Comment by peterzhuamazon** [comment]
We are on the way to replace the new public key with SHA2 hash.
* https://github.com/opensearch-project/opensearch-build/issues/3124#issuecomment-1533752538

**Comment by peterzhuamazon** [comment]
Related website changes: https://github.com/opensearch-project/project-website/issues/1562

**Comment by peterzhuamazon** [comment]
The key is out now to the public:
https://opensearch.org/verify-signatures.html
