### ISSUE TITLE
Release OpenSearch Clients 2.0.0 version

### ISSUE THREAD

**Issue by VachaShah** [opensearch-project/opensearch-build#2140]
### Is your feature request related to a problem? Please describe

Publish version `2.0.0` for below OpenSearch clients:

- `opensearch-java`: https://github.com/opensearch-project/opensearch-java
- `opensearch-py`: https://github.com/opensearch-project/opensearch-py
- `opensearch-ruby`: https://github.com/opensearch-project/opensearch-ruby
- `opensearch-js`: https://github.com/opensearch-project/opensearch-js
- `opensearch-go`: https://github.com/opensearch-project/opensearch-go
- `opensearch-php`: https://github.com/opensearch-project/opensearch-php
- `opensearch-net`: https://github.com/opensearch-project/opensearch-net
- `opensearch-dsl-py`: https://github.com/opensearch-project/opensearch-dsl-py
- `opensearch-rs`: https://github.com/opensearch-project/opensearch-rs

Branch 2.0 will be created for all of the above clients. 

### Describe the solution you'd like

Release the mentioned clients to the respective package managers.

**Comment by bbarani** [comment]
Released the below clients for 2.0 version:
opensearch-py: https://github.com/opensearch-project/opensearch-py
opensearch-ruby: https://github.com/opensearch-project/opensearch-ruby
opensearch-js: https://github.com/opensearch-project/opensearch-js

**Comment by bbarani** [comment]
@VachaShah What is the plan for opensearch-cli?

**Comment by CEHENKLE** [comment]
@vamsi-amazon what are your plans for opensearch-cli?  Thanks!

**Comment by peterzhuamazon** [comment]
We are releasing opensearch-rs 2.0.0 on 2022/06/02:
* https://github.com/opensearch-project/opensearch-rs/issues/51

**Comment by peterzhuamazon** [comment]
We are releasing opensearch-dsl-py 2.0.0 on 2022/06/02:
* https://github.com/opensearch-project/opensearch-dsl-py/issues/50
