### ISSUE TITLE
[BUG] opensearch_node container does not restart on error

### ISSUE THREAD

**Issue by tuotempo** [opensearch-project/opensearch-build#2143]
**Describe the bug**
I am running an opensearch docker container, that sometimes exits with code 0 even if I see errors on logs

**To Reproduce**
I were not able to reproduce it sistematically

**Expected behavior**
If the container exits for an error, it should restart automatically.

**Plugins**
discovery-ec2
opensearch-alerting
opensearch-anomaly-detection
opensearch-asynchronous-search
opensearch-cross-cluster-replication
opensearch-index-management
opensearch-job-scheduler
opensearch-knn
opensearch-observability
opensearch-performance-analyzer
opensearch-reports-scheduler
opensearch-security
opensearch-sql
prometheus-exporter
repository-s3

**Screenshots**

**Host/Environment:**
 - OS: Ubuntu
 - Version 18.04.4 LTS

**Additional context**
here is the output of `docker ps -a --no-trunc`:
```
CONTAINER ID                                                       IMAGE                                           COMMAND                               CREATED        STATUS                         PORTS                 NAMES
9ac96c1a80544e9927bd570499ca69d3a7c44921973c682b670d6884409ff74a   opensearchproject/opensearch:1.2.3              "./opensearch-docker-entrypoint.sh"   3 months ago   Exited (0) 11 minutes ago                            opensearch_node
```
looking at log files, I see there was an out of memory error:
```
java.lang.OutOfMemoryError: Java heap space
[2022-05-09T12:06:33,484][ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [host] fatal error in thread [opensearch[host][scheduler][T#1]], exiting
java.lang.OutOfMemoryError: Java heap space
Killing performance analyzer process 12
OpenSearch exited with code 127
Performance analyzer exited with code 143
```
In order to handle those cases, I have set container policy to restart on-failure, but since the exit code is 0, it remains stopped. 
I suspect the problem can be on [terminateProcesses](https://github.com/opensearch-project/opensearch-build/blob/main/docker/release/config/opensearch/opensearch-docker-entrypoint.sh#L57
) function, but I'm not 100% sure.

Thanks for your support.

**Comment by CEHENKLE** [comment]
Done!

**Comment by bbarani** [comment]
@tuotempo Thanks for submitting the issue. We have made lots of improvements to Docker image post 1.3.0 release. Can you try out the latest version of OpenSearch images (1.3.2 / 2.0) and let us know if you are still facing these issues?

**Comment by bbarani** [comment]
@tuotempo Are you able to validate the fix in the latest version (1.3.3) of docker images?

**Comment by bbarani** [comment]
Closing this issue for now. Please feel free to re-open if required.

**Comment by tuotempo** [comment]
Hello,
I have tested the 1.3.3 version of images, but the behavior is the same. Here is some additional info (if needed):

**Comment by tuotempo** [comment]
Hi @bbarani can you check our response please? We can't reopen this issue with results of our tests
