### ISSUE TITLE
[Enhancement] Run Dashboards integTest in parallel on Jenkins

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#2144]
Hi,

This is a build repo follow up to https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/110.

1. Add scripts / tweaks in FT repo script finder to allow components separation.
2. Python code in build repo able to pass --component properly or add something like --test to specify specific test.
3. Tweak jenkinsfile to consume this changes and run on Jenkins.

- [x] Add support in python code base
- [x] https://github.com/opensearch-project/opensearch-build/issues/3412

**Comment by peterzhuamazon** [comment]
* 20220524: https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/234

**Comment by gaiksaya** [comment]
In order to run integration tests for dashboard plugins, the plugins need to be part of the test manifest https://github.com/opensearch-project/opensearch-build/blob/main/manifests/2.5.0/opensearch-dashboards-2.5.0-test.yml

Right now only functional-test repo is added as one of the component.

One of the approach to go forward is have functional test repo as default and then parse through the manifest to collect all the components and pass each component as `-t <component>` to functional test repo.

**Comment by gaiksaya** [comment]
### Approach:

Clone functional test repo as default and add all plugins as a single component to test manifest

In this approach, functional test repo will be cloned by default based on input manifest (branch). We will add all other components to test manifest as below. The test workflow will iterate over all the components and pass the component name as parameter to functional test repo.
This makes sure we have all the components in test manifest for accountability and single point of truth what tests are run for which component and with what test configuration.

```yaml
---
schema-version: '1.0'
name: OpenSearch Dashboards
ci:
  image:
    name: opensearchstaging/ci-runner:ci-runner-rockylinux8-opensearch-dashboards-integtest-v2
components:
  - name: OpenSearch-Dashboards
    bwc-test:
      test-configs:
        - with-security
        - without-security
  - name: observabilityDashboards
    integ-test:
      test-configs:
        - with-security
        - without-security
  - name: securityDashboards
    integ-test:
      test-configs:
        - with-security
        - without-security
  - name: anomalyDetectionDashboards
     integ-test:
      test-configs:
        - with-security
        - without-security

**Comment by Divyaasm** [comment]
Closed via https://github.com/opensearch-project/opensearch-build/pull/3316 and https://github.com/opensearch-project/opensearch-build/pull/3465
