### ISSUE TITLE
Automate Version Increment process required for each plugin repo.

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/opensearch-build#2152]
### Is your feature request related to a problem? Please describe

Version Increment is a process that needs to be done for all plugin repos, present in manifest file during a specific release.
Example: for `1.3.2` [OpenSearch](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/1.3.2/opensearch-1.3.2.yml) and [OpenSearch Dashboard](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/1.3.2/opensearch-dashboards-1.3.2.yml) components had to get the version (from `1.3.1` to `1.3.2`)
increment done across its repositories.
This is time consuming and manual human effort to go through each repo, check for previous merged PR and then create a version increment PR, allow plugin team to review, followup, update the PR with suggestions and then finally get merged for CI to run.

### Describe the solution you'd like

Have a better process/workflow for each component repo or managed globally, that auto creates version increment PR and adds to the release Issue. Which will save a lot of time for a release engineer and avoids [human errors](https://github.com/opensearch-project/performance-analyzer-rca/pull/189#issuecomment-1146179883).

### Acceptance Criteria
1. Automated workflow that will increment the version for plugin and take care of all other code changes required to pass the CI.
2. PR is merged upon review and ready to use.

**Comment by dblock** [comment]
This is a dup of https://github.com/opensearch-project/opensearch-build/issues/1375
