### ISSUE TITLE
Data Prepper build: Deploy to ECR

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/opensearch-build#2159]
### Is your feature request related to a problem? Please describe

Data Prepper only deploys to DockerHub. Include ECR.

### Describe the solution you'd like

Update the Data Prepper promotion/release build to copy the source container to ECR in addition to DockerHub.

**Comment by prudhvigodithi** [comment]
This can be fixed by adding [copyContainer](https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/data-prepper/release-data-prepper-all-artifacts.jenkinsfile#L80), pointing `destinationRegistry` to public ECR gallery `public.ecr.aws/opensearchproject`
@peterzhuamazon @bbarani
