### ISSUE TITLE
[Bug]: sign-artifacts does not validate access-denied error from input URL.

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/opensearch-build#2167]
### Describe the bug

[sign-artifacts](https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/sign-artifacts/sign-standalone-artifacts.jenkinsfile) code does not validate the user passed in `URLs` input, it just tries to fetch the and save the file from `curl` output.
Sometimes the URL is not accessible
```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>MC5BTJWC2M4J3P6Z</RequestId><HostId>wOwukl4Gh/7Y775yp8L/ceP8JyXK+ZffhmZ5NlICH0Mq5+TlMsVqNQKCczqYtV5El9qobmOrlZk=</HostId></Error>
```
Still it wont fail and attempts to output the above error to a file and proceeds to sign the file, so now the signed file is corrupted.

**Solution:** 
Add some file validation method before proceeding to sign.

Current Behavior:
* Wrong URL, Return Code non-zero, still proceed to sign after downloading.

Expected Behavior:
* Wrong URL, Return Code non-zero, exit the signing and error out.

### To reproduce

Pass an access denied file to the input `URLs` and it proceeds to sign an error message file.

**Comment by zelinh** [comment]
This is a valid issue and we can add the validation for URL for that jenkins workflow.

**Comment by peterzhuamazon** [comment]
We do not need to touch the jenkinsfile just fix the library controlling the downloads.
