### ISSUE TITLE
[Docker] Add support for running OpenSearch containers with an arbitrary user

### ISSUE THREAD

**Issue by mtrop-godaddy** [opensearch-project/opensearch-build#2177]
### Is your feature request related to a problem? Please describe

I'm trying to migrate a few Elasticsearch clusters over to OpenSearch. In the current ES setup, the config and data directories are bind-mounted into the container and are owned by a user that exists on the host system. If I mount these directories into an OpenSearch container then it's unable to write to the data directory due to two issues:

* It's not possible to start the container with an arbitrary user because the `/usr/share/opensearch` directory isn't readable by everyone (there are some other permission related issues as well):

```
$ groupadd -g 12345 testuser
$ useradd -g 12345 -u 12345 testuser -s /usr/sbin/nologin -M
$ sudo docker run -ti -v /etc/passwd:/etc/passwd:ro -v /etc/group:/etc/group:ro -u 12345:0 --rm -e "discovery.type=single-node" opensearchproject/opensearch:2
{"msg":"exec container process `/usr/share/opensearch/./opensearch-docker-entrypoint.sh`: Permission denied","level":"error","time":"2022-06-10T13:51:16.000905528Z"}

$ sudo docker run -ti --rm -e "discovery.type=single-node" opensearchproject/opensearch:2 stat /usr/share/opensearch | grep "Access"
Access: (0700/drwx------)  Uid: ( 1000/opensearch)   Gid: ( 1000/opensearch)
```

* I don't want to make the data directory world-writable on the host system or change the ownership so the owner's UID/GID would match the one that OpenSearch uses within the container.

One of the solutions that I played with is to just set the ownership of the data/config directories so they're owned by the user with UID 1000. This works fine but that user is reserved for something else on the host systems so having Elasticsearch/OpenSearch dirs owned by it is a bit awkward and doesn't seem like good practice so I ideally want to avoid it if possible.

---

Elasticsearch images follow the OpenShift guidelines for example, which allow starting a container with a random UID: https://docs.openshift.com/container-platform/4.10/openshift_images/create-images.html#images-create-guide-openshift_create-images 

> By default, OpenShift Container Platform runs containers using an arbitrarily assigned user ID. This provides additional security against processes escaping the container due to a container engine vulnerability and thereby achieving escalated permissions on the host node.
>
> For an image to support running as an arbitrary user, directories and files that are written to by processes in the image must be owned by the root group and be read/writable by that group. Files to be executed must also have group execute permissions.

Another solution I tried is based on the above guidelines - I can get OpenSearch working by overriding the entrypoint and changing the ownership of directories/files within the container at runtime: 

```
#!/bin/bash

chgrp -R 0 /usr/share/opensearch
chmod -R g=u /usr/share/opensearch

exec chroot --userspec=12345:0 / "/usr/share/opensearch/opensearch-docker-entrypoint.sh" "${@}"
```

### Describe the solution you'd like

Ideally the OpenSearch image would follow the OpenShift guidelines and support starting containers with an arbitrary user: 
* https://docs.openshift.com/container-platform/4.10/openshift_images/create-images.html#images-create-guide-openshift_create-images.

See the `Support arbitrary user ids` section for more details but the main two changes that are needed for this are:

*  Directories and files that are written to by processes in the image must be owned by the `root` group and be read/writable by that group
* Files to be executed must also have group execute permissions.

As the documentation states, adding the following RUN command to the Dockerfile should make the image compliant:

```
RUN chgrp -R 0 /usr/share/opensearch && \
    chmod -R g=u /usr/share/opensearch
```

---

If the OpenShift guidelines were considered in the past and weren't implemented due to a security issue etc. then an alternative implementation that still allows running the container with a random user UID would still be greatly appreciated.

### Describe alternatives you've considered

* Changing the ownership of bind-mounted volumes on the host so they're owned by the `opensearch` user within the container.

* Mounting `/etc/passwd` and `/etc/group` into the container and then changing the ownership of all OpenSearch related directories/files at runtime with a custom entrypoint script. I haven't finished testing these yet but either one these options seems to work fine:

```
# Recursively change the ownership of all files
chown -R testuser:testuser /usr/share/opensearch

# OpenShift inspired solution
chgrp -R 0 /usr/share/opensearch
chmod -R g=u /usr/share/opensearch
```

* Build a new image, based on the upstream OpenSearch image, with modified permissions. This is still something I might play with but I ideally don't want to maintain a separate image if there's a chance this can be addressed in the official one.

**Comment by prudhvigodithi** [comment]
Hey @mtrop-godaddy, thanks for your suggestions and inputs, one other way for your situation is to use `bindfs`, but it has its own caveats, we need to explore this arbitrary user ids to start with `opensearch` user and group with `root` to docker and indirectly to kubernetes as well.

**Comment by peterzhuamazon** [comment]
[Triage] We are still using 1000:1000 as userid:groupid for our docker images.
If needed, users can use root to override ownership of certain folders.

Please feel free to re-open this issue if needed. Closing for now, thanks.
