### ISSUE TITLE
Have additional label for qualifiers instead of just use the major version, 2.0.0 vs 2.0.0-rc1 in github issues and PRs

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#2180]
We need to update the release template so that release manager will remember to specify qualifier information.

**Comment by bbarani** [comment]
I think the mechanism to create (labels)[https://github.com/opensearch-project/opensearch-plugins/blob/main/META.md#create-or-update-labels-in-all-plugin-repos] exist but we need to update the component issue template to tag the issues corresponding to specific release.

**Comment by gaiksaya** [comment]
Labels are automatically created now when we auto-increment PRs are created. Closing this issue.
