### ISSUE TITLE
Make sure OSD sanity test is having 1+ more days of testing time than OS sanity test during releases

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#2181]
The release template should separate the timing of sanity test to two sections so OSD sanity testing is having a later deadline than OS sanity testing, due to OSD is relying on OS to run.

**Comment by bbarani** [comment]
Closing this issue as we dont have plans to separate OpenSearch and OpenSearch dashboard releases at this point in time. Feel free to re-open if needed.
