### ISSUE TITLE
[Campaign Placeholder] Build 3.0.0 Release in distribution with all plugin owners switch their main branch to test 3.0.0

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#2182]
This is to build 3.0.0 early and run a campaign alongside plugin owners to fail-fast the breaking changes in main branches.
This include both OS and OSD plugins.

As of now OS core on main is already 3.0.0, same as OSD.

### This is a placeholder of a campaign that will start soon.

**Comment by bbarani** [comment]
The campaign for branch alignment is tracked as part of. https://github.com/opensearch-project/opensearch-build/issues/1375

**Comment by bbarani** [comment]
Closing this issue as we have have all aligned on the branching strategy as part of https://github.com/opensearch-project/opensearch-build/issues/1375 and the pending tasks will be followed in https://github.com/opensearch-project/opensearch-plugins/issues/142
