### ISSUE TITLE
[Campaign Placeholder] Ask Plugin Owner to adopt the IntegTest docker image used in Jenkins to improve consitencies

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#2184]
### This is the placeholder of a campaign

We want to ask the plugin owner to start testing integTest on their local through the use of docker image from Jenkins.

In this way, plugin owner can be confident that their local coding and testing would have the same results compare to Jenkins.

**Comment by gaiksaya** [comment]
Closing in favor of https://github.com/opensearch-project/opensearch-build/issues/3966
