### ISSUE TITLE
[Campaign Placeholder] Consistent and standardize developing env and repo folder structure for all BE and FE plugins

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#2185]
### This is a placeholder of a campaign

As of now not all the plugins are following the same structure in folder directories, or content of the build system.
This cause discrepancies, and makes it harder to debug by developers outside of the specific plugin team.

We want to formalize and unify the structure of the plugins so they all follow the same standards.

**Comment by dblock** [comment]
For native plugins we have https://github.com/opensearch-project/opensearch-plugin-template-java as a reference for the latest and greatest. Personally I am not in support of spending a lot of time standardizing every existing plugin's structure to match that, but I think it's a good idea to drive specific campaigns to address lack of common patterns. I would close this and open specific ones.

**Comment by bbarani** [comment]
Closing this as redundant issue of https://github.com/opensearch-project/opensearch-build/issues/2188
