### ISSUE TITLE
Setup code coverage for OpenSearch repo

### ISSUE THREAD

**Issue by dreamer-89** [opensearch-project/opensearch-build#2193]
### Is your feature request related to a problem? Please describe

Setup code coverage for OpenSearch repo. 

### Describe the solution you'd like

As part of this issue, we need to 
1. Update existing gradle check script to have ` -Dtests.coverage=true` to generate report on CI server. This step generates the report in .xml format under `build/codeCoverageReport` directory.
2. Provide mechanism to download/refer generated coverage.xml file on GHA action. This action uploads coverage file on CodeCov server. 

Documentation on OpenSearch: https://github.com/opensearch-project/OpenSearch/blob/main/TESTING.md#test-coverage-analysis

Issues on OpenSearch: 
1. https://github.com/opensearch-project/OpenSearch/issues/1320
2. https://github.com/opensearch-project/OpenSearch/issues/850

**Comment by gaiksaya** [comment]
Looks like @peterzhuamazon is working on end to end JenkinsFile for gradle check.
@peterzhuamazon  can you please update this issue?
Thanks!

**Comment by dreamer-89** [comment]
@gaiksaya : Thanks for providing the update. Can you please elaborate more on task @peterzhuamazon is working upon. I would like to know more how is it related to the ask on this issue.

**Comment by dreamer-89** [comment]
Discussed the ask from infra team with @bbarani. Infra team is currently working on public jenkins migration and will help with this issue post existing gradle check migration to public jenkins. 

CC @anasalkouz

**Comment by peterzhuamazon** [comment]
Since we have completed the migration of gradle check in #851 coverage is on the table now.
Will start now.

**Comment by peterzhuamazon** [comment]
PR lists:

20220628:
* https://github.com/opensearch-project/opensearch-build/pull/2279

**Comment by peterzhuamazon** [comment]
The coverage results are published to codecov, tho it is not showing the analysis correctly.
Need to sync up with @dreamer-89 on what is the next step.
Seems like the xml itself is the issue.

Thanks.

**Comment by peterzhuamazon** [comment]
It shows:
https://github.com/opensearch-project/OpenSearch/pull/3791#issuecomment-1176829987

**Comment by peterzhuamazon** [comment]
Codecov now shows:
https://app.codecov.io/gh/opensearch-project/OpenSearch

**Comment by peterzhuamazon** [comment]
This task is completed for now close the issue.
