### ISSUE TITLE
Enhance the rpm validation workflow with certification validation

### ISSUE THREAD

**Issue by zelinh** [opensearch-project/opensearch-build#2197]
### Is your feature request related to a problem? Please describe

Enhance the rpm validation workflow with certification validation. 
After we add rpm package signing, we will need certain validation for the signature after the distribution build workflow.

### Describe the solution you'd like

Add the certification validation for rpm package when running `rpm-validation` workflow.

**Comment by peterzhuamazon** [comment]
20220615:
* https://github.com/opensearch-project/opensearch-build/pull/2198

**Comment by peterzhuamazon** [comment]
* https://github.com/opensearch-project/opensearch-build/pull/2199

**Comment by peterzhuamazon** [comment]
* https://github.com/opensearch-project/opensearch-build/pull/2201

**Comment by peterzhuamazon** [comment]
This issue has been resolved now.
