### ISSUE TITLE
Pricing for Amazon OpenSearch Service subscription filter

### ISSUE THREAD

**Issue by alejodocmar** [opensearch-project/opensearch-build#2203]
I am an engineer in the AWS CodeGuruReviewer team. We are looking into pushing our logs from multiple components to an elastic search cluster and then query the logs using Kibana. We are considering following options:

-  Using LogStash to push logs from components to Elastic search
-  Using Firehose to push logs to Elastic search
-  Push logs to an S3 bucket and have a lambda listen to the S3 events and add logs to Elastic search

Can you please help us understanding the cost difference between these options. Also, I am having a hard time finding the pricing for "Amazon OpenSearch Service subscription filter" feature. Can you please point me to the pricing page for this feature.

**Comment by bbarani** [comment]
Hi @alejodocmar, we support the opensource version of OpenSearch and not the OpenSearch service hosted in AWS. Please reach out to AWS support team to understand the pricing and features.
