### ISSUE TITLE
Move all AWS account numbers, bucket names and other sensitive data to secrets

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/opensearch-build#2220]
### Is your feature request related to a problem? Please describe

With jenkins going public, we observed that few variables which should be secrets are rather being stored and used as environment variables.
From security perspective, it is better if we move all those to credential store (AWS secrets manager) and use it as secrets rather than exposed as env variables.

Few of them are as follow:

- ARTIFACT_BUCKET_NAME
- ARTIFACT_PRODUCTION_BUCKET_NAME
- SIGN_ASM_ACCOUNT, SIGN_ASM_KEYID, SIGN_ASM_REGION, SIGN_ASM_ROLE (can go as one secret) see [example](https://github.com/opensearch-project/opensearch-build/pull/2156/files#diff-63b9bb4025ab21358c7d296b6204b847ecfffac44b6b249a2363824b30c61b1fR31-R38)
- SIGNER_CLIENT_EXTERNAL_ID, SIGNER_CLIENT_ROLE, SIGNER_CLIENT_SIGNED_BUCKET, SIGNER_CLIENT_UNSIGNED_BUCKET (can go as one secret) See [example](https://github.com/opensearch-project/opensearch-build/pull/2156/files#diff-63b9bb4025ab21358c7d296b6204b847ecfffac44b6b249a2363824b30c61b1fR31-R38)
- SONATYPE_STAGING_PROFILE_ID
- AWS_ACCOUNT_ARTIFACT
- AWS_ACCOUNT_PUBLIC
- AWS_ACCOUNT_TESTING

### Describe the solution you'd like

Move them to AWS secrets manager

**Comment by bbarani** [comment]
@gaiksaya Can we close this issue?

**Comment by gaiksaya** [comment]
Not yet! Still yet to go through jenkinsFiles to see any ad-hoc environment variables usage.
