### ISSUE TITLE
Gradle Cache causing build failures for Security-plugin

### ISSUE THREAD

**Issue by DarshitChanpura** [opensearch-project/opensearch-build#2256]
Gradle cache cause [build failure](https://github.com/opensearch-project/security/runs/7034067513?check_suite_focus=true#step:4:55) for main CI pipelines.

**Expected Behavior**
Should work without issues.

**Related Issues**
https://github.com/opensearch-project/OpenSearch/issues/3663

Should investigate further on why did this happen.

*Temporary solution* 
Removing the CI step to restore the artifacts from gradle cache.

**Comment by gaiksaya** [comment]
Hi @DarshitChanpura , is this issue similar to what I noted down here: https://github.com/opensearch-project/opensearch-build/issues/2257#issuecomment-1165854605

**Comment by tlfeng** [comment]
In additon, the build failure you shown is actually related to the issue https://github.com/opensearch-project/OpenSearch/issues/3663 😉

**Comment by DarshitChanpura** [comment]
Okay... in that case I will close this issue @gaiksaya.

Thank you @tlfeng for pointing the correct issue!
