### ISSUE TITLE
Release OpenSearch Ruby Client 2.0.1 version

### ISSUE THREAD

**Issue by VachaShah** [opensearch-project/opensearch-build#2276]
### Is your feature request related to a problem? Please describe

Publish version 2.0.1 for `opensearch-ruby` client: https://github.com/opensearch-project/opensearch-ruby

### Describe the solution you'd like

Release the mentioned clients to the respective package managers.

**Comment by bbarani** [comment]
@VachaShah Is the code ready to be released? @peterzhuamazon Can we target June 30 2022 if the code is ready?

**Comment by VachaShah** [comment]
Yes the code is ready.

**Comment by peterzhuamazon** [comment]
We have planned to release this on 2022/06/30 2PR with @VachaShah.
Thanks.

**Comment by peterzhuamazon** [comment]
Branch: https://github.com/opensearch-project/opensearch-ruby/tree/2.0

**Comment by peterzhuamazon** [comment]
https://rubygems.org/gems/opensearch-ruby/versions/2.0.1
https://rubygems.org/gems/opensearch-api/versions/2.0.1

**Comment by peterzhuamazon** [comment]
https://github.com/opensearch-project/opensearch-ruby/releases/tag/v2.0.1

**Comment by peterzhuamazon** [comment]
Hi All,

We just shipped OpenSearch-ruby client for OpenSearch in version 2.0.1:
https://rubygems.org/gems/opensearch-ruby/versions/2.0.1
https://rubygems.org/gems/opensearch-api/versions/2.0.1

@VachaShah 2PR release.

Thanks.
