### ISSUE TITLE
Add signature verification to windows signing workflow

### ISSUE THREAD

**Issue by zelinh** [opensearch-project/opensearch-build#2290]
### Is your feature request related to a problem? Please describe

Coming from https://github.com/opensearch-project/opensearch-build/pull/2156#pullrequestreview-1025505369.

We should add windows signature verification from command line. Right now our signing workflow has functionality to sign the windows distribution but it doesn't have method to verify the signature. We can only validate the signature manually for now. 

### Describe the solution you'd like

Acceptance criteria: python [windows signer](https://github.com/opensearch-project/opensearch-build/blob/main/src/sign_workflow/signer_windows.py) has built in method to verify the signature like what we had for PGP signer. 
https://github.com/opensearch-project/opensearch-build/blob/700c80d60b463a8ed41f09d562709afb9d0a55f0/src/sign_workflow/signer_pgp.py#L49-L51

### Acceptance Criteria 

- This should Support all windows artifacts and validate all types of supported windows signatures.
- Integrate the windows artifact validation with validation workflow.

**Comment by prudhvigodithi** [comment]
[Triaged] This is a valid issue, the solution should be able to verify both windows and nuget packages.

**Comment by zelinh** [comment]
> @zelinh Can we also expand this story to add signature validation to TAR artifacts as well?

We actually have GPG signature verification for tarball artifacts immediately after we sign it which implemented here.
https://github.com/opensearch-project/opensearch-build/blob/356b2a2397795065a818fe32224fcac82c54eca7/src/sign_workflow/signer_pgp.py#L49-L51
For windows verification, it's quite different so we don't have it for now.

**Comment by bbarani** [comment]
Lets make sure to add validation for all Windows distribution types that we are planning to support (i.e. .exe, .zip, .msi, .msix etc..)

**Comment by gaiksaya** [comment]
The above PR adds the verification step using `osslsigncode` tool. The tool is currently installed only on release clients docker image. We need to install tool on other docker images if required. Currently windows signer is not used by distribution.
