### ISSUE TITLE
Product-ionize 1.1

### ISSUE THREAD

**Issue by minalsha** [opensearch-project/opensearch-build#231]
Document all issues that need to be addressed to productionize 1.1. Please note that this is a meta issue capturing all the sub issues needed. 

1. On Test side:

- [ ] Orchestration framework
- [ ] Integration Testing
- [ ] BWC Testing
- [ ] [Performance Testing](https://github.com/opensearch-project/opensearch-build/issues/126)

**Comment by dblock** [comment]
Closing this in favor of https://github.com/opensearch-project/opensearch-build/issues/348
