### ISSUE TITLE
[META] Add BWC tests to `bwc_test.py`

### ISSUE THREAD

**Issue by VachaShah** [opensearch-project/opensearch-build#232]
Plugin BWC tests are introduced for AD: https://github.com/opensearch-project/anomaly-detection/pull/158. Add support to wire these tests in [`test.py`](https://github.com/opensearch-project/opensearch-build/blob/main/bundle-workflow/python/test.py) similar to [integration tests](https://github.com/opensearch-project/opensearch-build/blob/main/bundle-workflow/python/test_workflow/integ_test_suite.py).

Tasks:

P0
- [x] #275
- [x] #296
- [x] #276
- [ ] #572
- [ ] #535
- [ ] #277
- [ ] #278

P1
- [ ] Add support to parallelize multiple runs https://github.com/opensearch-project/opensearch-build/issues/243

**Comment by gaiksaya** [comment]
[Triage] We will revisit the design when someone starts looking into BWC testing.
closing this for now, We will reopen this again later if required.
