### ISSUE TITLE
[Enhancement] Provide commit id information for each repo before distribution build starts

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#2325]
[Enhancement] Provide commit id information for each repo before distribution build starts.

Return a link to the yml file with all the commit-ids of repos from the input manifest file.

**Comment by bbarani** [comment]
@peterzhuamazon Do you have any updates on this issue? @bshien would need this data soon for his dashboard effort.

**Comment by peterzhuamazon** [comment]
@bbarani I will work on it next week.
Thanks.
