### ISSUE TITLE
New plugins geospatial, dashboard-maps need to be added to  2.2 release

### ISSUE THREAD

**Issue by vamshin** [opensearch-project/opensearch-build#2346]
### Is your feature request related to a problem? Please describe

We are adding two new plugins 
- geospatial (backend): https://github.com/opensearch-project/geospatial
- dashboard-maps(frontend): https://github.com/opensearch-project/dashboards-maps

### Describe the solution you'd like

These plugins will be used for building new Geo features. For the 2.2 release, we are launching [custom geojson](https://github.com/opensearch-project/geospatial/issues/122) feature. Infra teams help needed to consider these plugins in release process from 2.2 release onwards.

**Comment by dblock** [comment]
Please PR into the manifest!

**Comment by bbarani** [comment]
@peterzhuamazon Can you add the current state of the on-boarding process for these plugins here?

**Comment by peterzhuamazon** [comment]
We just approved multiple PRs:
https://github.com/opensearch-project/geospatial/pull/119
https://github.com/opensearch-project/opensearch-build/pull/2411
https://github.com/opensearch-project/opensearch-build/pull/2418
https://github.com/opensearch-project/opensearch-build/pull/2419
https://github.com/opensearch-project/dashboards-maps/pull/27
https://github.com/opensearch-project/opensearch-dashboards-functional-test/commit/b4a1f7a1cba7514eccb91a1cc5df807de5d214de

It is currently on both manifests will check results tomorrow.

Thanks.

**Comment by bbarani** [comment]
Closing this issue as we have releases the plugins in 2.2.0 version.
