### ISSUE TITLE
Release Ruby client versions for 1.x and 2.x lines

### ISSUE THREAD

**Issue by VachaShah** [opensearch-project/opensearch-build#2360]
Release ruby client patch versions for Faraday 2 support as requested in https://github.com/opensearch-project/opensearch-ruby/issues/91.

**Comment by peterzhuamazon** [comment]
We are releasing these two ruby client version on 2022/07/25 12:00 PM PST with @VachaShah @peterzhuamazon.
`2.0.3 and 1.0.1`

**Comment by peterzhuamazon** [comment]
We have an issue with ruby version as our current setup contains ruby 2.4.0, while faraday requires 2.6+ in the latest changes of ruby client.
```
ERROR:  Error installing dist/opensearch-transport-1.0.1.gem:
	The last version of faraday (>= 1.0, < 3) to support your Ruby & RubyGems was 1.10.0. Try installing it with `gem install faraday -v 1.10.0` and then running the current command again
	faraday requires Ruby version >= 2.6. The current ruby version is 2.4.0.0.
```

@VachaShah will open an issue on this and we would update our images to use a higher version specified by @VachaShah .
https://github.com/opensearch-project/opensearch-build/blob/main/docker/ci/dockerfiles/current/build.centos7.opensearch.x64.arm64.dockerfile#L72

**Comment by BrianHawley** [comment]
Faraday 2 requires Ruby 2.6. Faraday 1 works with Ruby 2.4. The new opensearch-transport gem supports Faraday 1, so you should be able to use Faraday 1 in your container if you want to use Ruby 2.4.

**Comment by VachaShah** [comment]
@BrianHawley Thank you for pointing this out! The error is coming for Faraday versions from the [script](https://github.com/opensearch-project/opensearch-build/blob/main/docker/ci/dockerfiles/current/build.centos7.opensearch.x64.arm64.dockerfile#L72) and the script uses Ruby 2.4 for releasing the newer 1.x and 2.x versions with Faraday changes. Do you have suggestions on how we can fix this error?

**Comment by peterzhuamazon** [comment]
> @VachaShah I saw that command when it was posted before:
> 
> ```dockerfile
> RUN . /etc/profile.d/rvm.sh && rvm install 2.4.0 && rvm --default use 2.4.0 && yum install -y rpm-build createrepo && yum clean all
> ```
> 
> The problem is that command doesn't install any gems at all except for the ones that rvm does (gem-wrappers, rubygems-bundler, rake, rvm, and bundler) - not even Ruby default gems in that version - or even run Ruby with any opensearch stuff. The only thing I don't understand is that leading `.`, but from context it looks like a sh source include command.
> 
> Now, it's possible that the `centos:7` image referenced isn't the one from docker, or has other files mapped into it from the outside using `docker` command line arguments or such, and one of those files is `default.gems`, and it's that file which references "dist/opensearch-transport-1.0.1.gem". The code to create such a file or map that directory isn't in that dockerfile, so it doesn't help with diagnosing the error. Nonetheless, that is one possibility for how to generate that error with `rvm install 2.4.0`; a possibility that I haven't verified myself.
> 
> Later on, this command installs a gem, though it's an unrelated gem that doesn't depend on the opensearch or faraday stuff:
> 
> ```dockerfile
> RUN gem install fpm -v 1.14.2
> ```
> 
> I don't even see anything in that file which copies the opensearch files into the container or otherwise references them. That means that the actual command to install the gems is probably in another file, as is the command that generates that error. So if we're to understand the error, we need to know which command in particular, in which file, raised it.
> 
> Given that this dockerfile doesn't even seem to copy the opensearch gemspec files over, the error is probably raised from a command in a later dockerfile, or some script commands run in the container after it's built.
> 
> As for how a gem install could generate that error, it might be an old rubygems version since those have known bugs. A call to `gem update --system` before the gem install commands might get rubygems to consider the Ruby version when picking a gem to install. That's why I'm curious about where the actual gem install command is, so we can know where to put workarounds like that.

Hi @BrianHawley @VachaShah 

1. The reference line is not a script we use to install gem it is part of the docker file, the `.` leading up is the old way of `source` in bourne shell.
2. The actual installation of the gem is here: https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/opensearch-ruby/Jenkinsfile#L37-L46
3. The installation is merely doing a test run installation before sending it to S3.

The workflow is outdated already that is why I was initially proposing to @VachaShah to do it manually.

I dont have anything against upgrading to 2.6, plus we already did that yesterday in the image push.

I would say just run the workflow again with new image and that is it.

The reason we use 2.4 to start with is because we only need 2.4 for fpm installation. Remember this is not a image for ruby client only, this is an image for opensearch build, which needs other tools after all.

Thanks.

**Comment by BrianHawley** [comment]
@peterzhuamazon I'm just trying to understand the issue to prevent future issues like that going forward :)

Based on that code, it looks like it's an issue with the default rubygems version that rvm installs with Ruby 2.5 or earlier where `gem install` doesn't do a good enough job of considering the Ruby version when picking a gem version to install. IIRC that bug may affect `bundle install` as well. If you call this code after installing Ruby, it will solve that kind of issue:
```
gem update --system
```
If you want to be more paranoid, you can specify a rubygems version in that command.

Or, you could just upgrade Ruby to at least 2.6, if fpm works with that :)

**Comment by dblock** [comment]
Ruby 2.6 is EOL March 31, 2022. Time to upgrade to 3.x.

**Comment by peterzhuamazon** [comment]
1.0.1: https://build.ci.opensearch.org/job/opensearch-ruby-build-sign-upload/5/console
2.0.3: https://build.ci.opensearch.org/job/opensearch-ruby-build-sign-upload/6/console

**Comment by peterzhuamazon** [comment]
> Ruby 2.6 is EOL March 31, 2022. Time to upgrade to 3.x.

Seems like the case upon checking: https://endoflife.date/ruby

@VachaShah let us update the dependencies in opensearch-ruby repo, then you can send an issue to opensearch-build so we can update these 3 images with higher version of ruby as in this PR:
* #2365

**Comment by peterzhuamazon** [comment]
Hi All,

We just shipped OpenSearch-ruby client for OpenSearch.

1.x (opensearch-ruby 1.0.1 / opensearch-transport 1.0.1):
https://rubygems.org/gems/opensearch-ruby/versions/1.0.1
https://rubygems.org/gems/opensearch-transport/versions/1.0.1

Thanks.
2.x (opensearch-ruby 2.0.3 / opensearch-transport 2.0.1):
https://rubygems.org/gems/opensearch-ruby/versions/2.0.3
https://rubygems.org/gems/opensearch-transport/versions/2.0.1

**Comment by BrianHawley** [comment]
> > Ruby 2.6 is EOL March 31, 2022. Time to upgrade to 3.x.
> 
> Seems like the case upon checking: https://endoflife.date/ruby
> 
> @VachaShah let us update the dependencies in opensearch-ruby repo, then you can send an issue to opensearch-build so we can update these 3 images with higher version of ruby as in this PR:

@peterzhuamazon note that only MRI 2.6 and earlier are end-of-life. JRuby 9.2 and 9.3 are still receiving updates. JRuby 9.2's listed Ruby version is 2.5.x, and JRuby 9.3's listed Ruby version is 2.6.x, so those versions of the Ruby language are still in current maintenance. There shouldn't be any hurry to update the Ruby language version limits for the opensearch-ruby gems.

**Comment by peterzhuamazon** [comment]
> @peterzhuamazon I'm just trying to understand the issue to prevent future issues like that going forward :)
> 
> Based on that code, it looks like it's an issue with the default rubygems version that rvm installs with Ruby 2.5 or earlier, where `gem install` doesn't do a good enough job of considering the Ruby version when picking a gem version to install. IIRC that bug may affect `bundle install` as well. If you call this code after installing Ruby, it will solve that kind of issue:
> 
> ```
> gem update --system
> ```
> 
> If you want to be more paranoid, you can specify a rubygems version in that command.
> 
> Or, you could just upgrade Ruby to at least 2.6, if fpm works with that. That seems to fix that issue :)
> 
> In any case, this is a distraction if you've gotten the build system to work. Looking forward to the new gem versions.

Thanks @BrianHawley we eventually upgrade to 2.6 ruby and it runs well.
We didnt update gem in dockerfile because we need to preserve the exact version during the docker creation.

**Comment by peterzhuamazon** [comment]
> > > Ruby 2.6 is EOL March 31, 2022. Time to upgrade to 3.x.
> > 
> > 
> > Seems like the case upon checking: https://endoflife.date/ruby
> > @VachaShah let us update the dependencies in opensearch-ruby repo, then you can send an issue to opensearch-build so we can update these 3 images with higher version of ruby as in this PR:
> 
> @peterzhuamazon note that only MRI 2.6 and earlier are end-of-life. JRuby 9.2 and 9.3 are still receiving updates. JRuby 9.2's listed Ruby version is 2.5.x, and JRuby 9.3's listed Ruby version is 2.6.x, so those versions of the Ruby language are still in current maintenance. There shouldn't be any hurry to update the Ruby language version limits for the opensearch-ruby gems.

Yeah.

TBH we are not very locked by ruby version anyway.
If needed we can go as high as 3.1 version.
The only concern I have is whether 2.x and 3.x have too big of a difference and cause compatibility issues.

Thanks.

**Comment by BrianHawley** [comment]
@peterzhuamazon the opensearch gems CI test against Ruby 2.5 through 3.1 already, and I use them with Ruby 3.1, so there are no compatibility issues running the gems with the latest Ruby versions.
