### ISSUE TITLE
Update the docker images for ruby client release to use a higher Ruby version

### ISSUE THREAD

**Issue by VachaShah** [opensearch-project/opensearch-build#2364]
Coming from https://github.com/opensearch-project/opensearch-build/issues/2360#issuecomment-1194507743, Faraday requires Ruby version >=2.6. As mentioned in the comment, the Ruby version needs to be updated to 2.6

**Comment by BrianHawley** [comment]
Faraday 2 requires Ruby 2.6. Faraday 1 works with Ruby 2.4. The new opensearch-transport gem supports Faraday 1 as well, so you should be able to use Faraday 1 in your container if you want to use Ruby 2.4.

**Comment by BrianHawley** [comment]
Not that I have a problem with you updating Ruby. Just saying, it may not be necessary for this reason.

**Comment by dblock** [comment]
The workflow needs to start specifying which version of Ruby to install.
