### ISSUE TITLE
Cloudfront cache invalidation for min snapshots

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/opensearch-build#2372]
**Problem** : 
Due to large value of cache invalidation time for min [snapshots](https://artifacts.opensearch.org/snapshots/core/opensearch/2.1.0-SNAPSHOT/opensearch-min-2.1.0-SNAPSHOT-linux-x64-latest.tar.gz), the URL returned an old artifact causing the plugin teams's CI to fail. This causes issues if core engine makes changes and new artifact is not available soon.

The delay causes an overall delay in plugin development and integration process

**Action Item** :
We need to lower the cache invalidation time for `/snapshots/*` in order to resolve this.

Acceptance Criteria:
Min snapshots should be available within an interval of 5min (300 seconds) via artifacts.opensearch.org

_Originally posted by @gaiksaya in https://github.com/opensearch-project/opensearch-build/issues/2257#issuecomment-1165854605_

**Comment by peterzhuamazon** [comment]
I have set a second behavior in cloudfront for `/snapshots/*` to 300sec, just like the staging bucket in `ci.opensearch.org`.
