### ISSUE TITLE
OUI release 1.0.0

### ISSUE THREAD

**Issue by AMoo-Miki** [opensearch-project/opensearch-build#2376]
### Is your feature request related to a problem? Please describe

[OUI](https://github.com/opensearch-project/oui) is a fork of the last open source release of EUI to replace it as a dependency of Dashboards and plugins.

### Describe the solution you'd like

We would like to release OUI to NPM as `@opensearch-project/oui`. OUI has inherited some scripts for releasing from EUI but I am not sure how useful they would be to us.

### Describe alternatives you've considered

Manual release: very doable.

**Comment by peterzhuamazon** [comment]
20220802: Release OUI 1.0.0 version with @AMoo-Miki

**Comment by bbarani** [comment]
OpenSearch UI Framework (OUI) 1.0.0 version has been published on NPM. 

npm: https://www.npmjs.com/package/@opensearch-project/oui/v/1.0.0
github: https://github.com/opensearch-project/oui/releases/tag/1.0.0
