### ISSUE TITLE
[BUG] OpenSearch Security Tools Scripts do not have executable permission when unpacked from tarball

### ISSUE THREAD

**Issue by JeffH-AWS** [opensearch-project/opensearch-build#2377]
**Describe the bug**
By default, the contents of `/opensearch-2.1.0/plugins/opensearch-security/tools/` do not have executable permissions after unpacking the archive.

**To Reproduce**
1. Download OpenSearch tarball (`wget https://artifacts.opensearch.org/releases/bundle/opensearch/2.1.0/opensearch-2.1.0-linux-x64.tar.gz`
2. Unpack the archive `tar -xvf opensearch-2.1.0-linux-x64.tar.gz`
3. Change directories `cd opensearch-2.1.0/plugins/opensearch-security/tools`
4. Check permissions (`ll`, `ls -l`, etc.)
5. The scripts only have `rw-r--r--` / `644` permissions.

**Expected behavior**
The scripts in this folder should have `rwxr--r--` / `744` permissions when unpacked from the tar archive.

**Plugins**
N/A - affects fresh/greenfield install

**Screenshots**
```
$ ll
total 44
-rw-r--r-- 1 ec2-user ec2-user   772 Jun 30 21:49 audit_config_migrater.bat
-rw-r--r-- 1 ec2-user ec2-user  1388 Jun 30 21:49 audit_config_migrater.sh
-rw-r--r-- 1 ec2-user ec2-user   777 Jun 30 21:49 hash.bat
-rw-r--r-- 1 ec2-user ec2-user  1376 Jun 30 21:49 hash.sh
-rw-r--r-- 1 ec2-user ec2-user 19776 Jun 30 21:49 install_demo_configuration.sh
-rw-r--r-- 1 ec2-user ec2-user   849 Jun 30 21:49 securityadmin.bat
-rw-r--r-- 1 ec2-user ec2-user  1417 Jun 30 21:49 securityadmin.sh
```

**Host/Environment (please complete the following information):**
 - OS: Amazon Linux 2
 - Version 5.10.130-118.517.amzn2.x86_64

**Additional context**
As a workaround, users must add executable permissions.  i.e., `chmod u+x *sh` or `chmod 744 *sh`

**Comment by prudhvigodithi** [comment]
[Triage] We can follow this 
`Starting with Git 2.9, we can stage a file AND set the flag in one command:
git add --chmod=+x path/to/file`
@bbarani @peterzhuamazon

**Comment by peterzhuamazon** [comment]
I remember we used to have no permission, and we add a manual chmod to docker to solve this.
https://github.com/opensearch-project/opensearch-build/blob/main/docker/release/dockerfiles/opensearch.al2.dockerfile#L42

I think we can add a chmod from the code here:
https://github.com/opensearch-project/opensearch-build/blob/main/src/assemble_workflow/dist.py#L74-L79

Still these are kinda hacky solution.
It would be better if the scripts are 755 from the get go from Security repo.

Hi @cliu123 any insights on why these scripts are not 755 by default?

Thanks.

**Comment by dblock** [comment]
These look executable in the repo, e.g. https://github.com/opensearch-project/security/blob/main/tools/hash.sh so something else loses the flag.

**Comment by bbarani** [comment]
@gaiksaya @peterzhuamazon @prudhvigodithi Can you provide your inputs here?

**Comment by peterzhuamazon** [comment]
Per @dblock point this is more like an issue with the zip generation on security side it seems.

**Comment by gaiksaya** [comment]
One more possibility might be the permissions are changed while building/assembling the distribution. We might need to go through the python code to check that as well.

**Comment by peterzhuamazon** [comment]
> One more possibility might be the permissions are changed while building/assembling the distribution. We might need to go through the python code to check that as well.

Yes we need to check all the steps and see why the permissions are changed in the process.

**Comment by prudhvigodithi** [comment]
So this is what I found, with `git clone` and `./build` that creates the zip (opensearch-security-2.2.0.0-SNAPSHOT.zip) the permissions are still with executable, unzipping also I do see the executable permission, but with `./assemble`  and the final produced `tar` file the permissions are lost.
Its after this
```
Executing "/tmp/tmppngypsfe/opensearch-2.2.0/bin/opensearch-plugin install --batch file:/tmp/tmppngypsfe/opensearch-security-2.2.0.0-SNAPSHOT.zip" in /tmp/tmppngypsfe/opensearch-2.2.0
```

**Comment by peterzhuamazon** [comment]
> So this is what I found, with `git clone` and `./build` that creates the zip (opensearch-security-2.2.0.0-SNAPSHOT.zip) the permissions are still with executable, unzipping also I do see the executable permission, but with `./assemble` and the final produced `tar` file the permissions are lost.
> 
> Its after this
> 
> ```
> Executing "/tmp/tmppngypsfe/opensearch-2.2.0/bin/opensearch-plugin install --batch file:/tmp/tmppngypsfe/opensearch-security-2.2.0.0-SNAPSHOT.zip" in /tmp/tmppngypsfe/opensearch-2.2.0
> ```

Hi @dblock @prudhvigodithi I remember now why I add the code to tweak docker only.
The plugin install command will force 644 permission after installation.

https://github.com/opensearch-project/OpenSearch/blob/ba6dc5d28bb16e49e067b379545c5f20c74945d2/distribution/tools/plugin-cli/src/main/java/org/opensearch/plugins/InstallPluginCommand.java#L211-L212

**Comment by dblock** [comment]
This is https://github.com/opensearch-project/OpenSearch/issues/1220 and is a bug. Someone should pick it up. 

This issue should be closed as a dup of that I think.

**Comment by bbarani** [comment]
Closing this issue in favor of https://github.com/opensearch-project/OpenSearch/issues/1220. Please feel free to re-open this issue if needed.
