### ISSUE TITLE
[Bug]: Manifest CI checks failures 

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#2378]
### Describe the bug

See https://github.com/opensearch-project/opensearch-build/runs/7547753019?check_suite_focus=true

Looks like the wrong version of Java is used.

```
> Task :build-tools:jar
/879A/java/lang/management/PlatformManagedObject.sig: warning: Cannot find annotation method 'value()' in type 'Profile+Annotation': class file for jdk.Profile+Annotation not found
```

### To reproduce

https://github.com/opensearch-project/opensearch-build/runs/7547753019?check_suite_focus=true

### Expected behavior

Manifest CI checks to pass.

**Comment by zelinh** [comment]
We are planning to move our legacy manifests to a separate folder as mentioned in [this issue](https://github.com/opensearch-project/opensearch-build/issues/2332). We are actively working on it and by then this issue should be resolved.

**Comment by dblock** [comment]
@zelinh Should we just delete them? We can always go back in history.

**Comment by zelinh** [comment]
> @zelinh Should we just delete them? We can always go back in history.

I think either deleting them or moving them to a separate legacy folder is pretty much the same. I would lean on keeping them in our repository for some tracking purposes.

**Comment by gaiksaya** [comment]
Fixed in https://github.com/opensearch-project/opensearch-build/pull/2333
