### ISSUE TITLE
Create Perf test page

### ISSUE THREAD

**Issue by bshien** [opensearch-project/opensearch-build#2396]
The Perf test page will be a list and must have in each row:

- architecture
- security enabled?
- instance type
- workload details
- index latency(p50, p90, p99, p100)
- throughput(p0, p50, p100)
- etc.(more info in the json provided)

I first make a call to Jenkins to get the latest 10 performance tests. The data is coming from S3, in the form of JSON. I cache the JSON for all of these 10 tests, for both with and without security, and display the data from there.

![Screen Shot 2022-09-08 at 1 31 39 PM](https://user-images.githubusercontent.com/44730413/189220180-fee63f55-e8a2-4f69-8648-5ce12c9f8b61.png)

**Comment by bshien** [comment]
The Perf test page will be a list and must have in each row:

- architecture
- security enabled?
- instance type
- workload details
- index latency(p50, p90, p99, p100)
- throughput(p0, p50, p100)
- etc.(more info in the json provided)

**Comment by gaiksaya** [comment]
PR #2500 will help to get a dedicated URL to get the performance test results based on top 10 builds in jenkins. The file name has been changed to `perf-test.json` instead of `test_id.json` https://github.com/opensearch-project/opensearch-infra/pull/164 to avoid dynamic naming.
