### ISSUE TITLE
Create publishToMaven lib that automates maven releases completely

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/opensearch-build#2398]
### Is your feature request related to a problem? Please describe

Currently, even though most of the process for maven release is automated, there is a last step that needs human intervention by logging into the nexus sonatype, closing the staging repo and then hitting release. 
This causes @opensearch-project/engineering-effectiveness to become bottle neck for all maven related releases as they own the credentials to the platform.

### Describe the solution you'd like

This process can be automated completely in a such a way that no human intervention is required and any maintainer can release the opensearch and its artifacts.

### Describe alternatives you've considered

Some quick research gives this documentation: https://central.sonatype.org/publish/publish-guide/#releasing-to-central
https://github.com/sonatype/nexus-maven-plugins/blob/main/staging/maven-plugin/README.md

### Acceptance criteria:
 Publish the artifacts to maven repository without any human intervention.
 The publishing process should be automated end to end.

**Comment by prudhvigodithi** [comment]
[Triage], we can explore `nexus-maven-plugin` to do this promotion without human intervention.

**Comment by gaiksaya** [comment]
I don't believe any testing needs/can be done around it. The maven release needs all kinds of checksums, signature files, etc along with the artifacts which ensures that the artifacts being uploaded are legit. The authentication or access of end to end process is what needs to be considered while working on this.
Would like your thoughts on this @prudhvigodithi @dblock @saratvemulapalli

**Comment by dblock** [comment]
For clients I wouldn't do any extra work and trust CI/CD. If all tests pass (and they do during this process), :shipit:

**Comment by saratvemulapalli** [comment]
+1 As long as we sign the artifacts and verify the signatures we should be good. 
This is how I see it, for infra our job is to enable verified releases to maven for maintainers. We would rely on the maintainers to do all the checks in CIs and determine its ready for release.

**Comment by gaiksaya** [comment]
Posting a successful run here: https://build.ci.opensearch.org/job/publish-to-maven/4/console
The auto publish part works. Few nits needs to be worked upon. @rishabh6788 is taking care of it.

Thanks @rishabh6788 Great work. 🙌 
Also thanks @mch2 for all the knowledge transfer
