### ISSUE TITLE
Add license header checking

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#242]
**Is your feature request related to a problem? Please describe.**

We keep forgetting license headers in .py files.

**Describe the solution you'd like**

Add license header checking for source code in this repo that runs in CI/PRs. Hopefully an existing tool.

**Comment by peternied** [comment]
Maybe this GHA action https://github.com/marketplace/actions/license-checker could work?

**Comment by gaiksaya** [comment]
Closed via https://github.com/opensearch-project/opensearch-build/pull/2666
