### ISSUE TITLE
[Bug]: Performance test infrastructure broken 

### ISSUE THREAD

**Issue by kotwanikunal** [opensearch-project/opensearch-build#2429]
### Describe the bug

The migration of the performance test job to https://build.ci.opensearch.org/ has broken the performance test infra for OpenSearch core. This can affect upcoming launch testing. 

### To reproduce

Execute any performance test using https://build.ci.opensearch.org/job/perf-test/.

### Expected behavior

Test should run successfully. 

### Relevant log output

```shell
https://build.ci.opensearch.org/job/perf-test/322/console
```

**Comment by gaiksaya** [comment]
Performance tests are fixed now https://build.ci.opensearch.org/job/perf-test/340/
https://build.ci.opensearch.org/job/perf-test/341/

A role was missing from the infrastructure which was added and fixed the permissions with another role.

Closing this issue.
