### ISSUE TITLE
[Bug]: The shared library in jenkins points to 20211123

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/opensearch-build#2433]
### Describe the bug

In order to avoid jenkins use the cached library instead of new updated one, a date was added and was supposed to be updated with each iteration when we modify the libraries.
See https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/opensearch/distribution-build.jenkinsfile#L1

However since all jobs are now dockerized or use new agent the most recent library is used which hides this bug. If same agent is used in future the library wont be updated. 

### To reproduce

See all the jenkins file in https://github.com/opensearch-project/opensearch-build/blob/main/jenkins and PR https://github.com/opensearch-project/opensearch-build/pull/921

### Expected behavior

Suggesstion is to go with dynamic behavior which will retrieve the most recent library from that branch (in this case main)
https://www.jenkins.io/doc/book/pipeline/shared-libraries/#dynamic-retrieval

Used here https://github.com/opensearch-project/opensearch-java/blob/main/jenkins/stage-maven-release.jenkinsfile#L1

```
lib = library(identifier: 'jenkins@main', retriever: modernSCM([
    $class: 'GitSCMSource',
    remote: 'https://github.com/opensearch-project/opensearch-build.git',
]))
```

**Comment by dblock** [comment]
The problem with dynamic retrieval is that it will only work on a well defined branch. If you try to run Jenkins code from a personal fork/branch for testing, for example, you will have to change all the references to it. I think what we want is behavior similar to GHA where it uses the currently checked out code. I *think* the way to accomplish that is (haven't tested)

```
lib = library(identifier: "jenkins@$GIT_COMMIT", retriever: legacySCM(scm))
```

**Comment by zelinh** [comment]
[Triage] We have enough information on this and we will look into this issue later.

**Comment by prudhvigodithi** [comment]
Closing this issue as the shared libraries now are migrated to new [repo](https://github.com/opensearch-project/opensearch-build-libraries/), where jenkins files from [build repo](https://github.com/opensearch-project/opensearch-build/tree/main/jenkins) will use `$class: 'GitSCMSource',` 
Related PR: https://github.com/opensearch-project/opensearch-build/pull/2652/files
@jordarlu @gaiksaya @bbarani 

Please re-open if required.
Thank you
