### ISSUE TITLE
[Retrospective] Release Version 2.2.0

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#2451]
#2271

How to use this issue?
Please add comments to this issue, they can be small or large in scope. Honest feedback is important to improve our processes, suggestions are also welcomed but not required.

What will happen to this issue post release?
There will be a discussion(s) about how the release went and how the next release can be improved. Then this ticket will be updated with the notes of that discussion along side action items.

**Comment by ohltyler** [comment]
Last-minute changes that were merged in core OpenSearch (1-2 days before code cutoff for plugins) caused unforeseen failures in both source code and test cases for plugins ([example](https://github.com/opensearch-project/anomaly-detection/pull/637), [example](https://github.com/opensearch-project/anomaly-detection/pull/634/files)), where not all issues were able to be resolved by the code cutoff. Some were merged after the initial test builds were ready. This made it very difficult to plan for, and potentially could have delayed the release. I recommend core has a cutoff sooner than the plugins to prevent this, and give plugins some more buffer time to better handle situations like this.

Additionally, dependent plugins + core ([ref](https://github.com/opensearch-project/job-scheduler/pull/215), [ref](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/1860)) were not version bumped right after the latest release, and so our AD plugin couldn't test 2.2 compatibility until a few days before the code cutoff. I know this is the goal of infra team already, but it seems to not be enforced. But I believe the auto-version-increment campaigns should improve this for future releases.

**Comment by TheMeier** [comment]
The build-tools where not published with the release. See https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/pull/87

**Comment by lukas-vlcek** [comment]
I am not able to find any `org.opensearch` artifacts with `2.2.0` version in public mvn repositories (not just the build-tool as @TheMeier pointed out). Is there any ticket tracking this issue?

**Comment by kolchfa-aws** [comment]
Specifically regarding release notes: thank you for providing them early to the doc team! In the future, if the developers adhere to the PR naming guidelines, all of the bullet points in the release notes will have consistent verb forms and capitalization. This will avoid bullet points starting with different forms of the same verb like "Add", "adds", "Adding" and "added".

**Comment by bbarani** [comment]
> I am not able to find any `org.opensearch` artifacts with `2.2.0` version in public mvn repositories (not just the build-tools as @TheMeier pointed out). Is there any ticket tracking this issue?
> 
> This issue has been also reported [here](https://github.com/opensearch-project/opensearch-build/issues/2271#issuecomment-1212905942).

Hi @lukas-vlcek We have opened an issue with Sonatype to resolve this issue. We will keep this [thread](https://github.com/opensearch-project/opensearch-build/issues/2271#issuecomment-1213419604) updated with the current status

**Comment by bbarani** [comment]
Some code changes were merged in to 2.2.0 branch after finalizing the RC build assuming it will be auto picked up to create new RC build. We identified this change at the last minute and need a mechanism to prevent this from happening.

**Comment by bbarani** [comment]
@ohltyler We dont have plans to freeze core sooner than the cut-off time rather we would like to start the continuous integration process before the code-cutoff date to surface the issues mentioned [here](https://github.com/opensearch-project/opensearch-build/issues/2451#issuecomment-1212489812) sooner. Would it help if we add an additional phase (CI on-boarding) to the release checklist prior to code cut-off at everyone you should have version specific branch created and on-boarded in to the manifest? CC: @CEHENKLE @dblock

**Comment by dblock** [comment]
The existing checklist already has an entry that says "increment the version to next developer iteration", which automatically means that CI should be building on that next version.

**Comment by peterzhuamazon** [comment]
Thanks everyone for the feedback this retro is closed for now.
Thanks.
