### ISSUE TITLE
Publish logstash-output-opensearch plugin to rubygems.org for 1.3.0 version

### ISSUE THREAD

**Issue by deepdatta** [opensearch-project/opensearch-build#2452]
Need to build and publish the plugin from git repo [logstash-output-opensearch](https://github.com/opensearch-project/logstash-output-opensearch)
Date: 8/16/2022

**Comment by zelinh** [comment]
Logstash-output-opensearch plugin has been published to rubygems.org successfully. 
https://rubygems.org/gems/logstash-output-opensearch/versions/1.3.0-java
