### ISSUE TITLE
[Bug]: Local test cluster logs for integ-test generated files are empty

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/opensearch-build#2464]
### Describe the bug

The test recorder records logs for integ-test as below:
1. Local cluster logs:

- stdout: https://ci.opensearch.org/ci/dbc/integ-test/2.1.0/5740/linux/x64/tar/test-results/1/integ-test/alerting/with-security/local-cluster-logs/stdout.txt
- stderr: https://ci.opensearch.org/ci/dbc/integ-test/2.1.0/5740/linux/x64/tar/test-results/1/integ-test/alerting/with-security/local-cluster-logs/stderr.txt

2. Plugin actual integ-test logs:

- stdout:  https://ci.opensearch.org/ci/dbc/integ-test/2.1.0/5740/linux/x64/tar/test-results/1/integ-test/alerting/with-security/test-results/stdout.txt
- stderr:https://ci.opensearch.org/ci/dbc/integ-test/2.1.0/5740/linux/x64/tar/test-results/1/integ-test/alerting/with-security/test-results/stderr.txt
- <component>.yml : https://ci.opensearch.org/ci/dbc/integ-test/2.1.0/5740/linux/x64/tar/test-results/1/integ-test/alerting/with-security/test-results/alerting.yml

However, the local cluster logs do not have any data in them. See above links

### To reproduce

Click the above urls or try running integ-test locally and see that local-test cluster logs are empty

### Expected behavior

The txt files should have data about the cluster.

**Comment by jordarlu** [comment]
@rishabh6788 commented how to fix this issue on https://github.com/opensearch-project/opensearch-build/pull/3016#issuecomment-1368177810

**Comment by bbarani** [comment]
@gaiksaya Can we close this issue since we have merged the fix?

**Comment by gaiksaya** [comment]
Yes the issue is fixed as seen in recent integ-test run https://ci.opensearch.org/ci/dbc/integ-test/1.3.8/7019/linux/x64/tar/test-results/3754/integ-test/alerting/with-security/local-cluster-logs/stdout.txt
