### ISSUE TITLE
[Bug]: The cdk clusters used for performance testings are not destroyed if build is aborted

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/opensearch-build#2504]
### Describe the bug

If the build is aborted in https://build.ci.opensearch.org/job/perf-test/ the underlying performance test clusters brought up using cdk are not destroyed causing them to be abandoned until manually cleaned

### To reproduce

Run the above job and abort it.
Got to the related aws account and see that cloudformation stack for that job is not destroyed

### Expected behavior

Stacks should be cleaned irrespective of success or failure

### Acceptance criteria 

- [ ] When the Jenkins/CI job is abortted/interrupted/terminated, CDK cluster that was created by code shall be deleted  
- [x] When the Jenkins/CI job is completed successfully, CDK cluster that was created by code shall be deleted
- [x] When the Jenkins/CI job is fail, CDK cluster that was created by code shall be deleted

**Comment by jordarlu** [comment]
https://stackoverflow.com/questions/25047537/running-a-post-build-script-when-a-jenkins-job-is-aborted
https://www.jenkins.io/doc/book/pipeline/syntax/#post

**Comment by gaiksaya** [comment]
When a workflow is aborted it is usually due to issue with the jenkins example: timeouts, connectivity error, etc.
One of the approach can be:
Export the name of the stack form python code (AFAIK they are static so not really required) and use the aborted block to destroy the stack using aws cli command.

What it would look like:
```
post {
    aborted {
        node(AGENT_LABEL) {
            script {
                withCredentials([string(credentialsId: "${args.roleAccountNumberCred}", variable: 'AWS_ACCOUNT_NUMBER')]) {
                    withAWS(role: args.assumedRoleName, roleAccount: "${AWS_ACCOUNT_NUMBER}", duration: 900, roleSessionName: 'jenkins-session', region: "${region}") {
                        cfnDelete(stack:'my-stack', pollInterval:1000, roleArn: 'args.assumedRoleNam')
                    }
                }
            }
        }
    }
}

**Comment by jordarlu** [comment]
this issue is resolved. Test ref is here https://build.ci.opensearch.org/job/perf-test/3962/console  , thanks
