### ISSUE TITLE
[Bug]: A broken link on page opensearch-build/vars/README.md

### ISSUE THREAD

**Issue by jordarlu** [opensearch-project/opensearch-build#2510]
### Describe the bug

A broken link on Jenkins shared library README.md is discovered. 

existing:

Running Integration Tests
See [runIntegTests](https://github.com/opensearch-project/opensearch-build/blob/main/vars/runIntegTests.groovy).

Correction:
Running Integration Tests
See [runIntegTestScript](https://github.com/opensearch-project/opensearch-build/blob/main/vars/runIntegTestScript.groovy).

### To reproduce

Please browse here https://github.com/opensearch-project/opensearch-build/tree/main/vars#running-integration-tests, and click the link of [runIntegTests](https://github.com/opensearch-project/opensearch-build/blob/main/vars/runIntegTests.groovy).

### Expected behavior

the link should be corrected to be [runIntegTestScript](https://github.com/opensearch-project/opensearch-build/blob/main/vars/runIntegTestScript.groovy)   ( Thanks to @prudhvigodithi )

**Comment by bbarani** [comment]
Closing this issue as we have fixed the broken link on the documentation page.
