### ISSUE TITLE
Release .NET Clients version 1.1.0 to NuGet

### ISSUE THREAD

**Issue by joshuali925** [opensearch-project/opensearch-build#2522]
### Is your feature request related to a problem? Please describe

OpenSearch 2.x had a few breaking changes and is no longer compatible with .NET Client version 1.0.0. We would like to publish .NET Client version 1.1.0 to NuGet, which will be compatible with OpenSearch 1.x and 2.x.

### Describe the solution you'd like

Infra's help to prepare a new release, and publish artifacts to NuGet after code is ready. 

Artifacts will be generated by [this workflow](https://github.com/opensearch-project/opensearch-net/actions/workflows/release.yml) from branch `1.1` (cut after code is ready).

Code is currently pending on a few PRs:
https://github.com/opensearch-project/opensearch-net/pull/51

### Additional context

Release issue in opensearch-net repo: https://github.com/opensearch-project/opensearch-net/issues/76

**Comment by bbarani** [comment]
@joshuali925 @anirudha Please confirm that all the necessary reviews have been completed before proceeding with the release. @prudhvigodithi

**Comment by wbeckler** [comment]
We have not merged a couple key commits for this release. This should happen in the next 24 hours.

**Comment by bbarani** [comment]
@wbeckler @anirudha @joshuali925 Are we good for releasing the 1.1.0 version? Do we have a branch for releasing the new version? Please confirm before we start the publishing process. @prudhvigodithi

**Comment by gaiksaya** [comment]
The version for `1.1.0` branch do not match actual version of the artifacts. Please fix the version number and let us know. We can proceed then.
Thanks!

**Comment by prudhvigodithi** [comment]
We just shipped OpenSearch 1.1.0 .NET clients to Nuget repo https://www.nuget.org/profiles/opensearchproject.
https://www.nuget.org/packages/OpenSearch.Client/1.1.0
https://www.nuget.org/packages/OpenSearch.Client.JsonNetSerializer/1.1.0
https://www.nuget.org/packages/OpenSearch.Net/1.1.0
https://www.nuget.org/packages/OpenSearch.Net.VirtualizedCluster/1.1.0
Thanks to everyone who are part of this process.
