### ISSUE TITLE
Create a custom jenkins build

### ISSUE THREAD

**Issue by vibrantvarun** [opensearch-project/opensearch-build#2536]
Opensearch extensibility team is planning to automate performance testing. To automate that we need to create a Jenkins job. In order to that is there any process to have a custom Jenkins build for the above purpose?

**Comment by gaiksaya** [comment]
Hi @vibrantvarun , Please see https://github.com/opensearch-project/opensearch-ci to bring up you own jenkins infrastructure.

**Comment by bbarani** [comment]
I would recommend using OpenSearch Benchmark for this purpose

**Comment by gaiksaya** [comment]
Closing this issue. Please re-open if required.
Thanks!
