### ISSUE TITLE
Automate: Update the manifest refs to tags.

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/opensearch-build#2546]
### Is your feature request related to a problem? Please describe

After every release the [Post release activity](https://github.com/opensearch-project/opensearch-build/issues/2481) is to update the [manifest refs](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/2.2.1/opensearch-2.2.1.yml#L13) to point to the generated tags, here is an example [manual PR ](https://github.com/opensearch-project/opensearch-build/pull/2543).

### Describe the solution you'd like

Have an jenkins jobs or extend existing [jenkins job](https://github.com/opensearch-project/opensearch-build/tree/main/jenkins/release-tag) that cuts the tag for every component, followed by to raise a PR with updated manifest, where `ref` value inside the manifest points to the right tag.

**Comment by dblock** [comment]
+1 on extending the existing job

**Comment by bbarani** [comment]
[Triage] We will work on auto updating the manifest with corresponding tag information after every release.

**Comment by hitenshKharva** [comment]
I would like to try fixing this issue.

**Comment by hitenshKharva** [comment]
@gaiksaya @peterzhuamazon I went through the approaches discussed during the office hours but I am still confused on the approach to fix this issue. 
Few questions:
1. when a new release tag is generated, where should I fetch it?
2. My best case approach if we can run a python script via github action to replace manifest refs to tags? Does that sound good?
3. Also, if we go ahead with above approach what will be the optimal way to trigger the Github action once new tags are generated?

Thanks.

**Comment by gaiksaya** [comment]
Hey!

1. Release tags are generated after each release of OpenSearch. This is the [workflow](https://build.ci.opensearch.org/job/distribution-release-tag-creation/) responsible for creating tags across all the repositories. Source coded [here](https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/release-tag/release-tag.jenkinsfile). This is the underlying [library](https://github.com/opensearch-project/opensearch-build-libraries/blob/main/vars/createReleaseTag.groovy) which is run in the above workflow.
2. There are 3 options: 
   i. Create a new groovy library that will update the refs and create a pull request (all in one)
   ii. Create a python script that can be run on anything (jenkins/GHA)and then create pull request: [Example](https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/manifests-update.jenkinsFile#L33-L50)
   iii. Create a simple GHA workflow that takes version as an input and does the update using it.
3. If using GitHub actions, it will be triggered using `workflow_dispatch` event that will take `version` as an input. Example: https://github.com/opensearch-project/data-prepper/blob/main/.github/workflows/release.yml#L3-L14. We can send dispatch as a post condition to above release-tag workflow.
