### ISSUE TITLE
Automate: The docker layer validation.

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/opensearch-build#2547]
### Is your feature request related to a problem? Please describe

During the release when the [docker promotion](https://build.ci.opensearch.org/job/docker-promotion/) job is called, it copies the RC images to the actual version tags and pushes to the [production account dockerhub](https://hub.docker.com/u/opensearchproject), this is done using `gcrane` cli. Once called and promotion is done as a verification the layers for RC image vs the prod image are compared manually.

### Describe the solution you'd like

Automation the is step within the validation workflow.
This can leverage [container-diff](https://github.com/GoogleContainerTools/container-diff) to compare 2 images.

**Comment by zelinh** [comment]
Closed this for now. We are using `gcrane` which takes care most of the efforts here.
