### ISSUE TITLE
Build and publish logstash-output-opensearch to RubyGems.org for 2.0.0 Version

### ISSUE THREAD

**Issue by deepdatta** [opensearch-project/opensearch-build#2548]
Build and publish logstash-output-opensearch to rubygems.org for 2.0.0 Version

**Comment by gaiksaya** [comment]
logstash-output-opensearch 2.0.0 for OpenSearch is shipped now.
https://rubygems.org/gems/logstash-output-opensearch/versions/2.0.0-java
