### ISSUE TITLE
[CI/CD] Disable gradle precommit on Draft PRs

### ISSUE THREAD

**Issue by nknize** [opensearch-project/opensearch-build#256]
Since draft PRs are just that, we shouldn't expect precommit to pass. Therefore, we shouldn't spend CI/CD resources running precommit unless the PR is no longer a draft. Is there a git hook to prevent spinning up resources to execute the precommit check on draft PRs?

**Comment by peternied** [comment]
[Triage] @nknize The current resource usage is not a concern, we would rather detect more issues in advance.
