### ISSUE TITLE
[Bug]: Unable to download artifacts for 1.3.5

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#2588]
### Describe the bug

Cannot download the latest version of 1.3.5 security using the `latest` url, using a previous build number `5996` does work

#### Run this command
```
wget https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/1.3.5/latest/linux/x64/tar/builds/opensearch/plugins/opensearch-security-1.3.5.0.zip
```

#### See this output
```
--2022-09-08 18:03:56--  https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/1.3.5/latest/linux/x64/tar/builds/opensearch/plugins/opensearch-security-1.3.5.0.zip
Resolving ci.opensearch.org (ci.opensearch.org)... 18.165.83.97, 18.165.83.92, 18.165.83.108, ...
Connecting to ci.opensearch.org (ci.opensearch.org)|18.165.83.97|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: /ci/dbc/distribution-build-opensearch/1.3.5/6021/linux/x64/tar/builds/opensearch/plugins/opensearch-security-1.3.5.0.zip [following]
--2022-09-08 18:03:56--  https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/1.3.5/6021/linux/x64/tar/builds/opensearch/plugins/opensearch-security-1.3.5.0.zip
Reusing existing connection to ci.opensearch.org:443.
HTTP request sent, awaiting response... 403 Forbidden
2022-09-08 18:03:56 ERROR 403: Forbidden.
```

### Expected behavior

No 403 error

**Comment by peternied** [comment]
@gaiksaya Could you look into this?

**Comment by prudhvigodithi** [comment]
I see whats happening, the index file was overridden by this build which has only the `OpenSearch` component built
 https://build.ci.opensearch.org/job/distribution-build-opensearch/6021/consoleFull
I feel like this is bug moving forward, if we rebuild the already released version, then it overrides the index version and fails to download with `/latest/`

2 solutions to fix bug (temporarily )
1. Manually update the index file in s3
2. Rebuild the distribution with full 1.3.5 manifest, but this will be a new number from RC which us 5996.

@peterzhuamazon @gaiksaya @bbarani

**Comment by Angie-Zhang** [comment]
index-management backport to 1.3.5 also meets this issue: 
https://github.com/opensearch-project/index-management/pull/489
https://github.com/opensearch-project/index-management/runs/8243634566?check_suite_focus=true

**Comment by gaiksaya** [comment]
Hi @peternied @Angie-Zhang I am able to wget the above artifacts. Can you try now?
Thanks!

**Comment by prudhvigodithi** [comment]
Hey @peternied @Angie-Zhang @gaiksaya  just checking to see if this issue can be closed.
Thank you

**Comment by peternied** [comment]
I was able to confirm this works, thanks for getting it resolved!
