### ISSUE TITLE
[Enhancement] Add Key expiration alerting and monitoring

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#2625]
The key management of our releases needs to be monitored.
1. The general key for all the signatures on artifacts
2. The key specifically for the ruby artifacts like opensearch-ruby and logstash-oss-opensearch.

They will expire in about a year:
1. Need to extend 20230512 https://github.com/opensearch-project/opensearch-build/issues/2136
2. Need to extend / recreate 20220802

### Acceptance criteria
- [ ] Monitor the current status along with the expiration is added for all the keys used for signing the OpenSearch artifacts (including clients and standalone components)
- [ ] Automated alerting mechanism is in place for all the keys used for signing the artifacts
- [ ] Create dashboards to view the current status of all the keys

**Comment by rishabh6788** [comment]
The signing key metrics are not getting published for our internal monitoring.
