### ISSUE TITLE
Consolidate Data Prepper build to a single job

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/opensearch-build#2632]
### Is your feature request related to a problem? Please describe

The Data Prepper Jenkins promotion job has a step which copies from the Data Prepper staging ECS repository into the promotion DockerHub and ECS repositories. That stage is shown below.

https://github.com/opensearch-project/opensearch-build/blob/2300e055106a23ac98801d209647bdfa590b893f/jenkins/data-prepper/release-data-prepper-all-artifacts.jenkinsfile#L80-L109

After running this Jenkins job, the build process requires that the Jenkins team run the "Copy Docker Image Jenkins job" up to four more times. These jobs will apply either the latest version label (e.g. `2`) or the `latest` label. Please note that not all releases need these. For example running a patch for `1.5.2` after releasing `2` should not update `latest`.

We should be able to supply all the parameters needed into the one Data Prepper Jenkins job.

### Describe the solution you'd like

The Data Prepper promotion Jenkins job could take in two new boolean flags:

* "Label latest major" - If set to true, the job will parse the version string for the major version (e.g. `2.0.0` -> `2`). Then it will run the "Copy Docker Image Jenkins job" to apply the major version label (e.g. `2`).
* "Label latest" - If set to true, then run the "Copy Docker Image Jenkins job" to apply the `latest` label.

### Describe alternatives you've considered

Instead of the boolean flags, we could have a comma-delimited list of extra labels to apply. However, these specific flags are more explicit to the users releasing Data Prepper.

**Comment by dlvenable** [comment]
@asifsmohammed , @gaiksaya

**Comment by peterzhuamazon** [comment]
[Triage]

@dlvenable we are ok with the approach you can either do the label major/latest or just code other 3 copies after the initial copy, either way works.
