### ISSUE TITLE
[RELEASE] Release version 1.2.0 of opensearch-net client (with SIGv4 support)

### ISSUE THREAD

**Issue by MaxKsyunz** [opensearch-project/opensearch-build#2635]
### Is your feature request related to a problem? Please describe

.NET client accepted a PR with SIGv4 support. 

It'd be great to release this on nuget.org so that other people can use it.

### Describe the solution you'd like

This needs support from infra team to sign artifacts and publish to nuget.org.

### Describe alternatives you've considered

The packages can be published as a release on the repository but they won't be signed or as accessible as on nuget.org

**Comment by dblock** [comment]
Can we prioritize https://github.com/opensearch-project/opensearch-net/issues/79 sooner so that this kind of asks aren't necessary?

**Comment by dblock** [comment]
Is there any update on this? @bbarani ?

**Comment by harshavamsi** [comment]
> Is there any update on this? @bbarani ?
> 
> See [opensearch-project/opensearch-net#112 (comment)](https://github.com/opensearch-project/opensearch-net/issues/112#issuecomment-1284811613)

Let's target early next week via MCM. Opened https://github.com/opensearch-project/opensearch-net/issues/113 to track.

**Comment by harshavamsi** [comment]
> [Triage] @MaxKsyunz please let us know once you have the branch ready and the release date defined so we can assign resources and start working on it.
> 
> cc: @harshavamsi

We have [1.2.0](https://github.com/opensearch-project/opensearch-net/releases/tag/v1.2.0) tag ready to release. Tentative release date 10/26.

**Comment by prudhvigodithi** [comment]
We just shipped OpenSearch 1.2.0 .NET clients to Nuget repo https://www.nuget.org/profiles/opensearchproject.
https://www.nuget.org/packages/OpenSearch.Client/1.2.0
https://www.nuget.org/packages/OpenSearch.Client.JsonNetSerializer/1.2.0
https://www.nuget.org/packages/OpenSearch.Net/1.2.0
https://www.nuget.org/packages/OpenSearch.Net.VirtualizedCluster/1.2.0
https://www.nuget.org/packages/OpenSearch.Net.Auth.AwsSigV4/1.2.0
Thanks to everyone who are part of this process.

**Comment by prudhvigodithi** [comment]
Hey Closing this issue as release is completed, please feel free to open if required. Thanks
