### ISSUE TITLE
Support release process for opensearch-testcontainers

### ISSUE THREAD

**Issue by reta** [opensearch-project/opensearch-build#2656]
### Is your feature request related to a problem? Please describe

We have a new repository `https://github.com/opensearch-project/opensearch-testcontainers/` to support OpenSearch integration with TestContainers.

### Describe the solution you'd like

The release process is not yet in place, the artifacts are: signed JARs under `org.opensearch` group (Sonatype or alternative public Apache Maven repositories).

### Describe alternatives you've considered

N/A

### Additional context

@peterzhuamazon please hint what should be done, happy to work on that, thank you!

**Comment by peterzhuamazon** [comment]
[Triage] This requires integration with Maven like other client releases such as data prepper
https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/data-prepper/release-data-prepper-all-artifacts.jenkinsfile#L121-L170

@reta let us have more talks on this on the actual release timing.

cc: @bbarani

**Comment by reta** [comment]
thanks @peterzhuamazon, anything pending from my side or you guys are going to discuss it internally?

**Comment by dblock** [comment]
I think you should copy https://github.com/opensearch-project/opensearch-java/pull/187 and https://github.com/opensearch-project/opensearch-java/pull/188 and ... that's it?

**Comment by dblock** [comment]
@peterzhuamazon I'd like to have "something that can be replicated/copied by other projects" as an outcome of this exercise.

**Comment by peterzhuamazon** [comment]
Talked with @reta and he will use references from data prepper and opensearch java to create a jenkinsfile, which includes calling existing libs to publish snapshots and maven central.

Infra will setup the webhook and token for the official releases to be happened through creation of tags.

Thanks.

**Comment by peterzhuamazon** [comment]
Released snapshot: 
* https://github.com/opensearch-project/opensearch-testcontainers/pull/23
Added Daily Snapshot:
* https://github.com/opensearch-project/opensearch-testcontainers/pull/26

**Comment by peterzhuamazon** [comment]
We will do the production release at another time with another Jenkins workflow.

Current snapshot workflow: 
* https://build.ci.opensearch.org/job/opensearch-testcontainers-snapshot/

**Comment by dblock** [comment]
I love this. Is there a cookbook of how to do this for any repo? Should we document this in opensearch-build for the next person?

**Comment by peterzhuamazon** [comment]
> I love this. Is there a cookbook of how to do this for any repo? Should we document this in opensearch-build for the next person?

We will have a team meeting on this and hope we can have a blog as well to describe what is needed to onboard.

**Comment by peterzhuamazon** [comment]
New fix: 
* https://github.com/opensearch-project/opensearch-testcontainers/pull/28

**Comment by reta** [comment]
> > I love this. Is there a cookbook of how to do this for any repo? Should we document this in opensearch-build for the next person?
> 
> We will have a meeting on this and hope we can have a blog as well to describe what is needed to onboard.

@dblock we have just one more thing left for this week - check that releases work - and than I will document everyting + port it to `spring-data-opensearch`

**Comment by peterzhuamazon** [comment]
> > > I love this. Is there a cookbook of how to do this for any repo? Should we document this in opensearch-build for the next person?
> > 
> > 
> > We will have a meeting on this and hope we can have a blog as well to describe what is needed to onboard.
> 
> @dblock we have just one more thing left for this week - check that releases work - and than I will document everything + port it to `spring-data-opensearch`

There is still something that we need some overhaul once all the things are released.
I will sync up to you later on the details to make it rock solid.

Thanks.

**Comment by peterzhuamazon** [comment]
We have released OpenSearch Testcontainers 2.0.0 with @reta:

![image](https://user-images.githubusercontent.com/65193828/198144021-634fbfd0-25fa-4ffa-920e-30d5569e7509.png)


https://build.ci.opensearch.org/job/opensearch-testcontainers-release/7/

https://github.com/opensearch-project/opensearch-testcontainers/releases/tag/release-2.0.0

There are still some things to improve and I will work with @reta on that.

Thanks.

**Comment by peterzhuamazon** [comment]
Maven Central: https://repo1.maven.org/maven2/org/opensearch/opensearch-testcontainers/2.0.0/

**Comment by peterzhuamazon** [comment]
@reta please feel free to close this issue once all the related changes are addressed.

Thanks.

**Comment by peterzhuamazon** [comment]
Releasing 1.0.0 with @reta on the official maven central release.

**Comment by peterzhuamazon** [comment]
![image](https://user-images.githubusercontent.com/65193828/198710106-718fc2dc-c2c2-4b26-b76d-c5928fca821b.png)

Maven Central: https://repo1.maven.org/maven2/org/opensearch/opensearch-testcontainers/1.0.0/
