### ISSUE TITLE
Onboard cross cluster replication artifacts to OpenSearch

### ISSUE THREAD

**Issue by ankitkala** [opensearch-project/opensearch-build#266]
Repo link: https://github.com/opensearch-project/cross-cluster-replication/

**Comment by dblock** [comment]
Let's use this opportunity to document what there is to be done. As far as bundle build, you would need to ensure the project is building against 1.1, and add it to the 1.1 manifest, which is currently in PR https://github.com/opensearch-project/opensearch-build/pull/234.

**Comment by peternied** [comment]
[Triage] this has already been merged
