### ISSUE TITLE
[PR test & review] Simplification of the ZIP publication implementation 

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/opensearch-build#2664]
### Is your feature request related to a problem? Please describe

This task is related to the enhancements made to custom gradle plugin [opensearchpluginzip](https://github.com/opensearch-project/opensearch-plugins/blob/main/BUILDING.md#opensearchpluginzip).

PR: https://github.com/opensearch-project/OpenSearch/pull/4360/files
Test the above PR with changes proposed by @lukas-vlcek.

- [x] Test and execute the build workflow.
- [x] Build OpenSearch Component.
- [x] Build plugin component that outputs the zip file.
- [x] Verify the generated zip file is published to local maven (on host).
- [x] Verify by passing and not passing the `groupId` to the `pluginZip` maven publication POM.
- [x] Test by removing the plugin `apply plugin: 'opensearch.pluginzip'` from the `build.gradle` file.
- [x] Test by adding `apply plugin: 'opensearch.pluginzip'` and removing the publication `pluginZip(MavenPublication)`.

### Describe the solution you'd like

N/A

**Comment by prudhvigodithi** [comment]
When applying the plugin `apply plugin: 'opensearch.pluginzip'`
commenting out the publication
```
/*publishing {
    publications {
        pluginZip(MavenPublication) { publication ->
            pom {
                groupId = 'org.opensearch.plugin'
                name = "opensearch-job-scheduler"
                description = "OpenSearch Job Scheduler plugin"
            }
        }
    }
}*/
```
```
* Exception is:
org.gradle.execution.TaskSelectionException: Task 'publishPluginZipPublicationToMavenLocal' not found in root project 'opensearch-job-scheduler'.
```

**Comment by lukas-vlcek** [comment]
@prudhvigodithi

The message:

> Plugin 'opensearch.pluginzip' is applied but no 'pluginZip' publication is defined.

is expected.

There is explicit test for this situation. The test `missingPublications()` which uses the `missingPublication.gradle` template. The output should contain that WARN message.

I am not sure about the exception though... let me have a look.

**Comment by prudhvigodithi** [comment]
Hey @lukas-vlcek thanks, ya that is expected, we should be good to close this issue as well.
