### ISSUE TITLE
[Enhancement] Include OSD-FT repo into manifest auto creation

### ISSUE THREAD

**Issue by noCharger** [opensearch-project/opensearch-build#2671]
## Context and Benefits

During the release of the OSD-FT repo https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/285, we must [raise the PR](https://github.com/opensearch-project/opensearch-build/pull/2577) to include OSD-FT repo in the manifest for both the next minor and patch release. Because more plugins are adopting OSD-FT, we could automate this process to include OSD-FT ahead of time, to make it easier for plugins to run release testing and save the opensearch-build repo maintainer's time reviewing those PRs.

**Comment by peterzhuamazon** [comment]
I will work with @noCharger on this tomorrow, should be straight forward changes overall.

**Comment by peterzhuamazon** [comment]
Synced up with @noCharger on the key points he will raise the PR based on our conversation.
Thanks.

**Comment by noCharger** [comment]
AI: Include FT repo into the template https://github.com/opensearch-project/opensearch-build/blob/main/manifests/templates/opensearch-dashboards/3.x/manifest.yml

**Comment by bbarani** [comment]
@noCharger @peterzhuamazon Whats the updated status?

**Comment by noCharger** [comment]
> @noCharger @peterzhuamazon Whats the updated status?

It has been handed over to @tianleh

**Comment by tianleh** [comment]
The feature currently doesn't support auto update of version number. Thus a PR is still needed even if we onboard.

Close as it is not needed at this stage.
