### ISSUE TITLE
[Bug]: Following up #2679 - Updating TestReleaseTagJob and restore it

### ISSUE THREAD

**Issue by jordarlu** [opensearch-project/opensearch-build#2680]
### Describe the bug

While doing #2679, we found we need more time to work on refactoring TestReleaseTagJob without lib-testers.
Opening this issue to track the progress 

### To reproduce

The TestReleaseTagJob is currently removed from the main repo to prevent CI failure.
@jordarlu will update when it is ready to restore

### Expected behavior

the CI test should be a Pass

**Comment by prudhvigodithi** [comment]
Hey @jordarlu this issue can be part of this META https://github.com/opensearch-project/opensearch-build/issues/1468 👍

**Comment by jordarlu** [comment]
why I did not think of that way!? LOL ... thanks, @prudhvigodithi  :)
