### ISSUE TITLE
Release OpenSearch Maps Server to docker hub repo 1.0.0

### ISSUE THREAD

**Issue by junqiu-lei** [opensearch-project/opensearch-build#2681]
### Is your feature request related to a problem? Please describe

OpenSearch Maps Server helps to create a self-host maps server for OpenSearch Dashboard, for these who are not able to access to OpenSearch default maps service on air-gapped environments. We plan to release it as docker image to docker hub repo.

* Github repo: https://github.com/opensearch-project/maps/tree/main/opensearch-maps-server
* Docker repo: https://hub.docker.com/repository/docker/opensearchproject/opensearch-maps-server

### Describe the solution you'd like

Build the image and publish to docker hub repo.

**Comment by peterzhuamazon** [comment]
Next week oncall @rishabh6788 will take care of this and communicate with maps team on the timing.
We have discussed the details with @junqiu-lei on another meeting to onboard this release into part of universal build.
Thanks.

**Comment by bbarani** [comment]
@peterzhuamazon @rishabh6788 Lets look for ways to automate the publishing process similar to OpenSearch-java.

**Comment by peterzhuamazon** [comment]
Talked to @junqiu-lei in the office hour and he would make changes to the dockerfile as well as other things.
We will come back to this once he is ready and we will setup the universal build for them.

Thanks.

**Comment by junqiu-lei** [comment]
Thanks team, just sent out the PR to make changes to the dockerfile. 

https://github.com/opensearch-project/maps/pull/29

**Comment by peterzhuamazon** [comment]
I have provided the jenkinsfile PR and some tweaks for maps server to trigger a build + push to docker with tags.

**Comment by peterzhuamazon** [comment]
New fix PR: 
* https://github.com/opensearch-project/maps/pull/32

**Comment by peterzhuamazon** [comment]
New fix PR:
* https://github.com/opensearch-project/opensearch-build/pull/2772

**Comment by peterzhuamazon** [comment]
We have released maps-server 1.0.0 docker images on docker hub :rocket:!

This release is fully hand free from OSEE Team.
It is triggered directly by the component owner by creating a tag in their repo:
https://github.com/opensearch-project/maps/releases/tag/maps-server-release-1.0.0

The tag creation will trigger the webhook we setup in GitHub, which then trigger the build in Jenkins:
https://build.ci.opensearch.org/job/opensearch-maps-server-release/30/

The final release after jenkins complete the build:
https://hub.docker.com/r/opensearchproject/opensearch-maps-server/tags?page=1&name=1.0.0

Thanks @junqiu from the maps component team for the support.

Thanks.

**Comment by junqiu-lei** [comment]
Thanks team for great helps on the release!
