### ISSUE TITLE
[RELEASE] Release 2.1.0 version of opensearch-js client with Sigv4 support

### ISSUE THREAD

**Issue by harshavamsi** [opensearch-project/opensearch-build#2690]
### Is your feature request related to a problem? Please describe

We released [Sigv4 support](https://github.com/opensearch-project/opensearch-js/pull/279) for the opensearch-js client and would like to release it for people to use.   

### Describe the solution you'd like

Release version `2.1.0` and publish to npm.

Release checklist -- https://github.com/opensearch-project/opensearch-js/issues/303

**Comment by harshavamsi** [comment]
Hi @gaiksaya thanks for the effort on automating this! We are good to do whenever you have bandwidth. How about 10/19/2022?

**Comment by gaiksaya** [comment]
Hey @harshavamsi,

This would be very short notice. Can we so it sometime next week or does this need to be asap (that will be manual)?
cc: @zelinh

**Comment by harshavamsi** [comment]
@gaiksaya We would like to release 3 clients together if possible. We would be fine if we're able to automate one and release the other two manually. If there is bandwidth to release two this week and automate the other next week, that works. Or we could do all three next week.

**Comment by gaiksaya** [comment]
Hey @harshavamsi ,
What other clients are you planning to release? I know one of them is `opensearch-js`
Regarding opensearch-js I am trying to get the publishing lib in but would need sometime.

**Comment by harshavamsi** [comment]
> Hey @harshavamsi , What other clients are you planning to release? I know one of them is `opensearch-js` Regarding opensearch-js I am trying to get the publishing lib in but would need sometime.

We would like to do [.NET](https://github.com/opensearch-project/opensearch-build/issues/2635) early next week. We would also do the ruby client pending [sigv4 implementation](https://github.com/opensearch-project/opensearch-ruby/pull/104)

**Comment by luigidragone96** [comment]
Hi, is there any news regarding the release of the updated client on NPM?

**Comment by gaiksaya** [comment]
Hi @luigidragone96, I am working on automating the release process for NPM client. ETA: Monday Oct 31st but will update here is anything changes.
Thanks!

**Comment by luigidragone96** [comment]
@gaiksaya thanks for the update!

**Comment by gabrielrra** [comment]
Thanks, can't wait to use this feature

**Comment by wbeckler** [comment]
For the new automated release process, we will be waiting at least one more day, until November 1, to make sure we have everyone needed on hand to make sure it goes well.

**Comment by gaiksaya** [comment]
🚀  opensearch-js 2.1.0 is now released https://www.npmjs.com/package/@opensearch-project/opensearch/v/2.1.0
