### ISSUE TITLE
Proposal: Hyperlink directly to version download in release notes

### ISSUE THREAD

**Issue by krisfreedain** [opensearch-project/opensearch-build#2707]
### Is your feature request related to a problem? Please describe

When a new release goes out, the download page for that specific version has a direct link over to the release notes. It may be beneficial to also include a direct link to the version download from the release notes. 

### Describe the solution you'd like

example using the 1.3.6 release notes:

## Release Details

[OpenSearch and OpenSearch Dashboards 1.3.6](https://opensearch.org/versions/opensearch-1-3-6.html) includes the following bug fixes, infrastructure and maintenance updates.

OpenSearch [Release Notes](https://github.com/opensearch-project/OpenSearch/blob/main/release-notes/opensearch.release-notes-1.3.6.md).

OpenSearch Dashboards [Release Notes](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/release-notes/opensearch-dashboards.release-notes-1.3.6.md).

**Comment by gaiksaya** [comment]
[Triage] We will add them going forward.
Thanks!

**Comment by bbarani** [comment]
@peterzhuamazon Do you want to add it to the release checklist before closing this issue?

**Comment by peterzhuamazon** [comment]
> @peterzhuamazon Do you want to add it to the release checklist before closing this issue?

Will do.

**Comment by zelinh** [comment]
I achieved this request under our latest consolidated release notes for 2.4.0 in #2887
