### ISSUE TITLE
[Bug]: `latest` 3.0.0 OSD failed to run due to "Unknown configuration key(s)" from opensearch_security

### ISSUE THREAD

**Issue by tianleh** [opensearch-project/opensearch-build#2708]
### Describe the bug

From the CI of FTR https://github.com/opensearch-project/opensearch-dashboards-functional-test/actions/runs/3204452803/jobs/5235756954, we notice that `latest` 3.0.0 OSD failed to start due to 

```
{"type":"log","@timestamp":"2022-10-07T11:41:44Z","tags":["fatal","root"],"pid":2249,"message":"InvalidConfigurationError: Unknown configuration key(s): \"opensearch_security.multitenancy.enabled\", \"opensearch_security.multitenancy.tenants.preferred\", \"opensearch_security.readonly_mode.roles\", \"opensearch_security.cookie.secure\". Check for spelling errors and ensure that expected plugins are installed.\n    at ensureValidConfiguration (/home/runner/work/opensearch-dashboards-functional-test/opensearch-dashboards-functional-test/opensearch-dashboards-3.0.0/src/core/server/legacy/config/ensure_valid_configuration.js:53:11)\n    at Server.setup (/home/runner/work/opensearch-dashboards-functional-test/opensearch-dashboards-functional-test/opensearch-dashboards-3.0.0/src/core/server/server.js:182:5)\n    at Root.setup (/home/runner/work/opensearch-dashboards-functional-test/opensearch-dashboards-functional-test/opensearch-dashboards-3.0.0/src/core/server/root/index.js:44:14)\n    at bootstrap (/home/runner/work/opensearch-dashboards-functional-test/opensearch-dashboards-functional-test/opensearch-dashboards-3.0.0/src/core/server/bootstrap.js:128:5)\n    at Command.<anonymous> (/home/runner/work/opensearch-dashboards-functional-test/opensearch-dashboards-functional-test/opensearch-dashboards-3.0.0/src/cli/serve/serve.js:193:5) {\n  code: 'InvalidConfig',\n  processExitCode: 64,\n  cause: undefined\n}"}

 FATAL  Error: Unknown configuration key(s): "opensearch_security.multitenancy.enabled", "opensearch_security.multitenancy.tenants.preferred", "opensearch_security.readonly_mode.roles", "opensearch_security.cookie.secure". Check for spelling errors and ensure that expected plugins are installed.

```

This is the `latest` url https://ci.opensearch.org/ci/dbc/distribution-build-opensearch-dashboards/3.0.0/latest/linux/x64/tar/dist/opensearch-dashboards/opensearch-dashboards-3.0.0-linux-x64.tar.gz

This is what it resolves to `https://ci.opensearch.org/ci/dbc/distribution-build-opensearch-dashboards/3.0.0/4145/linux/x64/tar/dist/opensearch-dashboards/opensearch-dashboards-3.0.0-linux-x64.tar.gz`

### To reproduce

`wget https://ci.opensearch.org/ci/dbc/distribution-build-opensearch-dashboards/3.0.0/latest/linux/x64/tar/dist/opensearch-dashboards/opensearch-dashboards-3.0.0-linux-x64.tar.gz`

` tar -xzf opensearch-dashboards-3.0.0-linux-x64.tar.gz`

`  cd opensearch-dashboards-3.0.0`
`  bin/opensearch-dashboards serve`

**Comment by cliu123** [comment]
@tianleh Could you make sure security-dashboards-plugin has been installed in OpenSearch-Dashboards?

**Comment by tianleh** [comment]
> @tianleh Could you make sure security-dashboards-plugin has been installed in OpenSearch-Dashboards?

The artifact is not manually setup. It is from the infra's Jenkins build. 

Looks like security plugin is not in the manifest https://github.com/opensearch-project/opensearch-build/blob/main/manifests/3.0.0/opensearch-dashboards-3.0.0.yml But it has been added in the opensearch yml https://github.com/opensearch-project/opensearch-build/blob/main/manifests/3.0.0/opensearch-3.0.0.yml#L44

I think security team may need to add security OSD plugin to https://github.com/opensearch-project/opensearch-build/blob/main/manifests/3.0.0/opensearch-dashboards-3.0.0.yml @cliu123

**Comment by peternied** [comment]
This PR will resolve https://github.com/opensearch-project/opensearch-build/pull/2698

**Comment by rishabh6788** [comment]
Latest build job succeeded for 3.0.0 https://build.ci.opensearch.org/job/distribution-build-opensearch-dashboards/4148/

**Comment by tianleh** [comment]
Successfully run latest OSD 3.0.0 https://github.com/opensearch-project/opensearch-dashboards-functional-test/actions/runs/3208786242/jobs/5244953549 

`latest` resolves --2022-10-08 02:20:58--  https://ci.opensearch.org/ci/dbc/distribution-build-opensearch-dashboards/3.0.0/4148/linux/x64/tar/dist/opensearch-dashboards/opensearch-dashboards-3.0.0-linux-x64.tar.gz
