### ISSUE TITLE
Ignore plugin failure for OpenSearch snapshot artifact(s)

### ISSUE THREAD

**Issue by bbarani** [opensearch-project/opensearch-build#2716]
### Is your feature request related to a problem? Please describe

Currently the OpenSearch distribution job generates both -min, snapshot artifacts for components and distribution bundle for OpenSearch. The job fails completely and doesn't upload the -min distribution, snapshot artifacts as well when there is an issue with plugin build. 

### Describe the solution you'd like

Upload -min distribution, snapshot artifacts of successful builds even when there is any issue with plugin builds

**Comment by dblock** [comment]
I believe the original problem is about the availability of the -SNAPSHOT builds in Maven, more than -min. The -SNAPSHOT build of each component, including OpenSearch, should be uploaded after each component is built and not after all components are built. Other than OpenSearch we have common-utils, job-scheduler, etc., that all publish SNAPSHOTs to maven.

**Comment by bbarani** [comment]
@dblock We are looking in to this [issue](https://github.com/opensearch-project/opensearch-build/issues/441) to solve the dependencies between different components so we can fail the dependent components once the parent plugin fails and upload other components to maven.

**Comment by prudhvigodithi** [comment]
Since the related PR is merged https://github.com/opensearch-project/opensearch-build/pull/2717, can we proceed to close this?

**Comment by bbarani** [comment]
Closing this issue and the enhancement to skip plugin failures will be tracked in https://github.com/opensearch-project/opensearch-build/issues/441.
