### ISSUE TITLE
[On-boarding]: Neural Search plugin

### ISSUE THREAD

**Issue by jmazanec15** [opensearch-project/opensearch-build#2736]
### What is the name of your plugin?

neural-search

### What is the link to your GitHub repo?

https://github.com/opensearch-project/neural-search

### Targeted release version

2.4

### What type of the plugin are we on-boarding?

OpenSearch

### Does this plugin has all the necessary automated tests?

Integration tests: yes

BWC: Will be added after initial release.

### Have you completed the required reviews including Security reviews, UX reviews?

Yes or in progress

### Have you on-boarded automated security scanning for the GitHub repo associated with this plugin?

Unknown

### Additional context

Plugin extends k-NN plugin and has dependency on ml-commons client.

**Comment by peterzhuamazon** [comment]
Invited bot to this repo for automation.

**Comment by bbarani** [comment]
Closing this issue as we have released 2.4.0 version with neural plugin.
