### ISSUE TITLE
[On-boarding]: Security Analytics Dashboards plugin

### ISSUE THREAD

**Issue by amsiglan** [opensearch-project/opensearch-build#2740]
### What is the name of your plugin?

security-analytics-dashboards-plugin

### What is the link to your GitHub repo?

https://github.com/opensearch-project/security-analytics-dashboards-plugin

### Targeted release version

2.4.0

### What type of the plugin are we on-boarding?

OpenSearch-dashboards plugin

### Does this plugin has all the necessary automated tests?

Not yet, in progress

### Have you completed the required reviews including Security reviews, UX reviews?

Not yet, in progress.

### Have you on-boarded automated security scanning for the GitHub repo associated with this plugin?

We have below security policies enabled:
<img width="1124" alt="image" src="https://user-images.githubusercontent.com/114732919/195959201-e0a4e549-d84d-4e8d-9a57-12e33dac5f90.png">

https://github.com/opensearch-project/security-analytics-dashboards-plugin/security

### Additional context

This plugin is dependent on [security-analytics](https://github.com/opensearch-project/security-analytics) plugin

**Comment by bbarani** [comment]
@amsiglan, do we need to on-board security-analytics backend [repo](https://github.com/opensearch-project/security-analytics) as well? Please make sure to add the necessary parent plugins that needs to be on-boarded as part of this plugin.

**Comment by bbarani** [comment]
Closing this issue as we have released 2.4.0 version with Security Analytics Dashboards plugin.
