### ISSUE TITLE
[Bug]: How can we download the OpenSearch min artifacts for windows

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#2754]
### Describe the bug

_Note; this the windows platform specific security demo script_ https://github.com/opensearch-project/security/pull/2161

We are trying to setup builds and validation of OpenSearch for the Security Plugin, `./gradlew.bat build` functions on a windows machine, but need the minimum artifact, just like how they are obtained for linux with 

```
opensearch_version=`./gradlew properties -q | grep "opensearch_version:" | awk '{print $2}' | sed 's/-SNAPSHOT//g'`
wget https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/$opensearch_version/latest/linux/x64/tar/builds/opensearch/dist/opensearch-min-$opensearch_version-linux-x64.tar.gz
```

I assume there would be a pattern that would look something like the following.  Is there a url we can use to get these artifacts?

[1] Possible windows artifact pattern https://.ci.opensearch.org/ci/dbc/distribution-build-opensearch/$opensearch_version/latest/_windows/x64/zip/_builds/opensearch/dist/opensearch-min-$opensearch_version-_windows-x64.zip_

### Notes

I Inspected a recent 3.0.0 build, https://build.ci.opensearch.org/job/distribution-build-opensearch/6226/flowGraphTable/  Do not see a step where artifacts are uploaded.

**Comment by bbarani** [comment]
@peterzhuamazon has added the links to the -min artifacts [here](https://github.com/opensearch-project/opensearch-build/issues/33#issuecomment-1240033380)

**Comment by peternied** [comment]
Thanks @bbarani it looks like we can get https://artifacts.opensearch.org/snapshots/core/opensearch/2.4.0-SNAPSHOT/opensearch-min-2.4.0-SNAPSHOT-windows-x64-latest.zip can keep us unblocked.

I notice this is different than the previous urls we were using prefixed with `https://build.ci.opensearch.org/job/distribution-build-opensearch/`, should we broadly us one over the other?

**Comment by peternied** [comment]
FYI @scrawfor99 ^

**Comment by peterzhuamazon** [comment]
@peternied unblocked, link available now.
Thanks.

**Comment by peternied** [comment]
> I notice this is different than the previous urls we were using prefixed with https://build.ci.opensearch.org/job/distribution-build-opensearch/, should we broadly us one over the other?

Can we please keep this open until we have an answer to this question?

**Comment by dblock** [comment]
Agreed, I'll reopen.

**Comment by gaiksaya** [comment]
Hi @peternied, the snapshots are accessible via artifacts.opensearch.org. However for other components like plugin zips, etc [https://build.ci.opensearch.org/job/](https://build.ci.opensearch.org/job/distribution-build-opensearch/) was used. 
More details in README https://github.com/opensearch-project/opensearch-build/blob/main/README.md#min-snapshots

**Comment by peternied** [comment]
Thanks @gaiksaya, glad to see this is documented!  According to the documentation there are two different ways to get artifacts, Latest Distribution Url vs Min Snapshots.  Are these functionality the same, or are there considerations teams should have to use one vs the other?

**Comment by gaiksaya** [comment]
The [latest distribution url ](https://github.com/opensearch-project/opensearch-build/blob/main/README.md#latest-distribution-url) is more towards distribution artifacts like tarballs, zips, manifest where as the [Min Snapshots](https://github.com/opensearch-project/opensearch-build/blob/main/README.md#min-snapshots) only focuses on min artifact will always be latest as it gets overridden in each run. I hope this helps.

**Comment by peternied** [comment]
Cool, so it seems like for our build processes we should use the latest distribution url.  It looks like the windows build isn't being published to that bucket.  Can we use this issue to track that we need to update the build process to mirror the linux builds that are being published

**Comment by peterzhuamazon** [comment]
> Cool, so it seems like for our build processes we should use the latest distribution url. It looks like the windows build isn't being published to that bucket. Can we use this issue to track that we need to update the build process to mirror the linux builds that are being published

It is already published as part of the bundle build.
The artifacts path is more of a old method before ci being introduced.

**Comment by peternied** [comment]
Does that mean there is a modification to the following URL that will get the latest windows build? https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/3.0.0/6234/windows/x64/zip/builds/opensearch/dist/opensearch-min-3.0.0-windows-x64.zip

Could you help me figure out what that url is?

**Comment by bbarani** [comment]
@peternied it should follow the below format but it looks like we don't have successful full distribution build for 3.0 yet but the below URL works for 2.3.1 at this point in time. @peterzhuamazon can you please confirm?

https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/2.3.1/latest/windows/x64/zip/dist/opensearch/opensearch-2.3.1-windows-x64.zip

**Comment by peternied** [comment]
@scrawfor99 Checkout the most recent comment [1] to see how we can get the current windows build url

[1] https://github.com/opensearch-project/opensearch-build/issues/2754#issuecomment-1286244248

**Comment by peternied** [comment]
Issue seems resolved for me, thanks for all the help tracking this down
