### ISSUE TITLE
Validate the OpenSearch distribution artifacts on DockerHub and ECR

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/opensearch-build#2759]
Acceptance Criteria:

DockerHub and ECR images need below validations:
* Pull the image
* Validate docker digest/SHA/layers
* Use docker-compose to bring up the cluster
* Run basic apis against the above cluster

**Comment by jordarlu** [comment]
After reviewing the objective with the team, the step#2 'Validate docker digest/SHA/layers' shall cover the following  : 
1. Validating the digest between 'opensearchstaging/opensearch' and 'opensearchproject/opensearch'
2. Validating the digest between 'opensearchstaging/opensearch-dashboards and opensearchproject/opensearch-dashboards'

The expectation is the digest of 'opensearchproject' matching with 'opensearchstaging'

**Comment by jordarlu** [comment]
Close issue as PR was merged. Thanks
