### ISSUE TITLE
[Bug]: Wrong timeouts and resource leaks for longevity tests

### ISSUE THREAD

**Issue by kotwanikunal** [opensearch-project/opensearch-build#2768]
### Describe the bug

Performance tests currently have a [timeout of 15 hrs](https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/opensearch/perf-test.jenkinsfile#L9) which is not enough for longevity tests which take longer to complete, given the nature of the tests.

The tests are run using a client for opensearch-benchmarks, the server for which is outside the the boundaries of the Jenkins environment. The test still continues to run, but the tracking Jenkins job exits. 

This leads to resource leaks since the termination code path is not encountered [Ref 1](https://github.com/opensearch-project/opensearch-build/blob/main/src/test_workflow/perf_test/perf_test_cluster.py#L98-L102) [Ref 2](https://github.com/opensearch-project/opensearch-build/blob/main/src/test_workflow/perf_test/perf_test_cluster.py#L135)

### To reproduce

Execute a longevity performance test on Jenkins for any OpenSearch distribution.

### Expected behavior

- Tests should complete successfully
- Cluster should be cleaned up post test completion

### Relevant log output

```shell
INFO:root:Test execution id: 09321616-7388-450e-9318-f791679f9231, status: RUNNING
Cancelling nested steps due to timeout

https://build.ci.opensearch.org/job/perf-test/984/console
```

**Comment by rishabh6788** [comment]
@kotwanikunal would increasing the timeout value on jenkins side help resolve this problem? If yes, what should be the ideal timeout value to make sure the jobs are run completely.

**Comment by kotwanikunal** [comment]
> @kotwanikunal would increasing the timeout value on jenkins side help resolve this problem? If yes, what should be the ideal timeout value to make sure the jobs are run completely.

We can increase it to the length of longevity tests, which would be an easy fix. The only caveat is that the test takes roughly 13 days to complete the test. I checked test execution `7ebb4afb-e7d6-4e62-b237-472795b5f7c9`.

**Comment by bbarani** [comment]
Closing this issue as we have increased the timeout to 15 days now.

**Comment by gaiksaya** [comment]
The performance testing issues for leaky resources was solved by increasing the timeout: https://build.ci.opensearch.org/job/perf-test/2295/
It took 12 days to complete the longetivity tests and the run was successful which means resources were destroyed/terminated as well.
