### ISSUE TITLE
[Bug]: gradle-check action ran for different PR

### ISSUE THREAD

**Issue by andrross** [opensearch-project/opensearch-build#2782]
### Describe the bug

I submitted a revision to PR [4869](https://github.com/opensearch-project/OpenSearch/pull/4869) which appeared to trigger a gradle check action [5204](https://build.ci.opensearch.org/job/gradle-check/5204/). This [reported a failure in my PR](https://github.com/opensearch-project/OpenSearch/pull/4869#issuecomment-1287264211), but that gradle check action was actually for a [different PR](https://github.com/opensearch-project/OpenSearch/pull/4832) and ran against a different commit, leading to quite a lot of confusion. Seems like maybe a race condition?

More details here: https://github.com/opensearch-project/OpenSearch/pull/4869#issuecomment-1287320731

### To reproduce

Probably requires two PR submitting changes nearly simultaneously? Not sure how to deterministically reproduce.

### Expected behavior

The gradle check action should run against my commit in my PR, not a different commit.

**Comment by peterzhuamazon** [comment]
It is possible that it is a race condition tho I have not seen such cases happen until this point.
Will need to keep this open for a while as this might be a very rare case.

Thanks.

**Comment by andrross** [comment]
I just observed a similar problem, but in this case it wasn't a PR workflow and instead was the gradle check that runs on merge. See [this commit](https://github.com/opensearch-project/OpenSearch/commit/1cdff3bffa28f9bd98fa4a28207a8a06d33630c7). The little red `x` links to [this GitHub Action Workflow](https://github.com/opensearch-project/OpenSearch/actions/runs/4198401713/jobs/7281976501), which links to [this gradle check jenkins run](https://build.ci.opensearch.org/job/gradle-check/11249/consoleFull), which shows that it ran for an entirely [different commit on a user fork](https://github.com/sandeshkr419/OpenSearch/commit/d3df6eec65ac117fcf6fb292cd87cd85272f5f4a)

**Comment by jordarlu** [comment]
Hi, I am cloing this issue as it has been a while with no further updating from all stack holders in case... pls feel free to re-open or create a new one if you face the same issue ... thanks,
