### ISSUE TITLE
[On-boarding]: search-relevance plugin for reranking results

### ISSUE THREAD

**Issue by macohen** [opensearch-project/opensearch-build#2784]
### What is the name of your plugin?

Search Query & Result Transformer (fka search-relevance)

### What is the link to your GitHub repo?

https://github.com/opensearch-project/search-processor

### Targeted release version

2.6.0

### What type of the plugin are we on-boarding?

OpenSearch

### Does this plugin has all the necessary automated tests?

Not yet. https://github.com/opensearch-project/search-processor/issues/46

### Have you completed the required reviews including Security reviews, UX reviews?

Feature brief was completed on 2022-10-20. 

### Have you on-boarded automated security scanning for the GitHub repo associated with this plugin?

Yes

### Additional context

We are going to release this plugin as its own docker image, include instructions to self-install, and push the inclusion in the distribution until 2.5.0. We do need backport to work for this repo and a review for other onboarding.

**Comment by zelinh** [comment]
This PR should be part of the onboarding for WhiteSource GitHub integration. 
https://github.com/opensearch-project/dashboards-search-relevance/pull/49

**Comment by gaiksaya** [comment]
Added the secrets required for backport workflows in above repositories.

**Comment by gaiksaya** [comment]
Closing this issue. Search relevance was successfully onboarded
