### ISSUE TITLE
[On-boarding]: Search Comparison UI

### ISSUE THREAD

**Issue by macohen** [opensearch-project/opensearch-build#2785]
### What is the name of your plugin?

dashboards-search-relevance

### What is the link to your GitHub repo?

https://github.com/opensearch-project/dashboards-search-relevance

### Targeted release version

2.4.0

### What type of the plugin are we on-boarding?

OpenSearch-dashboards

### Does this plugin has all the necessary automated tests?

Not yet. Still under development. 

### Have you completed the required reviews including Security reviews, UX reviews?
Security review completed.

UX Review completed on 2022-10-20.

### Have you on-boarded automated security scanning for the GitHub repo associated with this plugin?

No. 

### Additional context

This will be released as an experimental plugin.

**Comment by macohen** [comment]
We want to create two plug-ins and both started as forks of this repo before the one plugin per repo standard was created. This plugin will go into a new repo which has a request for creation in process. The other plugin will end up in the search-relevance repo. That is request #2784.

**Comment by dblock** [comment]
Thanks @macohen. I was confused by the GitHub link above. Edit the issue per naming convention pls.

**Comment by macohen** [comment]
Got it. Thanks for the feedback. If I understand the instructions correctly, I just updated the name of the plugin to dashboards-results-comparison. We'll handle changes to support conventions inside the repo.

**Comment by bbarani** [comment]
Closing this issue as we have released 2.4.0 version with Search Comparison UI plugin.
