### ISSUE TITLE
Cleanup 1.0 automation tools

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#279]
**Is your feature request related to a problem? Please describe.**

Can these be deleted? What else can be deleted?

**Describe the solution you'd like**

Delete the following:

https://github.com/opensearch-project/opensearch-build/blob/main/manifests/manifest.linux.x64.example.yml
https://github.com/opensearch-project/opensearch-build/blob/main/manifests/manifest.linux.x64.example.yml
https://github.com/opensearch-project/opensearch-build/blob/main/.github/workflows/check-vulnerability-whitesource.yml

**Comment by dblock** [comment]
@peterzhuamazon Maybe you can help us identifying what's used and what's not used anymore?

**Comment by peterzhuamazon** [comment]
@gaiksaya 
https://github.com/opensearch-project/opensearch-build/blob/main/manifests/manifest.linux.x64.example.yml
https://github.com/opensearch-project/opensearch-build/blob/main/manifests/manifest.linux.x64.example.yml

@dblock 
 https://github.com/opensearch-project/opensearch-build/blob/main/.github/workflows/check-vulnerability-whitesource.yml
Please leave this as it be as @zelinh will need it to check out whitesource.

**Comment by dblock** [comment]
> @dblock
> https://github.com/opensearch-project/opensearch-build/blob/main/.github/workflows/check-vulnerability-whitesource.yml
> Please leave this as it be as @zelinh will need it to check out whitesource.

This was deleted in https://github.com/opensearch-project/opensearch-build/pull/295 as it was disabled. Anyone can put it back when we start running it again.

**Comment by peternied** [comment]
[Triage] these files have been removed
