### ISSUE TITLE
[On-boarding]: Opensearch-py-ml plugin

### ISSUE THREAD

**Issue by dhrubo-os** [opensearch-project/opensearch-build#2803]
### What is the name of your plugin?

opensearch-py-ml

### What is the link to your GitHub repo?

https://github.com/opensearch-project/opensearch-py-ml

### Targeted release version

2.4, but flexible to extend as this is python client, not a part of OpenSearch release artifact 

### What type of the plugin are we on-boarding?

Opensearch plugin. A python client to connect with opensearch and ml-commons plugin.

### Does this plugin has all the necessary automated tests?

YES. This plugin depends on the functionality which will be release in 2.4 so no need to have BWC tests.

### Have you completed the required reviews including Security reviews, UX reviews?

Appsec review is ongoing:

### Have you on-boarded automated security scanning for the GitHub repo associated with this plugin?

Yeah we need to enable automated CVE scanning on this repo.

**Comment by rishabh6788** [comment]
@dhrubo-os I assume this is a stand-alone component and doesn't need to be bundled with opensearch.

**Comment by dhrubo-os** [comment]
Yeah, it doesn't need to be bundled with opensearch.

**Comment by dhrubo-os** [comment]
closing this issue in favor of : https://github.com/opensearch-project/opensearch-build/issues/2814
