### ISSUE TITLE
[BUG] Data Prepper Workflow will still copy image to `latest` when `RELEASE_LATEST_TAG` is not checked

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#2815]
Hi,

The workflow has some bugs that even if `latest` is off 1.5.2 still copied to latest.

https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/data-prepper/release-data-prepper-all-artifacts.jenkinsfile

@rishabh6788 @zelinh 
https://build.ci.opensearch.org/job/release-data-prepper-all-artifacts/26/

I suspect the `Major` tag have the same issue.

Thanks.

**Comment by zelinh** [comment]
I think I know what's wrong here. 
https://github.com/opensearch-project/opensearch-build/blob/2fe6e745ab9c6ae09b91e5c00bd8800dc0b6caa3/jenkins/data-prepper/release-data-prepper-all-artifacts.jenkinsfile#L98
We are having the condition check with just the `RELEASE_LATEST_TAG` or `RELEASE_MAJOR_TAG` inside the if statement bracket, this would also be true as Jenkins considers it as string. 
We could either use `params.RELEASE_LATEST_TAG` or `RELEASE_LATEST_TAG.toBoolean()` to specify it as boolean parameter. I would take care of it now.
