### ISSUE TITLE
Validate the artifact(s) signatures

### ISSUE THREAD

**Issue by bbarani** [opensearch-project/opensearch-build#2858]
Currently we do not have mechanism to automatically validate the signatures for artifacts published on opensearch.org.
We need a mechanism to do so.

Details on how to verify the signatures: https://opensearch.org/verify-signatures.html
### Acceptance Criteria
- [ ] Validate the urls of the signatures `.sig` files.
- [ ] Import the keys and validate the signature
- [ ] Check if the key is not expired

**Comment by gaiksaya** [comment]
Hi @bbarani,

Signature is validated as a part of signing system. https://github.com/opensearch-project/opensearch-build/blob/main/src/sign_workflow/signer_pgp.py#L72-L74
This applies to all signing platforms. 
The code will fail if the verification fails.

Do we want another check again to validate them?

Thanks!

**Comment by Divyaasm** [comment]
One Idea is to make signature validation optional using a seperate parameter, so that it can be used only when required especially during releases.

**Comment by bbarani** [comment]
@gaiksaya @Divyaasm We don't need another verification if the signature is already validated as part of signer code. Lets make sure that all the distribution types including Mac and Windows are covered here though.

**Comment by gaiksaya** [comment]
Yes they are covered:
Windows: https://github.com/opensearch-project/opensearch-build/blob/main/src/sign_workflow/signer_windows.py#L50-L52
Mac: https://github.com/opensearch-project/opensearch-build/blob/main/src/sign_workflow/signer_mac.py#L50-L55

**Comment by Divyaasm** [comment]
Closing the issue as the Signature Verification is done as part of Signer Code for all the Distributions and platforms
