### ISSUE TITLE
[Enhancement] Add Release Bundle Build Workflow to CI

### ISSUE THREAD

**Issue by cliu123** [opensearch-project/opensearch-build#2866]
The utils used in both `/public` folder and `/server` folder need to be declared in `/common` folder. Otherwise, the release bundle build would throw `Error: Cannot find module...`. These errors do not surface up till the release build so there is no effective way to catch them in development stage.

**Is your enhancement request related to a problem?**
The request comes from https://github.com/opensearch-project/security-dashboards-plugin/issues/1175.

**What solution would you like?**
Add release bundle workflow to CI

**What alternatives have you considered?**
We should introduce a CI worfklow to run this workflow to fail early.

**Comment by gaiksaya** [comment]
[Triage] Hi @cliu123 ,

We are already [creating issues](https://github.com/opensearch-project/opensearch-build/issues/1899) for build failures in respective component repos. Example: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3030
Regarding frequent builds, the builds are run once per day. For upcoming release, its once per hour.

Is there something else that is expected that I am missing?

**Comment by jordarlu** [comment]
Closing this old issue as we have feature in place.
