### ISSUE TITLE
[Broken CI] `main` builds blocked due to 2.5.0 not being available 

### ISSUE THREAD

**Issue by DarshitChanpura** [opensearch-project/opensearch-build#2868]
All current PRs to main, in security plugin, are broken due to unavailability of 2.5.0 which is blocking CI.

Reference issue: https://github.com/opensearch-project/security/issues/2221

**Comment by zelinh** [comment]
We haven't initiate our build for 2.5 as we don't currently have the manifest for 2.5. We are trying to resolve some of the issues on our side so we could get it started. 
https://github.com/opensearch-project/opensearch-build/issues/2854

**Comment by peternied** [comment]
@zelinh Any update? This is blocking our main builds in Security from executing BWC tests that pass.

**Comment by peternied** [comment]
@opensearch-project/engineering-effectiveness  We cannot complete the release issues for 2.4.0 which requires we have updated our plugins 2.x branches to the 2.5.0 build.

**Comment by zelinh** [comment]
@peternied We should be now having the build for 2.5.0 min artifact.

**Comment by peternied** [comment]
CI is starting to pass [1], we are able to build against 2.5.0 - thanks @zelinh !

[1] https://github.com/opensearch-project/security/pull/2249

**Comment by bbarani** [comment]
Closing this issue as 2.5.0 builds are available now.
