### ISSUE TITLE
[RELEASE] Ruby Gem "opensearch-aws-sigv4" version 1.0.0 (First release)

### ISSUE THREAD

**Issue by nhtruong** [opensearch-project/opensearch-build#2875]
### Is your feature request related to a problem? Please describe

We're adding Sigv4 Support for Ruby client in the form of a new ruby gem called `opensearch-aws-sigv4`

Issue: https://github.com/opensearch-project/opensearch-ruby/issues/71
Pull Request: https://github.com/opensearch-project/opensearch-ruby/pull/110

### Describe the solution you'd like

Release `opensearch-aws-sigv4` gem to https://rubygems.org/

**Comment by gaiksaya** [comment]
Hi @nhtruong Can you use, https://github.com/opensearch-project/opensearch-build/issues/new?assignees=&labels=release%2Cuntriaged&template=standalone_releases_template.yaml&title=%5Brelease%5D%3A+ template to create an issue?
This helps us to understand other aspects of release including dates, checks, etc. 

Thanks!
