### ISSUE TITLE
[Bug]: Investigate performance degradation between 2.3.0 and 2.4.0 version

### ISSUE THREAD

**Issue by bbarani** [opensearch-project/opensearch-build#2888]
### Describe the bug

Performance test results showed increase of indexing latency in 2.4.0 version compared to 2.3.0 version as listed [here](https://github.com/opensearch-project/opensearch-build/issues/2649#issuecomment-1314333731).  We need to identify the root cause if the degradation ( i.e. Is the degradation caused due to perf tool setup OR related to OpenSearch core changes)

### To reproduce

The results are published in 2.4.0 release [issue](https://github.com/opensearch-project/opensearch-build/issues/2649#issuecomment-1314333731)

**Comment by anasalkouz** [comment]
I can see the latency increased on 2.4 on 10/21/2022. @adnapibar may be Rabi if we can see what was merged on that date.

![Screen Shot 2022-11-14 at 3 30 05 PM](https://user-images.githubusercontent.com/25317259/201789443-6901ff03-8ab1-4c78-8a6b-44bdff54f0fe.png)

**Comment by adnapibar** [comment]
Doesn't look like any significant change 
![image](https://user-images.githubusercontent.com/2838888/201790277-da700c3e-f8cc-4de6-8332-635061a5562d.png)

**Comment by adnapibar** [comment]
Do we know why there is a significant difference in the p99 between the perf tests ran today vs 11/10? 
e.g. OpenSearch 2.3.0 vs 2.4.0 Linux (With security): 1.66% (11/10) vs -42.42% (today)

**Comment by andrross** [comment]
The NYC taxis dataset does define a couple [geo_point data types](https://github.com/opensearch-project/opensearch-benchmark-workloads/blob/main/nyc_taxis/index.json#L74). This change to [add support for GeoJSON](https://github.com/opensearch-project/OpenSearch/commit/050389736599e40c49278e900d5060f75b959282) was backported to the 2.x branch on October 21, so it lines up with the regression. @heemin32 is there any chance this change resulted in a performance regression during indexing?

The throughput graph shows the change in performance a little more clearly, in my opinion:

![Screen Shot 2022-11-14 at 5 04 40 PM](https://user-images.githubusercontent.com/9160839/201801477-b365cf6d-d87b-469f-9b54-6251fa2dc95e.png)

**Comment by navneet1v** [comment]
The change in question defines a new way of inputting the geo point. It doesn't make any change in the indexing.

**Comment by heemin32** [comment]
The change include creation of XContent for array format so that it can be extendible by plugin correctly. This might have caused the index delay for point data in array format.

https://github.com/opensearch-project/OpenSearch/commit/a282d399225247226d5abc3e3cd903462c973877

**Comment by heemin32** [comment]
NYC taxis dataset contains geopoint in array format. I suspect the degradation is from the change that I made in [AbstractPointGeometryFieldMapper.java](https://github.com/opensearch-project/OpenSearch/commit/050389736599e40c49278e900d5060f75b959282#diff-4ca9b742104d223b833a8dc0028f62e91bc66569a5f0688fde997b846c10f81b). 

Instead of reverting the entire commit, I am going to revert the change in `AbstractPointGeometryFieldMapper.java` which shouldn't impact on existing functionality.

**Comment by bbarani** [comment]
Closing this issue as we found the root cause of the degradation. You can view more info on this [PR](https://github.com/opensearch-project/OpenSearch/pull/5249)
