### ISSUE TITLE
[release]: opensearch sql cli 1.1.0

### ISSUE THREAD

**Issue by penghuo** [opensearch-project/opensearch-build#2898]
### What is the name of your component?

opensearchsql cli

### What is the link to your GitHub repo?

https://github.com/opensearch-project/sql/tree/2.4/sql-cli

### Targeted release date

11/23

### Where should we publish this component?

https://pypi.org/project/opensearchsql/

### What type of artifact(s) will be generated for this component?

https://pypi.org/project/opensearchsql/

### Have you completed the required reviews including security reviews, UX reviews?

yes.

### Have you on-boarded automated security scanning for the GitHub repo associated with this component?

yes.

**Comment by gaiksaya** [comment]
Hi @penghuo ,

Thanks for creating this issue. We would like to automate this release. Details in this [issue](https://github.com/opensearch-project/opensearch-build/issues/1234). 
Quick question: How are release tags managed for this component in sql repo?

**Comment by penghuo** [comment]
we did not define release tag for component.

**Comment by penghuo** [comment]
can we onboarding the automated release now?

**Comment by gaiksaya** [comment]
Yes. As mentioned in the above design diagram, the release needs to be based on tag as a trigger.

**Comment by gaiksaya** [comment]
You can check https://github.com/opensearch-project/opensearch-ruby repo as an example on how to release artifacts  with multiple components. 
Let me know the details so that we can proceed with automation.

**Comment by gaiksaya** [comment]
Hi @penghuo Can you update the issue with new repo links and estimated date of release? Looks like the repo was split.
Thanks!

**Comment by gaiksaya** [comment]
Closing this as no response from the requester, Please re-open if and when we need to proceed.
Thanks!
