### ISSUE TITLE
[Bug]: Manifests workflow failing

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#2904]
### Describe the bug

```
Error when evaluating 'strategy' for job 'manifest-checks-jdk11'. .github/workflows/manifests.yml (Line: 41, Col: 19): Error parsing fromJson,.github/workflows/manifests.yml (Line: 41, Col: 19): Error reading JToken from JsonReader. Path '', line 0, position 0.,.github/workflows/manifests.yml (Line: 41, Col: 19): Unexpected type of value '', expected type: Sequence.
```

https://github.com/opensearch-project/opensearch-build/actions/runs/3474030907

### To reproduce

https://github.com/opensearch-project/opensearch-build/actions/runs/3474030907

**Comment by gaiksaya** [comment]
This is fixed now. Issue was set-ouput command was replaced incorrectly. It was fixed in #2903
