### ISSUE TITLE
[Bug]: Cron created by manifest workflow doesn't have build_platform parameter

### ISSUE THREAD

**Issue by zelinh** [opensearch-project/opensearch-build#2912]
### Describe the bug

Our manifest workflow will help us create input manifest and add the build job to our cron once we have a new version from OS or OSD core. e.g. #2894 

However since we start to build for different platform distribution, we would need to add build_platform parameters to trigger the build workflow which our current manifest workflow doesn't have. We would need to manually add the param to the cron in order to trigger it. #2911 

### To reproduce

When we have a new OS or OSD version, run `./manifest.sh update`

### Expected behavior

When the workflow raise the PR, it should also add this param to the cron. For different job type(OS or OSD), it would also add different platform parameter. e.g. for OS it should be `BUILD_PLATFORM=linux macos windows` but for OSD it's `BUILD_PLATFORM=linux windows`

**Comment by dblock** [comment]
Should the scripts default to the full list of platforms instead?

**Comment by zelinh** [comment]
> Should the scripts default to the full list of platforms instead and only have to specify which platforms to build when it's not all 3?

Yes. In my PR raised, the platform will be default to be all 3 if not specified in the map.

**Comment by gaiksaya** [comment]
Closed via #2919
