### ISSUE TITLE
Revert component-based scripts lookup

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#2945]
### Is your feature request related to a problem? Please describe

In https://github.com/opensearch-project/opensearch-build/pull/2934 we have added a way to include component build scripts. There are several problems with that.

1. In https://github.com/opensearch-project/opensearch-build/issues/2188 we agreed to split monorepos. The maps monorepo came in as another new kind of monorepo that should not be supported. 
2. There are no tests in the PR.
3. The new feature of path lookup is not documented in https://github.com/opensearch-project/opensearch-build/blob/cbe6841a3c459b65d5fb17b713994e5c01d7ee8e/src/paths/script_finder.py#L27

### Describe the solution you'd like

1. Add tests and documentation on top of https://github.com/opensearch-project/opensearch-build/pull/2934.
1. Split the maps monorepo, https://github.com/opensearch-project/opensearch-build/issues/2188
1. Revert https://github.com/opensearch-project/opensearch-build/pull/2934

**Comment by gaiksaya** [comment]
[Triage] Hi @junqiu-lei Any plans on separating the repos?

**Comment by junqiu-lei** [comment]
Hi @gaiksaya , will take actions based on decision from https://github.com/opensearch-project/dashboards-maps/issues/95

**Comment by bbarani** [comment]
@junqiu-lei @gaiksaya Can you provide an update on this issue?

**Comment by gaiksaya** [comment]
I believe this PR took care of adding tests and documentation: https://github.com/opensearch-project/opensearch-build/pull/2952
These are the components in build repo that still have scripts here: https://github.com/opensearch-project/opensearch-build/tree/main/scripts/components

**Comment by junqiu-lei** [comment]
I'll raise a PR for the revert of https://github.com/opensearch-project/opensearch-build/pull/2952
