### ISSUE TITLE
Insufficient memory for windows gradle check on core

### ISSUE THREAD

**Issue by Poojita-Raj** [opensearch-project/opensearch-build#2966]
### Describe the bug

For opensearch core, gradle check on windows CI results in OOM errors due to the insufficient memory allocated for the windows agent on Jenkins. 

Here's the links to the Jenkins runs with memory failures:

https://build.ci.opensearch.org/job/gradle-check/7512
https://build.ci.opensearch.org/job/gradle-check/7511
https://build.ci.opensearch.org/job/gradle-check/7504

### To reproduce

Run gradle check on windows for 1.3 or 1.x branches. 

### Expected behavior

For gradle check to pass, this is a request to increase the memory allocated for the CI runner in order to get a full gradle check without any failures due to insufficient memory (since windows is limited at 32gb currently).

**Comment by peterzhuamazon** [comment]
Will try to add more memory to WINRM consumption.
Set to 30270 from 10240 MB per connection.

Thanks.
