### ISSUE TITLE
A workflow to forward port changes to main branch.

### ISSUE THREAD

**Issue by amitgalitz** [opensearch-project/opensearch-build#2978]
### Is your feature request related to a problem? Please describe

Since plugins have transitioned to follow the same branching mechanisms that is utilized by core, we have seen increased scenarios where our main branch is broken while we are working on time-sensitive PRs for the latest minor version release (ex: 2.4).

This means that are sometimes developing against the 2.x branches instead of main which we have in the past. In such cases we then need to forward port our changes to main branch so its also included in the future 3.0 release. 

### Describe the solution you'd like

We have already added a workflow in the past to allow adding labels such as `backport 2.4` to backport changes to different branches after they merge. Would it be possible to add a label such as `forward-port main` or `port main` to create automatic PRs to merge our changes to main branch after we have merged to 2.x branch. If some changes have conflicts then we can either open our own PRs or make changes to the current PR opened by the bot (not sure if this is possible).

This can save some development time the same adding the backport label has saved development time for us.

**Comment by gaiksaya** [comment]
[Triage] Tagging @bbarani to add comments here.

**Comment by bbarani** [comment]
@VachaShah Do you have any inputs on implementing forward port workflow similar to backport?

**Comment by bbarani** [comment]
@VachaShah Do you have any inputs here?

**Comment by gaiksaya** [comment]
I recently saw a label `backport main` (sorry cannot recollect in which repo) that port the changes to main branch. I believe the tool does its job of porting the changing from one commit to specified branch whether it is backport or port.
@amitgalitz Did you try that?

**Comment by VachaShah** [comment]
> @VachaShah Do you have any inputs here?

Hi @bbarani, sorry I missed this! For the scenario that @amitgalitz is describing, if the backport workflow is present on the 2.x branch, you can add a label `backport main` to the PR and it will cherry-pick the changes into a PR towards the main branch. Similar to what @gaiksaya has mentioned above. It will work in the same way as backports work now.

**Comment by bbarani** [comment]
@amitgalitz Did you try the suggestion by @gaiksaya ?

**Comment by gaiksaya** [comment]
This is being used in multiple repositories now. Example: https://github.com/opensearch-project/k-NN/pulls?q=is%3Apr+label%3A%22backport+main%22+is%3Aclosed

Please give it a try and let us know.

Closing this issue! Please re-open if issue still persist.

Thanks!
