### ISSUE TITLE
OpenSearch / OpenSearch Dashboards Multi-Arch Docker image (X64 + ARM64)

### ISSUE THREAD

**Issue by bbarani** [opensearch-project/opensearch-build#30]
Is your feature request related to a problem? Please describe.
No

Describe the solution you'd like
Provide (ARM64)Docker images via DockerHub for OpenSearch / OpenSearch Dashboards (With plugins)

Describe alternatives you've considered
Generating the image using the source code

Additional context
Currently there are no (ARM) Docker images for OpenSearch / OpenSearch Dashboards

**Comment by peterzhuamazon** [comment]
Both x64 and arm64 version of OpenSearch/Dashboards should co-exist as layers.
Will use docker buildx to achieve this.

**Comment by peterzhuamazon** [comment]
Voting for Release: https://github.com/opensearch-project/opensearch-build/issues/105
