### ISSUE TITLE
[release]: Publish opensearch-sdk-java SNAPSHOTs to Maven

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/opensearch-build#3011]
### What is the name of your component?

`opensearch-sdk-java`

### What is the link to your GitHub repo?

https://github.com/opensearch-project/opensearch-sdk-java

### Targeted release date

Q1 2023

### Where should we publish this component?

Maven

### What type of artifact(s) will be generated for this component?

Jars, and XML config.

### Have you completed the required reviews including security reviews, UX reviews?

No, we'd like to publish SNAPSHOTs and we'll take go through the review process when we are ready to release. 

### Have you on-boarded automated security scanning for the GitHub repo associated with this component?

Yes: Mend Renovate
https://github.com/opensearch-project/opensearch-sdk-java/pull/256

### Additional context

**What are we looking for?**
We'd like the SNAPSHOTS to be published nightly. 

Here is how the artifacts look like:
```
%> ls
maven-metadata-local.xml			opensearch-sdk-java-1.0.0-SNAPSHOT.module
opensearch-sdk-java-1.0.0-SNAPSHOT.jar		opensearch-sdk-java-1.0.0-SNAPSHOT.pom
vemsarat@3c22fb88f11c 1.0.0-SNAPSHOT % 

```

cc: @rishabh6788

**Comment by dblock** [comment]
Reading https://github.com/opensearch-project/opensearch-build/issues/1182#issuecomment-1353709327 it seems like we no longer need to do anything in opensearch-build to enable that?

**Comment by bbarani** [comment]
@gaiksaya I am good with using GHA to publish snapshots.

**Comment by gaiksaya** [comment]
I am working on setting up the infra for this process. 
Update is same as here https://github.com/opensearch-project/opensearch-build/issues/1182#issuecomment-1363427482

@saratvemulapalli Can you or someone confirm that the mentioned gradle task `./gradlew publishAllPublicationsToSnapshotsRepository` will take care of publishing snapshots to maven? More details in the issue description mentioned above.
Thanks!

**Comment by gaiksaya** [comment]
Hi @saratvemulapalli ,

I also do not see any task to publish on Maven under sdk-java project:
```
Publishing tasks
----------------
generateMetadataFileForMavenJavaPublication - Generates the Gradle metadata file for publication 'mavenJava'.
generatePomFileForMavenJavaPublication - Generates the Maven POM file for publication 'mavenJava'.
publish - Publishes all publications produced by this project.
publishMavenJavaPublicationToMavenLocal - Publishes Maven publication 'mavenJava' to the local Maven repository.
publishToMavenLocal - Publishes all Maven publications produced by this project to the local Maven cache.
``` 
Let me know what command needs to be used. Thanks!

**Comment by saratvemulapalli** [comment]
Thanks @gaiksaya. Looks like publish snapshot task is not available. Let me PR the change.

**Comment by gaiksaya** [comment]
The infrastructure set up is merged and ready to publish snapshots. Please update this issue once the gradle task is ready.
Thanks!

**Comment by saratvemulapalli** [comment]
@gaiksaya the PR[1] is up. You can use `publishAllPublicationsToSnapshotsRepository` task to publish to snapshots repo. I've put in sonatype creds as system variables. If you expect it differently let me know. 

[1] https://github.com/opensearch-project/opensearch-sdk-java/pull/311

**Comment by gaiksaya** [comment]
@saratvemulapalli I tried running the above task and as expected it failed due to lack of creds in my local. Question about the group id 

I see that it is trying to put the contents under `org.opensearch.opensearch-sdk-java`. Can you confirm if that is right? Or should it be something like `org.opensearch.sdk`?

```
./gradlew publishMavenJavaPublicationToSnapshotsRepository

> Task :compileJava
Note: /Users/gaiksaya/opensearch-project/sarat/src/main/java/org/opensearch/sdk/SDKClient.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :publishMavenJavaPublicationToSnapshotsRepository FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':publishMavenJavaPublicationToSnapshotsRepository'.
> Failed to publish publication 'mavenJava' to repository 'Snapshots'
   > Could not PUT 'https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/opensearch-sdk-java/1.0.0-SNAPSHOT/maven-metadata.xml'. Received status code 401 from server: Unauthorized

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

Thank!

**Comment by saratvemulapalli** [comment]
@gaiksaya thats a good question. I like `org.opensearch.sdk` as we would have more sdks coming along. 
I'll update the group id to be `org.opensearch.sdk` and it should publish to `'https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/sdk/opensearch-sdk-java/1.0.0-SNAPSHOT/`

**Comment by gaiksaya** [comment]
Can you also tell me what should be the [trigger](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows) for publishing the snapshots? Will add a workflow accordingly. 
Thanks!

**Comment by saratvemulapalli** [comment]
Lets do a cron, twice everyday?

**Comment by gaiksaya** [comment]
Sounds good. PR[1] raised for the same.
Thanks!

[1] https://github.com/opensearch-project/opensearch-sdk-java/pull/312

**Comment by gaiksaya** [comment]
Snapshots are live https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/sdk/opensearch-sdk-java/
Workflow: https://github.com/opensearch-project/opensearch-sdk-java/actions/runs/3888010406/jobs/6634902820
