### ISSUE TITLE
[On-boarding]: OpenSearch Search Request Processor

### ISSUE THREAD

**Issue by noCharger** [opensearch-project/opensearch-build#3018]
### What is the name of your plugin?

https://github.com/opensearch-project/search-processor/blob/main/build.gradle#L12

### What is the link to your GitHub repo?

https://github.com/opensearch-project/search-processor

### Targeted release version

2.5.0

### What type of the plugin are we on-boarding?

OpenSearch

### Does this plugin has all the necessary automated tests?

Not yet, need some guidence on this. (https://github.com/opensearch-project/search-processor/issues/46)

### Have you completed the required reviews including Security reviews, UX reviews?

Yes for all.

### Have you on-boarded automated security scanning for the GitHub repo associated with this plugin?

Yes, we have enabled dependabot
https://github.com/opensearch-project/search-processor/blob/main/.github/dependabot.yml

**Comment by macohen** [comment]
We also need backporting enabled with an APP_ID.

**Comment by macohen** [comment]
duplicates https://github.com/opensearch-project/opensearch-build/issues/2784
