### ISSUE TITLE
SQL & Observability Repo's split need build support for the new structure

### ISSUE THREAD

**Issue by YANG-DB** [opensearch-project/opensearch-build#3044]
### Is your feature request related to a problem? Please describe

Repository split as discussed here... 
See https://github.com/opensearch-project/sql/issues/640
See https://github.com/opensearch-project/observability/issues/803
See https://github.com/opensearch-project/opensearch-build/issues/2188

### Describe the solution you'd like

Recently the next changes have taken place to allow better utilization of the existing repositories

**SQL** was split into the following repos:
-  https://github.com/opensearch-project/sql  (remains but removed additional components)
 - https://github.com/opensearch-project/sql-jdbc
 - https://github.com/opensearch-project/sql-odbc
 - https://github.com/opensearch-project/sql-cli
 - https://github.com/opensearch-project/dashboards-query-workbench

**Observability** was split into the following repos:
-  https://github.com/opensearch-project/observability  (remains but removed additional components)
 - https://github.com/opensearch-project/dashboards-observability

**Reporting**  was split into the following repos:
 - https://github.com/opensearch-project/dashboards-reports (remains and rerouted to _../reporting_ with reduced functionality)
 - https://github.com/opensearch-project/dashboards-reporting
 - https://github.com/opensearch-project/reporting-cli

### Additional context

New plugins need to be build with the same composition as the former plugins assembed
- **SQL** (backend repo) 
  - sql-jdbc
  - sql-odbc
  - sql-cli
  - dashboards-query-workbench (frontend)

- **Observability** (backend repo) 
   - dashboards-observability (frontend)

- **Reporting** (backend repo) 
   - reporting-cli
   - dashboards-reporting (frontend)

**Comment by pjfitzgibbons** [comment]
As a clarification to build team :

The "backend" repos (those with no prefix - `observability`, `reporting` ) have been updated to remove the front-end section of the codebase.  These repos are likely actively failing builds right now.

The "frontend" repos `dashboards-observability`, `dashboards-reporting` are "new to you", and need to be checked for proper GH workflow steps as well as verify the now "alternate" artifact paths for front-end are accounted for in the build system.

**Comment by prudhvigodithi** [comment]
[Triage] Hey @YANG-DB @pjfitzgibbons we will get back on this after having a team level discussion.

**Comment by bbarani** [comment]
@prudhvigodithi Can we close this issue?

**Comment by prudhvigodithi** [comment]
Hey Closing this issue the 2.5.0 release is already done with the repo split and with new naming convention.
https://github.com/opensearch-project/opensearch-build/blob/main/manifests/2.5.0/opensearch-dashboards-2.5.0.yml#L25-L29.
@YANG-DB @pjfitzgibbons closing this issue, please reopen if you see any issue.
Thank you
