### ISSUE TITLE
Autocut issues for OpenSearch Windows CI failures

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/opensearch-build#3052]
**Is your feature request related to a problem? Please describe.**
Because of hardware limitations we are running windows CI's nightly for OpenSearch.
When the builds fails we dont report them today.

**Describe the solution you'd like**
I would like an autocut issue labelled windows and ci. 

**Additional Information**
Coming from: https://github.com/opensearch-project/OpenSearch/issues/5716

**Comment by saratvemulapalli** [comment]
@peterzhuamazon I am looking at the jenkins file which probably needs the change. I can pick up this work, is there a way to test it? 
https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/opensearch/distribution-build.jenkinsfile#L885

**Comment by bbarani** [comment]
@rishabh6788 Can you add your inputs?

**Comment by minalsha** [comment]
@bbarani , @rishabh6788  can you please take care of this issue on your end?

**Comment by minalsha** [comment]
following up on this since it has been over a month. Still waiting on input here, @rishabh6788 . Please update. Thanks

**Comment by bbarani** [comment]
@rishabh6788 Whats the status on this?

**Comment by bbarani** [comment]
Closing this issue as we do not have mechanism to broadcast notifications for Gradle check rather only for OpenSearch distributions ( including plugins). Please feel free to re-open if you have any other questions.
