### ISSUE TITLE
automatically increment bwc version

### ISSUE THREAD

**Issue by kaituo** [opensearch-project/opensearch-build#3063]
### Is your feature request related to a problem? Please describe

We need to bump the bwc version in every release (example: https://github.com/opensearch-project/anomaly-detection/pull/775) because only the latest N-1.x will be upgradable to N.0 (e.g., from 2.x to 3.0) when that ships. 

Known issue: https://github.com/opensearch-project/OpenSearch/issues/5076
latest development: https://github.com/opensearch-project/OpenSearch/issues/5091

### Describe the solution you'd like

Could you automate bumping bwc version similar to release version (e.g., https://github.com/opensearch-project/anomaly-detection/pull/774)?

**Comment by gaiksaya** [comment]
Hi @kaituo,

You can do that by updating the `updateVersion` task in your build.gradle file. You can tell the task what all it needs to update https://github.com/opensearch-project/anomaly-detection/blob/main/build.gradle#L793-L802

**Comment by zelinh** [comment]
I think we could use `opensearch_version` from gradle properties for this one. Our current version bump workflow is incrementing this version everytime and this is pretty much the same as the version used for bwc. Only difference I'm thinking right now would be the `-SNAPSHOT` suffix. 
I could elaborate this PR https://github.com/opensearch-project/anomaly-detection/pull/778 to accommodate the changes.

**Comment by prudhvigodithi** [comment]
Related open issue https://github.com/opensearch-project/opensearch-build/issues/2373

**Comment by bbarani** [comment]
@prudhvigodithi @zelinh Whats the next step to move forward?

**Comment by prudhvigodithi** [comment]
A solution added by k-nn team https://github.com/opensearch-project/k-NN/blob/2.x/build.gradle#L327, that can increment the bwc version in the same existing gradle task `updateVersion`, sample PR for incrementing BWC version https://github.com/opensearch-project/k-NN/pull/826/files.
@ankitkala @peternied

**Comment by gaiksaya** [comment]
Closing this issue as no action item is pending from this repo. Please feel free to update the `updateVersion` task in order to accommodate more updates you version number in your repo. All the build-repo does is runs that tasks.
