### ISSUE TITLE
Update github license checker in the github action

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#3079]
Hi,
I have noticed that the license checker actually missing bunch of files such as the ones in scripts/pkg/build_scripts

Also the initial license checker github action is deprecated in developmeng
https://github.com/kt3k/license_checker_github_action

New one:
https://github.com/kt3k/deno_license_checker

Thoughts?

**Comment by hitenshKharva** [comment]
I would like to work on this issue.

**Comment by hitenshKharva** [comment]
Hey @peterzhuamazon,

Can you provide an example file in the scripts/pkg/build_scripts that misses the github_license_checker?
Currently, the GitHub license checker checks for files with `.{py,groovy,sh,js,ts} ` as extensions. Are we considering adding more file extensions here?

**Comment by peterzhuamazon** [comment]
Thanks @hitenshKharva for the great contribution.
