### ISSUE TITLE
[Help/Bug?] Can't find a way to build from Debian or Ubuntu

### ISSUE THREAD

**Issue by Deeptwix** [opensearch-project/opensearch-build#3085]
**Issue**
While trying to build on Debian 11 and Ubuntu 22.10, the task `:libs:opensearch-plugin-classloader:javadoc` always fails and I can't get past it.

![image](https://user-images.githubusercontent.com/7429892/211799098-2b75c43d-688c-4b31-89fd-d69beae56e89.png)

**Steps to reproduce**
- Using a fresh Debian 11 CT or VM or a fresh Ubuntu 22.10 VM 
- Install requirements (git, curl, pyenv, python 3.7.12, pipenv, jdk-17, nvm, node and yarn)
- Clone the repo, cd in & run `./build.sh manifests/2.4.0/opensearch-2.4.0.yml` (tried with 1.4.0, 2..0, 2.3.0, 2.4.0, 2.4.1, with platforms and components specified or not)

**Disclaimer**
I'm not that knowledgeable about Java and Gradle, so I imagine it's pretty likely that I've missed something.
If that's the case, and there's a way that it could be made more obvious in the docs, I'd gladly make a PR to improve it.

**Comment by bbarani** [comment]
@peterzhuamazon @prudhvigodithi @rishabh6788  Can you provide your inputs here?

**Comment by rishabh6788** [comment]
Will take a look and try to reproduce the issue to debug further.

**Comment by rishabh6788** [comment]
@Deeptwix I tried building on Ubuntu-22.04 ec2 instance with `openjdk-17` and it built successfully. 
In the log you pasted it mentions a log file `javadoc.options`, can you please paste the log from that file?

**Comment by rishabh6788** [comment]
also, please use `--stacktrace` flag to get additional context.

**Comment by Deeptwix** [comment]
Thanks for taking the time @rishabh6788.

Just to be sure, you didn't add any settings to the "build.sh" and didn't setup anything that I didn't mention in my message ?
As I said I really wouldn't be surprised if there is something that I've missed.

I've attached the `javadoc.options` and the result from the `--stacktrace`
[javadoc.options](https://github.com/opensearch-project/opensearch-build/files/10467690/javadoc.options.txt)
[stacktrace](https://github.com/opensearch-project/opensearch-build/files/10467691/stacktrace.txt)

**Comment by rishabh6788** [comment]
From stacktrace `A problem occurred starting process 'command '/usr/lib/jvm/java-17-openjdk-amd64/bin/javadoc''`. Seems like an issue with java installation. Can you please clean your existing java installation and re-install using `sudo apt-get install openjdk-17-jdk` command and then try again?
@Deeptwix

**Comment by Deeptwix** [comment]
I purged it `apt remove openjdk-17-jdk openjdk-17-jre --purge` and reinstalled them and it works.
It kinda melts my brain that I've had the issue on two different systems but at least it works.

Thanks a lot @rishabh6788 !
