### ISSUE TITLE
Release a standalone, minimal artifact

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#31]
**Is your feature request related to a problem? Please describe.**

Release a standalone, minimal artifact, not just a bundle with plugins installed.

**Naming**

In https://discuss.opendistrocommunity.dev/t/naming-for-opensearch-1-0-distributions/5789 and https://discuss.opendistrocommunity.dev/t/convergence-of-opensearch-opendistro-plugins/5625/10 we discussed calling it `-min`.

**Additional Context**

https://github.com/opensearch-project/OpenSearch/issues/632
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/319
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/340

**Comment by bbarani** [comment]
Released it as part of OpenSearch 1.0 release
