### ISSUE TITLE
Onboard opensearch-benchmarks for performance testing

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/opensearch-build#3100]
### Is your feature request related to a problem? Please describe

Currently, opensearch is using internal tool to do its performance testing. Since https://github.com/opensearch-project/opensearch-benchmark is out, we can start using the same for opensearch distribution as well.

### Describe the solution you'd like

Use opensearch-benchmark for performance testing

### Acceptance criteria 
- [ ] Run performance testing using opensearch-benchmark tool
- [ ] The results should be reported as an html output file, index to other opensearch cluster, etc.
- [ ]  Framework should be generic enough to run any kind of workloads, iterations.
- [ ] Framework should also support longevity testing

**Comment by gaiksaya** [comment]
Current code base using internal tool https://github.com/opensearch-project/opensearch-build/tree/main/src/test_workflow/perf_test
We also need to use https://github.com/opensearch-project/opensearch-cluster-cdk to deploy clusters to be used in performance testing. 
The above cdk codebase only supports tarball today. We need to support other distributions as well

**Comment by nknize** [comment]
+1 for this! Especially for getting public benchmarks going for segrep!!!!

**Comment by mch2** [comment]
Related - https://github.com/opensearch-project/OpenSearch/issues/3983

**Comment by ankitkala** [comment]
I see that we're also considering pushing the benchmark result into a cluster. Are we thinking about keeping these results public?

**Comment by ankitkala** [comment]
We're leveraging the existing setup for running the performance benchmarks for cross-cluster-replication as well. Support in opensearch-benchmark is already added. 
Since we're moving away from the internal tool, there might be additional efforts to achieve the same by directly calling opensearch-benchmark.

**Comment by bbarani** [comment]
> I see that we're also considering pushing the benchmark result into a cluster. Are we thinking about keeping these results public?

@ankitkala We are planning to surface the results to the community ( as needed ) and its tracked [here](https://github.com/opensearch-project/opensearch-benchmark/issues/102)

**Comment by bbarani** [comment]
We are actively working on setting up the base for using OpenSearch-benchmark for performance testing and you can track the status using this project [board](https://github.com/orgs/opensearch-project/projects/100/views/5)

**Comment by rishabh6788** [comment]
Closing this in favor of https://github.com/opensearch-project/opensearch-benchmark/issues/102. 
P0 was released and the benchmark dashboard is available to public on https://opensearch.org/benchmarks.
