### ISSUE TITLE
[release]: Publish opensearch-reporting-cli to npm

### ISSUE THREAD

**Issue by rupal-bq** [opensearch-project/opensearch-build#3112]
### What is the name of your component?

opensearch-reporting-cli

### What is the link to your GitHub repo?

https://github.com/opensearch-project/reporting-cli

### Targeted release date

Feb 2, 2023

### Where should we publish this component?

https://www.npmjs.com/
Publish tgz to artifacts.opensearch.org

### What type of artifact(s) will be generated for this component?

npm package

### Have you completed the required reviews including security reviews, UX reviews?

Yes

### Have you on-boarded automated security scanning for the GitHub repo associated with this component?

Yes

**Comment by rishabh6788** [comment]
Closing https://github.com/opensearch-project/opensearch-build/issues/3113 as it is related to the same component. Will track `.tgz` and `npm` release in this issue.

**Comment by rishabh6788** [comment]
@rupal-bq Could you please provide a tentative release date to be better prepared?

**Comment by rupal-bq** [comment]
> @rupal-bq Could you please provide a tentative release date to be better prepared?

Can we do first week of Feb?

**Comment by gaiksaya** [comment]
Hi @rupal-bq ,

Sure we can start with the process accordingly. Can you fix the date and update the issue with the same?

**Comment by rupal-bq** [comment]
> Hi @rupal-bq ,
Sure we can start with the process accordingly. Can you fix the date and update the issue with the same?
Can you also confirm what the URL for tg.gz look like? I believe it should be similar to other components on opensearch.org download page
Example: https://artifacts.opensearch.org/logstash/logstash-oss-with-opensearch-output-plugin-8.4.0-linux-x64.tar.gz


Thanks @gaiksaya. I updated the date in issue description. 

Yes, url will should be similar to other components on download page. 
https://artifacts.opensearch.org/reporting-cli/opensearch-reporting-cli-1.0.0-linux-x64.tgz

**Comment by anirudha** [comment]
@gaiksaya can we have a release date for this please, thanks

**Comment by gaiksaya** [comment]
Sorry got busy with another release. I was trying to create a different role for each component with limited access to uploading path in S3 however there is some blocker as it was a 3 hop role assumption. We are moving forward with manual role creation for now. 
We already have NPM publishing in place just need to onboard this components. For tarball I need to create a new lib which will do the copying. ETA: 2 days.

Thanks!

**Comment by gaiksaya** [comment]
Looks like the artifact that will be published to artifacts.opensearch.org is`.tgz`. Need to add support for the same https://github.com/opensearch-project/opensearch-build/blob/main/src/sign_workflow/signer_pgp.py#L22
Will work on that too. Thanks!

**Comment by rupal-bq** [comment]
@gaiksaya Thank you for helping with the release. 
https://www.npmjs.com/package/@opensearch-project/reporting-cli
