### ISSUE TITLE
[release]: Publish opensearch-reporting-cli to opensearch artifacts

### ISSUE THREAD

**Issue by rupal-bq** [opensearch-project/opensearch-build#3113]
### What is the name of your component?

opensearch-reporting-cli

### What is the link to your GitHub repo?

https://github.com/opensearch-project/reporting-cli

### Targeted release date

Q1 2023

### Where should we publish this component?

https://opensearch.org/artifacts

### What type of artifact(s) will be generated for this component?

.tgz file

### Have you completed the required reviews including security reviews, UX reviews?

Yes

### Have you on-boarded automated security scanning for the GitHub repo associated with this component?

No. we need to enable automated CVE scanning on this repo.

**Comment by rishabh6788** [comment]
Closing this issue and tracking in https://github.com/opensearch-project/opensearch-build/issues/3112
