### ISSUE TITLE
[Retrospective] Release version 2.5.0

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#3117]
#2908

How to use this issue?
Please add comments to this issue, they can be small or large in scope. Honest feedback is important to improve our processes, suggestions are also welcomed but not required.

What will happen to this issue post release?
There will be a discussion(s) about how the release went and how the next release can be improved. Then this ticket will be updated with the notes of that discussion along side action items.

**Comment by bbarani** [comment]
1.) Fix flaky tests in respective repos
2.) Automated testing for all supported distribution types
3.) Improve current tests ( some issues were found only during sanity testing but not reported via automated tests)
4.) Better documentation on-boarding process

**Comment by penghuo** [comment]
Add 2 issues impact SQL plugin.
1. SQL Plugin main branch BWC test faiiled after OpenSearch bump to 2.6. https://github.com/opensearch-project/OpenSearch/issues/5815
2. Auto bump is blocked by dependency package. https://github.com/opensearch-project/sql/pulls?q=is%3Apr+is%3Aopen+-is%3Adraft+-AUTO+in%3Atitle

**Comment by hdhalter** [comment]
Development should create documentation issues for features that require documentation. It's best to enter an issue as early as possible in the release cycle or reach out directly to your documentation partner. Some requests didn't get to us until code freeze or after and we didn't have enough time to get them assigned and through the review process. Review process is tech review, 2 doc reviews, and editorial. To insist on the highest standards, the review process can require several iterations over several days.

**Comment by jhmcintyre** [comment]
For future releases, let's explore ways to confirm final roster of included features earlier in the release cycle to support content development deadlines.
