### ISSUE TITLE
[release]: Data Prepper 2.1.0

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/opensearch-build#3125]
### What is the name of your component?

Data Prepper 2.1.0

### What is the link to your GitHub repo?

https://github.com/opensearch-project/data-prepper

### Targeted release date

Early Feb. - exact release date to be specified later.

### Where should we publish this component?

Publishing to Docker Hub, ECS, opensearch.org artifacts, Maven Central.

The current Jenkins job publishes these.

### What type of artifact(s) will be generated for this component?

* Docker image
* tar.gz artifacts
* Maven artifacts

The current Jenkins job publishes these.

### Have you completed the required reviews including security reviews, UX reviews?

Not at this time, though we are in the process and will release only after completion.

### Have you on-boarded automated security scanning for the GitHub repo associated with this component?

Yes.

### Additional context

Data Prepper builds artifacts using GitHub Actions. This will publish to staging repositories. Our team is responsible for this portion. We will need the opensearch-build team to run the Jenkins job which promotes these to production.

A Data Prepper maintainer will supply the DATA_PREPPER_BUILD_NUMBER parameter.

Parameters:

VERSION: 2.1.0
RELEASE_MAJOR_TAG: true
RELEASE_LATEST_TAG: true
DATA_PREPPER_BUILD_NUMBER - To be supplied later.

**Comment by gaiksaya** [comment]
Hi @dlvenable, we would like to change a few things for data-prepper release process as mentioned here: https://github.com/opensearch-project/data-prepper/issues/2122
Let us know what do you think about that. 

We would like to make this process has automated as possible and give the ownership entirely to you.
Thanks!

**Comment by dlvenable** [comment]
@gaiksaya , We are interested in making that change, but I think for 2.1, we won't be able to make it. The current process requires a manual step, but it is a light touch - run a job and let it go. The only other manual step is the Maven artifact release.

**Comment by peterzhuamazon** [comment]
I will work with @asifsmohammed on the release of this.

**Comment by asifsmohammed** [comment]
VERSION: 2.1.0
RELEASE_MAJOR_TAG: true
RELEASE_LATEST_TAG: true
DATA_PREPPER_BUILD_NUMBER - 42

**Comment by peterzhuamazon** [comment]
![Screen Shot 2023-03-02 at 3 32 44 PM](https://user-images.githubusercontent.com/65193828/222545318-2d7d61f8-cd4a-4b0c-9041-6bb84912f804.png)

**Comment by peterzhuamazon** [comment]
We have released dataprepper 2.1.0 on tar, docker(hub/ecr), and maven.
https://repo1.maven.org/maven2/org/opensearch/dataprepper/data-prepper-api/2.1.0/

So @asifsmohammed will verify all three above before closing the issue. Thanks.

**Comment by asifsmohammed** [comment]
Verified maven release. Thanks @peterzhuamazon

**Comment by dlvenable** [comment]
Data Prepper 2.1.0 is now released.
