### ISSUE TITLE
Onboard OpenSeach-PHP to the automated release process.

### ISSUE THREAD

**Issue by harshavamsi** [opensearch-project/opensearch-build#3133]
### Is your feature request related to a problem? Please describe

Onboard [opensearch-php](https://github.com/opensearch-project/opensearch-php) to the new automated release process.

### Describe the solution you'd like

The solution is outlined in https://github.com/opensearch-project/opensearch-build/issues/1234.

**Comment by gaiksaya** [comment]
Hi @harshavamsi Can you open the issue using standlaone release template: https://github.com/opensearch-project/opensearch-build/issues/new?assignees=&labels=release%2Cuntriaged&template=standalone_releases_template.yaml&title=%5Brelease%5D%3A+
This helps us to understand the scope, dates, etc

**Comment by harshavamsi** [comment]
@gaiksaya definitely! Was unsure if that is what we needed.

**Comment by wbeckler** [comment]
FYI the issue was opened here: https://github.com/opensearch-project/opensearch-build/issues/3146
