### ISSUE TITLE
Onboard OpenSeach-Ruby to the automated release process

### ISSUE THREAD

**Issue by nhtruong** [opensearch-project/opensearch-build#3134]
### Is your feature request related to a problem? Please describe
Onboard [opensearch-ruby](https://github.com/opensearch-project/opensearch-ruby) to the new automated release process.

### Describe the solution you'd like
The solution is outlined in https://github.com/opensearch-project/opensearch-build/issues/1234.

**Comment by gaiksaya** [comment]
Opensearch-ruby is onboarded to 1-click release process.
