### ISSUE TITLE
Onboard OpenSeach-JavaScript to the automated release process

### ISSUE THREAD

**Issue by nhtruong** [opensearch-project/opensearch-build#3135]
### Is your feature request related to a problem? Please describe
Onboard [opensearch-js](https://github.com/opensearch-project/opensearch-js) to the new automated release process.

### Describe the solution you'd like
The solution is outlined in https://github.com/opensearch-project/opensearch-build/issues/1234.

**Comment by gaiksaya** [comment]
Hi @nhtruong,

Looks like opensearch-js is already onboarded: 
https://github.com/opensearch-project/opensearch-js/pull/317
Are you expecting something else?

Let us know. Thanks!

**Comment by gaiksaya** [comment]
Ah! Is it okay to close the issue or do you want to it keep open?

**Comment by nhtruong** [comment]
nope let's close it
