### ISSUE TITLE
[release]: logstash-output-opensearch plugin 2.0.1 with oss-Logstash 8.6.1

### ISSUE THREAD

**Issue by sshivanii** [opensearch-project/opensearch-build#3138]
### What is the name of your component?

logstash-output-opensearch plugin 2.0.1 with oss-Logstash 8.6.1 as Docker image and tar artifacts

### What is the link to your GitHub repo?

https://github.com/opensearch-project/logstash-output-opensearch/tree/main/release

### Targeted release date

1/30/2023

### Where should we publish this component?

Publish to Docker Hub, opensearch.org artifacts

### What type of artifact(s) will be generated for this component?

- Docker image
- tar.gz artifacts for linux with x64
- tar.gz artifacts for linux arm64
- tar.gz artifacts for macos x64

### Have you completed the required reviews including security reviews, UX reviews?

Not required

### Have you on-boarded automated security scanning for the GitHub repo associated with this component?

No

### Additional context

logstash-output-opensearch plugin 2.0.1 with oss-Logstash 8.6.1 releases the following artifacts and we will need help from the build team to onboard to the new OpenSearch [release](https://github.com/opensearch-project/opensearch-build/issues/1234) process, especially for arm64 since GitHub does not provide a runner for it :

- Docker image
- tar.gz artifacts for linux with x64
- tar.gz artifacts for linux arm64
- tar.gz artifacts for macos x64

**Comment by zelinh** [comment]
[Triages] Our team is working closely regarding of this release.

**Comment by zelinh** [comment]
Closing this issue as we have completed the tasks on our end.

**Comment by excalq** [comment]
@zelinh It looks like Logstash 8.8 was released today. Might be worth preparing another release soon - it doesn't look like much has changed since 8.6.
