### ISSUE TITLE
[release]: logstash-output-opensearch plugin 2.0.1

### ISSUE THREAD

**Issue by sshivanii** [opensearch-project/opensearch-build#3139]
### What is the name of your component?

logstash-output-opensearch plugin 2.0.1

### What is the link to your GitHub repo?

https://github.com/opensearch-project/logstash-output-opensearch

### Targeted release date

1/30/2023

### Where should we publish this component?

rubygems.org

### What type of artifact(s) will be generated for this component?

rubygem 

### Have you completed the required reviews including security reviews, UX reviews?

Not required

### Have you on-boarded automated security scanning for the GitHub repo associated with this component?

No

### Additional context

logstash-output-opensearch plugin will be released to rubygems.org and we will need help from the build team to onboard to the new [OpenSearch](https://github.com/opensearch-project/opensearch-build/issues/1234) process

**Comment by gaiksaya** [comment]
Keeping it open till the gem is release. We are set for the release.

**Comment by gaiksaya** [comment]
Release was successful: https://rubygems.org/gems/logstash-output-opensearch
https://build.ci.opensearch.org/job/logstash-output-opensearch-release/5/console
