### ISSUE TITLE
Onboard opensearch-rs to new release process

### ISSUE THREAD

**Issue by Xtansia** [opensearch-project/opensearch-build#3142]
### Is your feature request related to a problem? Please describe

[opensearch-rs](https://github.com/opensearch-project/opensearch-rs) is still using a manual release process. It needs onboarding to a new automated one using one-click release.

### Describe the solution you'd like

Adapt to #1234 

Depends on:
- [ ] #2505's - publishToCrates functionality

### Describe alternatives you've considered

Continue using manual approach

**Comment by gaiksaya** [comment]
Hi @Xtansia Can you use the [standalone release template](https://github.com/opensearch-project/opensearch-build/issues/new?assignees=&labels=release%2Cuntriaged&template=standalone_releases_template.yaml&title=%5Brelease%5D%3A+) to create this issue? This helps us to get most of the answers required to prioritize the work.
Thanks!

**Comment by zelinh** [comment]
[Triages] @Xtansia I will be closing this one and feel free to create a new one with the template. Thanks.
https://github.com/opensearch-project/opensearch-build/issues/new?assignees=&labels=release%2Cuntriaged&template=standalone_releases_template.yaml&title=%5Brelease%5D%3A+
