### ISSUE TITLE
[On-boarding]: ml-commons-dashboards plugin

### ISSUE THREAD

**Issue by ruanyl** [opensearch-project/opensearch-build#3154]
### What is the name of your plugin?

Machine Learning Dashboards (ml-commons-dashboards)

### What is the link to your GitHub repo?

https://github.com/opensearch-project/ml-commons-dashboards

### Targeted release version

2.6.0

### What type of the plugin are we on-boarding?

OpenSearch-dashboards

### Did you read the on-boarding document

Yes

### Does this plugin has all the necessary automated tests?

Not yet, in progress

### Have you completed the required reviews including Security reviews, UX reviews?

Not yet, in progress

### Have you on-boarded automated security scanning for the GitHub repo associated with this plugin?

Yes

<img width="970" alt="image" src="https://user-images.githubusercontent.com/486382/215385319-fe7b4164-b8c6-4356-9457-e3e44de8f06d.png">

### Additional context

The plugin repo is still private

**Comment by zelinh** [comment]
[Triages] Please comment on this issue whether the security is reviewed. Thanks.

**Comment by gaiksaya** [comment]
The plugin is onboarded with experimental feature flag on by default. Closing the issue
