### ISSUE TITLE
The `latest` Opensearch 3.0.0 build does not include security

### ISSUE THREAD

**Issue by RyanL1997** [opensearch-project/opensearch-build#3172]
### Describe the bug

The current `latest` build of opensearch does not have available security plugin available. I created this issue to track the fix.

### To reproduce

* https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/3.0.0/latest/linux/x64/tar/builds/opensearch/plugins/opensearch-security-3.0.0.0.zip
* https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/3.0.0/latest/windows/x64/tar/builds/opensearch/plugins/opensearch-security-3.0.0.0.zip

### Expected behavior

Should have security plugin available with `latest` Opensearch build.

### Host / Environment

Linux/Windows

**Comment by zelinh** [comment]
I think for windows, you are using the wrong URL. It should be https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/3.0.0/latest/windows/x64/zip/builds/opensearch/plugins/opensearch-security-3.0.0.0.zip

**Comment by bbarani** [comment]
@RyanL1997 You should be able to download both TAR and zips now.

As mentioned by @zelinh please use the corrected path for Windows artifact.

```
https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/3.0.0/latest/linux/x64/tar/builds/opensearch/plugins/opensearch-security-3.0.0.0.zip

https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/3.0.0/latest/windows/x64/zip/builds/opensearch/plugins/opensearch-security-3.0.0.0.zip
```

**Comment by bbarani** [comment]
Closing this issue as the artifacts can be downloaded using the appropriate URL's. Feel free to re-open if needed.

**Comment by RyanL1997** [comment]
@bbarani @zelinh Thank you all for the updates! I have also tested the with the new builds. Everything should be fine now.
