### ISSUE TITLE
[Bug] 3.0.0 build fail for a long while

### ISSUE THREAD

**Issue by ananzh** [opensearch-project/opensearch-build#3173]
### Describe the bug

For this functional-test PR: https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/423, I see the without-security tests failed due to by missing component [here](https://github.com/opensearch-project/opensearch-dashboards-functional-test/actions/runs/4069492251/jobs/7009299743)
```
Expected to find element: [class="visTable visTable__groupInColumns"], but never found it.
```
So it seems the latest 3.0.0 is not fetching the changes. From a list of build, I see 3.0.0 failed for quite a while. 

### To reproduce

* Download the latest 3.0.0 
```
wget https://ci.opensearch.org/ci/dbc/distribution-build-opensearch-dashboards/3.0.0/latest/linux/x64/tar/dist/opensearch-dashboards/opensearch-dashboards-3.0.0-linux-x64.tar.gz
```
* unzip it
* Then go to src/plugins. I could both vis_type_table and vis_type_table_new folder which should be pretty old. Since vis_type_table_new is there for vis builder hookup in 2.4. Or if you check the manifest.yml the commit hash is `bb94a9d6fb795a6e11d4739f428430f5fab18461` and if click https://github.com/opensearch-project/OpenSearch-Dashboards/tree/bb94a9d6fb795a6e11d4739f428430f5fab18461 you can see it is around 12/12/2022. Seems we don't have any success after that.

### Expected behavior

Have a latest 3.0.0 build to unblock functional tests.

**Comment by peterzhuamazon** [comment]
Related failure only on 3.0.0 for DEB on OSD core:
```
make: *** [Release/obj.target/fibers/src/libcoro/coro.o] Error 1

make: Leaving directory `/tmp/tmp4pgkscxm/OpenSearch-Dashboards/node_modules/fibers/build'

gyp ERR! build error 

gyp ERR! stack Error: `make` failed with exit code: 2

gyp ERR! stack     at ChildProcess.onExit (/tmp/tmp4pgkscxm/OpenSearch-Dashboards/node_modules/node-gyp/lib/build.js:194:23)

gyp ERR! stack     at ChildProcess.emit (events.js:400:28)

gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)

gyp ERR! System Linux 5.10.135-122.509.amzn2.aarch64

gyp ERR! command "/usr/share/opensearch/.nvm/versions/node/v14.20.1/bin/node" "/tmp/tmp4pgkscxm/OpenSearch-Dashboards/node_modules/.bin/node-gyp" "rebuild" "--release"

gyp ERR! cwd /tmp/tmp4pgkscxm/OpenSearch-Dashboards/node_modules/fibers

gyp ERR! node -v v14.20.1

gyp ERR! node-gyp -v v8.4.1

gyp ERR! not ok 

node-gyp exited with code: 1

Please make sure you are using a supported platform and node version. If you

would like to compile fibers on this machine please make sure you have setup your

build environment--

Windows + OS X instructions here: https://github.com/nodejs/node-gyp

Ubuntu users please run: `sudo apt-get install g++ build-essential`

RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'` 

Alpine users please run: `sudo apk add python make g++`

/bin/sh: nodejs: command not found

info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

ERROR [bootstrap] failed:

ERROR Error: Command failed with exit code 127: /usr/share/opensearch/.nvm/versions/node/v14.20.1/lib/node_modules/yarn/bin/yarn.js install --non-interactive

          at makeError (/tmp/tmp4pgkscxm/OpenSearch-Dashboards/packages/osd-pm/dist/index.js:25150:11)

          at handlePromise (/tmp/tmp4pgkscxm/OpenSearch-Dashboards/packages/osd-pm/dist/index.js:24085:26)

          at processTicksAndRejections (internal/process/task_queues.js:95:5)

          at async installInDir (/tmp/tmp4pgkscxm/OpenSearch-Dashboards/packages/osd-pm/dist/index.js:23821:3)

          at async Project.installDependencies (/tmp/tmp4pgkscxm/OpenSearch-Dashboards/packages/osd-pm/dist/index.js:14780:5)

          at async Object.run (/tmp/tmp4pgkscxm/OpenSearch-Dashboards/packages/osd-pm/dist/index.js:9003:11)

          at async runCommand (/tmp/tmp4pgkscxm/OpenSearch-Dashboards/packages/osd-pm/dist/index.js:57870:5)

          at async Module.run (/tmp/tmp4pgkscxm/OpenSearch-Dashboards/packages/osd-pm/dist/index.js:263:3)

error Command failed with exit code 1.

```

**Comment by peterzhuamazon** [comment]
Related core issue:
* https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3282

**Comment by peterzhuamazon** [comment]
As per conversation with @ananzh and @kavilla this is related to updated node version in OSD 3.0.0 which caused the generation of deb dist specifically.

We will remove deb compilation from scheduled crontab, and ask core team to fix this issue before add it back.

Thanks.

**Comment by bbarani** [comment]
@peterzhuamazon Do you have any updates?

**Comment by jordarlu** [comment]
as of today (5/10/2023), the build 3.0.0 fail due to a few individual components :   

- Ml commons 
- Neural search 
- Anomaly Detection 
- Cross cluster replication 

There are Auto Cut issues created againt on each of them.
I am closing this duplicated issue. 

https://github.com/issues?q=is%3Aopen+is%3Aissue+user%3Aopensearch-project+label%3Av3.0.0+%2Cautocut
