### ISSUE TITLE
[Proposal] Publish snapshots with partial builds

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/opensearch-build#3180]
### Is your feature request related to a problem? Please describe

Our distribution manifest consists of bunch of components and is maintained by different maintainers. 
Our build/assemble/publish workflow is sequential and assumes all steps of each workflow to succeed. 

As the project grows bigger, few components will consistently fail causing blockers for consumers who depend on snapshots. The stale snapshots are ending with manually kicking off builds with updated manifests. 
We have seen multiple problems in the recent weeks:

- https://github.com/opensearch-project/security/issues/2149
- https://github.com/opensearch-project/OpenSearch/issues/5815 
- https://github.com/opensearch-project/opensearch-sdk-java/pull/365#issuecomment-1412723479
- https://github.com/opensearch-project/job-scheduler/pull/306#issuecomment-1409522076
and many more.

Our workflows fail hard when one component fails. 

### Describe the solution you'd like

Our jenkins workflows should allow fail through and let partial components to be published. 
For example: 
Our manifest contains OpenSearch, Job Scheduler, security. Its ok to have security to fail the build but we should still continue running though the workflows to publish OpenSearch and JS snapshots. 

We can leverage jenkins scripts[1] to smartly identify the successful components and run through all stages of the pipeline for snapshots. 

[1] https://www.jenkins.io/doc/pipeline/steps/workflow-basic-steps/

### Describe alternatives you've considered

Wait for snapshots being published :/

**Comment by ryanbogan** [comment]
+1

**Comment by bbarani** [comment]
@saratvemulapalli Are you referring to Maven artifacts or TAR here? We did add an enhancement to[ publish TAR snapshots for core](https://github.com/opensearch-project/opensearch-build/issues/2716) even if plugins fail but yet to work on the Maven part. We are looking in to moving the snapshot outside of distribution build job to individual repos as well.

**Comment by saratvemulapalli** [comment]
@bbarani this is for maven artifacts. I like https://github.com/opensearch-project/opensearch-build/issues/3185 , our monolithic build should be broken down to make this seamless.

**Comment by saratvemulapalli** [comment]
I'll close this as we are already taking care of this and move towards publishing artifacts from each repo.
