### ISSUE TITLE
Replace remote min artifact with local release artifact for integration testing

### ISSUE THREAD

**Issue by setiah** [opensearch-project/opensearch-build#319]
Currently the integ tests in CICD pipeline fails because it expects the min opensearch artifact to be build and published in  public repo artifacts.opensearch.org. This does not work for the cicd release workflow where it is expected to run integTests on not-yet-published artifacts. 

```
* What went wrong:
Execution failed for task ':integTest'.
> Could not resolve all files for configuration ':opensearch_distro_extracted_testclusters--integTest-0-1.1.0-'.
   > Could not resolve opensearch-distribution:opensearch:1.1.0.
     Required by:
         project :
      > Could not resolve opensearch-distribution:opensearch:1.1.0.
         > Could not get resource 'https://artifacts.opensearch.org/releases/core/opensearch/1.1.0/opensearch-min-1.1.0-linux-x64.tar.gz'.
            > Could not HEAD 'https://artifacts.opensearch.org/releases/core/opensearch/1.1.0/opensearch-min-1.1.0-linux-x64.tar.gz'. Received status code 403 from server: Forbidden
      > Could not resolve opensearch-distribution:opensearch:1.1.0.
         > Could not get resource 'https://artifacts.opensearch.org/release-candidates/core/opensearch/1.1.0/opensearch-min-1.1.0-linux-x64.tar.gz'.
            > Could not HEAD 'https://artifacts.opensearch.org/release-candidates/core/opensearch/1.1.0/opensearch-min-1.1.0-linux-x64.tar.gz'. Received status code 403 from server: Forbidden
```

**Comment by setiah** [comment]
A simpler "potential" workaround which could avoid the need for any code changes -

If we create an `opensearch-downloads` folder in maven local repository and download the tarball there, the DistributionDownloadPlugin should be able to read the min artifact tarball from that repo itself. We have DependencyInstaller that provides all maven dependencies for a plugin integ test, and that could also provide the min artifact tarball in maven local location. 

@VachaShah could you give this a try locally and see if it works?

**Comment by peternied** [comment]
Rather than use DependencyInstaller could just download everything?

It sounds like some local maven files need to be put into the correct spot, and maybe certain tests need additional copying around, if we can have the test environment pre-populated this is a easier problem to solve.

**Comment by setiah** [comment]
This is now tracked under https://github.com/opensearch-project/OpenSearch/issues/1240
