### ISSUE TITLE
[release]: One-click release process for opensearch-net

### ISSUE THREAD

**Issue by wbeckler** [opensearch-project/opensearch-build#3194]
### What is the name of your component?

The component is the .Net client

### What is the link to your GitHub repo?

https://github.com/opensearch-project/opensearch-net

### Targeted release date

Feb 23, 2023

### Where should we publish this component?

Nuget.org

### What type of artifact(s) will be generated for this component?

Nuget package

### Have you completed the required reviews including security reviews, UX reviews?

Yes

### Have you on-boarded automated security scanning for the GitHub repo associated with this component?

Not sure. What is considered the baseline for this?

**Comment by wbeckler** [comment]
I just realized this is a dupe of https://github.com/opensearch-project/opensearch-build/issues/3141

**Comment by wbeckler** [comment]
For context: this depends on #2965 , which was completed.

**Comment by gaiksaya** [comment]
Yeah the dependent issue is complete. We just need to onboard .net repository to this process. Will work on this next week and update the issue once its done.
Thanks!

**Comment by Xtansia** [comment]
We have a handful of features, bug-fixes & dependency updates waiting to be released in the .NET client, it would be awesome to be able to release these with the new automated process, biggest name one being support for Amazon OpenSearch Serverless: https://github.com/opensearch-project/opensearch-net/blob/main/CHANGELOG.md#unreleased

**Comment by gaiksaya** [comment]
Closing this issue as opensearch-net is onboarded to 1-click release process. Please re-open in case of any issues.

**Comment by gaiksaya** [comment]
Reopening until a release is successful.

**Comment by gaiksaya** [comment]
🎉  OpenSearch DotNet client is released successfully on Nuget: https://www.nuget.org/profiles/opensearchproject
