### ISSUE TITLE
Jenkins Integration for Validation Workflow

### ISSUE THREAD

**Issue by Divyaasm** [opensearch-project/opensearch-build#3201]
Creation of Jenkins wrapper for the Validation workflow to automatically run the Job.

### Acceptance criteria
- Create a Groovy library to call the validation script.
- Create a new Jenkins job that uses the Validation library.
   - Build for Tar, Rpm,Docker and Yum distributions both individually and altogether.

**Comment by prudhvigodithi** [comment]
The best approach to do this is:
1) Define multiple stages, each stage corresponds to separate distribution.
2) Run all the above stages in parallel using jenkins declarative pipeline (Ref: https://www.jenkins.io/blog/2017/09/25/declarative-1/)

With this all stages are executed in parallel and have better logging using existing jenkins blue ocean to visualize each failed stage separately.

**Comment by gaiksaya** [comment]
Validation workflow can be added after this PR sis merged: https://github.com/opensearch-project/opensearch-build-libraries/pull/160

**Comment by peterzhuamazon** [comment]
Resolve path issues:
* https://github.com/opensearch-project/opensearch-ci/pull/282

**Comment by Divyaasm** [comment]
Closing as https://github.com/opensearch-project/opensearch-build/pull/3555 is merged
