### ISSUE TITLE
Discussion on whether to switch JDK19 for the Jenkins Pipeline Builds on 3.x

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#3206]
We have added support for JDK19 in our ci image, ami, pipelines tools.
Now we can have a discussion and plan to properly switch to JDK19 for 3.x versions.

Related:
* https://github.com/opensearch-project/opensearch-build/issues/2807

Thanks.

**Comment by peterzhuamazon** [comment]
Add @reta into the conversation to see the status of core.
And if we are ready to use JDK19 on Jenkins.

cc:  @CEHENKLE @dblock @bbarani

Thanks.

**Comment by reta** [comment]
Thanks @peterzhuamazon, the CI on `main` is using JDK-19 for a long time (to Gradle all tests etc):
```
=======================================
OpenSearch Build Hamster says Hello!
  Gradle Version        : 7.6
  OS Info               : Linux 5.15.0-1028-aws (amd64)
  JDK Version           : 19 (Eclipse Temurin JDK)
  JAVA_HOME             : /usr/lib/jvm/temurin-19-jdk-amd64
  Random Testing Seed   : BA194221D5185096
  In FIPS 140 mode      : false
=======================================
```

**Comment by reta** [comment]
But I am unsure we have to switch the default CI to non-LTS JDK, next month it is going to be superseded by JDK-20

**Comment by peterzhuamazon** [comment]
Hi @reta 

We are mainly talking about the build pipeline.
On gradle check we already use jdk19 but on build, we are still using the current LTS 17.
Since 19 is not LTS I assume we want to keep on 17?

I wonder if we want to fix on 17 or on the next potential LTS.

Thanks.

**Comment by peterzhuamazon** [comment]
Adding more into the discussion on this: @nknize @saratvemulapalli @mch2.

Thanks.

**Comment by reta** [comment]
@peterzhuamazon I would suggest to keep CI on JDK-17 LTS, in 3 weeks JDK-20 is out so switching to JDK-19 is probably not well timed, it go out of support.

**Comment by peterzhuamazon** [comment]
> @peterzhuamazon I would suggest to keep CI on JDK-17 LTS, in 3 weeks JDK-20 is out so switching to JDK-19 is probably not well timed, it will go out of support.

Shall we remove jdk19 from the ci images/ami as well if that happens?
I assume we will never use jdk19 after that?

Thanks.

**Comment by reta** [comment]
> Shall we remove jdk19 from the ci images/ami as well if that happens?

But we use it in Gradle check now ... Or you mean once JDK-20 is out?

**Comment by peterzhuamazon** [comment]
> > Shall we remove jdk19 from the ci images/ami as well if that happens?
> 
> But we use it in Gradle check now ... Or you mean once JDK-20 is out?

Yes!

**Comment by reta** [comment]
> > > Shall we remove jdk19 from the ci images/ami as well if that happens?
> > 
> > 
> > But we use it in Gradle check now ... Or you mean once JDK-20 is out?
> 
> Yes!

Sure, once GA releases are available.

**Comment by gaiksaya** [comment]
Closing this issue as 3.x is now using jdk-20 https://github.com/opensearch-project/opensearch-build/blob/main/manifests/3.0.0/opensearch-3.0.0.yml#L9
