### ISSUE TITLE
`yarn` version incompatibility issue blocks Dashboards plugins CI, docker-image, windows build

### ISSUE THREAD

**Issue by zhongnansu** [opensearch-project/opensearch-build#3210]
### issue description
Multiple Dashboards plugins CI failure reported during plugin bootstrap step, after this [commit](https://github.com/opensearch-project/OpenSearch-Dashboards/commit/de89c527dee3a997bfffc2079dbf97e4f813e54e) to Dashboards core merged recently. `@opensearch-project/opensearch@2.1.0: The engine "yarn" is incompatible with this module. Expected version "^1.22.10". Got "1.21.1"`
- [dashboards-observability plugin CI](https://github.com/opensearch-project/dashboards-observability/actions/runs/4206487652/jobs/7300033984)
- [dsahboards-maps plugin CI](https://github.com/opensearch-project/dashboards-maps/actions/runs/4206519945/jobs/7300112650)
```
yarn run v1.21.1
$ node ../../scripts/osd bootstrap
 info [opensearch-dashboards] running yarn

$ node ./preinstall_check
[1/5] Validating package.json...
[2/5] Resolving packages...
warning Resolution field "typescript@4.0.2" is incompatible with requested version "typescript@~4.5.2". 
[3/5] Fetching packages...
warning sha.js@2.4.11: Invalid bin entry for "sha.js" (in "sha.js").
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error @opensearch-project/opensearch@2.1.0: The engine "yarn" is incompatible with this module. Expected version "^1.22.10". Got "1.21.1"
error Found incompatible module.
ERROR [bootstrap] failed:
ERROR Error: Command failed with exit code 1: /opt/hostedtoolcache/node/14.[20](https://github.com/opensearch-project/dashboards-maps/actions/runs/4206519945/jobs/7300112650#step:13:21).1/x64/lib/node_modules/yarn/bin/yarn.js install --non-interactive
          at makeError (/home/runner/work/dashboards-maps/dashboards-maps/OpenSearch-Dashboards/packages/osd-pm/dist/index.js:25150:11)
          at handlePromise (/home/runner/work/dashboards-maps/dashboards-maps/OpenSearch-Dashboards/packages/osd-pm/dist/index.js:24085:26)
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
          at async installInDir (/home/runner/work/dashboards-maps/dashboards-maps/OpenSearch-Dashboards/packages/osd-pm/dist/index.js:238[21](https://github.com/opensearch-project/dashboards-maps/actions/runs/4206519945/jobs/7300112650#step:13:22):3)
          at async Project.installDependencies (/home/runner/work/dashboards-maps/dashboards-maps/OpenSearch-Dashboards/packages/osd-pm/dist/index.js:14780:5)
          at async Object.run (/home/runner/work/dashboards-maps/dashboards-maps/OpenSearch-Dashboards/packages/osd-pm/dist/index.js:9003:11)
          at async runCommand (/home/runner/work/dashboards-maps/dashboards-maps/OpenSearch-Dashboards/packages/osd-pm/dist/index.js:57870:5)
          at async Module.run (/home/runner/work/dashboards-maps/dashboards-maps/OpenSearch-Dashboards/packages/osd-pm/dist/index.js:[26](https://github.com/opensearch-project/dashboards-maps/actions/runs/4206519945/jobs/7300112650#step:13:27)3:3)
error Command failed with exit code 1.
```

### Root cause
The recent [commit](https://github.com/opensearch-project/OpenSearch-Dashboards/commit/de89c527dee3a997bfffc2079dbf97e4f813e54e) in OpenSearch Dashboards updates dependency [@opensearch-project/opensearch](https://www.npmjs.com/package/@opensearch-project/opensearch) from `^1.1.0`to `^2.1.0`, where openearch-js`2.1.0` specifies `yarn: ^1.22.1`, in this [commit](https://github.com/opensearch-project/opensearch-js/commit/9f137e9331e45ec65a733ac7d490ccd8bd75bf15).

Plugin CI workflow [fetches yarn version](https://github.com/opensearch-project/dashboards-observability/blob/0527730d9c7a7743e03061048937c6b3aa611788/.github/workflows/dashboards-observability-test-and-build-workflow.yml#L35) from `Openesarch-Dashbaords/package.json` file, to set up `yarn`, and still found [1.21.1](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/9124fe80d6dba77a905b7cd36c306aa42a70bf2d/package.json#L470). This is causing the yarn version incompatibility, and bootstrap will fail.

Dashboards docker image, windows build scripts are using hardcoded yarn version, which will potentially be impacted, according to @peterzhuamazon 

### Impact
- All Opensearhc Dashboards Plugin CI & build
- Dashboards docker image build, windows build process, etc

### Proposed solution
- step 1: To unblock dashboards plugins CI, Opensearch-Dashboards core repo needs to update `yarn` version in `package.json` to `^1.22.1`  https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3443
- step 2: After step 1 is completed,  to unblock docker image build, windows build, we could fetch the yarn version on demand from `Openesarch-Dashbaords/package.json` , instead of hardcode.

**Comment by peterzhuamazon** [comment]
This issue is brought up late as plugins are not always following the core defined yarn version.

After glance around 5 docker images and 1 ami get impacted.

```

./release.centos.clients.x64.arm64.dockerfile:    for node_version in $NODE_VERSION_LIST; do nvm install $node_version; npm install -g yarn@^1.21.1; done
./build.centos7.opensearch-dashboards.x64.arm64.dockerfile:    for node_version in $NODE_VERSION_LIST; do nvm install $node_version; npm install -g yarn@^1.21.1; done
./test.rockylinux8.systemd-base.x64.arm64.dockerfile:RUN npm install -g yarn@1.22.18
./test.rockylinux8.opensearch-dashboards.x64.arm64.dockerfile:RUN npm install -g yarn@1.22.18
./test.centos7.performance-test.x64.dockerfile:    for node_version in $NODE_VERSION_LIST; do nvm install $node_version; npm install -g yarn@^1.21.1; done

./scripts/windows/scoop-install-commons.ps1:volta install yarn@^1.21.1
```

Among these 6 there are 2 docker images related to bundle build + integTest, and 1 ami related to bundle build, means they need to be updated now to avoid failures on 2.6.0 builds.

The rest of them can be updated at a later time.

The updates of these images/ami should retrieve the value of yarn dynamically from core osd repo, instead of hardcoding again in the template.

Thanks.

**Comment by peterzhuamazon** [comment]
Since this issue would impact on 2.6.0 release, cc @CEHENKLE @bbarani into the discussion on this.

Thanks.

**Comment by kristenTian** [comment]
Would it be easier to mitigate by downgrading the yarn version in openearch-js to be compatible with opensearch-dashboard?

**Comment by peterzhuamazon** [comment]
PRs:

* https://github.com/opensearch-project/opensearch-build/pull/3191
* https://github.com/opensearch-project/opensearch-build/pull/3212

**Comment by joshuarrrr** [comment]
Why don't we just revert https://github.com/opensearch-project/OpenSearch-Dashboards/commit/de89c527dee3a997bfffc2079dbf97e4f813e54e in `2.x`?

In general, OpenSearch Dashboards considers bumping direct dependencies (such as `@opensearch-project/opensearch`) to be a breaking change when the dependency bump contains a breaking change (which it clearly does in this case).

**Comment by joshuarrrr** [comment]
Revert PR: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3464

**Comment by kavilla** [comment]
+1 @joshuarrrr. I think the call if we want the sigv4 into OpenSearch Dashboards core, without a deep dive, I don't see why not cut a minor release OpenSearch JS client for 1.x to have this feature. And then have OpenSearch Dashboards take the minor version bump from the client.

**Comment by peterzhuamazon** [comment]
Adding @zhongnansu @derek-ho on to the change on this.
Do we need to make the changes to make the revert.

Thanks.

**Comment by zhongnansu** [comment]
@joshuarrrr
I am against reverting https://github.com/opensearch-project/OpenSearch-Dashboards/commit/de89c527dee3a997bfffc2079dbf97e4f813e54e only because it includes opensearch-js version bump

- openearch-js client 2.0 was released June, 2022. But in OSD core, we are still using `1.x`clients now. According to the [compatibility matrix](https://github.com/opensearch-project/opensearch-js/blob/main/COMPATIBILITY.md#compatibility-with-opensearch) of opensearch-js client. Client version `1.x` doesn't support OpenSearch version `2.x`, which means OSD was supposed to bump opensearch-js client lib.

- As for dashboards plugins, in any `2.x.x.x`, they know they are talking to OpenSearch `2.x`. But  opensearch-js client`1.x` is being used, as it's decided from upstream OSD core. But till now, there's no known issue complaining that plugin failed to talk to OpenSearch `2.x `using opensearch-js client `1.x`, which means plugins are not using any deprecated APIs. So there shouldn't be a problem with plugin consuming opensearch-js `2.x` now
- Plus, this commit is a feature commit that was put on the roadmap, and targeted to release in 2.6.0. Also, no backwards compatibility CI has ever failed in any PR during feature implementation stage. 

cc: @zengyan-amazon @peterzhu1992 @bbarani

**Comment by kavilla** [comment]
> Client version 1.x doesn't support OpenSearch version 2.x, which means OSD was supposed to bump opensearch-js client lib.

Might be a confusing matrix but on our site we state:
> All clients are compatible with any version of OpenSearch. 

[[SOURCE](https://opensearch.org/docs/latest/clients/index/)]

> Plus, this commit is a feature commit that was put on the roadmap, and targeted to release in 2.6.0. Also, no backwards compatibility CI has ever failed in any PR during feature implementation stage.

For build wise we usually rely on the build CI to verify and have reverted commits in the past.

**Comment by zhongnansu** [comment]
> For build wise we usually rely on the build CI to verify and have reverted commits in the past.

@kavilla @joshuarrrr 
That's why I tried to backport the fix to OSD `2.x`, so that plugin CI on `2.x` could be triggered to verify. https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3465. 
The original plugin CI failure reported in this issue has been addressed in `main`. https://github.com/opensearch-project/dashboards-maps/actions/runs/4227411858/jobs/7341865358

**Comment by kristenTian** [comment]
Could we at least test the yarn version bump fix the build?

> > For build wise we usually rely on the build CI to verify and have reverted commits in the past.
> 
> @kavilla @joshuarrrr That's why I tried to backport the fix to OSD `2.x`, so that plugin CI on `2.x` could be triggered to verify. [opensearch-project/OpenSearch-Dashboards#3465](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3465). The original plugin CI failure reported in this issue has been addressed in `main`. https://github.com/opensearch-project/dashboards-maps/actions/runs/4227411858/jobs/7341865358

**Comment by peterzhuamazon** [comment]
Awaiting: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3477

**Comment by zhongnansu** [comment]
@peterzhuamazon 
Plugin CI on main is unblocked. But the fix needs to be backported to OSD `2.x`, otherwise the same issue will happen.
I have a backport PR opened here: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3465

**Comment by zhongnansu** [comment]
> Awaiting:
> 
> * [[Manual backport 2.x][MD] Support SigV4 as a new auth type of datasource (#3058) OpenSearch-Dashboards#3477](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3477)

This PR is merged, I noticed that Plugin CI starts to fail on `2.x`, because of same yarn incompatibility. https://github.com/opensearch-project/dashboards-observability/actions/runs/4236740246/jobs/7361893066 , and the PR to fix it from OSD side is blocked. https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3465

Adding @AMoo-Miki, since I saw you opened a related issue in plugin repo about the yarn config in CI workflow. I do want to mention that the same way to configure yarn is used across almost all dashboards plugins.  https://github.com/opensearch-project/dashboards-observability/issues/290

**Comment by bbarani** [comment]
Tagging @gaiksaya as she is the release manager for 2.6.0 release.

**Comment by gaiksaya** [comment]
Hi @zhongnansu @peterzhuamazon What are the next steps here? As the today is the code cutoff date for 2.6.0 trying to see if we need to extend that from dashboards prespective.
Thanks!

**Comment by peterzhuamazon** [comment]
All images updated now in docker hub (3131 3126 3125 3123 docker-build Jenkins).
Windows image requires a redeployment later.
Thanks.

**Comment by gaiksaya** [comment]
@peterzhuamazon I do not see any PRs for adding yarn version https://github.com/opensearch-project/opensearch-build/tree/main/docker/ci/dockerfiles/current am I missing anything?

**Comment by zhongnansu** [comment]
> Hi @zhongnansu @peterzhuamazon What are the next steps here? As the today is the code cutoff date for 2.6.0 trying to see if we need to extend that from dashboards prespective. Thanks!

The next step is approve and merge in this PR: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3465, to fix yarn issue and unblock plugin CI

**Comment by AMoo-Miki** [comment]
All the effected plugins were using a flawed logic to install Node.js and Yarn runtimes based on the information they were reading from OSD's manifest. They all took the ranges OSD provided, manipulated it incorrectly and attempted to install Node and Yarn. I have gone through all the repos and raised PRs with the correct procedure on all of them.

There is also a possibility of some repos using strict versions for their own `engines.*` which is a bad and wrong practice. While I did not see this in any repo, i caught one PR that attempted to do so and commented on it.

There is also a repo that uses a file named `.node-version` that we are investigating to remove in the future; I will reach out to them if we decide to remove the file so that they can use `.nvmrc` instead.

**Comment by AMoo-Miki** [comment]
> > Hi @zhongnansu @peterzhuamazon What are the next steps here? As the today is the code cutoff date for 2.6.0 trying to see if we need to extend that from dashboards prespective. Thanks!
> 
> The next step is approve and merge in this PR: [opensearch-project/OpenSearch-Dashboards#3465](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3465), to fix yarn issue and unblock plugin CI @gaiksaya

That PR is not an acceptable solution; OSD cannot make arbitrary changes to accommodate mistakes in CI scripts of plugins.

**Comment by kristenTian** [comment]
Should we also add the `.npmrc` to enforce the restriction the node version in OSD core?

**Comment by AMoo-Miki** [comment]
Kristen, my goal is relaxing all of these restrictions. If `nvmrc` would allow me, I would have used a range there as well.

**Comment by peterzhuamazon** [comment]
All new images for Jenkins have been deployed with yarn 1.22.19.
