### ISSUE TITLE
[release]: OpenSearch-Benchmark

### ISSUE THREAD

**Issue by IanHoang** [opensearch-project/opensearch-build#3224]
### What is the name of your component?

OpenSearch-Benchmark (OSB)

### What is the link to your GitHub repo?

https://github.com/opensearch-project/opensearch-benchmark

### Targeted release date

Pypi - March 9th
Docker - April 13th

### Where should we publish this component?

Pypi, Docker

### What type of artifact(s) will be generated for this component?

N/A

### Have you completed the required reviews including security reviews, UX reviews?

AppSec Review was completed around Oct 2021

### Have you on-boarded automated security scanning for the GitHub repo associated with this component?

Yes, please enable automated CVE scanning on this repo

**Comment by gaiksaya** [comment]
[Triage] PyPi needs to be released by March 9. Will sync up with @rishabh6788 to get this in next week.
Thanks!

**Comment by gaiksaya** [comment]
OpenSearch Benchmark was onboarded to 1-click release process https://github.com/opensearch-project/opensearch-benchmark/pull/226 and was released successfully on PyPi: https://pypi.org/project/opensearch-benchmark/0.2.0/

**Comment by gaiksaya** [comment]
Released on dockerhub too https://hub.docker.com/r/opensearchproject/opensearch-benchmark
