### ISSUE TITLE
[BUG] OpenSearch container does not allow for graceful termination

### ISSUE THREAD

**Issue by shikharbhardwaj** [opensearch-project/opensearch-build#3229]
**Describe the bug**

OpenSearch container does not do a graceful shutdown when a termination signal (SIGTERM/SIGINT) is sent.
This issue was discovered when running the official docker image within Kubernetes, where a rollout would cause the container to be terminated forcefully after `terminationGracePeriodSeconds ` instead of catching the `SIGTERM` signal sent and shutting down cleanly.

This could be fixed by using a proper init process (like `tini`) as PID 1 instead of a shell, which would register signal handlers for these termination signals and allow for graceful termination. An example for this change is in the gist below.

Resources with more details on this issue:
* https://hynek.me/articles/docker-signals/
* https://engineeringblog.yelp.com/2016/01/dumb-init-an-init-for-docker.html

**To Reproduce**
1. Run an OpenSearch container using the official docker image (tested on both 1.3.7 and 2.5.0).
2. Send a `SIGTERM` or `SIGINT` to the container and it will not terminate.

Gist here with more detailed reproduction/remediation steps: [OpenSearch container termination signal handling](https://gist.github.com/shikharbhardwaj/9ba1f31fe9f5083b9f64a8976414c37e)

**Expected behavior**
The container should listen for these termination signals and shutdown gracefully.

**Plugins**
N/A

**Host/Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Docker: 20.10.16
 - OpenSearch versions: 1.3.7, 2.5.0

**Additional context**

**Comment by peterzhuamazon** [comment]
Hi @shikharbhardwaj, if you dont mind, we would like to invite you to open a PR if you have any solutions.
We would love to assist in the process.

Thanks!

**Comment by shikharbhardwaj** [comment]
@peterzhuamazon sounds good, I will raise a PR for this.

**Comment by peterzhuamazon** [comment]
Added review, sorry for the delay on this @shikharbhardwaj .

Thanks.

**Comment by chawinphat** [comment]
@peterzhuamazon commenting so you can assign me

**Comment by chawinphat** [comment]
@peterzhuamazon 

I was able to gracefully terminate using Tini as described above only with the path being '/bin/tini". Using the relative path "./tini" gives the error: 

`teddyt@Teddys-MacBook-Pro docker % docker run -it -p 9200:9200 -p 9600:9600 -e "discovery.type=single-node" chawinphat/opensearch:1.3.9
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "./tini": stat ./tini: no such file or directory: unknown.`

**Comment by peterzhuamazon** [comment]
> Hi @shikharbhardwaj we have solved this by using the exec command in the docker entrypoint file.
> 
> https://github.com/opensearch-project/opensearch-build/blob/d99811b3cfab45e950cdd2ed7f004074baf7d93e/docker/release/config/opensearch/opensearch-docker-entrypoint.sh
> 
> If the command in line 101 is started using the exec command the opensearch process will run with PID 1 and the TERM signal will be sent to this process.

Hi @239487230597507 would you willing to share your changes?
If so, would you mind contributing the changes as a PR?

This issue has been opened for a while and we would like to resolve it soon. Thanks 😄

**Comment by cinimins** [comment]
Any updates here? It happened already for the 2nd time that our opensearch got corrupted because the container got killed by Kubernetes (probably duing some write-operation) after the termination grace period was exceeded.

Since the author of the PR hasn't commented in almost over a year, should we open a new PR based on his branch or do you want to go with the approach by @239487230597507 ?

**Comment by 239487230597507** [comment]
@cinimins @peterzhuamazon I will try to create a PR. Unfortunately I am a complete Github noob so it might take a couple of days. :D

**Comment by nanoguy0** [comment]
To anyone who is finding this thread like myself, for the current workaround, I am using the --init option on Docker 1.13+ which uses tini and is part of https://github.com/krallin/tini. 

Example from my compose file:
```yml
  opensearch:
    image: opensearchproject/opensearch:latest
    init: true
```
