### ISSUE TITLE
[Enhancement]: Adding more outputs in the OpenSearch build scripts for better clarifications

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#3235]
### Describe the bug

[Enhancement]: Adding more outputs in the OpenSearch build scripts for better clarifications

The https://github.com/opensearch-project/opensearch-build/blob/main/scripts/components/OpenSearch/build.sh script is running multiple gradle tasks. This can often confuse users as they are not sure what is currently being run. Suggest adding some more text output before the gradle task run, make it much more clear to the users.

Thanks.

### To reproduce

Build OpenSearch core with the build repo, see output before each task.

### Expected behavior

Showing output such as "Start building x" before the task.

### Additional context

Example issue.

**Comment by gaiksaya** [comment]
Hi @peterzhuamazon Looks like gradle is doing the heavy lifting in that script. Do we want to add more details to gradle tasks or build script?

**Comment by AlisherKaziz** [comment]
[CCI] Hello @peterzhuamazon can i contribute to this issue?

**Comment by peterzhuamazon** [comment]
Yes @AlisherKaziz you are welcome to contribute this issue and start a PR.
Thanks!

**Comment by Spectorisimo** [comment]
Hello, can I work on this issue?

**Comment by peterzhuamazon** [comment]
> Hello @peterzhuamazon, can I work on this issue?

I will put you on the assigner list as well, Thanks!
