### ISSUE TITLE
[Testing Confirmation] Confirm current testing requirements

### ISSUE THREAD

**Issue by scrawfor99** [opensearch-project/opensearch-build#3241]
### Is your feature request related to a problem? Please describe

As part of the discussion around implementing an organization-wide testing policy, I am visiting each repo to see what tests they currently perform. I am conducting this work on GitHub so that it is easy to reference. 

Looking at the OpenSearch Build repository, it appears there is 

| Repository  | Unit Tests | Integration Tests | Backwards Compatibility Tests | Additional Tests | Link | 
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | 
| OpenSearch Build | <li>- [x] </li> | <li>- [x] </li> | <li>- [ ] </li> | Certificate of Origin, Link Checker, License Header, Groovy Tests, Yaml Lint, Python Tests  | https://github.com/opensearch-project/opensearch-build/issues/3241 | 

I know you have scripts for running backward compatibility tests, but I was not sure if you had any you ran against your own changes. If you do, please let me know. 

I also don't see any requirements for code coverage in the testing documentation. If there are any specific requirements could you respond to this issue to let me know? 

### Describe the solution you'd like

If there are any tests I missed or anything you think all repositories in OpenSearch should have for testing please respond to this issue with details.

**Comment by gaiksaya** [comment]
[Triage] This is build repo so integration tests do not apply. We do have unit tests and code coverage is applied to it. 
@scrawfor99 Is anything more expected here?
Thanks!

**Comment by scrawfor99** [comment]
Hi @gaiksaya, thank you for following up. I will make sure to note your feedback. It sounds like you are all set!

**Comment by bbarani** [comment]
Closing this issue as we have confirmed that we are all set with testing requirements
