### ISSUE TITLE
[release]: One-click release for opensearch-rs

### ISSUE THREAD

**Issue by Xtansia** [opensearch-project/opensearch-build#3247]
### What is the name of your component?

opensearch-rs - OpenSearch Rust language client

### What is the link to your GitHub repo?

https://github.com/opensearch-project/opensearch-rs

### Targeted release date

N/A

### Where should we publish this component?

https://crates.io/crates/opensearch

### What type of artifact(s) will be generated for this component?

Rust crate, which is a source distribution similar to an NPM package.

### Have you completed the required reviews including security reviews, UX reviews?

Yes

### Have you on-boarded automated security scanning for the GitHub repo associated with this component?

Mend/WhiteSource config has been merged: https://github.com/opensearch-project/opensearch-rs/pull/93

### Additional context

Depends on:
- [ ] #2505's - publishToCrates functionality

**Comment by wbeckler** [comment]
@bbarani can you help get this prioritized. The release of the rust client contains long overdue fixes for connectivity for OpenSearch Serverless.

**Comment by prudhvigodithi** [comment]
Hey @wbeckler and @Xtansia can you please add the target date for this release?
@jordarlu

**Comment by gaiksaya** [comment]
Did some research around publishing the rust clients to crates.io.

Here are few findings:
1. There is no mechanism to sign crates (yet!) See https://github.com/rust-lang/crates.io/issues/75 for details
2. We need to have rust toolchain installed to run crago commands. (Adding cargo installation on docker image used for release)
3. CI systems you can use the CARGO_REGISTRY_TOKEN environment variable to publish programmatically or just use --token. https://doc.rust-lang.org/cargo/commands/cargo-publish.html
```
cargo publish --token <token>
```

cc: @Xtansia

**Comment by gaiksaya** [comment]
The above repo is onboarded to 1-click release process. Please re-open in case of any failures. 
Thanks!
