### ISSUE TITLE
Mechanism to link the DockerFile name/location of a docker image.

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/opensearch-build#3259]
### Is your feature request related to a problem? Please describe

Mechanism to link the dockerfile name/location of a docker image.

### Describe the solution you'd like

1) Simply just update the existing [README](https://github.com/opensearch-project/opensearch-build/tree/main/docker/release) file.
2) Dockefile supports [LABELS](https://docs.docker.com/engine/reference/builder/#label) Add the dockerfile name as a label
`LABEL "DOCKERFILE"="opensearch.al2.dockerfile"` and using `docker image inspect` should output all the added labels.
3) Comment on top of the checked in dockerfile that denotes the image will be built with a name and latest number tag.

**Comment by peterzhuamazon** [comment]
I vote for both 2 and 3 so we have good documentations on both sides.

**Comment by peterzhuamazon** [comment]
Example label already used in production release images, we need to apply similar to the ci images:
https://github.com/opensearch-project/opensearch-build/blob/main/docker/release/dockerfiles/opensearch.al2.dockerfile#L106

**Comment by peterzhuamazon** [comment]
Example label entry:
http://label-schema.org/rc1/

**Comment by aabeshov** [comment]
Hi @prudhvigodithi , can I help in solving this issue ? Is it still relevant ?
I am newbie at OpenSource Developing and I am looking for first issue.

**Comment by prudhvigodithi** [comment]
Hey @aabeshov, Welcome to OpenSearch community, yes this issue is still relevant, please raise a PR when you get a chance.
Thank you

**Comment by aabeshov** [comment]
@prudhvigodithi Hello ,just committed PR , could you check it please ? 
And wasn't sure if I need to change README, because of the first comment.
