### ISSUE TITLE
Add Opensearch-ci-bot for write access to Opensearch-Benchmark repo

### ISSUE THREAD

**Issue by IanHoang** [opensearch-project/opensearch-build#3286]
### Is your feature request related to a problem? Please describe

Based on step 1 of this section, opensearch-ci-bot needs write access. 

https://github.com/opensearch-project/opensearch-build/blob/main/ONBOARDING.md#onboarding-to-universal--1-click-release-process

Currently, it doesn't seem like it has write access yet. 

### Describe the solution you'd like

Enable  opensearch-ci-bot to have write access.

**Comment by peterzhuamazon** [comment]
Added bot, thanks.
