### ISSUE TITLE
Adding docker-patch functionality to patch latest images in major tag

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#3303]
Adding docker-patch functionality to patch latest images in major tag.

Requirements:
1. Use the docker image label to figure out the build number of latest major version docker image.
2. Use the build number to find out the distribution build workflow logs.
3. Use the log to find out the docker-build workflow run number.
4. Use the docker-build run number to re-run the workflow to rebuild images.
5. Before pushing we should backup the old opensearchstaging images
6. Run docker-promotion to run the docker image publishing again.

We will only patch the latest version in 1.x, 2.x, and so on.

Thanks.a

**Comment by peterzhuamazon** [comment]
Writing some design ideas on this.

**Comment by peterzhuamazon** [comment]
Proposal:

To streamline the process of docker image patching/re-release, I suggest the creation of a master Jenkins workflow and a related library. By grouping multiple workflows together, we can perform the necessary updates in one go. This is possible because we are already tracking the docker image building id using the build id of the distribution-build workflow.

Steps as follow:

* A master workflow named docker-patching
    * Parameters:
        * PRODUCT: OpenSearch / OpenSearch-Dashboards
        * VERSION: Version of PRODUCT
        * CVE_MITIGATION_LEVEL: The level of CVEs get migrated when comparing old and new images, 
                                                               ex: HIGH, CRITICAL
    * Functions:
        * Trigger patchDockerImage.groovy lib



* A Jenkins lib named patchDockerImage.groovy
    * Parameters (value passed from the docker-patching workflow):
        * product
        * version
        * cveMitigationLevel
    * Functions:
        * Use docker API, combined product and version to find the corresponding image on opensearchproject official docker repository (i.e. opensearchproject/opensearch:2.7.0)
        * Get the metadata of label layer and retrieve the label information
            * LABEL org.label-schema.schema-version=1.0 org.label-schema.name=opensearch org.label-schema.version=2.6.0 org.label-schema.url=https://opensearch.org/ org.label-schema.vcs-url=https://github.com/OpenSearch org.label-schema.license=Apache-2.0 org.label-schema.vendor=OpenSearch org.label-schema.description=7160 org.label-schema.build-date=2023-02-24T20:20:55Z
        * Retrieve the build time of the image from labels
        * Retrieve the dist build id of the corresponding distribution-build workflow from labels
        * Trigger a docker-copy run to backup the image with a new tag in opensearchstaging such as using above product, version, build time, dist build id information.
            * Original Image: opensearchstaging/opensearch:2.7.0.7160
            * Backup Image: opensearchstaging/opensearch:2.7.0.7160.20230224
            * If there is already an image with the same name, skip
        * Use the dist build id to retrieve the log of related distribution-build runs
        * Parse log content and retrieve the docker build id of the corresponding docker-build workflow
        * Use the docker build id to retrieve the parameter of the corresponding docker-build run
        * Trigger a new docker-build with the same parameters
        * Trigger a docker-scan to scan the new images
        * Trigger a docker-promotion to release the image if the above docker-scan shows no CVEs within the cveMitigationLevel. Else, exit with error and inform user about the issue.

**Comment by Divyaasm** [comment]
Associated flow for the set of Docker related Jenkins Jobs called in a sequential order by the re-release Shared Library
<img width="919" alt="Screenshot 2023-07-21 at 1 15 27 PM" src="https://github.com/opensearch-project/opensearch-build/assets/113469545/2bd83b63-7b09-4591-b753-1b0e1e5cdaa9">

**Comment by gaiksaya** [comment]
Closing this issue in favor of #3930
