### ISSUE TITLE
Make code compatible to run a docker image

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/opensearch-build#332]
We want to make sure the code used to build/test artifacts runs on a documented docker image

* OpenSearch Linux x64/arm64 builds/test workflows - [ci-runner.centos7.dockerfile](https://github.com/opensearch-project/opensearch-build/blob/main/bundle-workflow/dockerfiles/ci-runner.centos7.dockerfile)
* OpenSearch Dashboard Linux builds - ? 
* OpenSearch Windows build workflow - ?

**Comment by dblock** [comment]
https://github.com/opensearch-project/opensearch-build/issues/33

**Comment by peternied** [comment]
[Triage] Rather than supporting all platforms lets lock into to a docker image that will be predictable.

**Comment by cjcjameson** [comment]
@peternied we're looking for ways to help #33 and get Windows installers. does your comment mean we should find other ways to help?

**Comment by peternied** [comment]
@cjcjameson Good callout, I really should have said lock into a single version of `*nix`, the windows platform is entirely different and deserving of support!  

If you were to start here with a docker image, that establishes the basis of a build platform - https://github.com/opensearch-project/opensearch-build/tree/main/bundle-workflow/dockerfiles

If you create a [Meta] issue to support Windows platform we could collaborate on what the roadmap would look like, or I could create it.

**Comment by bbarani** [comment]
@gaiksaya Can you please review and close this issue if this has been already addressed?

**Comment by gaiksaya** [comment]
We are good for linux but for windows @peterzhuamazon can add more. I dont think we are building on docker for windows today. https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/opensearch/distribution-build.jenkinsfile#L303-L307

**Comment by peterzhuamazon** [comment]
We only have windows ami as windows docker must run on windows, but we can dig into that as windows integTest would be very beneficial for this.

Thanks.

**Comment by gaiksaya** [comment]
I believe docker image is needed for build as well. Not just integ-test. Is there a plan to add that too?

**Comment by gaiksaya** [comment]
We have added docker images for all builds/tests/release except for windows. However, the documentation needs to be added for the same.

**Comment by gaiksaya** [comment]
Added details here: https://github.com/opensearch-project/opensearch-build/wiki/Building-an-OpenSearch-and-OpenSearch-Dashboards-Distribution#building-from-source

Closing this issue.
