### ISSUE TITLE
Proposal for a job/webpage to create issue across all repos.

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/opensearch-build#3349]
### Is your feature request related to a problem? Please describe

Today we use a combination of `meta` and `gh` cli to create issues out of a template across all the repos, this has its own challenges for the workspace setup on the local, following a [series of steps ](https://github.com/opensearch-project/opensearch-plugins/blob/main/META.md), but now and then a developer/release-manager have to spend some time to create issues/campaigns across multiple repos, this also include writing the template and setting up the `meta` and `gh` environment.

### Describe the solution you'd like

A job/webpage to create issue across all repos that looks as follows

![Screenshot 2023-03-27 at 2 21 27 PM](https://user-images.githubusercontent.com/28733332/228071008-79a6c654-0f53-4959-9798-351e50fa01ca.png)

The job/webpage/tool can have 3 conditions.
1) Create a new issue and click create, feeding in the issue context and choosing the plugin repos (a radio buttons), the plugin list can be dynamically loaded from the existing [plugins list](https://github.com/opensearch-project/opensearch-plugins/blob/main/.meta).
2) Update the existing issue: The update can be done with existing github supported GraphQL, here is the sample of existing issue update used by [release-notes tracker](https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/release-notes-check/release-notes-check.jenkinsfile#L102-L110).
3) Finally an option to have delete/close: This can be used in case of an issue to be deleted and recreated or finally close the all the issues.

### Additional context

This is just a proposal setup and would save lot of time for a release manager or in general for a user who want to create multiple campaigns and stories/issues across all the repos. If this is an overkill and have something better and simpler other than configuring `meta` `gh` with issue template (a .MD file), open for suggestions and can close this issue :)

**Comment by dblock** [comment]
I don't recommend web pages. This requires tokens and what not. However, we could probably use tooling to create campaigns. It could be a bot that's installed in the org and we could take an issue, add `@bot create campaign` or something like that and it would go and create issues.

**Comment by Divyaasm** [comment]
This can be confined to Github workflow and can be run in individual repos.

**Comment by prudhvigodithi** [comment]
This can be done by creating a github action and having a workflow using this GH action, this workflow will have inputs same as [described above](https://github.com/opensearch-project/opensearch-build/issues/3349#issue-1642856730) and can be part of each repo. So when this workflow is triggered from the repo the meta/campaign/issue is created from that source repo and across other repos.

**Comment by prudhvigodithi** [comment]
Closing this issue as the Component release issues are auto-created along with the main release issue part of the build repo.
Example for 2.10.0 https://github.com/opensearch-project/opensearch-build/issues/3743
