### ISSUE TITLE
[Bug]: Gradle check workflows are failing with docker throttling

### ISSUE THREAD

**Issue by andrross** [opensearch-project/opensearch-build#3358]
### Describe the bug

As far as I can tell, all gradle check workflows in the opensearch-project/OpenSearch repository are failing with some version of the following error:

```
> Task :test:fixtures:gcs-fixture:composeBuild FAILED
Building gcs-fixture
Service 'gcs-fixture' failed to build: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

https://build.ci.opensearch.org/job/gradle-check/13164/ is the first instance I have found and it ran at 6:17:46 PM (UTC)

### To reproduce

Do anything to trigger a gradle check workflow (e.g. submit a PR)

**Comment by peterzhuamazon** [comment]
Per this note:
https://www.docker.com/increase-rate-limits/

```
The rate limits of 100 container image requests per six hours for anonymous usage, and 200 container image requests per six hours for free Docker accounts are now in effect. Image requests exceeding these limits will be denied until the six hour window elapses.

NOTE: Docker Pro and Docker Team accounts enable 5,000 pulls in a 24 hour period from Docker Hub.
```

There are few approaches I see:
1. Have the workflow agent login as the admin bot user, to consume more pulls from the docker org/team. The problem with this approach is it would be not safe to login as bot user for a long time. Plus the rate is still 5000 within 24hr which is not ideal.
2. Since docker does not allow use default switching registry: https://github.com/moby/moby/issues/7203. It is better to switch all the pull of docker agent image from dockerhub to ECR, to at least reduce that part of the pull rate.

Welcome more suggestions.

Thanks.

**Comment by kotwanikunal** [comment]
List of Dockerfiles within OpenSearch and their corresponding base OS:

```
./test/fixtures/gcs-fixture/Dockerfile -> FROM ubuntu:18.04
./test/fixtures/krb5kdc-fixture/Dockerfile -> FROM ubuntu:18.04
./test/fixtures/minio-fixture/Dockerfile -> FROM ubuntu:14.04
./test/fixtures/s3-fixture/Dockerfile -> FROM ubuntu:18.04
./test/fixtures/azure-fixture/Dockerfile -> FROM ubuntu:18.04
./distribution/docker/build/docker/Dockerfile -> FROM centos:8 AS builder
./distribution/docker/build/ppc64le-docker/Dockerfile -> FROM centos:8 AS builder
./distribution/docker/build/arm64-docker/Dockerfile -> FROM centos:8 AS builder
./distribution/docker/build/s390x-docker/Dockerfile ->  FROM centos:8 AS builder
```

**Comment by kotwanikunal** [comment]
@peterzhuamazon Also it looks like the `minio` tag is different for ECR


2022.11.17 | image manifest | 4 months ago | public.ecr.aws/bitnami/minio:2022.11.17 | 78.7 MB
-- | -- | -- | -- | --


https://gallery.ecr.aws/bitnami/minio

**Comment by peterzhuamazon** [comment]
Three way changes:
1. @kotwanikunal identify the number of docker pull in gradle check and send corresponding PRs.
2. @peterzhuamazon create a new user just for pulling docker images on dockerhub.
3. @peterzhuamazon sync the ci-runner images between dockerhub and ecr.
4. @peterzhuamazon change the pointer of the jenkinsfile docker pull from dockerhub to ecr.

**Comment by andrross** [comment]
@peterzhuamazon What is the latest status here? I saw a [throttling failure](https://github.com/opensearch-project/OpenSearch/pull/6968#issuecomment-1496293246) this morning. Was #3364 supposed to mitigate the issue?

/cc @jordarlu

**Comment by peterzhuamazon** [comment]
This issue should be resolved for now.
Monitoring.

**Comment by peterzhuamazon** [comment]
```

> Task :test:fixtures:azure-fixture:composeBuild
Building azure-fixture

```

https://build.ci.opensearch.org/job/gradle-check/13565/console

Yes!

**Comment by peterzhuamazon** [comment]
No more:
```


> Task :test:fixtures:azure-fixture:composeBuild FAILED
Service 'azure-fixture' failed to build: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

**Comment by peterzhuamazon** [comment]
Closing now.
Thanks.
