### ISSUE TITLE
[Enhancement] Better handle of switching node version for OSD core

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#3362]
As of now, if there is a version bump in nodejs for OSD core, the developer needs to update these values in dockerfile and ami template so that the images/amis can be rebuild.

- https://github.com/opensearch-project/opensearch-build/pull/3356
- https://github.com/opensearch-project/opensearch-ci/issues/258

The above is understandable as we do not want to use older version of node to build OSD and its plugins, even if they are compatible with lower versions defined by this PR:
- https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3463

However, the current switching of the node version is not ideal, as it uses the .nvmrc value to switch version, and sometimes if the images are not bundled with the requested version, the build fail:
https://github.com/opensearch-project/opensearch-build/commit/1116d3b3698accaec39cd498975dec0035e1963c#diff-764d0f380e0ea7d984b96da62499e5bb1c9ad946ef6834fede55159c7dc13366
https://build.ci.opensearch.org/blue/organizations/jenkins/distribution-build-opensearch-dashboards/detail/distribution-build-opensearch-dashboards/5794/pipeline/165

In discussing with @AMoo-Miki we note that node version change is going to be rapid later on in order to fix more cves related to nodejs.

We also might need to support multiple version in .nvmrc.

Since we do not want to do a installation of dependency during the build, this needs to have some improvements in both categories:
1. Quick and easy quicker to rebuild images/amis after the updates in code.
2. Ability to switch node version than the default nvm use abilities.

Thanks.

**Comment by prudhvigodithi** [comment]
[Triage]
Need a solution to fetch the node version from the Dashboard repo during the docker build, this way a manual PR is not required every time a new version is added.
@peterzhuamazon

**Comment by AMoo-Miki** [comment]
So far, `.nvmrc` has been the source truth:
1. It can handle only one version
2. dockerfile has been an exception

I believe we should:
* keep `.nvmrc` as the source of truth because it will be how contributors set their environment up,
* get dockerfile to match `.nvmrc`, and
* talk about `"We also might need to support multiple version"`

**Comment by peterzhuamazon** [comment]
This has been partially solved by @AMoo-Miki to allow fallbacks of node14:
* https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4151

As for faster build of images, this PR has added some quick syncing to mitigate the issues a bit more.
* https://github.com/opensearch-project/opensearch-build/issues/3386
As of now we dont see this as a main bottleneck to node18 upgrade, close for now.

Thanks.
