### ISSUE TITLE
[Bug]: Change PA log name

### ISSUE THREAD

**Issue by dzane17** [opensearch-project/opensearch-build#3373]
### Describe the bug
PA log has been moved out of `/tmp` dir to `$OPENSEARCH_HOME/logs/PerformanceAnalyzer.log` [PR](https://github.com/opensearch-project/performance-analyzer-rca/pull/315). Please change PA log name [here](https://github.com/opensearch-project/opensearch-build/blob/main/docker/release/config/opensearch/opensearch-docker-entrypoint.sh#L61) from `performance-analyzer.log` to `PerformanceAnalyzer.log`.

**Comment by peterzhuamazon** [comment]
Awaiting: 
* https://github.com/opensearch-project/opensearch-build-libraries/pull/186

**Comment by peterzhuamazon** [comment]
PR: 
* https://github.com/opensearch-project/opensearch-build/pull/3394

**Comment by peterzhuamazon** [comment]
Complete now.
