### ISSUE TITLE
[Bug]: Fix missing local test cluster logs for integration tests

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/opensearch-build#3382]
### Describe the bug

Currently, the local test cluster only records stdout and stderr for local cluster that is deployed by the test workflow. 
Missing logs files:
```
- gc.log.00
- opensearchcluster1.log
- opensearchcluster1_deprecation.json
- opensearchcluster1_deprecation.log
- opensearchcluster1_index_indexing_slowlog.json
- opensearchcluster1_index_indexing_slowlog.log
- opensearchcluster1_index_search_slowlog.json
- opensearchcluster1_index_search_slowlog.log
- opensearchcluster1_server.json
- opensearchcluster1_task_detailslog.json
- opensearchcluster1_task_detailslog.log
```

### To reproduce

Run below command locally and see that test-results/../local-test-cluster folder only includes stdout and stderr files
```
./test.sh integ-test manifests/2.7.0/opensearch-2.7.0-test.yml --component geospatial -p opensearch=https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/2.7.0/7325/linux/x64/tar --keep
``` 

### Expected behavior

Should record all log files 

### Additional context

Estimate: 3 points

### Acceptance Criteria

- [ ]  Local cluster logs should be recorded in test-results folder 
- [ ] The temp directory (where local opensearch and dashboards is downloaded) should be cleaned up after each test
- [ ] Add tests cases verifying the behavior

**Comment by gaiksaya** [comment]
That's the missing piece @zelinh. See the tmp directory after using `--keep` option. The cluster logs are present where opensearch is downloaded. so for 2.7.0 `/some/tmp/directory/opensearch-2.7.0/logs/*`

**Comment by zelinh** [comment]
Basically the reason of these missing logs is that the workflow is forced to deleted everything when terminating the local cluster for tarball & zip. 
e.g. 
https://github.com/opensearch-project/opensearch-build/blob/c871a82509a3588d60ded128f45b2c7ec08771b9/src/test_workflow/integ_test/distribution_tar.py#L41-L43

I would raise a PR to remove this part so the `local-test-cluster` folder within the TemporaryDirectory would subject to the `keep` argument.

**Comment by rishabh6788** [comment]
Do we have any anecdotes from plugin teams requiring any of the above mentioned logs apart from the OS log which is present in `stdout` file?

**Comment by zelinh** [comment]
Closing this issue as this has been fixed.
