### ISSUE TITLE
[Enhancement] Make ci-runner images easier to build and sync between different container registries

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#3386]
Hi,
After this PR:
* https://github.com/opensearch-project/opensearch-build/pull/3364

1. We need to improve how we build docker images as well as how to sync between different container registries.
2. Right now we will still build image of ci-runner and push to docker staging, then it should be easily synced to ecr staging without the need to manually sync or one by one through the docker-copy workflows.

Thanks.

**Comment by prudhvigodithi** [comment]
[Triage]
@peterzhuamazon is working on this issue.
