### ISSUE TITLE
Add jenkins file running all OSD integration tests in parallel

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/opensearch-build#3412]
### Is your feature request related to a problem? Please describe

See https://github.com/opensearch-project/opensearch-build/issues/2144

Currently all dashboard integration tests are run serially which takes a long time to run and is not easily reproducible for a single component. 

### Describe the solution you'd like

Need to run each component integration test parallely at CI level.

### Acceptance Criteria

- [x] All dashboard components' integration tests should run parallely 
- [x] Should be able to run all or some components. eg: Run only AD-dashboards integration tests instead of all
- [x] The jenkins file should be source coded and contain test cases

**Comment by Divyaasm** [comment]
Closed by https://github.com/opensearch-project/opensearch-build/pull/3316 and https://github.com/opensearch-project/opensearch-build/pull/3465
