### ISSUE TITLE
Website "Downloads.html" page does not have the most recent artifacts 

### ISSUE THREAD

**Issue by scrawfor99** [opensearch-project/opensearch-build#3426]
### Is your feature request related to a problem? Please describe

Hi all,

I am reaching out here and on the documentation repo related to an issue filed over on the [security repository](https://github.com/opensearch-project/security/issues/2710). Basically, we had a CVE that was fixed last week but a user found themselves struggling to get the corrected version. They were downloading the most recent OpenSearch version from the [website](https://opensearch.org/downloads.html), but the security patch that they wanted was not present in the distribution. After looking into this for them, I noticed we are currently packaging the version offered on release and then not updating that package when new changes are made.

I understand that we want to offer a stable version on the website and that we go through an extensive process during the releases. However, I was wondering if we could add a drop down menu or something similar for each version which could offer patched versions of the total OpenSearch builds in-between releases? Similar to how Jenkins continually updates the components. 

### Describe the solution you'd like

A link users could click to download patched minor versions from the website.

**Comment by dblock** [comment]
Reading https://github.com/opensearch-project/security/issues/2710 it sounds like the 2.6.0 download on the website was correct, but the download on dockerhub for 2.6.0 contained more fixes?

**Comment by rishabh6788** [comment]
@scrawfor99 Could you please share the exact url in question here?

**Comment by dblock** [comment]
I think https://github.com/opensearch-project/security/issues/2710#issuecomment-1516821441 explains what's going on.

These fixes were not made as part of 2.6.0, they were applied after 2.6.0, and will be in 2.6.1 or 2.7.0, whichever exists first. Neither exists at the time of writing this.

Fixes cannot be "retroactively" applied to 2.6.0 because that was already released. We do not modify released products, that would create many different kinds of versions 2.6.0 out there, and users would be reporting bugs in different 2.6.0s. So, we release 2.6.1 if we find a critical vulnerability and need to make a release in a hurry (e.g. log4j), or 2.7.0 that includes fixes for any medium+ CVEs, which is what's next at the time of writing.

To summarize, the downloaded 2.6.0 version does not contain the fixes because they were made after 2.6.0 was released.

I'm going to close this issue. Does this help @Bogendra? Anything you'd like us to do differently?

**Comment by Bogendra** [comment]
> I think [opensearch-project/security#2710 (comment)](https://github.com/opensearch-project/security/issues/2710#issuecomment-1516821441) explains what's going on.
> 
> These fixes were not made as part of 2.6.0, they were applied after 2.6.0, and will be in 2.6.1 or 2.7.0, whichever exists first. Neither exists at the time of writing this.
> 
> Fixes cannot be "retroactively" applied to 2.6.0 because that was already released. We do not modify released products, that would create many different kinds of versions 2.6.0 out there, and users would be reporting bugs in different 2.6.0s. So, we release 2.6.1 if we find a critical vulnerability and need to make a release in a hurry (e.g. log4j), or 2.7.0 that includes fixes for any medium+ CVEs, which is what's next at the time of writing.
> 
> To summarize, the downloaded 2.6.0 version does not contain the fixes because they were made after 2.6.0 was released.
> 
> We do have daily builds with all the fixes, but that's untested software, and is not recommended for production, hence it's not on the downloads page.
> 
> I'm going to close this issue. Does this help @Bogendra? Anything you'd like us to do differently?

Thanks for the clarification @dblock . Yes, this makes sense. 
But the issues I mentioned (Json-smart and Snakeyaml) are high CVE vulnerabilities. Based on your comment, I'm assuming there would be a release 2.6.1 that includes these fixes. Or such release would be available only for critical but not high CVEs ? If latter is the case, them we would have to wait for the official 2.7.0 release that would contain these fixes. My understanding was any high/medium vulnerabilities would warrant a patch version change release (2.6.1 or 2.6.2). Please correct me if my understanding is wrong and the usual release path is to wait for the next minor or major releases only ?

**Comment by Bogendra** [comment]
> @Bogendra I may have misspoken. Per https://opensearch.org/releases.html we follow [OpenSSF’s best practices for patching publicly known vulnerabilities](https://bestpractices.coreinfrastructure.org/en/criteria/0?details=true&rationale=true#0.vulnerabilities_fixed_60_days), and we make sure that there are no unpatched vulnerabilities of medium or higher severity that have been publicly known for more than 60 days in our actively maintained versions.

@dblock  - does this mean we can expect a patch to be applied to the 2.6.0 release containing the known high and medium vulnerabilities ? if yes, can we expect that the new patch to be available for download on the download page website ?

**Comment by dblock** [comment]
2.7.0 was released today (https://opensearch.org/blog/get-started-opensearch-2-7-0/) and the fixes should be available in it
