### ISSUE TITLE
Remove notifications from 1.1, move to 2.0

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#343]
**Is your feature request related to a problem? Please describe.**
Looks like notifications isn't shipping as part of 1.1?

**Describe the solution you'd like**
Remove it from https://github.com/opensearch-project/opensearch-build/blob/main/manifests/opensearch-1.1.0.yml and create a 2.0 manifest?

**Comment by peternied** [comment]
> create a 2.0 manifest?

@dblock Do you mean a `1.2.0` manifest?

**Comment by dblock** [comment]
> > create a 2.0 manifest?
> 
> @dblock Do you mean a `1.2.0` manifest?

We can make a 1.2 manifest when OpenSearch has a branch with 1.2.

We already have an OpenSearch 2.0 branch (main).

So ... yes?

**Comment by peternied** [comment]
Thanks for the clarification - I was expecting that when the OpenSearch core repository has a viable build to create a min of, they would add it.  Until core creates the manifest it seems like that could be a signal of its state.

**Comment by dblock** [comment]
> Thanks for the clarification - I was expecting that when the OpenSearch core repository has a viable build to create a min of, they would add it. Until core creates the manifest it seems like that could be a signal of its state.

I think we can go further, https://github.com/opensearch-project/opensearch-build/issues/388.

**Comment by peternied** [comment]
[Triage] Notifications can onboard when they are ready
