### ISSUE TITLE
[Bug]: Incorrect URL of OS build manifest passed into OSD integ test parameter 

### ISSUE THREAD

**Issue by zelinh** [opensearch-project/opensearch-build#3432]
### Describe the bug

The URL of OS build manifest passed into OSD integ test parameter is wrong in our `distribution-build-opensearch-dashboards` jenkins workflow. 

The correct URL for example for 2.7.0 should be `https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/2.7.0/latest/linux/x64/tar/builds/opensearch/manifest.yml`

But in our workflow, it's `https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/2.7.0/latest/linux/x64/tar/builds/opensearch-dashboards/manifest.yml `

e.g. 
Failing OSD integ test: https://build.ci.opensearch.org/job/integ-test-opensearch-dashboards/3451/console

I think the reason comes from 
https://github.com/opensearch-project/opensearch-build/blob/e637dfdd3b40c26305b0f4c79721f6585afd62ba/jenkins/opensearch-dashboards/distribution-build.jenkinsfile#L191-L192
as two URL links for OS & OSD are using the same `BuildManifest` object. 

### To reproduce

Run the `distribution-build-opensearch-dashboards` and trigger integ tests from it.

**Comment by rishabh6788** [comment]
Will take a look at this.

**Comment by zelinh** [comment]
I think `getURL` from https://github.com/opensearch-project/opensearch-build-libraries/blob/c8033da031a598a6f807f5da14b5e0408713d418/src/jenkins/BuildManifest.groovy#L141 is using `getFileName` which uses the same name for OS & OSD.

**Comment by rishabh6788** [comment]
I don't think this is an issue because the passed parameter in the mentioned job is wrong. https://build.ci.opensearch.org/job/integ-test-opensearch-dashboards/3451/parameters/
BUILD_MANIFEST_URL_OPENSEARCH has the wrong url which caused the failure.   
@zelinh @peterzhuamazon

**Comment by zelinh** [comment]
Any objection that we close this issue? @peterzhuamazon

**Comment by rishabh6788** [comment]
Closing as this has been fixed.
