### ISSUE TITLE
Integrate Validation mechanism with OS and OSD builds

### ISSUE THREAD

**Issue by Divyaasm** [opensearch-project/opensearch-build#3441]
### Is your feature request related to a problem? Please describe

The idea is to integrate a Validation mechanism to each successful build in OS and OSD, and update the latest build only when the validation is successful. 

### Describe the solution you'd like

Utilize the [Validation](https://github.com/Divyaasm/opensearch-build/tree/main/src/validation_workflow) framework, the idea is to validate the artifacts by downloading them, start a cluster and run the api commands to test the cluster similar to https://opensearch.org/docs/latest/install-and-configure/install-opensearch/tar/

Sub issues under the meta issue:

- [x] [Update the current Validation mechanism to download OS and OSD artifacts from CI bucket](https://github.com/opensearch-project/opensearch-build/issues/3690)
- [x] [Update existing Validation Framework to run individually for OS and OSD](https://github.com/opensearch-project/opensearch-build/issues/3691)
- [ ] The approach to call the validation library will be done in integtest workflow.
       Related issue : #4424 

Acceptance Criteria:

1. Separate the Validation Framework using -- type OS or OSD currently it does for OS and OSD together.
2. Add a new functionality to fetch the artifacts from CI bucket
3. The idea is to start with Tar distribution seperately for OS and OSD
4. ~~Call the Validation Groovy library in the post method before the[ /latest](https://github.com/opensearch-project/opensearch-build/blob/68a2fe7a67f30171545ceff689a3493dcb6d7558/jenkins/opensearch/distribution-build.jenkinsfile#L844) is updated.~~

### Additional context

A possible solution to address https://github.com/opensearch-project/opensearch-build/issues/3390

**Comment by bbarani** [comment]
Tagging the [PR](https://github.com/opensearch-project/opensearch-build/pull/4377)

**Comment by Divyaasm** [comment]
Validation workflow is now integrated with Integ-test workflow for now instead of Build Workflow.
