### ISSUE TITLE
[Bug]: Promote artifacts description not clear enough

### ISSUE THREAD

**Issue by zelinh** [opensearch-project/opensearch-build#3456]
### Describe the bug

The description for the https://build.ci.opensearch.org/job/distribution-promote-artifacts/ jenkins jobs is a little confusing for tarball/rpm/deb cause it only says linux in the side bar description. It doesn't tell difference between distribution type for linux platform. 

<img width="344" alt="Screen Shot 2023-05-01 at 3 30 54 PM" src="https://user-images.githubusercontent.com/87548827/235542942-654e9c9a-426f-4ab8-8cf1-ada73ce30fca.png">

### To reproduce

Look at the left part in this https://build.ci.opensearch.org/job/distribution-promote-artifacts/

**Comment by Tokesh** [comment]
Hello! I can try to solve it.

**Comment by peterzhuamazon** [comment]
> Hello! I can try to solve it. I have studied enough materials on working with Jenkins. I'm currently looking for a file where I can add this setting. I roughly imagine how it should look like. As far as I understand it looks like this? opensearch-build/jenkins/promotion/promote-artifacts.jenkinsfile

Im following up on the PR, thanks.
