### ISSUE TITLE
[Bug]: Not correct path in Readme of building CI runner docker image

### ISSUE THREAD

**Issue by Tokesh** [opensearch-project/opensearch-build#3458]
### Describe the bug

Hello everyone! I noticed that in [Readme](https://github.com/opensearch-project/opensearch-build/tree/main/docker) there is not correct path for creating image in docker

### To reproduce

If you recheck, i can change the path in readme. But we are still trying to find where it was removed from directory with my college friend @aabeshov

### Screenshots

<img width="1065" alt="image" src="https://user-images.githubusercontent.com/78027392/235616549-6187ace9-3b5a-4f7a-98d2-25a0d6952720.png">

### Host / Environment

my: MacOS Intel i7
@aabeshov: MacOS M1 Pro

### Additional context

<img width="573" alt="image" src="https://user-images.githubusercontent.com/78027392/235617072-4bebd6a9-94a5-48ac-a378-78aab15faeb4.png">

**Comment by Tokesh** [comment]
Based on review of @peterzhuamazon on [forum](peterzhuamazon)
I can suggest to change readme which located : opensearch-build/docker/

### Build CI Runner Docker Image from Dockerfile

```bash
bash build-image-single-arch.sh -r <Repo name> -v <Tag name> -f <Dockerfile>
```
Did I get it right or should I read it back?

**Comment by jordarlu** [comment]
Hi, @Tokesh , it might be worth to also mention where the [build-image-single-arch.sh](https://github.com/opensearch-project/opensearch-build/blob/main/docker/ci/build-image-single-arch.sh) is located as it is not in the repo root folder.
Or, adding the path in the bash to build-image-single-arch.sh 

I am unable to see the comment in the [forum](https://forum.opensearch.org/t/opensearch-build-troubles/14218) you provided above, would you mind create a PR for team to review? 

thank you!

**Comment by aabeshov** [comment]
> Hi, @Tokesh , it might be worth to also mention where the [build-image-single-arch.sh](https://github.com/opensearch-project/opensearch-build/blob/main/docker/ci/build-image-single-arch.sh) is located as it is not in the repo root folder. Or, adding the path in the bash to build-image-single-arch.sh
> 
> I am unable to see the comment in the [forum](https://forum.opensearch.org/t/opensearch-build-troubles/14218) you provided above, would you mind create a PR for team to review?
> 
> thank you!

Hello @jordarlu , we wanted to ask, if we need to also change instructions of building multi-arch ?
Because in README file 
this steps
<img width="1049" alt="image" src="https://github.com/opensearch-project/opensearch-build/assets/78027095/f66291cf-9975-4e7c-bcc3-a4e3e4e409ea">
But we noticed that it's already in `build-image-multi-arch.sh`
<img width="1049" alt="image" src="https://github.com/opensearch-project/opensearch-build/assets/78027095/2e305544-81c3-4e07-b0a5-fc9956e96583">
Should we also replace instruction of building multi-arch by build-image-multi-arch.sh?
