### ISSUE TITLE
[Bug]: Add workflows to verify all expected maven artifacts are published for a release

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/opensearch-build#3463]
### Describe the bug

Coming from: https://github.com/opensearch-project/job-scheduler/issues/374
Few maven publish workflows within a component changed and published artifacts in a different location.
This caused problems. 

We identified the problem by manually looking at maven co-ordinates and these should be written as automated workflows and a pre-check for gating the release.

### Proposal

Lets add workflows to verify all expected maven co-ordinates have expected artifacts before we officially release OpenSearch distribution. 
This should help us automate and verify this doesn't happen for any component within the distribution.

**Comment by jordarlu** [comment]
Issue is vlaid, we will need brain stone session to finalize the design before moving forward.

**Comment by gaiksaya** [comment]
Related: https://github.com/opensearch-project/opensearch-build/issues/2928

**Comment by peterzhuamazon** [comment]
I think this is duplicated with https://github.com/opensearch-project/opensearch-build/issues/2928 @saratvemulapalli is it ok we close this issue and sync the comment to the old one?

Thanks.

**Comment by saratvemulapalli** [comment]
Thanks folks. Yup the issue #2928 captures it.

**Comment by saratvemulapalli** [comment]
Dup #2928
