### ISSUE TITLE
[Renew Key] Upcoming expiration of our current sub public key (expire on 20240512)

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#3468]
This is a reminder that the new sub public key that we extended in #2136 will expire on 20240512.

We need to take action to extend the key again before that.

Guide: https://github.com/opensearch-project/opensearch-build/issues/2040#issuecomment-1125449385

* Upload the key to the production S3 bucket while work with project-website on it.
* Upload to keyserver: https://github.com/opensearch-project/opensearch-build/issues/2040#issuecomment-1132261924.
* Build a release and sign and specifically test rpm on rockylinux9/almalinux9.
* Update on https://opensearch.org/verify-signatures.html.
* Make sure the key will expire in exactly one year on 20250512.
* Create a new issue for the next year.

Thanks.

**Comment by peterzhuamazon** [comment]
We need to update the cert for another year now.
Since 2.14.0 will release on 05/14, which is right after the expiration.

**Comment by peterzhuamazon** [comment]
Also update this:
https://opensearch.org/verify-signatures.html

**Comment by peterzhuamazon** [comment]
The renewed key has been created and uploaded to bucket, not yet switch.

* Next renew: https://github.com/opensearch-project/opensearch-build/issues/4669

**Comment by peterzhuamazon** [comment]
The key able to verify old artifacts:
```
% gpg --verify opensearch-2.0.0-rc1-linux-x64.tar.gz.sig
gpg: Signature made Tue 03 May 2022 05:30:55 PM UTC using RSA key ID 542C03B4
gpg: Good signature from "OpenSearch project <opensearch@amazon.com>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: C5B7 4989 65EF D1C2 924B  A9D5 39D3 1987 9310 D3FC
     Subkey fingerprint: 2187 3199 B103 0FCD 49DA  83F8 C2EE 2AF6 542C 03B4
(base)
```

**Comment by peterzhuamazon** [comment]
Yum can install on a rockylinux9:
```
113 MB/s | 799 MB     00:07
OpenSearch 2.x                                                                                                                                                                                                                                                                               77 kB/s | 4.2 kB     00:00
Importing GPG key 0x9310D3FC:
 Userid     : "OpenSearch project <opensearch@amazon.com>"
 Fingerprint: C5B7 4989 65EF D1C2 924B A9D5 39D3 1987 9310 D3FC
 From       : <>
Is this ok [y/N]: y
Key imported successfully
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
```

**Comment by peterzhuamazon** [comment]
Update changelog:
* https://github.com/opensearch-project/project-website/pull/2833

**Comment by peterzhuamazon** [comment]
Will upload keys to all the key servers once we live.

**Comment by nerijus** [comment]
Could you please extend the key to more years? Because now every year we have to do steps in https://github.com/opensearch-project/opensearch-build/issues/3124#issuecomment-1533756275

**Comment by flybyray** [comment]
> 542C03B4



> Yum can install on a rockylinux9:
> 
> ```
> 113 MB/s | 799 MB     00:07
> OpenSearch 2.x                                                                                                                                                                                                                                                                               77 kB/s | 4.2 kB     00:00
> Importing GPG key 0x9310D3FC:
>  Userid     : "OpenSearch project <opensearch@amazon.com>"
>  Fingerprint: C5B7 4989 65EF D1C2 924B A9D5 39D3 1987 9310 D3FC
>  From       : <>
> Is this ok [y/N]: y
> Key imported successfully
> Running transaction check
> Transaction check succeeded.
> Running transaction test
> Transaction test succeeded.
> Running transaction
> ```

Depends on how your repo file looks like. There are still signatures out there which are not updated.
```txt
[ TEST 2024-08-20 14:49 ]
root@db:~ # curl -fsSLO https://artifacts.opensearch.org/releases/bundle/opensearch/2.x/opensearch-2.x.repo.sig
[ TEST 2024-08-20 14:49 ]
root@db:~ # curl -fsSLO https://artifacts.opensearch.org/releases/bundle/opensearch/2.x/opensearch-2.x.repo
[ TEST 2024-08-20 14:49 ]
root@db:~ # gpg --verify opensearch-2.x.repo.sig opensearch-2.x.repo
gpg: Signature made Sat 07 May 2022 12:57:51 AM CEST
gpg:                using RSA key C2EE2AF6542C03B4
gpg: Good signature from "OpenSearch project <opensearch@amazon.com>" [unknown]
gpg: Note: This key has expired!
Primary key fingerprint: C5B7 4989 65EF D1C2 924B  A9D5 39D3 1987 9310 D3FC
     Subkey fingerprint: 2187 3199 B103 0FCD 49DA  83F8 C2EE 2AF6 542C 03B4
```

**Comment by flybyray** [comment]
way nicer 
https://github.com/opensearch-project/opensearch-build/issues/3527#issuecomment-1553341927
