### ISSUE TITLE
Enhancement on docker validation code structure 

### ISSUE THREAD

**Issue by jordarlu** [opensearch-project/opensearch-build#3475]
Coming from https://github.com/opensearch-project/opensearch-build/pull/3325, we want to continue improve on code quality of docker validation .. the following are from the comment of the above PR  : 

https://github.com/opensearch-project/opensearch-build/pull/3325#pullrequestreview-1409710534

**Comment by prudhvigodithi** [comment]
Hey @jordarlu I see the PR is merged, can we close this issue ?
@bbarani @peterzhuamazon

**Comment by jordarlu** [comment]
I am closing this issue for now, and we can create new one to track any further improvement. thanks
