### ISSUE TITLE
Problem with Building Image Path

### ISSUE THREAD

**Issue by aabeshov** [opensearch-project/opensearch-build#3478]
### Is your feature request related to a problem? Please describe

Today I wanted to build CI Runner Docker Image. Using this command
```bash
docker build -f ./docker/ci/dockerfiles/integtest-runner.al2.dockerfile . -t <Docker Hub RepoName>/<Docker Image Name>:<Tag Name>
```
And I faced that problem
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/78027095/236479200-b31ca7ba-7a03-4bbf-bdc7-50aa86134d9e.png">

### Describe the solution you'd like

I figured out that in Dockerfile it's written that it uses "config/yg-setup.sh" but we execute this command in the wrong directory.
So I guess we need to edit README file to change path by
executing this command
```bash
docker build -f ./docker/ci/dockerfiles/current/<<name_of_dockerfile>> . -t <Docker Hub RepoName>/<Docker Image Name>:<Tag Name>
```
in this directory
```bash
~/opensearch-build/docker/ci
```
And then using 
```bash
docker build -f ./dockerfiles/current/<<name_of_dockerfile>> . -t <Docker Hub RepoName>/<Docker Image Name>:<Tag Name>
```

### Describe alternatives you've considered

Or we can edit every Dockerfile and change every line where it uses "config/<<files_name>>"
So then we will be able to execute build command from root directory.

**Comment by gaiksaya** [comment]
Hi @aabeshov ,

Thanks for bringing this up. Documentation is an important step and we are constantly trying to keep it to up to date. We highly recommend users to contribute as well. Please feel free to create a pull request in the mean time.
Thanks again!

**Comment by aabeshov** [comment]
@aabeshov Yeap of course, Thanks for replying!
Could you also check this issue? #3458 
It has also similar problem.

**Comment by aabeshov** [comment]
@gaiksaya Yeap of course, Thanks for replying!
Could you also check this issue? #3458 
It has also similar problem.

**Comment by aabeshov** [comment]
> Hi @aabeshov ,
> 
> Thanks for bringing this up. Documentation is an important step and we are constantly trying to keep it to up to date. We highly recommend users to contribute as well. Please feel free to create a pull request in the mean time. Thanks again!

@g Yeap of course, Thanks for replying!
Could you also check this issue? #3458 
It has also similar problem.

**Comment by aabeshov** [comment]
> Hi @aabeshov ,
> 
> Thanks for bringing this up. Documentation is an important step and we are constantly trying to keep it to up to date. We highly recommend users to contribute as well. Please feel free to create a pull request in the mean time. Thanks again!

Yeap of course, Thanks for replying!
Could you also check this issue? #3458 
It has also similar problem.
