### ISSUE TITLE
[Meta] Move OpenSearch staging jobs into production for v1.1

### ISSUE THREAD

**Issue by mch2** [opensearch-project/opensearch-build#348]
Set up nightly jobs for 1.1 OpenSearch builds. Snapshot builds will be pushed to our snapshot maven repository - [here](https://aws.oss.sonatype.org/content/repositories/snapshots/).  Release builds (x64 and arm64) will be pushed to artifacts.opensearch.org/builds.  A release workflow will be set up to push to maven central.

### Build

- [x] #350
- [x] #210 
- [x] #20
- [x] #73

### Test

- [ ] #123 

### Release

- [x] #351 
- [x] #87

**Comment by gaiksaya** [comment]
[Triage] Closing this issue. Track https://github.com/opensearch-project/opensearch-ci/issues/59
