### ISSUE TITLE
[release]: SQL JDBC driver

### ISSUE THREAD

**Issue by Yury-Fridlyand** [opensearch-project/opensearch-build#3505]
### Did you read the on-boarding document

+

### What is the name of your component?

sqj-jdbc

### What is the link to your GitHub repo?

https://github.com/opensearch-project/sql-jdbc

### Targeted release date

11.05.2023

### Where should we publish this component?

Maven

### What type of artifact(s) will be generated for this component?

non-shadow jar

### Have you completed the required reviews including security reviews, UX reviews?

+

### Have you on-boarded automated security scanning for the GitHub repo associated with this component?

+

**Comment by gaiksaya** [comment]
Hi @Yury-Fridlyand , sql-jdbc is already on boarded to 1-click release process. See https://github.com/opensearch-project/opensearch-build/issues/2692#issuecomment-1372971262
Is there something more required?

**Comment by Yury-Fridlyand** [comment]
Hi
Yes, I'm aware of it. I created a tag, but [Jenkins CI](https://build.ci.opensearch.org/job/sql-jdbc-release/) wasn't triggered. Something is missing or misconfigured, but I don't know what.

**Comment by gaiksaya** [comment]
I see that the release was released on GitHub. From [releasing.md](https://github.com/opensearch-project/sql-jdbc/blob/main/RELEASING.md#releasing):
> Please note that the release workflow is triggered only if created release is in draft state.

The release will be automatically published once the artifacts are released on maven. Can you delete the release and then re-cut the tag and just leave at that. All other things should be taken care automatically.

Thanks!

**Comment by Yury-Fridlyand** [comment]
Ouch. Will try.

**Comment by Yury-Fridlyand** [comment]
That worked, but [CI failed](https://build.ci.opensearch.org/job/sql-jdbc-release/4/console) @gaiksaya.
What can we do?

**Comment by gaiksaya** [comment]
I just resend the webhook trigger. Looks like it went through! Not sure for what reason the asset_url was going null. 

https://github.com/opensearch-project/sql-jdbc/releases/tag/1.3.0.0
https://aws.oss.sonatype.org/content/repositories/releases/org/opensearch/driver/opensearch-sql-jdbc/1.3.0.0/

**Comment by gaiksaya** [comment]
Closing this issue as release was successful. Also created an issue to on-board sql-jdbc to 2PR approval process: https://github.com/opensearch-project/sql-jdbc/issues/77

**Comment by Yury-Fridlyand** [comment]
Woohoo! Thanks!
