### ISSUE TITLE
[release]: Data Prepper 2.3.0

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/opensearch-build#3518]
### Did you read the on-boarding document

Yes.

### What is the name of your component?

Data Prepper

### What is the link to your GitHub repo?

https://github.com/opensearch-project/data-prepper

### Targeted release date

Jun 06, 2023

### Where should we publish this component?

This is already scripted

### What type of artifact(s) will be generated for this component?

* Docker/ECR image
* tar.gz archive
* Maven artifacts

### Have you completed the required reviews including security reviews, UX reviews?

Some are still in progress.

### Have you on-boarded automated security scanning for the GitHub repo associated with this component?

Yes.

### Additional context

Data Prepper builds artifacts using GitHub Actions. This will publish to staging repositories. Our team is responsible for this portion. We will need the opensearch-build team to run the Jenkins job which promotes these to production.

A Data Prepper maintainer will supply the `DATA_PREPPER_BUILD_NUMBER` parameter when it is time to release.

Parameters:

`VERSION`: 2.3.0
`RELEASE_MAJOR_TAG`: true
`RELEASE_LATEST_TAG`: true
`DATA_PREPPER_BUILD_NUMBER` - To be supplied later

**Comment by bbarani** [comment]
@dlvenable Its high time we automate the release process for Data prepper to avoid any delay in releasing the artifacts due to resourcing bottlenecks. Can we work together and see if we can automate it for this release?

**Comment by zelinh** [comment]
[Triage] @dlvenable @bbarani Can you update the current status for this?

**Comment by dlvenable** [comment]
@zelinh , We are planning to release this on Jun 06, 2023. We will still need support from the this project to manually kick off the Jenkins job.

**Comment by asifsmohammed** [comment]
VERSION: 2.3.0
RELEASE_MAJOR_TAG: true
RELEASE_LATEST_TAG: true
DATA_PREPPER_BUILD_NUMBER - 57

**Comment by prudhvigodithi** [comment]
### Jenkins build to trigger the release: 
https://build.ci.opensearch.org/job/release-data-prepper-all-artifacts/

### Docker: 
[2.3.0](https://hub.docker.com/layers/opensearchproject/data-prepper/2.3.0/images/sha256-e67471ad0231fdb8de4c581c483391a9ff89d7320191c2a4c0151f7c142efa54?context=explore), [2](https://hub.docker.com/layers/opensearchproject/data-prepper/2/images/sha256-e67471ad0231fdb8de4c581c483391a9ff89d7320191c2a4c0151f7c142efa54?context=explore)

### ECR: 
[2.3.0](https://gallery.ecr.aws/opensearchproject/data-prepper), [2](https://gallery.ecr.aws/opensearchproject/data-prepper)

### Sonatype Release Repo
[2.3.0](https://aws.oss.sonatype.org/content/repositories/releases/org/opensearch/dataprepper/data-prepper-api/2.3.0/
)

**Comment by gaiksaya** [comment]
Closing this issue as 2.3.0 is out.
