### ISSUE TITLE
[Bug]: Final link failed: bad value during build process

### ISSUE THREAD

**Issue by aoterolorenzo** [opensearch-project/opensearch-build#3520]
### Describe the bug

Build process failed. During k-NN build:

Trace command: 'bash /tmp/tmp2yxwcklx/k-NN/scripts/build.sh -v 2.6.0 -p linux -a x64 -s false -o builds' returned non-zero exit status 1.

### To reproduce

`./build.sh manifests/2.6.0/opensearch-2.6.0.yml`

### Expected behavior

Build success

### Host / Environment

AMD64, Debian 11. Minimal base image.

### Relevant log output

```shell
19:18:58  /tmp/tmp2yxwcklx/k-NN/jni/src/org_opensearch_knn_jni_FaissService.cpp: In function ???jlong Java_org_opensearch_knn_jni_FaissService_loadIndex(JNIEnv*, jclass, jstring)???:
19:18:58  /tmp/tmp2yxwcklx/k-NN/jni/src/org_opensearch_knn_jni_FaissService.cpp:75:12: warning: converting to non-pointer type ???long int??? from NULL [-Wconversion-null]
19:18:58     75 |     return NULL;
19:18:58        |            ^~~~
19:18:58  /usr/bin/ld: /usr/lib/x86_64-linux-gnu/libblas.a(cblas_xerbla.o): warning: relocation against `RowMajorStrg' in read-only section `.text'
19:18:58  /usr/bin/ld: /usr/lib/x86_64-linux-gnu/libblas.a(xerbla.o): relocation R_X86_64_PC32 against symbol `CBLAS_CallFromC' can not be used when making a shared object; recompile with -fPIC
19:18:58  /usr/bin/ld: final link failed: bad value
19:18:58  collect2: error: ld returned 1 exit status
19:18:58  make[3]: *** [CMakeFiles/opensearchknn_faiss.dir/build.make:126: release/libopensearchknn_faiss.so] Error 1
19:18:58  make[2]: *** [CMakeFiles/Makefile2:275: CMakeFiles/opensearchknn_faiss.dir/all] Error 2
19:18:58  make[1]: *** [CMakeFiles/Makefile2:282: CMakeFiles/opensearchknn_faiss.dir/rule] Error 2
19:18:58  make: *** [Makefile:205: opensearchknn_faiss] Error 2
19:18:58  
19:18:58  FAILURE: Build failed with an exception.
19:18:58  
19:18:58  * What went wrong:
19:18:58  Execution failed for task ':buildJniLib'.
19:18:58  > Process 'command 'make'' finished with non-zero exit value 2
19:18:58  
19:18:58  * Try:
19:18:58  > Run with --stacktrace option to get the stack trace.
19:18:58  > Run with --info or --debug option to get more log output.
19:18:58  > Run with --scan to get full insights.
19:18:58  
19:18:58  * Get more help at https://help.gradle.org/
19:18:58
```

**Comment by gaiksaya** [comment]
Hi @aoterolorenzo ,

Each manifest also as a docker image associated with it that can be used to build artifacts. See https://github.com/opensearch-project/opensearch-build/blob/main/manifests/2.6.0/opensearch-2.6.0.yml#L7-L9
The same docker image has been used to create 2.6.0 too in our CI system and has all required packages with right versions. @peterzhuamazon can add more about k-NN lib issues.
Can you try using the same image for building?
Thanks!

**Comment by aoterolorenzo** [comment]
Hi @gaiksaya

Thanks for your response.

As Bitnami, we are trying to add OpenSearch to our catalog, and unfortunately, our pipelines are using minimal base images. The compilation on our side works perfectly executed on a common `debian-11` or `ubuntu-20` image, but impossible to achieve under a minimal environment.

Is the `ci-runner` Dockerfile public? Having a list of necessary dependencies would be nice to have, since I think our problem relies in missing dependencies that are probably native in most of SO common images. Some of them have been already added to our scenario, like `libblas-dev` and `gfortran`, but due to the build logic complexity is difficult to obtain a proper output to debug what is missing. 

Also in this case I think that it is more than just a dependency, and I suspect that the debian repositories are pointing to a BLAS library that has not been compiled with `-fPIC`... And this is breaking the `k-NN` lib compilation in some way.
@peterzhuamazon could you help with this specific issue?

**Comment by gaiksaya** [comment]
Yes! All images are public on [docker hub](https://hub.docker.com/r/opensearchstaging/ci-runner) as well as [ECR](https://gallery.ecr.aws/opensearchstaging/ci-runner) and can build the components as they right dependencies involved.

**Comment by aoterolorenzo** [comment]
Thank you! I'll check for missing dependencies against the docker manifests!

However, I could encounter still missing dependencies that probably are natively in the base images (hope not), in this case still would be great to have a complete dependency graph/list.

Apart from that, I sill think that my error is related to a repository dependency (maybe `libblas-dev`) without the `-fPIC` flag, so any further help here is more than welcome. I will try to compile ourself that library before the Opensearch build process.

Again, thank you for your help!

**Comment by bbarani** [comment]
@aoterolorenzo  do you have any updates?

**Comment by jordarlu** [comment]
Greetings again, @aoterolorenzo .. I hope the build went well on your end by taking the images from either docker Hub or ECR ? I am closing this issue by assuming it is good on your end now ... but pls feel free to re-open it if you are still seeing any concern ,, thanks!!
