### ISSUE TITLE
[BUG] OpenSearch-Dashboards integTest does not uninstall OpenSearch after completion

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#3524]
Hi,

When running the OSD integTest through Python, both OS and OSD will be installed.
But when completing the test or failed the test, only OSD will be uninstalled.

The logic here should be finetuned, this is only for DEB/RPM, not for TAR due to how `uninstall` function is being written:
https://github.com/opensearch-project/opensearch-build/blob/main/src/test_workflow/integ_test/distribution_rpm.py#L56
https://github.com/opensearch-project/opensearch-build/blob/main/src/test_workflow/integ_test/distribution_deb.py#L54

Thanks.

**Comment by peterzhuamazon** [comment]
We might able to retrieve the above service list and run the uninstall based on that.
In src/test_workflow/test_cluster.py

**Comment by zelinh** [comment]
[Triage] We have enough information here. @Divyaasm Please help take a look here. Thanks.
