### ISSUE TITLE
[Notification] OpenSearch Dashboards will bump to Node.js 18

### ISSUE THREAD

**Issue by ananzh** [opensearch-project/opensearch-build#3526]
As part of our continued efforts to improve OpenSearch Dashboards, we are planning to upgrade the underlying Node.js version from v14 to v18. This change will enhance performance, add new features, and bolster security. However, such major version changes might also affect the compatibility of existing plugins. Here is more introduction: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3601.

We will merge the change into main and backport to 2.x. Target release is 2.8.

Therefore, we want to notify the build team asap since Centos 7 doesn't support Node.js 18 and we might need extra research and effort working on it. Here is a testing branch that could be used to build new image:
https://github.com/AMoo-Miki/OpenSearch-Dashboards/tree/node-18-webpack-4

**Comment by ananzh** [comment]
This is also related to issue https://github.com/opensearch-project/opensearch-build/issues/1563

**Comment by ananzh** [comment]
We will bump to the latest LTS version `18.16.0`.

**Comment by peterzhuamazon** [comment]
Close this as the main issue will be synced to:
* #1563
