### ISSUE TITLE
Rename "bundle" to "distribution"?

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#353]
**Is your feature request related to a problem? Please describe.**
We've been calling our output a bundle, but it's really a distribution.

**Describe the solution you'd like**
Rename bundle to distribution everywhere.

**Comment by dblock** [comment]
@julesg WDYT?

**Comment by jcgraybill** [comment]
Yes, let's do this in as many places as possible. "Distribution" is the way the project describes collections of components that are built, tested, and downloaded together (see https://opensearch.org/downloads.html).

Using a different term ("bundle") for the distributions while they're being built and tested can be confusing ("At X stage in the process, is it called a bundle or a distribution? What are the rules that describe when to use each word?"), and creates different language used by 'insiders' and 'outsiders' to describe the same thing. We should always be moving in the direction of eliminating distinctions between 'insiders' and 'outsiders'. It should be simple for anybody who uses an OpenSearch distribution to find the code used to build that distribution and weigh in on it or contribute to it, so I think consistent language matters here. It's a small thing, but being welcoming requires removing both large and small barriers.

It looks like both terms evolved independently. Now that it's becoming clearer they have the same referent, I think it's worth doing some work to standardize.

**Comment by peterzhuamazon** [comment]
Seems like @zelinh already applied some renaming, need him to check through-fully how many more renames are needed.

**Comment by zelinh** [comment]
After checking comprehensively, this renaming from `bundle` to `dist` has been completed everywhere in bundle build file path.
