### ISSUE TITLE
[Retrospective] Release version 1.3.10 

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/opensearch-build#3535]
### Release issue:
https://github.com/opensearch-project/opensearch-build/issues/3331

###  How to use this issue?
Please add comments to this issue, they can be small or large in scope. Honest feedback is important to improve our processes, suggestions are also welcomed but not required.

### What will happen to this issue post release?
There will be a discussion(s) about how the release went and how the next release can be improved. Then this ticket will be updated with the notes of that discussion along side action items.

**Comment by prudhvigodithi** [comment]
One action item from this release is the plugins snapshots maven publish (1.3.x). With this resolved [META issue](https://github.com/opensearch-project/opensearch-build/issues/3185) the maven publish workflow is now moved to each individual repos that can publish the plugin snapshots through the GitHub CI runners and not part of distribution-build Jenkins job, however for multiple repos this workflow is not back ported to 1.3 branch resulting in missing snapshots of plugins for 1.3 version. 
[HotFix added ](https://github.com/opensearch-project/opensearch-build/pull/3523), but for long term the maven publish workflow should be back ported to 1.3 branches.
@bbarani @gaiksaya @peterzhuamazon

**Comment by bbarani** [comment]
Closing this issue as we have released 1.3.10 version.
