### ISSUE TITLE
Use appropriate Jenkins agent label for benchmark test

### ISSUE THREAD

**Issue by rishabh6788** [opensearch-project/opensearch-build#3537]
Currently the benchmark job runs on Jenkins agent label `Jenkins-Agent-AL2-X64-M52xlarge-Docker-Host-Benchmark-Test`. The naming convention suggests that the process runs inside a docker container on the AL2 host when actually the job runs on the  host directly. 
Create new jenkins agent with label `Jenkins-Agent-AL2-X64-M52xlarge-Host-Benchmark-Test` and use that for benchmarking job in future.

**Comment by peterzhuamazon** [comment]
Note sure if we need a new agent, but rename would help a lot.

**Comment by peterzhuamazon** [comment]
Handled by this:
* https://github.com/opensearch-project/opensearch-ci/pull/339
