### ISSUE TITLE
[release]: performance-analyzer-commons

### ISSUE THREAD

**Issue by khushbr** [opensearch-project/opensearch-build#3547]
### Did you read the on-boarding document

Yes

### What is the name of your component?

performance-analyzer-commons

### What is the link to your GitHub repo?

https://github.com/opensearch-project/performance-analyzer-commons

### Targeted release date

05/30/2023

### Where should we publish this component?

https://aws.oss.sonatype.org/content/repositories/snapshots/ 

### What type of artifact(s) will be generated for this component?

Java JAR file

### Have you completed the required reviews including security reviews, UX reviews?

Yes

### Have you on-boarded automated security scanning for the GitHub repo associated with this component?

Yes

### Additional context

https://github.com/opensearch-project/performance-analyzer-commons/issues/2

**Comment by khushbr** [comment]
The Library [performance-analyzer-commons](https://github.com/opensearch-project/performance-analyzer-commons) doesn't need public release but meant for internal consumption by the Plugin and the agent. The library will be packaged, tested and released with the [performance-analyzer](https://github.com/opensearch-project/performance-analyzer) plugin.

Current ask is to Publish the repo source Java JAR to Maven Snapshot repo.

**Comment by khushbr** [comment]
@gaiksaya @prudhvigodithi Adding you for comment, this library will closely follow the Data Prepper component.

**Comment by gaiksaya** [comment]
I believe we just need to add the mentioned repo to our maven credentials access, generate and IAM role that will be used to publish to snapshots repository. Waiting for approval of this PR: https://github.com/opensearch-project/performance-analyzer-commons/pull/11

**Comment by khushbr** [comment]
@gaiksaya The PR has been merged, can you please add the repo for maven creds. Thank You!

**Comment by gaiksaya** [comment]
This is an independent component which is follow it's only release cadence similar to other components like spring-data-opensearch, opensearch-java.
See the on-boarding documentation: https://github.com/opensearch-project/opensearch-build/blob/main/ONBOARDING.md#onboarding-to-universal--1-click-release-process

Sample PR: https://github.com/opensearch-project/spring-data-opensearch/pull/74

Thanks!

**Comment by gaiksaya** [comment]
> @gaiksaya The PR has been merged, can you please add the repo for maven creds. Thank You!

Thanks! @zelinh Will be taking care of it.

**Comment by peterzhuamazon** [comment]
Hi, 
Some steps out of the offline meeting:
* PA Commons Libs needs to be onboard to 1click process, and needs to be released before any build on Jenkins for PA.
* PA Commons Libs has its own version scheme and PA team is responsible for the releases.
* PA gradle task will take care of getting the jars that published above during build time and bundled into zip
* Confirm PA RCA is now replaced fully by PA Commons Libs or not, which include following changes not limited to:
  * Config location, name
  * Folder location
  * Removal of original rca folder from root of artifacts
  * Impact on PA cli script that used to start the agent
  * All of the distributions except Windows will be impacted as their build/assemble/startup script is heavily coded according to the previous setups of RCA
  * Whether the plugin can handle the lib jar loading during runtime.

cc: @khushbr @gaiksaya 

Thanks

**Comment by khushbr** [comment]
https://github.com/opensearch-project/opensearch-build/issues/3548

**Comment by peterzhuamazon** [comment]
> #3548

Completed.

**Comment by zelinh** [comment]
We have completed onboarding 1-click release process from our side. Jenkins job is created. https://build.ci.opensearch.org/job/performance-analyzer-commons-release/

**Comment by gaiksaya** [comment]
The validation checks failed:
<img width="1152" alt="image" src="https://github.com/opensearch-project/opensearch-build/assets/61760125/9f3018e4-439f-479c-8ffc-34d843615b83">

@khushbr is looking into it

**Comment by gaiksaya** [comment]
PA commons released now: https://aws.oss.sonatype.org/content/repositories/releases/org/opensearch/performance-analyzer-commons/

Thanks!

**Comment by khushbr** [comment]
Release done for PA-Commons `1.0.0` -  https://github.com/opensearch-project/performance-analyzer-commons/releases/tag/1.0.0

Thank you @gaiksaya , much appreciate all the prompt help for getting this out.
