### ISSUE TITLE
Add Opensearch-ci-bot for write access to 'performance-analyzer-commons' repo

### ISSUE THREAD

**Issue by khushbr** [opensearch-project/opensearch-build#3548]
### Is your feature request related to a problem? Please describe

Based on step 1 of this section, opensearch-ci-bot needs write access.

https://github.com/opensearch-project/opensearch-build/blob/main/ONBOARDING.md#onboarding-to-universal--1-click-release-process

### Describe the solution you'd like

Enable opensearch-ci-bot to have write access.

**Comment by khushbr** [comment]
Repo Link: https://github.com/opensearch-project/performance-analyzer-commons

**Comment by peterzhuamazon** [comment]
I will take care of this seems like the previous invite expired.

**Comment by peterzhuamazon** [comment]
The bot has write access now:
![image](https://github.com/opensearch-project/opensearch-build/assets/65193828/8f2f9171-8c6c-4890-87c2-2c33cbc73e2b)
