### ISSUE TITLE
[BUG] Unit Test TestBuilder.test_export_artifacts fails on desktop

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/opensearch-build#355]
**Describe the bug**
Unit Test TestBuilder.test_export_artifacts fails on desktop, some how this test works on the CI workflow.

```
~> bundle-workflow % pipenv run pytest
..........................F..................................                                                                                                                                  [100%]
============================================================================================== FAILURES ==============================================================================================
_________________________________________________________________________________ TestBuilder.test_export_artifacts __________________________________________________________________________________

self = <tests_build_workflow.test_builder.TestBuilder testMethod=test_export_artifacts>, mock_walk = <MagicMock name='walk' id='4516530320'>

    @patch("os.walk")
    def test_export_artifacts(self, mock_walk):
        mock_walk.side_effect = self.mock_os_walk
        self.builder.export_artifacts()
>       self.assertEqual(self.builder.build_recorder.record_artifact.call_count, 2)
E       AssertionError: 0 != 2

tests/tests_build_workflow/test_builder.py:81: AssertionError
====================================================================================== short test summary info =======================================================================================
FAILED tests/tests_build_workflow/test_builder.py::TestBuilder::test_export_artifacts - AssertionError: 0 != 2
1 failed, 60 passed in 8.49s

```

**To Reproduce**
1. Clone the code
2. cd bundle-workflow
3. `pipenv install`
4. `pipenv run pytest`

**Expected behavior**
Test passes.

 - OS: Mac OS X Big Sur

**Additional context**

**Comment by abhinavGupta16** [comment]
@bbarani - I can replicate the issue on MacOS BigSur
_____________________________________________________________________________________________________________ TestBuilder.test_export_artifacts ______________________________________________________________________________________________________________

self = <tests_build_workflow.test_builder.TestBuilder testMethod=test_export_artifacts>, mock_walk = <MagicMock name='walk' id='4401875120'>

    @patch("os.walk")
    def test_export_artifacts(self, mock_walk):
        mock_walk.side_effect = self.mock_os_walk
        self.builder.export_artifacts()
        self.assertEqual(self.builder.build_recorder.record_artifact.call_count, 2)
>       AssertionError: 0 != 2

AssertionError
===================== short test summary info ======================
FAILED tests/tests_build_workflow/test_builder.py::TestBuilder::test_export_artifacts - AssertionError: 0 != 2`

**Comment by dblock** [comment]
Fixed in https://github.com/opensearch-project/opensearch-build/pull/409.
