### ISSUE TITLE
Run nightly performance test for specific featuers consistently on unreleased versions 

### ISSUE THREAD

**Issue by tlfeng** [opensearch-project/opensearch-build#3581]
### Is your feature request related to a problem? Please describe

For example, run nightly performance test for Segment Replication feature only on the next OpenSearch version, such as on OpenSearch built from `2.x` branch.
In the commit https://github.com/opensearch-project/opensearch-build/commit/ffdba8c93f149c20660801f424e3806d0e32dd75, new triggers of the perf test are added. The test will be ran on both version 2.7.0 and 2.8.0.
There are 2 problem:
1. It's not necessary to run performance test on the already released version, such as 2.7.0, because there will be no new enhancement added to the released version, no need to monitor the performance every day.
2. There is no automatic mechanism to consistently run perf test in the OpenSearch built from `2.x` branch. Version 2.8.0 will be code freeze on May.30th, and I hope to run perf test on version 2.9.0 after the code freeze, because new enhancements will get to 2.9.0 and the benchmark result is necessary to ensure no regression issue occurs.

https://github.com/opensearch-project/opensearch-build/blob/ffdba8c93f149c20660801f424e3806d0e32dd75/jenkins/opensearch/benchmark-test.jenkinsfile#L25-L27

### Describe the solution you'd like

1. Remove the configurations of running perf test on version 2.7.0
2. Have a script to fetch OpenSearch build artifacts comes from 2.x branch consistently. Bumping version manually in the above lines of code is acceptable, but not the best option.

**Comment by prudhvigodithi** [comment]
[Untriage]
@tianleh thanks, we will get back on this issue after discussing few points.
Thank you

**Comment by tlfeng** [comment]
@prudhvigodithi Thanks for your reply. I noticed there is a new commit https://github.com/opensearch-project/opensearch-build/commit/037c3bf9abd9a8e30c6874cee3fe75e85448e7b9 that removes running benchmark test on version 2.7 and added 3.0.
Glad to see unreleased version 3.0 that fetched from latest build is added to the nightly benchmark test, that will help testing the newly added feature.
Hope to see benchmark tests always run against unreleased version, which is built from `2.x` and `main` branch nightly.

**Comment by rishabh6788** [comment]
Having an automation to add nightly benchmarks for newer versions is desirable but it has a lot of dependency on when the newer version distribution is available and how stable it is. 
Also, there may be requirements to add new feature flags or metadata tags which will only complicate the whole setup. 
For now the plan is to have nightly runs for last released 2.x version, upcoming 2.x version and 3.0 and we will be updating the benchmark job accordingly.
