### ISSUE TITLE
[release]: performance-analyzer-rca

### ISSUE THREAD

**Issue by khushbr** [opensearch-project/opensearch-build#3583]
### What is the name of your plugin?

performance-analyzer-rca

### What is the link to your GitHub repo?

https://github.com/opensearch-project/performance-analyzer-rca

### Targeted release version

2.9.0

### What type of the plugin are we on-boarding?

Observability

### Did you read the on-boarding document

Yes

### Does this plugin has all the necessary automated tests?

Yes

### Have you completed the required reviews including Security reviews, UX reviews?

Yes

### Have you on-boarded automated security scanning for the GitHub repo associated with this plugin?

Yes

### Additional context

* performance-analyzer-rca[RCA] is not a plugin but follows the same versioning as OpenSearch
* RCA is an independent agent, running in a side-car JVM and doesn't interact directly with OpenSearch.

Currently, the plugin is packages with PA in the distribution build will continue to do so. We need assistance for publishing the RCA JARs to Maven Central and Snapshot repo, refer: https://github.com/opensearch-project/performance-analyzer-rca/issues/312

**Comment by prudhvigodithi** [comment]
[Untriage]
@khushbr moving forward the performance-analyzer-rca[RCA] will be released as an isolated component?
or with [PA](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/2.8.0/opensearch-2.8.0.yml#L176-L183) part of the build manifest?
@gaiksaya @zelinh

**Comment by khushbr** [comment]
Hey @prudhvigodithi , RCA will continue to be built with PA as part of the build manifest.

**Comment by gaiksaya** [comment]
> RCA is an independent agent, running in a side-car JVM and doesn't interact directly with OpenSearch.
In that case should RCA follow its own versioning?

**Comment by khushbr** [comment]
I am going to close this issue for now. 

Going forward, we want to converge the common functionality of RCA and [Telemetry Collector ](https://github.com/opensearch-project/telemetry-collector) into a single Agent.  Ideally, this Agent should be version agnostic but given the history of RCA evolution with OpenSearch version and releases, it would be better to rehome the common components into Collector and not RCA.
