### ISSUE TITLE
OpenSearch / OpenSearch Dashboards - RPM distribution (ARM64) 

### ISSUE THREAD

**Issue by bbarani** [opensearch-project/opensearch-build#36]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Provide signed (ARM64)RPM artifact for OpenSearch / OpenSearch Dashboards
- [ ] discuss approach to release RPM distribution (ARM64)
- [ ] document the approach in a github issue
- [ ] automate the RPM distribution builds

**Describe alternatives you've considered**
Generating the artifact using the source code

**Additional context**
Currently there are no (ARM) RPM artifacts for OpenSearch / OpenSearch Dashboards

**Comment by peterzhuamazon** [comment]
Fast forward work after this one complete is #27 #849.

**Comment by bbarani** [comment]
Closing this issue as we have shipped RPM artifacts with 2.0 RC1 release.
