### ISSUE TITLE
[BUG] Fix flake8 to ignore W503

### ISSUE THREAD

**Issue by setiah** [opensearch-project/opensearch-build#363]
Flake8 config flags both W503 and W504 as noncompliant. W503 has been replaced with W504. Need to fix the config to ignore W503. It probably happens due to older pipenv version?

**Comment by dblock** [comment]
Everything is locked via pipenv, this should be reproducible everywhere.

**Comment by dblock** [comment]
I found https://github.com/mila-iqia/cookiecutter-pyml/issues/10 and https://github.com/pypa/packaging/pull/145, so sounds like we should ignore one of them (W503).

**Comment by setiah** [comment]
As per pep style guide, either W503 or W504 styling works as long as it is consistent locally. We may or may not do string concats this way, but it applies for other concats and needs fixing.

We could follow W504 and ignore W503 in flake config, as that seems to be the latest pep approved styling
 as described here https://www.python.org/dev/peps/pep-0008/#should-a-line-break-before-or-after-a-binary-operator
```
# Correct:
# easy to match operators with operands
income = (gross_wages
          + taxable_interest
          + (dividends - qualified_dividends)
          - ira_deduction
          - student_loan_interest)
```

**Comment by peternied** [comment]
[Triage] Lets leave the existing configuration for now.
