### ISSUE TITLE
[release]: opensearch-sdk-java

### ISSUE THREAD

**Issue by owaiskazi19** [opensearch-project/opensearch-build#3638]
### Did you read the on-boarding document

Yes

### What is the name of your component?

opensearch-sdk-java

### What is the link to your GitHub repo?

https://github.com/opensearch-project/opensearch-sdk-java

### Targeted release date

07/18/2023 (2.9.0)

### Where should we publish this component?

maven central

### What type of artifact(s) will be generated for this component?

Jars

### Have you completed the required reviews including security reviews, UX reviews?

Yes

### Have you on-boarded automated security scanning for the GitHub repo associated with this component?

Yes

### Additional context

This will be an experimental release for extensibility.

**Comment by gaiksaya** [comment]
opensearch-sdk-java needs to be on-boarded to 1-click release process. Please go through the on-boarding documentation here: https://github.com/opensearch-project/opensearch-build/blob/main/ONBOARDING.md#onboarding-to-universal--1-click-release-process and let us know if you have any questions.

Thanks!

**Comment by gaiksaya** [comment]
opensearch-sdk-java has been on-boarded to 1-click release process. Next steps:
 1. Push a tag using the right commit and branch to opensearch-sdk-java
 2. Reach out this repo once the workflow succeeds https://build.ci.opensearch.org/view/Release/job/opensearch-sdk-java-release/
 3. After a successful release please publish the drafted release on GitHub and change 
 ```
publishRelease: true
autoPublish: true
```

Since this is the first release the above parameters are set to false to verify the artifacts.

**Comment by gaiksaya** [comment]
![image](https://github.com/opensearch-project/opensearch-build/assets/61760125/8a5ec12c-6b5e-4722-8426-2db3bda556b2)

**Comment by gaiksaya** [comment]
Validation is missing: 
```
failureMessage | Invalid  POM:  /org/opensearch/sdk/opensearch-sdk-java/0.1.0/opensearch-sdk-java-0.1.0.pom:  Project description missing, License information missing, Developer  information missing
-- | --

**Comment by prudhvigodithi** [comment]
(Related Topic https://github.com/opensearch-project/opensearch-build/issues/2928#issuecomment-1646647258) 
From the error looks the POM file generated is not in right format for publishing to maven 
https://central.sonatype.org/publish/requirements/

**Comment by prudhvigodithi** [comment]
Here is an example https://github.com/opensearch-project/job-scheduler/blob/main/build.gradle#L100-L118

**Comment by prudhvigodithi** [comment]
> Validation is missing:
> 
> ```
> failureMessage | Invalid  POM:  /org/opensearch/sdk/opensearch-sdk-java/0.1.0/opensearch-sdk-java-0.1.0.pom:  Project description missing, License information missing, Developer  information missing
> -- | --
> ```

The suggested approach should work https://github.com/opensearch-project/opensearch-sdk-java/pull/903#issuecomment-1650555977.

**Comment by gaiksaya** [comment]
OpenSearch sdk java is now released: https://aws.oss.sonatype.org/content/repositories/releases/org/opensearch/sdk/opensearch-sdk-java/0.1.0/
