### ISSUE TITLE
Add support to choose ec2 instance type for data nodes and ml-nodes.

### ISSUE THREAD

**Issue by rishabh6788** [opensearch-project/opensearch-build#3649]
### Is your feature request related to a problem? Please describe

The nightly benchmark runs are happening only against the default instance type `r5.xlarge` and r6g.xlarge`. 

### Describe the solution you'd like

Since https://github.com/opensearch-project/opensearch-cluster-cdk supports choosing ec2 instance types, the nightly benchmark should also be able to add that support to choose desired ec2 instance type.

**Comment by gaiksaya** [comment]
Closing via https://github.com/opensearch-project/opensearch-cluster-cdk/pull/30
