### ISSUE TITLE
[release]: Resign the JDBC driver and the TACO (expires on 2024-04-16)

### ISSUE THREAD

**Issue by GumpacG** [opensearch-project/opensearch-build#3652]
### Did you read the on-boarding document

Yes

### What is the name of your component?

- OpenSearch JDBC driver
- OpenSearch Tableau Connector

### What is the link to your GitHub repo?

https://github.com/opensearch-project/sql-jdbc

### Targeted release date

The signer certificate expires on 2024-04-16. Resigning should be before that.

### Where should we publish this component?

artifacts: https://artifacts.opensearch.org/
download page: https://opensearch.org/downloads.html#drivers

### What type of artifact(s) will be generated for this component?

Signed shadow jar and signed taco file.

### Have you completed the required reviews including security reviews, UX reviews?

N/A

### Have you on-boarded automated security scanning for the GitHub repo associated with this component?

Yes

### Additional context

This is just a reminder to renew signer certificate before 2024-04-16 and publish resigned artifacts.

**Comment by gaiksaya** [comment]
@GumpacG I believe this issue covers it? https://github.com/opensearch-project/opensearch-build/issues/3468

**Comment by GumpacG** [comment]
@gaiksaya https://github.com/opensearch-project/opensearch-build/issues/3468 is for renewing the OpenSearch PGP key while this issue is for the jarsigner specifically.

**Comment by rishabh6788** [comment]
@GumpacG If I understand correctly the sign is valid till `2024-04-16` and since `JarSigner` team owns the signing infra, they will have to update the signer dates on their side. 
Is the signed artifact not acceptable?

**Comment by GumpacG** [comment]
The artifacts are valid. I created this issue here as a reminder to get it resigned before expiration as this is where we got the driver and taco signed (https://github.com/opensearch-project/opensearch-build/issues/3614 & https://github.com/opensearch-project/opensearch-build/issues/3631). This issue is also going to be on the website for [signature changelog similar to the PGP keys](https://opensearch.org/verify-signatures.html#:~:text=log%20for%20dates.-,Change%20Log,-Date). Sorry, I'm not too sure what the protocol is for updating the website. Please let me know if this should be done a different way.

**Comment by GumpacG** [comment]
Based on [Tableau's documentation](https://help.tableau.com/current/api/webdataconnector/en-us/docs/wdc_packaging.html#:~:text=Take%20note%20of%20when%20the%20TACO%20file%20expires.%20After%20it%20does%2C%20users%20will%20no%20longer%20be%20able%20use%20the%20connector%20in%20Tableau%20without%20disabling%20verification%20and%20you%20must%20provide%20a%20new%20signed%20TACO%20file.), I don't think that they do. With that being said, I actually got the dates wrong. The signer certificate expires on 2024-04-16, however the artifacts have timestamps valid until 2031-11-09. 
To get this off opensearch-build's plate, what I can do is close this issue and create a tracking issue in https://github.com/opensearch-project/sql-jdbc/ in case we don't release new artifacts before 2031 to get artifacts resigned. 
Does that sound alright?

**Comment by GumpacG** [comment]
Closing this issue to move to sql-jdbc repo. https://github.com/opensearch-project/sql-jdbc/issues/97
