### ISSUE TITLE
Add support to sign mac artifacts

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/opensearch-build#3669]
### Is your feature request related to a problem? Please describe

The current signing system https://github.com/opensearch-project/opensearch-build/tree/main/src/sign_workflow does not support signing mac artifacts.

One of the requirement is #3633 

### Describe the solution you'd like

Add signing support from infrastructure side to sign the mac artifacts

**Comment by zelinh** [comment]
@gaiksaya will create a separate issue for mac notarization.

**Comment by gaiksaya** [comment]
Created issue: https://github.com/opensearch-project/opensearch-build/issues/3682

Closing this issue as signing is supported now.
