### ISSUE TITLE
Central release workflow to support OpenSearch public release.

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/opensearch-build#3676]
### Is your feature request related to a problem? Please describe

Coming from the [RFC](https://github.com/opensearch-project/.github/issues/167) (Improving public engagement for OpenSearch release process) the central one click release workflow to support OpenSearch public release should remove the steps part of the release phase.

### Describe the solution you'd like

Central release workflow to support OpenSearch public release.

### Acceptance criteria:

Finish the suggested release pending issues/improvements as listed in https://github.com/opensearch-project/opensearch-build/issues/4216, once done consolidate all the release workflows/tools under one wrapper/cli and execute the wrapper/cli to call a release.

**Comment by gaiksaya** [comment]
Closing this issue as we now have centralized release workflow. See linked PRs.
Thanks!
