### ISSUE TITLE
Add security plugin check in startup script to to support bundle manifest for min distributions

### ISSUE THREAD

**Issue by rishabh6788** [opensearch-project/opensearch-build#3686]
Currently if the OpenSearch min bundle is run using [opensearch-tar-install.sh](https://github.com/opensearch-project/opensearch-build/blob/main/scripts/startup/tar/linux/opensearch-tar-install.sh) script, it will fail due to lack of security plugin in the bundle. 
Add security plugin check in the startup script. 
This will help in generating bundle manifest with artifact location for the min snapshot artifact generated during distribution build.

**Comment by gaiksaya** [comment]
I believe we need to check for any plugin configuration that goes in start up script. This includes:
- Security
- Performance Analyzer
- K-NN

See start up scripts here: https://github.com/opensearch-project/opensearch-build/tree/main/scripts/startup

**Comment by gaiksaya** [comment]
Hi @rishabh6788 I believe we can close this issue now since we added the check?
