### ISSUE TITLE
Update the current Validation mechanism to support artifacts from any URL or local path

### ISSUE THREAD

**Issue by Divyaasm** [opensearch-project/opensearch-build#3690]
Current Scenario:

The current Validation mechanism is designed to download OS and OSD artifacts only from [opensearch.org](https://opensearch.org/downloads.html) 

Acceptance criteria:
1. We should be able to validate artifacts which are locally present on the user machine.
2. And the code should be able to fetch the downloads from ci-staging bucket for both OS and OSD. The complete ci-staging url is provided by the user.
3. Url is the only input parameter provided by the user in the above two cases. And multiple distribution validations are taken care from Jenkins end.

**Comment by bbarani** [comment]
@Divyaasm Can you provide an update on current status?

**Comment by Divyaasm** [comment]
> @Divyaasm Can you provide an update on current status?

Just updated the procedure as recommended by @gaiksaya and @peterzhuamazon. Thanks

**Comment by Divyaasm** [comment]
Closing as the related PR #3993  is merged.
