### ISSUE TITLE
Detecting and alerting of duplication keys/components/entries in YAML file

### ISSUE THREAD

**Issue by jordarlu** [opensearch-project/opensearch-build#3694]
### Is your feature request related to a problem? Please describe

it was found in release 1.3.11 , a PR to update [manifest](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/1.3.11/opensearch-1.3.11.yml) has duplicated components name.
It would cause the resource wasted on CI to rebuild the duplicated components 

### Describe the solution you'd like

We want to have a check to detect if there is any duplication entries based on keys/components/names and probably fail the GitHub check

### Describe alternatives you've considered

Manually check for duplicate values

### Acceptance Criteria
* The manifest check should fail at CI level for components with duplicate components.name values in opensearch and opensearch-dashboard as well as test manifests. See what are [manifests](https://github.com/opensearch-project/opensearch-build/wiki/Building-an-OpenSearch-and-OpenSearch-Dashboards-Distribution#what-are-manifests)

**Comment by jordarlu** [comment]
One of the possible approaches with using yamllint - https://stackoverflow.com/a/35149964

**Comment by rblcoder** [comment]
.pre-commit-config.yaml has 
```
'pipenv run yamllint .'
```
The DEVELOPER_GUIDE.md also mentions running
```
$ pipenv run pre-commit install
$ pipenv run pre-commit run --all-files
```
How do we do this at CI level?
Should we try to run the same git hook in CI?

**Comment by hitenshKharva** [comment]
I would like to work on this issue.
