### ISSUE TITLE
Upgrade CMake to version: 3.23.3

### ISSUE THREAD

**Issue by navneet1v** [opensearch-project/opensearch-build#3706]
As part of upgrading the downstream libraries in K-NN to add the support for filtering[https://github.com/opensearch-project/k-NN/pull/942], we need to upgrade the CMake version otherwise builds for the K-NN Native Libraries will start to fail. The ask for the issue to upgrade the Cmake version to 3.23.3.

**Places to change:**
A simple search of Cmake in build repo these many places where changes needs to be done: https://github.com/search?q=repo%3Aopensearch-project%2Fopensearch-build%20cmake&type=code

Can you provide what is the best way to make these changes? Can this change be picked by the Build team?

Once the CMake is upgraded I will start to merge the PR in 2.x branch otherwise the build for 2.x will start to fail

**Comment by jordarlu** [comment]
@peterzhuamazon will take a look this , most likey it may be pushed to after 2.9.0, but Peter will provide more insights of it .. thanks ... here is a link to it for the reference .. https://github.com/opensearch-project/opensearch-build/issues/1563.

**Comment by navneet1v** [comment]
@jordarlu this needs to go in 2.9. There are changes in k-NN plugin that requires this.

**Comment by navneet1v** [comment]
The code change from k-nn is merged in 2.x branch. The build might start to fail now. Can we prioritize the 2.9 release distributions first

**Comment by peterzhuamazon** [comment]
Hi @navneet1v this is a last minute change and we are working on it already.
Thanks.

**Comment by peterzhuamazon** [comment]
PRs:
* https://github.com/opensearch-project/opensearch-build/pull/3722

**Comment by peterzhuamazon** [comment]
This task is complete by now.
Thanks.
