### ISSUE TITLE
[META] Update all 1-click process default docker to v4

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/opensearch-build#3712]
### Is your feature request related to a problem? Please describe

We recently upgraded the python version in the build repo (3.7 to 3.9 #3351). Due to this any code using build repo code fails if right python version is not used. Signing artifacts used by any client uses the build repo code hence updating the image to most recent one which is **opensearchstaging/ci-runner:release-centos7-clients-v4**

### Describe the solution you'd like

Update all code using standardReleasePipelineWithGenericTrigger and standardReleasePipeline build libraries

**Comment by joshuali925** [comment]
left a question https://github.com/opensearch-project/sql-jdbc/pull/104#pullrequestreview-1519562035

**Comment by peterzhuamazon** [comment]
Note: @gaiksaya please add this line to all the jenkinsfile so it can pick up the image from ecr: 
```
                    registryUrl 'https://public.ecr.aws/'
```

**Comment by gaiksaya** [comment]
Will take it up as an enhancement, It will need version upgrades as base library will need changes.

**Comment by bbarani** [comment]
Closing this issue as all the PR's related to this effort has been merged.
