### ISSUE TITLE
Add support for building patch releases

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#373]
**Describe the bug**
As of now, bundle workflows scripts are using bundle version as core version in the build step.

https://github.com/opensearch-project/opensearch-build/blob/main/bundle-workflow/src/build.py#L56

This means if we have discrepancy between a bundle version and the core version it bundled, it would fail.
1.0.1 example:
https://github.com/opensearch-project/opensearch-build/blob/main/manifests/1.0.1/opensearch-1.0.1.yml#L4-L9

**To Reproduce**
Use above manifest of 1.0.1 and try to run build.sh within bundle workflow.

**Expected behavior**
Bundle 1.0.1 with 1.0.0 core would work.

**Plugins**
All Plugins component script, example here:
https://github.com/opensearch-project/opensearch-build/blob/main/bundle-workflow/scripts/components/alerting/build.sh#L71

**Screenshots**

**Host/Environment (please complete the following information):**
 - OS: [Linux]
 - Version [AL2]

**Additional context**

**Comment by dblock** [comment]
We need to include component versions in the build manifest and possibly be able to pull binaries from a released location in assembly instead of rebuilding dependencies.
