### ISSUE TITLE
Automate model tracing and uploading for `opensearch-py-ml`

### ISSUE THREAD

**Issue by thanawan-atc** [opensearch-project/opensearch-build#3733]
### Is your feature request related to a problem? Please describe

OpenSearch ML Commons team has made available a few pre-trained sentence transformer models (https://opensearch.org/docs/latest/ml-commons-plugin/pretrained-models/) in language independent format to support users in their ML search and analytics use cases on OpenSearch. However, we receive frequent requests from customers to incorporate additional models into our model hub (https://github.com/opensearch-project/opensearch-py-ml/issues/182). Moreover, the current manual process of tracing and uploading these models is laborious and time-consuming. As a result, we want to automate this process to streamline model availability effectively.

### Describe the solution you'd like

Currently, I have a GitHub Actions workflow that can be triggered to trace and upload the model to my person S3 bucket. I believe that it can be easily modified to upload the model to OpenSearch ML Commons S3 production bucket by changing the credentials. What we want to discuss is about how to automate the last step (Step VI in diagram below): notifying the release team to initiate the Jenkins workflow after we have the model in our S3 production bucket. We hope to find a way to automatically notify you once our model is uploaded to our S3 production bucket instead of manually cutting the ticket.

### Additional context

- Existing System: Our procedure entails running a notebook (https://github.com/opensearch-project/opensearch-py-ml/blob/main/docs/source/examples/demo_tracing_model_torchscript_onnx.ipynb) to trace and validate the model’s embedding correctness before manual uploading to our production bucket. Subsequently, we create a ticket to notify the release team to initiate a Jenkins pipeline (https://github.com/opensearch-project/opensearch-py-ml/blob/main/jenkins/ml-models.JenkinsFile) to transfer the model to the model release hub. 
- New System: During the past few weeks, I have worked on creating GitHub Actions workflow which can now reach Step V, but I need help with Step VI.
<img width="413" alt="Screenshot 2023-07-13 at 10 35 49 AM" src="https://github.com/opensearch-project/opensearch-build/assets/106889996/777336ae-8ccf-4e47-9cf5-25368676d538">

**Comment by peterzhuamazon** [comment]
[Triage] As of now the ml py repo has two jenkinsfile, one for manually trigger jenkins workflow to publish models, and the other is to 1-click release for pypi push.

https://github.com/opensearch-project/opensearch-py-ml/tree/main/jenkins

The discussion from last time including these questions:
1. The model is provided by the ml team on their own S3 bucket, while our workflow only grabs the model, sign them, and publish to production s3 bucket. There is a size limit on the signing working of the artifacts, means ml teams needs to restrict their model sizes, or separate one model to several differents parts of an archive before we can keep automate the process further.
2. The previous conversation mentioned that training of these models require significant amount of GPU power from EC2 instances, and that is one of the reason the training part of ml team's own workflow, without integrating with our build system, as the build system only takes care of the publishing.

We need the ml teams to re-open the discussion of above questions again before we can help with linking all the parts into a one-click process.

Thanks.

**Comment by thanawan-atc** [comment]
To your question:
- With this automoated process we are targeting to release model which are under 2 GB. We believe that should not affect the current existing workflow.
- We aren't planning to train any model in the workflow. We are talking about the models which are already pre-trained (https://www.sbert.net/docs/pretrained_models.html) and published to public for use.
- We would like to keep the manual process in place if we plan to release any big model by us. In that way we can train and upload in our bucket manually and then raise a ticket (like before). But we want to automate the process for the smaller and pre-trained models to reduce our manual work. And these models doesn't require training in the github workflow.

**Comment by peterzhuamazon** [comment]
cc: @bbarani @prudhvigodithi

**Comment by gaiksaya** [comment]
Closing this issue as we have successfully automated uploading the models. Thanks @thanawan-atc for getting this in.
