### ISSUE TITLE
[Bug]: OSD Integration Tests: Workflow Check and OpenSearch Validation

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/opensearch-build#3792]
### Describe the bug

The [integ test workflow](https://github.com/opensearch-project/opensearch-build/tree/main/src/test_workflow) for OpenSearch Dashboards requires OpenSearch to be full up and running before running tests through OpenSearch Dashboards. Without OpenSearch cluster validation the integ tests are sometimes flaky and fail on that specific OSD component 

Sample Error
```
2023-07-12 23:20:46 INFO     Pinging http://localhost:5601/api/status

2023-07-12 23:20:46 INFO     Service not available, yet

2023-07-12 23:20:56 INFO     Sending SIGKILL to PID 219

2023-07-12 23:20:56 INFO     Process killed with exit code 1

2023-07-12 23:20:56 INFO     Sending SIGKILL to PID 240

2023-07-12 23:20:56 INFO     Process killed with exit code None
```
Error log: https://ci.opensearch.org/ci/dbc/integ-test-opensearch-dashboards/2.9.0/6382/linux/x64/tar/test-results/3680/integ-test/customImportMapDashboards/with-security/stdout.txt 

This was shown up for `customImportMapDashboards` during the 2.9.0 release where `customImportMapDashboards` [failed](https://github.com/opensearch-project/opensearch-build/issues/3616#issuecomment-1636583248)  and upon re-run [passed](https://build.ci.opensearch.org/blue/organizations/jenkins/integ-test-opensearch-dashboards/detail/integ-test-opensearch-dashboards/3684/pipeline) the next time.

### To reproduce

This is flaky but should show when running the [integ test workflow](https://github.com/opensearch-project/opensearch-build/tree/main/src/test_workflow) for OSD components.

Sample Failed build:
https://build.ci.opensearch.org/blue/organizations/jenkins/integ-test-opensearch-dashboards/detail/integ-test-opensearch-dashboards/3682/pipeline/

**Comment by peterzhuamazon** [comment]
[Triage] This needs some deep because the OSD without security plugin is able to connect to OS cluster, which mean the OS cluster has also disabled security plugin during without-security test.

We need some logs from the failure which we can pinpoint which part of the cluster deployment is not properly setup, in order to raise 401 issues during OSD integTest for multiple plugins.

**Comment by Divyaasm** [comment]
The Issue could be solved once the Build workflow is integrated with Validation Workflow. And the Integration tests are run only for the builds that pass the Validation which usually includes spinning up the OS and OSD cluster.
https://github.com/opensearch-project/opensearch-build/issues/3441

**Comment by Divyaasm** [comment]
Resolved by https://github.com/opensearch-project/opensearch-build/issues/4424 . The given artifacts are now validated first, if the cluster successfully comes up for OS and OSD Integ tests are triggered.
