### ISSUE TITLE
Add Spark SQL Application jar to snapshot

### ISSUE THREAD

**Issue by rupal-bq** [opensearch-project/opensearch-build#3794]
### Did you read the on-boarding document

Yes

### What is the name of your component?

Spark SQL Application

### What is the link to your GitHub repo?

https://github.com/opensearch-project/sql/tree/main/spark-sql-application

### Targeted release date

As soon as possible

### Where should we publish this component?

https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/

### What type of artifact(s) will be generated for this component?

jar file

### Have you completed the required reviews including security reviews, UX reviews?

N/A

### Have you on-boarded automated security scanning for the GitHub repo associated with this component?

Not required. Already enabled for repo.

### Additional context

Hi, We added [Spark SQL Application](https://github.com/opensearch-project/sql/tree/main/spark-sql-application) required for spark datasource and want to publish this application jar to snapshots. Please guide on how to achieve this. 

Can we update https://github.com/opensearch-project/sql/blob/main/.github/workflows/maven-publish.yml to publish spark-sql-application.jar ?

**Comment by peterzhuamazon** [comment]
[Triage] The secrets is already retrieving by the sql repo when initial setup done.
Since the spark sql app is within the same repo, we can use the same secrets, just need a corresponding publishing task.

However, it is confusing why spark sql app is in the sql repo as that is not a mono repo anymore.
Clients such as sql-jdbc have their own repository already.
Therefore, suggest sql team to move this client out of sql repo before publishing any jars.

Thanks.

**Comment by penghuo** [comment]
It is not a client. SQL plugin depend on spark-sql application to connect with Spark cluster.

**Comment by gaiksaya** [comment]
The above workflow uses `publishPluginZipPublicationToSnapshotsRepository` gradle task and publishes to snapshot repo.
I am not sure what framework is used to build the spark-sql. However, you just need to check how to publish to maven using that framework. Add that task to the above workflow or create a new workflow to publish spark only when code changes happen to `spark-sql-application` path.
From our end the credentials retrieval is already in place for the sql repo.

**Comment by rupal-bq** [comment]
Thanks @peterzhuamazon @gaiksaya @penghuo for explaining the process. created https://github.com/opensearch-project/opensearch-spark/pull/13 to update snapshot publish workflow. Closing this issue.
