### ISSUE TITLE
[Retrospective] Release 2.9.0

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/opensearch-build#3808]
This is Retrospective for the release 2.9.0
* https://github.com/opensearch-project/opensearch-build/issues/3616

How to use this issue?
Please add comments to this issue, they can be small or large in scope. Honest feedback is important to improve our processes, suggestions are also welcomed but not required.

What will happen to this issue post release?
There will be a discussion(s) about how the release went and how the next release can be improved. Then this ticket will be updated with the notes of that discussion along side action items.

**Comment by MaxKsyunz** [comment]
@AMoo-Miki during the release meeting you mentioned that the ODBC 1.5.0.0 artifact file prevented a script from completing successfully. Could you explain what happened? Is there something that needs to be done during ODBC release process to make this script pass?

**Comment by MaxKsyunz** [comment]
Thank you @bbarani.

How does one go about updating the website next time there is a new version of JDBC or ODBC drivers?

cc @acarbonetto

**Comment by prudhvigodithi** [comment]
## Details of all major event points for release `2.9.0`, along with their dates and short descriptions.

#### **July 11 2023** — Initial Planned Code Freeze date for 2.9.0

#### **July 11 2023** -- Initial Planned Code Complete date for 2.9.0

#### **Jul 14, 2023** — [1st RC generated](https://github.com/opensearch-project/opensearch-build/issues/3616#issuecomment-1636346380.)

##### PR's after the 1st RC

-  https://github.com/opensearch-project/dashboards-observability/pull/680
- https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4577 
- https://github.com/opensearch-project/alerting-dashboards-plugin/pull/645 
- https://github.com/opensearch-project/alerting-dashboards-plugin/pull/649/ 
- https://github.com/opensearch-project/alerting-dashboards-plugin/pull/649
- https://github.com/opensearch-project/index-management-dashboards-plugin/pull/813
- https://github.com/opensearch-project/security-analytics-dashboards-plugin/pull/656
- https://github.com/opensearch-project/index-management-dashboards-plugin/pull/818/files 
- https://github.com/opensearch-project/OpenSearch/pull/8513 
- https://github.com/opensearch-project/cross-cluster-replication/pull/1078 
- https://github.com/opensearch-project/OpenSearch/pull/8738 


#### **Jul 14, 2023** — [1st RC Integration tests](https://github.com/opensearch-project/opensearch-build/issues/3616#issuecomment-1636583248).

#### **Jul 14, 2023** - [1st RC manual sign off](https://github.com/opensearch-project/opensearch-build/issues/3616#issuecomment-1638891206).

#### **Jul 17, 2023** — [2nd RC generated](https://github.com/opensearch-project/opensearch-build/issues/3616#issuecomment-1641107212).

#### **Jul 18, 2023** -- [2nd RC Integration tests](https://github.com/opensearch-project/opensearch-build/issues/3616#issuecomment-1641364322).

#### **July 18, 2023** — [2nd RC manual sign off](https://github.com/opensearch-project/opensearch-build/issues/3616#issuecomment-1642426953).

##### PR's after the 2nd RC

- https://github.com/opensearch-project/alerting-dashboards-plugin/pull/659  https://github.com/opensearch-project/alerting-dashboards-plugin/pull/661 
- https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4599 
- https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/776 


#### **Jul 18, 2023** — Go/No-Go call, [move the release to July 20, 2023](https://github.com/opensearch-project/opensearch-build/issues/3616#issuecomment-1638966539).

#### **July 19, 2023 (1:07 pm)** - Called out in the “feature-anywhere” channel of the saved object limit issue on OSD

#### **July 19, 2023 (5:04 pm)** - Called out in the “opensearch-releases” channel of the [saved object limit issue on OSD](https://github.com/opensearch-project/opensearch-build/issues/3616#issuecomment-1642934238) and the need to get the fix in after discussing amongst the team if this is required for the `2.9` release. 

#### **July 19, 2023** - Got the OSD change for 2.9 related to the saved object limit issue merged.

Related PR: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4595 

#### **July 19, 2023** - Got the Alerting dashboard change for 2.9 related to the saved object limit issue merged.

Related PR: https://github.com/opensearch-project/alerting-dashboards-plugin/pull/659

#### **July 19, 2023** - Got the AD dashboard change for 2.9 related to the saved object limit issue merged.

Related PR: https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/pull/562 

#### **July 20, 2023** — [Move the release to July 24, 2023](https://github.com/opensearch-project/opensearch-build/issues/3616#issuecomment-1642934238). 

**As its not recommended to do the release on Friday's, the release date was adjusted to Monday (July 24, 2023)**.

#### **July 20, 2023** — [3rd RC generated](https://github.com/opensearch-project/opensearch-build/issues/3616#issuecomment-1644448439)(Only for OSD)  

#### **July 20, 2023 - [July 24, 2023](url) — [3rd RC manual sign off](https://github.com/opensearch-project/opensearch-build/issues/3616#issuecomment-1644690812). 

#### **July 24, 2023** — [Release](https://github.com/opensearch-project/opensearch-build/issues/3616#issuecomment-1646312725 ).

#### **July 24, 2023**. - [Post Release](https://github.com/opensearch-project/opensearch-build/issues/3616#issuecomment-1646312725)

**Comment by prudhvigodithi** [comment]
#### Following in the link to Retro Board:
https://github.com/orgs/opensearch-project/projects/140/views/1

**Comment by Divyaasm** [comment]
Closing the issue as the Retrospective Meet was completed
