### ISSUE TITLE
[BUG] Docker login/logout in Jenkins cause gradle check to fail on Windows

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#3816]
The windows runner does not have docker installed by default due to various reasons mentioned in opensearch-project/opensearch-ci#281.

When we add docker login for gradle check rate limit in #3367 we only make it run on linux.

We need to ignore this for windows for now. Thanks.

**Comment by peterzhuamazon** [comment]
Example issues: https://build.ci.opensearch.org/job/gradle-check/20933/console

**Comment by rishabh6788** [comment]
Waiting on https://github.com/opensearch-project/opensearch-ci/issues/281 to be resolved.

**Comment by peterzhuamazon** [comment]
PRs:
* https://github.com/opensearch-project/opensearch-build-libraries/pull/254
* https://github.com/opensearch-project/opensearch-build/pull/3817
* https://github.com/opensearch-project/opensearch-build/pull/3903

**Comment by peterzhuamazon** [comment]
More PR:
*  opensearch-project/opensearch-ci#354

**Comment by peterzhuamazon** [comment]
Keep seeing this:
```

ERROR: Timed out after 1210 seconds of waiting for winrm to be connected
com.amazonaws.AmazonClientException: Timed out after 1210 seconds of waiting for winrm to be connected
	at hudson.plugins.ec2.win.EC2WindowsLauncher.connectToWinRM(EC2WindowsLauncher.java:142)
	at hudson.plugins.ec2.win.EC2WindowsLauncher.launchScript(EC2WindowsLauncher.java:52)
	at hudson.plugins.ec2.EC2ComputerLauncher.launch(EC2ComputerLauncher.java:48)
	at hudson.slaves.SlaveComputer.lambda$_connect$0(SlaveComputer.java:298)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:80)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)


```

Will switch to c5 instance for windows as m5 is not stable at all for it.

**Comment by peterzhuamazon** [comment]
It is fixed now after several other PRs.

**Comment by peterzhuamazon** [comment]
Even more PRs:
* https://github.com/opensearch-project/opensearch-build/pull/4154

**Comment by peterzhuamazon** [comment]
We are moving to docker container run gradle check on both linux and windows now.
It does not make sense to maintain both docker image and ami version of the same setups.
Thanks.

**Comment by peterzhuamazon** [comment]
The container running gradle check is not returning stable runs.
We also have an issue with our Windows 2019 instance that does not support wsl2, which means we cannot run linux containers natively on Windows for now.

Per @mch2 discussion, we should either remove those docker-compose tasks for Windows, or put this task to backlog until we re-visit with update to Windows 2022 later.

As of now, it will still run windows but fail the docker-compose tasks, but at least it will not get blocked on the start because docker does not exist. Thanks.

**Comment by peterzhuamazon** [comment]
This has been fixed for now for docker commands not having errors on Windows agent.
But still, core team needs to disable linux containers on Windows runs.

@mch2 Thanks.
