### ISSUE TITLE
OpenSearch server not consistently spinning up in docker environment [BUG]

### ISSUE THREAD

**Issue by sarahchen6** [opensearch-project/opensearch-build#3821]
### What is the bug?
The `opensearchproject/opensearch:2.8.0` image occasionally produces the following error when running in a docker container environment: 

```
Error: Could not find or load main class Cannot
Caused by: java.lang.ClassNotFoundException: Cannot

Exited with code 1
```

Here is [the link](https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/10774/workflows/a8c0513a-a1b1-4306-88b7-cad8ae45d0da/jobs/401206) to an error occurrence.

### How can one reproduce the bug?
Spin up an environment with an `opensearchproject/opensearch:2.8.0` container. The error occurs non-deterministically, so it may require multiple runs in order to reproduce the bug.

### What is the expected behavior?
Container runs with no errors.

### What is your host/environment?
CircleCI, using a Docker executor and a "Medium+" resource class (3 vCPUs, 6GB RAM)

### Do you have any screenshots?
Below is a screenshot when an error occurs:
<img width="1252" alt="image" src="https://github.com/opensearch-project/docker-images/assets/68485867/132ddfed-3436-46b8-8471-0fe8fbb824fa">

Below is a screenshot when an error does not occur:
<img width="1252" alt="image" src="https://github.com/opensearch-project/docker-images/assets/68485867/ba120f21-d2da-4ee1-998a-0251e8a24fa2">

### Do you have any additional context?
The bug occurs very rarely; however, it is often enough such that test cases do not consistently pass because the OpenSearch container errors out before spinning up. I have been experimenting with various environment variables in the config / docker-compose file (i.e. `DISABLE_INSTALL_DEMO_CONFIG=true`, `OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m`, `bootstrap.memory_lock=true`). The simplest environment that fails with the same `Error: Could not find or load main class Cannot` issue is below:

```
environment:
      - discovery.type=single-node
      - DISABLE_SECURITY_PLUGIN=true
```

**Comment by rishabh6788** [comment]
`performance-analyzer` plugin can be resource intensive.
If you do not need the performance-analyzer plugin in your setup you can disable it following instructions [here](https://github.com/opensearch-project/opensearch-build/tree/main/docker/release#disable-performance-analyzer-agent-cli-and-related-configurations).

**Comment by jordarlu** [comment]
Hi, @sarahchen6 , hopefully you were able to find stable build experience by diabling the Performance Analyzer, and looked like you did it in your [PR](https://github.com/DataDog/dd-trace-rb/pull/3031) .. based on that, I am closing this issue, and please feel free to reopen it if still facing the same problem.. thanks !
