### ISSUE TITLE
[Bug]: [PyPI] Unsupported GPG signature uploaded to PyPI

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#3822]
### Describe the bug

We got this email.

```
What?

During your recent upload of opensearch-py to PyPI, we noticed you uploaded a GPG signature. However, support for GPG signatures has been removed from PyPI.

What should I do?

While uploads will continue to work, any signatures uploaded to PyPI will be discarded. It is recommended to no longer upload signatures to PyPI.
```

### To reproduce

Release opensearch-py.

**Comment by dblock** [comment]
https://github.com/opensearch-project/opensearch-py/releases/tag/v2.3.0

**Comment by gaiksaya** [comment]
We have this issue open for removing the signing part: https://github.com/opensearch-project/opensearch-build-libraries/issues/222

Also observed we can get away from jenkins and use github pypi OIDC to do the releases. Will create an issue soon once I have more details.

**Comment by gaiksaya** [comment]
Here is something to get started: https://github.com/pypa/gh-action-pypi-publish
