### ISSUE TITLE
[release]: Logstash OSS with OpenSearch Output Plugin 8.9.0

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/opensearch-build#3849]
### Did you read the on-boarding document

Yes

### What is the name of your component?

Logstash OSS with OpenSearch Output Plugin

### What is the link to your GitHub repo?

https://github.com/opensearch-project/logstash-output-opensearch

### Targeted release date

Aug 10, 2023

### Where should we publish this component?

Docker Hub
Artifacts on opensearch.org

### What type of artifact(s) will be generated for this component?

* Docker image
* tar.gz artifacts for linux with x64
* tar.gz artifacts for linux arm64
* tar.gz artifacts for macos x64

### Have you completed the required reviews including security reviews, UX reviews?

N/A

### Have you on-boarded automated security scanning for the GitHub repo associated with this component?

Yes.

### Additional context

None

**Comment by gaiksaya** [comment]
Hi @dlvenable ,

I see that logstash was on-boarded to 1-click release process https://github.com/opensearch-project/logstash-output-opensearch/pull/188
Are the above artifacts addition to the [ruby-gems publication](https://github.com/opensearch-project/logstash-output-opensearch/blob/main/jenkins/release.jenkinsFile) or are the completely different?
Thanks!

**Comment by gaiksaya** [comment]
Closing the issue as logstash OSS with output plugin https://opensearch.org/downloads.html
