### ISSUE TITLE
Add support for qualifiers to bundle-workflow

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#385]
**Is your feature request related to a problem? Please describe.**

Add support to bundle workflow to produce -beta and -rc releases, similar to snapshots.

**Comment by peternied** [comment]
[Triage] @dblock is this blocking a process or feature?  It seems like the existing bundle build workflow is constantly producing 'release candidates' or 'betas'

**Comment by dblock** [comment]
AFAIK no, but Java projects typically include those qualifiers in the version so someone might want this? I’m ok to close too.

**Comment by peternied** [comment]
If we feel we need this for 2.0.0 then we should make sure we add this to the roadmap, trying to keep the backlog small(er)
