### ISSUE TITLE
Block PRs from merging if the link checker fails in the documentation repo

### ISSUE THREAD

**Issue by kolchfa-aws** [opensearch-project/opensearch-build#3851]
### Is your feature request related to a problem? Please describe

The link checker in the [documentation repo](https://github.com/opensearch-project/documentation-website/) runs on every pull request and subsequent commit. Even when the link checker fails, the merge button is still enabled and the PR can be merged. So broken links sometimes seep through to the codebase.

### Describe the solution you'd like

We'd like to disallow merging when the link checker has found broken links and is failing. The other workflow (vale) is set up as non-blocking and should not prevent the PR from being merged.

### Describe alternatives you've considered

The alternative relies on individual diligence which is hard to enforce.

**Comment by kolchfa-aws** [comment]
@CEHENKLE for visibility

**Comment by CEHENKLE** [comment]
@bbarani  what do you think?  Can we make this a blocking check?

**Comment by bbarani** [comment]
I have enabled the mandatory status checks before merging in main branch.

<img width="607" alt="Screen Shot 2023-08-06 at 6 51 01 PM" src="https://github.com/opensearch-project/opensearch-build/assets/70038446/d886e8a4-b755-4559-b317-2d8f70f61959">

@kolchfa-aws Let us know if this works now.

**Comment by gaiksaya** [comment]
I see that above check is only enabled on `main` branch. For enabling on all branches you can modify the branch specific rules here: https://github.com/opensearch-project/documentation-website/settings/branches
Closing this issue as no action item is pending from our end. 
Thanks!
