### ISSUE TITLE
Move Lucene snapshot from custom repository to artifacts.opensearch.org

### ISSUE THREAD

**Issue by mch2** [opensearch-project/opensearch-build#3874]
### Is your feature request related to a problem? Please describe

Today OpenSearch hosts snapshot versions of Lucene at 
`repo.setUrl("https://d1nvenhzbhpy0q.cloudfront.net/snapshots/lucene/");`. These snapshot versions are used to build/test against unreleased versions of Lucene on main & 2.x [example](https://github.com/opensearch-project/OpenSearch/blob/main/buildSrc/version.properties#L2).  This extra url is a bit sloppy, confusing and requires extra management when we already have a url for artifacts.  It would be great to host these instead under the `https://artifacts.opensearch.org/snapshots` or `ci.opensearch.org` umbrella.

### Describe the solution you'd like

Create a repository under https://artifacts.opensearch.org/snapshots/lucene to host the snapshots.  I think all that would be required here is a new path?
For context the existing repo was set up using the https://github.com/opensearch-project/data-prepper/tree/main/release/staging-resources-cdk.

The workflow pushing built snapshots is [here](https://github.com/opensearch-project/OpenSearch/blob/main/.github/workflows/lucene-snapshots.yml).  All that would need to change there is the bucket/role used. 

### Describe alternatives you've considered

Leaving as is.

### Additional context

After this is created we can update the WF to push to the new bucket (or both temporarily), update RepositoriesSetupPlugin and any downstream using the old url directly.

### Acceptance Criteria

Lucene Snapshots should be downloaded from ci.opensearch.org

**Comment by gaiksaya** [comment]
Hey! 

I believe ci.opensearch.org is a better choice. We eventually want to move https://artifacts.opensearch.org/snapshots/ to ci.opensearch.org/snapshots too. 

Thanks!

**Comment by peterzhuamazon** [comment]
I want to mention that apart from moving the snapshot, we also need to start a campaign to make sure repos that use that snapshot will have the new url.

Ex: [October 9, 2023, 2:30 PM] Zhu, Peter: https://github.com/opensearch-project/ml-commons/blob/main/build.gradle#L33

**Comment by peterzhuamazon** [comment]
Just talked with @mch2 on this and get the latest status.
Will start working on this task by 1st switching to the staging account,

**Comment by peternied** [comment]
We've seen build & test failures [1] from the current hosting setup - 🤞 this change would improve the support and stability. 

- [1] https://github.com/opensearch-project/security/issues/3597

**Comment by peterzhuamazon** [comment]
Start looking at the setups to add a new role for the syncing.

**Comment by peterzhuamazon** [comment]
Able to connect to my own s3 bucket and also improve the github workflow more.
Next is to setup the account connection between aws and github actions, and raise PRs.

Thanks.

**Comment by peterzhuamazon** [comment]
@mch2 will take care of the dependencies update once the link is available.
We are able to create roles to allow the process to happen.

**Comment by peterzhuamazon** [comment]
All backend setups are completed now.
PR in OpenSearch: 
* https://github.com/opensearch-project/OpenSearch/pull/11241

**Comment by peterzhuamazon** [comment]
Old snapshots are synced to new bucket now.

**Comment by peterzhuamazon** [comment]
With PR merged now I think @mch2 will start testing both after publishing a new snapshot.

**Comment by peterzhuamazon** [comment]
Hi @mch2 we are closing this issue as Infra task is completed, please open another issue if you want to track changing urls.

Thanks.

**Comment by peterzhuamazon** [comment]
Hi @peternied @owaiskazi19 @mch2 :

Recently I have noticed you updated a lot of the lucene snapshots url.
However it is not `artifacts.opensearch.org` but `ci.opensearch.org`.
As I stated in this comment here:
https://github.com/opensearch-project/opensearch-build/issues/3874#issuecomment-1836600851

The production bucket have some lucene snapshots but it is very old.
I will ask my manager whether we still want to keep those or not.

Would you mind correct this url in all repos are corrected so repos can correctly consume the changes.

Thanks!

**Comment by peternied** [comment]
### My Bad
![image](https://github.com/opensearch-project/opensearch-build/assets/2754967/2a57dfe4-6142-4568-a993-c975c6559e23)
