### ISSUE TITLE
search of project

### ISSUE THREAD

**Issue by rickon43** [opensearch-project/opensearch-build#3890]
### Is your feature request related to a problem? Please describe

In this project request that will helpful to identify the keywords that mentioned .moreover, for this we need to use this in the dashboard 

### Describe the solution you'd like

In the dashboard that u need to mentioned the keyboard

**Comment by bbarani** [comment]
@rickon43 Can you please add more details on this issue? Do you have a question or enhancement request?

**Comment by rickon43** [comment]
In this which I have to add the task details just like overall history where we can see it is like enhancement request

**Comment by rickon43** [comment]
yes, I have question about this specific search about this enhancement request. like I want to know what u want to give the request about

**Comment by gaiksaya** [comment]
Hi @rickon43 ,

Sorry we are still not clear on the request here. Can you try giving us an example what feature are you requesting? If its more related to OpenSearch as product (new API requests, etc) we would suggest opening issue in https://github.com/opensearch-project/opensearch repository.
Thanks!

**Comment by bbarani** [comment]
Closing this issue as we didn't hear back from the requester for sometime now. Please feel free to re-open if needed.
