### ISSUE TITLE
Onboard opensearch-ruby-aws-sigv4 to the automated release process

### ISSUE THREAD

**Issue by nhtruong** [opensearch-project/opensearch-build#3892]
### Is your feature request related to a problem? Please describe
Onboard [opensearch-ruby-aws-sigv4](https://github.com/opensearch-project/opensearch-ruby-aws-sigv4) to the new automated release process.

### Describe the solution you'd like
The solution is outlined in https://github.com/opensearch-project/opensearch-build/issues/1234.

**Comment by zelinh** [comment]
[Triage] I would take a look into this to onboard to our 1-click release process. Thanks.

**Comment by gaiksaya** [comment]
The repo is on-boardeded to 1-click release process. Here is the new workflow: https://build.ci.opensearch.org/view/Release/job/release-opensearch-ruby-aws-sigv4/
The webhooks and everything are in place. 
Please update your documentation for new workflow link.
Thanks!

Closing this issue. Please re-open in case of any issues.

**Comment by jordarlu** [comment]
@nhtruong , just wondering if you are planning to have a new release soon?  thanks !!
