### ISSUE TITLE
[Benchmark test] Support telemetry parameter

### ISSUE THREAD

**Issue by tlfeng** [opensearch-project/opensearch-build#3909]
### Is your feature request related to a problem? Please describe

Support telemetry parameters in the benchmark script that used for nightly build.

Some telemetry device support parameters to change its behavior, such as https://github.com/opensearch-project/opensearch-benchmark/blob/ce55073c757303e1f001f14c3c0ef5a1f994fffe/osbenchmark/telemetry.py#L330 (search `:param telemetry_params` for more usage on that page).

Use case:
- Collect segment metrics for remote store feature.
The usage in opensearch-benchmark commands is adding parameters `--telemetry="node-stats" --telemetry-params="telemetry.json"`
Then create  telemetry.json` with content `{"node-stats-include-indices":"true","node-stats-include-indices-metrics":"segments"}`. (It's possible to pass parameters in line, except in separate files.)
- Change metrics collecting interval, by configuring `xxx-sample-interval` parameters.
- Filter the index on which the metrics are collected, by configuring `xxx-indices` pameters. For example, filter out the system indices.

### Describe the solution you'd like

Add support for OSB parameter `--telemetry-params` in this file of benchmark script https://github.com/opensearch-project/opensearch-build/blob/2.9.0/src/test_workflow/benchmark_test/benchmark_args.py

**Comment by rishabh6788** [comment]
`--telemetry-params` support has been added in https://github.com/opensearch-project/opensearch-build/pull/3912. 
See successful run [here](https://build.ci.opensearch.org/blue/organizations/jenkins/benchmark-test/detail/benchmark-test/5335/pipeline/37/)
