### ISSUE TITLE
Revamping distribution build system

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/opensearch-build#3921]
### Is your feature request related to a problem? Please describe

The current OpenSearch build system is fully automated, python based build system that uses manifests to build from the source. [Read how to build distributions from source](https://github.com/opensearch-project/opensearch-build/wiki/Building-an-OpenSearch-and-OpenSearch-Dashboards-Distribution). However, with current set up there are few limitations causing the end to end process to build distributions especially during release cycles to be delayed by 2 to 3 hours. Along with this, the distribution build workflow for [opensearch](https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/opensearch/distribution-build.jenkinsfile) and [opensearch-dashboards](https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/opensearch-dashboards/distribution-build.jenkinsfile) is tightly coupled for all distributions and architectures. Today, if we need to rebuild just one distribution or just one component of the distribution, it is not possible with this clunky workflow. Hence, we need to enhance our build system to allow decoupled, efficient builds as well as re-builds with minimal effort and time.

### Describe the solution you'd like

The solution can be categorized into two:

- [x] #3922
- [x] https://github.com/opensearch-project/opensearch-build/issues/1906

**Comment by zelinh** [comment]
Closing this issue as all sub tasks are done.
