### ISSUE TITLE
Add an Emeritus section to this repository

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#3923]
There are a couple of former maintainers that could be recognized as emeritus, what do you think about adding the following folks?

| Person |
| - | 
| [abhinavGupta16](https://github.com/abhinavGupta16)
| [kavilla](https://github.com/kavilla)
| [mch2](https://github.com/mch2)
| [peternied](https://github.com/peternied) (myself)

Anyone else that should be [recognized](https://github.com/opensearch-project/opensearch-build/graphs/contributors)?

**Comment by bbarani** [comment]
For now, we will add the below past maintainers to Emeritus section:

| Person |
| - | 
| [abhinavGupta16](https://github.com/abhinavGupta16)
| [Cameron Skinner](https://github.com/camerski)
| [mch2](https://github.com/mch2)
| [peternied](https://github.com/peternied) (myself)

CC: @jordarlu
