### ISSUE TITLE
[FEATURE] Set UID and GID of opensearch user and group to 10000

### ISSUE THREAD

**Issue by nilushancosta** [opensearch-project/opensearch-build#3932]
### Is your feature request related to a problem?
[Checkov](https://www.checkov.io/) recommends that the UID of containers run with 10000 or more - Ref: [Ensure containers run with a high UID to avoid host conflict](https://docs.bridgecrew.io/docs/bc_k8s_37)

### What solution would you like?
Change the UID (and GID to make is consistent) defined in the Dockerfile to 10000

**Comment by jordarlu** [comment]
Hi, @nilushancosta , with the concern that changing the UID and GID to other may break many, and this issue has been opened for quite some time now, I am closing it for now, please feel free to re-open it for any further discussion. Thank you !
