### ISSUE TITLE
[Proposal] Move 2.10.0 first RC generation date to Wednesday Sept 6th 2023

### ISSUE THREAD

**Issue by CEHENKLE** [opensearch-project/opensearch-build#3954]
### Is your feature request related to a problem? Please describe

Hello all;

The current first cut RC date is currently scheduled for September 05th (https://opensearch.org/releases.html).  This is a federal Holiday in the US, so it will be difficult for developers to get in last minute changes.

I'd like to propose that we move the first RC cut date to 5pm PT, Wed 6th, and the last possible release date to the 22nd.   As a reminder, OpenSearchCon starts on the 27ths, so this will be the last release before OSC.

If I don't hear any minus ones, we'll officially move the release date over the weekend.

### Describe the solution you'd like

N/A

**Comment by austintlee** [comment]
The title should say "Wednesday Sept 6th".

**Comment by rramachand21** [comment]
Would it be possible to move the 2.10 first RC generation date to Thursday 7th 2023 as contributors could not merge their changes including dependent PRs because of multi-hour impact on github yesterday:
1. https://www.githubstatus.com/incidents/c8zjb9351hlc - ~1 hour impact
2. https://www.githubstatus.com/incidents/frdfpnnt85s8 - ~7 hours impact

**Comment by CEHENKLE** [comment]
I personally don't have an issue, although it means we may need to move out the last possible release date to the 25th.  

I've put out a channel notification in slack, and if no one protests in the next few hours, we'll consider it officially moved.

**Comment by gaiksaya** [comment]
Closing this issue as the date for RC generation has been move to September 07, 2023.
See https://opensearch.org/releases.html and https://github.com/opensearch-project/opensearch-build/issues/3743
