### ISSUE TITLE
Proposal/potential to move the 2.11 in

### ISSUE THREAD

**Issue by CEHENKLE** [opensearch-project/opensearch-build#3955]
### Is your feature request related to a problem? Please describe

Hello all;

We've gotten a request from some folks at Amazon to *potentially* move the 2.11 date in.  The current 2.11 release window is November 9th - November 16th.  Re:invent (which is AWS major yearly conference) happens at the end of November, and the AWS OpenSearch service needs more time to pick up changes from open source OpenSearch.  So the ask is that we would move our release window into early October.

However, even though they're pushing really hard to get in before the conference, and they don't know if they're going to be ready.  If they're not ready, then there's no point in us moving the dates.

So here's the the proposal:

October 2nd we'll do a check in to see if there are enough changes to make a release worthwhile. 

-  If there are,  we would start our release window by building the first release candidate October 4th, with a last possible release date on October 18th.   This would become 2.11, and we would either made 2.12 in Dec or Jan (TBD).
- If they are not ready, then we'd leave the 2.11 date where it is November 9th - November 16th .

I'll also ask that the issues/PRs that are being tracked for the release get added here so we have better visibility.

### Describe the solution you'd like

N/A

**Comment by peternied** [comment]
I'd rather slim down this proposal to a pull request which is:

> Add another minor release target, this new release is scheduled to for an RC on Oct 4th. 

Since releases are based on windows entry/exit criteria, we can have those tough conversations as we do for every release.

**Comment by CEHENKLE** [comment]
Mostly agree, @peternied , but I think the nuance is that if the folks aren't going to have their changes ready, there's no point in doing the release (hence the check in Oct 2nd).

**Comment by rohin** [comment]
An early release, if possible, provides everyone an opportunity to be ready before peak holiday season. The ask of the community and maintainers is if we can pull this in leaving enough time for users around the project to incorporate in their production environments.

**Comment by CEHENKLE** [comment]
We've added the potential October release into the roadmap so we can have better visibility into what might go in to it, and what the status of those features are.  

If you have a candidate for that release, please add it, or put a comment here and I'll add it for you. 

Thanks!

**Comment by dagneyb** [comment]
In order to ensure we are tracking uniformly across issues going forward, can we go ahead and make the call that we will call this October 4th (latest) release date "2.11", and shift the future dates for subsequent releases in? If we don't end up doing this 2.11 release by October 4th and we push the date, we can adjust as needed at that point and add additional items to the release with the extra time.

Thanks

**Comment by reta** [comment]
One of nice to have deliverables in 2.11 would be JDK-21 (which is on plan to be released on Sep 19). It is very unlikely we'll get it in if release date slips into October. Also, would be have enough features for the release in just about a month from now?

**Comment by krisfreedain** [comment]
Something to consider with this; OpenSearchCon is three days and ends on Friday, September 29th - the following Monday is October 2nd, then RC on the 4th. 

Is that a potential strain on anyone?

**Comment by peternied** [comment]
I'm a visual person, here is a chart of the different options with special events included, each interval represents 5 days if this helps anyone else figure where things are at:

```mermaid
gantt
    title OpenSearch Release Timeline
    dateFormat YYYY-MM-DD
    excludes    weekends
    tickInterval 1week
    section Special Events
        OpenSearchCon          :crit, 2023-09-27, 3d
        Thanksgiving              :crit, 2023-11-23, 7d
        Christmas                   :crit, 2023-12-25, 7d
    section Original Schedule
        2.11          :2023-11-09, 7d
        2.12          :2024-01-09, 14d
    section Proposed Schedule
        2.11          :2023-10-04, 14d
        2.12          :2023-12-09, 30d
```

**Comment by CEHENKLE** [comment]
> One of nice to have deliverables in 2.11 would be JDK-21 (which is on plan to be released on Sep 19). It is very unlikely we'll get it in if release date slips into October. Also, would we have enough features for the release in just about a month from now?

If we want to do another release this year on the open source, we absolutely can (I'm personally betting on 2.12 being the first week in Dec, but I was kinda  waiting for the dust to settle down on 2.11 before brining it up).   

As for will there be enough features/fixes, the current working theory is that there will be, but that was why I wanted to check in on Oct 2nd.  But it sounds like that uncertainty is causing some pain.  So @dagneyb 's ask was to just commit to Oct, even if it's a skinny release, so we can reset the calendar now with some certainty.

**Comment by CEHENKLE** [comment]
> Something to consider with this; OpenSearchCon is three days and ends on Friday, September 29th - the following Monday is October 2nd, then RC on the 4th.
> 
> Is that a potential strain on anyone?

My thought is that the folks who requested the date shift are primarily in IN, and will not (for the most part) be attending OSC, so I believe they're less impacted.  The strain on the infra/EE (who will be attending OSC)  generally happens once the release train starts, so after OSC.   

But if other folks have different opinions please LMK.  Feel free to knock me off my ivory tower ;)

**Comment by rramachand21** [comment]
Would prefer a RC for 2.11 generated by October 5th as per the proposal above and commit to this date. This release is needed for reinvent as called out in the proposal.

**Comment by model-collapse** [comment]
Sept.28th-Oct.6th is the Chinese National Holiday. This adjustment will be extremely unfriendly to Chinese contributors. I would like to suggest the code freeze date to be Oct.10th, allocating 3 more days after the holiday for the developers to deal with pre-release issues. The Chinese learning team is onto a re:Invent related feature, and need to guarantee the deliver quality with the regard to the holidays.

**Comment by gaiksaya** [comment]
Just to make it clear (I think the dates got misunderstood in between the conversation).
> We would start our release window by building the first release candidate October 4th, with a last possible release date on October 18th.

- First release candidate would be built on **Oct 4th, 2023** (Just the candidate not the release). 
- The potential release date would be **Oct 18th, 2023**
cc: @dagneyb @rramachand21

**Comment by CEHENKLE** [comment]
Okay, this has been open for 3 weeks, and we're "thisclose" to having an RC up for 2.10, so I'm going to put up the PRs to officially move the dates around. 

Thanks,
/C

**Comment by CEHENKLE** [comment]
Please note:  I've left 2.12 where it was (January), so if folks want to have another release in 2023, we'll need to add it.  I think the best date would probably be to open the window the first week in Dec, with the release being on the 15th, but if we don't have a pressing need, also happy to hold it until next year.

**Comment by gaiksaya** [comment]
Hi @CEHENKLE
Can we close this issue? Seeing that website is already updated with new dates: https://opensearch.org/releases.html
Thanks!
