### ISSUE TITLE
Remove "Update to the <version> release branch in the distribution manifest" step from plugin repo release checklist

### ISSUE THREAD

**Issue by msfroh** [opensearch-project/opensearch-build#3979]
In the plugin repo release checklist (e.g. https://github.com/opensearch-project/dashboards-search-relevance/issues/253), there is a step "Update to the <version> release branch in the distribution manifest".

I created a PR to do that https://github.com/opensearch-project/opensearch-build/pull/3978 just a couple of minutes after @gaiksaya updated *all* the repos to the 2.10 release branch in https://github.com/opensearch-project/opensearch-build/pull/3977.

I love that all the repos were switched in a single PR (thanks @gaiksaya!), but we should probably remove that step from the checklist for the next release. (I lost 2 whole minutes making my change and posting a PR!)

**Comment by gaiksaya** [comment]
Adding the template that creates those issues and needs change https://github.com/opensearch-project/opensearch-build/blob/main/.github/ISSUE_TEMPLATE/component_release_template.md
