### ISSUE TITLE
Build process should use multiple agent nodes in parallel

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#399]
**Is your feature request related to a problem? Please describe.**
Building is a critical path process, but if we are making multiple builds based on different architectures they are unrelated, and should be parallelized for speed.  With the existing setup for jenkins with cloud agents, when parallel is being used the same machine is being reused this is causing contention between staging directories, local maven, and other things.

**Describe the solution you'd like**
Switch back to [parallel](https://www.jenkins.io/doc/book/pipeline/syntax/#parallel) for the stage execution, but come up with a method to make sure they are executed on different nodes.

**Describe alternatives you've considered**
There might be easier methods to signal/manage how this is done, open to alternative approaches that keep the isolation and would add speed to the existing processes.  Using docker for each agent could be a consideration

![Isolation Diagram](https://user-images.githubusercontent.com/2754967/132582006-2583a207-edbd-449c-8e4e-e13a0fdd0943.png)
[Img Source](https://gist.github.com/peternied/26d038d386b2e9119991bf3af61a3dd8)

**Additional context**
See #396

**Comment by peternied** [comment]
@peterzhuamazon Transferring this issue to you as you were going to look into making this change for staging environment

**Comment by peterzhuamazon** [comment]
Sure, I already get the docker image moved to staging repo, and we can consume the runner from there. Will follow up with more next actions next week.

**Comment by peternied** [comment]
@peterzhuamazon Any updates?

**Comment by peterzhuamazon** [comment]
I will start working on this tomorrow.
