### ISSUE TITLE
opensearch-dashboards-functional test repo should always checkout release branch head commit

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/opensearch-build#4057]
### Is your feature request related to a problem? Please describe

[opensearch-dashboards-functional test](https://github.com/opensearch-project/opensearch-dashboards-functional-test) repo is also added to the input manifest list file creating a distribution. This repository only hosts the tests to all the dashboards' plugins and core engine. 
The current test process downloads build manifest and checkouts the commit head commit during RC build. See [code block](https://github.com/opensearch-project/opensearch-build/blob/d1a6ab24f4e4cbedcfc1f8ea7149043fe7e8f5e7/src/test_workflow/integ_test/integ_test_suite_opensearch_dashboards.py#L61-L63)

However for past few releases and with new release window model [exit criteria](https://github.com/opensearch-project/.github/blob/main/RELEASING.md#Exit-Criteria-to-Close-Release-Window) we need to fix the failing tests and remove the flaky ones.
Hence, today, if there are changes to the test code in  opensearch-dashboards-functional test repo we need to rebuild the release candidate to include those changes. This is because, the way [test workflow](https://github.com/opensearch-project/opensearch-build/tree/main/src/test_workflow) code is written, we use build manifest to fetch the commit ids to checkout the repository. See [code block](https://github.com/opensearch-project/opensearch-build/blob/main/src/test_workflow/integ_test/integ_test_suite_opensearch_dashboards.py#L61-L66)
Since there is no change in the actual software code shipped to the customer but just the tests and the fact that opensearch-dashboards-functional test repo is not shipped to the custome,  re-creating RC is irrelevant. 

### Describe the solution you'd like

We would like to always checkout the head-commit of the release branch (mentioned in the [input manifest](https://github.com/gaiksaya/opensearch-build/blob/173efed68baa0868a1b24f78c933ef32c219cc68/manifests/2.10.0/opensearch-dashboards-2.10.0.yml#L15)). For example, if the release version is `2.10.0` the release branch would be `2.10`
This branch can either be grabbed from input manifest (preferred) or regex to `major.minor` branch to be checkout each time we run tests.

### Describe alternatives you've considered

- Keep what we have
- Pass branch to run test against as an input paramater

**Comment by gaiksaya** [comment]
Would like to get some input from developers here: @kavilla @dblock @amsiglan @kavithacm 
Thanks!

**Comment by gaiksaya** [comment]
Hi @tranngocsongtruc, assigning this issue to you. Please go through it and let us know if you have any questions.
Thanks!

**Comment by tranngocsongtruc** [comment]
> Hi @tranngocsongtruc, assigning this issue to you. Please go through it and let us know if you have any questions. Thanks!

Please assign me this issue. Thank you

**Comment by gaiksaya** [comment]
Hi @tranngocsongtruc looks like there is no progress on this issue. Please let us know if you need any help or have questions. Un-assigning you from this issue for now so that it can be picked up by someone else.

**Comment by chawinphat** [comment]
I'd like to try submit a PR for this.

**Comment by chawinphat** [comment]
@gaiksaya would the change for this issue just be changing this [code block](https://github.com/opensearch-project/opensearch-build/blob/main/src/test_workflow/integ_test/integ_test_suite_opensearch_dashboards.py#L61-L66) to 
pass in `build_manifest_opensearch_dashboards.components['functionalTestDashboards'].ref` instead of `build_manifest_opensearch_dashboards.components['functionalTestDashboards'].commit` as an argument.

**Comment by chawinphat** [comment]
@gaiksaya I talked to @peterzhu1992 at office hours this week and he suggested that grabbing the ref from the input manifest wouldn't work since the test does not read from the input manifest.

An alternative suggestion he made was to add a new parameter that accepts either a ref or a sha256 hash pointing to a commit. This would let users checkout whichever commit they want, including their own branches. Furthermore, the default behavior would still be to grab the ref from the build manifest.

**Comment by gaiksaya** [comment]
> An alternative suggestion he gave was to add a new parameter that accepts either a ref or a sha256 hash pointing to a commit. This would let users checkout whichever commit they want, including their own branches. Furthermore, the default behavior would still be to grab the commit from the build manifest.

Sounds like a plan. Makes sense to keep the default behavior same as it is right now but it a non-null value is provided, it should be able to check that ref out. One correction, you still cannot use the fork/own branches since the github repo_url comes from build manifest but whatever is in repo_url is in build manifest, many ref should be good to use.

**Comment by peterzhuamazon** [comment]
Closes by #4419.
