### ISSUE TITLE
Support JDK-21 builds on Build and CI

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#4071]
Support JDK-21 builds on Build and CI.

https://endoflife.date/oracle-jdk

JDK 20 is eol and we will need to support JDK21 from Temurin in both Core and Build/CI.

**Comment by peterzhuamazon** [comment]
Will work with @reta on this one.

**Comment by peterzhuamazon** [comment]
Waiting: 
* https://github.com/opensearch-project/OpenSearch/pull/10138

**Comment by peterzhuamazon** [comment]
PRs:

Placeholder

**Comment by peterzhuamazon** [comment]
Several areas to update for this new JDK:
1. Jenkins tool
2. Docker images
3. AMIs
4. Gradle Check Workflow.

------

We also need to have some sort of a meta / campaign so plugin owners can update their main branch with newer versions of the Gradle for JDK21 support.

Hi @reta would you mind create a campaign for that?
Thanks!

**Comment by peterzhuamazon** [comment]
Waiting for Gradle 8.4 while temurin delayed 21:
https://adoptium.net/blog/2023/09/temurin21-delay/

**Comment by peterzhuamazon** [comment]
Will change global tools settings and remove deprecated JDK exports for Ubuntu once I onboard both gradle checks to container based setups.

https://github.com/opensearch-project/opensearch-build/issues/3816#issuecomment-1771581749

**Comment by peterzhuamazon** [comment]
* #4172

**Comment by peterzhuamazon** [comment]
@reta awaiting:
* https://github.com/ScoopInstaller/Java/pull/495

**Comment by peterzhuamazon** [comment]
* https://github.com/opensearch-project/opensearch-ci/pull/367

**Comment by peterzhuamazon** [comment]
* https://github.com/adoptium/temurin/issues/9

**Comment by peterzhuamazon** [comment]
* https://github.com/adoptium/temurin/issues/9

**Comment by peterzhuamazon** [comment]
* https://github.com/opensearch-project/opensearch-ci/pull/370

**Comment by peterzhuamazon** [comment]
* https://github.com/opensearch-project/opensearch-ci/pull/371

**Comment by peterzhuamazon** [comment]
Try one run: https://build.ci.opensearch.org/job/gradle-check/29304/console

**Comment by peterzhuamazon** [comment]
Windows can switch to temurin21 now:
* https://github.com/ScoopInstaller/Java/pull/498

**Comment by peterzhuamazon** [comment]
* https://github.com/opensearch-project/OpenSearch/issues/10334

**Comment by reta** [comment]
@peterzhuamazon I think we are done with CI, right?

**Comment by peterzhuamazon** [comment]
> @peterzhuamazon I think we are done with CI, right?

I am using the opportunities of the `ci-runner` switch to update JDK21 on Windows to Temurin.
https://github.com/opensearch-project/opensearch-build/issues/4191

**Comment by peterzhuamazon** [comment]
All images have been updated to JDK21 with temurin distributions, except gradle check on Windows AMI.
That one can be taken care later on.

Thanks.
