### ISSUE TITLE
Add option to run benchmark against OS artifact url

### ISSUE THREAD

**Issue by rishabh6788** [opensearch-project/opensearch-build#4073]
The nightly benchmarks currently depend on the distribution manifest file to get the location of the OpenSearch distribution tarball and then set up the cluster and run benchmark. 
There have been a few requests to run ad-hoc benchmark tests using nightly benchmark framework against the distribution tarball provided by requester. Since the tarball was created locally and had no manifest associated with it we could not accept the request and guided the user to run it locally. 
Add a feature in the workflow to be able to run the benchmark workflow using either a distribution manifest url or the actual artifact url.

**Comment by Divyaasm** [comment]
@rishabh6788 please add more information on the current status of the issue.
