### ISSUE TITLE
[release]: OpenSearch Migrations - v0.2.0 - Historical Fetch Migrations

### ISSUE THREAD

**Issue by sumobrian** [opensearch-project/opensearch-build#4085]
### Did you read the on-boarding document

I reviewed this document but not sure if the procedures apply in this the migrations repo is not a plugin.

### What is the name of your component?

OpenSearch Migrations

### What is the link to your GitHub repo?

https://github.com/opensearch-project/opensearch-migrations

### Targeted release date

10/04 - Fetch Migrations with Capture and Replay Updates

### Where should we publish this component?

9/13 - Beta Release for Capture and Replay
9/27 - Beta Release for Historical Fetch with Capture and Replay updates
10/27 - Complete Migration Life Cycle
11/27 - AWS Solutions Library Release

### What type of artifact(s) will be generated for this component?

At present, we release only tarballs and zip files for the migration repo. We would like these to be PGP signed, and for these artifacts to be referenced on this page: https://opensearch.org/downloads.html.

Ideally, there should be a mechanism that allows us to redirect users to the latest version of the tooling, as this tooling will not be tied to a specific OpenSearch release."

### Have you completed the required reviews including security reviews, UX reviews?

Security review has been completed for first release. Second security review to be completed by 10/27. 

Given that this tooling is command line driven no UX review is needed.

### Have you on-boarded automated security scanning for the GitHub repo associated with this component?

Yes.

### Additional context

This issue is a followup to https://github.com/opensearch-project/opensearch-build/issues/4000.

**Comment by gaiksaya** [comment]
Hi @sumobrian,

Couple of questions:
1. I saw the documented process for previous release (0.1.0) and we only signed and released tarball. I believe that's what we want to do?
2. Will we be always releasing only tarballs or is there a possibility of another artifact in future?

**Comment by sumobrian** [comment]
For

**Comment by sumobrian** [comment]
The process will be the same for the next several releases. Meaning, we will continue to release tarballs. Eventually we will include other artifacts such as docker images and possibly release some of the components as jars but that's tbd.

**Comment by prudhvigodithi** [comment]
Hey @sumobrian I assume you also want to onboard to one click process and release once the repo has a new tag, something like https://github.com/opensearch-project/opensearch-migrations/archive/refs/tags/0.2.0.tar.gz?

**Comment by Divyaasm** [comment]
@sumobrian, the 1-click process is onboarded now. Pls feel free to open a new issue if required.
