### ISSUE TITLE
[Distribution Build Failure] Alerting build failing due to missing org.opensearch:common-utils:1.1.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#410]
**Describe the bug**
Alerting failed to build because `org.opensearch:common-utils:1.1.0.0-SNAPSHOT` was missing, it looks like common-utils was not built with the snapshot postfix.

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':alerting-core:compileKotlin'.
> Could not resolve all files for configuration ':alerting-core:compileClasspath'
....
Searched in the following locations:
  - file:/Users/petern/.m2/repository/org/opensearch/common-utils/1.1.0.0-SNAPSHOT/maven-metadata.xml
  - file:/Users/petern/.m2/repository/org/opensearch/common-utils/1.1.0.0-SNAPSHOT/common-utils-1.1.0.0-SNAPSHOT.pom
  - https://repo.maven.apache.org/maven2/org/opensearch/common-utils/1.1.0.0-SNAPSHOT/maven-metadata.xml
  - https://repo.maven.apache.org/maven2/org/opensearch/common-utils/1.1.0.0-SNAPSHOT/common-utils-1.1.0.0-SNAPSHOT.pom
  - https://jcenter.bintray.com/org/opensearch/common-utils/1.1.0.0-SNAPSHOT/maven-metadata.xml
  - https://jcenter.bintray.com/org/opensearch/common-utils/1.1.0.0-SNAPSHOT/common-utils-1.1.0.0-SNAPSHOT.pom
Required by:
    project :alerting-core
...
2021-09-08 11:31:16 ERROR    Error building alerting, retry with: ./bundle-workflow/build.sh manifests/opensearch-1.1.0.yml --component alerting --snapshot
```
```
ls /Users/petern/.m2/repository/org/opensearch/common-utils/1.1.0.0 
common-utils-1.1.0.0-javadoc.jar
common-utils-1.1.0.0-sources.jar
common-utils-1.1.0.0.jar
common-utils-1.1.0.0.pom
```

**To Reproduce**
1. `./bundle-workflow/build.sh manifests/opensearch-1.1.0.yml --component alerting --snapshot`

**Expected behavior**
Build should succeed

**Comment by peternied** [comment]
Reproduces locally, inspecting the last passing build to see why this worked

**Comment by dblock** [comment]
@peternied Did you build common-utils first? Otherwise it *will* fail with the repro command above, which is expected.

**Comment by peternied** [comment]
Found it, PRs to support snapshots was lost when branch was moved to from main->1.1.  Creating pull requests...

* https://github.com/opensearch-project/common-utils/pull/58
* https://github.com/opensearch-project/common-utils/pull/57

**Comment by peternied** [comment]
I am going to back out the branch update to 1.1 and have the common-utils team switch back when its ready.

**Comment by peternied** [comment]
Snapshot build is passing, waiting on completed build cycle

**Comment by peternied** [comment]
This issue is confirmed as no longer blocking the build.
