### ISSUE TITLE
Add support for additional opensearch-benchmark paramters

### ISSUE THREAD

**Issue by rishabh6788** [opensearch-project/opensearch-build#4103]
Add support for following opensearch-benchmark parameters:
* `--test-procedure`: To be able to select the type of[ test procedure](https://opensearch.org/docs/latest/benchmark/commands/command-flags/#test-procedure) to run. 
*  `--include-tasks`: Defines a comma-separated list of test procedure tasks to run. See [here](https://opensearch.org/docs/latest/benchmark/commands/command-flags/#include-tasks)
* `--exclude-tasks`: Defines a comma-separated list of test procedure tasks not to run.

**Comment by Divyaasm** [comment]
Hi @rishabh6788, could add more information on the issue. Thanks

**Comment by rishabh6788** [comment]
The required features have been added.
