### ISSUE TITLE
[release]: Publish opensearch-ai-flow-framework SNAPSHOTs to Maven

### ISSUE THREAD

**Issue by owaiskazi19** [opensearch-project/opensearch-build#4106]
### Did you read the on-boarding document

Yes

### What is the name of your component?

opensearch-ai-flow-framework

### What is the link to your GitHub repo?

https://github.com/opensearch-project/opensearch-ai-flow-framework

### Targeted release date

Q1 2024

### Where should we publish this component?

Maven

### What type of artifact(s) will be generated for this component?

```
snapshots/
└── org
    └── opensearch
        └── plugin
            └── opensearch-ai-flow-framework
                ├── 3.0.0.0-SNAPSHOT
                │   ├── maven-metadata.xml
                │   ├── maven-metadata.xml.md5
                │   ├── maven-metadata.xml.sha1
                │   ├── maven-metadata.xml.sha256
                │   ├── maven-metadata.xml.sha512
                │   ├── opensearch-ai-flow-framework-3.0.0.0-20231005.170838-1.pom
                │   ├── opensearch-ai-flow-framework-3.0.0.0-20231005.170838-1.pom.md5
                │   ├── opensearch-ai-flow-framework-3.0.0.0-20231005.170838-1.pom.sha1
                │   ├── opensearch-ai-flow-framework-3.0.0.0-20231005.170838-1.pom.sha256
                │   ├── opensearch-ai-flow-framework-3.0.0.0-20231005.170838-1.pom.sha512
                │   ├── opensearch-ai-flow-framework-3.0.0.0-20231005.170838-1.zip
                │   ├── opensearch-ai-flow-framework-3.0.0.0-20231005.170838-1.zip.md5
                │   ├── opensearch-ai-flow-framework-3.0.0.0-20231005.170838-1.zip.sha1
                │   ├── opensearch-ai-flow-framework-3.0.0.0-20231005.170838-1.zip.sha256
                │   └── opensearch-ai-flow-framework-3.0.0.0-20231005.170838-1.zip.sha512
                ├── maven-metadata.xml
                ├── maven-metadata.xml.md5
                ├── maven-metadata.xml.sha1
                ├── maven-metadata.xml.sha256
                └── maven-metadata.xml.sha512


```

### Have you completed the required reviews including security reviews, UX reviews?

Yes

### Have you on-boarded automated security scanning for the GitHub repo associated with this component?

Yes

### Additional context

OpenSearch plugin that enables builders to innovate AI apps on OpenSearch

**Comment by zelinh** [comment]
Since it's targeted to Q1 next year, I believe we could onboard this to our 1 click release process. Onboarding details are [here](https://github.com/opensearch-project/opensearch-build/blob/main/ONBOARDING.md#onboarding-to-universal--1-click-release-process). 

Notes: Since it's we are planning to publish the snapshot to maven. We would also need to enable Maven access to this `opensearch-ai-flow-framework` repo for the 1 click release.

**Comment by owaiskazi19** [comment]
@zelinh this issue is not for onboarding to 1 click process. It's for adding credential of our repo to publish snapshots to maven.

**Comment by gaiksaya** [comment]
> @zelinh this issue is not for onboarding to 1 click process. It's for adding credential of our repo to publish snapshots to maven.

Right! I believe they can create new issue later for actual release. This is just for publishing the snapshots to https://aws.oss.sonatype.org/content/repositories/snapshots/

**Comment by Divyaasm** [comment]
Can now publish to maven snapshots.
Closing the issue as IAM role is now created for the above repo and GH secrets have been updated accordingly.
