### ISSUE TITLE
Publish OpenSearch min snapshots for Mac M1 machines

### ISSUE THREAD

**Issue by ryanbogan** [opensearch-project/opensearch-build#4131]
**Is your feature request related to a problem? Please describe.**
Currently, the only way to run plugins on a Mac M1 machine is to specify a path to a custom distribution url that contains a darwin-tar or darwin-arm64-tar gz file of an OpenSearch snapshot.

**Describe the solution you'd like**
Publish minimum OpenSearch snapshot distributions so that gradle commands (check, run, integTest, etc.) can be run without specifying a path every time.

**Additional context**
https://github.com/opensearch-project/k-NN/issues/580

**Comment by ryanbogan** [comment]
@gaiksaya The M1 machines default to arm64 for the basic commands.  Are those available?

**Comment by gaiksaya** [comment]
No! I believe we are only building x64 for macOS: https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/opensearch/publish-min-snapshots.jenkinsfile#L111-L142

Not sure if there a plan in near future to add it. We do have issue open to support macOS as a distribution #38 .
Adding @bbarani @prudhvigodithi

**Comment by prudhvigodithi** [comment]
Hey @ryanbogan please check this comment https://github.com/opensearch-project/opensearch-build/issues/2216#issuecomment-1464045347 

Mac os support `x86_64` and `arm64` as well, mac m1 works for both `x86_64` and `arm64` with help of Rosetta 2
`arm64` is the architecture used by newer Macs built on Apple Silicon, shipped in late 2020 and beyond, but `x64` should work as well, `pgrep oahd` should output the Rosetta process.

**Comment by peterzhuamazon** [comment]
Duplicate with https://github.com/opensearch-project/opensearch-build/issues/4670 so move it to there now.
Thanks.
