### ISSUE TITLE
Central workflow to execute pre-release promotion jobs.

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/opensearch-build#4136]
### Is your feature request related to a problem? Please describe

During a release as a pre-release activity we need to [Promote Repos](https://github.com/opensearch-project/opensearch-build/blob/main/RELEASE_PROCESS_OPENSEARCH.md#promote-repos) and [Promote Artifacts](https://github.com/opensearch-project/opensearch-build/blob/main/RELEASE_PROCESS_OPENSEARCH.md#promote-artifacts) and execute multiple jobs manually that needs the RC build numbers and manifests as input.

Example for [Release 2.11.0](https://github.com/opensearch-project/opensearch-build/issues/3998) following are the jobs executed manually.

#### Promote Repos OS and OSD
https://build.ci.opensearch.org/job/distribution-promote-repos/74/console
https://build.ci.opensearch.org/job/distribution-promote-repos/75/console
https://build.ci.opensearch.org/job/distribution-promote-repos/76/
https://build.ci.opensearch.org/job/distribution-promote-repos/77/

####  Windows OS and OSD
https://build.ci.opensearch.org/job/distribution-promote-artifacts/339/console
https://build.ci.opensearch.org/job/distribution-promote-artifacts/337/

####  Linux OS and OSD deb:
https://build.ci.opensearch.org/job/distribution-promote-artifacts/340/
https://build.ci.opensearch.org/job/distribution-promote-artifacts/341/
https://build.ci.opensearch.org/job/distribution-promote-artifacts/342
https://build.ci.opensearch.org/job/distribution-promote-artifacts/343/

####  Linux OS and OSD Rpm:
https://build.ci.opensearch.org/job/distribution-promote-artifacts/344/console
https://build.ci.opensearch.org/job/distribution-promote-artifacts/344/console
https://build.ci.opensearch.org/job/distribution-promote-artifacts/346/
https://build.ci.opensearch.org/job/distribution-promote-artifacts/346/console

####  Linux OS and OSD Tar 
https://build.ci.opensearch.org/job/distribution-promote-artifacts/349/
https://build.ci.opensearch.org/job/distribution-promote-artifacts/350/
https://build.ci.opensearch.org/job/distribution-promote-artifacts/352/
https://build.ci.opensearch.org/job/distribution-promote-artifacts/353/

### Describe the solution you'd like

Come up with central workflow that triggers all the [Promote Repos](https://github.com/opensearch-project/opensearch-build/blob/main/RELEASE_PROCESS_OPENSEARCH.md#promote-repos) and [Promote Artifacts](https://github.com/opensearch-project/opensearch-build/blob/main/RELEASE_PROCESS_OPENSEARCH.md#promote-artifacts) jobs. This central workflow should track all the job status and notify if one of the jobs fails as part of the promotion. The central workflow should synchronously wait until all the promote jobs are completed.

**Comment by hitenshKharva** [comment]
I can work on this issue.

**Comment by gaiksaya** [comment]
Adding one of the approach we discussed offline:

A release candidate is considered ready for release when all the exit criteria is met. Once we get a `GO` from everyone, a release-candidate.yml similar to below can be committed into `manifests/version` folder fixing the release candidate number.

```yml
---
opensearch: 1384
opensearch-dashboards: 1099
```

This file should be reviewed, approved and then merged. Once merged, the centralized workflow say `release.jenkinsFile` will take this an input, parse for RC number and subsequently pass on to all child workflows. Some workflows are dependent on each other or need to run in certain order, that should be taken care by the centralized workflow. Most of them can run in parallel.

I believe this process can eventually be linked to a tag making a one click release process.

Let me know what you think @dblock @bbarani

**Comment by prudhvigodithi** [comment]
Closing this issue as this enhancement is merged in PR https://github.com/opensearch-project/opensearch-build/pull/4280, will re-open if required to make any changes or found any bugs.
Thank you

**Comment by prudhvigodithi** [comment]
Created a jenkins pipeline https://build.ci.opensearch.org/job/distribution-promotion/, that can be used to trigger the pre-release promotion activities.
