### ISSUE TITLE
[Bug]: Add license header for files failing license header checker github action

### ISSUE THREAD

**Issue by hitenshKharva** [opensearch-project/opensearch-build#4140]
### Describe the bug

A lot of files are missing the license header. 
Issue: [3079](https://github.com/opensearch-project/opensearch-build/issues/3079) requires the files to be fixed before merging PR: [4118](https://github.com/opensearch-project/opensearch-build/pull/4118) to make sure it doesn't break for all upcoming PRs for the opensearch-build repo.

### To reproduce

Check for License Header Checker Github action [Job Run](https://github.com/opensearch-project/opensearch-build/actions/runs/6541601291/job/17763338762?pr=4118)

**Comment by peterzhuamazon** [comment]
Thanks @hitenshKharva for the great contribution.
