### ISSUE TITLE
[Bug]: Distribution build failure GH issues do not provide detail information

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/opensearch-build#4155]
### Describe the bug

The current distribution build failure GH issues created in component repositories provide only below information:

```
Received Error: Error building cross-cluster-replication, retry with: ./build.sh manifests/3.0.0/opensearch-3.0.0.yml --component cross-cluster-replication.
The distribution build for cross-cluster-replication has failed for version: 3.0.0.
Please see build log at https://build.ci.opensearch.org/job/distribution-build-opensearch/8676/consoleFull
``` 

With the growing logging and workflow pipeline loading the logs also times out multiple times. 
Its is not clear what failed exactly. We do have #4018 open to mark a stage unstable that should give more information however until that is executed we need to fix the GH issue creation 

### To reproduce

See https://github.com/opensearch-project/cross-cluster-replication/issues?q=is%3Aissue++%5BAUTOCUT%5D+Distribution+Build+Failed+for+cross-cluster-replication-3.0.0+

### Expected behavior

GItHub issues creation logic should be improved and more details need to be added such as:

- Steps to reproduce using right environment (docker file, manifest, platform, architecture)
- Provide blue ocean link and node level log. Example: https://build.ci.opensearch.org/blue/rest/organizations/jenkins/pipelines/distribution-build-opensearch/runs/8676/nodes/69/steps/340/log/?start=0
- Check if component is failing for all platforms/architecture and add comment accordingly.

### Additional context

See https://stackoverflow.com/questions/54287643/get-step-id-in-jenkins-pipeline-for-linking-to-blueocean-or-pipeline-steps-view to get some details on how to get the exact node info detail to display the log link.

**Comment by chawinphat** [comment]
Hi, I'm interested in working on this issue. If anyone else is interested, feel free to let me know!

**Comment by gaiksaya** [comment]
Hi @chawinphat 

Thank you for the interest. This issue needs a little deep dive or infrastructure set up to reproduce. The blue ocean view of any pipeline is visible using env variable `${env.RUN_DISPLAY_URL}` However, it would still be difficult what exactly went wrong. I would put this in backlog. Maybe implementing #4018 give more insights to the user to view log if not a node level.

**Comment by jordarlu** [comment]
Hi, @gaiksaya , since the https://github.com/opensearch-project/opensearch-build/issues/4018 has been merged, should we also close this issue ? thanks

**Comment by gaiksaya** [comment]
Closing this issue as the build messages have been modified in above PR. #4018
