### ISSUE TITLE
Redirect the url link in cf-url-rewriter.ts to point to the latest distribution build number.

### ISSUE THREAD

**Issue by Divyaasm** [opensearch-project/opensearch-build#4166]
### Is your feature request related to a problem? Please describe
We currently link the latest in the artifact-url to latest build number in index.json file. But the logic needs to be updated after we add distribution level index.json files which have distribution-latest build number.

### Describe the solution you'd like

- [x] https://github.com/opensearch-project/opensearch-build/issues/4165

Once the above issue is addressed, update cf-url-rewriter logic to retrieve the latest distribution build number.

### Additional context

**Comment by bbarani** [comment]
@Divyaasm whats the status of this issue? I see a PR tagged to this issue but don't see much traction.

**Comment by Divyaasm** [comment]
Related CR has already been merged @bbarani, Just need to add the changes in this PR. Will update this soon.

**Comment by Divyaasm** [comment]
All the related PR's are merged. Closing the issue
