### ISSUE TITLE
[Maintenance] Maintain the same images on public ECR as Docker Hub

### ISSUE THREAD

**Issue by jtnz** [opensearch-project/opensearch-build#4169]
### Is your feature request related to a problem?
It appears that the [public ECR repos](https://gallery.ecr.aws/opensearchproject/logstash-oss-with-opensearch-output-plugin) don't have newer images pushed to them (I checked `logstash-oss-with-opensearch-output-plugin` specifically), compared to [Docker Hub](https://hub.docker.com/r/opensearchproject/logstash-oss-with-opensearch-output-plugin/tags).

For example on the public ECR the most recent image tag `7.16.3` (which also has fewer images). Docker hub latest most recent tag is `8.9.0`.

**Comment by peterzhuamazon** [comment]
ECR synced.

Thanks.
