### ISSUE TITLE
Run end-to-end automated integration tests for bundle

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#42]
**Is your feature request related to a problem? Please describe.**

We currently don't have/run integration tests on the OpenSearch bundle, including rolling and restart upgrades that include plugins.   

**Describe the solution you'd like**

Extend the OpenSearch backwards compatibility infrastructure to install the bundle and perform checks such as, for example, whether security is enabled by default. Repeat with upgrades.

**Comment by dblock** [comment]
@saratvemulapalli bump on status for this?

**Comment by saratvemulapalli** [comment]
Good question.
We should be able to close this as most of the work is already done and the remaining pieces are still being tracked by: #90
