### ISSUE TITLE
[Incremental Build] Build incremental components through build workflow

### ISSUE THREAD

**Issue by zelinh** [opensearch-project/opensearch-build#4210]
This is a sub-issue from https://github.com/opensearch-project/opensearch-build/issues/3922

Once we have a list of rebuilding plugins obtained from [this issue](https://github.com/opensearch-project/opensearch-build/issues/4201), we should be able to run the build workflow with these components. 

Acceptance Critieria:
- The build workflow will run through only those designated components.
- The build manifest will be updated with rebuilding artifacts and keep unchanged artifacts from previous build.
- The build itself should run with no errors.

Implementation plan.
We would run our current build_workflow with these components until recording/generating the build_manifest.

Since we don’t want to erase other previously build components from the build manifest, we would take input of the build manifest with relative path `builds/opensearch/manifest.yml`. After reading through the previous manifest, we would be updating the manifest with whatever components that we just incremental build. 

We have `BuildManifestBuilder` class in `build_recorder.py`. Normally it starts from scratch; if we only build few components, it would only record those built plugins. 

However, we can add a functionality to the builder itself. When `incremental` argument is enable, it would firstly read through `builds/opensearch/manifest.yml` and append/update the currently building components to the manifest.

**Comment by gaiksaya** [comment]
Hi @zelinh ,

Looks like associated PR is merged. Can we close this issue?
Thanks!

**Comment by zelinh** [comment]
This issue is resolved.
