### ISSUE TITLE
[Bug] Gradle Check fails after ~5 minutes but the Jenkins job itself continues to run and sometimes even succeeds

### ISSUE THREAD

**Issue by jed326** [opensearch-project/opensearch-build#4212]
### Describe the bug

Gradle Check fails after ~5 minutes but the Jenkins job itself continues to run and sometimes even succeeds.

### To reproduce

Not sure how to reproduce. See:
- https://github.com/opensearch-project/OpenSearch/pull/11181#issuecomment-1809292704
- https://github.com/opensearch-project/OpenSearch/pull/11181#issuecomment-1809273008

In the same PR we do see this running correctly:
- https://github.com/opensearch-project/OpenSearch/pull/11181#issuecomment-1809163353

### Expected behavior

Gradle Check does not fail while the underlying Jenkins job is still running.

**Comment by peterzhuamazon** [comment]
https://github.com/opensearch-project/OpenSearch/actions/runs/6856944906/job/18645104002?pr=11181#step:6:52

**Comment by peterzhuamazon** [comment]
```
parse error: Invalid numeric literal at line 1, column 10
```

This is due to jq parsing and jq just have a new release 1.7 here: https://github.com/jqlang/jq/releases/tag/jq-1.7

This is the 1st release since 1.6 from 2018. It might cause some issues if ubuntu-latest from github actions is onboarding it.

**Comment by peterzhuamazon** [comment]
Seems still 1.6:
https://github.com/actions/runner-images/blob/a8e7f69ab1e672a07c67b66bbcb1255618419e03/images/linux/Ubuntu2204-Readme.md

**Comment by jed326** [comment]
Got a successful run on my PR: https://github.com/opensearch-project/OpenSearch/pull/11181#issuecomment-1809321719

Seems like there's something flaky with one of the underlying components here

**Comment by peterzhuamazon** [comment]
Closing for now, thanks for reporting, and feel free to open if seeing again.

Thanks!
