### ISSUE TITLE
[Bug]: manifest ci check runs for any version runs on both jdk-11 and jdk-17

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/opensearch-build#4227]
### Describe the bug

The recent improvement in manifest ci check https://github.com/opensearch-project/opensearch-build/pull/4101 is not handling the jdk version correctly. On checking the previous workflow https://github.com/opensearch-project/opensearch-build/actions/runs/6267489648/workflow looks like the below is the right approach:

- Use jdk-11 on 1.x manifests
- Use jdk-17 for 2.x manifests
- Use jdk-21 (most recent update) for 3.x manifests

### To reproduce

See https://github.com/opensearch-project/opensearch-build/pull/4226 failing for 1.x series. 

### Expected behavior

CI check should only run on specific jdk versions and not a matrix of all.

**Comment by gaiksaya** [comment]
cc: @hitenshKharva if you wanna have a look.
Also tagging @zelinh 

Thanks!

**Comment by zelinh** [comment]
We could also get the JDK version from our manifest template. For example for 1.x manifest, we can get from here. https://github.com/opensearch-project/opensearch-build/blob/d1796ed5c1995420a07fd638253247a7f99d95b9/manifests/templates/opensearch/1.x/manifest.yml#L9

**Comment by gaiksaya** [comment]
> We could also get the JDK version from our manifest template. For example for 1.x manifest, we can get from here.
> 
> https://github.com/opensearch-project/opensearch-build/blob/d1796ed5c1995420a07fd638253247a7f99d95b9/manifests/templates/opensearch/1.x/manifest.yml#L9

I dont think that is feasible. Might be too dynamic if too many manifests are changed. Not required for CI check level.

**Comment by peterzhuamazon** [comment]
Will take a look on this.

**Comment by peterzhuamazon** [comment]
Have some tests and seems like `matrix.manifest` does not show up in the if statement as it is dynamically retrieved now.
Need more research on this but the idea is clear.

**Comment by peterzhuamazon** [comment]
I overlooked the implementation and now send an easier PR.
