### ISSUE TITLE
[BUG] Installation on Almalinux

### ISSUE THREAD

**Issue by Caos989989** [opensearch-project/opensearch-build#4236]
**Describe the bug**

It's not possible to run Opensearch on Almalinux 8.8.0

CentOS is end of life and Almalinux is the successor. So Opensearch should run on Almalinux.

**To Reproduce**

I installed Opensearch like the installation Docs describe (YUM package).

I can't start Opensearch on Almalinux.

I have a lot of errors like this:
unable to load JNA native support library, native methods will be disabled.
cannot check if running as root because JNA is not available
cannot install system call filter because JNA is not available

**Expected behavior**

Opensearch should run on Almalinux

**Plugins**

**Screenshots**

**Host/Environment (please complete the following information):**
 - OS: Almalinux
 - Version 8.8.0

**Additional context**

**Comment by peterzhuamazon** [comment]
The Yum packages are built on rockylinux8 for the final assemble, but Rockylinux is still 1 to 1 with RH.
I think Alma is going another route now and I am not sure if it still resembles that.
@Caos989989 if you could provide some error logs that would be helpful. Thanks.

**Comment by Caos989989** [comment]
Hi,

my serveradmin was able to install Opensearch. He was also struggling with this but after a few tries it's running.

But I can't tell exactly what the problem was. 

I found out that Elasticsearch also has problems. I think we found the solution here: https://stackoverflow.com/questions/47824643/unable-to-load-jna-native-support-library-elasticsearch-6-x

**Comment by jordarlu** [comment]
Thanks for letting the community know that, @Caos989989 ,, interesting to learn that too..
I will close this issue for now, but please re-open it if needed..  thanks.
