### ISSUE TITLE
Output link to Cypress logs in integ-test-opensearch-dashboards

### ISSUE THREAD

**Issue by Swiddis** [opensearch-project/opensearch-build#4238]
### Is your feature request related to a problem? Please describe

When tests fail in Jenkins, there's no easy way to locate the logs associated with that run. My understanding is that there's some workflow involving copying various IDs to manually assemble that URL, but I'm not sure where it's documented.

### Describe the solution you'd like

It would save a lot of debugging time if there were links to the Cypress logs (and video recordings!) within the Jenkins output itself, a simple message like `2023-12-25 12:00:00 INFO     Saved Cypress logs to: https://.../output.log`.

### Describe alternatives you've considered

Linking to documentation on how to generate the link could also help, without as much string building complexity, but seems roundabout compared to just formatting a string to the correct place directly.

**Comment by jordarlu** [comment]
Hi, @Swiddis , we currently have AUTOCUT issue sent to plugin repos with the test related links, please refer to this https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5506 where you would find the * Test-report manifest:* with all the links to the detail.. hopefully that would resolve this issue? thanks, 
cc : @kavilla

**Comment by jordarlu** [comment]
Thanks for the feedback, @Swiddis , we have the AUTOCUT mentioned at [here](https://github.com/opensearch-project/opensearch-build/blob/main/RELEASE_PROCESS_OPENSEARCH.md#autocut-issues) in [opensearch-build](https://github.com/opensearch-project/opensearch-build/tree/main) repo; and the intention was to provide more visibility and easier access to the logs when people needs it. ( by using the links in those AUTOCUT issues to access to the manifest or the logs on Jenknis ) ; good to know that worked for you.

**Comment by jordarlu** [comment]
Issue should have been addressed with instructions in the comments. thanks!
