### ISSUE TITLE
Add Cloudfront cache invalidation after each promotion

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#4262]
Add Cloudfront cache invalidation after each promotion.

We are currently manually invalidate the caches, need a mechanism to do so after running promote-repos.

Thanks.

### Acceptance Criteria:
* Save cloudfront id in the secret manager
* Use the id to make a call with awscli to invalidate based on major version:
```
/releases/bundle/opensearch-dashboards/1.x/*
/releases/bundle/opensearch/1.x/*

or

/releases/bundle/opensearch-dashboards/2.x/*
/releases/bundle/opensearch/2.x/*

......
```
* Execute this after the https://build.ci.opensearch.org/job/distribution-promote-repos/ workflow is done.

**Comment by dblock** [comment]
What caches are we invalidating? It feels like most things should have a permanent URI that doesn't change. The only one would be for the index file in distributions that handles the redirect to latest?

**Comment by gaiksaya** [comment]
The redirect to `latest` is a different set up (all things CI). This is about `artifacts.opensearch.org`. Whenever a new artifact is uploaded to the bucket looks we are not invalidating the cache today which results in delay in availability of the artifacts.

**Comment by jordarlu** [comment]
Maybe we can add `cfInvalidate(distribution:'someDistributionId', paths:['/*'], waitForCompletion: true)` after this line https://github.com/opensearch-project/opensearch-build-libraries/blob/2.0.2/vars/promoteRepos.groovy#L213

We will need to do AWS CLI to retrieve the CloudFront Distribution Id first, maybe something like this ?
`aws cloudfront list-distributions | jq -r '.DistributionList.Items[].Id'`
or
`aws cloudfront list-distributions | jq -r '.DistributionList.Items[]|select(.Aliases.Items[] == "ci.opensearch.org")|.Id'`

Do we expect to have more than one CloudFront distribution created on this CI account?

**Comment by peterzhuamazon** [comment]
> Maybe we can add `cfInvalidate(distribution:'someDistributionId', paths:['/*'], waitForCompletion: true)` after this line https://github.com/opensearch-project/opensearch-build-libraries/blob/2.0.2/vars/promoteRepos.groovy#L213
> 
> We will need to do AWS CLI to retrieve the CloudFront Distribution Id first, maybe something like this ? `aws cloudfront list-distributions | jq -r '.DistributionList.Items[].Id'` or `aws cloudfront list-distributions | jq -r '.DistributionList.Items[]|select(.Aliases.Items[] == "ci.opensearch.org")|.Id'`
> 
> Do we expect to have more than one CloudFront distribution created on this CI account?

In our case we can just save the id in secret manager as it is fixed.

**Comment by prudhvigodithi** [comment]
@gaiksaya and @peterzhuamazon can we close this?
@getsaurabh02

**Comment by peterzhuamazon** [comment]
We should, it has already been resolve in this PR:
* https://github.com/opensearch-project/opensearch-build/pull/4753

Thanks.
