### ISSUE TITLE
Add documentation for Github Wiki Workflow

### ISSUE THREAD

**Issue by chawinphat** [opensearch-project/opensearch-build#4267]
### Is your feature request related to a problem? Please describe

Recently, the Opensearch-build repository's wiki has been improved to be updatable through pull requests by utilizing a new GitHub Action workflow to sync the [docs](https://github.com/opensearch-project/opensearch-build/tree/main/docs) folder to the GitHub wiki. 

There is currently no documentation on how the workflow is utilized and how the docs folder works in conjunction with the workflow to mirror its contents onto the wiki.

### Describe the solution you'd like

Introduce a README.md file within the docs folder or somewhere else. One issue with adding the README file within /docs is that it might be displayed on the wiki as well. Potentially creating a sub directory within docs could work.

**Comment by jordarlu** [comment]
Thanks for creating issue to track on this, @chawinphat ,, would you be able to also take a lead on contributing a PR for it?  thanks !!

**Comment by chawinphat** [comment]
Sure, I'll look into contributing a PR for this.

**Comment by jordarlu** [comment]
I am going to close this issue as the PR has been merged, thank you, @chawinphat !!
