### ISSUE TITLE
Working backwards from the 1.1.0 release

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#427]
The 1.1.0 release process is new, and we should make sure that we've lined up all the work that needs to be completed beforehand to be sure we know timing and requirements between each stage.

**Comment by dblock** [comment]
I propose we rename this to auto generate all release issues and such automatically.

I started making changes to README in https://github.com/opensearch-project/opensearch-build/pull/461 with the idea that the release is automated.
