### ISSUE TITLE
[Incremental build] Onboard incremental build from Python workflow to jenkins CI.

### ISSUE THREAD

**Issue by zelinh** [opensearch-project/opensearch-build#4292]
This is a sub-issue from https://github.com/opensearch-project/opensearch-build/issues/3922

Once we have completed the feature implementation for incremental build on Python workflow, we can onboard it to Jenkins workflow.

The python workflow assume we have `builds` folder inside the repository directory for the architecture type that we are incrementally building. 

For this issue, to onboard to Jenkins, in jenkins workflow, we have to fulfill these requirements:
- Download the `builds` folder of previous build from CI S3 bucket.
- Set up the Maven local for OpenSearch plugins.
- Enable the parameter of `--incremental` in the `distribution-build` Jenkins jobs.

Acceptance Critieria:
- The Jenkins build job will run with `incremental` argument.
- The Jenkins build job will keep the rest of its functionalities except for building these specific incremental components.
- The Jenkins build job will set `incremental` parameter as true by default so it could significantly reduce build time.

**Comment by prudhvigodithi** [comment]
[Untraige]
Thanks @zelinh the `Acceptance Critieria` looks clear, please post a comment on the status of this issue.
Adding @gaiksaya

**Comment by zelinh** [comment]
The onboarding process is completed and we have run several Jenkins jobs to make sure it's working properly. We will enable the incremental build as default later.
