### ISSUE TITLE
[Bug]: Publish Wiki workflow failing 

### ISSUE THREAD

**Issue by chawinphat** [opensearch-project/opensearch-build#4308]
### Describe the bug

Running the publish wiki workflow after updating a file inside docs will result in this [error:](https://github.com/opensearch-project/opensearch-build/actions/runs/6961582353)

The bug is caused due to incorrectly setting the path to the ```docs``` folder by the [publish-wiki workflow](https://github.com/opensearch-project/opensearch-build/blob/main/.github/workflows/publish-wiki.yml). The workflow [documentation](https://github.com/Andrew-Chen-Wang/github-wiki-action) outlines a different way to do it by setting the ```path``` variable instead of ```paths```.

### To reproduce

Updating the markdown files inside the 'docs' folder on a fork and pushing the code will cause the workflow to fail.

### Expected behavior

The workflow should not fail, and changes to the 'docs' folder will be updated on the wiki.

### Screenshots

<img width="560" alt="image" src="https://github.com/opensearch-project/opensearch-build/assets/91317217/5b3121bd-3732-4256-9144-38ae8c7b510c">

**Comment by gaiksaya** [comment]
Closing this issue as wiki path is updated via #4310 and able to see workflow passing successfully https://github.com/opensearch-project/opensearch-build/actions/workflows/publish-wiki.yml
Thanks for the contribution @chawinphat
