### ISSUE TITLE
[Bug]: publish-opensearch-min-snapshots build fail on Windows for build version 1.3.15

### ISSUE THREAD

**Issue by jordarlu** [opensearch-project/opensearch-build#4319]
### Describe the bug

It was found that the CI build failure on Windows for build version 1.3.15 

```
scoop reset `scoop list jdk | cut -d ' ' -f1 | grep 11 | head -1`
— Shell Script
7s
script returned exit code 127
```

https://build.ci.opensearch.org/blue/organizations/jenkins/publish-opensearch-min-snapshots/detail/publish-opensearch-min-snapshots/514/pipeline/63

### To reproduce

Re-run the [min-snapshots build job](https://build.ci.opensearch.org/job/publish-opensearch-min-snapshots/) with using INPUT_MANIFEST as `1.3.15/opensearch-1.3.15.yml`

### Expected behavior

Should be able to switch to required Java version based on the value provided in INPUT_MANIFEST

### Screenshots

<img width="502" alt="Screenshot 2024-01-03 at 3 56 16 PM" src="https://github.com/opensearch-project/opensearch-build/assets/111453669/dc3c518e-b3d0-414c-8188-f49390ac92eb">

**Comment by rishabh6788** [comment]
@peterzhuamazon Is this still happening?

**Comment by jordarlu** [comment]
Looks like this is still happening as in https://build.ci.opensearch.org/blue/organizations/jenkins/publish-opensearch-min-snapshots/detail/publish-opensearch-min-snapshots/691/pipeline/63 
Would you recommand we try with more aggresive number in `maxTotalUses`? @peterzhuamazon and @rishabh6788 , thanks

**Comment by bbarani** [comment]
@jordarlu @peterzhuamazon Can we close this issue?

**Comment by jordarlu** [comment]
I haven't observed any instance in the most recent 30 runs, let me close this issue for now. thanks!
