### ISSUE TITLE
[BUG] Opensearch cluster won't start and gives permission denied error

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/opensearch-build#432]
**Describe the bug**
```
/bin/sh: 1: ./opensearch-tar-install.sh: Permission denied
```
This is an executable file on [github](https://github.com/opensearch-project/opensearch-build/blob/main/release/tar/linux/opensearch-tar-install.sh) that is bundled (zipped) with all plugins and core. Somehow the file permissions changed making it in-executable in the bundle and giving permission error when user tries to start opensearch 

This file should be executable so that the user can start opensearch.
**To Reproduce**
1. Clone this repo and see that `opensearch-tar-install.sh` is executable
2. Now download the recent bundle (created using new build system)
3. Untar the bundle and see the permission of `opensearch-tar-install.sh` in the un-tar-ed directory

**Expected behavior**
User should be able to start opensearch by running `./opensearch-tar-install.sh`

**Comment by peternied** [comment]
Do we just need to update the script with `git update-index --chmod=+x opensearch-tar-install.sh`?  See more details on [stackoverflow](https://stackoverflow.com/questions/40978921/how-to-add-chmod-permissions-to-file-in-git)

[Workaround] users can use `chmod` to resolve as well?

**Comment by gaiksaya** [comment]
The permission is correct on github(from where it is being [copied](https://github.com/opensearch-project/opensearch-build/blob/main/release/tar/linux/opensearch-tar-install.sh)). The block of code where it is copying into the bundle: https://github.com/opensearch-project/opensearch-build/blob/main/bundle-workflow/src/assemble.py#L35-L66
Need to check if `shutil.copyfile` is changing the [original permission](https://github.com/opensearch-project/opensearch-build/blob/main/release/tar/linux/opensearch-tar-install.sh) or something else.

**Comment by peternied** [comment]
I cannot reproduce, I spun up a fresh EC2 instance and did the following
```
sh-4.2$ yum install git -y
...
sh-4.2$ git clone https://github.com/opensearch-project/opensearch-build.git
Cloning into 'opensearch-build'...
remote: Enumerating objects: 1806, done.
remote: Counting objects: 100% (1254/1254), done.
remote: Compressing objects: 100% (600/600), done.
remote: Total 1806 (delta 808), reused 888 (delta 627), pack-reused 552
Receiving objects: 100% (1806/1806), 443.35 KiB | 22.17 MiB/s, done.
Resolving deltas: 100% (903/903), done.
sh-4.2$ cd opensearch-build/tools/release/tar/linux
sh-4.2$ ls -al
total 20
drwxr-xr-x 2 ssm-user ssm-user  112 Sep 10 16:30 .
drwxr-xr-x 3 ssm-user ssm-user   19 Sep 10 16:30 ..
-rwxr-xr-x 1 ssm-user ssm-user 5131 Sep 10 16:30 opensearch-dashboards-tar-build.sh
-rwxr-xr-x 1 ssm-user ssm-user 5713 Sep 10 16:30 opensearch-tar-build.sh
-rwxr-xr-x 1 ssm-user ssm-user 3092 Sep 10 16:30 opensearch-tar-install.sh
```

**Comment by gaiksaya** [comment]
My bad should have documented steps to reproduce in detail. Edited them. Recording offline conversation here:
Issue is in the newly created bundle not in the github file. The `opensearch-tar-install.sh` file is not executable in the bundle (tarball)

**Comment by peternied** [comment]
Got in touch offline - the issue is that the `opensearch-tar-build.sh` is placed inside of the build tar file, and then should be executable, it looks like its losing permissions around `shutil.copy(...)`
