### ISSUE TITLE
[On-boarding]: dashboards-assistant plugin

### ISSUE THREAD

**Issue by joshuali925** [opensearch-project/opensearch-build#4322]
### What is the name of your plugin?

dashboards-assistant

### What is the link to your GitHub repo?

https://github.com/opensearch-project/dashboards-assistant/

### Targeted release version

2.12.0

### What type of the plugin are we on-boarding?

OpenSearch-dashboards plugin

### Did you read the on-boarding document

yes

### Does this plugin has all the necessary automated tests?

no IT yet. BWC not required

### Have you completed the required reviews including Security reviews, UX reviews?

yes

### Have you on-boarded automated security scanning for the GitHub repo associated with this plugin?

yes

**Comment by gaiksaya** [comment]
Hi @joshuali925 ,

Were you able to build the distribution using this new plugin? Steps are mentioned in the [on-boarding document](https://github.com/opensearch-project/opensearch-build/blob/main/ONBOARDING.md#onboard-to-build-workflow).
Pending tasks before closing this issue:

1. On-board to 2.12.0 manifest
2. On-board to test workflow by adding integration tests

Thanks!

**Comment by gaiksaya** [comment]
Hi,

In order to release this plugin as a part of the distribution, please make sure to onboard to distribution test workflow. See details here: https://github.com/opensearch-project/opensearch-build/wiki/Testing-the-Distribution
Please note that this is a requirement and can be a blocker is the criteria is not met.

Thanks!

**Comment by bbarani** [comment]
@joshuali925 This plugin will not be included in to distribution build if it doesn't contain the test workflows.

**Comment by joshuali925** [comment]
thanks for the notice. I assume test workflow for dashboards plugins means cypress integration tests in the functional test repo?

The onboarding doc section for testing seems only covered opensearch but not dashboards. please correct me if i'm wrong, thanks

https://github.com/opensearch-project/opensearch-build/blob/31cc1efe54f4fe539d552ffcfd727ff1cdd9ab24/ONBOARDING.md#L40

I believe for dashboards we moved to [functional-test](https://github.com/opensearch-project/opensearch-dashboards-functional-test) repo, the integration tests shouldn't be in the plugin directory?

https://github.com/opensearch-project/opensearch-build/blob/31cc1efe54f4fe539d552ffcfd727ff1cdd9ab24/ONBOARDING.md#L46

Are there backwards compatibility tests for dashboards?

---

@ruanyl @SuZhou-Joe Does your team have bandwidth to add integration tests for dashboards-assistant to functional test repo?

**Comment by gaiksaya** [comment]
Hi @joshuali925 ,

Right! For dashboard plugins functional-test is the right place. We will add more details to the boarding document. The test workflow in this repository will run tests from functional test repo for all dashboards plugins under the hood.

**Comment by ruanyl** [comment]
@joshuali925 We will working on adding and setting up functional tests in https://github.com/opensearch-project/opensearch-dashboards-functional-test

**Comment by raintygao** [comment]
The PR to setup assistant in FT repo has been merged. I have created a PR to on board assistant to 2.12.0 manifest and test workflow. Please take a look. https://github.com/opensearch-project/opensearch-build/pull/4363

**Comment by prudhvigodithi** [comment]
Thanks, I have merged the PR https://github.com/opensearch-project/opensearch-build/pull/4363 and update the release issue as well https://github.com/opensearch-project/opensearch-build/issues/4115.

**Comment by peterzhuamazon** [comment]
Already onboarded, thanks.
