### ISSUE TITLE
Add maven information to Bundle Manifest

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/opensearch-build#433]
**Is your feature request related to a problem? Please describe.**
Follow up of https://github.com/opensearch-project/opensearch-build/pull/423#discussion_r705542585

Test system should only depend on one source of truth. For integration tests (very like bwc), it needs to download maven dependencies to kick off the test suite. To understand what dependencies and where to download from is coming from build_manifest.yml. 
**Describe the solution you'd like**
Add all maven information to bundle manifest so that test systems only depend on one single manifest and avoid feeding information from different places.

**Comment by peterzhuamazon** [comment]
@peternied will start new issues to track this related problem. Close this one.
