### ISSUE TITLE
[release]: Publish opensearch-cluster-cdk to NPM

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/opensearch-build#4330]
### Did you read the on-boarding document

Yes

### What is the name of your component?

opensearch-cluster-cdk

### What is the link to your GitHub repo?

https://github.com/opensearch-project/opensearch-cluster-cdk

### Targeted release date

Jan 25th, 2024

### Where should we publish this component?

npmjs.org

### What type of artifact(s) will be generated for this component?

Can be published directly using repo

### Have you completed the required reviews including security reviews, UX reviews?

~In process. Will be updating this issue once we the review is complete.~ Done

### Have you on-boarded automated security scanning for the GitHub repo associated with this component?

Yes

### Additional context

We want to publish `opensearch-cluster-cdk` to npm so that the cdk stacks can be extended by other projects programmatically.

**Comment by prudhvigodithi** [comment]
[Triage]
Assigning to @gaiksaya,

**Comment by gaiksaya** [comment]
Proceeding with the on-boarding. cc: @rishabh6788
