### ISSUE TITLE
Onboard Front end plugins onto publish to maven workflow

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/opensearch-build#4337]
### Is your feature request related to a problem? Please describe

For backend plugins, with every PR merge, an image is published - example: https://github.com/opensearch-project/observability/actions/runs/7268660153/job/19804910058, to https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch. Is it possible for front end OSD and plugins to use the same or similar workflow to publish fresh artifacts?

### Describe the solution you'd like

Similar to maven publish workflow for front end OSD and plugins

**Comment by gaiksaya** [comment]
Hi @derek-ho ,

What kind of artifacts are you looking for? 
Backend plugins publish to maven since it is java based code. Not sure if there is something similar for node artifacts. Artifacts are build daily and publish to ci.opensearch.org which is a cloudfront based on S3 as origin. 
If there is any way to publish the snapshots somewhere, please let us know. @AMoo-Miki is quite knowledgeable in this area so tagging him ;) 

Thanks!

**Comment by bbarani** [comment]
As @gaiksaya mentioned, we cannot publish node artifacts to Maven. There was a discussion to publish front end plugins to NPM and we were thinking of publishing the artifact with a `-SNAPSHOT` version along with incremented number each time we publish it to NPM. (Ex: x.x.x-SNAPSHOT.1, x.x.x-SNAPSHOT.2 etc..).  We would need additional feedback before we can proceed with an approach.

**Comment by seraphjiang** [comment]
OSD has its own package management system on top of NPM. it is a software not package library. no need to publish OSD to  npm.

Regarding plugin,  it is also not architecture in a way could be consume as a typical npm package, therefore no need to publish npm

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/packages/README.md

Artifacts are different story, it is good to support rpm, docker, brew, deb outside of raw art.gz/zip file which will simplify the admin effort for install and deployment

**Comment by jordarlu** [comment]
@derek-ho , I hope the above comments have been helpful in addressing your query. I am going to close this ticket for now ,but please feel free to re-open it if necessary. Thank you.
