### ISSUE TITLE
[Enhancement] Adding support for `--single-version loose` as part of build_workflow

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#4345]
Hi,
Adding support for `--single-version loose` as part of build_workflow.

This is just a small potential improvement, as @AMoo-Miki has added a support for relaxing dependency check for OSD plugins.
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5675

We can add a new param such as `--osd-loose-deps-check` or similar if needed.
Thanks.

**Comment by prudhvigodithi** [comment]
[Triage]
There is some discussion happening on this PR https://github.com/opensearch-project/opensearch-build/pull/4343.

**Comment by peterzhuamazon** [comment]
We might not need this anymore. See #4343.

**Comment by derek-ho** [comment]
@peterzhuamazon can you help out here for path forward? We recently see this issue come up again after OSD core listed cypress 9.X as a dependency:

```
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "@elastic/eslint-import-resolver-kibana > eslint-import-resolver-webpack@0.13.8" has unmet peer dependency "eslint-plugin-import@>=1.4.0".
warning " > @testing-library/react-hooks@7.0.2" has unmet peer dependency "react@>=16.9.0".
warning "@testing-library/react-hooks > react-error-boundary@3.1.4" has unmet peer dependency "react@>=16.13.1".
warning "cypress-mochawesome-reporter > mochawesome@7.1.3" has unmet peer dependency "mocha@>=7".
warning " > eslint-plugin-cypress@2.15.1" has unmet peer dependency "eslint@>= 3.2.1".
[4/4] Building fresh packages...

ERROR [single_version_dependencies] Multiple version ranges for the same dependency
      were found declared across different package.json files. Please consolidate
      those to match across all package.json files. Different versions for the
      same dependency is not supported.

      If you have questions about this please reach out to the operations team.

      The conflicting dependencies are:

        cypress
          9.5.4 => opensearch-dashboards
          ^13.6.0 => opensearch-security-dashboards
```

Adding `--single-version=loose` fixes it on the local CI, but autocuts are still open since the build process doesn't incorporate this parameter. Path forward is either for OSD core to ignore dev dependencies, or to add this flag to the build process to prevent autocuts. Thanks!

**Comment by derek-ho** [comment]
Autocut issue: https://github.com/opensearch-project/security-dashboards-plugin/issues/1786
PR that introduced cypress to OSD core: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5725

**Comment by peterzhuamazon** [comment]
Seems running fine in 2.13 version.
Close for now.

Thanks.
