### ISSUE TITLE
[Bug]: 2.12.0 build.sh missing

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/opensearch-build#4350]
### Describe the bug

I am seeing the following error log from the autocut:

C:\Users\Administrator\jenkins\workspace\distribution-build-opensearch-dashboards\scripts\default\opensearch-dashboards\build.sh: line 13: ../../../lib/shell/file_management.sh: No such file or directory

Found a similar line for tar builds as well. I am suspecting something went wrong with the build process and the default script build.sh is not present

### To reproduce

Logs: https://build.ci.opensearch.org/blue/rest/organizations/jenkins/pipelines/distribution-build-opensearch-dashboards/runs/7113/nodes/76/log/?start=0

**Comment by derek-ho** [comment]
Similar issue for main/3.0.0:

2024-01-17 12:39:19 INFO     Executing "bash /var/jenkins/workspace/distribution-build-opensearch-dashboards@2/scripts/default/opensearch-dashboards/build.sh -v 3.0.0 -p linux -a x64 -s false -o builds" in /tmp/tmpqpkioqxq/securityDashboards
+ . ../../../lib/shell/file_management.sh
/var/jenkins/workspace/distribution-build-opensearch-dashboards@2/scripts/default/opensearch-dashboards/build.sh: line 13: ../../../lib/shell/file_management.sh: No such file or directory

https://build.ci.opensearch.org/blue/rest/organizations/jenkins/pipelines/distribution-build-opensearch-dashboards/runs/7115/nodes/70/log/?start=0

**Comment by prudhvigodithi** [comment]
Thanks @derek-ho, this is coming from the PR https://github.com/opensearch-project/opensearch-build/pull/4343. @peterzhuamazon can you please take a look.
Thanks

**Comment by peterzhuamazon** [comment]
Seems like the cleanup is still not fully in effect:
```

$ husky install
husky - Git hooks installed

ERROR [single_version_dependencies] Multiple version ranges for the same dependency
      were found declared across different package.json files. Please consolidate
      those to match across all package.json files. Different versions for the
      same dependency is not supported.

      If you have questions about this please reach out to the operations team.

      The conflicting dependencies are:

        plotly.js-dist
          ^1.57.1 => gantt-chart-dashboards
          ^2.2.0 => observability-dashboards
        react-plotly.js
          ^2.4.0 => gantt-chart-dashboards
          ^2.5.1 => observability-dashboards
error Command failed with exit code 1.
```

But obs already get removed and gantt still having issues:
```

Removing ../OpenSearch-Dashboards/plugins/observabilityDashboards
+ rm -rf -- ../OpenSearch-Dashboards/plugins/observabilityDashboards

```

Will need to take a deeper look on this.

**Comment by peterzhuamazon** [comment]
Then right after gantt, dashboards-assistant also shows issues related to gantt and obs:
```

$ husky install
husky - Git hooks installed

 info [gantt-chart-dashboards] running yarn

[1/4] Resolving packages...
success Already up-to-date.

 info [observability-dashboards] running yarn

[1/4] Resolving packages...
success Already up-to-date.
$ husky install
husky - Git hooks installed

ERROR [single_version_dependencies] Multiple version ranges for the same dependency
      were found declared across different package.json files. Please consolidate
      those to match across all package.json files. Different versions for the
      same dependency is not supported.

      If you have questions about this please reach out to the operations team.

      The conflicting dependencies are:

        @types/react-test-renderer
          ^16.9.1 => assistant-dashboards
          ^18.0.0 => observability-dashboards
        husky
          ^8.0.0 => assistant-dashboards
          ^8.0.3 => observability-dashboards
        plotly.js-dist
          ^1.57.1 => gantt-chart-dashboards
          ^2.2.0 => observability-dashboards
        react-plotly.js
          ^2.4.0 => gantt-chart-dashboards
          ^2.5.1 => observability-dashboards
error Command failed with exit code 1.
```

**Comment by peterzhuamazon** [comment]
Think I find the issue now:
```
2024-01-18 18:43:23 ERROR    Failed plugins are ['observabilityDashboards', 'customImportMapDashboards']
```
