### ISSUE TITLE
Add dashboards-assistant experimental config into opensearch-dashboards.yml file.

### ISSUE THREAD

**Issue by SuZhou-Joe** [opensearch-project/opensearch-build#4361]
We are going to onboard a new dashboard plugin: `dashboards-assistant` into our build process and it will be experimental on 2.12.

**Comment by jordarlu** [comment]
Adding @peterzhuamazon, @gaiksaya and @prudhvigodithi for the comments, thanks !!

**Comment by peterzhuamazon** [comment]
Resolved now. Thanks.
