### ISSUE TITLE
Clarify when and where unit tests are executed during the release process

### ISSUE THREAD

**Issue by salyh** [opensearch-project/opensearch-build#4364]
### Is your feature request related to a problem? Please describe

After browsing through all the source code, jenkins jobs, github workflows and documentation its unclear for me when and where unit tests are executed during the release process for opensearch and dashboards. For opensearch i would have expected to find execution of "./gradle test" or "./gradle check" somewhere but found nothing.

### Describe the solution you'd like

Add some docs to outline where unit tests are executed. There is plenty information about the integration tests but almost nothing about  unit testing. Is it ensured that the unit tests are executed (and miust be successful) during the release process?

**Comment by jordarlu** [comment]
Thanks for sending up a question and describing the solution it might be more helpful for the community, @salyh.
I hope the following link would explain better how we engage the testing and where we configure those on demands. https://github.com/opensearch-project/opensearch-build/wiki/Testing-the-Distribution#testing-a-distribution
Please feel free to commnet further if any feedback or suggestions to improve..

**Comment by jordarlu** [comment]
Sorry, @salyh, it seems that I overlooked your mention of 'unit test'. My apologies.. 
We do indeed expect the community to include unit and/or regression tests with every code change, regardless of whether it's in Python, Gradle, Jenkins or others. Please check this link for guidance: https://github.com/opensearch-project/opensearch-build/blob/main/DEVELOPER_GUIDE.md#run-tests-1. It's important to note that without adequate unit testing, the PR most likely won't get the approval by the maintainer, which is a crucial step in ensuring our code maintains a high standard. 
Additionally, for every PR, we use [CI](https://build.ci.opensearch.org/job/gradle-check/) to run all current checks, as seen here: https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/gradle/gradle-check.jenkinsfile. This process helps us ensure that new changes don't affect the existing code negativelly. 
You're absolutely right in saying that we currently don't run unit tests during the release process. Considering the community has hundreds of unit test cases, re-running them all during the release cycle would be very time-consuming. Therefore, we choose to perform unit testing outside of the release cycle.
I hope that explains a bit...

**Comment by jordarlu** [comment]
Hello, @salyh , I hope the response above might have aswered the questions, and am going to close this issue for now. Please feel free to re-open it if needed, thank you!
