### ISSUE TITLE
[Bug]: opensearch-build is failing to build windows artifact on main

### ISSUE THREAD

**Issue by SuZhou-Joe** [opensearch-project/opensearch-build#4369]
### Describe the bug

https://build.ci.opensearch.org/blue/organizations/jenkins/distribution-build-opensearch-dashboards/detail/distribution-build-opensearch-dashboards/7146/pipeline/76

windows build is failing and the flow won't update index until all the flows pass, the index now always points to a staled main build artifact.

### To reproduce

https://build.ci.opensearch.org/blue/organizations/jenkins/distribution-build-opensearch-dashboards/detail/distribution-build-opensearch-dashboards/7146/pipeline/76

### Expected behavior

The build should success.

### Screenshots

![image](https://github.com/opensearch-project/opensearch-build/assets/13493605/40600b1f-9d0c-4e4a-9a8b-bd0fd0b0c6f4)

### Host / Environment

windows

### Relevant log output

```shell
info [  opensearch-dashboards  ] Cleaning npm from node

   â”‚ debg Deleting patterns: [

   â”‚        'C:/Users/ContainerAdministrator/tmpte2i8pc2/OpenSearch-Dashboards/build/opensearch-dashboards-3.0.0-windows-x64/node/**/node_modules',

   â”‚        'C:/Users/ContainerAdministrator/tmpte2i8pc2/OpenSearch-Dashboards/build/opensearch-dashboards-3.0.0-windows-x64/node/**/npm*',

   â”‚        'C:/Users/ContainerAdministrator/tmpte2i8pc2/OpenSearch-Dashboards/build/opensearch-dashboards-3.0.0-windows-x64/node/**/npx*',

   â”‚        'C:/Users/ContainerAdministrator/tmpte2i8pc2/OpenSearch-Dashboards/build/opensearch-dashboards-3.0.0-windows-x64/node/**/corepack*',

   â”‚        'C:/Users/ContainerAdministrator/tmpte2i8pc2/OpenSearch-Dashboards/build/opensearch-dashboards-3.0.0-windows-x64/node/**/nodevars*'

   â”‚      ]

   â”‚ERROR failure 1 sec

   â”‚ERROR Error: EPERM: operation not permitted, rmdir 'C:\Users\ContainerAdministrator\tmpte2i8pc2\OpenSearch-Dashboards\build\opensearch-dashboards-3.0.0-windows-x64\node\node_modules\npm\node_modules\node-gyp\node_modules\readable-stream'



Done in 370.19s.

+ mkdir -p builds/dist

+ ARTIFACT_BUILD_NAME=opensearch-dashboards-3.0.0-windows-x64.zip

+ ARTIFACT_TARGET_NAME=opensearch-dashboards-min-3.0.0-windows-x64.zip

+ cp target/opensearch-dashboards-3.0.0-windows-x64.zip builds/dist/opensearch-dashboards-min-3.0.0-windows-x64.zip

cp: cannot stat 'target/opensearch-dashboards-3.0.0-windows-x64.zip': No such file or directory
```

**Comment by jordarlu** [comment]
thanks for opening a bug on this issue, @SuZhou-Joe 
Looks like we may need to update the clean up pattern here https://github.com/opensearch-project/OpenSearch-Dashboards/blob/b5d39b6e651ecf6c32fc87d6f8f893a86d48e3f2/src/dev/build/tasks/nodejs/clean_node_builds_task.ts#L40-L44,
Maybe to make it like `'node/**/node_modules/**'` instead?
Looping in @peterzhuamazon to comment further,, thanks

**Comment by peterzhuamazon** [comment]
> thanks for opening a bug on this issue, @SuZhou-Joe Looks like we may need to update the clean up pattern here https://github.com/opensearch-project/OpenSearch-Dashboards/blob/b5d39b6e651ecf6c32fc87d6f8f893a86d48e3f2/src/dev/build/tasks/nodejs/clean_node_builds_task.ts#L40-L44, Maybe make it like `'node/**/node_modules/**'` instead? Looping in @peterzhuamazon to comment further,, thanks

This is a flaky failure for a while, which I have not seen in previous releases until 2.12.
We need OSD core team to help with this.
The path does not have more than 260 chars, and it is within a location that should be able to get removed.
The call is trying to use `rm` `rmdir` which is alias to `Remove-Item` on Windows, and seems like it is trying to use `force` already with recursive, and the user should be the `ContainerAdministrator` which is default to the Windows container.
* https://github.com/opensearch-project/OpenSearch-Dashboards/blob/b5d39b6e651ecf6c32fc87d6f8f893a86d48e3f2/src/dev/build/lib/fs.ts#L104-L123

Need @AMoo-Miki to help checking the issue here if possible.

Thanks.

**Comment by bbarani** [comment]
@AMoo-Miki  @ashwin-pc Can you please provide your inputs here?

**Comment by jordarlu** [comment]
Hello, @AMoo-Miki and @ashwin-pc, your comments would be greatly appreciated! Thank you in advance!

**Comment by peterzhuamazon** [comment]
Close as it is running fine in production now.
Feel free to reopen on this.

Thanks.
