### ISSUE TITLE
[On-boarding]: Onboarding skills to build repo

### ISSUE THREAD

**Issue by zane-neo** [opensearch-project/opensearch-build#4378]
### What is the name of your plugin?

opensearch-skills

### What is the link to your GitHub repo?

https://github.com/opensearch-project/skills

### Targeted release version

2.12

### What type of the plugin are we on-boarding?

OpenSearch

### Did you read the on-boarding document

Yes

### Does this plugin has all the necessary automated tests?

Yes

### Have you completed the required reviews including Security reviews, UX reviews?

No UX review and security review is ongoing

### Have you on-boarded automated security scanning for the GitHub repo associated with this plugin?

No

**Comment by peterzhuamazon** [comment]
Seems like this is something we want to onboard for 2.12.0.

@prudhvigodithi could you take a look at this? Seems like their repo is already public.

cc: @bbarani 

Thanks.

**Comment by prudhvigodithi** [comment]
Thanks @peterzhuamazon, hey @zane-neo can you please take a look at the recent onboarding issue with dashboards-assistant plugin.
https://github.com/opensearch-project/opensearch-build/issues/4322 

Were you able to build the distribution using this new plugin? Steps are mentioned in the [on-boarding document](https://github.com/opensearch-project/opensearch-build/blob/main/ONBOARDING.md#onboard-to-build-workflow).
Pending tasks before closing this issue:

- On-board to 2.12.0 manifest
- On-board to test workflow by adding integration tests

Thanks!

**Comment by peterzhuamazon** [comment]
Just followed up with Zan on a few things:
1. Zan will open a PR for changes in opensearch-build including github/workflows, manifests, more.
2. Zan will resolve the maven publish issues in skills build.gradle, as well as repo order fix.
3. Peter will help onboard skills repo with SONATYPE credential access, so skills can use github actions to publish maven artifacts to staging sonatype repo.

There are some other small things to follow up later.
Thanks.

**Comment by peterzhuamazon** [comment]
Work with @zane-neo to complete the above tasks.

Also maven snapshot publishing to sonatype is here:
* opensearch-project/skills#156
* opensearch-project/skills#163
* opensearch-project/skills#166
* #4387


https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/plugin/opensearch-skills/3.0.0.0-SNAPSHOT/
https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/plugin/opensearch-skills/2.12.0.0-SNAPSHOT/
