### ISSUE TITLE
Add release notes collection to build workflow assembly

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#438]
**Is your feature request related to a problem? Please describe.**

We're collecting and generating release notes manually. The bundle workflow can do it for us.

https://github.com/opensearch-project/opensearch-plugins/issues/120 for individual plugin release notes.

Acceptance criteria:
- [ ] The release notes tools should be able to automatically collate the release notes across multiple repositories to create a master release notes corresponding to a specific distribution
- [ ] The release notes tool should also include link checker, spelling checker and any other validation that can be run as part of a pull request workflow.

**Comment by peternied** [comment]
[Triage] this can be automated we have a script already

**Comment by peterzhuamazon** [comment]
https://github.com/opendistro-for-elasticsearch/opendistro-build/blob/main/release-tools/scripts/releasenotes.sh

**Comment by peterzhuamazon** [comment]
[Grooming] Each Plugin Team should have their release notes ready as soon as their code is ready for release.

**Comment by peterzhuamazon** [comment]
Make a proposal on what we can do to force plugin owners push a release note.

**Comment by bbarani** [comment]
https://github.com/opensearch-project/OpenSearch/issues/1868

**Comment by bbarani** [comment]
I am closing this issue as its actively tracked in https://github.com/opensearch-project/OpenSearch/issues/1868

**Comment by gaiksaya** [comment]
Created another one for consolidated release notes https://github.com/opensearch-project/opensearch-build/issues/4009
