### ISSUE TITLE
[Plugins CI] Generate 1.4.0 artifact to unblock CIs

### ISSUE THREAD

**Issue by DarshitChanpura** [opensearch-project/opensearch-build#4392]
Security-dashboards-plugin CI for `1.x` branch is currently blocked due to security plugin 1.4.0.0 artifact not being available[1]. All security-dashboards plugin PRs currently pointing to 1.x branch are blocked.

I understand that the 1.3 is the last minor version in 1.x line and there will not be 1.4.0 however OpenSearch and OpenSearch Dashboards seems to already been incremented to 1.4.0. So this is request to publish 1.4.0 artifact to unblock merging changes in 1.x line to then be backported to 1.3.

If we think that is not the best solution, an alternative approach is to announce it to plugins to stop basing PRs against 1.x, and directly push the changes to 1.3 which will unblock changes going into 1.3.

Thoughts?

[1] - https://github.com/opensearch-project/security-dashboards-plugin/pull/1750

**Comment by prudhvigodithi** [comment]
[Triage]
Hey @DarshitChanpura I have added `1.x` series to version increment automation this should have PR's created with `1.4.0` version increment.
Thanks

**Comment by DarshitChanpura** [comment]
> Hey @DarshitChanpura I have added 1.x series to version increment automation this should have PR's created with 1.4.0 version increment.
Thanks

Thank you @prudhvigodithi . This did create PRs however the CI build seems to not have run for 1.4.0 even though security plugin is added to 1.4 [manifest](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/1.4.0/opensearch-1.4.0.yml)

**Comment by derek-ho** [comment]
@jordarlu @prudhvigodithi windows 1.4 artifacts are not available yet. This is blocking this PR: https://github.com/opensearch-project/security-dashboards-plugin/pull/1951, can we generate those?

**Comment by gaiksaya** [comment]
Hi @derek-ho @DarshitChanpura was this issue resolved?

**Comment by DarshitChanpura** [comment]
@gaiksaya not yet. The windows artifact is not yet available: https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/1.4.0/1389/windows/x64/zip/builds/opensearch/plugins/opensearch-security-1.4.0.0.zip

**Comment by gaiksaya** [comment]
Hi @DarshitChanpura I can access it now https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/1.4.0/latest/windows/x64/zip/builds/opensearch/plugins/opensearch-security-1.4.0.0.zip
Can you please check and close the issue if it is resolved?

Thanks!

**Comment by DarshitChanpura** [comment]
yes, I can too. Thank you for fixing it @gaiksaya !
