### ISSUE TITLE
Update documentation on ECR and docker-hub for opensearch to reflect admin credentials change

### ISSUE THREAD

**Issue by DarshitChanpura** [opensearch-project/opensearch-build#4396]
Update [docker-hub](https://hub.docker.com/r/opensearchproject/opensearch) and [ECR](https://gallery.ecr.aws/opensearchproject/opensearch) documentation to reflect changes to admin user credentials in security plugin demo configuration tool once 2.12 is GA. (Owners: @peterzhuamazon @prudhvigodithi since they have access to update)

### Tasks:

- [x] Update docker-hub documentation
- [x] Update ECR documentation

**Comment by prudhvigodithi** [comment]
Also we should update ECR as well https://gallery.ecr.aws/opensearchproject/opensearch. 
Thanks

**Comment by DarshitChanpura** [comment]
thanks @prudhvigodithi. I've updated the description.

**Comment by peterzhuamazon** [comment]
Updated already.

**Comment by DarshitChanpura** [comment]
@peterzhuamazon any reason why this got re-opened?

**Comment by rishabh6788** [comment]
Will be closed after 2.12.0 released.

**Comment by bbarani** [comment]
@rishabh6788 @peterzhuamazon @DarshitChanpura  Can we close this issue?

**Comment by DarshitChanpura** [comment]
On [docker-hub](https://hub.docker.com/r/opensearchproject/opensearch) & [ECR](https://gallery.ecr.aws/opensearchproject/opensearch), some description still needs be updated;
```md
Send requests to the OpenSearch REST API to verify that OpenSearch is working. By default, OpenSearch uses self-signed TLS certificates. The -k short option skips the certificate verification step so requests don't fail. The default username is admin and the default password is admin.

curl -X GET "https://localhost:9200" -ku admin:admin
curl -X GET "https://localhost:9200/_cat/nodes?v" -ku admin:admin
curl -X GET "https://localhost:9200/_cat/plugins?v" -ku admin:admin
```

**Comment by peterzhuamazon** [comment]
Changed now. 
![Screenshot 2024-03-12 at 1 36 47 PM](https://github.com/opensearch-project/opensearch-build/assets/65193828/e09d83bf-8631-44bf-9668-030f766d0866)

**Comment by peterzhuamazon** [comment]
This issue is completed for now.
Thanks.

**Comment by peterzhuamazon** [comment]
More updates:
```
The default username is `admin` and the password will be `admin` for OpenSearch 2.12 and earlier. For OpenSearch 2.12 and later, the password will be the custom value, which is required to be provided during the demo configuration setup for security plugin.
```
