### ISSUE TITLE
When verifying dependencies in CI, only look for compile time dependencies

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#440]
**Is your feature request related to a problem? Please describe.**

Coming from https://github.com/opensearch-project/opensearch-build/pull/414#discussion_r706329805, only look for compile time dependencies, `./gradlew :dependencies --configuration compile`

**Comment by peternied** [comment]
[Triage] @dblock Looks like this is resolved, please reopen if it isn't complete

**Comment by dblock** [comment]
Yes, was resolved in https://github.com/opensearch-project/opensearch-build/pull/495.
