### ISSUE TITLE
[Bug]: Distribution failure GitHub issue is not closed if incremental build skips building.

### ISSUE THREAD

**Issue by zelinh** [opensearch-project/opensearch-build#4444]
### Describe the bug

We recently noticed a circumstance that our auto-cut distribution failure will not be closed if incremental build skips building certain plugin repo.

### Encountering this scenario: 
During RC creation, we have a cron triggered distribution build job for example with build number **100** completed with most components built successfully but PA plugin repo failed. We updated the `latest` index after the job finished since essential components (OS, JS, CU)are passing. 

However, if one developer manually triggers the build job **101** without enabling incremental build, the distribution build job will run build across all components; in this build, if any of the essential plugins for example OpenSearch repo flakily failed, an auto-cut GitHub issue will be created and `latest` index will not be updated.

In the next run, a cron-triggered distribution build job **102** enabled with the incremental build is building based on `latest`. It will pick up the built artifacts from **100**. Since it's the release cycle, OS repo doesn't have commits change during this period, current job will be only incrementally building PA plugin.

The issue comes as we are not auto closing our GitHub issue for OS if they don't have any changes and we not re-building it. 

### Our GitHub issue update system
The problem is that our GitHub issue update mechanism is reading through the logs generated from our Python build workflow. https://github.com/opensearch-project/opensearch-build/blob/9ecf30a001adf0ed1354a422cf479e187f1ad950/jenkins/opensearch/distribution-build.jenkinsfile#L889-L893
It looks for `Successfully built` from the logs to close any of the existing GH issue.

If incremental build skips building current component(No changes from previous build), the build workflow will log `Skipping ***`. Therefore our GH issue logic miss to catch it so it didn't close any of the existing issue.

### To reproduce

Follow the scenario I provided.

### Expected behavior

The auto-cut GitHub issue should be auto-closed if it's skipped by incremental build.

**Comment by zelinh** [comment]
This seems like an edge case, and the simple way to close this kinds of auto-cut issue is to manually re-run the build for this particular component or wait until the cron job to trigger the job if this component has any commit changes.

However, we want to reduce the confusion caused by this issue if it ever happened.

**Comment by zelinh** [comment]
We are using a hacky way to update GitHub issue when we are building. It's highly depends on the logging from the Python workflow. I had the situation that I was suggested not to change the python build logging since it's used by this CI level GitHub creation and update.

I think we could enhance this issue update mechanism to use the build/bundle manifest generated from the distribution build workflow.
We have different build/bundle manifests available for all our distribution types, architectures and platform. We could use that as the reference to know which components pass or fail.

**Comment by rishabh6788** [comment]
Assigning to @zelinh as he is actively looking into this issue.

**Comment by zelinh** [comment]
Closing this issue as we think it's not really a bug. When incremental build skips building certain repo, it shouldn't confirm build issue could be closed since it's not really building it. 

The situation in our case could be resolved when we come up with a long term plan on our auto cut issue mechanism. We will create a new enhancement request to keep track of that.
