### ISSUE TITLE
[Retrospective] Release 2.12.0

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/opensearch-build#4454]
This is Retrospective for the release 2.12.0
* https://github.com/opensearch-project/opensearch-build/issues/4115

How to use this issue?
Please add comments to this issue, they can be small or large in scope. Honest feedback is important to improve our processes, suggestions are also welcomed but not required.

What will happen to this issue post release?
There will be a discussion(s) about how the release went and how the next release can be improved. Then this ticket will be updated with the notes of that discussion along side action items.

**Comment by bbarani** [comment]
Closing this issue as we have completed the retro for 2.12.0 version. - https://github.com/orgs/opensearch-project/projects/196
