### ISSUE TITLE
Check that maven repositories in each component are properly ordered and include local 

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#446]
**Is your feature request related to a problem? Please describe.**

In order to build a monolith we want stable dependencies during build. Each component needs to keep `mavenLocal` in their gradle configuration, then AWS maven, then maven central, so we can drop things in maven local and get those picked up during the bundle build.

Add a CI check for this.

**Acceptance Criteria:**
When running ./build.sh manifest/x.y.z/opensearch-x.y.z.yml build fails for any component that has the maven repositories incorrectly ordered.

**Comment by peterzhuamazon** [comment]
Need more investigation on how severe the problem is.

**Comment by gaiksaya** [comment]
[Triage] @dblock What would be the acceptance criteria for this issue?

**Comment by dblock** [comment]
> [Triage] @dblock What would be the acceptance criteria for this issue?

When running `./build.sh manifest/x.y.z/opensearch-x.y.z.yml` build fails for any component that has the maven repositories incorrectly ordered.

**Comment by gaiksaya** [comment]
Closing this issue in favor of https://github.com/opensearch-project/opensearch-build/issues/637
Seems like duplicate. Thanks!
