### ISSUE TITLE
[Benchmark] Upgrade self-managed benchmark datastore cluster to 2.12.0 version

### ISSUE THREAD

**Issue by rishabh6788** [opensearch-project/opensearch-build#4476]
The current benchmark datastore serving https://opensearch.org/benchmarks is using OpenSearch-2.7.0 version. Since the release of OS-2.7.0 version there have been many significant changes, updates and bug-fixes have gone into OpenSearch Dashboards. 
This issue is to track the upgrade of benchmark datastore cluster from OS-2.7.0 to OS-2.12.0.

**Comment by zelinh** [comment]
[Triaged] @rishabh6788 Are we able to close this issue? Seems like the migration is completed.

**Comment by rishabh6788** [comment]
Version upgrade was completed successfully.
