### ISSUE TITLE
[Benchmark] Add support to run benchmark against user provided cluster endpoint

### ISSUE THREAD

**Issue by rishabh6788** [opensearch-project/opensearch-build#4478]
### Is your feature request related to a problem? Please describe

As of now the nightly benchmark platform supports running end to end benchmark, meaning, the workflow creates the opensearch cluster as per user provided configuration, runs the benchmark using opensearch-benchmark tool and then deletes the cluster once the benchmark is finished. 

There are cases when the user wants to preserve the cluster to post-analysis after the benchmark has run but the benchmark doesn't support preserving the cluster after the benchmark. This is also not scalable and will become difficult to manage as more and more users want to preserve the cluster, and managing access will be another pain. 

### Describe the solution you'd like

The solution that we are proposing is to allow users to just provide an endpoint to their own clusters and use the benchmark platform to run the benchmark against it. 
This way the users can manage the life-cycle of their clusters and leverage benchmark platform to execute benchmarks and also be able to analyze benchmark metrics data using metrics datastore cluster.

**Comment by Divyaasm** [comment]
Closing via https://github.com/opensearch-project/opensearch-build/pull/4579
