### ISSUE TITLE
[release]: opensearch-dashboards-test-library on npm

### ISSUE THREAD

**Issue by ashwin-pc** [opensearch-project/opensearch-build#4493]
### Did you read the on-boarding document

Yes

### What is the name of your component?

opensearch-dashboards-test-library

### What is the link to your GitHub repo?

https://github.com/opensearch-project/opensearch-dashboards-test-library

### Targeted release date

asap

### Where should we publish this component?

NPM

### What type of artifact(s) will be generated for this component?

Just a copy of the source files

### Have you completed the required reviews including security reviews, UX reviews?

This is already being used as is for the https://github.com/opensearch-project/opensearch-dashboards-functional-test repo

### Have you on-boarded automated security scanning for the GitHub repo associated with this component?

No

**Comment by jordarlu** [comment]
Hi, @ashwin-pc , by following the `1-click process` at [here](https://github.com/opensearch-project/opensearch-build/blob/main/ONBOARDING.md#onboarding-to-universal--1-click-release-process), could you open an issue like [this](https://github.com/opensearch-project/opensearch-build/issues/3548) to add access for  [opensearch-ci-bot](https://github.com/opensearch-ci-bot) to access  `https://github.com/opensearch-project/opensearch-dashboards-functional-test` repo if you haven't yet?

**Comment by jordarlu** [comment]
Adding @gaiksaya for helping on adding openseach-ci-bot to access `https://github.com/opensearch-project/opensearch-dashboards-functional-test` repo. :)

**Comment by gaiksaya** [comment]
openseach-ci-bot  has been added to the above mentioned repo. Please proceed with next steps. 
Thank you!

**Comment by jordarlu** [comment]
Hi, @ashwin-pc, could you please confirm what artifacts ( you mentioned source files ) you want to be published to NPM? in which folder of the repo the artifacts will be placed? Just to provide more info, this is the library we use to publish the artifacts to NPM https://github.com/opensearch-project/opensearch-build-libraries/blob/main/vars/publishToNpm.groovy , thanks

**Comment by getsaurabh02** [comment]
Closing this. @ashwin-pc feel free to re-open or create new issue if this is still relevant.
