### ISSUE TITLE
[Bug]: Auto close the created AUTOCUT integration test failure issues.

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/opensearch-build#4495]
### Describe the bug

The autocut issues created for integration test failures during a release are not auto closed.
https://github.com/issues?q=is%3Aopen+is%3Aissue+user%3Aopensearch-project+label%3Av2.12.0+label%3Aautocut+%5BAUTOCUT%5D+in%3Atitle+

This auto close is available for issues created for distribution build failures, example https://github.com/opensearch-project/k-NN/issues/1484#issuecomment-1945273259.

### To reproduce

Closed manually https://github.com/opensearch-project/dashboards-notifications/issues/161#issuecomment-1953487850

### Expected behavior

- The workflow should detect the passed integration tests for all distributions.
- Ensure no distribution label exists to the issue.
- Once right checks are met close the issue.

**Comment by peterzhuamazon** [comment]
Close this as it seems already resolved in #5038.
