### ISSUE TITLE
When there is a build failure in bundle-build workflow an issue should be created 

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#451]
When there are build failures, they should not depend on manual inspect and write up to create an issue on the associated branch.

This issue could have common mitigation, how to repro locally quickly, and other helpful features.

Eg https://github.com/opensearch-project/job-scheduler/issues/58

**Comment by aditjind** [comment]
Should the issues be marked with priority levels as well, which issues need urgent attention as it is blocking many other teams, etc?
