### ISSUE TITLE
[release]: Release 2.6.0 version of opensearch-js client on npm

### ISSUE THREAD

**Issue by bandinib-amzn** [opensearch-project/opensearch-build#4513]
### Did you read the on-boarding document

Yes

### What is the name of your component?

[opensearch-js](https://github.com/opensearch-project/opensearch-js)

### What is the link to your GitHub repo?

https://github.com/opensearch-project/opensearch-js

### Targeted release date

asap. Before 2.13 code freeze date if possible.

### Where should we publish this component?

NPM

### What type of artifact(s) will be generated for this component?

[To be enter]

### Have you completed the required reviews including security reviews, UX reviews?

[To be enter]

### Have you on-boarded automated security scanning for the GitHub repo associated with this component?

Yes. It is already there.

### Additional context

N/A

**Comment by jordarlu** [comment]
Hi, @bandinib-amzn, is this issue completed by https://build.ci.opensearch.org/job/opensearch-js-release/11/?  thanks,
