### ISSUE TITLE
[Bug]: Debian Package - no service restart after apt upgrade

### ISSUE THREAD

**Issue by wieso-itzi** [opensearch-project/opensearch-build#4515]
### Describe the bug

I didn't know if Bug or Feature Request was the right category for this, since I don't know if the behaviour is intentional or not.

The problem at hand is that after upgrading opensearch and opensearch-dashboards from Version 2.11.1 to 2.12.0 via apt upgrade, the systemd service of these 2 packages didn't automatically restart (even though the units are enabled and were active when starting the update). The packages were installed from the official OpenSearch Apt-Repo (https://artifacts.opensearch.org/releases/bundle/opensearch/2.x/apt).

### To reproduce

Add https://artifacts.opensearch.org/releases/bundle/opensearch/2.x/apt or https://artifacts.opensearch.org/releases/bundle/opensearch-dashboards/2.x/apt to your sources.list
Install opensearch or opensearch-dashboards in Version 2.11.1
Start and enable the systemd unit
Perform an upgrade to Version 2.12.0 via apt upgrade

### Expected behavior

This behaviour is really unusual for systemd units that are distributed via Debian package. A user upgrading the package would expect the service to be restarted automatically after the upgrade (especially if the systemd unit was enabled).
If this really is the intended behaviour for your Debian packages I would advise you to specify in the documentation that it's recommended to hold the packages back via "apt mark hold" (similar to how it's described in the kubeadm documentation for their debian packages), since any kind of automatic upgrade process that's in place would stop the service (or at least force the user to implement some sort of hook in their automatic upgrade process that starts the service afterwards).
If it's not intended and it would be ok for you to be changed then I could gladly help out with a PR. I've implemented this before, both with postinst-Scripts and debhelper, it's not that complicated.

### Host / Environment

The problem occured on a Debian 12 (bookworm) host but I would be expect it to behave the same on all systemd-based Hosts that upgrade the Debian package

**Comment by peterzhuamazon** [comment]
Hi, @wieso-itzi,

This is duplicate with https://github.com/opensearch-project/opensearch-build/issues/3891.

We would be greatly appreciate if you can help with a PR or some comments on how to resolve this.
And I would be happy to review the code with you.

If you dont mind can you close this PR and continue the conversation in the old one I posted, so that context is not lost in the process?

Thanks!
