### ISSUE TITLE
Publish built artifacts publicly to `release-candidates/` folder 

### ISSUE THREAD

**Issue by setiah** [opensearch-project/opensearch-build#453]
### Proposal

The build workflow today keeps the built tar artifacts in an internal S3 bucket. The test workflow pulls these artifacts from the internal S3 bucket to run all long running tests against them. There is no good reason to keep these artifacts internal. If instead of keeping these artifacts in internal bucket, we could push them to external `artifacts.opensearch.org` bucket under `release-candidates/` folder, we can simplify our release workflow by cutting one additional step (which is internal) while also making the release process more transparent to community. The tests results for a release candidates will be publicly viewable on the Jenkins dashboard. Some release candidates might pass all long running tests, and some might fail. The newest candidate that passes all long running tests, will always be tagged `latest` automatically as a post-testing step and can be used by community. At the time of release, the `latest` tagged release candidate will be released. 

There are also several benefits to this approach - 
1. It provides a *public* test audit history for all release candidates that were or will be promoted to release.
2. it keeps the snapshot and release-candidate workflows similar from testing perspective w/ only change being a different url to read from. A uniform approach keeps the cicd system simpler.

**Comment by setiah** [comment]
cc: @mch2 @dblock

**Comment by peternied** [comment]
Created https://github.com/opensearch-project/OpenSearch/issues/1240 to allow for ad-hoc locations for these artifacts instead of requiring the current hardcoded path

**Comment by gaiksaya** [comment]
Issue is resolved by this PR: https://github.com/opensearch-project/opensearch-build/pull/1378

**Comment by peternied** [comment]
I would like to verify this issue after we've had a build created

**Comment by gaiksaya** [comment]
> I would like to verify this issue after we've had a build created

Hi @peternied, you can verify with recent build for `1.2.4` version. Let me know if you want the links to those.
Thanks!
