### ISSUE TITLE
[BENCHMARK] Pass OS Cluster password securely. 

### ISSUE THREAD

**Issue by rishabh6788** [opensearch-project/opensearch-build#4533]
### Is your feature request related to a problem? Please describe

The nightly benchmark platform currently deploys a secure and non-secure opensearch cluster to run benchmarks on. Before Os-2.12.0 the security plugin provided `admin:admin` credentials as part of default configuration and we used the same for  setting up the secure test-cluster. Starting OS-2.12.0 the security plugin has mandated that a strong password is supplied by the user. For now we have hardcoded that strong password in the workflow code and running nightly benchmarks. Since the test-clusters are created in a VPC and are only accessible inside the VPC this does not pose any threat but moving forward where we are planning to open our benchmark platform to accept remote cluster endpoints to run benchmarks it becomes necessary to allow users to provide their cluster passwords without leaking it publicly. 

### Describe the solution you'd like

The user should be able to pass their cluster password securely while submitting benchmark runs using the public benchmark platform against their remote cluster.

**Comment by Divyaasm** [comment]
closed via https://github.com/opensearch-project/opensearch-build/pull/4621
