### ISSUE TITLE
[Bug]: Distribution incremental build failed on non-supported platform

### ISSUE THREAD

**Issue by zelinh** [opensearch-project/opensearch-build#4545]
### Describe the bug

Recently we noticed this job distribution build job failed on Performance Analyzer on Windows platform. 
https://build.ci.opensearch.org/blue/organizations/jenkins/distribution-build-opensearch/detail/distribution-build-opensearch/9601/pipeline/75/
```
2024-03-17 19:09:34 INFO     Removing C:\Users\ContainerAdministrator\tmp34c74y_f

Traceback (most recent call last):

  File "C:\Users\Administrator\jenkins\workspace\distribution-build-opensearch\src\run_build.py", line 112, in <module>

    sys.exit(main())

  File "C:\Users\Administrator\jenkins\workspace\distribution-build-opensearch\src\run_build.py", line 87, in main

    for component in manifest.components.select(focus=components, platform=target.platform):

  File "C:\Users\Administrator\jenkins\workspace\distribution-build-opensearch\src\manifests\input_manifest.py", line 211, in select

    raise ValueError(f"No components matched focus={','.join(focus)}, platform={platform}.")

ValueError: No components matched focus=performance-analyzer, platform=windows.

script returned exit code 1
```

Performance Analyzer is not supported on windows platform so it shouldn't be built. 

Build failure happened when only this non-supported platform component has commits changed when running incremental build. 

This one passed https://build.ci.opensearch.org/job/distribution-build-opensearch/9607/ when rebuilding plugins are more than just PA.
`Plugins for incremental build: ['k-NN', 'performance-analyzer', 'neural-search']`

### To reproduce

Only one specific plugin has commit changes and run incremental build on this plugin's unsupported platform.

### Expected behavior

The build should be skipped if the platform is not supported.

**Comment by rishabh6788** [comment]
@zelinh Please take a look.

**Comment by zelinh** [comment]
Closing out this issue as this is resolved.
