### ISSUE TITLE
[Bug]: Release notes checker does not check release notes for core engines

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/opensearch-build#4549]
### Describe the bug

With recent enhancement to compile consolidated release notes [PR](https://github.com/opensearch-project/opensearch-build/pull/4196), a change was introduced to skip few components [here](https://github.com/opensearch-project/opensearch-build/pull/4196/files#diff-367096ff0c801397154d58cb4c8fea65125f353b543f5bd686f55bf187499afc)

However, we do not add core engine (OpenSearch and OpenSearch-Dashboards) release notes, we do however need to check their presence in release notes tracker workflow that posts the comments on the release issue. 
Example: https://github.com/opensearch-project/opensearch-build/issues/4433#issuecomment-2004998714

### To reproduce

See https://github.com/opensearch-project/opensearch-build/issues/4433#issuecomment-2004998714

### Expected behavior

The table should also component: OpenSearch and OpenSearch-Dashboards. 

The condition is true for `action_type: compile` but the`action_type: check` should only skip `notifications-core` and not others

**Comment by rishabh6788** [comment]
Will take a look.

**Comment by gaiksaya** [comment]
One more thing, 
There is another bug let me know if I should create a different issue for the same.
The consolidated release notes adds `ml-commons` as `ml-common` and `Opensearch` should be `OpenSearch` in all headings. Somehow this is getting messed up. Example: https://github.com/opensearch-project/opensearch-build/pull/4595/commits/7b2352ecc0c7ee486f461e201ca2d131abc4ac5b

**Comment by rishabh6788** [comment]
> One more thing, There is another bug let me know if I should create a different issue for the same. The consolidated release notes adds `ml-commons` as `ml-common` and `Opensearch` should be `OpenSearch` in all headings. Somehow this is getting messed up. Example: [7b2352e](https://github.com/opensearch-project/opensearch-build/commit/7b2352ecc0c7ee486f461e201ca2d131abc4ac5b)

These seems minor nits, lets track in another issue. 
Closing this.
