### ISSUE TITLE
Automate locking of commits during release

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/opensearch-build#4561]
### Is your feature request related to a problem? Please describe

We lock commits in the manifest files after release candidate are generated in order to avoid unintentional commits from sneaking in. Example: #4560 

### Describe the solution you'd like

Automate this process instead of manually copy/paste and then create a PR. Since we have disabled ci check of the manifests there are high chances of human copy/paste error.

**Comment by prudhvigodithi** [comment]
[Triage]
Hey @gaiksaya we can come up with a workflow that has the `releaseVersion`, `releaseCandidate` as inputs, now the workflow should download the build manifest and update the input release manifest. To raise a PR we need a temp branch to be created so that the bot can raise a PR from that temp branch to main. Should we go with a jenkins job or github workflow ?

Adding @bbarani @peterzhuamazon @rishabh6788

**Comment by gaiksaya** [comment]
GH workflow sounds good to me. Can be manually triggered with inputs. Lease resistance path I believe.

Is it possible to use the same workflow to update those commits as we want. For example:
### Scenario 1:

Input: `releaseVersion`, `releaseCandidate` 
Action: Updates all commits

Now RC1 is built but looks like common-utils and other bunch of repos have changed commits.

### Scenario 2:
Input: `releaseVersion`, `updateAllToRecentCommit` 
Action: Updates all commits to most recent after fixes went it

###Scenrio 3:
Input: `releaseVersion`, `updateAllToRecentCommit`, `componentName`
Action: Only updates specific component commit.

Is it possible to do that or you think that can come as an enhancement?

**Comment by prudhvigodithi** [comment]
@gaiksaya once we have the RC number for a release, everything falls under `Scenario 1`, this includes if the commit has changed or not for a repo part of the manifest. If no change still keeps the same, if changed adds the new commit.

**Comment by gaiksaya** [comment]
Not really right?

In order to generate RC2, we would first update the commit in manifest and then trigger RC to include that commit. So after first RC, the process is opposite.

**Comment by prudhvigodithi** [comment]
Closing this as the manifest lock automation enhancement is completed.
Related PR: https://github.com/opensearch-project/opensearch-build/pull/4583
Jenkins Job: https://build.ci.opensearch.org/job/release-manifest-commit-lock/
