### ISSUE TITLE
[Bug]: Opensearch Docker image no longer runs on Raspberry Pi 4.

### ISSUE THREAD

**Issue by electricbrain-code** [opensearch-project/opensearch-build#4572]
### Describe the bug

Opensearch raspberry pi "Fatal glibc error: This version of Amazon Linux requires a newer ARM64 processor compliant with at least ARM architecture 8.2-a with Cryptographic extensions."

During the upgrade process from 2.9.0 all the way up to 2.12.0, at the first step of 2.9.0 -> 2.10.0 it seems the docker ARM images no longer runs on Raspberry Pi because it is not compliant with Amazon's CPUs.

### To reproduce

1) Download the 2.9.0 docker image to a raspberry pi 4 docker host. Start it up (been running fine).
2) Download the 2.10.0 docker image to the same host. Results in:
"Fatal glibc error: This version of Amazon Linux requires a newer ARM64 processor compliant with at least ARM architecture 8.2-a with Cryptographic extensions."

### Expected behavior

Should more or less run like 2.9.0 docker image.

### Host / Environment

Raspberry Pi 4B 8G
Ubuntu 22.04.3 LTS
docker-ce/jammy,now 5:25.0.2-1 ubuntu.22.04 jammy arm64 [installed]

### Relevant log output

Fatal glibc error: This version of Amazon Linux requires a newer ARM64 processor compliant with at least ARM architecture 8.2-a with Cryptographic extensions.

**Comment by electricbrain-code** [comment]
Testing on the Raspberry Pi *5* 8GB reveals the CPU complies and the docker 2.10.0 image runs

docker run -it registry:5000/opensearchproject/opensearch:2.10.0 /bin/bash

I just have to upgrade all the Pi 4 nodes to Pi 5's :-(

**Comment by electricbrain-code** [comment]
Testing on the BPi-CM4 fails:
Amlogic A311D Quad core ARM Cortex-A73 and dual core ARM Cortex-A53 CPU ,ARM G52 MP4(6EE) GPU
Fatal glibc error: This version of Amazon Linux requires a newer ARM64 processor
                   compliant with at least ARM architecture 8.2-a with Cryptographic
                   extensions. On EC2 this is Graviton 2 or later.

**Comment by electricbrain-code** [comment]
Testing with ODroid C4 passes
Amlogic S905X3 12nm Processor - ARMv8-A architecture with Neon and Crypto extensions
Note: no mention of v8.2-a just v8-A

**Comment by electricbrain-code** [comment]
Someone needs to tell Docker their Architecture field doesn't work anymore......
It the same for Pi4, Pi5, Odroid C4, BPi-CM4, etc.

root@host8:~# docker node inspect hostd.localdomain --pretty
ID:                     ys2cnk4nowep88t6mtmktqads
Labels:
 - arch=aarch64
 - memory=4gb
 - public=true
 - system=RPi5
Hostname:               hostd.localdomain
Joined at:              2023-11-06 00:48:13.70802782 +0000 utc
Status:
 State:                 Ready
 Availability:          Active
 Address:               192.168.0.58
Platform:
 Operating System:      linux
 Architecture:          aarch64
Resources:
 CPUs:                  4
 Memory:                3.612GiB
Plugins:
 Log:           awslogs, fluentd, gcplogs, gelf, journald, json-file, local, logentries, splunk, syslog
 Network:               bridge, host, ipvlan, macvlan, null, overlay
 Volume:                local
Engine Version:         24.0.7

**Comment by peterzhuamazon** [comment]
Hi @electricbrain-code we switched from Amazon Linux 2 to Amazon Linux 2023 on the base image to increase glibc version as well as in preparation of AL2 deprecation. 

This is expected behavior and we currently have not supported RPi officially on our compatibility chart.

If needed I think you can contact AmazonLinux team regarding their container images on https://github.com/amazonlinux/container-images or https://github.com/amazonlinux/amazon-linux-2023/, as opensearch is just using the existing image provided from them. Thanks.
