### ISSUE TITLE
[release]: Onboard Opensearch Migrations onto Maven Central

### ISSUE THREAD

**Issue by AndreKurait** [opensearch-project/opensearch-build#4592]
### Did you read the on-boarding document

Yes

### What is the name of your component?

Migrations TrafficCapture

### What is the link to your GitHub repo?

https://github.com/opensearch-project/opensearch-migrations/tree/main/TrafficCapture

### Targeted release date

04/12/24 in order to unblock existing project workstreams

### Where should we publish this component?

Maven - GroupId `org.opensearch.migrations.trafficcapture`

### What type of artifact(s) will be generated for this component?

Jar, Javadoc, Signature, Pom, etc.

We have an project composed of various subprojects. We intend to expose each subproject as a separate artifact in maven.

```
captureKafkaOffloader
captureOffloader
captureProtobufs
coreUtilities
jsonJMESPathMessageTransformer
jsonJMESPathMessageTransformerProvider
jsonJoltMessageTransformer
jsonJoltMessageTransformerProvider
jsonMessageTransformerInterface
jsonMessageTransformers
nettyWireLogging
openSearch23PlusTargetTransformerProvider
replayerPlugins
testUtilities
trafficCaptureProxyServer
trafficCaptureProxyServerTest
trafficReplayer
```

### Have you completed the required reviews including security reviews, UX reviews?

Existing security reviews covering the solution. No UX review needed as it is a command line solution.

### Have you on-boarded automated security scanning for the GitHub repo associated with this component?

Yes

### Additional context

This is an extension of https://github.com/opensearch-project/opensearch-build/issues/4085

**Comment by rishabh6788** [comment]
Will take this up this week.

**Comment by rishabh6788** [comment]
The migrations team confirmed on publishing all the mentioned sub-projects separately. There could be more projects that will be added at a later point in time. As of now the version bump would be uniform across all projects, meaning if a version is updated from 0.1.0 to 0.2.0, all the projects will be published to maven central with newer version even if there is no change in them.
