### ISSUE TITLE
[Enhancement] 2.14 Infra / Build Improvements

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#4611]
[Enhancement] 2.14 Infra / Build Improvements

* https://github.com/opensearch-project/opensearch-build/issues/4427
  * https://github.com/opensearch-project/opensearch-build/pull/4458
  * https://github.com/opensearch-project/opensearch-build/pull/4525
  * https://github.com/opensearch-project/opensearch-build/pull/4525
  * https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/1142
* https://github.com/opensearch-project/opensearch-ci/issues/412
  * https://github.com/opensearch-project/opensearch-ci/pull/413
  * https://github.com/opensearch-project/opensearch-build/pull/4594
  * https://github.com/opensearch-project/opensearch-build/pull/4597
  * https://github.com/opensearch-project/opensearch-ci/pull/417
  * https://github.com/opensearch-project/opensearch-ci/pull/418
  * https://github.com/opensearch-project/opensearch-build/pull/4642
* https://github.com/opensearch-project/opensearch-build/issues/4612
  * https://github.com/opensearch-project/opensearch-build/pull/4641
* https://github.com/opensearch-project/opensearch-build/issues/4379 (paused for 2.14.0) 
  * https://github.com/opensearch-project/opensearch-build/pull/4645
  * https://github.com/opensearch-project/opensearch-build/pull/4647
  * https://github.com/opensearch-project/k-NN/pull/1634
  * https://github.com/opensearch-project/opensearch-build/pull/4663
  * https://github.com/opensearch-project/k-NN/pull/1664
  * https://github.com/opensearch-project/opensearch-build/pull/4667
  * https://github.com/opensearch-project/k-NN/pull/1674
* https://github.com/opensearch-project/opensearch-build/issues/4084
  * https://github.com/opensearch-project/opensearch-build/pull/4665
* https://github.com/opensearch-project/opensearch-build/issues/3468
  * https://github.com/opensearch-project/project-website/pull/2833
* #4532
  * #4673
- [x] updating

**Comment by gaiksaya** [comment]
Hi @peterzhuamazon Looks like most tasks in this issue are complete and also 2.14.0 (labelled) is out. Can we close it?

**Comment by peterzhuamazon** [comment]
Closing as it is a 2.14.0 task and completed now.
Thanks.
