### ISSUE TITLE
Run link-checker only on specific release note markdown file

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/opensearch-build#4616]
### Is your feature request related to a problem? Please describe

Link checker workflow is consistently failing with `Too many requests` as consolidated release notes contains of all the PRs and issues resolved for all releases. We need to narrow it down to an upcoming release or a specific release-notes.md file

### Describe the solution you'd like

We need to narrow it down to an upcoming release or a specific release-notes.md file rather than running it for entire folder of release notes

**Comment by rishabh6788** [comment]
Closing this issue.
