### ISSUE TITLE
Make plugin integtest.sh run against non-snapshot build

### ISSUE THREAD

**Issue by setiah** [opensearch-project/opensearch-build#469]
The plugin integtest.sh picks up the opensearch version provided in build.gradle, which is 1.1.0-SNAPSHOT. Since the release candidates are non snapshot built artifacts, make this configurable in integ test job

**Comment by dblock** [comment]
I believe the plan is to delete all integtest.sh from all repos and have a default one in this repo. When we re-add any custom integtest.sh in repos let’s put them in a scripts/ sub folder.

**Comment by minalsha** [comment]
Closing the issue since the PR is merged.
