### ISSUE TITLE
Fix integtests to work with multiple plugins 

### ISSUE THREAD

**Issue by setiah** [opensearch-project/opensearch-build#473]
Currently, the integ test instrumentation works fine when running for one component and all possible configurations but it fails when multiple components are tested as part of the same workflow. The instrumentation logic needs to be fixed to handle that.

- [ ] Rework instrumentation logic
- [ ] Fix `alerting`, `reports-scheduler`, `notebooks` integ test instrumentation

Steps to reproduce -
1. Run integration tests on main branch
`bash test.sh integ-test --test-run-id <execution-id> --s3-bucket <bucket_name> --opensearch-version <version> --build-id <id> --architecture <arch>`

Issue signature -

**Comment by minalsha** [comment]
@setiah  please add details with repro steps and what needs to be done. Thanks

**Comment by owaiskazi19** [comment]
`reports-scheduler`, `notebooks` will be fixed as a part of https://github.com/opensearch-project/opensearch-build/issues/476
