### ISSUE TITLE
Release promotion pipeline enhancements

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/opensearch-build#4750]
### Is your feature request related to a problem? Please describe

With #4748  closed, we were able to bring down the pipeline runtime from 1 hour 6min ([1.3.16 release run](https://build.ci.opensearch.org/job/central-release-promotion/5/)) to 21min ([1.3.17 release run](https://build.ci.opensearch.org/job/central-release-promotion/8/)) which is around **68%**. However, there are still few other jobs that are manually triggered today.

Listing them here:

- Docker promotion workflow
- Maven promotion workflow
- Manually invalidate cloudfront
- Validation workflow for all platforms/arch

Other enhancements that are out of the scope of this issue are:
- Manual Validation for core native plugins (example: respository-s3)  https://github.com/opensearch-project/opensearch-build/issues/4659#issuecomment-2153321246
- Adding validation for APT repo
- Increasing the validation time for windows artifacts since its takes 15min for the CI docker image to be pulled on windows agent. 

### Describe the solution you'd like

Add above workflows to automated centralized pipeline bringing us closer to https://github.com/opensearch-project/opensearch-build/issues/3676

**Comment by peterzhuamazon** [comment]
Add on top of this list, we can also add things like:
* Tag repos after release
* Update manifests with tag
* Send helm/ansible PRs
* Cut tag on infra
* More......

to the central release workflow too.

My concern is that we should have a resume function because the central promotion pipeline includes too many steps now. We do not want to switch back to manual trigger if one step failed in the process.

Thanks.

**Comment by gaiksaya** [comment]
@peterzhuamazon IMO the workflows that you mentioned can be added into new central workflow for post release activities. `central-post-release-workflows` WDYT? Trying to keep promotion job as promotion only.
Adding @prudhvigodithi @rishabh6788 to the conversation.

**Comment by peterzhuamazon** [comment]
> @peterzhuamazon IMO the workflows that you mentioned can be added into new central workflow for post release activities. `central-post-release-workflows` WDYT? Trying to keep promotion job as promotion only. Adding @prudhvigodithi @rishabh6788 to the conversation.

Yeah that would also be good so we can separate these two.
Each would take max about 30min and could be easily restarted as well.

Thanks.
