### ISSUE TITLE
[Benchmark] Add c5.2xlarge nightly runs for OS 2.11 - OS 2.15 

### ISSUE THREAD

**Issue by IanHoang** [opensearch-project/opensearch-build#4754]
### Is your feature request related to a problem? Please describe

It'd be good to have a few single node clusters with c5.2xlarge run on a nightly basis.

### Describe the solution you'd like

We can create a suite of single node clusters and run a Big5 workload against them each night. The test configurations should  look something like the following:

**Cluster configurations**
- Single node cluster
- Instance Type: C5.2xlarge
- Workload: Big5
- Heap size: 8GB
- Virtual Memory Max Map Count: 262144
- Discovery Type: single node
- Restore from snapshot: Yes
- Workload Params: 
    - No replicas (i.e. run with --workload-params="number_of_replicas:0").
    - Target-throughput set to 0 or "" to ensure that we run in benchmarking mode

**Comment by rishabh6788** [comment]
Nightlies with mentioned configuration has been scheduled.
