### ISSUE TITLE
[Validation workflow] Support both docker and ECR as image source for container images validation

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/opensearch-build#4756]
### Is your feature request related to a problem? Please describe

Currently the jenkins (as well as python workflow) provides docker validation with either Dockerhub OR ECR but not both.
With #4750, it would be great if we can validate both in one go rather than triggering the job twice. The job params are pretty confusing too as a lot of validations happens together. 

### Describe the solution you'd like

Give an option as 
- Dockerhub
- ECR
- Both

### Describe alternatives you've considered

Keep triggering twice. :(

**Comment by Divyaasm** [comment]
Closed via https://github.com/opensearch-project/opensearch-build/pull/4762
