### ISSUE TITLE
[META] Plugins Integration Testing for Test Automation Surge

### ISSUE THREAD

**Issue by owaiskazi19** [opensearch-project/opensearch-build#476]
Run the Integration Test cases in the OpenSearch distribution building workflow for the plugins

Successful:
|Plugin Name	|Result|
|---	|---	|
|AD Plugin	|<ul><li>- [x] With security</li><li>- [x] without security</li></ul>	|<ul><li>- [x] With security</li><li>- [x] without security</li></ul>	|<ul><li>- [x] </li></ul>	|
|SQL Plugin	|<ul><li>- [x] With security</li><li>- [x] without security</li></ul>	|<ul><li>- [x] With security</li><li>- [x] without security</li></ul>	|<ul><li>- [x] </li></ul>	|
|KNN Plugin	|<ul><li>- [x] With security</li><li>- [x] without security</li></ul>	|<ul><li>- [x] With security</li><li>- [x] without security</li></ul>	|<ul><li>- [x] </li></ul>	|
|Async-search	|<ul><li>- [x] With security</li><li>- [x] without security</li></ul>	|<ul><li>- [ ] With security</li><li>- [x] without security</li></ul>	|<ul><li>- [x] </li></ul>	|

Changes required:
|Plugin Name	|Result| Issue| Fix
|---	|---	|--- |---
|Alerting Plugin	|<ul><li>- [ ] With security</li><li>- [ ] without security</li></ul>	| Since we are downloading alerting plugin as a common dependency for other plugins, the logic to run integ test needs to be changed to run alerting as an individual plugin	| Fixed in https://github.com/opensearch-project/opensearch-build/pull/512
|Notebooks	|<ul><li>- [ ] With security</li><li>- [ ] without security</li></ul>	| Not able to find `/gradlew` to run integ test as the plugin resides in https://github.com/opensearch-project/dashboards-notebooks/tree/main/opensearch-notebooks	| Fixed in #529 
|Reports Scheduler	|<ul><li>- [ ] With security</li><li>- [ ] without security</li></ul>	| Not able to find `/gradlew` to run integ test as the plugin resides in https://github.com/opensearch-project/dashboards-reports/tree/main/reports-scheduler	| Fixed in #529

Reference for Plugins: https://github.com/opensearch-project/opensearch-build/issues/58

**Comment by minalsha** [comment]
@owaiskazi19  can you also document what changes are required for successfully running Alerting/notebooks and Reports Scheduler plugins. Also, please document the resolution shared by @dblock  to address this.
