### ISSUE TITLE
[On-boarding]: dashboards-query-enhancements

### ISSUE THREAD

**Issue by ashwin-pc** [opensearch-project/opensearch-build#4766]
### What is the name of your plugin?

dashboards-query-enhancements

### What is the link to your GitHub repo?

Feature branch source code:
https://github.com/opensearch-project/OpenSearch-Dashboards/tree/feature/discover-next/plugins-extra/query_enhancements

### Targeted release version

2.16

### Does the plugin require documentation?

No

### What type of the plugin are we on-boarding?

OpenSearch-dashboards plugin

### Did you read the on-boarding document?

Yes

### Does this plugin has all the necessary automated tests?

Its an experimental plugin right now. We will add all the necessary scripts once onboarded.

### Have you completed the required reviews including Security reviews, UX reviews?

This is an experimental plugin right now. Security and UX reviews will happen shortly

### Have you on-boarded automated security scanning for the GitHub repo associated with this plugin?

Currently the code is in a feature branch, when the repo is created we will add the required scanning to the repo

**Comment by peterzhuamazon** [comment]
Hi @ashwin-pc ,

Since we are in the middle of the release we cant take it on 2.15.0 anymore.

Thanks.

**Comment by ashwin-pc** [comment]
@peterzhuamazon updated the release. Whats the next steps here?

**Comment by gaiksaya** [comment]
@ashwin-pc Are we good to start with repo creation? I believe that is first step at this point?

**Comment by rishabh6788** [comment]
@ashwin-pc any update on this?

**Comment by prudhvigodithi** [comment]
Hey @ashwin-pc are you still on track to onboard this plugin to [2.16.0 release](https://github.com/opensearch-project/opensearch-build/issues/4771)? Can you please provide your thoughts as I dont see any new repo part of https://github.com/opensearch-project org.
@getsaurabh02.

**Comment by prudhvigodithi** [comment]
Had an discussion with @ashwin-pc, the dashboards-query-enhancement code will be moved to Dashboards core.
Thank you

**Comment by ashwin-pc** [comment]
Ref: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7212

**Comment by gaiksaya** [comment]
Hi @ashwin-pc @prudhvigodithi Will this plugin be enabled by default? Wondering if we need to make any distribution level installation changes to activate it. 
cc: @peterzhuamazon
