### ISSUE TITLE
Rename bundle that is created as part of bundle build into bin dist or min 

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#479]
**Is your feature request related to a problem? Please describe.**

Bundle build produces:

```
bundle
core-plugins
libs
maven
plugins
```

The `bundle` name is confusing and contains only the -min artifact. We should rename it to maybe `bin`?

**Comment by peterzhuamazon** [comment]
I agree with DB on this, I go to build/.../.../bundle folder and only finds min.
Renaming it to dist is definitely a better idea.

**Comment by dblock** [comment]
@xuezhou25 since you were just looking at something related feel free to take this one too!

**Comment by kartg** [comment]
@Rishikesh1159 was working on this
