### ISSUE TITLE
[BUG] IntegTests autocuts will remove labels but will not close issues if no test failed

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#4799]
[BUG] IntegTests autocuts will remove labels but will not close issues if no test failed #4799 
https://github.com/opensearch-project/asynchronous-search/issues/584

Thanks.

**Comment by getsaurabh02** [comment]
Should it add a comment also?

**Comment by peterzhuamazon** [comment]
More examples:
https://github.com/opensearch-project/security-analytics-dashboards-plugin/issues/1043

**Comment by peterzhuamazon** [comment]
I think the logic is supposed to be:
1. If test failed and no issue open, open the issue and add related distro label.
2. if test succeed later then remove that related distro label.
3. If all failed distribution labels are removed due to integTests passing, close issue.

**Comment by prudhvigodithi** [comment]
Hey @peterzhuamazon thats the expected behavior as of today, I have created an issue regrading this topic in past, please check this issue https://github.com/opensearch-project/opensearch-build/issues/4495.
Thanks

**Comment by peterzhuamazon** [comment]
Got it @prudhvigodithi , closing this one in favor of the old issue:
* https://github.com/opensearch-project/opensearch-build/issues/4495

Thanks.
