### ISSUE TITLE
[Bug]: Central promotion workflow failed

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/opensearch-build#4801]
### Describe the bug

The recent change merged failed in central promotion workflow for 2.15.0 with below errors:

```
Could not instantiate {wait=true, job=docker-promotion, parameters=[@string(name=SOURCE_IMAGES,value=opensearch:2.15.0.9992, opensearch-dashboards:2.15.0.7749), @string(name=RELEASE_VERSION,value=2.15.0), @string(name=DOCKER_HUB_PROMOTE,value=true), @string(name=ECR_PROMOTE,value=true), @string(name=TAG_LATEST,value=true), @string(name=TAG_MAJOR_VERSION,value=true)]} for org.jenkinsci.plugins.workflow.support.steps.build.BuildTriggerStep: java.lang.IllegalArgumentException: Could not instantiate {name=DOCKER_HUB_PROMOTE, value=true} for hudson.model.StringParameterValue: java.lang.ClassCastException: hudson.model.StringParameterValue.value expects class java.lang.String but received class java.lang.Boolean
```

Also cloudfront invalidation is for wrong cloudfront

### To reproduce

https://build.ci.opensearch.org/blue/organizations/jenkins/central-release-promotion/detail/central-release-promotion/9/pipeline

### Expected behavior

Should succeed without any failures

**Comment by peterzhuamazon** [comment]
Hi,

Just to list a few here for improvements:
1. Docker promotion trigger error as seen in description
2. Cloudfront invalidation has some wrong triggers
3. Even with parallel runs some promotion runs just longer than others, need to either increase the amount of agent executors or change the order of the runs.

Thanks.
