### ISSUE TITLE
[On-boarding]: Query Insights plugin

### ISSUE THREAD

**Issue by ansjcy** [opensearch-project/opensearch-build#4826]
### What is the name of your plugin?

Query Insights

### What is the link to your GitHub repo?

https://github.com/opensearch-project/OpenSearch/tree/main/plugins/query-insights
https://github.com/opensearch-project/query-insights

### Targeted release version

2.16

### Does the plugin require documentation?

Yes, we already had documentation in https://opensearch.org/docs/latest/observing-your-data/query-insights/index/

### What type of the plugin are we on-boarding?

OpenSearch

### Did you read the on-boarding document?

yes

### Does this plugin has all the necessary automated tests?

yes

### Have you completed the required reviews including Security reviews, UX reviews?

yes

### Have you on-boarded automated security scanning for the GitHub repo associated with this plugin?

yes

### Additional context

Query Insights currently lives in OpenSearch core repo (https://github.com/opensearch-project/OpenSearch/tree/main/plugins/query-insights). We are in the process to move it to a separate repo after 2.16. (https://github.com/opensearch-project/query-insights)

**Comment by gaiksaya** [comment]
Hi @ansjcy ,

2.15 is already out. See https://opensearch.org/versions/opensearch-2-15-0.html
Can you please update the targeted release date here?
Thanks!

cc: @prudhvigodithi @getsaurabh02

**Comment by ansjcy** [comment]
Thanks @gaiksaya , please let us know what are the action items from query-insights to finish the onboarding process. We have created the necessary gradle build scripts in our repo, and let us know if we should also raise a PR to include the plugin in the manifest files in opensearch-build.

**Comment by gaiksaya** [comment]
Hey @ansjcy ,

Can you try and build the component locally. See the instructions in [onboarding](https://github.com/opensearch-project/opensearch-build/blob/main/ONBOARDING.md#onboard-to-build-workflow) document as well as [wiki](https://github.com/opensearch-project/opensearch-build/wiki/Building-an-OpenSearch-and-OpenSearch-Dashboards-Distribution) to build distribution from source. Once you are ready, please create a PR to add the component to [2.16.0 manifest](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/2.16.0/opensearch-2.16.0.yml).
Tagging @prudhvigodithi (2.16.0 release manager)
@peterzhuamazon Please add if I missed anything. 

Thanks!

**Comment by gaiksaya** [comment]
Query insights plugin has been released in 2.16.0. Closing this issue.
