### ISSUE TITLE
[Bug]: /lib64/libm.so.6: version `GLIBC_2.27' not found

### ISSUE THREAD

**Issue by penghuo** [opensearch-project/opensearch-build#4834]
### Describe the bug

opensearch-sql repo github workflow failed. https://github.com/opensearch-project/sql/actions/runs/9865774421/job/27243340727?pr=2811

```
Run actions/checkout@v3
/usr/bin/docker exec  ff6201b20d7adc4ce3fc4d7b4060c504c70b5b08f74e82452f5add288eff9532 sh -c "cat /etc/*release | grep ^ID"
/__e/node20/bin/node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /__e/node20/bin/node)
```

### To reproduce

https://github.com/opensearch-project/sql/actions/runs/9865774421/job/27243340727?pr=2811

### Expected behavior

no issue

**Comment by peterzhuamazon** [comment]
Close as it is fixed for now.

Thanks.
