### ISSUE TITLE
[BENCHMARK] Add support for opensearch-benchmark's `compare` feature

### ISSUE THREAD

**Issue by rishabh6788** [opensearch-project/opensearch-build#4837]
### Is your feature request related to a problem? Please describe

As of today we are using [opensearch-benchmark's ](https://github.com/opensearch-project/opensearch-benchmark) `execute-test` api to run performance benchmark tests on nightly and as well as ad-hoc basis. 
We are also adding support to run performance benchmark on OpenSearch [pull requests](https://github.com/opensearch-project/opensearch-build/pull/4831). 

So, while a developer is working on their changes, apart from just getting performance benchmark numbers published on the PR, they might also want to know how their changes compare against a baseline. 

### Describe the solution you'd like

Fortunately, opensearch-benchmark's [compare](https://opensearch.org/docs/latest/benchmark/reference/commands/compare/) command solves this problem for us. It only requires `baseline` and `contender` `test-execution-ids` as input params and publishes a detailed comparison result. 

We need to add this feature into existing [benchmark workflow](https://github.com/opensearch-project/opensearch-build/blob/main/src/run_benchmark_test.py) and add a job in jenkins, similar to [benchmark-test](https://build.ci.opensearch.org/job/benchmark-test/) to execute this workflow on ad-hoc basis and as well as on pull request.

**Comment by rishabh6788** [comment]
Assigning this to @OVI3D0

**Comment by OVI3D0** [comment]
Commenting for assignment
