### ISSUE TITLE
Automatically add new manifests to the Jenkins pipeline

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#487]
**Is your feature request related to a problem? Please describe.**

In https://github.com/opensearch-project/opensearch-build/pull/461 we generate a new manifest. Add it to the [build pipeline](https://github.com/opensearch-project/opensearch-build/blob/main/bundle-workflow/Jenkinsfile).

**Describe the solution you'd like**

Part of the update modify something that adds the version to the build/test pipeline.

**Comment by dblock** [comment]
@peternied I don't see where I can add/commit configuration that would, for example, add 2.0 builds. Where's the list of the manifests that we're building?

**Comment by mch2** [comment]
To do this I think we need to set up a job DSL with [pipelineJob](https://jenkinsci.github.io/job-dsl-plugin/#path/pipelineJob) that kicks off a job using our Jenkinsfile with a manifest as input. Right now the job is created manually that loads the Jenkinsfile from this repo and invokes it with the 1.1 manifest.

**Comment by peternied** [comment]
We have too many manual processes around the build at the moment, if we enable more than one at a time it is going to bog ~us~ _me_ down.

When logs are publicly accessible #453 and the public CI instance is available - I'd be happy to support N manifests build because then the primary bottleneck is removed.

**Comment by dblock** [comment]
Here's a manual version of what we're trying to automate: https://github.com/opensearch-project/opensearch-build/pull/664.

**Comment by dblock** [comment]
Closed via https://github.com/opensearch-project/opensearch-build/pull/1407
