### ISSUE TITLE
JAVA_HOME missing in dockerhub image

### ISSUE THREAD

**Issue by MichaelRoosz** [opensearch-project/opensearch-build#49]
When using the official dockerhub image "opensearchproject/opensearch:1.0.0-rc1" the env var "JAVA_HOME" is not defined, breaking /tools/securityadmin.sh:
https://github.com/opensearch-project/security/blob/2ecb088a1ac58bd1ac4a0c1100492bc1566b9be7/tools/securityadmin.sh#L19

To fix it I manually set the env var `JAVA_HOME=/usr/share/opensearch/jdk`, but maybe this can be fixed in the image or in the plugin?

**Comment by MichaelRoosz** [comment]
Should I create a PR for this? 1.0.0 release is coming soon.

**Comment by peterzhuamazon** [comment]
Seems like AdoptOpenJDK installation does not add the JAVA_HOME to profile.
We have identify a fix now and will apply it in the next release.
Thanks.

**Comment by peterzhuamazon** [comment]
Add fix PR.

**Comment by cebor** [comment]
This issue is still in version 1.1.0!

**Comment by peterzhuamazon** [comment]
> This issue is still in version 1.1.0!

Please give detailed description of what is the issues so we can take a look @cebor 😄

**Comment by cebor** [comment]
> > This issue is still in version 1.1.0!
> 
> Please give detailed description of what is the issues so we can take a look @cebor 😄

`JAVA_HOME` env var is not set, and so its not possible to run `securityadmin.sh` out of the box.

**Comment by peterzhuamazon** [comment]
> > > This issue is still in version 1.1.0!
> > 
> > 
> > Please give detailed description of what is the issues so we can take a look @cebor 😄
> 
> `JAVA_HOME` env var is not set, and so its not possible to run `securityadmin.sh` out of the box.
> 
> Issues is also described by the author above. ;-)

Can you show your full step on how to produce this?
I just checked and java home is set on my side.
Thanks.

**Comment by cebor** [comment]
Steps to reproduce:

```bash
# start container
docker run --name ostest --rm -e "discovery.type=single-node" opensearchproject/opensearch:1.1.0

# run securityadmin.sh
docker exec -it ostest bash -c "cd plugins/opensearch-security/tools && ./securityadmin.sh -cd ../securityconfig/ -icl -nhnv -cacert ../../../config/root-ca.pem -cert ../../../config/kirk.pem -key ../../../config/kirk-key.pem"
```

**Comment by JSkier21** [comment]
Also have this issue. Running in Podman, OS1.1.0 JAVA_HOME is blank, can't run those tools either.

**Comment by peterzhuamazon** [comment]
This @MichaelRoosz @JSkier21 
Seems like /etc/profile, /etc/profile.d are both working on Bash, while default Bounce Shell only works with ~/.profile.

I have setup the ENV directly in dockerfile this time, seems working: https://github.com/opensearch-project/opensearch-build/pull/944

```

$ docker exec -it ostest bash -c "cd plugins/opensearch-security/tools && ./securityadmin.sh -cd ../securityconfig/ -icl -nhnv -cacert ../../../config/root-ca.pem -cert ../../../config/kirk.pem -key ../../../config/kirk-key.pem"
Security Admin v7
Will connect to localhost:9300 ... done
Connected as CN=kirk,OU=client,O=client,L=test,C=de
OpenSearch Version: 1.1.0
OpenSearch Security Version: 1.1.0.0
Contacting opensearch cluster 'opensearch' and wait for YELLOW clusterstate ...
Clustername: docker-cluster
Clusterstate: GREEN
Number of nodes: 1
Number of data nodes: 1
.opendistro_security index already exists, so we do not need to create one.
Populate config from /usr/share/opensearch/plugins/opensearch-security/securityconfig
Will update '_doc/config' with ../securityconfig/config.yml
   SUCC: Configuration for 'config' created or updated
Will update '_doc/roles' with ../securityconfig/roles.yml
   SUCC: Configuration for 'roles' created or updated
Will update '_doc/rolesmapping' with ../securityconfig/roles_mapping.yml
   SUCC: Configuration for 'rolesmapping' created or updated
Will update '_doc/internalusers' with ../securityconfig/internal_users.yml
   SUCC: Configuration for 'internalusers' created or updated
Will update '_doc/actiongroups' with ../securityconfig/action_groups.yml
   SUCC: Configuration for 'actiongroups' created or updated
Will update '_doc/tenants' with ../securityconfig/tenants.yml
   SUCC: Configuration for 'tenants' created or updated
Will update '_doc/nodesdn' with ../securityconfig/nodes_dn.yml
   SUCC: Configuration for 'nodesdn' created or updated
Will update '_doc/whitelist' with ../securityconfig/whitelist.yml
   SUCC: Configuration for 'whitelist' created or updated
Will update '_doc/audit' with ../securityconfig/audit.yml
   SUCC: Configuration for 'audit' created or updated
Done with success
```

```

$ docker exec -it ostest bash -c "env"
HOSTNAME=ac1f16b539e0
TERM=xterm
LD_LIBRARY_PATH=:/usr/share/opensearch/plugins/opensearch-knn/knnlib
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/share/opensearch/jdk/bin
PWD=/usr/share/opensearch
JAVA_HOME=/usr/share/opensearch/jdk
discovery.type=single-node
SHLVL=1
HOME=/usr/share/opensearch
_=/usr/bin/env
```
