### ISSUE TITLE
Support plugin specific opensearch.yml settings for local_test_cluster 

### ISSUE THREAD

**Issue by setiah** [opensearch-project/opensearch-build#493]
The LocalTestCluster should support plugin specific opensearch settings during the local test cluster bootup. These are required for running tests on plugins. For example, this tool (which was used earlier) had a bunch of additional settings required for integration tests that were added as part of cluster setup https://github.com/opensearch-project/opensearch-build/blob/main/tools/standard-test/deploy_single_tar_cluster.sh.

**Comment by peternied** [comment]
@setiah Please validation and acceptance criteria to this issue

Do we need to clone all of the logic from the referenced script - can we run that script in place of updating LocalTestCluster or is more work need?

**Comment by setiah** [comment]
I'm not sure what you mean by validation and acceptance criteria. 

The issue is simple. We spin up a local test cluster for running integration tests [here](https://github.com/opensearch-project/opensearch-build/blob/3a6dbae708c05d64bf066a4556adb18a4183bf4e/bundle-workflow/src/test_workflow/integ_test/local_test_cluster.py#L32). It misses some opensearch.yml settings that are required by integration tests for "some" plugins, e.g. [see](https://github.com/opensearch-project/opensearch-build/blob/main/tools/standard-test/deploy_single_tar_cluster.sh#L105-L122). We need to add those so the local test cluster is created with those settings. 

Short term fix - add this setting irrespective of plugin type as was the case for the legacy bundle-integ-test job.
Right fix - Add these settings based on the component type being tested as these are requirements can be specific to a component
