### ISSUE TITLE
[Enhancement] Migrate rpm-validation signature check functions to distribution-validation workflow

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#4968]
Hi,

We used to have a pure groovy check for rpm-validation, focused on these:
* RPM signature validation
* RPM installation/runtime validation.
https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/rpm-validation/rpm-validation.jenkinsfile

The second part is already part of the distribution-validation, we want to migrate the 1st part to python code as well.

Thanks.

**Comment by prudhvigodithi** [comment]
[Triage]
Moving forward the the https://github.com/opensearch-project/opensearch-build/tree/main/src/validation_workflow workflow should be source of truth for all the validations.

**Comment by Divyaasm** [comment]
Rpm metadata and signature validation migrated to python workflow. Pending clean up of the existing rpm-validation jenkins job.

**Comment by Divyaasm** [comment]
Removed rpm-validation job status from dashboards
