### ISSUE TITLE
Remove `integtest.sh` from all plugin repos

### ISSUE THREAD

**Issue by setiah** [opensearch-project/opensearch-build#497]
The [integtest.sh](https://github.com/opensearch-project/opensearch-build/blob/main/bundle-workflow/scripts/default/integtest.sh) tool contains the logic to run integration tests for a plugin. This logic is mostly common across most plugins, so it has been moved to `opensearch-build` repo. Thus it can be removed from the individual plugin repos.
However, if a plugin requires some custom logic to run integtests, which the standard tool doesn't provide, they can continue maintaining this integtest.sh in their own repo. In this case, when the integration tests are run, if a plugin has a integtest.sh tool in their repo, it gets precedence over the standard default integtest.sh in the `opensearch-build` repo. This precedence order logic is defined in ScriptFinder [here](https://github.com/opensearch-project/opensearch-build/blob/84f2fa1cf15abe314aee62dbd2cb39bf2c9bb65f/bundle-workflow/src/paths/script_finder.py#L65) 

Action items:

Raise PRs on all plugin repos and remove integtest.sh 
- [ ] index-management
- [ ] anomaly-detection,
- [ ] alerting
- [ ] asynchronous-search
- [ ] k-NN

Changes will need to be backported into 1.x branches if such exist, too.

**Comment by dblock** [comment]
I took the liberty to make PRs in all plugin repos that had an integtest.sh file using meta, see https://github.com/opensearch-project/opensearch-plugins/pull/80/files.

**Comment by dblock** [comment]
- https://github.com/opensearch-project/anomaly-detection/pull/220
- https://github.com/opensearch-project/sql/pull/213
- https://github.com/opensearch-project/alerting/pull/181
- https://github.com/opensearch-project/k-NN/pull/101

**Comment by dblock** [comment]
Okay, this time it's ready.

I used #574: 

```
./bundle-workflow/checkout.sh manifests/1.1.0/opensearch-1.1.0.yml
cd /tmp/tmpco2jldpf
$ find . -name integtest.sh
```
