### ISSUE TITLE
[On-boarding]: opensearch-system-templates

### ISSUE THREAD

**Issue by mgodwan** [opensearch-project/opensearch-build#4986]
### What is the name of your plugin?

opensearch-system-templates

### What is the link to your GitHub repo?

https://github.com/opensearch-project/opensearch-system-templates/

### Targeted release version

2.17

### Does the plugin require documentation?

Yes
https://github.com/opensearch-project/documentation-website/issues/8145

### What type of the plugin are we on-boarding?

OpenSearch plugin

### Did you read the on-boarding document?

Yes

### Does this plugin has all the necessary automated tests?

Yes, Integration tests have been added

### Have you completed the required reviews including Security reviews, UX reviews?

Yes

### Have you on-boarded automated security scanning for the GitHub repo associated with this plugin?

Mend checks are enabled on the repo

**Comment by gaiksaya** [comment]
Closing this issue as plugin is released in 2.17.0 distribution.
Thanks!
