### ISSUE TITLE
[BUG] Artifact distribution naming is not consistent with OpenSearch/plugins

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/opensearch-build#50]
**Describe the bug**
CPU architectures are named `x86_64` and `aarch64` in OpenSearch, where as rest of the plugins use `x64` and `arm64`.
Also platform for MacOS has different naming conventions, OpenSearch/Dashboards use `darwin` and the plugins use `macos`.

- [x] CPU architecture - Done PR opensearch-project/OpenSearch#612 
- [ ] MacOS Platform

**Comment by bbarani** [comment]
saratvemulapalli@, what's the status of this issue? Can you mention that one item that requires attention?

**Comment by saratvemulapalli** [comment]
@bbarani we have taken care of the CPU architecture and it is unified across all the repositories.
For macos, the representation is different in OpenSearch/Dashboards (darwin) vs plugins (macos). 

We should close down what it should be, depending on which either plugins have to change or OpenSearch/Dashboards will change.

**Comment by mch2** [comment]
@dblock Yes arm64 and x64 build are run in parallel and are tagged appropriately.  MacOS is not yet set up.

**Comment by peternied** [comment]
This will be looked into when we do the mac release.

**Comment by gaiksaya** [comment]
[Triage] We will work on it when we start supporting macos. Closing this for now.

**Comment by saratvemulapalli** [comment]
> [Triage] We will work on it when we start supporting macos. Closing this for now.

Makes sense, but how would you track it, if the issue is closed?
Do we already have a meta issue for macos builds?

**Comment by gaiksaya** [comment]
> > [Triage] We will work on it when we start supporting macos. Closing this for now.
> 
> Makes sense, but how would you track it, if the issue is closed? Do we already have a meta issue for macos builds?

Yes we do https://github.com/opensearch-project/opensearch-build/issues/38
