### ISSUE TITLE
[Enhancement]: Docker instances yield two deprecation warnings related to cgroup

### ISSUE THREAD

**Issue by CarterPape** [opensearch-project/opensearch-build#5000]
### Describe the bug

On startup, Docker instances of OpenSearch Dashboards will throw deprecation warnings about `cpu.cgroup.path.override` and `cpuacct.cgroup.path.override`, unless the user has overridden the default entrypoint scripts.

### To reproduce

Launch a vanilla Docker image of OpenSearch Dashboards with the following:

```sh
docker pull opensearchproject/opensearch-dashboards:latest
docker run -it -p 5601:5601  --name opensearch-dashboard opensearchproject/opensearch-dashboards:latest
```

The dashboard will fail to connect to the cluster, but the deprecation warning gets thrown before this. Even when properly configured with `docker-compose.yml` and connected to a cluster, the dashboard will throw the deprecation warnings because the deprecated settings are set in the Docker entrypoint script (e.g. `docker/release/config/opensearch-dashboards/opensearch-dashboards-docker-entrypoint-default.x.sh`).

### Expected behavior

No deprecation warning expected.

### Host / Environment

Latest Docker image located at https://hub.docker.com/r/opensearchproject/opensearch-dashboards
(build date 2024-08-15T20:09:22Z)

### Relevant log output

```shell
opensearch-dashboards  | {"type":"log","@timestamp":"2024-09-06T02:17:39Z","tags":["warning","config","deprecation"],"pid":1,"message":"\"cpu.cgroup.path.override\" is deprecated and has been replaced by \"ops.cGroupOverrides.cpuPath\""}
opensearch-dashboards  | {"type":"log","@timestamp":"2024-09-06T02:17:39Z","tags":["warning","config","deprecation"],"pid":1,"message":"\"cpuacct.cgroup.path.override\" is deprecated and has been replaced by \"ops.cGroupOverrides.cpuAcctPath\""}
```

**Comment by prudhvigodithi** [comment]
[Triage]
Need to update the opensearch-dashboards-docker-entrypoint https://github.com/opensearch-project/opensearch-build/blob/main/docker/release/config/opensearch-dashboards/opensearch-dashboards-docker-entrypoint-2.x.sh file to remove the deprecated flags with the supported ones. @ashwin-pc can you please add some more details here is it safe to completely remove the deprecated flags ?
Thanks 
@peterzhuamazon

**Comment by prudhvigodithi** [comment]
Adding @AMoo-Miki @kavilla.

**Comment by AMoo-Miki** [comment]
@prudhvigodithi OSD [uses](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/dev/build/tasks/os_packages/docker_generator/resources/bin/opensearch-dashboards-docker#L198) `ops.cGroupOverrides.cpuPath` and `ops.cGroupOverrides.cpuAcctPath`. This seems to predate the forking of OSD and as such it should be safe to replace.

**Comment by prudhvigodithi** [comment]
Got it thanks Miki, adding @peterzhuamazon @getsaurabh02.

**Comment by peterzhuamazon** [comment]
Thanks @AMoo-Miki ,

I will go ahead and do a replacement and ready for 2.18.

Thanks.
