### ISSUE TITLE
Add opensearch-test role and its trust relationships to Cloudformation template

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/opensearch-build#501]
**Is your feature request related to a problem? Please describe.**
opensearch-test role being used by Jenkins platform does have the policies defined in cloudformation. 

**Describe the solution you'd like**
Add all the policies to the template to ensure they are codified.

This is required for the test system to be production ready.

**Comment by peternied** [comment]
[Triage] This has been completed https://github.com/opensearch-project/opensearch-build/pull/496
