### ISSUE TITLE
[Bug]: `typed-ast` dependency has been archived for Python 3.8+

### ISSUE THREAD

**Issue by phvalguima** [opensearch-project/opensearch-build#5054]
### Describe the bug

Following the comments upstream, `typed-ast` package has been archived:
* https://pypi.org/project/typed-ast/

And both Debian and Ubuntu are removing `python3-typed-ast` from their repos:
* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1051802
* https://launchpad.net/ubuntu/+source/python3-typed-ast/+publishinghistory

The overall recommendation is to move forward to use standard lib's `ast` module instead for Python 3.8+. Is there any reason we still need this legacy dependency?

### To reproduce

--

**Comment by gaiksaya** [comment]
[Triage] Thank you for opening the issue @phvalguima 
Looks like its is recommended to use `ast` 
```
 The ast module of Python 3.8+ supports all features of typed_ast. typed_ast does not support parsing code that uses syntax introduced in Python 3.8 onwards. We recommend using ast on Python 3.8 or above.
```

**Comment by peterzhuamazon** [comment]
The original usage of this package comes from this PR by @prudhvigodithi :
* https://github.com/opensearch-project/opensearch-build/pull/2438

**Comment by peterzhuamazon** [comment]
Judging by the code I dont see this is being used anywhere tho.

Also mypy and pytest both pass:

Success: no issues found in 415 source files

938 passed, 4 warnings in 168.43s (0:02:48)

**Comment by peterzhuamazon** [comment]
Sending a PR:
* https://github.com/opensearch-project/opensearch-build/pull/5058

Also ask @prudhvigodithi to take a look as I dont think it is actually used, can remove. Thanks.

**Comment by prudhvigodithi** [comment]
Coming from https://github.com/opensearch-project/opensearch-build/pull/2438/files#r945288056 I just added it back (since it was part of Pip lock file) which was removed, I will double check to see the dependency.
Thanks

**Comment by prudhvigodithi** [comment]
Coming from https://github.com/opensearch-project/opensearch-build/pull/5058 I have cloned the fork and ran `./release_notes.sh check manifests/2.17.0/opensearch-2.17.0.yml --date 2024-07-26`, it dint complain for `typed-ast` but failed for `idna`, after adding `idna = "~=3.10"` to PipFile it started to work.
@gaiksaya @peterzhuamazon

**Comment by gaiksaya** [comment]
Thanks! Else we can go with the recommendation to use `ast` just to be safe as to not break any functionality.

**Comment by peterzhuamazon** [comment]
> Thanks! Else we can go with the recommendation to use `ast` just to be safe as to not break any functionality (compile or runtime)

I dont think ast is a drop in replacement because we didnt call typed-ast at all. ast is a builtin for python 3.8 and up.

**Comment by peterzhuamazon** [comment]
> Coming from #5058 I have cloned the fork and ran `./release_notes.sh check manifests/2.17.0/opensearch-2.17.0.yml --date 2024-07-26`, it dint complain for `typed-ast` but failed for `idna`, after adding `idna = "~=3.10"` to PipFile it started to work. @gaiksaya @peterzhuamazon

Thanks, updated PR.
