### ISSUE TITLE
[Feature] Publish plugins SNAPSHOT artifacts (along with SNASPHOT distribution)

### ISSUE THREAD

**Issue by reta** [opensearch-project/opensearch-build#5096]
### Is your feature request related to a problem? Please describe

At the moment, we do not publish plugins SNAPSHOT artifacts but min distribution only (see please https://build.ci.opensearch.org/job/publish-opensearch-min-snapshots/). However, it becomes increasingly demanded to have plugins SNAPSHOT artifacts published as well.

### Describe the solution you'd like

Publish  plugins SNAPSHOT artifacts under S3 bucket `https://artifacts.opensearch.org/snapshots/plugins/ ` so OpenSearch tooling (`opensearch-plugin`, etc) could be used to install them for SNAPSHOT distributions.

### Describe alternatives you've considered

Publish ZIPs to Apache Maven but that would change completely the distribution model for releases and snapshots.

### Additional context

See please https://github.com/opensearch-project/OpenSearch/pull/16219

**Comment by reta** [comment]
CC @prudhvigodithi

**Comment by prudhvigodithi** [comment]
We have been pushing the created core-plugins already to https://ci.opensearch.org.

Example:
https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/3.0.0/latest/linux/x64/tar/builds/opensearch/core-plugins/analysis-icu-3.0.0.zip 

https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/3.0.0/latest/linux/x64/rpm/builds/opensearch/core-plugins/analysis-icu-3.0.0.zip 

https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/3.0.0/latest/linux/x64/deb/builds/opensearch/core-plugins/analysis-icu-3.0.0.zip 

and we do the same for arm64

@peterzhuamazon @cwperks @reta can we just the leverage this ? :)

Thank you

**Comment by reta** [comment]
> @peterzhuamazon @cwperks @reta can we just the leverage this ? :)

So this is somewhat inconsistent: all this 3 URLs point to the same plugin (at least they should) because the distributions of the plugins does not depend on the OpenSearch packaging. We could leverage that, indeed, but looks more like a workaround, not a solution.

**Comment by peterzhuamazon** [comment]
At the moment we just let every distribution build the native plugins zip, but when release we only release x64/tar version.

**Comment by peterzhuamazon** [comment]
So that we do not need to change the workflow too much.

**Comment by dblock** [comment]
Will this address my problem in https://github.com/opensearch-project/opensearch-api-specification/pull/610?

I am using the 3.0 docker build and need to install one of the optional plugins. 

Normal docker reference:

```
FROM opensearchstaging/opensearch:2.18.0@sha256:f311da085b968663fadf041bafc78b24dc21556f0726e625caf3560f7323a020

# attempt to install the plugin here
RUN ./bin/opensearch-plugin install https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/2.18.0/10380/linux/x64/tar/builds/opensearch/core-plugins/analysis-phonenumber-2.18.0.zip
```

The above example is problematic because (it doesn't work), but I also need to manually match the version to the docker image SHA somehow.

**Comment by reta** [comment]
> Will this address my problem in [opensearch-project/opensearch-api-specification#610](https://github.com/opensearch-project/opensearch-api-specification/pull/610)?

It will @dblock

**Comment by peterzhuamazon** [comment]
After some talk on the triage meeting I fully understand what @reta is talking about.

Similar to:
https://artifacts.opensearch.org/snapshots/core/opensearch/3.0.0-SNAPSHOT/<>.tar.gz

Do a:
https://artifacts.opensearch.org/snapshots/plugins/opensearch/3.0.0-SNAPSHOT/<>.zip

We can start this with opensearch first, as I just checked we havent done any core snapshot for OSD core on artifacts.opensearch.org for a long time.


Thanks.

**Comment by Divyaasm** [comment]
Acceptance criteria:
Publish native plugins along side the core snapshot -> 
https://artifacts.opensearch.org/snapshots/core/opensearch/3.0.0-SNAPSHOT/<>.tar.gz

**Comment by peterzhuamazon** [comment]
We also need to add the checksum files alongside the native plugin zips.
Probably need to use the same folder structure as the release ones.

**Comment by peterzhuamazon** [comment]
@reta if we put the snapshot native plugins zips on s3, I assume you can directly run `opensearch-plugin install <>`? Or do we need to make changes in core to make it happen.

**Comment by reta** [comment]
> Hi @reta if we put the snapshot native plugins zips on s3, I assume you can directly run `opensearch-plugin install <>`? Or do we need to make changes in core to make it happen.

Thanks @peterzhuamazon, we only need to know the location, if it is different from the released versions fe

**Comment by peterzhuamazon** [comment]
After offline sync, we will use this folder structure:
```
https://ci.opensearch.org/ci/dbc/snapshots/plugins/analysis-icu/2.10.0-SNAPSHOT/analysis-icu-2.10.0-SNAPSHOT.zip
```

**Comment by peterzhuamazon** [comment]
PRs:
* https://github.com/opensearch-project/opensearch-build-libraries/pull/556

**Comment by peterzhuamazon** [comment]
Hi @reta confirms 2.19.0-SNAPSHOT is up with core plugins
https://build.ci.opensearch.org/job/publish-opensearch-min-snapshots/1947/console

3.0.0-SNAPSHOT still in progress here: https://build.ci.opensearch.org/job/publish-opensearch-min-snapshots/1948/console

Thanks.

**Comment by reta** [comment]
Thanks @peterzhuamazon , we have one more issue to clarify, for official plugins we also sign them and publish signature, it seems like we don't do this for snapshots?

```
/opensearch-2.19.0-SNAPSHOT$ ./bin/opensearch-plugin install transport-reactor-netty4                                                                                                                                                                                                     [15/178]
-> Installing transport-reactor-netty4                                                                                                                                     
-> Downloading transport-reactor-netty4 from opensearch                                                                                                                    
[=================================================] 100%                                                                                                                   
-> Failed installing transport-reactor-netty4                                                                                                                              
-> Rolling back transport-reactor-netty4                                                                                                                                   
-> Rolled back transport-reactor-netty4                                                                                                                                    
Exception in thread "main" java.io.IOException: Server returned HTTP response code: 403 for URL: https://artifacts.opensearch.org/snapshots/plugins/transport-reactor-netty4/2.19.0-SNAPSHOT/transport-reactor-netty4-2.19.0-SNAPSHOT.zip.sig
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:2013)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1614)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:223)
        at java.base/java.net.URL.openStream(URL.java:1325)                                                                                                                
        at org.opensearch.plugins.InstallPluginCommand.urlOpenStream(InstallPluginCommand.java:490)
        at org.opensearch.plugins.InstallPluginCommand.verifySignature(InstallPluginCommand.java:630)
        at org.opensearch.plugins.InstallPluginCommand.downloadAndValidate(InstallPluginCommand.java:608)
        at org.opensearch.plugins.InstallPluginCommand.download(InstallPluginCommand.java:316)
        at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:271)
        at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:248)
        at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104)
        at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
        at org.opensearch.cli.MultiCommand.execute(MultiCommand.java:104)
        at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
        at org.opensearch.cli.Command.main(Command.java:101)
        at org.opensearch.plugins.PluginCli.main(PluginCli.java:60)

```

**Comment by peterzhuamazon** [comment]
> Thanks @peterzhuamazon , we have one more issue to clarify, for official plugins we also sign them and publish signature, it seems like we don't do this for snapshots?
> 
> ```
> /opensearch-2.19.0-SNAPSHOT$ ./bin/opensearch-plugin install transport-reactor-netty4                                                                                                                                                                                                     [15/178]
> -> Installing transport-reactor-netty4                                                                                                                                     
> -> Downloading transport-reactor-netty4 from opensearch                                                                                                                    
> [=================================================] 100%                                                                                                                   
> -> Failed installing transport-reactor-netty4                                                                                                                              
> -> Rolling back transport-reactor-netty4                                                                                                                                   
> -> Rolled back transport-reactor-netty4                                                                                                                                    
> Exception in thread "main" java.io.IOException: Server returned HTTP response code: 403 for URL: https://artifacts.opensearch.org/snapshots/plugins/transport-reactor-netty4/2.19.0-SNAPSHOT/transport-reactor-netty4-2.19.0-SNAPSHOT.zip.sig
>         at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:2013)
>         at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1614)
>         at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:223)
>         at java.base/java.net.URL.openStream(URL.java:1325)                                                                                                                
>         at org.opensearch.plugins.InstallPluginCommand.urlOpenStream(InstallPluginCommand.java:490)
>         at org.opensearch.plugins.InstallPluginCommand.verifySignature(InstallPluginCommand.java:630)
>         at org.opensearch.plugins.InstallPluginCommand.downloadAndValidate(InstallPluginCommand.java:608)
>         at org.opensearch.plugins.InstallPluginCommand.download(InstallPluginCommand.java:316)
>         at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:271)
>         at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:248)
>         at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104)
>         at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
>         at org.opensearch.cli.MultiCommand.execute(MultiCommand.java:104)
>         at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
>         at org.opensearch.cli.Command.main(Command.java:101)
>         at org.opensearch.plugins.PluginCli.main(PluginCli.java:60)
> ```

Yes we dont have signings for snapshots, on both plugins zips and min artifacts.
Do we need them in order to install?

**Comment by reta** [comment]
> Do we need them in order to install?

Could we do that? I think it will be helpful, or there are any drawbacks?

**Comment by peterzhuamazon** [comment]
> > Do we need them in order to install?
> 
> Could we do that? I think it will be helpful, or there are any drawbacks?

The existing min pipeline is not designed to have signing in mind, let me take a look on it today.

**Comment by peterzhuamazon** [comment]
Related OS PR that is pending due to this:
* https://github.com/opensearch-project/OpenSearch/pull/16581

**Comment by peterzhuamazon** [comment]
More PRs:
* https://github.com/opensearch-project/opensearch-build-libraries/pull/561

**Comment by peterzhuamazon** [comment]
New run:
* https://build.ci.opensearch.org/job/publish-opensearch-min-snapshots/1954/console
* https://build.ci.opensearch.org/job/publish-opensearch-min-snapshots/1955/console

**Comment by peterzhuamazon** [comment]
Needs to add gnupg to macos for signature verifications.
```
+ curl -sSL https://artifacts.opensearch.org/publickeys/opensearch.pgp

+ gpg --import -

<>: line 1: gpg: command not found

script returned exit code 127
```

**Comment by peterzhuamazon** [comment]
More more PRs:
*  Adding gnupg to the macos agents for signature verifications #503

**Comment by peterzhuamazon** [comment]
The above wont affect linux installation as that is already pushed.

**Comment by peterzhuamazon** [comment]
Weird I dont see the sig files for uploads.

**Comment by reta** [comment]
Yeah, me neither

**Comment by peterzhuamazon** [comment]
Out of no where the core-plugins location being null:
```
Running /var/jenkins/workspace/publish-opensearch-min-snapshots/src/run_sign.py null --sigtype .sig ...
```

**Comment by peterzhuamazon** [comment]
A re-run in test branch passed somehow, will just re-run production as I suspect just hiccups.

**Comment by peterzhuamazon** [comment]
Even worse, now the new macos agents cannot find pipenv, due to py39 not exist in macports?:
```

==> amazon-ebs.Jenkins-Agent-MacOS13-ARM64-Mac2M2proMetal-13.6.7-2024-11-08T09-08-06Z: Error: Port py39-python-install not found
    amazon-ebs.Jenkins-Agent-MacOS13-ARM64-Mac2M2proMetal-13.6.7-2024-11-08T09-08-06Z: Selecting 'python39' for 'python' failed: The specified group 'python' does not exist.
    amazon-ebs.Jenkins-Agent-MacOS13-ARM64-Mac2M2proMetal-13.6.7-2024-11-08T09-08-06Z: Selecting 'python39' for 'python3' failed: The specified group 'python3' does not exist.
```

**Comment by peterzhuamazon** [comment]
py39-python-install has been deleted as part of the macports:
https://ports.macports.org/port/py39-python-install/

**Comment by peterzhuamazon** [comment]
Even more PRs:
* https://github.com/opensearch-project/opensearch-ci/pull/504

**Comment by peterzhuamazon** [comment]
Seems like it is very random that var passed to signing will become `null`
```
Running /var/jenkins/workspace/publish-opensearch-min-snapshots/src/run_sign.py null --sigtype .sig ...
```

**Comment by peterzhuamazon** [comment]
On the side note windows takes forever to complete the signing.
I think we need to remove signing from normal artifacts now and only reserve for core plugins.

**Comment by peterzhuamazon** [comment]
Even Even more:
* https://github.com/opensearch-project/opensearch-build-libraries/pull/564

**Comment by peterzhuamazon** [comment]
One more PR:
* https://github.com/opensearch-project/opensearch-build/pull/5180

**Comment by peterzhuamazon** [comment]
I thinks this time it is publishing:
![Screenshot 2024-11-12 at 12 24 42 PM](https://github.com/user-attachments/assets/84dd7549-c8c6-44b5-b97b-15232e561ccd)

Hi @reta could you help confirm from your side on the installation? Thanks!

**Comment by reta** [comment]
> Hi @reta could you help confirm from your side on the installation? Thanks!

Works like a charm, @peterzhuamazon !

```
$ /home/opensearch-3.0.0-SNAPSHOT$ ./bin/opensearch-plugin install transport-nio
-> Installing transport-nio
-> Downloading transport-nio from opensearch
[=================================================] 100%   
-> Installed transport-nio with folder name transport-nio

```
