### ISSUE TITLE
[BUG] Fatal glibc error: CPU does not support x86-64-v2

### ISSUE THREAD

**Issue by 4d4ch4u32** [opensearch-project/opensearch-build#5120]
### Describe the bug

Docker image v2.17.x on GitLab CI is not working, it fails with the error `Fatal glibc error: CPU does not support x86-64-v2`.

### Related component

Build

### To Reproduce

Running OpenSearch as a service in a GitLab CI Job:

```yaml
job_name:
  services:
    - name: opensearchproject/opensearch:2.17.0
      alias: opensearch
      command: ["bash", "-c", "env 'OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m' 'discovery.type=single-node' 'cluster.name=opensearch' ./opensearch-docker-entrypoint.sh"]
```

### Expected behavior

OpenSearch is running in GitLab CI without errors.

### Additional Details

GitLab Log:

```
Running with gitlab-runner 17.4.0 (b92ee590)
  on cur-devtools-svr05 Jjtz6bvP, system ID: s_0c0e0a0e3[2](https://git.xxx.de/xxx/xxx-software/-/jobs/12494/viewer#L2)3c
Preparing the "docker" executor
Using Docker executor with image git.xxx.com:5050/dev-tools/glubuntu-php:latest-php-8.[3](https://git.xxx.de/xxx/xxx-software/-/jobs/12494/viewer#L3) ...
Starting service mysql:8.0.28...
Using locally found image version due to "if-not-present" pull policy
Using docker image sha256:f2ad9f23df82a3e5efabd157[4](https://git.xxx.de/xxx/xxx-software/-/jobs/12494/viewer#L4)b862a94c0657c73a6179efec07d5cf9ae5a307f for mysql:8.0.28 with digest mysql@sha256:fc77d54cacef90ad3d7[5](https://git.xxx.de/xxx/xxx-software/-/jobs/12494/viewer#L5)964837fad0f2a9a368b69e7d799665a3f4e90e[6](https://git.xxx.de/xxx/xxx-software/-/jobs/12494/viewer#L6)00c2d ...
Starting service opensearchproject/opensearch:2.17.0...
Using locally found image version due to "if-not-present" pull policy
Using docker image sha256:884999f8490ec8441c36[7](https://git.xxx.de/xxx/xxx-software/-/jobs/12494/viewer#L7)53687f3a5902c4b686c2b31d8eecf90c35e4e1f0c85 for opensearchproject/opensearch:2.17.0 with digest opensearchproject/opensearch@sha256:7b9517dff561f54456fad947f11820fa595a340fd1034fc63d57b77f724b3f8f ...
Waiting for services to be up and running (timeout 30 seconds)...
*** WARNING: Service runner-jjtz6bvp-project-2-concurrent-0-b[8](https://git.xxx.de/xxx/xxx-software/-/jobs/12494/viewer#L8)29bc9726b952fa-opensearchproject__opensearch-1 probably didn't start properly.
Health check error:
start service container: Error response from daemon: Cannot link to a non running container: /runner-jjtz6bvp-project-2-concurrent-0-b82[9](https://git.xxx.de/xxx/xxx-software/-/jobs/12494/viewer#L9)bc9726b952fa-opensearchproject__opensearch-1 AS /runner-jjtz6bvp-project-2-concurrent-0-b829bc9726b952fa-opensearchproject__opensearch-1-wait-for-service/service (services.go:215:0s)
Service container logs:
2024-[10](https://git.xxx.de/xxx/xxx-software/-/jobs/12494/viewer#L10)-15T14:54:11.507195573Z Fatal glibc error: CPU does not support x86-64-v2
*********
```
```

**Comment by Divyaasm** [comment]
@peterzhuamazon , can you please take a look and add your thoughts?

**Comment by Divyaasm** [comment]
@4d4ch4u32 , can you add details about underlying OS

**Comment by 4d4ch4u32** [comment]
> @4d4ch4u32 , can you add details about underlying OS

This container is used in the GitLab CI: https://git.var-lab.com/dev-tools/glubuntu-php (it's a Ubuntu with pre-installed packages, see the Dockerfile in the repository for details)

But I'm not sure if the GitLab services are also running inside the "Job-Image" which is defined for the GitLab CI-job. It possible that the services are injected with another magic made by GitLab devs...

**Comment by 4d4ch4u32** [comment]
> Moving this to the correct repo. This needs debugging @4d4ch4u32, please help.

Which information do you need?

**Comment by peterzhuamazon** [comment]
Redundant of https://github.com/opensearch-project/opensearch-build/issues/4580.

This is more related to the AL2023 more than the build repo.

I think @4d4ch4u32 should check the issues on https://github.com/amazonlinux/container-images or https://github.com/amazonlinux/amazon-linux-2023/.

Thanks.

**Comment by 4d4ch4u32** [comment]
Now that I've realised my stupidity, I'm not surprised that it works well. With an appropriate CPU. 😆 

The CPU of the host I used is not supporting `x86-64-v2` 🤷‍♂️ 😿
