### ISSUE TITLE
[BUG] Opensearch 2.17.0 Fails to start on Ubuntu 22.04.5 LTS (Jammy Jellyfish)

### ISSUE THREAD

**Issue by servebeer** [opensearch-project/opensearch-build#5121]
### Describe the bug

I have a "fresh" install of Ubuntu 22.04.5 LTS (Jammy Jellyfish), openjdk version "11.0.24",  and installed Opensearch 2.17.0 (amd64) via APT. It installed with no errors but when I try to start it via "sudo systemctl start opensearch" it results in this error:

× opensearch.service - OpenSearch
     Loaded: loaded (/lib/systemd/system/opensearch.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Mon 2024-10-21 17:30:43 UTC; 9min ago
       Docs: https://opensearch.org/
    Process: 628 ExecStart=/usr/share/opensearch/bin/systemd-entrypoint -p ${PID_DIR}/opensearch.pid --quiet (code=exited, status=1/FAILURE)
   Main PID: 628 (code=exited, status=1/FAILURE)
        CPU: 19.110s

Oct 21 17:30:43 graylog systemd-entrypoint[889]: Error: A fatal exception has occurred. Program will exit.
Oct 21 17:30:43 graylog systemd-entrypoint[889]:         at org.opensearch.tools.launchers.JvmErgonomics.flagsFinal(JvmErgonomics.java:125)
Oct 21 17:30:43 graylog systemd-entrypoint[889]:         at org.opensearch.tools.launchers.JvmErgonomics.finalJvmOptions(JvmErgonomics.java:87)
Oct 21 17:30:43 graylog systemd-entrypoint[889]:         at org.opensearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:70)
Oct 21 17:30:43 graylog systemd-entrypoint[889]:         at org.opensearch.tools.launchers.JvmOptionsParser.jvmOptions(JvmOptionsParser.java:150)
Oct 21 17:30:43 graylog systemd-entrypoint[889]:         at org.opensearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:108)
Oct 21 17:30:43 graylog systemd[1]: opensearch.service: Main process exited, code=exited, status=1/FAILURE
Oct 21 17:30:43 graylog systemd[1]: opensearch.service: Failed with result 'exit-code'.
Oct 21 17:30:43 graylog systemd[1]: Failed to start OpenSearch.
Oct 21 17:30:43 graylog systemd[1]: opensearch.service: Consumed 19.110s CPU time.

### Related component

Build

### To Reproduce

1. > sudo systemctl status opensearch
2. Output matched error listed above

### Expected behavior

Opensearch should start and run w/o any errors.

### Additional Details

**Plugins**
none

**Screenshots**
![Screenshot 2024-10-21 at 12 44 05](https://github.com/user-attachments/assets/486dae31-1c0b-4aaf-b761-28ce78d6be80)

**Host/Environment (please complete the following information):**
 - OS: Ubuntu Jammy Jellyfish
 - Version 22.04.5 LTS

**Additional context**
none

**Comment by peterzhuamazon** [comment]
I dont have an environment for 22.04.5 for now.
Tho I also want to mention you dont need to install JDK11.
As the deb pkg is already including a copy of jdk.

**Comment by peterzhuamazon** [comment]
No issues:
```
$ cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.5 LTS"
PRETTY_NAME="Ubuntu 22.04.5 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.5 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

```
$ sudo env OPENSEARCH_INITIAL_ADMIN_PASSWORD=myStrongPassword123! apt-get install opensearch
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  opensearch
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 906 MB of archives.
After this operation, 1179 MB of additional disk space will be used.
Get:1 https://artifacts.opensearch.org/releases/bundle/opensearch/2.x/apt stable/main amd64 opensearch amd64 2.17.1 [906 MB]
Fetched 906 MB in 24s (37.3 MB/s)
Selecting previously unselected package opensearch.
(Reading database ... 96382 files and directories currently installed.)
Preparing to unpack .../opensearch_2.17.1_amd64.deb ...
Running OpenSearch Pre-Installation Script
Unpacking opensearch (2.17.1) ...
Setting up opensearch (2.17.1) ...
Running OpenSearch Post-Installation Script
### NOT starting on installation, please execute the following statements to configure opensearch service to start automatically using systemd
 sudo systemctl daemon-reload
 sudo systemctl enable opensearch.service
### You can start opensearch service by executing
 sudo systemctl start opensearch.service
### Create opensearch demo certificates in /etc/opensearch/
 See demo certs creation log in /var/log/opensearch/install_demo_configuration.log
### Breaking change in packaging since 2.13.0
 In 2.13.0 and later releases of OpenSearch, we have changed the permissions associated with access to installed files
 If you are configuring tools that require read access to the OpenSearch configuration files, we recommend you add the user that runs these tools to the 'opensearch' group
 For more information, see https://github.com/opensearch-project/opensearch-build/pull/4043
```

**Comment by peterzhuamazon** [comment]
```
$ sudo systemctl start opensearch
$ curl https://localhost:9200 -ku admin:myStrongPassword123!
{
  "name" : "ip-172-31-43-194",
  "cluster_name" : "opensearch",
  "cluster_uuid" : "DT1wTm-kQi-sgc00WU2Cjg",
  "version" : {
    "distribution" : "opensearch",
    "number" : "2.17.1",
    "build_type" : "deb",
    "build_hash" : "1893d20797e30110e5877170e44d42275ce5951e",
    "build_date" : "2024-09-26T21:59:47.005429436Z",
    "build_snapshot" : false,
    "lucene_version" : "9.11.1",
    "minimum_wire_compatibility_version" : "7.10.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "The OpenSearch Project: https://opensearch.org/"
}
```

**Comment by peterzhuamazon** [comment]
Test 2.17.0, cleanup /etc/opensearch beforehand:
```
$ sudo env OPENSEARCH_INITIAL_ADMIN_PASSWORD=myStrongPassword123! apt-get install opensearch=2.17.0
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  opensearch
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 906 MB of archives.
After this operation, 1179 MB of additional disk space will be used.
Get:1 https://artifacts.opensearch.org/releases/bundle/opensearch/2.x/apt stable/main amd64 opensearch amd64 2.17.0 [906 MB]
Fetched 906 MB in 17s (52.0 MB/s)
Selecting previously unselected package opensearch.
(Reading database ... 96382 files and directories currently installed.)
Preparing to unpack .../opensearch_2.17.0_amd64.deb ...
Running OpenSearch Pre-Installation Script
Unpacking opensearch (2.17.0) ...
Setting up opensearch (2.17.0) ...
Running OpenSearch Post-Installation Script
### NOT starting on installation, please execute the following statements to configure opensearch service to start automatically using systemd
 sudo systemctl daemon-reload
 sudo systemctl enable opensearch.service
### You can start opensearch service by executing
 sudo systemctl start opensearch.service
### Create opensearch demo certificates in /etc/opensearch/
 See demo certs creation log in /var/log/opensearch/install_demo_configuration.log
### Breaking change in packaging since 2.13.0
 In 2.13.0 and later releases of OpenSearch, we have changed the permissions associated with access to installed files
 If you are configuring tools that require read access to the OpenSearch configuration files, we recommend you add the user that runs these tools to the 'opensearch' group
 For more information, see https://github.com/opensearch-project/opensearch-build/pull/4043

```
```
$ sudo systemctl start opensearch
$ curl https://localhost:9200 -ku admin:myStrongPassword123!
{
  "name" : "ip-172-31-43-194",
  "cluster_name" : "opensearch",
  "cluster_uuid" : "iYQGjo7PQ9mMSmYa3uujmg",
  "version" : {
    "distribution" : "opensearch",
    "number" : "2.17.0",
    "build_type" : "deb",
    "build_hash" : "8586481dc99b1740ca3c7c966aee15ad0fc7b412",
    "build_date" : "2024-09-13T01:04:13.864000718Z",
    "build_snapshot" : false,
    "lucene_version" : "9.11.1",
    "minimum_wire_compatibility_version" : "7.10.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "The OpenSearch Project: https://opensearch.org/"
}
```

**Comment by peterzhuamazon** [comment]
No issues with the default settings, able to install both 2.17.0 and 2.17.1 on Ubuntu 22.04.5 and start cluster without issues.

Thanks.

**Comment by peterzhuamazon** [comment]
> I dont have an environment for 22.04.5 for now. Tho I also want to mention you dont need to install JDK11. As the deb pkg is already including a copy of jdk.

I believe that is the cause due to the demo script is using `JAVA_HOME` as higher order than the bundled JDK.
https://github.com/opensearch-project/security/blob/2.x/tools/install_demo_configuration.sh#L34-L57

User has 11 as JAVA_HOME and bundled JDK is 21.
I vaguely remember there is mismatch before where user has to use JDK21 for the demo scripts to pass.

**Comment by servebeer** [comment]
@dbwiddis you are correct about the error coming from  /var/log/opensearch/install_demo_configuration.log. I cleaned up a bunch of artifacts from previous install attempts and ran the install again with: sudo -E env OPENSEARCH_INITIAL_ADMIN_PASSWORD=StrongPassword apt install opensearch. This time, I got a different error: Running OpenSearch Post-Installation Script
ERROR: Something went wrong during demo configuration installation. Please see the logs in /var/log/opensearch/install_demo_configuration.log
dpkg: error processing package opensearch (--configure):
 installed opensearch package post-installation script subprocess returned error exit status 1
Processing triggers for libc-bin (2.35-0ubuntu3.8) ...
Errors were encountered while processing:
 opensearch

I think I am going to start from scratch and rebuild the virtual host.

**Comment by servebeer** [comment]
I appreciate everyone's input! I tried again after a fresh install of Ububtu Server, and this time it installed w/o any issues... go figure.
