### ISSUE TITLE
linux/arm64 Image Published to Dockerhub

### ISSUE THREAD

**Issue by Conklin-Spencer-bah** [opensearch-project/opensearch-build#5159]
### Is your feature request related to a problem? Please describe

linux/arm64 can be built but today it is not published on dockerhub. 

### Describe the solution you'd like

linux/arm64 to exist on Dockerhub.

### Describe alternatives you've considered

Building my own linux/arm64 image and publishing it.

**Comment by gaiksaya** [comment]
Hi @Conklin-Spencer-bah,

The docker images published on dockerhub contain both the architectures. The image automatically detects the underlying architecture and pulls the right layer accoordingly.
See https://hub.docker.com/r/opensearchproject/opensearch/tags

<img width="686" alt="image" src="https://github.com/user-attachments/assets/69773af4-6d70-4a70-87e3-ed2318ca15bf">

**Comment by gaiksaya** [comment]
Closing this issue. Please re-open if you still have questions. 
Thanks!
