### ISSUE TITLE
Make compiled plugin artifacts available

### ISSUE THREAD

**Issue by adaisley** [opensearch-project/opensearch-build#517]
**Is your feature request related to a problem? Please describe.**
We're trying to build our own version of OpenSource Dashboards 1.0.0 from source with a few minor UI changes and we're encountering a bit of an issue in that trying to run `/usr/share/opensearch-dashboards/bin/opensearch-dashboards-plugin --allow-root install securityDashboards` gives us an error saying a valid URL was not specified.

I asked on the forums if anyone could provide the correct link to this so that we might download it and bring it into our Dockerfile, then run the install step on the .zip. According to @searchymcsearchface, compiled plugin artifacts aren't yet available?

**Describe the solution you'd like**
Make compiled plugin artifacts available on https://artifacts.opensearch.org/downloads/kibana-plugins/

**Describe alternatives you've considered**
I haven't got too many alternatives here I'm afraid.

**Additional context**
https://discuss.opendistrocommunity.dev/t/errors-when-installing-plugins-in-opensearch-dashboards/7030

**Comment by dblock** [comment]
Aside of making .zips available, we have work in progress in https://github.com/opensearch-project/opensearch-build/pull/435 to get the OpenSearch Dashboards build working top-down in a repeatable way similarly to what we [did for OpenSearch](https://github.com/opensearch-project/opensearch-build/tree/main/bundle-workflow#readme).

**Comment by dblock** [comment]
@adaisley You can now build OpenSearch Dashboards from the source using this repo.

```
./build.sh manifests/1.1.0/opensearch-dashboards-1.1.0.yml
./assemble.sh artifacts/manifest.yml
```

**Comment by dblock** [comment]
Note that plugins seem to be working around this by publishing a .zip on GitHub, and are recommending to use those (e.g. https://github.com/opensearch-project/cross-cluster-replication/issues/258), which isn't the same .zip that's included in the distribution with plugins. For one these aren't built in the same CI, and aren't signed.

**Comment by bbarani** [comment]
@adaisley, The plugin zips are available at ci.artifacts.org/... location and the exact location can be found inside the manifest.yml file inside the OpenSearch-Dashboards distribution.

Example:
https://ci.opensearch.org/ci/dbc/bundle-build-dashboards/1.2.4/512/linux/x64/builds/plugins/alertingDashboards-1.2.0.zip

**Comment by bbarani** [comment]
I am closing this issue as we are already publishing the compiled artifacts now. Please feel free to re-open this issue if this resolution doesn't address your issue.
