### ISSUE TITLE
Turn on DCO checks for all opensearch plugins

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/opensearch-build#53]
Just like OpenSearch/Dashboards plugins need to have DCO checks that block merges unless passed.

**Comment by dblock** [comment]
I also had opened https://github.com/opensearch-project/opensearch-build/issues/51 for all repos in the org.

**Comment by ylwu-amzn** [comment]
To confirm, plugin team doesn't need to anything? The DCO check here means this https://github.com/marketplace/actions/dco-check?

**Comment by dblock** [comment]
I don't think so @ylwu-amzn, the DCO check in OpenSearch doesn't look like this one.

<img width="939" alt="Screen Shot 2021-06-24 at 12 03 45 PM" src="https://user-images.githubusercontent.com/542335/123296002-40d0f480-d4e4-11eb-92e4-3786a85592fb.png">

**Comment by dblock** [comment]
There's a dup for enabling this in infra.
