### ISSUE TITLE
securityadmin.sh can't find JAVA_HOME in docker container

### ISSUE THREAD

**Issue by aponb** [opensearch-project/opensearch-build#54]
**Describe the bug**
When setting customized certificates in a dockerized cluster, you need to call securityadmin.sh from ./plugins/opensearch-security/tools in a running container. The script securityadmin.sh is unable to find JAVA_HOME. After setting exporting JAVA_HOME like
`export JAVA_HOME=/usr/share/opensearch/jdk`
securityadmin.sh can be called without problems.
There should be a JAVA_HOME Variable set in the docker container

**Comment by dblock** [comment]
Same or different than https://github.com/opensearch-project/opensearch-build/issues/49?

**Comment by MichaelRoosz** [comment]
yes, same

**Comment by dblock** [comment]
Closing as dup of #49

**Comment by peterzhuamazon** [comment]
This has been resolved in #95 Thanks.
