### ISSUE TITLE
bundle-workflow does not build security component on MacOS

### ISSUE THREAD

**Issue by zelinh** [opensearch-project/opensearch-build#543]
**Describe the bug**
bundle-build failed to build on security plugin on MacOS
These commands 
https://github.com/opensearch-project/opensearch-build/blob/b37270feab5c70b2980e716172f479f006610d5e/bundle-workflow/scripts/components/security/build.sh#L66-L69
will give error:
`sed: 1: "plugin-descriptor.prope ...": extra characters at the end of p command`

**To Reproduce**
Run `./bundle-workflow/build.sh manifests/1.1.0/opensearch-1.1.0.yml --component security --snapshot` on MacOS

**Expected behavior**
build successfully 

**Plugins**
Security

**Host/Environment (please complete the following information):**
 - OS: MacOS
 - Version 11.5.2

**Comment by dblock** [comment]
Looks like https://stackoverflow.com/questions/16745988/sed-command-with-i-option-in-place-editing-works-fine-on-ubuntu-but-not-mac may be a solution. There are other hits on Google.

**Comment by zelinh** [comment]
@dblock Yes adding an empty string like 
`sed -i '' "s/\(^opensearch\.version=\).*\$/\1${OPENSEARCH_RELEASE}/" plugin-descriptor.properties` works on mac but doesn't work on Linux. 
It will give this 
`+ sed -i '' 's/\(^opensearch\.version=\).*$/\11.1.0/' plugin-descriptor.properties`
`sed: can't read s/\(^opensearch\.version=\).*$/\11.1.0/: No such file or directory`

 it seems `sed` has different command setting for Linux and MacOS environment.
