### ISSUE TITLE
[Infra] Setup lucene snapshot maven repository

### ISSUE THREAD

**Issue by nknize** [opensearch-project/opensearch-build#554]
A S3 bucket is needed to store snapshot builds of lucene for periodically updating development branches with evolving lucene features. This is supported in [RepositoriesSetupPlugin.java](https://github.com/opensearch-project/OpenSearch/blob/main/buildSrc/src/main/java/org/opensearch/gradle/RepositoriesSetupPlugin.java#L95) and needs to be changed to an OpenSearch S3 bucket.  Builds and publishing artifacts do not need to be automated. Committers and Maintainers should have write access to be able to manually push and update the codebase with updated snapshot builds.

**Comment by abhinavGupta16** [comment]
[triage] We are not working on it
