### ISSUE TITLE
Create and use new vagrant boxes for packaging tests

### ISSUE THREAD

**Issue by adnapibar** [opensearch-project/opensearch-build#555]
Packaging tests use Vagrant boxes from elastic (https://app.vagrantup.com/elastic).

We may need to create new boxes and replace the existing ones in tests.

**Comment by saratvemulapalli** [comment]
@adnapibar moved the issue to opensearch-build. Could you lay down what configurations are needed and for what tests?

**Comment by gaiksaya** [comment]
@adnapibar Can you add more details about requirements and what you are looking for?
Thanks!

**Comment by adnapibar** [comment]
@gaiksaya The packaging tests are used to test a distribution for a particular OS.
https://github.com/opensearch-project/OpenSearch/blob/main/TESTING.md#testing-packaging

These tests use Vagrant to setup virtual machines to install and test the corresponding distribution. The VM boxes used are currently provided by elastic. This issue is created to remove the dependency on elastic managed boxes. Here is the Vagrant config
https://github.com/opensearch-project/OpenSearch/blob/main/Vagrantfile

**Comment by abhinavGupta16** [comment]
We don't have plans to support Vagrant. If we need to consider Vagrant, please create a proposal and justification.
