### ISSUE TITLE
Document that plugin CI needs to always build -SNAPSHOT

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#561]
### Is your feature request related to a problem? Please describe

In https://github.com/opensearch-project/anomaly-detection/pull/214 a plugin is switching from SNAPSHOT to non-SNAPSHOT. This is expected in "normal" release workflow of a component, but we will never be using CI builds because we now build the monolith from the top.

### Describe the solution you'd like

Document that plugins should just keep building -SNAPSHOT in their CI.

### Describe alternatives you've considered

Let plugins me.

**Comment by peterzhuamazon** [comment]
Need someone to update the above instructions to https://github.com/opensearch-project/opensearch-build/blob/main/ONBOARDING.md

**Comment by bbarani** [comment]
Closing this ticket as I see that the updates have been already made to [on-boarding document ](https://github.com/opensearch-project/opensearch-build/blob/main/ONBOARDING.md)to use -SNAPSHOT in plugin CI. Feel free to re-open this issue in case if any gaps.
