### ISSUE TITLE
OpenSearch Data-prepper docker image release 1.0.0 for OpenSearch

### ISSUE THREAD

**Issue by chenqi0805** [opensearch-project/opensearch-build#57]
**Is your feature request related to a problem? Please describe.**
version 1.0 docker image release on 06/15

**Describe the solution you'd like**
https://github.com/opensearch-project/data-prepper/tree/1.0/release/docker

**Describe alternatives you've considered**

**Additional context**

**Comment by peterzhuamazon** [comment]
I am going to build the docker image with `1.0` branch and push to staging bucket.
This release only consist of docker and TARBALL is not included.

**Comment by peterzhuamazon** [comment]
The image has been pushed to staging, @chenqi0805 please check:
```
docker pull opensearchstaging/data-prepper:1.0.0
```

**Comment by chenqi0805** [comment]
@peterzhuamazon Validated the staging image. Ready to push to production.

**Comment by peterzhuamazon** [comment]
The image has been pushed to production, @chenqi0805 please check:
```
docker pull opensearchproject/data-prepper:1.0.0
```

**Comment by chenqi0805** [comment]
verified and close
