### ISSUE TITLE
Automate the whitesource scans

### ISSUE THREAD

**Issue by bbarani** [opensearch-project/opensearch-build#578]
### Is your feature request related to a problem? Please describe

We need an automated way to scan our code and surface the CVE's. Currently there is no automated mechanism to scan and surface the CVE's corresponding to a particular repository under OpenSearch organization

### Describe the solution you'd like

An automated scan using Whitesource scanning tool is scheduled to track and surface the CVE's on periodic basis.

Basically fix: https://github.com/opensearch-project/opensearch-build/blob/opensearch-1.0.0/.github/workflows/check-vulnerability-whitesource.yml

### Describe alternatives you've considered

Manually verifying the CVE against public vulnerability database

### Tasks

- [x] #613
- [x] #614
- [x] #615
- [ ] Whitesource scanner implementation in opensearch-build
- [ ] Scanning is automatically triggered, with alarm if it does not run or has failures

**Comment by dblock** [comment]
Is it viable to replace Whitesource with Dependabot and if yes/no why/not?

**Comment by bbarani** [comment]
We can enable Dependabot as an additional scanning tool but we cannot replace Whitesource with it due to the below limitations,

**Here are the high level benefits of using Whitesource (Notes from vendor).**
Dependabot only works with GitHub. WhiteSource works with GitHub and other repos, your build tools, IDEs, and other CI\CD tools. Here is a screenshot of examples of some of our integrations.Not listed here are integrations with IDEs (ItelliJ, Eclipse, Visual Studio, and VS Code) and browsers (Chrome and Edge).

> WhiteSource can enforce policies to proactively prevent open source libraries with security or compliance issues from making into your builds. WhiteSource can fail build pipelines when it identifies a library in the repo used with the build that violates a security or license policy defined in WhiteSource.

> Enterprise reports related to inventory\Bill Of Materials, Security Vulnerabilities, License due diligence, and project risk

> Reliability: Our library matching algorithms are primarily based on SHA1 hashes, which are 100% reliable as methods to match a file in your scan to a file in our inventory. In addition, our team of security researchers validates each and every security vulnerability identified by our machine learning algorithms before they are published to our vulnerability database, Together, our matching algorithms and validation of security vulnerabilities reduce the presence of false positive and false negative security alerts.

> Completeness: WhiteSource supports over 200 programming languages, over a dozen package managers, and has the most comprehensive inventory of open source libraries and their security vulnerabilities. Our vulnerability database is comprised of vulnerability reports sourced from more than 20 security advisory services.  

Overall, the long term plan is to use
CodeQL  for Static code scanning
Dependabot for automated regular scans
Whitesource  for security + license scans

We are also looking to purchase license to Whitesource Bolt for automated PR scans.

**Comment by peterzhuamazon** [comment]
More development: https://github.com/opensearch-project/opensearch-build/pull/1411#issuecomment-1000945335

**Comment by zelinh** [comment]
Closing this issue since we already implemented our backup offline WhiteSource scan running on Jenkins once a day here https://github.com/opensearch-project/opensearch-build/pull/1411
