### ISSUE TITLE
Release OpenSearch Java Client 0.1.0 in maven repository

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/opensearch-build#585]
Repo: https://github.com/opensearch-project/opensearch-java
Branch: 0.1

**Comment by dblock** [comment]
Are we still trying to do this?

**Comment by peterzhuamazon** [comment]
I dont think it is right to push to https://aws.oss.sonatype.org/content/repositories/snapshots
as that is the repository for snapshots not staging.

See publish/stage-maven-release.sh for more information as that is the script to push to the correct location.

**Comment by gaiksaya** [comment]
They want to publish snapshots too. Cron-job that will keep running on `main` branch so that developers can use it.

**Comment by dblock** [comment]
We want a standalone snapshot build so that developers can contribute to the library and immediately use their changes.

**Comment by VijayanB** [comment]
1 & 2 Action items for component owner is completed.
New branch for release: https://github.com/opensearch-project/opensearch-java/tree/0.1
Daily Snapshot branch: https://github.com/opensearch-project/opensearch-java/tree/main

To produce 0.1.0-SNAPSHOT as version and qualifier
```
./gradlew publishToMavenLocal
```

To produce 0.1.0 as version
```
export VERSION=0.1.0
./gradlew publishToMavenLocal
```

**Comment by dblock** [comment]
I would love that. The whole reason we didn't use GHA to drive bundle workflow was credentials.

**Comment by gaiksaya** [comment]
[Discussed offline]

Looks like there was some concrete discussion for not using GHA considering storing and maintaining credentials. 
Going ahead with jenkins workflow. Current plan is to have JenkinsFile stored under folder in https://github.com/opensearch-project/opensearch-build/tree/main/jenkins for each component.
I'll work with @VijayanB to create those workflows.
Thanks!

**Comment by VijayanB** [comment]
@dblock @peternied 
Since #743 seems unnecessary, i could think of three possible options
Option 1) ( no dependencies to opensearch-build )
a.  Create jenkins job which checks out opensearch-java 
b.  publish snapshot to maven local
c. push to https://aws.oss.sonatype.org/content/repositories/snapshots

Option 2) follow similar to opensearch snapshot publications
a. Create manifest file similar to https://github.com/opensearch-project/opensearch-build/blob/main/manifests/1.1.0/opensearch-1.1.0.yml#L13 
b. Create jenkins file and have only snapshot task similar to https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/opensearch/Jenkinsfile#L26
c. Create a jenkins job to execute above jenkins file.


Option 3) Independent of manifest
a. Create a new python program "run_publish_maven_local", which accepts github ref, branch, and execute ./gradlew publishToMavenlocal as subprocess command.
b. Create a Jenkins file  "jenkins/opensearch-java/Jenkins" similar to https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/opensearch/Jenkinsfile#L26 but calls run_publish_maven_local.py

Do you see any other? if not we can decide which one seems reasonable for this task.

**Comment by gaiksaya** [comment]
🎉  Opensearch-java client is now available on maven central for customers to consume: https://repo1.maven.org/maven2/org/opensearch/client/opensearch-java/
