### ISSUE TITLE
OpenSearch Dashboards bundle builds all arch (only build the current OS arch)

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#592]
### Is your feature request related to a problem? Please describe

Bundle build supports specifying target arch based on the current system arch. Dashboards builds for all architectures at once. Reconcile this behavior.

```
 info [  opensearch-dashboards  ] Creating the archives for each platform
   │ info archiving /tmp/tmpv0k8rhd0/OpenSearch-Dashboards/build/opensearch-dashboards-1.1.0-linux-x64 to /tmp/tmpv0k8rhd0/OpenSearch-Dashboards/target/opensearch-dashboards-1.1.0-linux-x64.tar.gz
   │ info archiving /tmp/tmpv0k8rhd0/OpenSearch-Dashboards/build/opensearch-dashboards-1.1.0-linux-arm64 to /tmp/tmpv0k8rhd0/OpenSearch-Dashboards/target/opensearch-dashboards-1.1.0-linux-arm64.tar.gz
   │ info archiving /tmp/tmpv0k8rhd0/OpenSearch-Dashboards/build/opensearch-dashboards-1.1.0-darwin-x64 to /tmp/tmpv0k8rhd0/OpenSearch-Dashboards/target/opensearch-dashboards-1.1.0-darwin-x64.tar.gz
   │ info archiving /tmp/tmpv0k8rhd0/OpenSearch-Dashboards/build/opensearch-dashboards-1.1.0-windows-x64 to /tmp/tmpv0k8rhd0/OpenSearch-Dashboards/target/opensearch-dashboards-1.1.0-windows-x64.zip
```

### Describe the solution you'd like

Just like OpenSearch, only build the current arch. We don't release artifacts outside of a short list of architectures, and even if the build supports it, I think it makes sense to split these up. Parallelize builds on different architectures in Jenkinsfile.

**Comment by kavilla** [comment]
This should be possible now since this just got implemented: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/795.

But it was only backported to `1.x`, can we neglect 1.0.0 so we don't have to introduce conditional code for only one branch.

**Comment by dblock** [comment]
> This should be possible now since this just got implemented: [opensearch-project/OpenSearch-Dashboards#795](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/795).
> 
> But it was only backported to `1.x`, can we neglect 1.0.0 so we don't have to introduce conditional code for only one branch.

Yes, we're only building 1.1.0 here so no need to backport anything.

**Comment by dblock** [comment]
Looks like opensearch-project/OpenSearch-Dashboards#795 wasn't backported to 1.1. If we can still do that, great, otherwise we can either 1) add a different build.sh into Dashboards main vs. 1.1 branch 2) just move forward and stop trying to build dashboards 1.1.0 and go for 1.2.0 instead.
