### ISSUE TITLE
[Bug] Remove psutil as a dependency in Pipfile

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#597]
### Describe the bug

I am not sure why `pstuil` is being added as dependency in bundle-workflow.
https://github.com/opensearch-project/opensearch-build/blob/main/bundle-workflow/Pipfile#L24
It is not supported in many places.

1. It does not support arm64 arch listed here: https://github.com/giampaolo/psutil/issues/1966
2. It does not support Windows on cygwin: https://github.com/giampaolo/psutil/issues/82 (issue opened in 2010 and a contributor attempt to work on it but PR closed later)

It is only used right here for test:
https://github.com/opensearch-project/opensearch-build/blob/927d87b59b369f00b2a366c4f29ffb0d7ff3d342/bundle-workflow/src/test_workflow/integ_test/local_test_cluster.py

@setiah @gaiksaya can you chime in for more information on why we need this?
Or we can have a path on how to resolve this later.

### To reproduce

See above.

**Comment by gaiksaya** [comment]
The issue was resolved by installting `python3-devel` on the host machine.
See https://github.com/opensearch-project/opensearch-build/issues/527 for more details.
It is used to grab the child processes id.

**Comment by peterzhuamazon** [comment]
It still does not work on windows.

**Comment by dblock** [comment]
> It still does not work on windows.

Many other things don't work on windows in our build AFAIK, I think we can fix it later.
