### ISSUE TITLE
on-board opensearch-cli

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/opensearch-build#62]
**Is your feature request related to a problem? Please describe.**
on-board opensearch-cli
**Describe the solution you'd like**
We should able to upload our artifacts from github actions, run integration tests, package artifact and available from download page.

**Describe alternatives you've considered**
NA

**Additional context**
This is similar to odfe-cli.

**Comment by bbarani** [comment]
opensearch-cli has been released and available for download at opensearch.org hence closing this issue.
