### ISSUE TITLE
Automated performance testing is enabled on bundle builds

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#622]
Performance tests are executed as part of the bundle build and the results are available for distribution

**Comment by peterzhuamazon** [comment]
Please associate this correct to the corresponding meta issue @peternied .

**Comment by zelinh** [comment]
Move it to Icebox since we will need more discussions on this.

**Comment by dblock** [comment]
Dup of https://github.com/opensearch-project/opensearch-build/issues/129
