### ISSUE TITLE
Generate TAR for both OpenSearch and Dashboards

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#623]
Generate TAR for both OpenSearch and Dashboards

**Comment by peterzhuamazon** [comment]
In Release Candidates:

https://artifacts.opensearch.org/release-candidates/bundle/opensearch-dashboards/1.1.0/opensearch-dashboards-1.1.0-linux-x64.tar.gz
https://artifacts.opensearch.org/release-candidates/bundle/opensearch-dashboards/1.1.0/opensearch-dashboards-1.1.0-linux-arm64.tar.gz

**Comment by peterzhuamazon** [comment]
> @peterzhuamazon for OpenSearch this should be the output from bundle-workflow. Are release notes something we’re missing in the assemble step? Anything else?

I am a bit confused @dblock this is tarball not release notes.

**Comment by dblock** [comment]
> > @peterzhuamazon for OpenSearch this should be the output from bundle-workflow. Are release notes something we’re missing in the assemble step? Anything else?
> 
> I am a bit confused @dblock this is tarball not release notes.

We're not including release notes in the tarball? Then ignore me.

**Comment by peterzhuamazon** [comment]
> > > @peterzhuamazon for OpenSearch this should be the output from bundle-workflow. Are release notes something we’re missing in the assemble step? Anything else?
> > 
> > 
> > I am a bit confused @dblock this is tarball not release notes.
> 
> We're not including release notes in the tarball? Then ignore me.

nope. It is only presented in the build repo and plugin repo.

**Comment by peterzhuamazon** [comment]
New build 20210929 17:00 PST, 306 build.

**Comment by peterzhuamazon** [comment]
New build 20210930.
