### ISSUE TITLE
[Docker Images] Images should be built and published by CI system 

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#628]
Today docker images that are used for build and testing are manually built and uploaded, this should be done automatically with a github action or a jenkins workflow.

Here is an example github action that we could use, https://github.com/marketplace/actions/build-and-push-docker-images.

**Comment by peterzhuamazon** [comment]
I can do this as LINUX now support buildx for both x64 and arm64, the thing is we need to run on Ubuntu as it is the only known version for now to support `binfmt-support` `qemu-user-static`.

**Comment by peternied** [comment]
@peterzhuamazon putting this into the product backlog and we can circle back to it, we might want to create a separate repo or a proposal

**Comment by peterzhuamazon** [comment]
We already start the automation in #801 so close this.

**Comment by peternied** [comment]
Lets close this when it is fully automated, documented and merged into main, it looks like the core changes are still in a [fork](https://github.com/peterzhuamazon/opensearch-build/tree/opensearch-docker-pipeline)
