### ISSUE TITLE
Add dashboards-reports to integTest automation

### ISSUE THREAD

**Issue by davidcui-amzn** [opensearch-project/opensearch-build#65]
Add integration with front-end `dashboards-reports` and back-end `reports-scheduler` for the `dashboards-reports` plugin. 

---
Command to run integration tests for `dashboards-reports` (front-end plugin):
```
yarn test
```
Prerequisites:
* OpenSearch sample data (ecommerce, flights, logs) must be installed

----
Command to run integration tests for back-end `reports-scheduler`: 
``` 
./gradlew integTest
```
Remote cluster:
```
./gradlew integTest -Dtests.rest.cluster=localhost:9200 -Dtests.cluster=localhost:9200
```

**Comment by davidcui-amzn** [comment]
> @davidcui-amzn how about secured cluster, seems like you provided test for cluster without security plugin.

For front-end `dashboards-reports`, we do not interact with the security dashboards plugin. For the backend `reports-scheduler`, the command will be 

```
./gradlew integTest -Dtests.rest.cluster=localhost:9200 -Dtests.cluster=localhost:9200 -Dhttps=true -Duser=admin -Dpassword=admin
```

**Comment by peterzhuamazon** [comment]
Resolved and reports is now in the cicd for auto integtests.
Thanks.
