### ISSUE TITLE
Improving Test Coverage for sign_workflow

### ISSUE THREAD

**Issue by Rishikesh1159** [opensearch-project/opensearch-build#650]
### Is your feature request related to a problem? Please describe

Currently the test Coverage for bundle-workflow/src/sign_workflow is 87.10%. I am trying to improve the test coverage score.

### Describe the solution you'd like

I am trying to improve the test coverage score from 87.10%. 
I am adding two unit test functions in bundle-workflow/tests/tests_sign_workflow/test_signer.py , to improve code coverage percent of bundle-workflow/src/sign_workflow .

### Additional context

<img width="1158" alt="Screen Shot 2021-09-29 at 11 23 06 AM" src="https://user-images.githubusercontent.com/62345295/135327187-5ba3ea57-7722-4170-a2d3-ffdcd135b597.png">

**Comment by dblock** [comment]
Closed this. No need to open issues if you're also opening a PR (almost) at the same time, just make the PR :)
