### ISSUE TITLE
Dockerhub Description for Data Prepper wrong?

### ISSUE THREAD

**Issue by gruselglatz** [opensearch-project/opensearch-build#67]
In the description you find this:

What is OpenSearch Data Prepper?

Data Prepper is a new component of OpenSearch that receives trace data from the OpenTelemetry collector, and aggregates, transforms, and normalizes it for analysis and visualization in **Kibana** 

But should it not be:

What is OpenSearch Data Prepper?

Data Prepper is a new component of OpenSearch that receives trace data from the OpenTelemetry collector, and aggregates, transforms, and normalizes it for analysis and visualization in **OpenSearch Dashboard**

**Comment by bbarani** [comment]
@gruselglatz Thanks for your comment. I have updated the description in Dockerhub now.
