### ISSUE TITLE
[Docker] Automate testing docker images for release

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/opensearch-build#689]
### Is your feature request related to a problem? Please describe

The docker images we produce for release are manually tested.
We should standardize and automate our test workflow to verify docker images as part of our release. 

### Describe the solution you'd like

Restructure our integration-test workflow to spin up cluster using a docker image as an option and run tests using the cluster.

**Comment by peterzhuamazon** [comment]
[Grooming] Close this issue in favor of this one: https://github.com/opensearch-project/opensearch-build/issues/1359
