### ISSUE TITLE
on-board beats

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/opensearch-build#69]
On board following beats
```
1.     packetbeat-oss
2.     heartbeat-oss
3.     auditbeat-oss
4.     journalbeat-oss
5.     filebeat-oss
6.     metricbeat-oss
```

**Comment by peterzhuamazon** [comment]
We already uploaded beats @peternied please assign this to the corresponding task.

**Comment by peternied** [comment]
@elfisher Please re-open if more work is need in this space - beats v7.12.1 are on artifacts.opensearch.org
