### ISSUE TITLE
Integrate performance testing into release workflow  

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#693]
### Is your feature request related to a problem? Please describe

Integrate performance testing workflow into https://github.com/opensearch-project/opensearch-build/blob/main/.github/ISSUE_TEMPLATE/release_template.md

### Describe the solution you'd like

Pre-requisites:

- [ ] Performance tests are run continuously 
- [ ] Test results are published for every bundle build
- [ ] Test results include delta between this build and previously released versions of OpenSearch
- [ ] Plugins have a way to do performance tests within a framework, similarly to backwards compatibility tests

We need a series of steps in the release template around performance tests. This issue should answer, what are those steps?

- [ ] Ensure that there are no performance regressions
- [ ] Ensure that the error rate is stable/comparable
- [ ] Publish/include a performance footprint summary, release notes?
- [ ] ... something else?

**Comment by dblock** [comment]
@bbarani Add your thoughts please?

**Comment by saratvemulapalli** [comment]
@dblock some of the answers to questions above would be taken care by https://github.com/opensearch-project/opensearch-build/issues/126. 
I would rather have granular issues created and link it to the meta issue to understand where we are on performance testing. 

 - Performance tests are run continuously -> https://github.com/opensearch-project/opensearch-build/issues/129
 - Test results are published for every bundle build -> https://github.com/opensearch-project/opensearch-build/issues/707
 - Test results include delta between this build and previously released versions of OpenSearch -> New Issue
 - Plugins have a way to do performance tests within a framework, similarly to backwards compatibility tests -> New Issue

**Comment by dblock** [comment]
This is a different cut of https://github.com/opensearch-project/opensearch-build/issues/126, closing as dup.
