### ISSUE TITLE
[Bug]: node.data, node.ingest, and node.master deprecation

### ISSUE THREAD

**Issue by elsif2** [opensearch-project/opensearch-build#694]
### Describe the bug

Upon starting v1.0.0, depreciation warnings are generated for the `node.data`, `node.ingest`, and `node.master` configuration options although they appear in the current [documentation](https://opensearch.org/docs/opensearch/cluster/#master-node).

```
{"type": "deprecation", "timestamp": "2021-10-05T11:26:37,811-07:00", "level": "DEPRECATION", "component": "o.o.d.c.s.Settings", "cluster.name": "T4", "node.name": "node1.0", "message": "[node.master] setting was deprecated in OpenSearch and will be removed in a future release! See the breaking changes documentation for the next major version." }
{"type": "deprecation", "timestamp": "2021-10-05T11:26:37,814-07:00", "level": "DEPRECATION", "component": "o.o.d.c.s.Settings", "cluster.name": "T4", "node.name": "node1.0", "message": "[node.data] setting was deprecated in OpenSearch and will be removed in a future release! See the breaking changes documentation for the next major version." }
{"type": "deprecation", "timestamp": "2021-10-05T11:26:37,814-07:00", "level": "DEPRECATION", "component": "o.o.d.c.s.Settings", "cluster.name": "T4", "node.name": "node1.0", "message": "[node.ingest] setting was deprecated in OpenSearch and will be removed in a future release! See the breaking changes documentation for the next major version." }
```

I did not see any mention of these in the [release notes](https://github.com/opensearch-project/opensearch-build/blob/main/release-notes/opensearch-release-notes-1.0.0.md) either.

### To reproduce

Define the following in the `opensearch.yml` file:

```
node.master: false
node.data: true
node.ingest: true
```

### Expected behavior

If these are in fact deprecated, the documentation should provide the replacement configuration options otherwise a warning should not be generated.

### Host / Environment

Ubuntu 18LTS

**Comment by peternied** [comment]
This issue is being tracked in the OpenSearch repository, see https://github.com/opensearch-project/OpenSearch/issues/1238 for the specifics
