### ISSUE TITLE
Request level logging during the tests

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#696]
There was problems during the no-security enabled test runs for both arm64 and x86, 100% failure rate from the perf testing system.  After inspecting the hosts we were not able to find any errors or request logs that indicated the source of the issue. 

When we deploy a OpenSearch cluster to run performance tests we should have request logs saved on disk so we can correlate any aberrate behavior to what the testing system saw.

**Comment by peterzhuamazon** [comment]
Need follow up with the OpenSearch Core Team.
Initially we were told to set log4j settings to record logs, but not showing.
We need to have info level (or more detailed) logs in order to get information on the failures.

**Comment by bbarani** [comment]
Closing this issue as we can view the logs by modifying the log4j settings.

**Comment by peternied** [comment]
@bbarani Has this been documented, or has the test cluster setup been updated to get this information?  I don't see and PRs related to this issue

**Comment by bbarani** [comment]
@saratvemulapalli @anasalkouz Can you please let us know if you have documented the settings to print debug logs in case of any issues?

**Comment by saratvemulapalli** [comment]
@peternied @bbarani yes we do document this in multiple places[1][2].

[1] https://opensearch.org/docs/latest/opensearch/logs/
[2] https://github.com/opensearch-project/OpenSearch/blob/main/TESTING.md#miscellaneous

Let us know if you think this is not good enough.

**Comment by peternied** [comment]
I don't think this issue should be closed as the performance tests would need to be updated to add additional logging to catch these failures, or has this already happened @bbarani ?

**Comment by bbarani** [comment]
@peternied We will not enable debugging by default during performance test runs rather would enable it when we find any discrepancies. I am good with closing this issue as long as we have option to enable it for debugging purpose.
