### ISSUE TITLE
[Performance] Need to validate the 1.1.0 without security performance tests

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#697]
We should retrigger this test process for both x86 and arm64 with lots of debugging logging including #696 as well as other logging that would be useful to root cause and resolve any issues running these tests.

After getting successful runs back we should make fixes for any issues encountered.

**Comment by peterzhuamazon** [comment]
We didnt apply the mentor test again due to time limits, and @skkosuri-amzn and I have proceed with a series of simple tests to prove that mensor test is having issues.
