### ISSUE TITLE
Check maven central distribution requirements 

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#700]
Follow up from https://github.com/opensearch-project/opensearch-build/issues/699

At the end of the release process we were surprised by some checks that failed, we should make sure these checks can be enforced before we are in the middle of a release or at least have a best effort to minimize these issues.

Add a check next to https://github.com/opensearch-project/opensearch-build/tree/main/bundle-workflow/src/build_workflow/opensearch that verifies that:

- [ ] Every .jar came with a corresponding .md5 and .sha1 signature file.
- [ ] Every artifact comes with a corresponding sources jar.
- [ ] Every artifact comes with a corresponding javadoc jar.
- [ ] POM contains project name, description, URL, license information, SCM URL, and developer information.

**Comment by dblock** [comment]
Add a check next to https://github.com/opensearch-project/opensearch-build/tree/main/bundle-workflow/src/build_workflow/opensearch that verifies that every .jar came with a corresponding .md5 and .sha1 signature file.

**Comment by prudhvigodithi** [comment]
Hey @peternied with existing automation every published jar  has .md5, .sha1, sha256, sha512 and .asc extension
https://repo1.maven.org/maven2/org/opensearch/opensearch/1.3.2/

it has sources and javadoc jar as well
https://repo1.maven.org/maven2/org/opensearch/opensearch-job-scheduler/2.0.1.0/

Pom extensions for jar and zip are customizable 
Example https://github.com/opensearch-project/job-scheduler/blob/main/build.gradle#L86-L117
https://github.com/opensearch-project/job-scheduler/blob/main/build.gradle#L119-L128

Thank you

**Comment by prudhvigodithi** [comment]
@peternied the requirements are already deep in the automation, I'm fine to have an extra workflow/checks to ensure those are there, but if a team want to have a new POM XML extension there are chances the workflow has to be extended, also not always sources and javadoc jar are required, its up to the team (to remove the the shadow jars), I'm open for a discussion on this, Adding @dblock @bbarani @peterzhuamazon @gaiksaya @zelinh

**Comment by bbarani** [comment]
Closing this issue as it will be tracked via https://github.com/opensearch-project/opensearch-build/issues/2928
