### ISSUE TITLE
Document publishing to maven central

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#701]
### Describe the bug

We have a Jenkins workflow that pulls artifacts from S3 based on build number, then signs all the jars, then uses stage maven release script to send to Sonatype. 

We publish snapshots daily in a Jenkins workflow.

We have some manual process to push a button to publish the maven artifacts to maven central after release.

All of this needs to be documented from README.

**Comment by bbarani** [comment]
Closing this issue as this will be tracked as part of this https://github.com/opensearch-project/opensearch-build/pull/1459/files and https://github.com/opensearch-project/opensearch-build/issues/1257
