### ISSUE TITLE
Create artifacts for rest-api-spec

### ISSUE THREAD

**Issue by naveentatikonda** [opensearch-project/opensearch-build#702]
We are trying to fetch the updates in apis from the rest-api-spec into OpenSearch-Specification and many clients(like opensearch - js). We are doing it manually as the artifacts are not yet created. Can we create the artifacts for rest-api-spec like "rest-resources-zip-7.15.1.zip" in https://artifacts-api.elastic.co/v1/versions/7.15    

Here is an example to show where it is being used:
https://github.com/opensearch-project/opensearch-js/blob/main/scripts/download-artifacts.js#L117

They just added the url something similar to how elasticsearch added it but it needs to be updated once the url is finalized.

**Comment by zelinh** [comment]
[Triage] We need more information from core team and @naveentatikonda on this one.

**Comment by naveentatikonda** [comment]
@zelinh This is on hold right now.

**Comment by gaiksaya** [comment]
@naveentatikonda Closing this now.  Please create new one with specific requirements and usecase from your end.
Thanks!
