### ISSUE TITLE
Publish performance test results for every build 

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/opensearch-build#707]
Add support to publish performance test results.

**Comment by kotwanikunal** [comment]
I will follow up on this once we have the basic infrastructure for #129 in place.

**Comment by kotwanikunal** [comment]
Currently we have nightly performance tests running as a part of #129. The results are published to the artifact bucket post completion ([Example here](https://ci.opensearch.org/ci/dbc/perf-test/2.0.0/3810/linux/x64/tar/test-results/perf-test/with-security/1af44c88-35f4-439d-a897-27416dd95d13.html)). 
The results are unfortunately not directly discoverable. 
We have plans to publish the results publicly using the [opensearch.org](https://opensearch.org/) website in the future.

**Comment by bbarani** [comment]
We are tracking the dashboard creation for viewing performance test runs [here](https://github.com/opensearch-project/opensearch-build/issues/2297)

**Comment by bbarani** [comment]
You can access the published performance test results using the below html url pattern,

```
https://ci.opensearch.org/ci/dbc/perf-test/<version>/<distribution-build-number>/linux/x64/tar/test-results/<job-build-number>/perf-test/<with/without-security>/perf-test.html
```

More info: https://github.com/opensearch-project/opensearch-build/tree/main/src/test_workflow#perftest-job
