### ISSUE TITLE
Docker Image from Main branch

### ISSUE THREAD

**Issue by seriouz** [opensearch-project/opensearch-build#708]
Have you considered to provide a Docker image that's nightly builded from the Main branch? You could name it `opensearch:unstable` or something like that.
We are using massively Docker in our company and to get a preview of what's going into the next version and to test the features would be great.

**Comment by saratvemulapalli** [comment]
Tagging @bbarani for thoughts on this.

**Comment by peternied** [comment]
[Triage] The distribution builds are meant to be of a higher quality since much effort needs to be built on top of them, we will be closing out this issue, but if you have a compelling use case please reopen.
