### ISSUE TITLE
[Bug]: stage-maven-release.sh process leaves artifacts in the upload directory

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#712]
After running stage-maven-release.sh a file is created that will automatically be uploaded if the script runs a second time, the upload process should be idempotent to prevent pollution of the environment or for a retry of the process.

Filename: 
```
{SONATYPE_PROFILE_ID}.properties
```
File Contents:
```
#Generated by org.sonatype.plugins:nexus-staging-maven-plugin:1.6.5
#Thu Oct 07 02:31:22 UTC 2021
stagingRepository.id=orgopensearch-1012
stagingRepository.url=https\://aws.oss.sonatype.org\:443/content/repositories/orgopensearch-1012
stagingRepository.profileId={SONATYPE_PROFILE_ID}
stagingRepository.managed=false
```

See [AbstractStagingDeployStrategy.java](https://github.com/sonatype/nexus-maven-plugins/blob/master/staging/maven-plugin/src/main/java/org/sonatype/nexus/maven/staging/deploy/strategy/AbstractStagingDeployStrategy.java#L154) from `org.sonatype.plugins:nexus-staging-maven-plugin` where this is documented.  It does not look like it can be disabled or the file location altered.

**Comment by bbarani** [comment]
Closing this issue as we are noticing this issue anymore now.
