### ISSUE TITLE
 Weekly Community Engagement on 2021/10/12 - 2021/10/25

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#720]
We are engaging with the community on a weekly basis.
This is for 2021/10/12 - 2021/10/25

**Comment by peterzhuamazon** [comment]
https://github.com/opensearch-project/ansible-playbook/pull/2

**Comment by dblock** [comment]
@peterzhuamazon Curious, what's this issue? ;)

**Comment by peterzhuamazon** [comment]
https://github.com/opensearch-project/helm-charts/pull/81
