### ISSUE TITLE
Automate listing dependencies and their versions for each dependency 

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#722]
### Is your feature request related to a problem? Please describe

Every time someone reports a CVE in a dependent component we have several challenges:

1. Find all versions of OpenSearch and OpenSearch Dashboards that contains the dependency <= the vulnerable version.
2. Determine whether the dependency is runtime or build time.
3. Determine whether the CVE affects the product(s) by understanding how the dependency is used.
2. Figure out which component brought in the vulnerable dependency.
3. Upgrade the dependency.
4. Evaluate the severity and backport, as needed.

If we can generate a table of dependent versions for every release in some automated way, we can make these and related tasks easy. 

### Describe the solution you'd like

Produce an easy to use dependency map during the build process for OpenSearch and OpenSearch Dashboards.

**Comment by bbarani** [comment]
Closing this issue as its being tracked by @AMoo-Miki
