### ISSUE TITLE
Document building end-to-end bundle

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#73]
**Is your feature request related to a problem? Please describe.**
Users want to be able to reproduce building the end-to-end OpenSearch and OpenSearch dashboard bundle, and are [asking](https://discuss.opendistrocommunity.dev/t/how-bundles-from-https-artifacts-opensearch-org-was-created/6547/3) how we did it for 1.0 (manually).

- [ ] Do #20 for all components
- [ ] Document access controls of how a central account can fetch components to make the bundle
- [ ] Open source scripts and jobs that generate the bundle assembly
- [ ] Sign bundle
- [ ] Include a manifest that has all the SHAs of commits of every component bundled
- [ ] Publish bundle to artifacts.opensearch.org

**Comment by dblock** [comment]
Note https://discuss.opendistrocommunity.dev/t/how-to-build-opensearch-including-all-plugins/6274 asking for the same.

**Comment by peternied** [comment]
This should be done during the face-lift of the repository https://github.com/opensearch-project/opensearch-build/issues/448

**Comment by peternied** [comment]
[Triage] This is covered in the repo readme.
