### ISSUE TITLE
Split, simplify and move usage of CI runners between OpenSearch and OpenSearch Dashboards

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#732]
### Is your feature request related to a problem? Please describe

CI runners are the kitchen sink of everything to support OpenSearch and OpenSearch Dashboards. We *will* run into conflicts sooner than later. We will also want to build multiple versions at the same time which will make it difficult to track what's what. For example, in `centos7-x64-arm64-jdk14-node10.24.1-cypress6.9.1-20211005`, OpenSearch doesn't need node or cypress, while OpenSearch Dashboards doesn't need Java. Then, we're going to lower the Java version for OpenSearch, so we'll need to use multiple images.

### Describe the solution you'd like

- [ ] Split images, e.g. `centos7-x64-arm64-jdk14` and `centos7-x64-arm64-node10.24.1-cypress6.9.1`.
- [ ] Move which build image to use into the build manifest so that it sticks to the version being built and not to the Jenkinsfile.

**Comment by reta** [comment]
We certainly could do that, pre-baking the images has the benefits that we don't need to download and install JDKs every time (+ `gradle` as well), so in general - builds are faster and more stable.

**Comment by peterzhuamazon** [comment]
> @peterzhuamazon thanks a lot for merging the PRs, could you please ping us when the new images are available so we could alter the build pipelines to use the per-branch JDK specifications, thank you!

Will ping.

**Comment by peterzhuamazon** [comment]
https://hub.docker.com/r/opensearchstaging/ci-runner/tags?page=1&ordering=last_updated

**Comment by gaiksaya** [comment]
How did we build these images? Manually or is that automated?
