### ISSUE TITLE
Automate deployment of Test Clusters

### ISSUE THREAD

**Issue by abhinavGupta16** [opensearch-project/opensearch-build#735]
### Is your feature request related to a problem? Please describe

- [ ] We need to automate the deployment of all test clusters (listed below) automatically. 

> - x64 _no-security_
> - x64 _with-security_
> - arm64 _no-security_
> - arm64 _with-security_

**Note:** This can be done in parallel to save time.

- [ ] Send notification emails to the required users informing them about the release so we don't have to update the slack channel

**Optional (Next steps) :**
- [ ] Integrate it to run automatically after bundle artifacts are online

### Describe the solution you'd like

Setup a tool/jar/script that can deploy the 4 test clusters in parallel

### Acceptance Criteria
After I have run the tool, the test clusters should be deployed for all the different hardware and a notification email should be sent to the required users automatically.

**Comment by peterzhuamazon** [comment]
[Grooming] We have asked the plugin owners to use tarball and docker images to build their own cluster at this point. We are not going to provide test cluster per release session anymore.
