### ISSUE TITLE
[Docker] Create a process for creating CI docker images

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#779]
There are many different workflows that need preinstalled tools for build, testing, or publishing stages.  This vary from project to project, some using python, ruby, cypress etc.  We need a way to keep these changes easy to track, and update.

Acceptance Criteria
- [ ] Figure out how docker images should be built/consumed, e.g. Can we use dockerfiles directly in the build job?
- [ ] Figure out the release management process, e.g. Jenkins job that can only be triggered by OpenSearch-Build maintainers?
- [ ] Documentation for how to onboard to docker release process
- [ ] Build tools/systems/processes for releasing a docker image.
- [ ] Write a guide for how to work with new workflows and docker images
- [ ] After reviewing this update the documentation for how this can be done

**Comment by zelinh** [comment]
[Triage] Moving this to product backlog. We have enough context for this one.

**Comment by zelinh** [comment]
We need to create a proper document before we move on to the implementation.

**Comment by peternied** [comment]
Refocused this item for CI docker images

**Comment by gaiksaya** [comment]
Closing this issue. Please see updated documentation for CI docker images https://github.com/opensearch-project/opensearch-build/tree/main/docker/ci#build-ci-runner-docker-image-from-dockerfile
