### ISSUE TITLE
Publish 'Docker official images' to DockerHub.

### ISSUE THREAD

**Issue by bbarani** [opensearch-project/opensearch-build#780]
### Is your feature request related to a problem? Please describe

The Docker images that are currently published on OpenSearch [DockerHub](https://hub.docker.com/u/opensearchproject) organization are not [Docker official images](https://docs.docker.com/docker-hub/official_images/).

### Describe the solution you'd like

Publish Docker official image(s) by following the [guidelines](https://github.com/docker-library/official-images#what-are-official-images) to Dockerhub

Initial Scope:
- OpenSearch
- OpenSearch-Dashboards

### Additional context

[Docker official image creation process](https://docs.docker.com/docker-hub/official_images/#creating-a-docker-official-image)

**Comment by peterzhuamazon** [comment]
We have matches a lot of the tenets here:
```
Focus on [Free](https://www.debian.org/social_contract#guidelines) and [Open-Source](https://opensource.org/) Software

    Support [multiple architectures](https://github.com/docker-library/official-images#architectures-other-than-amd64)

    Exemplify [Dockerfile best practices](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/)

    [Actively rebuild](https://github.com/docker-library/official-images#library-definition-files) for updates and security fixes

    Adhere to upstream recommendations

    Add minimal quality-of-life behavior for the container environment where fit
```

Tho we probably need to re-evaluate the dockerfiles we have according to best practices, that would take some time to complete:
https://docs.docker.com/develop/develop-images/dockerfile_best-practices/

I still have questions on what this supposed to mean:
```
    Adhere to upstream recommendations
```

**Comment by prudhvigodithi** [comment]
I found these links helpful
https://github.com/docker-library/official-images
https://github.com/docker-library/faq#an-images-source-changed-in-git-now-what

**Comment by dtaivpp** [comment]
@elfisher What can we do to get this moved forward? This is really important for people to have good visibility on which images the OpenSearch project is publishing.

**Comment by bbarani** [comment]
Some resources for creating official Docker image

https://docs.docker.com/develop/develop-images/dockerfile_best-practices/
https://github.com/docker-library/official-images/blob/master/README.md#contributing-to-the-standard-library
https://github.com/docker-library/official-images/blob/master/NEW-IMAGE-CHECKLIST.md

**Comment by rishabh6788** [comment]
created PR for opensearch and opensearch-dashboards for official image program
OS: https://github.com/docker-library/official-images/pull/13161
OSD: https://github.com/docker-library/official-images/pull/13194

**Comment by gaiksaya** [comment]
For now we have decided to go ahead with `Docker Verified Publisher` program
