### ISSUE TITLE
[Meta] Create a self serviceable standalone component release process 

### ISSUE THREAD

**Issue by bbarani** [opensearch-project/opensearch-build#781]
### Is your feature request related to a problem? Please describe

The current standalone component release process used to release standalone components like Data prepper, OpenSearch clients, SQL drivers etc... is not scalable and self serviceable by the component owners

### Describe the solution you'd like

Define the requirements, create a design and implement a repeatable, scalable and self serviceable standalone release process that requires very less manual intervention adhering to OpenSearch release standards.

- [ ] Finalize the requirements
- [ ] Create the design document
- [ ] Implementation

### Additional context

Add necessary guard rails to make sure that the self serviceable standalone release doesn't compromise the artifact quality.

**Comment by anirudha** [comment]
https://github.com/opensearch-project/opensearch-build/issues/794
https://github.com/opensearch-project/opensearch-build/issues/795
related older issues

**Comment by peternied** [comment]
Closing this this issue is in favor of #1234 that is being actively worked on with deliverables
