### ISSUE TITLE
add dashboards functional test repo into the build process

### ISSUE THREAD

**Issue by tianleh** [opensearch-project/opensearch-build#783]
### Is your feature request related to a problem? Please describe

Part of the effort to https://github.com/opensearch-project/opensearch-build/issues/604

### Describe the solution you'd like

This repo https://github.com/opensearch-project/opensearch-dashboards-functional-test is added to dashboards 1.1.0 yml

**Comment by bbarani** [comment]
@tianleh I am closing this issue as we have added the functional repo to build process already.
