### ISSUE TITLE
Support opensearch-py library on conda forge

### ISSUE THREAD

**Issue by jaidisido** [opensearch-project/opensearch-build#785]
### Is your feature request related to a problem? Please describe

The `opensearch-py` python library is only available on pypi. A number of users rely on the conda repository instead.

### Describe the solution you'd like

Publish `opensearch-py` to both pypi and conda. The process to releasing to conda is described [here](https://levelup.gitconnected.com/publishing-your-python-package-on-conda-and-conda-forge-309a405740cf).

### Additional context

As the maintainer of [AWS Data Wrangler](https://github.com/awslabs/aws-data-wrangler) we publish on both pypi and conda-forge. In our latest release we have added support for opensearch with `opensearch-py` being one of our dependencies. However, our release to conda is currently [blocked](https://github.com/conda-forge/awswrangler-feedstock/issues/89) because your library is not available on conda-forge.

**Comment by robert-schmidtke** [comment]
Hi @abhinavGupta16 @bbarani, did you have the time to assess whether you could publish on conda as well? A small update is much appreciated, thanks!

**Comment by bbarani** [comment]
@VijayanB Can you explore more on this request? We would like to document and automate the deployment of opensearch-py library to [conda](https://conda-forge.org/) along with PyPi

**Comment by BastianZim** [comment]
Hi everybody, just fyi, there is already a package maintained by a core member of conda-forge: https://github.com/conda-forge/opensearch-py-feedstock

**Comment by bbarani** [comment]
Closing this issue as there is already a package published by the community : https://github.com/conda-forge/opensearch-py-feedstock
