### ISSUE TITLE
Mechanism for identifying released build artifacts and numbers

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#787]
### Is your feature request related to a problem? Please describe

In order to produce a 1.1.1 patch build we need to locate artifacts from the 1.1.0 release, including the manifest, and maven artifacts.

- Where is the released 1.1.0 build output? Probably an URL on artifacts.opensearch.org?
- ...  

### Describe the solution you'd like

A mechanism/page/something that links to the complete signed and unsigned output of a well known release.

**Comment by bbarani** [comment]
Closing this issue as we are shipping the build manifest with the distribution (starting 1.2.0) that contains the exact location of the artifacts.
