### ISSUE TITLE
Preserve intermediate released build artifacts perminately

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#788]
Related to https://github.com/opensearch-project/opensearch-build/issues/787

There are two environments for build artifacts and the location of these artifacts have shifted as improvements have been made. In order to ensure we can patch previous releases we need to keep intermediate artifacts where they will be safe/consist as part of a post release process.

### Acceptance Criteria
- design a process for storing all artifacts and logs from a distribution build workflow
  * include the Jenkins job log
  * should capture everything in S3 associated with that build
  * needs to be accessible without S3
- create a job that give a job name, build num, s3 path, will copy everything
- update the release process to include this job
- run this job on all previous releases

**Comment by zelinh** [comment]
[Triage] @peternied Could you provide more details to this task?

**Comment by peternied** [comment]
Updated with much additional detail

**Comment by bbarani** [comment]
@opensearch-project/engineering-effectiveness Please provide an update.

**Comment by peterzhuamazon** [comment]
All the build artifacts are now in S3, but build log is directly associate with Jenkins.
We can use the build number to find the build log.

Thanks.

**Comment by bbarani** [comment]
Closing this issue based on @peterzhuamazon comment.
