### ISSUE TITLE
Weekly Community Engagement on 2021/10/25 - 2021/11/8

### ISSUE THREAD

**Issue by abhinavGupta16** [opensearch-project/opensearch-build#800]
Continuing the Issue #720

**Comment by peterzhuamazon** [comment]
https://github.com/opensearch-project/ansible-playbook/pull/10

**Comment by peterzhuamazon** [comment]
https://github.com/opensearch-project/helm-charts/issues/119

**Comment by peterzhuamazon** [comment]
https://github.com/opensearch-project/helm-charts/pull/116

**Comment by peterzhuamazon** [comment]
https://github.com/opensearch-project/helm-charts/pull/117

**Comment by peterzhuamazon** [comment]
https://github.com/opensearch-project/helm-charts/pull/118

**Comment by peterzhuamazon** [comment]
https://github.com/opensearch-project/opensearch-build/issues/873

**Comment by peterzhuamazon** [comment]
https://github.com/opensearch-project/helm-charts/pull/124

**Comment by peterzhuamazon** [comment]
https://github.com/opensearch-project/ansible-playbook/issues/11
https://github.com/opensearch-project/ansible-playbook/pull/12

**Comment by peterzhuamazon** [comment]
https://github.com/opensearch-project/helm-charts/pull/94
