### ISSUE TITLE
Multiple clusters support for CCR Plugin

### ISSUE THREAD

**Issue by gbbafna** [opensearch-project/opensearch-build#816]
### Is your feature request related to a problem? Please describe

For [CCR](https://github.com/opensearch-project/cross-cluster-replication) plugin testing , we need multiple test clusters . 

### Describe the solution you'd like

A way to spin multiple clusters on specified OS versions .  

### Additional context

We will need to connect these two clusters and then use it to replicate data b/w the two clusters.

**Comment by peterzhuamazon** [comment]
> Hi @gbbafna please correct this URL [here:](https://github.com/opensearch-project/opensearch-infra/blob/main/opensearch-cluster/cdk/multi-node/userdata/tar/main.sh#L36) with https://artifacts.opensearch.org/release-candidates/plugins/discovery-ec2/1.1.0/discovery-ec2-1.1.0.zip
> 
> Also please file a bug in the same repo. We will work on it. Thanks!

This needs to be rebuild for 1.2.0 as well when new release come.

**Comment by gaiksaya** [comment]
> > Hi @gbbafna please correct this URL [here:](https://github.com/opensearch-project/opensearch-infra/blob/main/opensearch-cluster/cdk/multi-node/userdata/tar/main.sh#L36) with https://artifacts.opensearch.org/release-candidates/plugins/discovery-ec2/1.1.0/discovery-ec2-1.1.0.zip
> > Also please file a bug in the same repo. We will work on it. Thanks!
> 
> This needs to be rebuild for 1.2.0 as well when new release come.

Yes thats why asked to file a bug. We can work on correcting it whoever picks that task up. CDK needs some refactoring
