### ISSUE TITLE
Docker image on Kubernetes: complaines about ES_TMP dir

### ISSUE THREAD

**Issue by ict-one-nl** [opensearch-project/opensearch-build#82]
I'm trying to build a Terraform module to deploy OpenSearch to k8s. The OpenDistro images are running fine, if I spin up the OpenSearch images locally (single node) it's fine as well. But when I try to run it on k8s it's not starting:

![image](https://user-images.githubusercontent.com/2643715/125058428-8aa40800-e0aa-11eb-98be-0060728bc3a3.png)

Can you give me some pointers as to where this error originates? I tried setting the ES_TMPDIR to the data directory and creating an /tmp but no sigar.

**Comment by peterzhuamazon** [comment]
Hi @ict-one-nl, can you try `OPENSEARCH_TMPDIR` since we have renamed all these vars.
https://github.com/opensearch-project/OpenSearch/search?q=OPENSEARCH_TMPDIR

**Comment by ict-one-nl** [comment]
Will try, thanks. The error does mention the ES_TMPDIR instead of the Opensearch one though :)

**Comment by ict-one-nl** [comment]
Found it....problem was using the old opendistro jvm.options file, which mentioned this var. My own fault, thanks though.
