### ISSUE TITLE
Monitor 1.2.0 bundle builds and make sure they are passing

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#822]
Monitor on our slack channel that is posting build status periodically, if there is a failed build take action from this checklist:

![image](https://user-images.githubusercontent.com/2754967/139122112-538a3646-d3a8-4133-a817-50eca04cd351.png)

- Look at the build logs and determine if this is a new failure
   - If known, please reply to the post as a thread, and link the existing github issue - All done!
- Create a new issue on the component repository, or the OpenSearch-build repository.
  - Add `[Bundle Build Break]` to the title of the issue, make sure the title reference the problem source
  - Include the a log snippet and be sure that the .
  - Create a public gist of the full build log and attach it to the issue
  - Add the `v1.2.0` tag onto the issue.
  - See example issue https://github.com/opensearch-project/k-NN/issues/150
- Reply to thread with the new issue in the build status channel
- Create a new post in the release slack channel

Please also follow up with any questions, comments, or pull requests.

**Comment by zelinh** [comment]
Bundle builds are working now.

**Comment by peternied** [comment]
This is meant to be an ongoing tasks, we need to be sure that the 1.2.0 builds are working until release.
