### ISSUE TITLE
request whitesource scanning tool to have permissions to run on pull requests

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#823]
Whitesource scanner needs permissions to run on pull requests.  Please make a request for these permissions to be added on our projects.
- [ ] Get permissions for all repositories in OpenSearch-Project
- [x] Or if blocked get permissions for a single repository OpenSearch

**Comment by zelinh** [comment]
AppSec team helps me confirm the request, still waiting for approval.

**Comment by zelinh** [comment]
We onboard the WhiteSource native Github app on `OpenSearch` repository first. The Github app has been installed and registered with our license key. I'm closing this issue and we will move on to the next step that is to scan the repo.
