### ISSUE TITLE
[Bundle Build Break] Make sure k-NN is building with updated docker images

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#824]
> From: https://github.com/opensearch-project/opensearch-build/pull/810
> dblock: I merged this. I believe we need to make a new CI runner with these changes and update it in the manifests, but I don't know what that takes

We need to make sure the build process is using the updates docker images:
#### Validate that k-NN can build
- [x] Locally build and startup the docker image, [dockerfile](https://github.com/opensearch-project/opensearch-build/blob/main/docker/ci/dockerfiles/ci-runner.centos7.dockerfile)
- [x] Copy the git clone/ build systems from the [bundle job](https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/opensearch/Jenkinsfile#L72) and execute them in the docker container
- [ ] If there are any errors create issues and track them down

#### Update the docker image on the CI system
- [x] Use [dockerfile](https://github.com/opensearch-project/opensearch-build/blob/main/docker/ci/dockerfiles/ci-runner.centos7.dockerfile) to build the image for publishing
- [x] Request permission to docker hub org
- [x] Publish updated image to docker hub 
- [x] Update the pointer to the current docker images [build manifest](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/1.2.0/opensearch-1.2.0.yml#L5)
- [x] Make sure that the imaging picking process will still work, [jenkinsfile](https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/opensearch/Jenkinsfile#L33)
- [x] Create PR(s) and merge everything
- [x] Verify that the build is passing in the build release slack channel

Note: Review [docker release](https://github.com/opensearch-project/opensearch-build/tree/main/docker/release) covers the process for release docker images which are likely simaliar to what we are doing with the CI images

**Comment by zelinh** [comment]
This issue has been solved and bundle build is now working successfully.
