### ISSUE TITLE
[Bug]: Windows build packages opensearch-tar-install.sh

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#828]
### Describe the bug

Windows build packages opensearch-tar-install.sh via [this script](https://github.com/opensearch-project/opensearch-build/blob/main/scripts/components/OpenSearch/install.sh#L75).

### Expected behavior

Port the [`opensearch-tar-install.sh`](https://github.com/opensearch-project/opensearch-build/blob/main/scripts/legacy/tar/linux/opensearch-tar-install.sh) script to `opensearch-zip-install.bat` and package it into the windows distribution instead. That .bat will need to call a new Windows version of the install security demo configuration script, which is https://github.com/opensearch-project/security/issues/1476.

**Comment by peterzhuamazon** [comment]
This is not needed for now as it is mainly for knn and pa configurations and those two are not really supported on Windows yet. Will keep this open until those plugins are available.


Thanks.

**Comment by bbarani** [comment]
I am closing this issue as we have released Windows artifact along with supporting version of K-NN plugin in 2.4.0 release. Feel free to re-open this issue if needed.

**Comment by peterzhuamazon** [comment]
Addtional info, we actually add that in here:
* https://github.com/opensearch-project/opensearch-build/blob/main/scripts/startup/zip/windows/opensearch-windows-install.bat
