### ISSUE TITLE
Enable opensearch-dashboards plugins build process for version 1.2

### ISSUE THREAD

**Issue by Tengda-He** [opensearch-project/opensearch-build#830]
### Is your feature request related to a problem? Please describe

Enable opensearch-dashboards plugins build process for version 1.2 release 

### Describe the solution you'd like

add all the opensearch-dashboards plugins components configuration to the opensearch-dashboards-1.2.0.yml file.

**Comment by dblock** [comment]
Note that this work is part of each team's 1.2 release issue linked to https://github.com/opensearch-project/opensearch-build/issues/567.

**Comment by kavilla** [comment]
All plugins merged in.
