### ISSUE TITLE
opensearch-cli 1.1 release

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/opensearch-build#833]
We are interested in releasing opensearch-cli 1.1.0 . It requires signing before release.

Candidates: Macos amd64/arm64
                      Linux  amd64/arm64
                      Windows x64

**Comment by VijayanB** [comment]
Artifacts need to be signed:

1. Linux
     arm64 : https://github.com/VijayanB/opensearch-cli-1/suites/4411044686/artifacts/116540298
     x64      : https://github.com/VijayanB/opensearch-cli-1/suites/4411044686/artifacts/116540299
      

2. Windows
      x64   : https://github.com/VijayanB/opensearch-cli-1/suites/4411044686/artifacts/116540302
      x86   : https://github.com/VijayanB/opensearch-cli-1/suites/4411044686/artifacts/116540303

3. Mac ( Please sign only the artifact inside zip ). Later, i will create another issue for notarizing pkg 
     x64   : https://github.com/VijayanB/opensearch-cli-1/suites/4411044686/artifacts/116540301
     arm64 : https://github.com/VijayanB/opensearch-cli-1/suites/4411044686/artifacts/116540300

**Comment by dblock** [comment]
Are we publishing something off a private fork?

**Comment by vamshin** [comment]
@dblock opensearch-cli is public https://github.com/opensearch-project/opensearch-cli

**Comment by VijayanB** [comment]
Uploaded the artifact here

[opensearch-cli-1.1.0-macos-arm64.zip](https://github.com/opensearch-project/opensearch-build/files/7573567/opensearch-cli-1.1.0-macos-arm64.zip)
[opensearch-cli-1.1.0-macos-x64.zip](https://github.com/opensearch-project/opensearch-build/files/7573568/opensearch-cli-1.1.0-macos-x64.zip)
[opensearch-cli-1.1.0-windows-x86.zip](https://github.com/opensearch-project/opensearch-build/files/7573569/opensearch-cli-1.1.0-windows-x86.zip)
[opensearch-cli-1.1.0-windows-x64.zip](https://github.com/opensearch-project/opensearch-build/files/7573570/opensearch-cli-1.1.0-windows-x64.zip)
[opensearch-cli-1.1.0-linux-x64.zip](https://github.com/opensearch-project/opensearch-build/files/7573572/opensearch-cli-1.1.0-linux-x64.zip)
[opensearch-cli-1.1.0-linux-arm64.zip](https://github.com/opensearch-project/opensearch-build/files/7573573/opensearch-cli-1.1.0-linux-arm64.zip)

**Comment by gaiksaya** [comment]
[Triage] We will look into it after 1.2.0 release. Estimated date to pick this task up: 30th November, 2021.
Thanks!
