### ISSUE TITLE
Add RPM Cluster Deployment in IntegTest framework for testing

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#849]
Add RPM Cluster Deployment in IntegTest framework for testing.

As of now the integTest framwork in test workflow only supports downloading tarball from S3 and run the cluster/tests.
We need a function to install RPM packages when it is ready to automate the install and test process.

Thanks.

**Comment by abhinavGupta16** [comment]
@peterzhuamazon  - Could you add an estimate and an assignee to this task. Thank you!

**Comment by bbarani** [comment]
Duplicate of https://github.com/opensearch-project/opensearch-build/issues/1951
