### ISSUE TITLE
Convert freestyle gradle check to Jenkinsfile and migrate to public jenkins

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#851]
### Is your feature request related to a problem? Please describe

Convert freestyle gradle check to Jenkinsfile.

### Describe the solution you'd like

https://github.com/opensearch-project/opensearch-build/issues/74#issuecomment-956496829

**Comment by peterzhuamazon** [comment]
Seems like builder does not support pipeline syntax as of yet.
https://github.com/jenkinsci/ghprb-plugin/issues/719

**Comment by peterzhuamazon** [comment]
This probably help:
https://stackoverflow.com/questions/36850485/how-to-trigger-a-jenkins-2-0-pipeline-job-from-a-github-pull-request/45121585#45121585

**Comment by dblock** [comment]
I labeled this 1.3.0 because OpenSearch `gradle check` needs to use the same JDK as defined in the .properties file in the branch. Part of #981.

**Comment by reta** [comment]
@peterzhuamazon I think it is possible to use Jenkinsfile with Github Pull Request builder [1]. At least, when pipeline is created, there is an option to configure Github Pull Request builder and Jenkins file from SCM (I believe it could be set to the base branch like 1.x / main or use the pull request one, have to double check that). Have you tried to configure pipeline with Github Pull Request builder already? If not, I could give you a hand here.

https://medium.com/openwhisk/how-to-make-jenkins-pipeline-jobs-triggered-by-pull-requests-for-apache-projects-2a526f0eb366

**Comment by peterzhuamazon** [comment]
> @peterzhuamazon I think it is possible to use Jenkinsfile with Github Pull Request builder [1]. At least, when pipeline is created, there is an option to configure Github Pull Request builder and Jenkins file from SCM (I believe it could be set to the base branch like 1.x / main or use the pull request one, have to double check that). Have you tried to configure pipeline with Github Pull Request builder already? If not, I could give you a hand here.
> 
> https://medium.com/openwhisk/how-to-make-jenkins-pipeline-jobs-triggered-by-pull-requests-for-apache-projects-2a526f0eb366

Thanks @reta I will take a look at this.
Currently a bit busy with new releases and RPM creation.

Thanks.

**Comment by peterzhuamazon** [comment]
Although ghprb plugin is usable in pipeline workflow, it cannot be saved in the Jenkinsfile itself for backup. However, since it is very easy to setup, this can be a way for later.

**Comment by reta** [comment]
That is correct, thank you for update.

**Comment by bbarani** [comment]
@peterzhuamazon @gaiksaya Is this issue still valid?

**Comment by peterzhuamazon** [comment]
We can wait until the public jenkins is live as ghprb settings would be different to use push instead of pull mode.

**Comment by peterzhuamazon** [comment]
Pre-requisite PR: 
* https://github.com/opensearch-project/opensearch-ci/pull/138

**Comment by peterzhuamazon** [comment]
20220623:
* Build Repo: https://github.com/opensearch-project/opensearch-build/pull/2249

**Comment by peterzhuamazon** [comment]
Some explanations to the questions I get:

1. Why do we set 130min for Github Actions timeout?
Because gradle check jenkinsfile have a 120min timeout, once jenkins abort the run we need extra time for github action to retrieve the information, output the status, cleanup runners, etc. Therefore, adding 10min extra to the github actions timeout to be 130min to be safe.

2. Why do you set 7200seconds timeout within the github actions shell call?
The jenkins workflow can have zombie process or stuck process during the run, therefore, we need a mechanism to actively curl Jenkins for run information as well as timeout in case Jenkins failed to do so. This 7200seconds value is matching jenkins 120min timeout value.

3. Why are we use agent node directly without using any containers?
Jenkins gradle check requires a lot of resources from the runner, having a container would definitely impact the performance of the runner. Moreover, gradle check would spawn containers with docker-compose during the run, and running container in container is messy to manage and make it run correctly. Therefore, we directly run the gradle check workflows in agent node.

**Comment by peterzhuamazon** [comment]
@reta Please be aware Gradle Check now does not need `start gradle check` or rebasing to restart. You can just re-run it as any other github actions.

![image](https://user-images.githubusercontent.com/65193828/176053419-4af8149e-53b9-4ea8-bd0a-ab5f598cbc81.png)


Thanks.

**Comment by peterzhuamazon** [comment]
New Bug per @mch2 as we still need jdk14 for gradle check.
```
* What went wrong:
Execution failed for task ':distribution:bwc:bugfix:buildBwcDarwinTar'.
> JAVA14_HOME required
```

**Comment by peterzhuamazon** [comment]
Andrew Improvement: https://github.com/opensearch-project/opensearch-build/pull/2913

**Comment by peterzhuamazon** [comment]
Reta add JDK19: 
* https://github.com/opensearch-project/opensearch-build/pull/2808
