### ISSUE TITLE
[Bug]: Automate maven publication to Sonatype staging for validation

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#855]
### Is your feature request related to a problem? Please describe

Our maven publication process in 1.1 ran into a number of issues.

https://github.com/opensearch-project/opensearch-build/issues/699 

Is it going to work for 1.2?

### Describe the solution you'd like

A reliable system that ensures that maven promotion will work.

**Comment by mch2** [comment]
Ideally we could run validation against the central sync requirements on every build before publishing.  I have not seen an off the shelf way to do this and rolling our own seems a bit cumbersome given all the pom validations.  Here are my thoughts - 

We can use the [Sonatype Nexus Staging Plugin](https://github.com/sonatype/nexus-maven-plugins/tree/master/staging/maven-plugin) with the `keepStagingRepositoryOnCloseRuleFailure` and `autoReleaseAfterClose` set to false (default behavior).  This *should* run the validation and fail if validation fails.  In this case I believe someone would need to login to the UI to view the failed rules - will validate this assumption.
We then link our sign and release job to run on every build.

**Comment by bbarani** [comment]
Closing this issue as we have improved the Maven publishing process post 1.1 release.  We will document the process in this #1459 and #1257.
