### ISSUE TITLE
on-board repository for code scans

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/opensearch-build#860]
### Is your feature request related to a problem? Please describe

Can you onboard this repository: https://github.com/opensearch-project/opensearch-ruby for code scans.

### Describe the solution you'd like

onboard to available scans

**Comment by zelinh** [comment]
We haven't used whitesource any ruby project. We may need some time for configuration.

**Comment by gaiksaya** [comment]
[Triage] @zelinh Can you update the status of it here? Thanks!

**Comment by zelinh** [comment]
Current configuration can't scan any library for Ruby project even though `ruby.resolveDependencies` is enabled in WhiteSource unified agent file. I'm investigating this issue.

**Comment by zelinh** [comment]
The scan is completed and updated the link on our WhiteSource scan track. Closing now.

**Comment by gaiksaya** [comment]
> The scan is completed and updated the link on our WhiteSource scan track. Closing now.

I think the request is to on-board for all future scans as well.
