### ISSUE TITLE
OpenSearch client v1.0.2 release NPM request

### ISSUE THREAD

**Issue by ananzh** [opensearch-project/opensearch-build#861]
Need NPM release for opensearch-js v1.0.2

### Describe the solution you'd like

Use previous release template for v1.0.2 release

**Comment by kavilla** [comment]
Any ETA on this @peterzhuamazon

**Comment by peterzhuamazon** [comment]
@peternied since you are oncall for the week can you follow up with @ananzh and @kavilla thanks.

**Comment by peternied** [comment]
FYI - we are working this request offline, but will use this to track overall work.

**Comment by gaiksaya** [comment]
v1.0.2 is released: https://www.npmjs.com/package/@opensearch-project/opensearch/v/1.0.2

closing this issue. Thanks!
