### ISSUE TITLE
Document and make GA release process repeatable and reproducible

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#87]
**Is your feature request related to a problem? Please describe.**

Anyone should be able to run an OpenSearch release via a documented and reproducible process (minus access to signing keys).

**Describe the solution you'd like**

A document that anyone could follow to produce an OpenSearch alpha/beta/GA release.

- [x] Complete #20 for each component
- [x] Complete #73 for the bundle
- [x] Document the process

**Additional context**

After a release [someone asked](https://twitter.com/missingututuo/status/1414875584472121347) where the 1.0.0 tags were. Our release process is not documented and expectations of when such things as tags are done are unclear.

**Comment by AMoo-Miki** [comment]
As a user, I would prefer to be able to run an OpenSearch release via a documented and reproducible process that uses **_free and open-source tools_**.

**Comment by dblock** [comment]
We've codified and are running the process in 1.2. Watch https://github.com/opensearch-project/opensearch-build/issues/567. Let's close this issue when 1.2 is released and we've finished all the steps, made updates to the templates and did a post-mortem.

**Comment by bbarani** [comment]
Closing this issue as we have documented the process in form of release templates and readme file. Feel free to re-open this issue if you need more information.
