### ISSUE TITLE
Support installing Opensearch on macOS using homebrew

### ISSUE THREAD

**Issue by vrozov** [opensearch-project/opensearch-build#88]

**Comment by peternied** [comment]
[Triage] Resolving this issue depends on the MacOS distribution, https://github.com/opensearch-project/opensearch-build/issues/38

**Comment by bbarani** [comment]
We are currently working on creating Linux based distributions (RPM and Deb) at this point in time. Please feel free to provide your inputs on this issue #741 to prioritize other non Linux distributions for us to pickup post that effort. As always, we welcome any contribution towards the development of additional distributions.

**Comment by bbarani** [comment]
Closing this redundant issue in favor of https://github.com/opensearch-project/opensearch-build/issues/1589

**Comment by dblock** [comment]
I didn't see this one, sorry, would have edited it. Thanks @bbarani
