### ISSUE TITLE
[Retrospective] Release 1.2.0 

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#880]
The OpenSearch and OpenSearch Dashboards Release 1.2.0 is currently in progress.  To make sure that we do not lose issues that arose during the process please add them here.  This issue will be updated after the release is finished.

### How to use this issue?
Please add comments to this issue, they can be small or large in scope.  Honest feedback is important to improve our processes, suggestions are also welcomed but not required.

### What will happen to this issue post release?
There will be a discussion(s) about how the release went and how the next release can be improved.  Then this ticket will be updated with the notes of that discussion along side action items.

**Comment by peternied** [comment]
Component tickets off of the 1.2.0 release issue don't have dates on them.  It makes it hard to know, if looking at a component what the critical dates are or not.  This was a design to prevent them from drifting away from the agreed central data source of the primary release ticket.

Possible solutions:
 1. Have an automated task than checks for updates on the primary release ticket and trickles down date updates to component tasks.
 2. See about getting an iframe/ or external loaded data source into the issue
 3. Super hacky idea - create an issue that represents a milestone and update its title with a date which is loaded dynamically

**Comment by ylwu-amzn** [comment]
Checkstyle removed from OpenSearch https://github.com/opensearch-project/OpenSearch/pull/1370, that caused AD plugin 1.2 build failed, took team hours to figure out why. We should notify all plugin teams about such changes in future.

**Comment by peternied** [comment]
Automate snapshot builds were being created and used by the distribution downloader tool and they were out of date https://github.com/opensearch-project/opensearch-build/issues/953.  A few issues this exposed:

* We did not know that part of the build infrastructure broke
* We did not realize that we were testing again old bits until really close inspection was conduced, decompiling binaries
* We needed to re-run a number of test cases and this involved a manual reach out to all components
* We updated the release date on the project board and that felt a little too easy / hard to manage

**Comment by peternied** [comment]
Seeing random test failures, might be associated with out of data code that was copypasted
https://github.com/opensearch-project/common-utils/issues/97

**Comment by peternied** [comment]
Random integration test failures seem to happen frequently, the starting point of a test failure investigation is 'is this a random failure' indication low trust in the test systems.

**Comment by dblock** [comment]
There was some confusion of what should and what should not be included in the manifest, see https://github.com/opensearch-project/opensearch-build/pull/974.

**Comment by dblock** [comment]
Let's add to the template "All issues labelled 1.2.0 are closed" with a link to https://github.com/issues?q=is%3Aopen+is%3Aissue+user%3Aopensearch-project++label%3Av1.2.0+

**Comment by kavilla** [comment]
For improvement, plugin version bumping and adding to manifest as soon as possible would be ideal. Logically once a `1.1` branch was created the `main` branch version should be bumped then we can start building releases as soon as possible for testing and validation. That way we can know way ahead of time of incompatibility with plugins earlier.

**Comment by peternied** [comment]
# Reflecting on OpenSearch Release 1.2.0, 1.2.1, 1.2.2, and 1.2.3.

There have been a massive number of contributors authoring code, reviewing pull requests, contribution to issues – thank you all.
## Larger areas of consideration
* We changed communication to leverage publicly visible GitHub issues such as #567.  This is part our ongoing to allow for contribution.  This large change created churn as for teams experiences these processes for the first time.
* Performance test results initially indicated a regression and after investigation were determined to be inconclusive.  This delayed the release and created uncertainty within the features added in 1.2 We need investment in these systems to build confidence in the results.
* The process for patch releases was created for 1.2.1 there were setbacks when it was discovered that already built components could not be reused.  This increased the amount of work needed to support the patch release from only two directly impacted teams to all components.
* Log4j CVE patch released were made available quickly and there were back-to-back releases, illustrating the need to keep a release ready posture for other critical changes.
* Automation of the build process has made headway with docker images available as builds are release but integration tests for the distribution, performance tests, artifact promotion have largely been done manually.

## Action Items
* https://github.com/opensearch-project/opensearch-build/pull/760 @peternied
* https://github.com/opensearch-project/opensearch-build/issues/1258 @peternied
* https://github.com/opensearch-project/opensearch-build/issues/126 @chenkle
* https://github.com/opensearch-project/opensearch-build/issues/818 @ohtyler
* https://github.com/opensearch-project/OpenSearch/issues/1707 @tlfeng
* https://github.com/opensearch-project/opensearch-build/issues/1375 @dblock
* https://github.com/opensearch-project/opensearch-build/issues/1361 @bbarani

With this we are closing out the retro items for 1.2.0-1.2.3 - its 2022 🎆 and I can not wait for the next set of releases!
