### ISSUE TITLE
[BUG] Owner userid of files in opensearchproject/opensearch:1.0.0 causes error with docker + userns

### ISSUE THREAD

**Issue by drowfx** [opensearch-project/opensearch-build#89]
**Describe the bug**

**To Reproduce**
1. `docker pull opensearchproject/opensearch:1.0.0`
2. When extracting layer f4eb0e854a62 the pull fails with `failed to register layer: Error processing tar file(exit status 1): Container ID 12011476 cannot be mapped to a host ID`

**Expected behavior**
The pulls succeeds, as it did for opensearchproject/opensearch:1.0.0-rc1

**Host/Environment (please complete the following information):**
 - OS: Debian 10
 - Version 1.0.0
 - Docker 20.10.7, Swarm mode

**Additional context**
Looking at the linux-x64 tarballs of 1.0.0 and 1.0.0-rc1 from https://opensearch.org/artifacts/ the problem seems to come from the user ids stored in the tarball: The tarball opensearch-1.0.0-rc1-linux-x64.tar.gz of 1.0.0-rc1 which works has the files in the tarball owned by uid 995/gid 993
```
$ tar --numeric-owner -vtf ~/Downloads/opensearch-1.0.0-rc1-linux-x64.tar.gz | head
drwxr-xr-x 995/993           0 2021-06-03 22:49 opensearch-1.0.0-rc1/
drwxr-xr-x 995/993           0 2021-05-28 20:19 opensearch-1.0.0-rc1/lib/
-rw-r--r-- 995/993    13058405 2021-05-28 20:19 opensearch-1.0.0-rc1/lib/opensearch-1.0.0-rc1.jar
-rw-r--r-- 995/993        6546 2021-05-28 20:19 opensearch-1.0.0-rc1/lib/opensearch-plugin-classloader-1.0.0-rc1.jar
```
while the tarball opensearch-1.0.0-linux-x64.tar.gz of 1.0.0 which does not work has the files in the tarball owned by uid 12011476/gid 100 (note the uid 12011476 which matches the 'Container ID' in the docker error message)
```
$ tar --numeric-owner -vtf ~/Downloads/opensearch-1.0.0-linux-x64.tar.gz | head
drwxr-xr-x 12011476/100      0 2021-07-09 00:32 opensearch-1.0.0/
-rwxr-xr-x 12011476/100   3132 2021-07-09 00:32 opensearch-1.0.0/opensearch-tar-install.sh
drwxr-xr-x 12011476/100      0 2021-07-09 00:32 opensearch-1.0.0/bin/
-rwxr-xr-x 12011476/100   4890 2021-07-03 01:22 opensearch-1.0.0/bin/opensearch-env
```
which is outside of the 0 to 65536 uid range normally allowed in a user namespace (due to the default size of the dockremap subuid allocation).

I think the Dockerfile should probably normalize the uid/gid of the extracted files when unpacking the tarball [here in line 53](https://github.com/opensearch-project/opensearch-build/blob/main/release/docker/dockerfiles/opensearch.al2.dockerfile#L53) so the uid/gid stored in the tarball does not leak into the container image. The `chmod -R` on line 81 is too late as at this point there is already a layer with the invalid uid after the copy on line 68.

**Comment by peterzhuamazon** [comment]
Interesting, I have yet to see this happen on my pull.
As for the chown we try to reduce the size of image in this PR using --chown related to COPY.
https://github.com/opensearch-project/opensearch-build/pull/93

Seems like it will still happen on your system.

I have tried to bring a debian and reproduce but couldnt.
I also tried on AL2, macOS and not happening.

This could probably be fixed with the tarball itself in the next release.

Let me try if adding a chown in the same layer as untar would increase the layer size.

Thanks.

**Comment by peterzhuamazon** [comment]
My test result:
```
admin:~$ docker pull opensearchproject/opensearch:1.0.0
1.0.0: Pulling from opensearchproject/opensearch
99a21848b482: Pull complete
f4eb0e854a62: Pull complete
4f4fb700ef54: Pull complete
ffd3f715ed97: Pull complete
d19997574184: Pull complete
6f1e5d14588b: Pull complete
3b0e6bcbd287: Pull complete
Digest: sha256:405edc708d0f019a3e1224c34029edb9633b79b496bf04e7da4fc3e8b003bcda
Status: Downloaded newer image for opensearchproject/opensearch:1.0.0
docker.io/opensearchproject/opensearch:1.0.0
admin:~$ cat /etc/*release
ID="ec2"
VERSION="20210329-591"
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
admin:~$ docker --version
Docker version 20.10.7, build f0df350
```

**Comment by drowfx** [comment]
Is your docker configured with user namespaces? The problem occurs for me with the line `"userns-remap": "dockremap"` in my `daemon.json`. From my  understanding, the issue is that the default dockremap configuration reserves 65536 uids for the user namespace. So the issue does not occur without uid remapping (as then the range of allowed uids is at least 0..2*31-1), or when the dockremap user is changed from the default configuration to provide a larger uid space (so that the uid 12011476 fits).

I think that the fix for #93 would also fix this issue, as then the high uids would not exist in any layer of the final image (they would continue to exist in the stage0 image, but that exists only on your build infrastructure).

**Comment by peterzhuamazon** [comment]
Hi @drowfx I did not configure user namespace yes, could you send the exact settings so I can reproduce?

I was initially thinking about moving the untar from dockerfile to build script, but since #93 would do the work will leave it here and monitor.

We have a multi-arch image coming up very soon #30 so I will leave this open and let you do some testings once the image is ready and pushed to staging.

Thanks.

**Comment by peterzhuamazon** [comment]
Ok create dockremap user/group, setup subuid/subgid, setup daemon.json, and reproduce the error exactly like this:
```
dmin@ip-172-31-23-237:~$ docker pull opensearchproject/opensearch:1.0.0
1.0.0: Pulling from opensearchproject/opensearch
99a21848b482: Pull complete
f4eb0e854a62: Extracting [==================================================>]  432.5MB/432.5MB
4f4fb700ef54: Download complete
ffd3f715ed97: Download complete
d19997574184: Download complete
6f1e5d14588b: Download complete
3b0e6bcbd287: Download complete
failed to register layer: Error processing tar file(exit status 1): Container ID 12011476 cannot be mapped to a host ID
```

**Comment by peterzhuamazon** [comment]
Hi @drowfx could you test these images.
I build them and pushed to staging with fixes in #93, and I dont see it in debian with docker namespace anymore.

Thanks.

```
admin:~$ docker pull opensearchstaging/opensearch:1.0.0-reducesize
1.0.0-reducesize: Pulling from opensearchstaging/opensearch
430235fb155c: Pull complete
ae1a4e1b0dc6: Pull complete
074ddc6c1225: Pull complete
2ab3ac8d793a: Pull complete
4f4fb700ef54: Pull complete
93c0ee6b7647: Pull complete
d5a1ca66bce0: Pull complete
0c4b88f0ce45: Pull complete
Digest: sha256:c3881df7ee61cbec2d24b4e9b1a33ff2c516e6f8ddfe59d02c3c12ab5c200357
Status: Downloaded newer image for opensearchstaging/opensearch:1.0.0-reducesize
docker.io/opensearchstaging/opensearch:1.0.0-reducesize


admin:~$ docker pull opensearchstaging/opensearch-dashboards:1.0.0-reducesize
1.0.0-reducesize: Pulling from opensearchstaging/opensearch-dashboards
430235fb155c: Already exists
5e0a7f057fdd: Pull complete
b77c387d52d2: Pull complete
b2c284280a1a: Pull complete
ec8d0d7cd295: Pull complete
249a7540b0f9: Pull complete
Digest: sha256:2748421326e0551fd8bda2456f1398bbcb4ea458a6e2a6ad5506c53cb99a5684
Status: Downloaded newer image for opensearchstaging/opensearch-dashboards:1.0.0-reducesize
docker.io/opensearchstaging/opensearch-dashboards:1.0.0-reducesize
```

**Comment by drowfx** [comment]
@peterzhuamazon
```
[host]$ docker pull opensearchstaging/opensearch:1.0.0-reducesize
1.0.0-reducesize: Pulling from opensearchstaging/opensearch
430235fb155c: Pull complete
ae1a4e1b0dc6: Pull complete
074ddc6c1225: Pull complete
2ab3ac8d793a: Pull complete
4f4fb700ef54: Pull complete
93c0ee6b7647: Pull complete
d5a1ca66bce0: Pull complete
0c4b88f0ce45: Pull complete
Digest: sha256:c3881df7ee61cbec2d24b4e9b1a33ff2c516e6f8ddfe59d02c3c12ab5c200357
Status: Downloaded newer image for opensearchstaging/opensearch:1.0.0-reducesize
docker.io/opensearchstaging/opensearch:1.0.0-reducesize
[host]$ docker run --rm -it opensearchstaging/opensearch:1.0.0-reducesize /bin/sh
sh-4.2$ ls -l /usr/share/opensearch
total 284
-rw-r--r--  1 opensearch opensearch  11358 Jul  2 23:22 LICENSE.txt
-rw-r--r--  1 opensearch opensearch 215360 Jul  2 23:22 NOTICE.txt
-rw-r--r--  1 opensearch opensearch   3780 Jul  2 23:22 README.md
drwxr-xr-x  1 opensearch opensearch   4096 Jul  8 22:32 bin
drwxr-xr-x  1 opensearch opensearch   4096 Jul 23 16:37 config
drwxr-xr-x  2 opensearch opensearch   4096 Jul  8 22:32 data
drwxr-xr-x  9 opensearch opensearch   4096 Jul  2 23:23 jdk
drwxr-xr-x  3 opensearch opensearch   4096 Jul  2 23:23 lib
drwxr-xr-x  2 opensearch opensearch   4096 Jul  2 23:22 logs
drwxr-xr-x 19 opensearch opensearch   4096 Jul  2 23:23 modules
-rwxr-xr-x  1 opensearch opensearch   4283 Jul 22 18:54 opensearch-docker-entrypoint.sh
-rwxr-xr-x  1 opensearch opensearch   1271 Jul 22 18:54 opensearch-onetime-setup.sh
-rwxr-xr-x  1 opensearch opensearch   3132 Jul  8 22:32 opensearch-tar-install.sh
drwxr-xr-x  6 opensearch opensearch   4096 Jul  8 22:32 performance-analyzer-rca
drwxr-xr-x  1 opensearch opensearch   4096 Jul  8 22:32 plugins
-rwxr-xr-x  1 opensearch opensearch    315 Jul 23 16:37 securityadmin_demo.sh
sh-4.2$ exit
[host]$ docker pull opensearchstaging/opensearch-dashboards:1.0.0-reducesize
1.0.0-reducesize: Pulling from opensearchstaging/opensearch-dashboards
430235fb155c: Already exists
5e0a7f057fdd: Pull complete
b77c387d52d2: Pull complete
b2c284280a1a: Pull complete
ec8d0d7cd295: Pull complete
249a7540b0f9: Pull complete
Digest: sha256:2748421326e0551fd8bda2456f1398bbcb4ea458a6e2a6ad5506c53cb99a5684
Status: Downloaded newer image for opensearchstaging/opensearch-dashboards:1.0.0-reducesize
docker.io/opensearchstaging/opensearch-dashboards:1.0.0-reducesize
```

Looking good now :+1:

**Comment by peterzhuamazon** [comment]
Thanks @drowfx we would likely to push this from staging to prod env either with the release of multi-arch images, or in next release of 1.1 version.
Do you want to keep this issue open until then.
Or you are good for us to close this now?

**Comment by drowfx** [comment]
It looks like the fix is merged to the main branch, so i'll say close it.

**Comment by peterzhuamazon** [comment]
Thanks for working with us on this.
