### ISSUE TITLE
[Bug]: performance-analyzer-rca is not present in the 1.1.0 release manifest 

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#894]
### Describe the bug

performance-analyzer-rca is not present in the 1.1.0 release manifest inside the Linux distribution for 1.1.0, but is present in the input manifest

### To reproduce

Download https://artifacts.opensearch.org/releases/bundle/opensearch/1.1.0/opensearch-1.1.0-linux-x64.tar.gz, extract manifest.yml. It doesn’t contain PA RCA.

**Comment by gaiksaya** [comment]
[Triage] bug needs to be fixed from build side.

**Comment by dblock** [comment]
It's not present in latest 1.2.0 build either, https://ci.opensearch.org/ci/dbc/bundle-build/1.2.0/1050/linux/x64/dist/manifest.yml. I probably am misunderstanding something, is it a .zip plugin or something that we add to performance-analyzer?

**Comment by dblock** [comment]
So this zip ships inside performance-analyzer.zip and shouldn’t have been in the top level manifest. Removed in https://github.com/opensearch-project/opensearch-build/pull/974
