### ISSUE TITLE
Create Docker images off of bundle build

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#908]
In order to make validating 1.2.0 easier, provide docker images that can be pulled for testing

- [ ] Add new docker references in the staging docker
- [ ] Update the build process to publish the image
  - [dockerfile](https://github.com/opensearch-project/opensearch-build/blob/main/docker/release/dockerfiles/opensearch.al2.dockerfile), https://hub.docker.com/r/opensearchstaging/opensearch
  - [dockerfile](https://github.com/opensearch-project/opensearch-build/blob/main/docker/release/dockerfiles/opensearch-dashboards.al2.dockerfile),  https://hub.docker.com/r/opensearchstaging/opensearch-dashboards

- [ ] Update the notification to include a notice about the docker image

This should allow anyone to create a security/no-security build for OpenSearch and OpenSearch Dashboards

**Comment by peterzhuamazon** [comment]
Just sync up with @zelinh and he will add a post task to bundle-build to trigger docker-build with these commands for now:

```
$ cd docker/release && curl -sSL $URL -o opensearch.tgz && bash build-image-multi-arch.sh -v 1.2.0 -f ./dockerfiles/opensearch.al2.dockerfile -p opensearch -a 'x64,arm64' -r opensearchstaging/opensearch -t ./opensearch.tgz
```

VERSION will be dynamically retrieved from bundle-build as well as the URL for tarball downloads.

Thanks.

**Comment by peterzhuamazon** [comment]
We are able to push the 1st draft to dockerhub with Jenkins.
@zelinh is still improving the code.
We will be able to create a PR soon.

```

$ curl https://localhost:9200 -u admin:admin --insecure
{
  "name" : "4ef213db75b5",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "gOYhllg8RTecEeAUizpdJw",
  "version" : {
    "distribution" : "opensearch",
    "number" : "1.2.0",
    "build_type" : "tar",
    "build_hash" : "d3101081aff62aa317c0b0334305f99f570a80ee",
    "build_date" : "2021-11-09T00:57:54.309054Z",
    "build_snapshot" : false,
    "lucene_version" : "8.10.1",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "The OpenSearch Project: https://opensearch.org/"
}
```

https://hub.docker.com/r/opensearchstaging/opensearch/tags?page=1&name=1.2.0

**Comment by peterzhuamazon** [comment]
See docker-build 88 for auto trigger from bundle-workflow.

**Comment by peternied** [comment]
@peterzhuamazon Thanks that worked great, do you how do we need to adapt the configuration for opensearch-dashboards via the bundle build?

**Comment by peterzhuamazon** [comment]
This is completed as we have both #928 and #929 taking care of docker builds of bundle builds in OpenSearch and OpenSearch-Dashboards.
