### ISSUE TITLE
run a scheduled scan on the `opensearch` repository

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#909]
We already have WhiteSource app installed on `OpenSearch` repo. It created a PR that contains a '.whitesource' configuration file which can be customized to our needs. Once it's merged to the repository, WhiteSource bot will run configured scan on the `OpenSearch` repo. 
https://github.com/opensearch-project/OpenSearch/pull/1525

**Comment by peternied** [comment]
[Triage] @zelinh Please fill in the details for this scan for this sprint

**Comment by zelinh** [comment]
Filled the description of this task.

**Comment by zelinh** [comment]
We are updating the `.whitesource` file to LOCAL mode and use our own configuration `whitesource.config` which is copied from https://github.com/opensearch-project/opensearch-build/blob/main/tools/vulnerability-scan/wss-unified-agent.config. 
See the update in this PR, https://github.com/opensearch-project/OpenSearch/pull/1540
