### ISSUE TITLE
Optimize Docker image: reduce half of the size

### ISSUE THREAD

**Issue by osddeitf** [opensearch-project/opensearch-build#92]
**Is your feature request related to a problem? Please describe.**
The Docker image `opensearchproject/opensearch` is heavy compare with `elasticsearch`.
`opensearch` v1.0.0 is 915mb in Docker Hub, while `elasticsearch` v7.13.3 is 473mb.

**Describe the solution you'd like**
Optimize Dockerfile build stages. There's a waste of space introduce by a layer which cause the size is duplicated:
![image](https://user-images.githubusercontent.com/37999210/125932916-d59bb7a6-6707-41b4-8815-aef54cb2422b.png)

Layer 10 have `chown` command, whilst we can chown it in layer 6 (Dockerfile `COPY` command has --chown flag).

**Comment by peterzhuamazon** [comment]
Thanks @osddeitf we will test this and let you know about the results.
This is a solution to another issue #56 
Thanks.

**Comment by peterzhuamazon** [comment]
The PR is merged to main branch now.
