### ISSUE TITLE
[Discussion] Remove Sysvinit support in OpenSearch DEB/RPM packages

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#922]
### Is your feature request related to a problem? Please describe

The DEB/RPM packages are using process manager to start/stop the process.

In ODFE, we support both Sysvinit (which is legacy now in majority of common linux distribution) and systemd.

Now as we are developing OpenSearch DEB/RPM, the support compatibility charts is updated to only support
```
Red Hat Enterprise Linux 7, 8; CentOS 7, 8; Amazon Linux 2; Ubuntu 16.04, 18.04, 20.04
```

It seems that we can fully deprecate the sysvinit support now, as none of the above LINUX distro and version has sysvinit anymore.
https://opensearch.org/docs/latest/opensearch/install/compatibility/

Please let me know your thoughts on this.

Thanks.

**Comment by peterzhuamazon** [comment]
Hi @bbarani  @dblock @peternied please let me know what is your thoughts.

Thanks.

**Comment by peternied** [comment]
Is there some more background that I can get on this topic - what is the trade-off of removing sysvinit support?  I don't see it referenced in this codebase.

**Comment by bbarani** [comment]
What is the systemd?
The systemd (system daemon) is a service and management mechanism. In RHEL7 or above, it is responsible for initializing and activating system resources and server daemons at the boot time as well as on a running system.

In easy language, the systemd starts and manages all types of processes and services in Linux. In technical language, it is an initializer program that brings the system up to a defined state by activating all services and processes those are enabled in that state. To know which services and processes are enabled in which state, it uses configuration files.

SysVinit v/s Upstart v/s Systemd
Systemd is the replacement of the SysVinit and Upstart initializer programs. In RHEL6, the Upstart initialization program was used. Before RHEL6, the SysVinit was the default initialization program.

Source: [Differences between SysVinit, Upstart and Systemd](https://www.computernetworkingnotes.com/linux-tutorials/differences-between-sysvinit-upstart-and-systemd.html)

**Comment by stockholmux** [comment]
`legacy now in majority of common linux distribution` Can you break this down a little more? Are there any hold outs?


Also what is the effort required or risk to keep SysvInit around for those who are using an older distrubtion?

**Comment by peterzhuamazon** [comment]
> `legacy now in majority of common linux distribution` Can you break this down a little more? Are there any hold outs?
> 
> Also what is the effort required or risk to keep SysvInit around for those who are using an older distrubtion?

CentOS/RH 6 and before, Ubuntu 14 before + Ubuntu 15 early versions are the notable ones that still use Sysvinit, and they only Ubuntu 14 are still in extended maintenance support. 

The compatibility charts we put in our website list linux system are all having systemd now.
 https://opensearch.org/docs/latest/opensearch/install/compatibility/

**Comment by stockholmux** [comment]
@peterzhuamazon And the latter part of that message - what about keeping SysvInit around?

**Comment by peterzhuamazon** [comment]
> @peterzhuamazon And the latter part of that message - what about keeping SysvInit around?

I will take a considerate amount of efforts to migrate those scripts from ODFE to OpenSearch, while port them to work with OpenSearch (the original scripts we have only works for Kibana).

And we also need to get old env to test them.

I personally think it is not worth the effort consider RH 6 has been deprecated from LTS since 2018, it is already being replace by RH 7 since mid 2017.

Thanks.

**Comment by peternied** [comment]
Do we have these scripts somewhere and an details as to why this they would be hard to manage?  This missing data that makes it hard to understand the trade-offs with continuing support or removing it.

**Comment by gaiksaya** [comment]
[Triage] @peterzhuamazon is working on design document solving this issue #956

**Comment by bbarani** [comment]
@peterzhuamazon Can we close this issue as we have finalized the RPM design?

**Comment by peterzhuamazon** [comment]
@bbarani we can close this as we now maintain the sysvinit script alongside systemd scripts.
