### ISSUE TITLE
[BuildBuild] Have excellent documentation for how to setup OpenSearch for testing

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#933]
For the 1.2.0 release this is what we have we should refine and improve this.

---

- Use Docker-Compose to setup a cluster
  + Download this [gist](https://gist.github.com/peternied/f693b9230ba68f9d7b9a26a8e6c097b8) as docker-compose.yml on your machine
  + Get latest image versions `docker-compose pull`
  + Start the cluster `docker-compose up`

- [OpenSearch docker](https://hub.docker.com/r/opensearchstaging/opensearch/tags?page=1&name=1.2.0) 
  + Start without security
     - Docker command `docker pull opensearchstaging/opensearch:1.2.0 && docker run -it -p 9200:9200 -e "discovery.type=single-node" -e "DISABLE_SECURITY_PLUGIN=true" opensearchstaging/opensearch:1.2.0`
    - Connect command `curl https://localhost:9200`
  + Start with security
    - Docker command `docker pull opensearchstaging/opensearch:1.2.0 && docker run -it -p 9200:9200 -e "discovery.type=single-node" opensearchstaging/opensearch:1.2.0`
    - Connect command `curl --insecure https://admin:admin@localhost:9200`

- [OpenSearch-Dashboards docker](https://hub.docker.com/r/opensearchstaging/opensearch-dashboards/tags?page=1&name=1.2.0)
  + Start without security
    - Docker command `docker pull opensearchstaging/opensearch-dashboards:1.2.0 && docker run -it --network="host" -e "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true" opensearchstaging/opensearch-dashboards:1.2.0`
    - URL `https://localhost:5601`
  + Start without security
    - Docker command `docker pull opensearchstaging/opensearch-dashboards:1.2.0 && docker run -it --network="host" opensearchstaging/opensearch-dashboards:1.2.0`
    - URL `https://localhost:5601`

- Use TARs to deploy OpenSearch Manually
  + OpenSearch - Build 964
    * arm64 [[manifest](https://ci.opensearch.org/ci/dbc/bundle-build/1.2.0/964/linux/arm64/dist/manifest.yml)] [[tar](https://ci.opensearch.org/ci/dbc/bundle-build/1.2.0/964/linux/arm64/dist/opensearch-1.2.0-linux-arm64.tar.gz)]
    * x64 [[manifest](https://ci.opensearch.org/ci/dbc/bundle-build/1.2.0/964/linux/x64/dist/manifest.yml)] [[tar](https://ci.opensearch.org/ci/dbc/bundle-build/1.2.0/964/linux/x64/dist/opensearch-1.2.0-linux-x64.tar.gz)]

  + OpenSearch Dashboards - Build 364
    * arm64 [[manifest](https://ci.opensearch.org/ci/dbc/bundle-build-dashboards/1.2.0/364/linux/arm64/dist/manifest.yml)] [[tar](https://ci.opensearch.org/ci/dbc/bundle-build-dashboards/1.2.0/364/linux/arm64/dist/opensearch-dashboards-1.2.0-linux-arm64.tar.gz)]
    * x64 [[manifest](https://ci.opensearch.org/ci/dbc/bundle-build-dashboards/1.2.0/364/linux/x64/dist/manifest.yml)] [[tar](https://ci.opensearch.org/ci/dbc/bundle-build-dashboards/1.2.0/364/linux/x64/dist/opensearch-dashboards-1.2.0-linux-x64.tar.gz)]

From [Docker Release](https://github.com/opensearch-project/opensearch-build/tree/main/docker/release)

**Comment by peternied** [comment]
@kavilla @peterzhuamazon Can you confirm that the setup for Dashboards is correct?

**Comment by peterzhuamazon** [comment]
`--network="host"` sometimes having issues on macOS.
I normally just use the docker file to handle it.

**Comment by bbarani** [comment]
Closing this issue as we are adding the test documentation in the release issue.
