### ISSUE TITLE
[Bug]: Reporting build missing chromium dependency

### ISSUE THREAD

**Issue by joshuali925** [opensearch-project/opensearch-build#934]
### Describe the bug

dashboards-reports plugin uses chromium to generate reports, the binary should be included in the artifact like this:
https://github.com/opensearch-project/dashboards-reports/blob/main/.github/workflows/dashboards-reports-test-and-build-workflow.yml#L67-L91

But this part is missing in [build.sh](https://github.com/opensearch-project/opensearch-build/blob/main/scripts/components/reportsDashboards/build.sh#L64-L77).

### To reproduce

Run opensearch and dashboards, reporting does not work because chromium binary `reportsDashboards/.chromium/headless_shell` does not exist

**Comment by peternied** [comment]
>What are the possible values of PLATFORM and ARCHITECTURE in build.sh?

`PLATFORM` can be: 
* linux
* darwin
* windows

`ARCHITECTURE` can be:
* x64
* arm64

See [example usage](https://github.com/opensearch-project/opensearch-build/blob/main/scripts/components/OpenSearch/build.sh#L81-L113)

**Comment by joshuali925** [comment]
will `ARCHITECTURE` be supplied? 
```bash
[ -z "$ARCHITECTURE" ] && ARCHITECTURE=`uname -m`
```
this can also be `x86_64`, `amd64`, `aarch64`, ... but the case only accepts `x64` and `arm64`

**Comment by peternied** [comment]
This a better source of truth, here are the values that will be allowed by the build system

```python
class BuildArgs:
    SUPPORTED_PLATFORMS = ["linux", "darwin", "windows"]
    SUPPORTED_ARCHITECTURES = [
        "x64",
        "arm64",
    ]
    ```
https://github.com/opensearch-project/opensearch-build/blob/main/src/build_workflow/build_args.py#L12-L17

**Comment by dblock** [comment]
> I see, thanks. What should I do if some combinations are not supported by reporting yet? We currently do not have chromium builds for darwin-arm64 and windows-arm64.

Manifests support limiting platforms like [here](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/1.2.0/opensearch-1.2.0.yml#L50). There's no support for architectures, we probably want to extend that code to be able to write:

```
platforms:
   - windows:x64
   - darwin:arm64
```

Feel free to open an issue/PR :)

> i think it's trying to do `PLATFORM=$(uname -s | awk '{print tolower($0)}')`

Please fix!
