### ISSUE TITLE
Remove redundant role for `tests`

### ISSUE THREAD

**Issue by owaiskazi19** [opensearch-project/opensearch-build#935]
### Is your feature request related to a problem? Please describe

Currently we have two tests role under https://github.com/opensearch-project/opensearch-build/blob/main/deployment/lib/identities.ts#L47-L48 to publish test results to S3. Remove the redundant `*/dist/*/tests/*` if not used anywhere.

### Describe the solution you'd like

Remove redundant role for `tests`

**Comment by gaiksaya** [comment]
[Triage] Need to clean up the permissions and redeploy the staging jenkins stack

**Comment by abhinavGupta16** [comment]
Once this is done, we would also need to refactor https://github.com/opensearch-project/opensearch-build/blob/main/vars/uploadTestResults.groovy to use the [`uploadTos3.groovy`](https://github.com/opensearch-project/opensearch-build/blob/c5b236ddcf4ffc305c557f7c00446c5854cfd6f1/vars/uploadToS3.groovy)

**Comment by bbarani** [comment]
@gaiksaya Is this still valid when we move to public jenkins? If not, can we close this issue?

**Comment by gaiksaya** [comment]
@rishabh6788 Did we move these as well? If yes then we need to fix the permissions else we are good

**Comment by gaiksaya** [comment]
Closing this issue as the role has been added to public jenkins. Please reopen if issue still exists.
Thanks!
