### ISSUE TITLE
[Enhancement] Make Docker Build on Jenkins more robust with with less manual inputs

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#952]
### Is your feature request related to a problem? Please describe

In #801 there are some additional improvements raised after the completion of the issues.

```
More improvements:

    Make the script commands section a fixed list or retrieve value from manifest.
    Add scm to monitor docker dir and auto trigger docker builds.

```

### Describe the solution you'd like

Make improvements for above asks in opensearch-build repo.

**Comment by gaiksaya** [comment]
[Triage] We are executing the commands using jenkins file today. closing this issue. Please re-open if required
