### ISSUE TITLE
[Documentation] Adding a design doc for deb/rpm generation with assemble workflow

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#956]
**Is your feature request related to a problem?**
[Documentation] Adding a design doc for deb/rpm generation with assemble workflow

**What solution would you like?**
@peterzhuamazon and @zylzulu will create the design doc, two parts, fpm pkg generation and assemble workflow wrapping.

**What alternatives have you considered?**

**Do you have any additional context?**

**Comment by peterzhuamazon** [comment]
We have created an initial design docs with reviews.
We will publish this design in a form of readme later.

Thanks.

**Comment by zelinh** [comment]
Closing this and we will update the design doc as part of README.

**Comment by peterzhuamazon** [comment]
We created an issue with the design and link in the readme: https://github.com/opensearch-project/opensearch-build/issues/1452
