### ISSUE TITLE
Notification after Integration Test run on Jenkins

### ISSUE THREAD

**Issue by owaiskazi19** [opensearch-project/opensearch-build#960]
### Is your feature request related to a problem? Please describe

Currently, `TestPublisher` is publishing test results to S3. To make the results more visible send a notification informing about the test run.

### Describe the solution you'd like

Notification can be send to either slack or through email.

**Comment by gaiksaya** [comment]
[Triage] @owaiskazi19 Are you working on this? If yes can you assign it to yourself and add the approach here?
Thanks!

**Comment by owaiskazi19** [comment]
> [Triage] @owaiskazi19 Are you working on this? If yes can you assign it to yourself and add the approach here? Thanks!

I have assigned it. I'll add the approach once we finalize it. Thanks.

**Comment by owaiskazi19** [comment]
Followed 2 designs for the issue:

1. [Discarded] Sending a single notification after every bundle is build and tested. Draft PR for the same: https://github.com/opensearch-project/opensearch-build/pull/972. Based on the discussion as all 3 tests Integ, Perf and BWC combined takes around 10 hrs to run. It'll delay the notification for a longer time.

2. Creating a separate channel for sending notification of tests as when they are run. https://github.com/opensearch-project/opensearch-build/pull/1105
