### ISSUE TITLE
[Integ-Test] We should have a test case that makes sure the JVM version between client/server are the same

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#964]
It looks like there can be cases where the JVM versions are mismatched between the remote cluster and the tests.  By adding a test that fails this would help us identify that the configuration is incorrect and we could get false negatives.

While this issue is less likely to happen in automated workflows, developers will still be running tests manually as they update/modify the suites.

From https://github.com/opensearch-project/index-management/issues/194

**Comment by peternied** [comment]
@saratvemulapalli this would be a great getting started issue if you had some one in mind

**Comment by bbarani** [comment]
@opensearch-project/engineering-effectiveness Is this issue still valid? Can we close this issue?

**Comment by peterzhuamazon** [comment]
> @opensearch-project/engineering-effectiveness Is this issue still valid? Can we close this issue?

The artifact always bundle the corresponding JDK version.
If user use an unsupported JDK on their host and bypass the bundled JDK, the cluster will have issue to start up.
Need more confirmation.

**Comment by saratvemulapalli** [comment]
@peternied its been a while since this was opened. 
Trying to understand the context (from past me), are you suggesting we test if client (test runners), server (test clusters) are on the same JVM version? What are the upsides?

**Comment by wbeckler** [comment]
Ensuring a consistent JVM version would prevent a certain kind of flaky tests when developers are running the test suite manually

**Comment by gaiksaya** [comment]
JVM versions are constant across the build and test systems as it is picked up from the single source which is the input manifest. Closing this issue for now as it does not seem valid anymore. Please feel free to re-open with more details if required.

Thanks!
