### ISSUE TITLE
[Retrospect] Release 1.1.1

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#984]
### Is your feature request related to a problem? Please describe

The OpenSearch and OpenSearch Dashboards Release 1.1.1 is currently in progress.  To make sure that we do not lose issues that arose during the process please add them here.  This issue will be updated after the release is finished.

### How to use this issue?
Please add comments to this issue, they can be small or large in scope.  Honest feedback is important to improve our processes, suggestions are also welcomed but not required.

### What will happen to this issue post release?
There will be a discussion(s) about how the release went and how the next release can be improved.  Then this ticket will be updated with the notes of that discussion along side action items.

**Comment by bbarani** [comment]
Closing this issue as we decided to **not** release 1.1.1 version of OpenSearch to prioritize the release of 1.2.x version of OpenSearch to fix critical log4j vulnerabilities.
