### ISSUE TITLE
Extract Groovy build library into its own project

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#985]
### Is your feature request related to a problem? Please describe

We've bolted Groovy code in this repo and load it in Jenkinsfile via `library( ... legacySCM())`. This creates issues with CPS, loading, doesn't allow `@grab`, executing arbitrary code, etc. 

See https://gitter.im/jenkinsci/jenkins?at=61956ac68b8103027214d6f2 for a discussion.

### Describe the solution you'd like

- Extract the Groovy build library into its own repo (everything in `src/jenkins` and `tests/jenkins`)
- Install with Jenkins via CDK
- Import via `@Library`, trusted

This will allow to write arbitrary code, fully extend Jenkins as we see fit by building DSLs, and is the recommended way of doing it.

https://www.jenkins.io/doc/book/pipeline/shared-libraries/

**Comment by gaiksaya** [comment]
I believe this is already implemented in out code base now under 
src: https://github.com/opensearch-project/opensearch-build/tree/main/src/jenkins
vars: https://github.com/opensearch-project/opensearch-build/tree/main/vars
